### ISSUE TITLE
Send Message & listen for response

### ISSUE THREAD

**Issue by freyguy** [slackapi/bolt-python#1000]
I'm attempting to spin up an ephemeral iteration of Bolt that will be torn down after the single use. I plan to deploy this via AWS API Gateway/Lambda so with a secondary system, this will be initiated to verify an action.

The app ideally is going to be initiated, send a block message to a user request response, accept the response and send a verification message acknowledging response was received and then tear down the socket. The app is not subscribed to any event listeners, it's sole purpose is to send these messages, listen for response, and acknowledge.

I've been successful in sending a message using the WebClient, but have not been successful in sending utilizing Bolt. 

```python
from slack_sdk.errors import SlackApiError
from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler
from slack_bolt.oauth.oauth_settings import OAuthSettings

app_token = xoxb...
signing_secret = <TOKEN>

# Socket Mode app initialization
app = App(
    token=app_token,
    signing_secret=signing_secret
)


user_id = <USERID>

initial_blocks = <BLOCKS>

def first_message(client, channel_id, initial_blocks, initial_message):
    channel_id = message["channel"]
    client.chat_scheduleMessage(
        channel=channel_id,
        text=initial_message,
        blocks = initial_blocks)


# Event listener for user submission of the initial modal
@app.action("confirm")
def user_confirm_response(ack, body, logger):
    ack()
    logger.info(body)
    try:
        respond("Your response has been recorded. Thank you for confirming.")
        exit()
    except:
        logger.info("Failed to send \"success\" response.")
        exit()

@app.action("deny")
def user_deny_response(ack, body, logger):
    ack()
    logger.info(body)
    try:
        respond(text = "Your response has been recorded. A member of our team may reach out after further investigation.")
        exit()
    except:
        logger.info("Failed to send \"deny\" response.")
        exit()

def main():
    SocketModeHandler(app, <TOKEN>).start()
    first_message(user_id, initial_blocks, initial_message)

# Start the Socket Mode app
if __name__ == "__main__":
    main()
```

**Comment by seratch** [comment]
Hi @freyguy, the cause of your issue should be related to the following part:

```python
def main():
    SocketModeHandler(app, <TOKEN>).start()
    first_message(user_id, initial_blocks, initial_message)
```

If you change the part like as below, the initial message will be sent as you expect:
```python
def main():
    first_message(user_id, initial_blocks, initial_message)
    SocketModeHandler(app, <TOKEN>).start()
```

The reason behind this is that `SocketModeHandler#start()` blocks the current thread to prevent the python process from terminating. Thus, your code needs to send the initial mesage before calling the method.

I hope this helps.

**Comment by freyguy** [comment]
Thanks @seratch, doing some testing in Lambda I'm beginning to wonder if this is possible as it seems like the SocketModeHandler won't result in the output of the `app.action` result from the user interacting with the block from Lambda, which we are utilizing to trigger secondary automation.

Or am I understanding this incorrectly?
