### ISSUE TITLE
views_update() resets entire home page on Android only

### ISSUE THREAD

**Issue by dbeilin** [slackapi/bolt-python#1001]
I wrote a simple Slack app that builds a UI using the Blocks. My entire app is based around the home page and consists of:
- 1x Radio Button
- x Drop down menus
- 1x Button

The single button I use has a `confirm` message that pops up. I wanted to customize that message whenever a user changes their selection for the radio button. This is handled in this function:

```python
@app.action("idle_minutes-action")
async def handle_idle_minutes_change(ack, body, client):
    '''
    This function is called when the user changes the "idle minutes" radio button
    '''
    try:
        await ack()
        user_id = body["user"]["id"]
        view_id = body["view"]["id"]
        action = body["actions"][0]
        minutes_selected = action["selected_option"]["value"]
        minutes_in_hours = int(minutes_selected) / 60
        username, _ = await get_slack_user_info(user_id, client)

        # Find and update the button block's confirmation message
        blocks = body["view"]["blocks"]
        for block in blocks:
            if block["type"] == "actions":
                for element in block["elements"]:
                    if (element["type"] == "button" and
                        element["action_id"] == "start_remote_dev-action"):
                        element["confirm"]["text"]["text"] = (
                            f"You are about to start a Remote Dev for "
                            f"{int(minutes_in_hours)} hours 🔫"
                        )
                        element["confirm"]["confirm"]["text"] = (
                            f"Yes, give me {int(minutes_in_hours)} hours"
                        )

        # Update the view after the confirmation message has been updated
        await client.views_update(
            user_id=user_id,
            view_id=view_id,
            view={"type": "home", "blocks": blocks}
        )

        log.info("User %s changed the idle minutes to: %s", username, minutes_selected)

    except SlackApiError as err:
        log.error("Error in handle_idle_minutes_change: %s", err)
```

As you can see, I'm looping over the blocks, searching for my button and updating the text inside of it. This has been working since I deployed this app to my team, but as of the latest [Android app update](https://slack.com/release-notes/android) it stopped working as expected.
By "stopped working as expected", I mean that the entire home page resets to the default values whenever I change a selection in the radio buttons. The log still says the selection was changed, the response for ` await client.views_update(` is `ok`, and the message is updated successfully.

I tested the same Slack app on an iPhone and this behavior doesn't happen. It also works as expected on our laptops (a mix of Macs and Ubuntu laptops).

The issue seems to be only with the Android version.

#### The `slack_bolt` version

```
slack-bolt==1.18.1
slack-sdk==3.26.0
```

#### Python runtime version

```
Python 3.12.0
```

#### OS info

```
ProductName:            macOS
ProductVersion:         14.1.2
BuildVersion:           23B92
Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000
```

### Notes
The Slack app is not part of the directory, it's local to our workspace (and runs in Socket Mode as well) so I don't know how you can reproduce it.

**Comment by hello-ashleyintech** [comment]
hello, @dbeilin! 👋 Thanks so much for submitting this and sorry to hear you're running into some trouble.

Rather than an SDK issue, this looks more like an Android-specific issue, as you mentioned. I will escalate this to the responsible team and leave an update as soon as I hear back! In the meantime, we'll leave this issue open as a server side issue and a bug.
