### ISSUE TITLE
Perform OAuth 2 flow on behalf of a user

### ISSUE THREAD

**Issue by auser1991** [slackapi/bolt-python#1002]
I have a slack bot written in Python using the SocketModeHandler. 

I am trying to create a integration that required a OAuth2 flow to retrieve token on behalf of the user to create a webex meeting. I am not sure how to do this with slack_bolt and wondering if I can get some guidance. Here is the documentation for the WebEx oauth flow: https://developer.webex.com/docs/authentication

### Reproducible in:

```bash
Python 3.10.12 
slack-bolt 1.18.0
slack-sdk  3.23.0
```

#### Code:
```python
import os
import logging
import requests
from flask import Flask, request, jsonify, make_response
from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler
# BUILD app
app = App(token=SLACK_BOT_TOKEN)
slack_client = app.client

SLACK_APP_TOKEN=""
SLACK_BOT_TOKEN = ""
REDIRECT_URI = "http://127.0.0.1:3000/auth"
CLIENT_ID = ""
CLIENT_SECRET = ""
AUTH_URL = 'https://webexapis.com/v1/authorize'
TOKEN_URL = 'https://webexapis.com/v1/access_token'
SCOPE = ['meeting:recordings_read', 'meeting:admin_preferences_write', 'meeting:admin_schedule_write', 'meeting:admin_preferences_read', 'meeting:schedules_read', 'meeting:participants_read', 'meeting:admin_participants_read', 'meeting:preferences_write', 'meeting:admin_recordings_read', 'meeting:recordings_write', 'meeting:preferences_read', 'meeting:transcripts_read', 'meeting:schedules_write', 'spark:kms', 'meeting:controls_write', 'meeting:admin_recordings_write', 'meeting:controls_read', 'meeting:participants_write', 'meeting:admin_schedule_read', 'meeting:admin_transcripts_read']


# test oauth
def trigger():
    headers = {
        'content-type':'application/json'
    }

    params={
        "response_Type": "code",
        "client_id": CLIENT_ID,
        "redirect_uri": REDIRECT_URI,
        "scope": SCOPE,
        "state": "1234abcd"

    }
    r = requests.get(
        AUTH_URL,
        params=params,
        headers=headers
    )
    r.raise_for_status()
    logger.info("TOKEN! =", r.json())

@app.command("/test-webex")
def handle_some_command(ack, body, logger):
    ack()
    logger.info("testing webex trigger")
    trigger()
    

flask_app = Flask(__name__)
with flask_app.app_context():
    SocketModeHandler(app, SLACK_APP_TOKEN).connect()


# Step 2: User authorization, this happens on the provider.
@flask_app.route("/auth", methods=["GET"])
def oauth():
    """ Begin OAuth2 authentication on bahalf of the user """
    try:
        logger.debug("got to here")
        code = request.args.get("code") 

        # begin oauth2 authentication
        headers = {
            'accept':'application/json',
            'content-type':'application/x-www-form-urlencoded'
        }
        payload = ("grant_type=authorization_code&client_id={0}&client_secret={1}&"
                        "code={2}&redirect_uri={3}")\
                    .format(CLIENT_ID, CLIENT_SECRET, code, REDIRECT_URI)
        r = requests.post(
            TOKEN_URL, 
            data=payload, 
            headers=headers
        )
        r.raise_for_status()
        return make_response(jsonify({
            "status": True,
            "response": r.json()
        }),
        200 )
    except:
        return make_response(jsonify({"status": False, "response": r.text }), 500)



if __name__ == "__main__":
    # This allows us to use a plain HTTP callback
    os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = "1"

    flask_app.secret_key = os.urandom(24)
    flask_app.run(host='0.0.0.0', port=3000, debug=True)

```

Not sure if this correct...

**Comment by WilliamBergamin** [comment]
Hi @auser1991 thanks for writing in 💯 implementing OAuth is not as trivial as it seems

I may need more information to help you out but the following may help

By default slack will use `slack/install` and `slack/oauth_redirect` to perform the OAuth flow, [this document](https://slack.dev/bolt-python/concepts#authenticating-oauth) explains more about this, in the above code it seems like you are implementing `/auth` for the OAuth flow

Here is [an example](https://github.com/slackapi/bolt-python/blob/main/examples/flask/oauth_app.py) that implements OAuth with the Flask adapter (this example does not use socket mode)

**Comment by auser1991** [comment]
@WilliamBergamin, thank you for your help,

So the following code does not work... I below is an example of a OAuth2 that I used and works:
```
redirect_uri = "http://127.0.0.1:3000/auth"
client_id = ""
client_secret = ""
authorization_base_url = 'https://webexapis.com/v1/authorize'
token_url = 'https://webexapis.com/v1/access_token'
scope = ["meeting:controls_read",
"meeting:transcripts_read",
"meeting:recordings_read",
"spark:kms",
"meeting:preferences_write",
"meeting:preferences_read",
"meeting:participants_write",
"meeting:recordings_write",
"meeting:controls_write",
"meeting:participants_read",
"meeting:schedules_read",
"meeting:schedules_write"]

@app.route("/")
def demo():
    oauth = OAuth2Session(
        client_id,
        scope=scope,
        redirect_uri=redirect_uri)
    
    authorization_url, state = oauth.authorization_url(
        authorization_base_url
        )

    session['oauth_state'] = state
    return redirect(authorization_url)


@app.route("/auth", methods=["GET"])
def callback():
    oauth = OAuth2Session(
        client_id,
        scope=scope,
        redirect_uri=redirect_uri,
        state=session['oauth_state'])
    
    token = oauth.fetch_token(
        token_url, 
        client_secret=client_secret,
        include_client_id=client_id,
        authorization_response=request.url
    )

    print("Token aquired!!", token)

    return make_response(jsonify({"status": True, "token": token}), 200)
```

I used this logic to perform as the OAuth authentication server for webex and it works. The /auth as my callback url. From what I understand, if I want to get the webex token for a user I have to send them to the https://webexapis.com/v1/authorize url to obtain their token to create a webex meeting on their behalf...

Is there a way to implement this in the slack bot? I am having a had time finding a way...

**Comment by auser1991** [comment]
I guess a better question is how do I redirect the user to the authentication flow I have above? Is this configured in the redirect_urls under Oauth and permissions within slack?

**Comment by WilliamBergamin** [comment]
Hi @auser1991 thanks for adding more information is I'm understanding this correctly you want to link Slack user accounts with Webex user accounts

There may be multiple ways to implement this but I would recommend something similar to how the [Google Calendar app](https://slack.com/help/articles/206329808-Google-Calendar-for-Slack) handles this. You will need to store the OAuth information of Slack and Webex in some sort of stateful environment like a database and link the data

- The SQLAlchemyInstallationStore could be leveraged in order to keep tract of individual Slack users and their OAuth tokens ([example](https://github.com/slackapi/bolt-python/blob/main/examples/sqlalchemy/oauth_app.py))
- A button could be placed in the applications [app home](https://api.slack.com/surfaces/app-home) that onclick [loads a the URL](https://api.slack.com/reference/block-kit/block-elements#button) in the user's browser that redirects them to theWebex authentication flow
- I believe it should be possible to use the redirect_uri and the event sent by the button click to link the 2 authorizations but I have not tested this out myself

Let me know if this help you on your journey

**Comment by auser1991** [comment]
Thanks @WilliamBergamin,

I figured that was the way to go with this, I'll give it a try go and let you know. You have been very helpful, I truly appreciate it!

**Comment by auser1991** [comment]
@WilliamBergamin, I was able to use a button for the redirect for the webex auth!

So the flow is as follows:
1. user invokes the modal with /test
2. modal appears with button to redirect user to webex OAuth 2 flow start
3. user signs in with SSO account, clicks authorize
4. Webex redirects to my OAuth webapp server at /callback
5. The server retrieves the users token, stores it, and redirects back to slack channel using https://slack.com/app_redirect?channel=XXXX
6. user is redirected back to slack

This flow works for what I am doing, however, is there a way to redirect the user from my OAuth server back to the modal view to perform the rest of the actions? Not sure if its possible... would be great! Please let me know your thoughts.

**Comment by WilliamBergamin** [comment]
This is awesome 🚀  
Great question, I don't think there is an easy way to do this, you could redirect the user to the applications channel using the `channel_id` the url would look like this `https://app.slack.com/client/<workspace_id>/<app_channel_id>` but you may need to hardcode these values somewhere
