### ISSUE TITLE
How to modify my Python Slack Bolt Socket mode code to reload automatically during any code changes?

### ISSUE THREAD

**Issue by vinod827** [slackapi/bolt-python#1004]
I have the following Python code which works fine using the Web Socket mode. When I type a slash command (`/hello-socket-mode`) on my Slash application then it very well invokes my method, `handle_some_command()`:-

```
import os
from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler

# Install the Slack app and get xoxb- token in advance
app = App(token="<bot token>")


# Add functionality here
@app.command("/hello-socket-mode")
def handle_some_command(ack, body, logger):
    ack()
    print('testing slash command')
    logger.info(body)


if __name__ == "__main__":
    # Create an app-level token with connections:write scope
    handler = SocketModeHandler(app,"<app token>")
    handler.start()
```

Since I'm in the development phase of my Slack app, I want to add reload functionality to this backend code of the web socket such that it reloads automatically whenever there is a change in the code. I tried to add `uvicorn` here but with that, I stopped getting invocation to my backend method, handle_some_command()whenever I tried to enter the slash command in the my slack application. I created a separate Python script called run.py with following code:-

```
from uvicorn import run


if __name__ == "__main__":
    run("main:app", host="0.0.0.0", port=3000, reload=True, log_level="info")
```

And then executed, python run.py to run my app using `uvicorn` to reload whenever there is a code change. It is not working at all, I'm not getting any slash command invocation to my backend code now. I just need some way of reload and not necessarily `uvicorn` here. I would appreciate it if someone could please guide me on this to make it work.

**Comment by seratch** [comment]
Hi @vinod827, thanks for asking the question. Unfortunately, there is no recommended way for it so far but one possible solution would be Jurigged. Refer to a gist I created in the past for details: https://gist.github.com/seratch/cad385de1ca07cb3c63bc5408ba66823

If anyone finds better solutions, sharing them here would be appreciated.

**Comment by vinod827** [comment]
> Hi @vinod827, thanks for asking the question. Unfortunately, there is no recommended way for it so far but one possible solution would be Jurigged. Refer to a gist I created in the past for details: https://gist.github.com/seratch/cad385de1ca07cb3c63bc5408ba66823
> 
> If anyone finds better solutions, sharing them here would be appreciated.

Hi, @seratch I'm able to perform a hot reload of code changes using your suggestions, [Jurigged](https://github.com/breuleux/jurigged), thank you, really appreciate it
