### ISSUE TITLE
How do I use strong message types?

### ISSUE THREAD

**Issue by KaloyanP** [slackapi/bolt-python#1023]
This is more of a query, rather than a bug:

I can't find a type-based way to construct requests I send to Slack or to route messages I receive from Slack. 

I want to have stronger typing of messages I receive from and send to Slack so that I can benefit from:
- static analysis of my code,
- prevent silly naming errors
- test the requests my app would send to Slack in CI
- write bots faster
- make Copilot and IntelliSense suggestions smarter
- tab-autocomplete my way to success (maybe not quite that one)

Simplistically, I imagine this would look something like this:

```python
class Section(BaseBlock):
    _type: str = 'section'
    text: TextObject
    accessory: ElementObject
    block_id: str

section1=Section()
section2=Section()

def send_hello(client: WebClient)
    client.chat_PostMessage(
        channel='C123456',
        blocks=[section1, section2]
    )
```

Is there a package I can use to enforce this typing? 

#### The `slack_bolt` version

Any

#### Python runtime version

Any

#### OS info

Any

## Requirements

See preamble

**Comment by seratch** [comment]
Hi @KaloyanP, thanks for asking this!

bolt-python's underlying slack-sdk package offers class-based Block Kit construction approach like you mentioned. Check the module's api docs and unit tests should be the quickest way to learn how to use it:
* https://slack.dev/python-slack-sdk/api-docs/slack_sdk/models/blocks/index.html
* https://github.com/slackapi/python-slack-sdk/tree/main/tests/slack_sdk/models

I hope this helps.
