### ISSUE TITLE
slack bot suddenly got inactive on my slack account

### ISSUE THREAD

**Issue by suavelad** [slackapi/bolt-python#1029]
I noticed this evening when testing my app that I was getting this error:

{'error':'account_inactive'}

When I checked, I noticed my slack bot was no longer showing up as an installed app on my slack workspace.

I later went to the slack api dashboard and triggered a reinstall, then retested.

This time , I was getting another error:

{'error': 'invalide_auth'}

When I checked again, I noticed my slack bot token had changed also .

Please what could be the cause ?

I cannot afford to have this same occurrence in production. 
This is the first time after  over 6 months.

Regards,

**Comment by suavelad** [comment]
Hi @hello-ashleyintech   In other to investigate, I would like to ask if a member of the workspace can uninstall a bot.

What are the ways bot can be uninstalled ?
Regards

**Comment by seratch** [comment]
>What are the ways bot can be uninstalled ?

Users in your workspace can visit the app configuration from "Configuration" button on the "About" tab of your app, and they can uninstall the app by clicking the "Remove App" button there.

**Comment by suavelad** [comment]
Hi @seratch ,

I noticed when a user remove app, it is removes it from the workspace?

How can we prevent this ?



Secondly,

I created a slack bot  which is linked to workspace A ( the origin from which the bot was created ) with SLACK_TOKEN_A

I installed the bot into workspace B . When sending a message to a user in workspace B using:

client = WebClient(token=SLACK_TOKEN)
client.chat_postMessage(
                            channel=approver_slack_user,
                            # thread_ts=message_ts,
                            text=f"Hey <@{approver_slack_user}> :wave:",
                            blocks=blocks,
                        )
for the token, I used SLACK_TOKEN_A (which is the originator of the bot) and I got channel_not_found message.

Am I suppose to use the SLACK_TOKEN for the user workspace I want to talk to

**Comment by seratch** [comment]
>How can we prevent this ?

When a user can install apps into workspace, there is no way to prevent the removal. To detect the event, your app can subscribe this event: https://api.slack.com/events/app_uninstalled

As for the second question, when your app can be installed into multiple workspaces, your app is responsible to manage tokens per workspace. The token for workspace A does not have permissions to access any data within workspace B. To enable the proper token management, your app needs to serve the OAuth flow to store the installation data including the tokens in a database. Refer to the following resources for details:
* https://slack.dev/bolt-python/concepts#authenticating-oauth
* https://github.com/slackapi/bolt-python/blob/main/examples/oauth_app.py

**Comment by suavelad** [comment]
@seratch Thanks for the response

On the unistalling/removal of a slack app.

Does this mean that if I install my slack bot into a workspace called workspace A  which has users in it, if any of the users deletes the bot app, from the workspace, it removes it totally for the workspace ?

**Comment by seratch** [comment]
When a user has the permission to remove an app from their workspace, yes. Your app can be removed by the interactions on the app configuration page.

**Comment by suavelad** [comment]
@seratch  I guess this happened because the bot app is owned my the workspace (workspace A)  and the user was a member of it.

a user from workspace B where our bot is installed on will/should not be able to see the delete button ?

**Comment by seratch** [comment]
A user in the workspace B can remove your app from workspace B. Thus, the remove button can be available for their own workspace. The removal is an operation for each workspace.

**Comment by suavelad** [comment]
@seratch  Apologies that my questions are much.

Are you saying that if all my workspace , we installed polly bot app, and I use the X - button at the side (in the app listing module), it will remove the polly bot app from my workspace and not other member of my workspace will be able to use it?


<img width="317" alt="image" src="https://github.com/slackapi/bolt-python/assets/20010335/22437e22-1a4a-4982-8a9f-0dc426ae6e85">

**Comment by seratch** [comment]
No, clicking the "x" on the UI means just hiding the DM from the side bar at the moment. As I mentioned above, removing an app can be done on my the app configuration page, where a user has to visit the app's "About" tab, click the "Configuration"  button, scroll down on the app configuration page to its buttom, and then click "Remove App" button. This is a quite intentional operation so that no one won't do that unintentionally.

**Comment by seratch** [comment]
This depends on how the workspace is configured in terms of user permissions by admins. Since this is a general question about Slack, not specific to this Python SDK, would you mind contacting our customer support team? You can send a question by /feedback command within your Slack workspace. It'd be appreciated if you could understand this.

**Comment by seratch** [comment]
Since this issue has been inactive for a few weeks, let me close this now.
