### ISSUE TITLE
Customize user-facing message sent when an installation is not managed by bolt-python app

### ISSUE THREAD

**Issue by escc86** [slackapi/bolt-python#1074]
Hello I have a question regarding a message that user receives when has not installed the app or completed the oAuth flow.

When a user click a button or execute an slack command receives the following message

`We apologize, but for some unknown reason, your installation with this app is no longer available. Please reinstall this app into your workspace`

My question: is there a way to do not send this message to the user or send a custom message instead?

**Comment by seratch** [comment]
Hi @escc86, thanks for writing in. At this moment, there is no way to customize the message, but I agree this could be a valid feature request. I may enhance the built-in middleware in future releases: https://github.com/slackapi/bolt-python/blob/v1.18.1/slack_bolt/middleware/authorization/multi_teams_authorization.py#L90-L100
