### ISSUE TITLE
[Question] Is there a way to specify the default tab for an app

### ISSUE THREAD

**Issue by budbach** [slackapi/bolt-python#1079]
Under "Apps" on the left hand side of the GUI, when selecting the app, it seems to default to opening the home page.  For an app I am working on, I'd prefer the app to open to the messages tab as that is where most of the apps functionality is.  Ideally, there would be a way to set the default tab fo the app.

#### The `slack_bolt` version

slack-bolt==1.18.1
slack_sdk==3.27.1

#### Python runtime version

Python 3.9.16

#### Steps to reproduce:

1.  In the GUI, click an app name with a home tab and messages tab under Apps 
2. The app opens to the "Home" tab

## Requirements

The app opens to the "Messages" tab

**Comment by vegeris** [comment]
Hi there, 

The App view does indeed default to opening the Home tab by default, or the Messages tab if a user has unread messages from the app. I don't believe we support customizing which tab opens by default, but one can disable the App Home tab if it's not relevant to their app via the [App Config](https://api.slack.com/apps) UI (`Features` -> `App Home` -> `Show Tabs`), or [deep-link](https://api.slack.com/reference/deep-linking#open_app_home) to a particular tab.

**Comment by eddyg** [comment]
I also think this would be a _great_ idea. I suggested exactly this as a Feature Request in the [#feedback](https://community.slack.com/archives/CQATA0B6J/p1665147745231609) channel [a couple years ago](https://community.slack.com/archives/CQATA0B6J/p1665147745231609), but nothing ever came of it. 😐

**Comment by budbach** [comment]
Yeah, for this app the user mostly goes to the messages tab to interact conversationally with an AI backed chatbot.  The home tab also has some features that are important but not the focus.  Nearly everytime they open the app, they need to switch from the Home tab to the messages tab and it isn't a very good experience.

**Comment by Andrej-Marsic** [comment]
Has this been addressed by any chance? Is the only option really to disable the home page?
