### ISSUE TITLE
How to send data for external_select where it takes more time to fetch the data?

### ISSUE THREAD

**Issue by tikluganguly** [slackapi/bolt-python#1083]
Hi All,

I have a function like the following

`def sent_list_options(ack:Ack,options:Optional[Dict[str, Any]],logger:log.Logger):`
                 `query=options.get('value')`
                 `ack(mod.get_search_option_by_query(query))`

I could see the function executing properly and getting the option list. But it takes close to 3-4 seconds to get the options. and by that time, I see an option not found in the external_select. Generally, this issue can be handled if we call an ack at the beginning of the function. But here I cannot use ack as using that will always give me a blank option list. Please suggest what can I do to display options where the options take more time to generate

Thanks
Tiklu

**Comment by zimeg** [comment]
Hey @tikluganguly! 👋 From what I can tell, [the acknowledgement response with options has to happen within 3 seconds](https://api.slack.com/interactivity/handling#acknowledgment_response) and only the first acknowledgment can provide updated options. This might cause the "option not found" message you're finding with `external_select` and I'm not sure of a workaround to avoid this right away...

This might not be the best suggestion, but is it possible to speed up the response that returns options? I understand a lot of querying might happen behind the scenes, but if any of that work can be offloaded it could be useful 🤔

I also experimented with a quick example of sending a double acknowledgment with options, but without much luck: https://github.com/zimeg/slacks/tree/cli.boltpy.modal

**Comment by tikluganguly** [comment]
Actually it is not possible to speed up the response as of now. That is why I was hoping if there is an option to send a ack and then if there is any other option to send the response.

**Comment by tikluganguly** [comment]
I liked the sample that you shared. Let me try it and I will get back to you with the response
