### ISSUE TITLE
How does `bolt-python` rotate tokens?

### ISSUE THREAD

**Issue by kennym** [slackapi/bolt-python#1084]
We enabled Token Rotation for our Slack app, however I was unsure of:

1. How does slack-bolt rotate our bot token exactly? Does it schedule a task to update the `bot_token` before the `bot_token_expires_at` time, or do we have to make sure we schedule that?
2. Today I tested the token rotation, and it did not seem to update the `bot_token` using the [example Django approach](https://github.com/slackapi/bolt-python/tree/main/examples/django).

<img width="1271" alt="image" src="https://github.com/slackapi/bolt-python/assets/160117/626a6d3a-ac2d-487f-bf75-15f028fddbd6">

![image](https://github.com/slackapi/bolt-python/assets/160117/8d3fcae2-09e7-4ce0-bbbd-040cae2b3441)

### Reproducible in:

```bash
django-slack==5.19.0
slack-bolt==1.18.1
slack-sdk==3.26.1
Python 3.11.6
ProductName:            macOS
ProductVersion:         14.4.1
BuildVersion:           23E224
Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000
```

**Comment by zimeg** [comment]
Hey @kennym! 👋 Thanks for exploring token rotation and writing in!

> How does slack-bolt rotate our bot token exactly? Does it schedule a task to update the `bot_token` before the `bot_token_expires_at` time, or do we have to make sure we schedule that?

A check to [rotate tokens happens with each request](https://github.com/slackapi/bolt-python/blob/dbe2333046b582c087fd19d6812c8a523835f53c/slack_bolt/authorization/authorize.py#L299-L310) and [rotations are done when needed](https://github.com/slackapi/python-slack-sdk/blob/70cf7baa2238b391accd66f1a32b51418a32c072/slack_sdk/oauth/token_rotation/rotator.py#L19-L56). This should all happen behind the scenes [if you're using the built-in OAuth functionality too](https://slack.dev/bolt-python/concepts#token-rotation) 🤔

> Today I tested the token rotation, and it did not seem to update the `bot_token` using the [example Django approach](https://github.com/slackapi/bolt-python/tree/main/examples/django).

Ah darn... I'm not immediately sure why this might be. Do you happen to be using the `oauth_app/slack_listeners.py` version of the app? Perhaps the suggested `token_rotation_expiration_minutes=1000000` is preventing token rotation from happening after 12 hours.

[From the docs](https://api.slack.com/authentication/rotation#exchange):

> Notice that your `access_token` now ... will always expire in 43,200 seconds, which is 12 hours.

Reducing this time to `<=720` might be a fix and can be helpful for testing. I hope this is helpful, but I'm interested if this is the case for your setup or if it might be something else. Please let me know!

**Comment by kennym** [comment]
Thank you, your answer is very appreciated.

> A check to [rotate tokens happens with each request](https://github.com/slackapi/bolt-python/blob/dbe2333046b582c087fd19d6812c8a523835f53c/slack_bolt/authorization/authorize.py#L299-L310) and [rotations are done when needed](https://github.com/slackapi/python-slack-sdk/blob/70cf7baa2238b391accd66f1a32b51418a32c072/slack_sdk/oauth/token_rotation/rotator.py#L19-L56). This should all happen behind the scenes [if you're using the built-in OAuth functionality too](https://slack.dev/bolt-python/concepts#token-rotation) 🤔

Thanks for all the references. This makes a lot more sense now.

I will test again.

> Reducing this time to <=720 might be a fix and can be helpful for testing. I hope this is helpful, but I'm interested if this is the case for your setup or if it might be something else. Please let me know!

How low can we go here?

**Comment by seratch** [comment]
The bot_token_expires_at time is not customizable as Slack server-side decides the value and includes it in the API response.

While I understand the option name "token_rotation_expiration_minutes" is a bit confusing, you can set token_rotation_expiration_minutes=1000000 to let bolt-python do rotation every time you receive a request from Slack.  (see also: https://github.com/slackapi/bolt-python/issues/510#issuecomment-958693339) If you don't customize the value, bolt-python does rotation either when the token is expiring within 120 minutes or when the token is already expired when it receives a request from Slack.

**Comment by kennym** [comment]
> or when the token is already expired when it receives a request from Slack.
So, the Token Rotation will still work with the refresh token even after the `bot_token` has expired?

Which would effectively mean that as long as we have `SlackInstallation` and `SlackBot` records we should not run into errors with expired tokens, correct?

**Comment by kennym** [comment]
> While I understand the option name "token_rotation_expiration_minutes" is a bit confusing, you can set token_rotation_expiration_minutes=1000000 to let bolt-python do rotation every time you receive a request from Slack. (see also: https://github.com/slackapi/bolt-python/issues/510#issuecomment-958693339) If you don't customize the value, bolt-python does rotation either when the token is expiring within 120 minutes or when the token is already expired when it receives a request from Slack.

For testing I've set `token_rotation_expiration_minutes=1000000`, but I'm not seeing our token being refreshed.

For context, we're using the Slack Events API (webhooks).

We handle a request from the Events API, route it through our system, where we eventually send a message back to the user, like so:

```
  OAUTH_SETTINGS = OAuthSettings(
      success_url=success_url,
      install_page_rendering_enabled=False,
      install_path="/api/oauth/slack/install/",
      redirect_uri_path="/api/oauth/slack/oauth_redirect/",
      client_id=client_id,
      client_secret=client_secret,
      scopes=scopes,
      user_scopes=user_scopes,
      # token_rotation_expiration_minutes=FIVE_DAYS_IN_MINUTES,
      token_rotation_expiration_minutes=1000000,
      installation_store=DjangoInstallationStore(
          client_id=client_id,
          logger=log,
      ),
      state_store=DjangoOAuthStateStore(
          expiration_seconds=120,
          logger=log,
      ),
  )

    slack_app = SlackApp(
        token=bot_token,
        signing_secret=settings.SLACK_SIGNING_SECRET,
        oauth_settings=OAUTH_SETTINGS,
    )
    
    slack_app.client.chat_postMessage(...)
```

However this doesn't seem to trigger the token refresh - what are we doing wrong?

**Comment by seratch** [comment]
The automatic rotation can be triggered only when your app's listeners (e.g., app.event, app.action) are executed. If you need to use WebClient outside of such functions, you can manually run the same rotation logic before utilizing the stored tokens. Please refer to the following internal code in bolt-python to learn how to implement this:
- https://github.com/slackapi/bolt-python/blob/v1.18.1/slack_bolt/authorization/authorize.py#L233-L272
- https://github.com/slackapi/bolt-python/blob/v1.18.1/slack_bolt/authorization/authorize.py#L369-L375
