### ISSUE TITLE
Connecting an installation to the authed user of my app

### ISSUE THREAD

**Issue by ravi-ojha** [slackapi/bolt-python#1086]
### What's my goal?

I'm creating a distributable slackbot app for my django project. I have followed the oauth flow from the example project and it works well.

### Where am I stuck?

After the installation, I'd like to "link" the installation with the User model of my app. This will help me identify the slack installation for any user. Here's the quick view of App init.

```python
def success(args: SuccessArgs) -> BoltResponse:
    # TODO: connect the slack's team_id with the auth'ed `User` model of my app, somewhat like this
    # But I can't figure out a way to get the authed user

    # user = get_auth_user()
    # user.slack_team_id = args.installation.team_id
    # user.save()

    return BoltResponse(
        status=200,
        body="Yay! It works.",
    )


def failure(args: FailureArgs) -> BoltResponse:
    return BoltResponse(status=args.suggested_status_code, body=args.reason)


slack_app = App(
    signing_secret=settings.SLACK_SIGNING_SECRET,
    oauth_settings=OAuthSettings(
        client_id=settings.SLACK_CLIENT_ID,
        client_secret=settings.SLACK_CLIENT_SECRET,
        scopes=[
            "app_mentions:read",
            "channels:history",
            "channels:read",
            "chat:write",
            "users:read",
        ],
        # If you want to test token rotation, enabling the following line will make it easy
        # token_rotation_expiration_minutes=1000000,
        installation_store=DjangoInstallationStore(
            client_id=settings.SLACK_CLIENT_ID,
        ),
        state_store=DjangoOAuthStateStore(
            expiration_seconds=120,
        ),
        install_page_rendering_enabled=False,
        install_path="/slack/install/",
        redirect_uri_path="/slack/oauth-redirect/",
        callback_options=CallbackOptions(success=success, failure=failure),
    ),
)
```

Normally, I'd get the user from django's `request` but since the `args.request` is a `BoltRequest` that doesn't work.

One hacky way I could think of is to use the `SlackOAuthState` in some way, as in attach a user attribute to the SlackOAuthState object. When it is consumed, I can get the user attached to this state object.

#### The `slack_bolt` version

1.18.1

#### Python runtime version

3.9.10

**Comment by seratch** [comment]
Hi @ravi-ojha, thanks for asking the question. You can use `args.request.headers` to access cookie data your app can set. 
* https://slack.dev/bolt-python/api-docs/slack_bolt/oauth/callback_options.html#slack_bolt.oauth.callback_options.SuccessArgs
* https://slack.dev/bolt-python/api-docs/slack_bolt/request/request.html#slack_bolt.request.request.BoltRequest
* https://slack.dev/python-slack-sdk/api-docs/slack_sdk/oauth/installation_store/models/installation.html

Perhaps, parsing your service's auth session cookie string and assoiate your service's user ID and Slack's enterprise_id/team_id + user_id would be good to go. I hope this helps.

**Comment by ravi-ojha** [comment]
Ahh.. thank you! That was a bit stupid of me not to think about raw cookies. What using `request.user` from Django does to a fella lol

And just wanna say thanks to everyone maintaining this package and examples. This part from [django oauth example](https://github.com/slackapi/bolt-python/blob/main/examples/django/oauth_app/slack_datastores.py) was a huge help!

**Comment by ravi-ojha** [comment]
Appreciate the help! Closing this now, I was able to build a nice custom bot for my side project [Ticketping](https://ticketping.com/)
