### ISSUE TITLE
Get Channel_id through channel_name besides using conversations.list

### ISSUE THREAD

**Issue by Tang20031010** [slackapi/bolt-python#1093]
(Describe your issue and goal here)

#### The `slack_bolt` version
slack-bolt==1.18.1
slack_sdk==3.27.2

#### Python runtime version

Python 3.12.3

#### OS info

ProductName:            macOS
ProductVersion:         14.4.1

#### Steps to reproduce:

I am trying to get channel id by channel name. I would like to let the user input a channel's name and use that to get the channel's id since I need the channel id to do conversations.join. I have found one thread in https://github.com/slackapi/bolt-js/issues/1725 and tried the suggestion by using conversations.list to filter and then use the conversations.info. However, there are too many channels in the organization. I have tried pagination but still failed to retrieve all channels through conversations.list. I think there are more than 50000 channels and the return from conversations.list is not stable. Since that post is in 2023, I am wondering if we have additional solutions to this situation. The worst case I am thinking is letting user input the channel id. 

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by filmaj** [comment]
> I would like to let the user input a channel's name and use that to get the channel's id since I need the channel id to do conversations.join.

Could you use [the Block Kit Conversation Select Menu](https://api.slack.com/reference/block-kit/block-elements#conversations_select)? It will render a drop down menu of conversations (channels, public or private, even DMs and MPDMs) that is contextual to the user (meaning: the user has access to them). Then, you can [listen to `block_actions` payloads](https://api.slack.com/interactivity/handling#payloads) on this element to get channel / conversation ID.

**Comment by Tang20031010** [comment]
Thank you for your quite response! I looked into it; however, this does not seem quite fit to my situation as what I want is to let the user only interact with the UI I implemented instead of going to slack to do the operation.

**Comment by filmaj** [comment]
I see. Yes, it's a common request and unfortunately we have no good answer. If you have access to an admin token, you could use [the `admin.conversations.search` API](https://api.slack.com/methods/admin.conversations.search) as it accepts a `query` parameter for the channel name. The other is to paginate through `conversations.list`, as you pointed out.

**Comment by Tang20031010** [comment]
Thank you! I probably need to go with letting the user input input channel_id.
