### ISSUE TITLE
Scaling with socket mode

### ISSUE THREAD

**Issue by Keeo** [slackapi/bolt-python#1105]
How can I scale the application connected using socket mode?

Based on the documentation, it looks like I can have up to 10 connections open without any way of scaling more horizontally or vertically.

### The page URLs

* https://api.slack.com/apis/socket-mode

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by zimeg** [comment]
Hey @Keeo 👋  You're right to find the limit of 10 open connections! The creation and scaling of these connections should happen automatically as separate processes are created for the app. A bit more detail can be found in #1071.

I hope this is helpful in understanding how connections for your app are managed! The scaling of infrastructure that powers your app processes is another topic altogether, but please let me know if this is of interest! 🚀

**Comment by Keeo** [comment]
Thank you, and also looking on the rate limits, the scaling wont be an issue.
