### ISSUE TITLE
How do I map a user from my service to a team ID?

### ISSUE THREAD

**Issue by aryabhatta-dey** [slackapi/bolt-python#1111]
Hey, I am using the Django example from [here](https://github.com/slackapi/bolt-python/tree/main/examples/django). I want to be able to map the user who is installing the Slack bot from my site to the team ID they are installing it to. How can I achieve this?

I have found these related threads but am unsure how to implement the same functionality in the Django sample app:
1. https://github.com/slackapi/python-slack-sdk/issues/1233
2. https://github.com/slackapi/bolt-js/issues/1541

**Comment by WilliamBergamin** [comment]
Hi @aryabhatta-dey thanks for writing in!

Have you looked at the [django/oauth_app exemple](https://github.com/slackapi/bolt-python/tree/main/examples/django/oauth_app) it implements [OAuth](https://api.slack.com/authentication/oauth-v2) and stores the user installation information in [djando.db models](https://docs.djangoproject.com/en/5.0/ref/databases/) this should allow you to figure out who is installing your application from your website.

**Comment by aryabhatta-dey** [comment]
Hey thx for the prompt reply. I have taken a look at it. There is possibly some miscommunication. Please let me clarify - what I want to do is map the slack team id to an external user_uuid (generated from my service which is external to slack and hence the user_uuid here has no relation to slack's user_id).

**Comment by aryabhatta-dey** [comment]
I was hoping there would be a way to achieve what's mentioned here - https://github.com/slackapi/bolt-js/issues/1541

**Comment by aryabhatta-dey** [comment]
Hey this resolved it. Thank you for the help! Appreciate it!
