### ISSUE TITLE
Add support for custom-expiring ephemeral messages (chat.postEphemeral with a set timer)

### ISSUE THREAD

**Issue by PeakMike** [slackapi/bolt-python#1114]
We'd like to enhance the Slack Bolt Python SDK to support sending ephemeral messages that automatically expire after a set time. This feature would be particularly useful for delivering contextual tips or temporary information without cluttering the chat history. 

### Category (place an `x` in each of the `[ ]`)

* [x] **slack_bolt.App** and/or its core components
* [ ] **slack_bolt.async_app.AsyncApp** and/or its core components
* [ ] Adapters in **slack_bolt.adapter**
* [ ] Others

## Requirements

Specifically, we're looking to:
1. Extend the chat.postEphemeral method to include an optional 'expiry' parameter.
2. Allow setting the expiry time in seconds (e.g., 60 seconds for a message to disappear after 1 minute).
3. Automatically handle the message deletion on the client-side once the expiry time is reached.

This feature would enable more dynamic and less intrusive ways to provide temporary information to users, enhancing the overall user experience in Slack apps built with the Bolt SDK.

**Comment by seratch** [comment]
Hi @PeakMike, thanks for sharing this feedback! 

I see that this functionality can be useful for some use cases, but unfortunately, `chat.postEphemeral` API itself is not designed to have the expiration of the message. Additionally, even if there was a chance to enhance `chat.postEphemeral` to support this, it wouldn't be feasible to add this type of feature just on the bolt-python side. Such an enhancement requires Slack server-side changes as well, but we don't have any plans to make changes to the API endpoint on our roadmap.

As a workaround, please consider implementing something similar using `chat.postMessage` and your own database to manage the message expiration. When a message expires, your app can delete the message by calling `chat.delete` API. I understand you'd like to use `chat.postEphemeral` instead, but we are unable to offer anything for this use case at this time. It'd be appreciated if you could understand this.

We don't have anything else to offer you on this topic, so let me close this issue now. Thank you so much again for sharing this feedback.
