### ISSUE TITLE
Can we get any way to pass custom data into installation store ?

### ISSUE THREAD

**Issue by MadhabaPatra** [slackapi/bolt-python#1119]
Right now only installation is passed to installation store. I do have custom data in state. I want to pass this custom data into installation store.

**Comment by seratch** [comment]
Hi @MadhabaPatra, the installation data class has custom_values, so your installation store can save the additional properties and return them as necessary:
https://github.com/slackapi/python-slack-sdk/blob/v3.31.0/slack_sdk/oauth/installation_store/models/installation.py#L84

To attache the custom_values, you can implement either oauth_settings.callback_options.success or oauth_flow.store_installation:
- https://slack.dev/bolt-python/api-docs/slack_bolt/oauth/oauth_settings.html#slack_bolt.oauth.oauth_settings.OAuthSettings.callback_options
- https://slack.dev/bolt-python/api-docs/slack_bolt/oauth/oauth_flow.html#slack_bolt.oauth.oauth_flow.OAuthFlow.store_installation

Here are a few examples:
- callback_options.success: https://github.com/slackapi/bolt-python/blob/v1.19.1/examples/oauth_app_settings.py#L13-L36
- inheriting OAuthFlow (and then you can override the store_installation method to add custom_values extracted from request data): https://github.com/slackapi/bolt-python/blob/v1.19.1/slack_bolt/adapter/aws_lambda/lambda_s3_oauth_flow.py#L18

Hope this helps!

**Comment by MadhabaPatra** [comment]
Thanks @seratch . I created custom oauth flow and  i did override the store_installation function. You really helped me by sharing the aws oauth flow adapter.
