### ISSUE TITLE
User id is missing in installation query - Picking bot installation instead of user installation

### ISSUE THREAD

**Issue by MadhabaPatra** [slackapi/bolt-python#1121]
While sending an hello message, The bolt app could not able to generate actual payload in order to query in the installation.  It should look for user installation, but its looking for bot installation. i shared the event payload too.  

> {'token': '123', 'team_id': '123', 'context_team_id': 'T07D3RKQHLG', 'context_enterprise_id': None, 'api_app_id': 'A07EH8KPG5D', 'event': {'user': 'U07CC57KKSR', 'type': 'message', 'ts': '1723116410.561499', 'client_msg_id': '21f2e299-bfc3-4173-9f47-a1690dc9cdbd', 'text': 'hello', 'team': 'T07D3RKQHLG', 'blocks': [{'type': 'rich_text', 'block_id': 'ZL1yL', 'elements': [{'type': 'rich_text_section', 'elements': [{'type': 'text', 'text': 'hello'}]}]}], 'channel': 'D07F0TWHTKL', 'event_ts': '1723116410.561499', 'channel_type': 'im'}, 'type': 'event_callback', 'event_id': 'Ev07GFBKFA2D', 'event_time': 1723116410, 'authorizations': [{'enterprise_id': None, 'team_id': 'T07D3RKQHLG', 'user_id': 'U07CC57KKSR', 'is_bot': False, 'is_enterprise_install': False}], 'is_ext_shared_channel': False, 'event_context': '4-1'}

```
DEBUG:slack_bolt.App:Applying slack_bolt.middleware.ssl_check.ssl_check.SslCheck
DEBUG:slack_bolt.App:Applying slack_bolt.middleware.request_verification.request_verification.RequestVerification
DEBUG:slack_bolt.App:Applying slack_bolt.middleware.authorization.multi_teams_authorization.MultiTeamsAuthorization
DEBUG:slack_sdk.oauth.installation_store.file:Installation data missing for enterprise: none, team: T07D3RKQHLG: [Errno 2] No such file or directory: '/Users/gmadhabanandapatra/.bolt-app-installation/245591673607.7493291798183/none-T07D3RKQHLG/installer-latest'
DEBUG:slack_sdk.oauth.installation_store.file:Installation data missing for enterprise: none, team: T07D3RKQHLG: [Errno 2] No such file or directory: '/Users/gmadhabanandapatra/.bolt-app-installation/245591673607.7493291798183/none-T07D3RKQHLG/bot-latest'
DEBUG:slack_bolt.oauth.oauth_settings:No installation data found for enterprise_id: None team_id: T07D3RKQHLG
ERROR:slack_bolt.MultiTeamsAuthorization:Although the app should be installed into this workspace, the AuthorizeResult (returned value from authorize) for it was not found.
```

**Comment by MadhabaPatra** [comment]
Ignore the "No installation data found". I am concerning about the bolt app why does it searching the bot installation. i'm using custom installation store. To debug i had to use the default installation store.

**Comment by seratch** [comment]
Hi @MadhabaPatra, thanks for asking the question.

As you observed, a user ID in a payload can be absent in many events that your app can receive. Even when a user ID exists in a payload, your InstallationStore may not have the corresponding installation data for the user (say, user A installed your app and then, user B used your app's slash command).

Aside from that, the default InstallationStore-based authorize function in this Bolt framework expects a bot scope token to exist for a workspace where your app is added for receiving events. While it's technically possible not to have bot scopes for the installation flow, we highly recommend having bot scopes (e.g., at least having commands, chat:write) when your app is added to a workspace. Without that, many functionalities that bolt-python offers do not work. Not only that, sharing a single person's user token with other users could cause data confidentiality issues or unexpected misbehaviors.

If you want to receive user scopes at a time or via a different OAuth flow, it's still feasible while granting bot scopes for primary installation of your app. Your InstallationStore can return both bot token and user token for an incoming request.

If you really want to rely only on user tokens for your bolt app, you can implement your own authorize function. Here is the built-in InstallationStore-based authorize function code: https://github.com/slackapi/bolt-python/blob/v1.19.1/slack_bolt/authorization/authorize.py#L114. You can implement your own and pass it as "authorize" when initializing the App instance. However, if you go with this approach, as I mentioned above, please note that the app behaves using a user token, not a bot token. This can cause data security issues and misbehaviors (e.g., posting a message as a user, not a bot). Thus, I don't recommend this workaround at all. Please consider going straightforward with bot scopes for your primary installation flow.

I hope this helps.

**Comment by seratch** [comment]
If you're not trying to have user scopes but you're just confused with the absence of user ID in a query, your InstallationStore needs to return a bot installation data for enterprise_id + team_id. If your app has user scopes too, your InstallationStore can run at least two queries to find both bot and user installation data and combine them into a single data. Checking the built-in installation store implementations may be helpful to learn how to do this: https://github.com/slackapi/python-slack-sdk/tree/main/slack_sdk/oauth/installation_store

**Comment by MadhabaPatra** [comment]
Okay, so if we only use bot scopes, the InstallationStore runs a **find_bot** query. If we use both user scopes and bot scopes, it runs two queries: one to **find_bot** and another to **find_installation**. Is that correct?

**Comment by seratch** [comment]
No, it's not correct. As long as you implement find_installation correctly (meaning it always returns bot token plus may attach user token too if it's available), you don't need to implement find_bot. If you're still unsure, please check this code to learn how it works: https://github.com/slackapi/bolt-python/blob/v1.19.1/slack_bolt/authorization/authorize.py#L163-L353

**Comment by MadhabaPatra** [comment]
I understood now.

**Comment by MadhabaPatra** [comment]
Thanks @seratch for quick support.

**Comment by MadhabaPatra** [comment]
@seratch , Is there any possible to get installation data with custom values in the event ?

```
@slack_app.event(event="message", middleware=[no_bot_messages])
def handle_message():
    print("installation custom values??")
```

**Comment by seratch** [comment]
The simplest solution is to add a global middleware (https://slack.dev/bolt-python/concepts/global-middleware), which fetches the installation data again and sets the custom_values to the context object.

The downside of this approach is that your app has to run the same find_installation query twice (authorize + this global middleware). If you'd like to avoid this overhead, you can consider: 1) having a short-time cache layer within your InstallationStore, or 2) implementing authorize by inheriting the built-in InstallationStoreAuthorize and passing your own authorize to the App constructor. I don't recommend the second approach because it can create technical debt on your side in the long run.

I hope this helps. It seems everything on this topic is clear now. Would you mind closing this issue? Whenever you have a new question about bolt-python, please feel free to submit a new question!

**Comment by MadhabaPatra** [comment]
Thanks for detailed explanation. I appreciate it.
