### ISSUE TITLE
How to stop further middleware executions

### ISSUE THREAD

**Issue by MadhabaPatra** [slackapi/bolt-python#1122]
I'm trying to implement a middleware that checks a condition and, if the condition is satisfied, stops the execution of the middleware chain without proceeding to the next middleware or event listener.

```
def has_access(context, next):
    # Bunch of if else conditions

    if context.user_id != "123":
        # Stop execution
        pass

    if context.team_id != "xyz":
        # Stop execution
        pass

    next()
```

**Comment by MadhabaPatra** [comment]
However, using return None or even raising an exception to stop the execution hasn't worked either. 

Additionally, the Slack retry logic is triggered when using these methods.

**Comment by seratch** [comment]
Hi @MadhabaPatra, thanks for asking the question! 

When your global middleware returns a response object or calls `ack()` and skips `next()`, the rest of middleware and listeners won't be called. See also:
- https://github.com/slackapi/bolt-python/blob/v1.19.1/slack_bolt/middleware/url_verification/url_verification.py#L31-L34
- https://github.com/slackapi/bolt-python/blob/v1.19.1/slack_bolt/middleware/ignoring_self_events/ignoring_self_events.py#L28-L30

Let me close this issue now, but if you have follow-up questions, please feel free to write in.

**Comment by MadhabaPatra** [comment]
Thanks, @seratch , for the quick response! It was like getting help from an AI bot. 😊
