### ISSUE TITLE
A class with async "__call__" method fails to work as a middleware

### ISSUE THREAD

**Issue by chet-manley** [slackapi/bolt-python#1131]
(Filling out the following details about bugs will help us solve your issue sooner.)

### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version

```bash
slack-bolt==1.18.1
slack_sdk==3.31.0
```

#### Python runtime version

```bash
Python 3.11.9
```

#### OS info

```bash
bash: sw_vers: command not found
❯ uname -a
Linux 49d1cffcb728 6.8.4-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Apr  4 20:45:21 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

```python
from slack_bolt.app.async_app import AsyncApp

class MyCallableMiddleware:

    async def __call__(self, next_) -> None:
        await next_()

app = AsyncApp()
app.middleware(MyCallableMiddleware()) # this raises `ValueError: Async middleware function must be an async function`
```

### Expected result:

`AsyncApp.middleware` accepts _any_ `Callable[..., Awaitable[Any]]` object, per signature.

### Actual result:

The middleware instance pass the callable check here
https://github.com/slackapi/bolt-python/blob/main/slack_bolt/app/async_app.py#L678
and is thus sent to `AsyncCustomMiddleware` init here
https://github.com/slackapi/bolt-python/blob/main/slack_bolt/middleware/async_custom_middleware.py#L13
where the signature for `func` is `Callable[..., Awaitable[Any]]` (which my middleware instance is).
However, `inspect.iscoroutinefunction` is used to check `func`, which _does not pass_, as it checks for the existence of 
`CO_COROUTINE` flag (see here: [CPython source](https://github.com/python/cpython/blob/v3.11.9/Lib/inspect.py#L414)), 
despite the instance being both callable and asynchronous.

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @chet-manley, thanks for reporting this issue. The built-in inspect library's behaviuor is a bit surprising, but it seems this scenario should be supported. I found a workaround on bolt-python side, so will come up with a pull request resolving it. Once it's merged, we will release a new patch release fixing the issue.
