### ISSUE TITLE
How can I register messages from the bot?

### ISSUE THREAD

**Issue by MihailovAlexander** [slackapi/bolt-python#1159]
i have a simple code:
```python
import os
from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler

app_token = os.getenv("SLACK_APP_TOKEN")  # xapp
bot_token = os.getenv("TOKEN_BOT")  # xoxb
app = App(token=bot_token,
        signing_secret=os.environ.get("SLACK_SIGNING_SECRET"))

@app.event("message")
def handle_message_events(body, logger):
    print('!!!!!!!NEW MSG!!!!!!!')

if __name__ == "__main__":
    SocketModeHandler(app, app_token).start()
```
This code perfectly registers user messages, but unfortunately does not register messages from the bot. How can I register messages from the bot?

**Comment by seratch** [comment]
Hi @MihailovAlexander, thanks for writing in. 

Do you mean you'd like to receive the message events posted by your app's bot user itself too? If yes, bolt-python filters the message events out by default to prevent a common pitfall for developers causing an infinite self-reply loop. If you're aware of the risk and you still would like to take full control, you can pass `ignoring_self_events_enabled=False` to the App constructor to disable this built-in logic.

**Comment by MihailovAlexander** [comment]
@seratch, Thank you for your quick response, your solution helped me!🥳🥳🥳🥳
