### ISSUE TITLE
Circular Dependency when trying to run example code

### ISSUE THREAD

**Issue by jacoblElementor** [slackapi/bolt-python#1163]
Hi,
I'm trying to run a socket connection app, but I'm getting a circular dependency error.
Would appreciate help with this, adding here necessary info

#### The `slack_bolt` version
  * slack_bolt==1.20.1
  * slack_sdk==3.33.0
#### Python runtime version
  * Python 3.12.5
#### OS info
  ProductName:            macOS
  ProductVersion:         14.6.1
  BuildVersion:           23G93
  Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:04 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6020

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1. Copy example code for socket connection:
```python
import os
from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler

# Install the Slack app and get xoxb- token in advance
app = App(token=os.environ["SLACK_BOT_TOKEN"])

if __name__ == "__main__":
    handler = SocketModeHandler(app, os.environ["SLACK_APP_TOKEN"])
    handler.start()
```
3. Try running the code

### Expected result:

The code should be running, expecting connections.

### Actual result:
Getting a `circular import` error
```bash
Traceback (most recent call last):
  File "/.../src/socket.py", line 2, in <module>
    from slack_bolt import App
  File "/.../venv/lib/python3.12/site-packages/slack_bolt/__init__.py", line 9, in <module>
    from .app import App
  File "/.../venv/lib/python3.12/site-packages/slack_bolt/app/__init__.py", line 10, in <module>
    from .app import App
  File "/.../venv/lib/python3.12/site-packages/slack_bolt/app/app.py", line 9, in <module>
    from http.server import SimpleHTTPRequestHandler, HTTPServer
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/server.py", line 92, in <module>
    import email.utils
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/email/utils.py", line 29, in <module>
    import socket
  File "/.../src/socket.py", line 2, in <module>
    from slack_bolt import App
ImportError: cannot import name 'App' from partially initialized module 'slack_bolt' (most likely due to a circular import) 
```

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @jacoblElementor, thanks for writing in. I tried to reproduce your situation, but everything works for me without any issues. Perhaps, there might be a specific cause of your situation (I cannot guess what it is tho).

I'd recommend starting with a clean Python runtime. pyenv or something like that would be useful for this purpose. Once you've installed a valid Python runtime, you can start with a venv runtime. For instance, all what I did are:
```
python -m venv .venv
source .venv/bin/activate
echo "slack_bolt==1.20.1
slack_sdk==3.33.0
" > requirements.txt 
pip install -r requirements.txt
export SLACK_APP_TOKEN=....
export SLACK_BOT_TOKEN=...
python app.py
```

If you find a quick way to reproduce your situation, we're happy to check it out. Hope things go well for you soon.

**Comment by jacoblElementor** [comment]
Hi @seratch 
I did try using a new fresh venv, but I will try again, from total scratch
