### ISSUE TITLE
Using workflow custom function on AWS lambda

### ISSUE THREAD

**Issue by ben-dov** [slackapi/bolt-python#1169]
I am trying to convert a a legacy workflow step to the new custom function in AWS lambda, but do not see any documentation on this.

The closest is https://api.slack.com/automation/functions/custom-bolt and https://api.slack.com/tutorials/tracks/bolt-custom-function, but both are using `SocketModeHandler` and have no mention of FaaS, like AWS lambda.

Is the feature compatible?

**Comment by filmaj** [comment]
Yes, it should be no problem using any adapter of your choice. At the end of the day, custom functions are invoked by Slack sending a [`function_executed` event](https://api.slack.com/events/function_executed) to your app. How the event is delivered (socket mode or HTTP) is up to you to decide via your app configuration.
