### ISSUE TITLE
Trouble using an InstallationStore other than the default

### ISSUE THREAD

**Issue by brunogarciagonzalez** [slackapi/bolt-python#1172]
Hello 👋 ,

I am having trouble using an `InstallationStore` other than the default. Specifically, it looks like the installation data is not being installed when using other installation stores.

I have a  Django app that integrates with a new Slack application I am building. Our org does not have a Slack enterprise plan. Our org uses Okta OAuth for users to sign into Slack.

In the Slack Apps web platform (`api.slack.com`) I have added the proper Request URL ending in `/slack/events` to
```
Features > Interactivity & Shortcuts > Interactivity [ON] > Request URL
```
As well as to a slash command's Request URL.

When working with the default installation store, the installation works. This is on my local machine and leveraging an ngrok tunnel.
The default installation store cannot be used in production environment because the Django app is hosted on Heroku, which means the server's filesystem is ephemeral.

So I looked to the `AmazonS3InstallationStore`, and confirmed that my AWS credentials are correct and that the bucket's permissions are correct.

For example, running 
```python
try:
    s3_client.put_object(Bucket=settings.AWS_BUCKET, Key='test-file.txt, Body='test content')
   print('File written successfully')
except Exception as e:
   print(f"Failed to write file to S3: {str(e)}")
```
properly creates the object in the S3 bucket.

But when using this s3_client with an instance of `AmazonS3InstallationStore`, it does not look like the SackBolt `App()` instance ever writes the installation data to the s3 bucket. Instead  I ultimately get the following:
```
Failed to find an installation data for enterprise: none, team: <teamID>: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
```

I kept the `AmazonS3InstallationStore` installation store but reverted to localhost + ngrok, and here again nothing is being written to the S3 bucket. So I thought it was due to the Heroku environment at first, but now I am wondering if the installation store's `save()` method is not running?

I even tried the `SQLite3InstallationStore` on localhost + ngrok but that is not writing any records to the sqlite3 database either.

Here is my current code:

```python
import logging

from boto3 import Session
from django.conf import settings
from slack_bolt import App
from slack_sdk.oauth.installation_store.amazon_s3 import AmazonS3InstallationStore

logger = logging.getLogger(__name__)


aws_session = session = Session(
    aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
    aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY,
    region_name=settings.AWS_DEFAULT_REGION,
)

s3_client = session.client("s3")

s3_store = AmazonS3InstallationStore(
    bucket_name=settings.AWS_BUCKET,
    client_id=settings.SLACK_CLIENT_ID,
    s3_client=s3_client,
    logger=logger,
    historical_data_enabled=False,  # Keep old versions if True, False for simpler setup
)

app = App(
    signing_secret=settings.SLACK_SIGNING_SECRET,
    installation_store=s3_store,
    logger=logger,
)
```

Would love your take on this, all thoughts appreciated.

#### The `slack_bolt` version

```
slack_bolt==1.20.1
slack_sdk==3.32.0
```

#### Python runtime version

```
Python 3.10.9
```

#### OS info

```
ProductName:		macOS
ProductVersion:		14.7
BuildVersion:		23H124
Darwin Kernel Version 23.6.0: Wed Jul 31 20:49:39 PDT 2024; root:xnu-10063.141.1.700.5~1/RELEASE_ARM64_T6000
```

But also in Heroku server.

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

On local: Django's `runserver` & `ngrok http`
Heroku Procfile command is: `daphne app_name.asgi:application --port $PORT --bind 0.0.0.0 -v2`

### Expected result:

Similar to the default installation store automatically adding the installation data to its storage target (eg filesystem), I expect the S3 installation store to automatically store the data in the s3 bucket, or the sqlite3 store to insert into the sqlite3 database.

### Actual result:

Focusing on the s3 store -- the installation data is never uploaded to the s3 bucket, ultimately leading to 
```
Failed to find an installation data for enterprise: none, team: <teamID>: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
```

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by hello-ashleyintech** [comment]
Hi, @brunogarciagonzalez! Thanks for submitting this issue! 😄 

I'm currently looking into this, but wanted to get some additional insight into what was happening. How are you installing instances of your app? Are you installing through the OAuth flow at `/slack/install` or through something else?

**Comment by brunogarciagonzalez** [comment]
Hi @hello-ashleyintech !
Thanks for your time and help with this.

The app was created and installed into the Slack workspace via the `api.slack.com` web platform.
So it began by https://api.slack.com/apps and creating a new "Web API Application" there using the `From scratch` option.
My org's workspace was specified in the app creation process.

I have also triggered via the web platform's "Reinstall" button:
```
Settings > Install App > Reinstall to <TeamName>
```

With regards to `/slack/install`, I am not handling any webhooks or events outside of the SlackBolt `App()` instance.
I looked into listening for the "app_installed" event via the SlackBolt `App()` instance as follows:
```python
@app.events("app_installed")
def handler_method(etc):
    pass
```

But this even was never sent my way whenever reinstalling via the "Reinstall" button. Presumably because my Slack app would need [admin.apps:read](https://api.slack.com/scopes/admin.apps:read) permission? But that seems reserved for Enterprise Grid organizations, and we are not on an enterprise plan.

But when using the default installation store (I think* its the `FileInstallationStore`) with my current SlackBolt `App()` config, I was able to interact properly with our actual Slack workspace. The use of the `AmazonS3InstallationStore` looks to not write installation data to the s3 bucket.

Or how can the default `FileInstallationStore` work fine (which I take it to mean it properly handles the installation data) but the same flow for `AmazonS3InstallationStore` seems to not save the installation data, leading to the error
```
Failed to find an installation data for enterprise: none, team: <teamID>: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
```

Best regards

**Comment by seratch** [comment]
@brunogarciagonzalez When you enable InstallationStore in your app, **all the installations must be done starting at /slack/install URL**. The install button on api.slack.com admin page indeed issues a new installation token, but your InstallationStore is not able to store it in any way.

You said FileInstallationStore works fine, but I'd recommend double-checking if the file store really stores your instalation. You can check [this directory](https://github.com/slackapi/python-slack-sdk/blob/v3.33.1/slack_sdk/oauth/installation_store/file/__init__.py#L21) to verify if the data is successfully saved. If you find files there, this means you've gone through the OAuth flow starting at /slack/install at least once.

If the /slack/install URL does not work for you, please double check if you've passed all necessary arguments like SLACK_CLIENT_ID etc. You can reuse the example code here: https://tools.slack.dev/bolt-python/concepts/authenticating-oauth It seems you're explicitly passing only installation_store and it may be the cause of your situation. If you don't pass other necessary arguments via env variables, the OAuth URL serving does not work for you.

Lastly, we have an example app for Django users: https://github.com/slackapi/bolt-python/tree/main/examples/django Storing installations in a Django ORM database table may be much easier for you.

Hope you'll figure the way you want to go out soon!

**Comment by brunogarciagonzalez** [comment]
Hi @seratch ,

Thanks for helping me with this.

I checked the linked directory and you are right -- no installation data. In my attempt to give a clean opening message I neglected the following piece of info, which now sees important:
When developing with `localhost + ngrok` and not using an installation store, I was actually using a bot token, such that the `App()` looked something like:
```python
app = App(
    token=settings.SLACK_BOT_TOKEN,
    signing_secret=settings.SLACK_SIGNING_SECRET,
    logger=logger,
)
```

But deploying this code to Heroku is what lead to my first encounter with the installation store issue. I then proceeded to work with installation stores and find myself as described in my opening message.

So you are right that initially (on `local + ngrok', but still on our org's actual Slack workspace) I did not use installation store.
Yet, and If I may pivot the question of this ticket, -- why would a Heroku deployment trigger installation store code even with the use of a bot token, but that not take place on `local + ngrok`?

Here are those Heroku logs for Heroku + bot token config:
```
heroku/router at=info method=POST path="/slack/events/" host=<REDACTED> request_id=430ee348-b92d-43f2-8f13-078444efb015 fwd="34.204.180.238" dyno=web.2 connect=1ms service=77ms status=200 bytes=254 protocol=https
app/web.2 2024-10-02 18:05:56,660 DEBUG    Applying slack_bolt.middleware.ssl_check.ssl_check.SslCheck
app/web.2 2024-10-02 18:05:56,660 DEBUG    Applying slack_bolt.middleware.request_verification.request_verification.RequestVerification
app/web.2 2024-10-02 18:05:56,660 DEBUG    Applying slack_bolt.middleware.authorization.multi_teams_authorization.MultiTeamsAuthorization
app/web.2 2024-10-02 18:05:56,660 DEBUG    Installation data missing for enterprise: none, team: REDACTED: [Errno 2] No such file or directory: '/app/.bolt-app-installation/2168234900.7685095369446/none-REDACTED/installer-latest'
app/web.2 2024-10-02 18:05:56,660 DEBUG    Installation data missing for enterprise: none, team: REDACTED: [Errno 2] No such file or directory: '/app/.bolt-app-installation/2168234900.7685095369446/none-REDACTED/bot-latest'
app/web.2 2024-10-02 18:05:56,660 DEBUG    No installation data found for enterprise_id: None team_id: REDACTED
app/web.2 2024-10-02 18:05:56,660 ERROR    Although the app should be installed into this workspace, the AuthorizeResult (returned value from authorize) for it was not found.
app/web.2 2024-10-02 18:05:56,661 DEBUG    Sending a request - url: https://hooks.slack.com/commands/REDACTED/7812995069222/PXkUq2ZdtTAUirohywLuJ00o, body: {"text": ":warning: We apologize, but for some unknown reason, your installation with this app is no longer available. Please reinstall this app into your workspace :bow:"}, headers: {'Content-Type': 'application/json;charset=utf-8', 'User-Agent': 'Python/3.11.9 slackclient/3.32.0 Linux/5.15.0-1070-aws'}
app/web.2 2024-10-02 18:05:56,731 DEBUG    Received the following response - status: 200, headers: {'date': 'Wed, 02 Oct 2024 18:05:56 GMT', 'server': 'Apache', 'vary': 'Accept-Encoding', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'referrer-policy': 'no-referrer', 'x-slack-unique-id': 'REDACTED', 'x-slack-backend': 'r', 'access-control-allow-origin': '*', 'x-frame-options': 'SAMEORIGIN', 'content-type': 'text/html', 'content-length': '2', 'via': '1.1 slack-prod.tinyspeck.com, envoy-www-iad-ygcqkkrw, envoy-edge-iad-iojldtmr', 'x-envoy-attempt-count': '1', 'x-envoy-upstream-service-time': '31', 'x-backend': 'main_normal main_canary_with_overflow main_control_with_overflow', 'x-server': 'slack-www-hhvm-main-iad-lcca', 'x-slack-shared-secret-outcome': 'no-match', 'x-edge-backend': 'envoy-www', 'x-slack-edge-shared-secret-outcome': 'no-match', 'connection': 'close'}, body: ok
app/web.2 10.1.53.12:11939 - - [02/Oct/2024:18:05:56] "POST /slack/events/" 200 -

```

**Comment by seratch** [comment]
If you set the expected env variables like SLACK_CLIENT_ID, SLACK_CLEINT_SECRET, SLACK_BOT_SCOPES and so on, App constructor automatically enables the OAuth flow for you under the hood. If you unintentioanlly set those variables to the Heroku instance, you can remove them.

**Comment by brunogarciagonzalez** [comment]
@seratch ah that was exactly my problem. By removing env vars related to the oauth flow, the `App()` respected the bot token config I was going with -- thank you for your expertise!
