### ISSUE TITLE
FastAPI BackgroundTasks not functioning as expected with Bolt

### ISSUE THREAD

**Issue by rvishruth** [slackapi/bolt-python#1176]
I am integrating Slack Bolt with FastAPI and encountering an issue when trying to use BackgroundTasks in an event handler. Specifically, I expect the background task to run regardless of whether any prior background tasks are added within the FastAPI route handler. However, the background task only runs when it's first added within the route handler. Any guidance on how to resolve this issue or what's causing this?

[I tried asking in the FastAPI Github](https://github.com/fastapi/fastapi/discussions/12207), but had no luck there. Marking this as a question because I'm not completely sure if this is a bug yet.

### Reproducible in:

```python
from typing import Any

from fastapi import APIRouter, BackgroundTasks, FastAPI, Request
from slack_bolt.adapter.fastapi.async_handler import AsyncSlackRequestHandler
from slack_bolt.async_app import AsyncApp as SlackBoltApp
from slack_bolt.async_app import AsyncBoltContext
from slack_sdk.web.async_client import AsyncWebClient

from app.routes.slack import slack_router

app = FastAPI()

slack_bolt_app = SlackBoltApp(
    signing_secret="<>", token="<>"
)
slack_bolt_app_handler = AsyncSlackRequestHandler(slack_bolt_app)
slack_router = APIRouter(prefix="/slack", include_in_schema=False)


def write_log(message: str):
    print(message)


@slack_router.post("/events")
async def slack_events(request: Request, background_tasks: BackgroundTasks) -> Any:
    # background_tasks.add_task(write_log, message="cats are nice") # Line 26
    return await slack_bolt_app_handler.handle(
        request, addition_context_properties={"background_tasks": background_tasks}
    )


@slack_bolt_app.event("message")
async def handle_message_events(client: AsyncWebClient, body: dict[str, Any], context: AsyncBoltContext):
    print("Handling Slack message event.")
    print(type(context["background_tasks"]))
    context["background_tasks"].add_task(write_log, message="dogs are nice")


app.include_router(slack_router)

# Output if you uncomment line 26:
# Handling Slack message event.
# <class 'fastapi.background.BackgroundTasks'>
# cats are nice
# dogs are nice

# Output if you comment out line 26:
# Handling Slack message event.
# <class 'fastapi.background.BackgroundTasks'>
```

#### The `slack_bolt` version

1.20.1

#### Python runtime version

Python 3.12.4

#### OS info

Windows 11

#### Steps to reproduce:
1. `fastapi dev --reload`
2. Connect with the Slack events API
3. Receive a message event

### Expected result:

```
Handling Slack message event.
<class 'fastapi.background.BackgroundTasks'>
dogs are nice
```

### Actual result:

```
Handling Slack message event.
<class 'fastapi.background.BackgroundTasks'>
```

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @rvishruth, thanks for asking the question.

This looks very interesting. We're neither maintainers nor experts on FastAPI, so we're unable to assist with FastAPI-specific questions. That said, one thing I'm guessing is that perhaps BackgroundTasks might not work as expected with bolt-python in most cases. We've received a question related to BackgroundTasks before as well: https://github.com/slackapi/bolt-python/issues/1158#issuecomment-2340260984

bolt-python runs your event listeners as a separate asyncio task (or on a different thread if you use a non-asyncio App). Passing BackgroundTasks to different code executions may not be a great combination. Based on the behavior you've reported, it appears that the BackgroundTasks object can only be properly initialized when you call its add_task method for the first time within FastAPI's endpoint serving method. If that's the case, there isn't much we can do for this specific use case.

However, more importantly, I don't think you need to use BackgroundTasks to run time-consuming tasks asynchronously. The reason bolt-python runs your listener code as a separate asyncio task is to enable your app to immediately acknowledge (ack) the request within 3 seconds and then proceed with your tasks without worrying about timeouts. So, all you need to do is call the ack() method first and then put the rest of your processing after that. This way, your code should work without any issues.

Lastly, if you need to relay the async task to a different server, you might want to have a queue between servers, but I don't think that's the case here. Either way, there is no need to use BackgroundTasks for any reason.

I hope this was helpful to you.

**Comment by rvishruth** [comment]
Thanks @seratch! That's helpful! It looks like `slack_bolt_app_handler.handle(..)` actually acknowledges the request. So we actually don't need background tasks here! I do plan to eventually use a queue.
