### ISSUE TITLE
Command is not supported in threads

### ISSUE THREAD

**Issue by joshiayush** [slackapi/bolt-python#1177]
Hi team,

I'm using the new feature "Agents & Assistants" and I personally loved it! My company decided to move the code to the new "Agents & Assistants" and it worked, except for one thing that is - in our previous version we had a command in use that opens up a modal so that user can quickly fill it up and get the results.

We want to achieve the same thing in "Agents & Assistants" but I receive the following error:

![Screenshot from 2024-10-07 16-30-54](https://github.com/user-attachments/assets/8b80ddd1-e7a9-4a51-a768-3d18c65a6471)

How can we achieve this behaviour in threads?

**The `slack_bolt` version**

`slack_bolt==1.20.1`

**Comment by joshiayush** [comment]
@seratch Can you help?

**Comment by joshiayush** [comment]
@filmaj So how does "cohere-ai" achieves that?

**Comment by seratch** [comment]
@joshiayush I've answered the same question here: https://github.com/slackapi/python-slack-sdk/issues/1570#issuecomment-2398884643 I do hear having the command functionality could be valuable for your app too, but it'd be appreciated if you could understand this.

**Comment by joshiayush** [comment]
Sahi sahi!
