### ISSUE TITLE
Detect bot's available scopes before triggering functionality that needs it

### ISSUE THREAD

**Issue by stokedout** [slackapi/bolt-python#1178]
Is there a recommended way within a bot handler to check the current bot's scopes so that I can progressively enhance the experience for those with the right scopes, and do nothing for those without scopes (i.e those who haven't yet reinstalled)?

**Comment by seratch** [comment]
Hi @stokedout, thanks for asking the question! You can use `context.authorize_result.bot_scopes` for checking the scopes associated with the bot token.
