### ISSUE TITLE
IgnoringSelfEvents filters member_joined_channel/member_left_channel events out

### ISSUE THREAD

**Issue by fwump38** [slackapi/bolt-python#118]
The global middleware `IgnoringSelfEvents` is enabled by default for instances of App.

The [docs show an example](https://slack.dev/bolt-python/concepts#listener-middleware) for Listener middleware on how to filter out messages with `bot_message` subtype. Since a global middleware is already enabled for this, there doesn't appear to be a way to purposefully react to bot events.

Looking through the code, I don't see any reason that this middleware should be required so it shouldn't break things to turn it off but I am not sure how to do that.

The use case is for `member_joined_channel` events. The app I am working on lets users pick a channel for the bot to work in and then, as expected, the bot is unable to post to that channel until it is invited so I need to monitor for the bot being invited to the channel.

I configured a simple function (`@app.event("member_left_channel")`) to watch for these events but the aforementioned middleware prevents them from being executed.

### Category (place an `x` in each of the `[ ]`)

* [x] **slack_bolt.App** and/or its core components
* [ ] **slack_bolt.async_app.AsyncApp** and/or its core components
* [ ] Adapters in **slack_bolt.adapter**
* [x] Others

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
The reason why the middleware is enabled by default is that reacting to events generated by an app's bot user itself can easily result in infinite loop and that's a common pitfall when using Events API

Currently, the middleware lacks the required additional logic that is implemented in Bolt for JS. This is a bug. If this is correctly implemented, you do not need to turn the middleware off. 
https://github.com/slackapi/bolt-js/blob/%40slack/bolt%402.4.1/src/middleware/builtin.ts#L299-L306

I'll fix this issue. Thanks for pointing out this.

**Comment by seratch** [comment]
Also, we are not planning to introduce a way to turn the built-in middleware off in the short term. When we consider the feature, we will discuss the consistency among three Bolt framework implementations (Node, Python, JVM).

**Comment by prratek** [comment]
I ran into the same issue but for a different use case - I'd like to send a message with a bot and then thread another message in response to that. However, the `chat.postMessage` endpoint requires that you pass in the timestamp of the parent message to thread a response. Is there a way to get this timestamp given that you can't currently disable the `IgnoreSelfEvents` middleware?

**Comment by fwump38** [comment]
@prratek if you're sending the initial message with the slack_sdk by calling `Webclient.chat_postMessage` you should be able to receive the message ts from the response (if successful).

If you're just responding to an action/event/etc using Bolt for Python by using Bolt's `say()` function then I think say would need to be configured to return the `WebClient.chat_postMessage` response so you could call `Webclient.chat_postMessage` to send the threaded reply or, possibly, so that you could call `say()` again but with a timestamp provided to reply in-thread.

Just some ideas off the top of my head. When in doubt, calling the underlying slack_sdk (which is what Bolt is using) is always an option.

**Comment by seratch** [comment]
No worries, say method returns chat.postMessage API response as-is. https://github.com/slackapi/bolt-python/blob/v1.0.0/slack_bolt/context/say/say.py#L21

**Comment by prratek** [comment]
Thanks both of you! I deleted my comment a few minutes after posting because I realized `say()` returns the API response haha
