### ISSUE TITLE
Slack Action `type_select` Not Triggering After Modal is Opened

### ISSUE THREAD

**Issue by maniparas** [slackapi/bolt-python#1180]
Hello everyone, I'm seeing an issue with the SDK for a particular action `type_select`, I've provided more details below. Any help would be appreciated. Also, please let me know if more information is required from my side.

#### The `slack_bolt` version

```bash
slack_bolt==1.20.1
slack_sdk==3.33.1

```

#### Python runtime version

```bash
Python 3.9.6
```

#### OS info

```bash
ProductName:            macOS
ProductVersion:         15.0
BuildVersion:           24A335
Darwin Kernel Version 24.0.0: Mon Aug 12 20:51:54 PDT 2024; root:xnu-11215.1.10~2/RELEASE_ARM64_T6000
```

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1. Open the modal by clicking the “Create Broadcast” button.
2. Try to select either “Task” or “FYI” from the dropdown.
3. Observe that the modal is not dynamically updated, and no logging occurs for the type_select action.

### Expected result:

I was working on a dynamic form extension in Slack using the Bolt framework. The form allows users to select between different broadcast types (such as Task or FYI) using a dropdown. Based on the selected value, additional fields should be dynamically shown in the modal. For example:
- If the user selects Task, fields related to task details (like start date, end date, number of reminders) should appear.
- If the user selects FYI, these fields would not be shown.

Similarly, I have another dropdown for selecting the broadcast method (Channel or DM). If DM is selected, a field should appear for selecting multiple users who will receive the broadcast. However, the action for the dropdown selection `type_select` is not being triggered, preventing the dynamic form behavior from working as expected.

1. The modal should open after the button is clicked.
2. When the user selects Task or FYI in the dropdown, the type_select action should be triggered, and the modal should be updated with additional fields based on the selection.

```bash
# In broadcast_modal_content.py
def get_initial_blocks():
    return [
        {
            "type": "input",
            "block_id": "broadcast_type",
            "label": {"type": "plain_text", "text": "Is this a Task or FYI?"},
            "element": {
                "type": "static_select",
                "action_id": "type_select",  # This is the action ID not being triggered
                "options": [
                    {"text": {"type": "plain_text", "text": "Task"}, "value": "task"},
                    {"text": {"type": "plain_text", "text": "FYI"}, "value": "fyi"}
                ]
            }
        }
    ]

# In broadcast_action.py
@app.action("type_select")
def update_modal_on_type_selection(ack, body, client, logger):
    ack()  # Acknowledge the action
    logger.info("type_select action triggered")  # This log is never seen
    # Further processing for modal update
```

### Actual result:

- The open_broadcast_form action triggers correctly, and the modal opens.
- However, the type_select action is not triggered when a selection is made in the dropdown.

## Additional Details

<img width="740" alt="Screenshot 2024-10-15 at 12 38 41 PM" src="https://github.com/user-attachments/assets/161fcef6-930d-4c39-8354-2beaaa100531">

**Comment by seratch** [comment]
Hi @maniparas, thanks for asking the question. There are two approaches to implement what you'd like to build. 

The first one is to use actions/section block for the first selection, which triggers app.action listener execution. This comprehensive example app demonstrates how to implement such: https://github.com/seratch/apidays-workshop-2020/blob/main/python/app.py

The second is to add `"dispatch_action": True` to your input block: https://api.slack.com/reference/block-kit/blocks#input_fields This property enables your app to receive an app.action event when an end-user selects an item in the static_select list.

I hope this helps!

**Comment by maniparas** [comment]
Thank you for your response, @seratch, I really appreciate it! I would like to understand what went wrong with the implementation I tried—does it not work as an action callback? Additionally, are there any documents or resources that could help me learn the proper way to implement these kinds of features?

**Comment by seratch** [comment]
I mean just having an "input" type block does not trigger an app.action event (block_actions payload under the hood). The "input" blocks are supposed to be used for receiving user inputs in an app.view listener as view.state.values in the view_submission payload. As I mentioned above, if you want to use an input block for refreshing the whole modal view, adding dispatch_action: true to it is required. With that, the block can send app.action payload to your app. Another solution is to use section/actions block for the first category choice and then place input blocks for more details (the first approach I mentioned in the previous comment). 

There is no single page covering everthing around the Slack UI interactions but the following pages and their links may help:
- https://api.slack.com/surfaces/modals
- https://api.slack.com/block-kit/building

That said, before reading a bunch of document pages, I highly recommend running my example app  https://github.com/seratch/apidays-workshop-2020/blob/main/python/app.py and seeing how it works. This example uses actions blocks, but input blocks w/ dispatch_action: true can work in a similar way. Also, you can find many past questions about this topic: https://github.com/search?q=org%3Aslackapi+%22dispatch_action%22&type=issues

**Comment by maniparas** [comment]
It's working fine now. Thanks for the suggestions, I appreciate it. We can close this now. Do you want me to close or would you close this?

**Comment by seratch** [comment]
Glad to hear that you managed to implement the interactions! Let me close this issue now
