### ISSUE TITLE
SocketModeHandler Debug Mode? 

### ISSUE THREAD

**Issue by isaacjtrigoso** [slackapi/bolt-python#1189]
Hey Slack Support Team,

I have a question regarding the SocketModeHandler method for Slack Bolt. Recently I was attempting to debug a connection issue I was seeing and was looking through documentation to see if there was a way to get the output of this function. More specifically, I was looking to see if I log the steps the app is taking to connect to Slack and debug in that way. Here is my snippet of code I am referring to:
```
if __name__ == '__main__':
    handler = SocketModeHandler(app, 'slack_app_token')
    handler.start()
```
Is there a way we can output each step the handler takes to make a connection to Slack rather than just the "Slack Bolt is running" message?
Any information on this would be helpful, thank you!

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by isaacjtrigoso** [comment]
Hey @mwbrooks, 
This is exactly what I was looking for! That detailed log is what I was looking for and I was able to replicate your results by switching to debug on my logger. Thank you!

**Comment by mwbrooks** [comment]
Yay, that's fantastic to hear @isaacjtrigoso 🎉 Good luck on building your app :shipit:
