### ISSUE TITLE
How to access canvas document IDs and their contents

### ISSUE THREAD

**Issue by anhalu** [slackapi/bolt-python#1191]
I am developing a bot in slack, using the socketmode of slack_bolt. When developing the feature of reading and editing canvas, I encountered the following problems:
![Screenshot 2024-11-01 112126](https://github.com/user-attachments/assets/bdb00401-53e6-4d75-b5f4-3ec8ffd86a5e)

- I have seen the api used for canvas on slack api but it seems to be missing somewhere.
- I want to get the content of an available canvas in slack in the bot's channel, I use client.canvases_edit but I cannot find the canvas id (I have not seen any api providing the vancas id attribute to get it). When I use app.client.canvases_create to create, if the canvas does not exist, it will create a canvas id, but if it does exist, it will not return the canvas id to use for the following api.

My flow wants to be implemented as follows:
user mentions the bot -> then the bot will get the canvas content and return it to the user through some method.
Is there any way that when a user mentions the bot, the bot will get the canvas content to use, or through some channel id?

**Comment by anhalu** [comment]
@seratch  can you help me this case ? Many thanks.

**Comment by seratch** [comment]
Hi @anhalu, thanks for asking the question!

Currently, there isn't a public API available for custom apps to look up canvas IDs. This might change in the future, but we can't predict if or when that will occur. However, for canvas documents linked to a channel, you can check the channel's API response properties. Specifically, the `conversations.list/info` APIs can be used to lookup the full metadata of a channel, and if a canvas is associated with a channel, the response should include `$.channel.properties.canvas.file_id`, which is the canvas document's ID.

The canvas document platform has more private/internal APIs, so additional functionalities may be available in the future. Please feel free to share your needs with our customer support team either via `/feedback` in your corporate Slack workspace or at https://my.slack.com/help/requests/new. Thank you again for using the platform!

**Comment by anhalu** [comment]
@seratch  Thanks a lot for quickly reply!
```
@app.event('app_mention')
def mention_bot(ack, event, say, client, body):
    ack()
    say(f"Hello, <@{event['user']}>!")
    info  = client.conversations_info(channel=event['channel'])
    canvas_file_id = info['channel']['properties']['canvas']['file_id']
    # print(canvas_file_id)
    file_info = client.files_info(file=canvas_file_id)
```
When I use this, I have the file information about the file properties, which includes the paths of the canvas file, title, title_blocks ... How can I get the content blocks in the canvas file like the title blocks. Or is it required to load the content from the url to be able to read it?

**Comment by seratch** [comment]
I do understand the current set of APIs is incomplete for many use cases, but the only available method for fetching the canvas document data is https://api.slack.com/methods/canvases.sections.lookup w/ its criteria parameter.

**Comment by seratch** [comment]
Thank you so much again for taking the time to write in here. As mentioned above, there is not yet sufficient set of APIs for you, but this does not mean more APIs never come. We are unable to tell whether and when those new APIs that are useful for you can come but hope our platform team can deliver such as early as possible. Lete me close this issue for now. If you have more feedback on the feature enhancement idea, please contact our customer support team for it.
