### ISSUE TITLE
Frequent timeouts if calling async functions within an Async Bolt event handler

### ISSUE THREAD

**Issue by Mikkolehtimaki** [slackapi/bolt-python#1201]
Problem: Bolt is not responding to events, unless I send many events. Sending a single event (like messaging a bot) will timeout, unless more events are sent in quick succession (last one will eventually timeout). 

This happens when I make async calls within a Bolt event handler. Timeout happens at `await say(...)`

I am not entirely sure if this is a Bolt, Slack SDK or deployment platform error. I made a similar bug ticket to Slack SDK as the timeouts occurred withing that, but I can reproduce (shown here) the issue with any async call within a Bolt handler.

My Python code that causes the behavior:

```python
    slack_app = slack_bolt.async_app.AsyncApp()
    slack_client = AsyncWebClient(token=os.environ["SLACK_BOT_TOKEN"], timeout=120)

    @slack_app.message()
    async def message(message: dict, say: AsyncSay, ack: AsyncAck):
        """Handle direct messages to the app."""
        logger.info("handling message event!")
        history = [
            SlackMessage(
                user="myname",
                text=message["text"],
                role="user",
            )
        ]
        # this is a wrapper over async Openai client
        a = await answer(history, client=openai_client)
        await say(a)
```
Elsewhere:
```python
        self.app_handler = AsyncSlackRequestHandler(self.slack_app)

        @self.fastapi_app.post("/slack/events")
        async def endpoint(req: Request):
            """Handle Slack requests with Bolt."""
            return await self.app_handler.handle(req)
```

### Reproducible in:

Using Slack Bolt to handle events in an app (deployed to Modal cloud).

#### The `slack_bolt` version

```
slack_bolt==1.20.1
slack_sdk==3.33.1
```

#### Python runtime version

3.11

#### OS info

Debian Slim (Modal Cloud)

#### Steps to reproduce:

Send a message to the bot and wait.

If you keep sending events (like toggle between home or send more messages, it works).

### Expected result:

The bot should respond.

### Actual result:

```
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task cancelling name='Task-428' coro=<AsyncioListenerRunner.run.<locals>.run_ack_function_asynchronously() running at /usr/local/lib/python3.11/site-packages/slack_bolt/listener/asyncio_runner.py:118> wait_for=<Future finished result=[{'family': <AddressFamily.AF_INET: 2>, 'flags': <AddressInfo....RICSERV: 1028>, 'host': '34.204.109.226', 'hostname': 'slack.com', ...}, {'family': <AddressFamily.AF_INET: 2>, 'flags': <AddressInfo....RICSERV: 1028>, 'host': '54.225.153.205', 'hostname': 'slack.com', ...}, {'family': <AddressFamily.AF_INET: 2>, 'flags': <AddressInfo....RICSERV: 1028>, 'host': '3.210.88.6', 'hostname': 'slack.com', ...}, {'family': <AddressFamily.AF_INET: 2>, 'flags': <AddressInfo....RICSERV: 1028>, 'host': '34.193.255.5', 'hostname': 'slack.com', ...}, {'family': <AddressFamily.AF_INET: 2>, 'flags': <AddressInfo....RICSERV: 1028>, 'host': '54.92.199.186', 'hostname': 'slack.com', ...}, {'family': <AddressFamily.AF_INET: 2>, 'flags': <AddressInfo....RICSERV: 1028>, 'host': '34.196.46.202', 'hostname': 'slack.com', ...}, ...]>>
```
leading to
```
ERROR:slack_bolt.AsyncApp:Failed to run listener function (error: coroutine ignored GeneratorExit)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/slack_bolt/listener/asyncio_runner.py", line 118, in run_ack_function_asynchronously
    await listener.run_ack_function(request=request, response=response)
  File "/usr/local/lib/python3.11/site-packages/slack_bolt/listener/async_listener.py", line 119, in run_ack_function
    return await self.ack_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/modal_cloud/slack_chat_bot.py", line 115, in message
    await say(a)
  File "/usr/local/lib/python3.11/site-packages/slack_bolt/context/say/async_say.py", line 57, in __call__
    return await self.client.chat_postMessage(  # type: ignore[union-attr]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/slack_sdk/web/async_client.py", line 2719, in chat_postMessage
    return await self.api_call("chat.postMessage", json=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/slack_sdk/web/async_base_client.py", line 162, in api_call
    return await self._send(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/slack_sdk/web/async_base_client.py", line 191, in _send
    res = await self._request(http_verb=http_verb, api_url=api_url, req_args=req_args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/slack_sdk/web/async_base_client.py", line 209, in _request
    return await _request_with_session(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: coroutine ignored GeneratorExit
```

**Comment by seratch** [comment]
Hi @Mikkolehtimaki, thanks for asking the question. I don't think this is a general issue, so there might be some factor specific to the way you run the app and/or the infrastructure/runtime you're using. Could you try the following steps to narrow down the possible causes and identify the real issue?

1) Does the app exhibit the same behavior on your local machine?
  - If you need a simpler app to test, here's an example: https://github.com/slackapi/bolt-python/blob/main/examples/fastapi/async_app.py
  - Tools like ngrok or Cloudflare Tunnel can help you serve a public Request URL, which forwards requests to your localhost:3000/slack/events

2) If the issue occurs only on your Modal Cloud:
  - Check if there are any restrictions on outgoing HTTP requests from the platform (or by your custom settings).
  - Check if your team has set up a proxy server within the Modal Cloud tenant.

Additionally, you can find several discussions about the issue by searching "RuntimeError: coroutine ignored GeneratorExit" + aiohttp. Some people suggest that a proxy server blocking your outgoing requests could be a cause, although I'm not sure if that's the situation in your case.

**Comment by Mikkolehtimaki** [comment]
Okay it works normally in ngrok and Azure so closing this as a Modal issue.
