### ISSUE TITLE
Support app_uninstalled, tokens_revoked events

### ISSUE THREAD

**Issue by fwump38** [slackapi/bolt-python#121]
One of the built-in Global Middleware (MultiTeamsAuthorization) calls the authorize function for each request. This, expectedly fails for `app_uninstalled` and `tokens_revoked` events but they should still be allowed to be processed for clean-up purposes (removing rows from DB, etc)

#### The `slack_bolt` version

slack-bolt==0.9.3b0
slack-sdk==3.0.0b0

#### Python runtime version

Python 3.9.0

#### OS info

ProductName:    Mac OS X
ProductVersion: 10.15.7
BuildVersion:   19H2
Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1. Install an App to a workspace using OAuth (for multi-team authorization)
2. Subscribe to `app_uninstalled` or `tokens_revoked` events
3. Create function to listen for either of those events
4. Uninstall the App from the Manage Apps page

### Expected result:

The middleware should allow passing to the next middleware even if the AuthorizeResult is None so that cleanup can be done when a user uninstalls the app

### Actual result:

```
INFO 2020-10-21 15:57:14,508 basehttp 15742 123145406881792 "POST /slack/events HTTP/1.1" 200 52
DEBUG 2020-10-21 15:59:50,150 app 15742 123145406881792 Applying slack_bolt.middleware.ssl_check.ssl_check.SslCheck
DEBUG 2020-10-21 15:59:50,150 app 15742 123145406881792 Applying slack_bolt.middleware.request_verification.request_verification.RequestVerification
DEBUG 2020-10-21 15:59:50,150 app 15742 123145406881792 Applying slack_bolt.middleware.authorization.multi_teams_authorization.MultiTeamsAuthorization
DEBUG 2020-10-21 15:59:50,173 app 15742 123145423671296 Applying slack_bolt.middleware.ssl_check.ssl_check.SslCheck
DEBUG 2020-10-21 15:59:50,173 app 15742 123145423671296 Applying slack_bolt.middleware.request_verification.request_verification.RequestVerification
DEBUG 2020-10-21 15:59:50,173 app 15742 123145423671296 Applying slack_bolt.middleware.authorization.multi_teams_authorization.MultiTeamsAuthorization
DEBUG 2020-10-21 15:59:50,546 authorize 15742 123145406881792 The stored bot token for enterprise_id: None team_id: TJ4GH3ZRC is no longer valid. (response: {'ok': False, 'error': 'account_inactive'})
ERROR 2020-10-21 15:59:50,546 multi_teams_authorization 15742 123145406881792 auth.test API call result is unexpectedly None
DEBUG 2020-10-21 15:59:50,549 authorize 15742 123145423671296 The stored bot token for enterprise_id: None team_id: TJ4GH3ZRC is no longer valid. (response: {'ok': False, 'error': 'account_inactive'})
ERROR 2020-10-21 15:59:50,555 multi_teams_authorization 15742 123145423671296 auth.test API call result is unexpectedly None
```

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Thanks a lot for this insightful feedback! 

You are right about this. The use case is not covered by Bolt framework yet. As a workaround, you can bypass the built-in middleware by implementing your own `authorize` function. 

However, we’d like to resolve this issue by providing and/or changing a built-in solution. One thing we need to consider before moving this forward is that this is not specific to Bolt for Python but the change affects the design across three Bolt implementations. So, I will discuss this with the maintainer team, and then will share the result here.

**Comment by seratch** [comment]
We decided to go with the following change to all Bolt frameworks (Node, Python. JVM):

The built-in authorization middleware (both single team & multi teams) should skip calling `auth.test` for these two events (`app_uninstalled` , `tokens_revoked`). This means AuthorizeResult is an empty object only in this case.

**Comment by seratch** [comment]
It seems https://github.com/slackapi/bolt-js/issues/673 is related to this.

**Comment by stevengill** [comment]
Ahh good catch on that bolt-js issue being related to this.
