### ISSUE TITLE
Is Slack planning to develop a Slack Bolt Rust library?

### ISSUE THREAD

**Issue by kyaryunha** [slackapi/bolt-python#1225]
Is Slack planning to develop a Slack Bolt Rust library?

I'm curious if there are any plans.

I want to use Slack Bolt, but I'm worried because there is no official slack-bolt rust library.

### Category (place an `x` in each of the `[ ]`)

* [ ] **slack_bolt.App** and/or its core components
* [ ] **slack_bolt.async_app.AsyncApp** and/or its core components
* [ ] Adapters in **slack_bolt.adapter**
* [x] Others

**Comment by seratch** [comment]
Hi @kyaryunha, thanks for asking the question! Unfortunately, we don't have any plans to add more languages to Bolt family. There should be community libraries for Rust, so please try those out instead. Thanks again for your interest in Slack platform!
