### ISSUE TITLE
top-level constructor arg "authorize" is not respected when having "oauth_flow" together

### ISSUE THREAD

**Issue by seratch** [slackapi/bolt-python#123]
(Filling out the following details about bugs will help us solve your issue sooner.)

#### The `slack_bolt` version

0.9.4b0

#### Python runtime version

any

#### OS info

any

#### Steps to reproduce:

```python
app = App(
    oauth_flow=oauth_flow,
    authorize=my_authorize_func # this won't be respected
)
```

### Expected result:

The argument is used or the framework should tell something if it has to ignore it.

### Actual result:

The argument is not used.

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by stevengill** [comment]
in bolt-js, we throw an error if they provide both oauth flow stuff + authorize.

**Comment by seratch** [comment]
Thanks. Bolt Python can align with it.
