### ISSUE TITLE
Failed to find bot installation data

### ISSUE THREAD

**Issue by Redithion** [slackapi/bolt-python#134]
I'm using Bolt with Flask and I can't make it work. I'm using it with passenger and nginx. I've alread configured /slack/events but when I try to make the app react to `app_home_opened` I get this:

> App 5912 output: [ pid=5912, time=2020-10-28 22:20:40,851 ]: Failed to find bot installation data for enterprise: none, team: T027KNX9B: [Errno 2] No such file or directory: './data/none-T027KNX9B/bot-latest'
App 5912 output: [ pid=5912, time=2020-10-28 22:20:40,851 ]: auth.test API call result is unexpectedly None

### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version

slack-bolt==0.9.5b0
slack-sdk==3.0.0rc1

#### Python runtime version

Python 3.6.8

#### OS info

Ubuntu 18.04

#### Steps to reproduce:

App code:
```
import logging
import os
from slack_bolt import App
from slack_bolt.adapter.flask import SlackRequestHandler
from slack_bolt.oauth.oauth_settings import OAuthSettings
from slack_sdk.oauth.installation_store import FileInstallationStore
from slack_sdk.oauth.state_store import FileOAuthStateStore

logging.basicConfig(level=logging.DEBUG)

oauth_settings = OAuthSettings(
    client_id=os.environ["SLACK_CLIENT_ID"],
    client_secret=os.environ["SLACK_CLIENT_SECRET"],
    scopes=["channels:read", "groups:read", "chat:write"],
    redirect_uri=None,
    install_path="/slack/install",
    redirect_uri_path="/slack/oauth_redirect",
    state_store=FileOAuthStateStore(expiration_seconds=600, base_dir="./data")
)

app = App(
    signing_secret=os.environ["SLACK_SIGNING_SECRET"],
    installation_store=FileInstallationStore(base_dir="./data"),
    oauth_settings=oauth_settings
)

@app.middleware  # or app.use(log_request)
def log_request(logger, body, next):
    logger.debug(body)
    return next()


@app.event("app_mention")
def event_test(body, say, logger):
    logger.info(body)
    say("What's up?")


@app.event("message")
def handle_message():
    pass


from flask import Flask, request

BotApp = Flask(__name__)
handler = SlackRequestHandler(app)


@BotApp.route("/slack/events", methods=["POST"])
def slack_events():
    return handler.handle(request)


@BotApp.route("/slack/install", methods=["GET"])
def install():
    return handler.handle(request)


@BotApp.route("/slack/oauth_redirect", methods=["GET"])
def oauth_redirect():
    return handler.handle(request)


@app.event("app_home_opened")
def open_modal(client, event, logger):
  try:
    # view.publish is the method that your app uses to push a view to the Home tab
    client.views_publish(
      # the user that opened your app's app home
      user_id = event["user"],
      # the view object that appears in the app home
      view={
        "type": "home",
        "callback_id": "home_view",

        # body of the view
        "blocks": [
          {
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": "*Welcome to your _App's Home_* :tada:"
            }
          },
          {
            "type": "divider"
          },
          {
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": "This button won't do much for now but you can set up a listener for it using the `actions()` method and passing its unique `action_id`. See an example in the `examples` folder within your Bolt app."
            }
          },
          {
            "type": "actions",
            "elements": [
              {
                "type": "button",
                "text": {
                  "type": "plain_text",
                  "text": "Click me!"
                }
              }
            ]
          }
        ]
      }
    )
  except Exception as e:
    logger.error(f"Error opening modal: {e}")

if __name__ == "__main__":
	BotApp.run()

```

### Expected result:

app reacted to the event

### Actual result:

It fails, I think somehow it's not saving the OAuth data but I don't know why

**Comment by seratch** [comment]
Hi @Redithion, I guess you've installed the Slack app from the Install button in your Slack app configuration page: **Settings** > **Install App** (The URL should be `https://api.slack.com/apps/{your app id}/install-on-team`) and then you're trying to get the OAuth enabled app work with the workspace.

An installation from the admin page works only with a single bot token. In this case, you can pass as `token` in the `App`'s constructor args in the way the Getting Started guide does. https://slack.dev/bolt-python/tutorial/getting-started

If you use the client_id/client_secret for app initialization, the app requires Slack's OAuth flow installation, not the easy way from the admin page. Installing the app into your workspace from `https://{your domain}/slack/install` beforehand. By completing this process, the app can store issued bot token in your local file system.

**Comment by Redithion** [comment]
Thanks for your answer!
I'm just starting with this and I forgot to mention that when I tried `/slack/install` I got this:
![image](https://user-images.githubusercontent.com/8549367/97525095-daabc600-1984-11eb-889f-36c62553faf1.png)
I did install it in Settings > Install App (I have the Bot User OAuth Access Token)

Also, I tried changing the authentication method following the tutorial but I get

> App 11766 output: [ pid=11766, time=2020-10-29 00:24:18,026 ]: As you gave `installation_store`/`authorize` as well, `token` will be unused.

I don't mind using the Bot Token, I will only use this app internally.

**Comment by seratch** [comment]
Thanks for sharing this. Probably, the reason why you get the invalid_browser error is that you are not using https URL.

> As you gave installation_store/authorize as well, token will be unused.

This means your local host has the env variable named `SLACK_BOT_TOKEN` as well. You can unset the env variable if you don't need it.

Also, if you run your app only for a single workspace, it's totally fine to skip handling the OAuth flow (=this means simply initializing your app with only token and signing secret).

**Comment by Redithion** [comment]
Good to know about https (a fight for another day though)
>App 11766 output: [ pid=11766, time=2020-10-29 00:24:18,026 ]: As you gave `installation_store`/`authorize` as well, `token` will be unused.

You were right about this, I am not longer setting that variable and that message does not show anymore, but...I still get this:

>App 13019 output: [ pid=13019, time=2020-10-29 00:38:20,165 ]: Failed to find bot installation data for enterprise: none, team: T027KNX9B: [Errno 2] No such file or directory: '/home/ubuntu/.bolt-app-installation/none-T027KNX9B/bot-latest'
App 13019 output: [ pid=13019, time=2020-10-29 00:38:20,165 ]: auth.test API call result is unexpectedly None

I've just figured that I also need to remove `SLACK_CLIENT_SECRET` 

Thanks for all your help, I REALLY appreciate it

**Comment by Techno-Disaster** [comment]
I am getting the same issue today, should I open a new issue?    
My app installation becomes invalid after a few hours
Is it because after some time heroku sleeps or because heroku filesystems are not permanent? I am able to use the bot again ones i install via my url/slack/install.

I currently have the following env variables set: 

SLACK_CLIENT_ID
SLACK_CLIENT_SECRET
SLACK_SCOPES
SLACK_SIGNING_SECRET

Do i need to pass something like 
oauth_settings = OAuthSettings(
    ...
)

when I initialize the app too? I haven't exactly found the documentation for this.

**Comment by seratch** [comment]
@Techno-Disaster 
>should I open a new issue?

No, I don't think so. This is a simple question I can reply here.

>Is it because after some time heroku sleeps or because heroku filesystems are not permanent?

The Heroku filesystem is ephemeral. Consider using database or storage service for storing installation data ([available options](https://github.com/slackapi/python-slack-sdk/tree/v3.2.1/slack_sdk/oauth/installation_store)).
See also: https://help.heroku.com/K1PPS2WM/why-are-my-file-uploads-missing-deleted

**Comment by espdev** [comment]
@seratch 

Hi, 
I have the same issues for my FastAPI transport based async app with enabled OAuth and public distribution:

1. Slack button/URL from App settings page does not work
2. I get `Failed to find an installation data...` log message, but the app is authorizing and working in any workspace

I have setup my app for using OAuth something like this:

```python
oauth_settings = AsyncOAuthSettings(
    client_id=secrets.slack_client_id,
    client_secret=secrets.slack_client_secret,
    scopes=scopes,
    user_scopes=[],
    redirect_uri=None,
    install_path=oauth_config.install_path,
    redirect_uri_path=oauth_config.redirect_uri_path,
    installation_store=FileInstallationStore(
        base_dir=installation_base_dir,
        client_id=secrets.slack_client_id,
    ),
    state_store=FileOAuthStateStore(
        expiration_seconds=oauth_config.state_store_expiration_seconds,
        base_dir=installation_base_dir,
        client_id=secrets.slack_client_id,
    ),

...

app = App(
    ...
    oauth_settings=oauth_settings,
    ...
)

...

@api.get(oauth_settings.install_path)
async def install(req: Request):
    return await app_handler.handle(req)

@api.get(oauth_settings.redirect_uri_path)
async def oauth_redirect(req: Request):
    return await app_handler.handle(req)

```

I can install my app in any workspace but only use URL button from my `my.app.domain/install` path, the button from App settings does not work. I get an error: "invalid browser". The url from App settings does not have `state` query parameter. The url from `/install` path has something like this: `https://slack.com/oauth/v2/authorize?state=638c1eb1-d6d1-43b0-8a88-9d605d2c4802`

For every request from Slack I get the warning in the logs: `Failed to find an installation data...` with non-existing file: `installer-U02U97PGYBZ-latest` for example, but in the directory I have the file with other ID `installer-...-latest` and the app works.

I do not quite understand what is going on. Could you explain what I'm doing wrong?
Thanks!

**Comment by gfang-work** [comment]
Hi @seratch and @Redithion , I wonder if there is a way to install an org-wide app via console (api.slack.com/apps) and still authenticate with OAuth (using `OAuthSettings`) with Bolt framework?

**My main objective is to enable built-in token rotation** without the hustle of going through OAuth programmatically because my app is org-wide and will only be installed once by an org owner in an enterprise grid.

THANK YOU!

**Comment by seratch** [comment]
@gfang-work Installation from the admin page does not support token rotation. To use token rotation, your app needs to run the OAuth flow endpoints, and an installing user has to go through the OAuth flow.

**Comment by gfang-work** [comment]
@seratch This is a light-speed response.... I really appreciate it. (And sorry I created and deleted a dup question issue)

Is that still true when the installation through admin page is done via OAuth? It's just that the OAuth flow wasn't initiated by the code. Also, can the `installation_store` be AWS secret manager?

**Comment by seratch** [comment]
@gfang-work 
>Is that still true when the installation through admin page is done via OAuth? It's just that the OAuth flow wasn't initiated by the code. 

Yes, the process also generates OAuth access tokens but when you install your app from the button in the admin page, the Slack server-side does everything for you, so that your Bolt app's OAuth flow is never used. If your app implement the OAuth flow, I don't recommend using the installation flow from the admin page. Such an installation won't be managed by the `InstallationStore`.

>Also, can the installation_store, an argument of OAuthSettings, be AWS secret manager?

We don't have any built-in support but if you implement a kind of adapter between the two (meaning InstallationStore and AWS Secret Manager). That being said, since we are not AWS experts, it may be possible. But we are unable to help you regarding this topic.
