### ISSUE TITLE
Examples for sending messages outside of the response flow

### ISSUE THREAD

**Issue by jensenbox** [slackapi/bolt-python#135]
There is some information that indicates to use the WebClient that is part of the Bolt app however under most contexts the WebClient has been initialized with an empty token (understandably a reasonable situation).

What is unknown is the appropriate method to acquire a given installation (the `xoxb-`) token as well as initialize either a new WebClient or use the client attached to the Bolt application.

### The page URLs

* https://slack.dev/bolt-python/concepts#message-sending

## Requirements

Adding additional examples for sending a message that is out of the normal response flow would be great. A simplistic example would be if a user makes a payment on a website, a message would be sent to a given installation and channel indicating the event happened.

**Comment by seratch** [comment]
In this scenario, Bolt can help you only for installation data management. You can reuse your `InstallationStore` in the payment flow. If you build an app using Flask, pseudo code can be as below. The important thing is that you can implement the payment side as a simple web app (see the `payment` method in the code)

```python
from slack_bolt import App
from slack_bolt.adapter.flask import SlackRequestHandler

app = App()

@app.event("message")
def handle_message():
    pass

from flask import Flask, request, session, make_response

flask_app = Flask(__name__)
handler = SlackRequestHandler(app)

# Handles requests from Slack API server
@flask_app.route("/slack/events", methods=["POST"])
def slack_events():
    return handler.handle(request)

# Starts Slack OAuth (=app installation) flow
@flask_app.route("/slack/install", methods=["GET"])
def install():
    return handler.handle(request)

# Handles the redirection from Slack's OAuth flow
@flask_app.route("/slack/oauth_redirect", methods=["GET"])
def oauth_redirect():
    return handler.handle(request)

# Plain Flask routes to handle your own payment process
@flask_app.route("/payments/xxx", methods=["POST", "GET"])
def payment():
    # Assuming the same user installed the Slack app using the same browser
    team_id = session.get("slack_team_id")
    bot = app.installation_store.find_bot(enterprise_id=None, team_id=team_id)
    app.client.chat_postMessage(token=bot.bot_token, text="Thanks!")
    return make_response("Thanks!", 200)
```

We're not planning to add this type of content in the document website so far but I'm happy to help you out if you need further info.

**Comment by jensenbox** [comment]
Thanks!

The missing link for me was the WebClient call. Every time I have seen the method called it had already been initialized with a `token` - I was unaware that you could call `chat_postMessage` with a token parameter on it.

**Comment by andrewhharmon** [comment]
I'm trying to send a message from a 3rd part app, I'm trying to use a plain Flask route like you have here and use `app.client.chat_postMessage`. That works fine, but there is some metadata i'd like to pass along with the message so that when someone clicks a button in the message, my app can respond to the event and have access to that metadata. I was thinking i could add that metadata to the context but that isn's available with `app.client.chat_postMessage`. Any idea how to pass this kinda of data into a message and retrieve it upon an event action?

**Comment by seratch** [comment]
@andrewhharmon The recommended way for your use case would be to include the metadata in the `value` property of the button block element. You can set any string (up to 2K characters) to the property. https://api.slack.com/reference/block-kit/block-elements#button

**Comment by andrewhharmon** [comment]
Excellent suggestion! Thanks for the quick response.

**Comment by andrewhharmon** [comment]
@seratch i'm getting an error when my value is over 75 characters. (not 2k) this makes it a bit impractical to send data this way. Is there another workaround?

```
slack_sdk.errors.SlackObjectFormationError: value attribute cannot exceed 75 characters
```

**Comment by andrewhharmon** [comment]
interesting, it's validation being done from the slack_sdk... so i decided to skip using that and just pass a list of blocks as dicts instead of slack_sdk objects. I get a different limitation.

```
The server responded with: {'ok': False, 'error': 'invalid_blocks', 'errors': ['must be less than 151 characters [json-pointer:/blocks/0/elements/0/options/2/value]'], 'response_metadata': {'messages': ['[ERROR] must be less than 151 characters [json-pointer:/blocks/0/elements/0/options/2/value]']}}
```

so better, but still not 2k chars. Am I doing something wrong?

**Comment by seratch** [comment]
@andrewhharmon 
The issue has been fixed in `slackclient` v2.4.0: https://github.com/slackapi/python-slack-sdk/pull/514 
Thus, upgrading the `slackclient` version to newer (the latest is 2.9.3) should help!

**Comment by seratch** [comment]
> json-pointer:/blocks/0/elements/0/options/2/value

The value of an option has a different max length rule. 2K is not a universal length.

**Comment by andrewhharmon** [comment]
I'm a bit confused. I'm not using the `slackclient` but using `app.client.chat_postMessage` from the slack_bolt library. Does this rely on `slackclient` in the background somehow? I'm not sure how to update that. 

pip freeze shows me
```
slack-bolt==1.7.0
slack-sdk==3.8.0
```

**Comment by seratch** [comment]
@andrewhharmon 
>Does this rely on slackclient in the background somehow? 

No, it doesn't.

By the way, this issue is already closed. If you have more questions, can you create a new issue in the python-slack-sdk project from [here](https://github.com/slackapi/python-slack-sdk/issues/new/choose)? Sharing details like minimum working example reproducing your issue would be helpful for understanding what it is. Thanks!
