### ISSUE TITLE
Document how to override the success handler on CallbackOptions

### ISSUE THREAD

**Issue by jensenbox** [slackapi/bolt-python#137]
I have a multi-tenant application whereby an account can be associated to a given Slack Team which allows events generated on the account to send events to the Team.

To make the association, I need to start the OAuth flow from the web application side and finish by making the association to the account.

I have been looking for ways to pass data into the start of the OAuth flow but have resolve that none of the objects (`Installation` nor `Bot`) support additional data to be carried through so I am resolving to overriding the `success` class variable.

I have a complete Rube Goldberg method of overriding the CallbackOptions but wanted to ask the authors on the prescribe way to accomplish the override. In reality, all I need is an additional optional function to provide during the success flow - one that sends the current request and the installation so that I can associate the installation with the account found in the request. There already is an easy mechanism to override the `success_url` - I would propose a `success_callable` or something to that effect (if the override is not easy)

### Category (place an `x` in each of the `[ ]`)

* [ X] **slack_bolt.App** and/or its core components
* [ ] **slack_bolt.async_app.AsyncApp** and/or its core components
* [ ] Adapters in **slack_bolt.adapter**
* [ ] Others

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @jensenbox, thanks for this feedback! I've published a pull request #138 that brings a solution for your use case. Let me know if I miss something in your feedback.
