### ISSUE TITLE
OAuth docs say slack/install path displays Add to Slack button

### ISSUE THREAD

**Issue by stevengill** [slackapi/bolt-python#140]
OAuth document says `slack/install` will display an *Add to Slack* button. But in my tests, it actually redirects directly to request permission / install app page. In bolt-js, we do get the *Add to Slack* button. 

We either need to update the document removing reference to the Add to Slack button, or update the oauth implementation to mimic bolt-js and actually display an Add to Slack button. 

### The page URLs

https://slack.dev/bolt-python/concepts#authenticating-oauth

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Thanks, I've got the same feedback before (probably not here but somewhere in the community) but I completely forgot to add a task to this tracker at that time.

> update the oauth implementation to mimic bolt-js and actually display an Add to Slack button

The document were borrowed from Bolt for JS. I think we should change the behavior.
