### ISSUE TITLE
External Account Connection

### ISSUE THREAD

**Issue by jensenbox** [slackapi/bolt-python#144]
If I have a service like Intercom or PagerDuty which have a "corporate service accounts" that have multiple users in the account and I want the "corporate service account" to interact with Slack how do I associate a corporate service account to a completed OAuth flow?

I understand how to initiate the OAuth flow with Bolt and how it saves the data in the Installation, Bot and State tables - what I seem to be missing is how to make the association with the account that initiated the OAuth flow.

I looked in the BoltRequest and the BoltResponse but there is no way to pass in the data of the "corporate account ID".

Effectively, I would like to be able to associate the corporate account row in my database to an installation ID but I cannot see where in Bolt I would get that information to be able to make that association.

I am more than happy to provide more information or submit code examples of what I am looking to achieve.

Thanks!

**Comment by seratch** [comment]
How about doing as below?

As I answer to your question before, you can use callback functions to do extra when an installation is completed. The `success` function associates the installation with the corresponding row in your existing database tables.

`BoltRequest` represents an incoming request (and its payload) from the Slack API servers. So, the object does not contain any data that is specific to your backends. Instead, you can attach any data into `BoltContext` object. The `bind_corporate_account` method is a simple global middleware example. You can do the similar in your apps.

```python
def success(args: SuccessArgs) -> BoltResponse:
    # associate the installation with the corresponding corp account:
    account_service.associate_slack_account(args.installation)
    return args.default.success(args)

def failure(args: FailureArgs) -> BoltResponse:
    return args.default.failure(args)

app = App(
    oauth_settings=OAuthSettings(
        callback_options=CallbackOptions(success=success, failure=failure),
    ),
)

@app.use  # or @app.middleware
def bind_corporate_account(next, context: BoltContext):
    account = account_service.find(context.enterprise_id, context.team_id, context.user_id)
    context["corporate_account_id"] = account.get("corporate_account_id")
    next()

@app.command("/my-corp-account")
def run_ops(ack, context):
    corp_id = context.get("corporate_account_id")
    if corp_id:
        ack(f"Here is your corp account id: {corp_id}")
    else:
        ack("Your Slack account is not associated with your corp account yet. Visit: https://www.example.com")
```

**Comment by jensenbox** [comment]
Thank you for your detailed response. I am understanding the part on how to pull out the data using the context. However the difficulty still remains in the `account_service.associate_slack_account(args.installation)` portion.

At that stage of the code, there is no available information to indicate the current corporate account that needs to be associated.

I have been pulling the requests apart in Intercom and it appears that they transmit the information in the state - as an example state `102579:wbqeymqr:3824235` - There are two random numbers on either side of the `wbqeymqr` which is my Intercom instance.

I understand that Bolt is crafting UUID4 for the state generation and validation. I am wondering if it would be a good place to either add to the end of the UUID in a parseable format or just allow the developer to override the state generator during the OAuth startup so that it would potentially be available at the time of state `consume`.

Below is an entirely hypothetical example - notice the inclusion of the new property `state`:

```
def success(args: SuccessArgs) -> BoltResponse:
    # associate the installation with the corresponding corp account:
    account_service.associate_slack_account(args.installation, args.state)
    return args.default.success(args)
```

This would allow for the developer to do whatever they wanted with the state object as it was originally generated by allowing the passing in of a crafted state in the `oauth_flow.handle_installation` method.

Perhaps passing it back from https://github.com/slackapi/bolt-python/blob/main/slack_bolt/oauth/oauth_flow.py#L214 and then injecting into https://github.com/slackapi/bolt-python/blob/main/slack_bolt/oauth/oauth_flow.py#L269

That said, I am totally open to any other means of deriving the "corporate account id" during the `success` method.

Thanks again!

(FYI I will be in the webmeeting on Nov 11)

**Comment by seratch** [comment]
You can implement your own [OAuthStateStore](https://github.com/slackapi/python-slack-sdk/blob/v3.0.0rc1/slack_sdk/oauth/state_store/state_store.py) and it should work. With this, your success callback handler can access the value in `BoltRequest`'s data by `args.request.query.get("state")` (by the way, strictly speaking, my previous comment was incorrect. in this case, the request is an end-user's browser request. So, you can set values in cookies or state param. Sorry about the misinformation).

 Another option would be setting another cookie at the timing of `/slack/install`'s redirection for associating other external service (Intercom here) specific data and accessing the data in success callback handler. Either is fine.

> FYI I will be in the webmeeting on Nov 11

Thanks for joining the webinar! As I live in Asia, I won't be there live but hope you will enjoy the session.

**Comment by seratch** [comment]
Thanks for your contribution at https://github.com/slackapi/python-slack-sdk/pull/871 . If I understand the current state of the issue correctly, we do not have further action items here. Let me close this now but if you have anything to follow up, please feel free to write in here or create a new issue.
