### ISSUE TITLE
Unable to subscribe to events

### ISSUE THREAD

**Issue by BruceP99166** [slackapi/bolt-python#145]
I'm trying to follow the directions in Building an app with Bolt for Python ( https://api.slack.com/start/building/bolt-python#start) but am unsuccessful in subscribing to events.

The Bolt app is running; shows the message "Bolt app is running! (development server)" on the python console.

It's not clear what is needed to obtain verification of the ngrok url.

Working on Ubuntu 18.04.

### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version

slack-bolt==0.9.6b0
slack-sdk==3.0.0rc1
slackclient==2.9.3

#### Python runtime version

Python 3.8.0

#### OS info

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1. Follow the steps in Getting Started down to "Subscribing to Events":
- App code 
```import os
# Use the package we installed
from slack_bolt import App

# Third-party imports
from dotenv import load_dotenv

# Environment variables
dirpath = os.path.dirname(os.path.abspath(__file__))
config_path = os.path.join(dirpath, "config", "account_creation_notify_config.txt")
load_dotenv(dotenv_path=config_path)

try:
    SLACK_BOT_TOKEN = os.environ["SLACK_BOT_TOKEN"]
except KeyError:
    print("There is a problem with the SLACK_BOT_TOKEN environment variable.")
    exit(1)

try:
    SLACK_SIGNING_SECRET = os.environ["SLACK_SIGNING_SECRET"]
except KeyError:
    print("There is a problem with the SLACK_SIGNING_SECRET environment variable.")
    exit(1)

# Initializes your app with your bot token and signing secret
app = App(
    token=SLACK_BOT_TOKEN,
    signing_secret=SLACK_SIGNING_SECRET
)

# Start your app
if __name__ == "__main__":
    a = int(os.environ.get("PORT", 3000))
    app.start(port=int(os.environ.get("PORT", 3000)))
```
2. Enter the ngrok url in Request URL.  

### Expected result:

Challenge response ok and URL accepted to receive Slack events

### Actual result:

Challenge response is "Your URL didn't respond with the value of the challenge parameter." 
The ngrok dashboard shows a response of 404 Not Found to the challenge request.

Bolt app and ngrok dashboard
![Bolt app   ngrok dashboard](https://user-images.githubusercontent.com/17090922/98414622-553dab00-2041-11eb-9112-3fa90eda5dd5.PNG)

Slack app event subscription
![Slack event subscription](https://user-images.githubusercontent.com/17090922/98414673-6c7c9880-2041-11eb-90df-9e13d456a6fa.PNG)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @BruceP99166, thanks a lot for trying Bolt for Python out! It might be a bit confusing but as mentioned in the document you mentioned,

>By default Bolt for Python listens for all incoming requests at the /slack/events route, so for the Request URL you can enter your ngrok URL appended with /slack/events.

The Request URL needs to be `https://{your subdomain}.ngrok.io/slack/events`. The cause of the 404 error is that your Request URL is missing the path: `/slack/events`.

**Comment by BruceP99166** [comment]
Hi seratch,
Thanks, that worked.  Thanks much for your assistance.

BruceP
