### ISSUE TITLE
Duplicate requests from Slack for user input

### ISSUE THREAD

**Issue by haggaret** [slackapi/bolt-python#149]
My apologies if the answer to this exists somewhere already - it's possible I'm missing something obvious.

Created slack app and subscribed to various events including:
- app_home_opened
- app_mention
- message.im

Configured a request URL (that has been verified) that points to an AWS API Gateway, which ultimately forwards the requests onto a lambda function. Lambda function is set up as a bolt app - not much to it at this point - but in general this setup works. Lambda function code is similar to the example code here: 

https://github.com/slackapi/bolt-python/blob/main/examples/aws_lambda/aws_lambda.py

If the incoming request to my lambda results in an operation that takes no time, and the response goes back quick enough, there is no issue. However, if the processing of the request take too long (longer than the 3 seconds I have to respond) then I end up getting duplicate messages sent in from slack. This is apparently expected - retries from the slack side. Makes sense, but is causing me no end of grief.

I *thought* that if I used the ack() method after receiving the request, that this would alleviate the problem, but it seems an ack is not a response - they are distinct.

So, my question is - how do I respond within 3 seconds if the processing of the request is going to take me longer? Should I spawn another lambda function to do the processing and then respond back immediately?

I had previously found another implementation where there was a 'generic webhook to event bridge' lambda behind the API gateway, that would basically do just that - take the request, send it onto EventBridge, and immediately reply back. Then there was another lambda (or lambdas) that would pull the events off the EventBridge and process them.

How are others handling this?

Thanks

**Comment by seratch** [comment]
@haggaret Great question! Take a look at lazy listener function feature. The feature enables you to run multiple async functions with the same set of inputs.

* https://slack.dev/bolt-python/concepts#lazy-listeners
* https://github.com/slackapi/bolt-python/blob/v1.0.0/examples/aws_lambda/lazy_aws_lambda.py

**Comment by haggaret** [comment]
@seratch Thanks for the quick reply on this. I *think* I've implemented things properly (based on the examples in the pages you referenced) - I'm no longer getting the duplicate incoming messages to my lambda, which is great, but I don't seem to be able to send anything back using the respond method like in the example - or at least it doesn't look like the messages are making it back to slack.

**Comment by haggaret** [comment]
Actually, perhaps I'm just confused about respond() - in my case, I'm not responding to a command, I'm keying off a message, so I think I just need to use client.chat_postMessage

**Comment by seratch** [comment]
@haggaret `respond` method is available to use only when a payload contains a `response_url` in it. In the case of end-user interactions like slash commands, shortcuts, button clicks, and so on, `response_url` exists in a payload. By contrast, in Events API payloads, `response_url` does not exist as it is not a direct user action. So, you can use `say()` method or `client` (WebClient) to post a message in a channel/DM.

see also:
* https://api.slack.com/interactivity/handling#message_responses
* https://slack.dev/bolt-python/concepts#action-respond

**Comment by haggaret** [comment]
@seratch Yeah, thanks for that. Clearly I was confused - seem to be in business now - thanks for the help!

**Comment by seratch** [comment]
It was my pleasure helping you!
