### ISSUE TITLE
Code snippet error in api.slack.com tutorial

### ISSUE THREAD

**Issue by GCCree** [slackapi/bolt-python#150]
### Reproducible in:

```bash
slack-bolt==1.0.0
slack-sdk==3.0.0
Python 3.8.2
Microsoft Windows [Version 10.0.18363.1198]
```

#### The Slack SDK version

slack-bolt==1.0.0
slack-sdk==3.0.0

#### Python runtime version

Python 3.8.2

#### OS info

Microsoft Windows [Version 10.0.18363.1198]

#### Steps to reproduce:

Follow this guide: https://api.slack.com/start/building/bolt-python

### Expected result:

Opening the Home tab should result in Home tab being published to.

### Actual result:

Home tab is not published to. Instead, receive an error:
Error opening modal: 'WebClient' object has no attribute 'view_publish'

**Comment by seratch** [comment]
As the fix has been deployed, let me close this issue now. Thanks again for reporting this!

**Comment by GCCree** [comment]
`def update_home_tab(client, event, logger)` needs a colon at the end

**Comment by seratch** [comment]
Ah, you're right. I will send another fix for it.

**Comment by seratch** [comment]
The fix has been deployed. Thanks!
