### ISSUE TITLE
examples for shortcuts

### ISSUE THREAD

**Issue by bmosley** [slackapi/bolt-python#151]
I'd like to see an example of how to properly call shortcuts. the website shows to use `@app.shortcut("open_modal")` but cannot get it to properly work

**Comment by seratch** [comment]
@bmosley If you are asking the steps to configure a global shortcut:

Go to your Slack app's configuration page (the URL should be `https://api.slack.com/apps/{your app's ID}/interactive-messages`) and configure a global shortcut with Callback ID `open_modal`. Then, install the app into your Slack workspace. 

<img width="600" src="https://user-images.githubusercontent.com/19658/99628846-54157080-2a7a-11eb-8479-8c3f9acb7ec5.png">

After doing these, you will find the shortcut in the shortcut menu list.

<img width="600" src="https://user-images.githubusercontent.com/19658/99629086-bec6ac00-2a7a-11eb-81c8-69b11e33393f.png">

If you've already configured a shortcut and you're asking a question about how to receive payloads from Slack, let us know more details. Do you receive incoming requests from Slack when you run a global shortcut? What do you see in the console logs?

**Comment by bmosley** [comment]
Thanks @seratch, I think I was confusing `global_shortcut` with `shortcut`. I assume that works on only message level shortcuts?

**Comment by seratch** [comment]
`app.shortcut` should work for both (global & message shortcuts) as long as you set a valid `callback_id`.

**Comment by bmosley** [comment]
I see. This doesn't seem to work for me. I can get it working fine (sometimes) with non-global but globals don't seem to work.

**Comment by bmosley** [comment]
when run from the global shortcut menu
`ERROR:slack_bolt.App:Failed to run listener function (error: respond is unsupported here as there is no response_url)
Traceback (most recent call last):
  File "/Users/local/slack_test/env/lib/python3.8/site-packages/slack_bolt/listener/thread_runner.py", line 100, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/local/slack_test/env/lib/python3.8/site-packages/slack_bolt/listener/custom_listener.py", line 46, in run_ack_function
    return self.ack_function(
  File "app/app.py", line 150, in open_crappy_modal
    respond(
  File "/Users/local/slack_test/env/lib/python3.8/site-packages/slack_bolt/context/respond/respond.py", line 47, in __call__
    raise ValueError("respond is unsupported here as there is no response_url")
ValueError: respond is unsupported here as there is no response_url
`

**Comment by seratch** [comment]
Ah, yes, global shortcuts do not provide `response_url` as it can be triggered not only in channel but also anywhere (e.g., search bar, all unread view, threads view, and so on) in Slack. `response_url` is only available when your app receives user interactions that always happen in a channel (or DM).

Unfortunately, just changing the decorator may not work for some cases as the structure of payloads varies among features (slash commands, global shortcuts, message shortcuts, block actions, and any others). So, if you switch the decorator, check the data in `body`, `payload` (and its aliases like `command`, `action` etc).

**Comment by bmosley** [comment]
ok got it! that makes more sense, thank you! and also thank you for working on Bolt Python 👍
