### ISSUE TITLE
Input validation after view submission

### ISSUE THREAD

**Issue by haggaret** [slackapi/bolt-python#156]
Set up is AWS Lambda function using Lazy Listeners (for the most part).

Trying to figure out how I can handle input validation after a modal view submission.

I've found that I can't actually use a lazy listener on view submission because if I do, the modal is dismissed/cleared immediately and then I'm not able to respond back after validating the inputs in the case where one of the input is not valid.

So, without using the lazy listener approach for view submission, I can validate my inputs and respond back to Slack within the 3 second limit, but then after validation, assuming all inputs are valid, I actually want to be able to do some processing (like calling another lambda function and waiting for its response) which will more than likely take too much time. Not quite sure how to handle this. Would appreciate any ideas.

Possibilities might include:
- dedicated 'validate' button in modal view (super lame!)
- invoke another lambda to do the processing, don't wait for it to finish and respond asynchronously, but then I'm not sure if I can use bolt in that other lambda...
- is there a way to partially process an event before handing it off to the lazy listener?

Thanks

**Comment by seratch** [comment]
@haggaret If I understand your question here correctly, you can go with the following code:

```python
@app.command("/open-modal")
def handle_command(body, ack, client):
    ack()
    client.views_open(
        trigger_id=body["trigger_id"],
        view={
            "type": "modal",
            "callback_id": "view-id",
            "title": {"type": "plain_text", "text": "My App",},
            "submit": {"type": "plain_text", "text": "Submit",},
            "close": {"type": "plain_text", "text": "Cancel",},
            "blocks": [
                {
                    "type": "input",
                    "block_id": "b",
                    "element": {"type": "plain_text_input", "action_id": "a"},
                    "label": {"type": "plain_text", "text": "Label",},
                }
            ],
        },
    )

def validate(view) -> dict:
    input = view["state"]["values"]["b"]["a"]["value"]
    errors = {}
    if len(input) < 8:
        errors["b"] = "Title must contain at least 8 characters"
    return errors

# This methods must return the `ack()` response within 3 seconds
def ack_submission(ack, view):
    errors = validate(view)
    if len(errors) > 0:
        return ack(response_action="errors", errors=errors)  # Show errors on the modal
    # It's all set. You can store the data.
    ack()  # Closing the modal

# If you're using lazy listener functions along with slack_bolt.adapter.aws_lambda.SlackRequestHandler,
# this method will be executed in another AWS Lambda invocation
def do_whatever(view, logger):
    # If you want to skip this function when the inputs are invalid,
    # you can use the same validation logic here
    errors = validate(view)
    if len(errors) > 0:
        logger.info("if the inputs are invalid, skip running this function")
        return
    import time
    time.sleep(10)
    logger.info(f"Done with {view}")

app.view("view-id")(ack=ack_submission, lazy=[do_whatever])
```

**Comment by haggaret** [comment]
@seratch Ah ha! Thank you so much for the quick reply! I guess the part I was missing (or not grasping) was that I could use the ack function to do the validation and the lazy function to handle the processing! Perfect!

Thanks again for the quick reply!
