### ISSUE TITLE
Improve the stability of API mock servers in unit tests

### ISSUE THREAD

**Issue by seratch** [slackapi/bolt-python#157]
The same issue I raised at https://github.com/slackapi/python-slack-sdk/issues/808 is affecting this project's tests. I will be working on this soon.

```
=============================================================================================== short test summary info ================================================================================================
FAILED tests/slack_bolt/oauth/test_oauth_flow.py::TestOAuthFlow::test_handle_callback - ConnectionResetError: [Errno 54] Connection reset by peer
FAILED tests/slack_bolt/oauth/test_oauth_flow_sqlite3.py::TestOAuthFlowSQLite3::test_handle_callback - ConnectionResetError: [Errno 54] Connection reset by peer
================================================================================= 2 failed, 422 passed, 4 warnings in 98.22s (0:01:38) =================================================================================
```

### Category (place an `x` in each of the `[ ]`)

* [ ] **slack_bolt.App** and/or its core components
* [ ] **slack_bolt.async_app.AsyncApp** and/or its core components
* [ ] Adapters in **slack_bolt.adapter**
* [x] Others

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by vgupta-spothero** [comment]
@seratch hi! our company put together a bot using the Bolt python framework (leveraging the FastAPI adaptor) and were curious if you have any documentation you could point us to in regards to the mock server and its usage outside of the provided code?

**Comment by seratch** [comment]
@vgupta-spothero Hi, I am glad to know you use Bolt and are curious about testing 👍 

> any documentation you could point us to in regards to the mock server and its usage outside of the provided code

Unfortunately, we do not have any document about testing and we do not provide any available testing tools for developers yet. 

But if you are happy to reuse some part of the unit tests in this project, the following test code and its dependencies like `tests.mock_web_api_server` should be useful for writing scenario tests without Slack servers. If you like the code, please feel free to copy and customize them in your project (it's under the MIT license).

* https://github.com/slackapi/bolt-python/blob/v1.2.3/tests/adapter_tests/test_fastapi.py
* https://github.com/slackapi/bolt-python/blob/v1.2.3/tests/adapter_tests_async/test_async_fastapi.py

I cannot tell when and how but I am personally keen to provide some testing tools for Bolt users. We may be able to provide easy-to-use testing tools in the near future but until then, please go with your own solution 🙇

**Comment by vgupta-spothero** [comment]
> @vgupta-spothero Hi, I am glad to know you use Bolt and are curious about testing 👍
> 
> > any documentation you could point us to in regards to the mock server and its usage outside of the provided code
> 
> Unfortunately, we do not have any document about testing and we do not provide any available testing tools for developers yet.
> 
> But if you are happy to reuse some part of the unit tests in this project, the following test code and its dependencies like `tests.mock_web_api_server` should be useful for writing scenario tests without Slack servers. If you like the code, please feel free to copy and customize them in your project (it's under the MIT license).
> 
> * https://github.com/slackapi/bolt-python/blob/v1.2.3/tests/adapter_tests/test_fastapi.py
> * https://github.com/slackapi/bolt-python/blob/v1.2.3/tests/adapter_tests_async/test_async_fastapi.py
> 
> I cannot tell when and how but I am personally keen to provide some testing tools for Bolt users. We may be able to provide easy-to-use testing tools in the near future but until then, please go with your own solution 🙇

Sounds great @seratch! Thank you for that reply, much appreciated 🙏🏽

**Comment by adriandiazgar** [comment]
> I cannot tell when and how but I am personally keen to provide some testing tools for Bolt users. We may be able to provide easy-to-use testing tools in the near future but until then, please go with your own solution 🙇

This would be very useful, +1 here

**Comment by dgarana** [comment]
Can't wait for having that testing utils included on this framework :)
