### ISSUE TITLE
How do I handle the first message sent to installing user on successful install?

### ISSUE THREAD

**Issue by korymath** [slackapi/bolt-python#164]
Issue: I am unclear on how to send the first message to a user on a successful installation. The end goal would be, upon successful OAuth installation of an App build with `bolt-python`, a private chat message would be sent to the installing users describing the first steps with the app.

### Reproducible effect desired with the following snippet of example code:

```bash
pip install slack_bolt
export SLACK_SIGNING_SECRET=***
export SLACK_CLIENT_ID=111.111
export SLACK_CLIENT_SECRET=***
export SLACK_SCOPES=app_mentions:read,channels:history,im:history,chat:write
python oauth_app.py
```

#### The `slack_bolt` version

`slack-bolt==1.0.1`

#### Python runtime version

`Python 3.8.6`

#### OS info

ProductName:	Mac OS X
ProductVersion: 10.15.7

#### Steps to reproduce:

1. Run the `oauth_app.py` example script.

### Expected result:

The desired outcome is a message sent to installing user on successful installation through OAuth. That is, once the app is installed and the user sees the 'Thank you! Redirecting to the Slack App... click here' screen... how can I send that first message to them?

### Actual result:

DM between installing user and App opens. 

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @korymath, thanks for asking a question (and thanks a lot for your contribution at #163 )!

You can use `oauth_settings.callback_options.success` for this. See this example for details: https://github.com/slackapi/bolt-python/blob/v1.0.1/examples/oauth_app_settings.py#L20-L45

**Comment by korymath** [comment]
Thank you for the very fast reply; #163 was the least I could do.

`bolt-python` has made building these sorts of interactions so fun and easy. Thank you for the incredible scaffolding. I feel like I am standing on the shoulders of giants! Great work on the libraries.

I think that I understand. So, once I call the success callback, then I can `Do anything...`™️  ... which is great. This sounds exactly like what I want. 

But, I am not clear what I have access to in that callback? I assume that because this is not one of the events, then I do not have the conventional `client` or other [args](https://github.com/slackapi/bolt-python/blob/79eecae80783eefee9517a2a5b2350c5a506b18d/slack_bolt/kwargs_injection/args.py#L15) that I have gotten used to having access to? 

Does this mean I will need to parse that manually and then build a Web API call manually? (Sorry if these terms that not right... I am still learning)

**Comment by seratch** [comment]
`args.request.context` provides most of them! Here is an example to send DM to the user who installed your app. That being said, the installation is not happening in a Slack channel (in other words, even not inside Slack). So, the methods like `say()`, `respond()`, and so on are not available. Also, the `client` does not hold a valid bot token yet. To perform Web API calls here, you need to use the token in the `args.installation` object.

```python
def success(args: SuccessArgs) -> BoltResponse:
    installation = args.installation
    client = args.request.context.client
    try:
        client.chat_postMessage(
            token=installation.bot_token, # Use the token you just got from oauth.v2.access API response
            channel=installation.user_id,  # Only with chat.postMessage API, you can use user_id here
            text="Thanks for installing this app!"
        )
        return args.default.success(args)
    except SlackApiError as e:
        # TODO error handling
```

**Comment by korymath** [comment]
Thank you very much. This is exactly what I needed, I appreciate the guiding light to help me through these caves. 

All the best, and happy to close this issue with a well defined solution.
