### ISSUE TITLE
Unable to start the app

### ISSUE THREAD

**Issue by athifongoqa** [slackapi/bolt-python#170]
Good day, I'm trying to follow along with the Bolt for Python documentation on https://slack.dev/bolt-python/tutorial/getting-started. For some reason, it won't run. Please advise, thank you.

#### The `slack_bolt` version
slack-bolt==1.1.1
slack-sdk==3.1.0
slackclient==2.9.3

#### Python runtime version

Python 3.8.6

#### OS info

Microsoft Windows [Version 10.0.18363.1198]
#### Steps to reproduce:

(Based off steps given in the documentation)

1. Create an app
2. Tokens and installing apps
3. Setting up your local project

### Expected result:

For the app to let me know that it’s up and running.

### Actual result:

![image](https://user-images.githubusercontent.com/59336133/101234832-84d8e500-36cb-11eb-934b-103b67ec58e9.png)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
@athifongoqa hmm, it seems that you environment is failing to load `⚡️` in the app for some reason. We will update [the code](https://github.com/slackapi/bolt-python/blob/v1.1.1/slack_bolt/app/app.py#L929) not to fail on any environment in future versions.

A workaround I can suggest at this time is to use a Web framework along with Bolt. This means **you do not use `app.start()` method to spin up your app**.

Here is a simple example using Flask. If you prefer others, you can find many examples here: https://github.com/slackapi/bolt-python/tree/v1.1.1/examples

#### requirements.txt

```
slack_bolt>=1.1.1,<1.2
Flask>=1.1
```

#### app.py

```python
from flask import Flask, request
from slack_bolt import App
from slack_bolt.adapter.flask import SlackRequestHandler

app = App()

@app.command("/hello")
def hello(ack):
    ack("Hi!")

flask_app = Flask(__name__)
handler = SlackRequestHandler(app)

@flask_app.route("/slack/events", methods=["POST"])
def slack_events():
    return handler.handle(request)

if __name__ == "__main__":
    # app.start(3000)
    flask_app.run(port=3000, debug=True)
```

#### How to run

```bash
pip install -r requirements.txt
export SLACK_SIGNING_SECRET=***
export SLACK_BOT_TOKEN=xoxb-***
python app.py
```

**Comment by athifongoqa** [comment]
Two things: 

1. I am not all too familiar with what 'exporting' the signing secret and token actually means but I used `set SIGNING_SECRET` in the terminal bc apparently `export` is for Mac & Linux. Did I understand this correctly? If not, please advise further. Apologies if it is a silly question. 
2. I am now getting an error message with regards to not having an argument for App(), it seems.

![image](https://user-images.githubusercontent.com/59336133/101236804-b27a5a00-36dc-11eb-9a12-57975f73b181.png)

**Comment by seratch** [comment]
@athifongoqa 
>1

Yes, you can use `set` command for configuring env variables on Windows OS.

>2

This is related to question 1. Once you set both `SLACK_BOT_TOKEN` and `SLACK_SIGNING_SECRET` in env variables, the app should successfully spin up.

**Comment by athifongoqa** [comment]
So apparently `export` works better on Windows than `set`. Literally just changed that and all seems to be working fine now, thank you! I may be back soon for other issues in future haha! Keep well, Seratch!

**Comment by seratch** [comment]
@christheodosius Thanks for reporting this. We'll improve this at #309

**Comment by christheodosius** [comment]
> 
> 
> @christheodosius Thanks for reporting this. We'll improve this at #309

Fantastic, thank you so much!
