### ISSUE TITLE
oAuth redirect defaults to the slack app 

### ISSUE THREAD

**Issue by 1oglop1** [slackapi/bolt-python#179]
Hi, this issue is related to #166. 
oAuth flow redirect fails with errors similar to `unsupported browser`.
After trying out a few browsers it turned out that default `redirect_uri` is set to open a slack app.
As far as I'm aware this is a custom protocol URI and is not supported by all browsers. (https://api.slack.com/reference/deep-linking#client)

### Reproducible in:

```bash
Python 3.8.5
slack-bolt==1.1.2
slack-sdk==3.1.0
```

#### The `slack_bolt` version

```
slack-bolt==1.1.2
slack-sdk==3.1.0
```

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1. use example from [oAuth example app](https://github.com/slackapi/bolt-python/blob/main/examples/oauth_app_settings.py)
2. go to <url>/slack/install
3. Depends on the browser, when install is finished user is redirected to /slack/oauth_redirect - app tries to open a slack app or fails with `invalid_browser` reason.

### Expected result:

I'd rather have `redirect_uri` a required argument or default to slack web app instead of native app since this would also make administration easier.

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
>After trying out a few browsers it turned out that default redirect_uri is set to open a slack app.

No, the default URL for redirection after confirming a Slack app installation is `https://{your-domain}/slack/oauth_redirect` and you should set it in your Slack app configuration page (if not, set the URL).  https://slack.dev/bolt-python/concepts#authenticating-oauth

With the built-in settings, the page (`/slack/oauth_redirect`) asks an installer to open native Slack app [using meta tag](https://github.com/slackapi/python-slack-sdk/blob/v3.1.0/slack_sdk/oauth/redirect_uri_page_renderer/__init__.py#L38-L53). This does not mean the redirect_uri is a deep link.

As I mentioned in #166, I think the reason why your installation is getting "unsupported browser" is that you may be using "http" (not "https") url for the `/slack/install` URL access. Bolt for Python does not support "http" URLs for OAuth flow. If you are using ngrok, ngrok provides both http and https URLs. Make sure if you start typing the `/slack/install` URL with "https://" in your browser. If you start putting the URL with your domain, some browsers automatically use "http" URL (even when "https" URL is available) and it does not work in this scenario.

**Comment by 1oglop1** [comment]
Thanks for the quick response,

I'm using `inlets` (ngrok like) deployed to heroku with HTTPS:
I believe my settings are correct according to docs.

This is what I set in app oAth settings.
![image](https://user-images.githubusercontent.com/7480694/101943798-0a88f300-3bec-11eb-911c-7d691e6fab0f.png)


I could have added results from different browsers:
Opera:
![image](https://user-images.githubusercontent.com/7480694/101944184-9bf86500-3bec-11eb-896e-bccad580612a.png)

Firefox: 
![image](https://user-images.githubusercontent.com/7480694/101944298-c8ac7c80-3bec-11eb-9b26-9034817cda0f.png)

Thanks for mentioning the meta tag I believe that's a root cause of my issue. 
So I'd have to change `success_url` argument of `OAuthSettings` to redirect me to slack teams web app.

Is there a way to to get the `team_id` and `app_id` dynamically like `RedirectUriPageRenderer` does it? 
Or if would nice if I could select to `https://...` instead of  `slack://...` url somewhere.

**Comment by seratch** [comment]
@1oglop1 Checking this thread https://github.com/slackapi/bolt-python/issues/164 should be helpful. You can customize the callbacks using `callback_options.success/failure`. 

These functions have access to all the information generated through the OAuth callback process: https://github.com/slackapi/bolt-python/blob/v1.1.2/slack_bolt/oauth/callback_options.py#L13-L32

**Comment by seratch** [comment]
Let me know if you have further comments here. I will be closing this ticket after waiting for a few more days.

**Comment by 1oglop1** [comment]
@seratch Yes this was helpful, I missed that piece in docs cuz it was in folded section.
I'll construct similar response to what you linked.

Bolt is great, I just wish I could understand it's code a little better it looks full of interesting concepts.

I've setup a repo with API docs for myself it may be useful for someone: 
https://1oglop1.github.io/slack-bolt-python-api-docs/
https://github.com/1oglop1/slack-bolt-python-api-docs

**Comment by MrQubo** [comment]
Hi @1oglop1!

Sorry for the inconvenience.
I think I might have the same problem as you. I've already checked that I did set `https://` in redirect url.
Could you describe how you solved your problem?

**Comment by 1oglop1** [comment]
@MrQubo You should be able to modify this template meta tag to prevent opening the app 
https://github.com/slackapi/python-slack-sdk/blob/v3.1.0/slack_sdk/oauth/redirect_uri_page_renderer/__init__.py#L38-L53
with this method: https://1oglop1.github.io/slack-bolt-python-api-docs/oauth/callback_options.html#slack_bolt.oauth.callback_options.DefaultCallbackOptions
