### ISSUE TITLE
app.message() not being triggered on my AWS api gateway + lambda set up

### ISSUE THREAD

**Issue by epuerta9** [slackapi/bolt-python#181]
(Filling out the following details about bugs will help us solve your issue sooner.)

### Reproducible in:
aws api gateway and lambda 

#### The `slack_bolt` version

https://github.com/slackapi/bolt-python/releases/tag/v1.2.0b3

#### Python runtime version

(Paste the output of `python --version`)
python 3.8 
#### OS info

AWS Lambda

#### Steps to reproduce:
Having issues with the app.message(':wave:') basic functionality behind an api gateway and lambda. I have a current working slack bot using bolt-python and the rest of the functionality works. Things such as app.event('app_mention'), app.command('/mycommand'), and app.action() all work smoothly. Now, i'm trying to implement a listen for a certain message "form_request" to trigger my bolt-python app but nothing happens. The slack client does not send any event to my api gateway endpoint. The bot has proper permissions such as channel.read and channel.history to perform the right actions. Scratching my head with this one. Does my bolt-python always have to be running and listening? and since my api-gateway + lambda implementation is waiting to be invoked, does the slack client not handle the invoking but instead I need to be fetching?

1. my code implementation
![image](https://user-images.githubusercontent.com/14970360/102651100-ec664a00-4139-11eb-8320-17ea0a45d84e.png)

2. My results
![image](https://user-images.githubusercontent.com/14970360/102651173-128bea00-413a-11eb-81ff-dc929bf4b34f.png)

3. My api gateway traffic (no triggers recently during the trigger)
![image](https://user-images.githubusercontent.com/14970360/102651310-57178580-413a-11eb-95d3-3d6152e465dc.png)

4. My permissions  
![image](https://user-images.githubusercontent.com/14970360/102651542-b5dcff00-413a-11eb-8653-938e2f9da780.png)

### Expected result:

expected to have a request come in, and say processing result

(Tell what you expected to happen)

### Actual result:

(Tell what actually happened with logs, screenshots)
nothing happens..... no http request, no logs during the time frame, nothing to trigger my api gateway + lambda

**Comment by epuerta9** [comment]
[SOLVED] thanks to slack teams help, they pointed me in the right direction. The solution was subscribing to the message.channel event in the bot permissions.

**Comment by mwbrooks** [comment]
Hey @epuerta9 👋🏻 I'm glad to hear that you've solved your problem! Thanks sharing your solution so that others can find the answer!

Your issue had an immense amount of detail 🙇🏻 Really appreciate that! In the end, it looks like you had everything set up, including the scopes, but missed subscribing to the event.

**Comment by emcniece** [comment]
Is there an example of the subscription method somewhere?

**Comment by mwbrooks** [comment]
@emcniece You can't programmatically subscribe to the `message.channels` event and instead you'll need to manually subscribe using the App Settings. It will also add a new scope `channels.history` that will require the app to be reinstalled to your workspace (or user's workspaces).

Here is the [documentation for `message.channels` event](https://api.slack.com/events/message.channels) that is [mentioned above](https://github.com/slackapi/bolt-python/issues/181#issuecomment-748306358).

You'd subscribe to this event in your **App Settings ⟶ Event Subscriptions**:
![image](https://user-images.githubusercontent.com/21328/106820908-0946d600-6631-11eb-8ee8-6fc3e13cd930.png)
