### ISSUE TITLE
Is it supported to have more than one SIGNING_SECRET per app?

### ISSUE THREAD

**Issue by Ambro17** [slackapi/bolt-python#185]
When managing multiple bots under the same server, it would be useful to have only one `bolt.App` Instance and verify requests
given a set of signing secrets instead of just one

### Reproducible in:
Latest bolt version

```bash
slack-bolt==1.1.4
slack-sdk==3.1.0
Python 3.8.6
```

If not possible, what's the recommended approach? One server pero bot?

**Comment by Ambro17** [comment]
I extend the question for any way to having multiple WebClients with different tokens available through dep injection to use one client or another one depending on the command

**Comment by cookieplug** [comment]
Hey there, not sure if this is useful but I am currently trying to achieve the same objective. If you are using Flask for your applications, you will know that you need to use a SlackRequestHandler to route your requests through Flask and then onto your applications.

What I was thinking is that you could intercept the request before it is handled and dynamically update your _token_ and _signing_secret_ values by reassigning the app._token and app._signing_secret variables. However I noticed that you try to determine where the request came from before it is handled you will get a 401 status code when it is passed on to the handler. Quite a strange side-effect.

**Comment by cookieplug** [comment]
Context.

`
# Relevant imports.

app = App(
    # token=os.environ.get("BOT_ACCESS_TOKEN"),
    # signing_secret=os.environ.get("SLACK_SIGNING_SECRET")
)

@flask_app.route("/slack/events", methods=["POST"])
def slack_events():
    # Depending on where the request came from as your bot may be unique per team.
    team = request.form['team-domain']

    if team == "a":
        app._token = team_a_token
        app._signing_secret = team_a_signing_secret
    else:
        # Some other token.

    return handler.handle(request)

`

**Comment by cookieplug** [comment]
I am yet to test this as I am trying to understand why am I getting a 401 status code after looking at the response, but will keep you updated if I find a way around this.

**Comment by Ambro17** [comment]
Thank you for your help @cookieplug. What i did to workaround this limitation is manage bolt apps as blueprints, and then dividing them by routes. Something like this:
```python
from bot_a import bolt_app
from bot_b import bolt_app as bolt_app_b
from slack_bolt.adapter.flask import SlackRequestHandler as FlaskToChalice


app = Flask(__name__)

bolt_adapter = FlaskToBolt(app=poll_bolt_app, chalice=app)
bolt_adapter_b = FlaskToBolt(app=poll_bolt_app_b, chalice=app)


@app.route('/first')
def first():
    return bolt_adapter.handle(app.current_request)


@app.route('/second')
def first():
    return bolt_adapter.handle(app.current_request)
```

And then each bolt_app has the proper signing secret and bot token

**Comment by seratch** [comment]
Thanks for sharing the thoughts here! These should be helpful for others too. Let me add my comments here.

We are not planning to add the feature to automatically switch multiple signing secrets in a single Bolt app at this time. In line with this, having separate endpoints is a recommended way for running multiple Bolt apps in a single Web app instance (as @Ambro17 shared above). A concrete example can be like this:

```python
from slack_bolt import App
from slack_bolt.adapter.flask import SlackRequestHandler

app_a = App(signing_secret="secret-a", token="xoxb-a")
app_b = App(signing_secret="secret-b", token="xoxb-b")

@app_a.command("/app-a-command")
def app_a_command(ack):
    ack("This is App A!")

# To share a single listener among multiple apps,
# You can use non-decorator registration
def say_something(body, say, logger):
    logger.info(body)
    say("What's up?")

app_a.event("app_mention")(say_something)
app_b.event("app_mention")(say_something)

# To simplify above, you can go wit this
apps = [app_a, app_b]
for app in apps:
    app.event("app_mention")(say_something)

from flask import Flask, request

flask_app = Flask(__name__)
# Flask handler for App A
handler_a = SlackRequestHandler(app_a)
# Flask handler for App B
handler_b = SlackRequestHandler(app_b)

# Request URL for App A
@flask_app.route("/slack/app_a/events", methods=["POST"])
def slack_app_a_events():
    return handler_a.handle(request)

# Request URL for App B
@flask_app.route("/slack/app_b/events", methods=["POST"])
def slack_app_b_events():
    return handler_b.handle(request)
``` 

> dynamically update your token and signing_secret values by reassigning the app._token and app._signing_secret variables

I don't recommend this approach. There are two reasons. Firstly, as the field names start with `_`, they are private. We may change the internals in the future. The second one is more important. The values are shared among request handers. Thus, modifying them at runtime causes race condition issues when handling simultaneous requests. 

>I extend the question for any way to having multiple WebClients with different tokens available through dep injection to use one client or another one depending on the command

You can use global/listener middleware to inject anything to a `context` arg.

```python
database = {}

@app.middleware
def set_web_clients(context: BoltContext, next):
    user_token = database.get(context.user_id)
    if user_token is not None:
        context["user_token_client"] = WebClient(token=user_token)
    next()

@app.event("app_mention")
# or @app.event("app_mention", middleware=[set_web_clients]) if you apply the middleware only for this listener
def event_test(context: BoltContext):
    user_client: WebClient = context["user_token_client"]
    search_result = user_client.search_messages(query="my message")
    do_something(context.user_id, search_result)
```

Hope this was helpful to you.

**Comment by Ambro17** [comment]
Thank you for your example @seratch! 
I think this might be a recurrent question once one starts to divide functionality in more than one bot but one web server. 
Perhaps it might be useful to give it a place in the docs so we can find it more quickly,
What do you think?

**Comment by cookieplug** [comment]
Welcome back @seratch! Thanks a lot for the insightful comments, the approach both yourself and @Ambro17 have suggested definitely seems like the way to go. Not sure why I didn't think of using 2 app instances sooner!

**Comment by seratch** [comment]
>I think this might be a recurrent question once one starts to divide functionality in more than one bot but one web server.
>Perhaps it might be useful to give it a place in the docs so we can find it more quickly,
>What do you think?

Thanks for the suggestion! Currently, the team is updating the documents as preparation for Socket Mode release #159 - after finishing the task, let me revisit this. We may update the part on adapters to have an additional line that navigates developers to this issue.

As I've provided answers to all the questions here, allow me to close this issue now.
