### ISSUE TITLE
Add deployment guides

### ISSUE THREAD

**Issue by mwbrooks** [slackapi/bolt-python#190]
Let's add a collection of deployment guides for common, popular platforms! We can start by matching the _Bolt for JavaScript_ guides for [Heroku](https://slack.dev/bolt-js/deployments/heroku) and [AWS Lambda](https://slack.dev/bolt-js/deployments/aws-lambda). Ideally, we'd also like to add a guide for a container platform.

### The page URLs

* https://slack.dev/bolt-python/deployments/

### Progress

* [ ] AWS Lambda deployment guide
* [ ] Heroku deployment guide

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Cool 👍  I'm happy to be an early reviewer. Feel free to make a draft PR for views.

**Comment by seratch** [comment]
@mwbrooks As you have a work-in-progress branch for this, can you create a draft pull request for now? No rush about finishing them. https://github.com/slackapi/bolt-python/compare/main...mwbrooks:190-heroku-deployment-guide

**Comment by seratch** [comment]
We have not been working on this task for a while. I _think_ that we can close this issue if other maintainers are fine with it. Developers can refer to https://slack.dev/bolt-js/deployments/heroku for Heroku-specific speps.

**Comment by mwbrooks** [comment]
Personally, I think we can stop work on the Heroku guide and instead ensure that the Heroku example app included in this repository is up-to-date and helpful. So far, I'm seeing that developers are getting more value out of short example apps than long-form guides.

@srajiang Do you have any opinions, since you've taken the time to update the Getting Started and Heroku guides for Bolt JS?

**Comment by seratch** [comment]
As I mentioned in my last comment above, I agree that we can stop working on this for the reason @mwbrooks mentioned. If we go with the direction, we can close https://github.com/slackapi/bolt-python/pull/441 too.

**Comment by seratch** [comment]
@mwbrooks @srajiang Let me close this issue and the PR for now. If we come up with some idea for better documentation, we can revisit at anytime!
