### ISSUE TITLE
how we can listen to the request from button which is inside attachment

### ISSUE THREAD

**Issue by sudhir512kj** [slackapi/bolt-python#204]
how we can listen to the request from button which is inside attachment using slack_bolt

#### The `slack_bolt` version

1.1.2

#### Python runtime version

3.7

#### OS info

Windows OS 10
![7834738](https://user-images.githubusercontent.com/10810241/104441276-75e22e00-55b9-11eb-85cf-307c7e047552.PNG)
![hfjdghdfjghdj](https://user-images.githubusercontent.com/10810241/104441533-cfe2f380-55b9-11eb-8796-f12ab42438d2.PNG)

**Comment by seratch** [comment]
You can use `@app.action` as with top-level blocks.

```python
@app.message("button please")
def handle_messge_evnts(message, say):
    say(
        attachments=[
            {
                "blocks": [
                    {
                        "type": "actions",
                        "block_id": "b",
                        "elements": [
                            {
                                "type": "button",
                                "action_id": "button-action",
                                "text": {"type": "plain_text", "text": "Click Me"},
                                "value": "click_me_123",
                            }
                        ],
                    }
                ]
            }
        ]
    )

@app.action("button-action")
def handle_action(action, ack, logger):
    logger.info(f"action: {action}")
    ack()
```

**Comment by seratch** [comment]
As I've already provided an answer to this question, let me close this. Please feel free to write in if you have any further related questions.
