### ISSUE TITLE
Best way for a bot mentioning itself across platforms

### ISSUE THREAD

**Issue by tomerbsentinel** [slackapi/bolt-python#207]
Hi, I tried using those methods w/o any luck,
Any help would be appreciated. 

Try 1: <@me>
Try 2: <@{XYZ['user_id']}
Try 3: <@APP_NAME>

In the below example, I'm trying to send a msg in a "only visible to you", but if I fail, I will send it as a normal chat msg.

```try:
        # Execute the Time watch script and notify the user.
        msg = f"""Your task was received and is being processed...
It should take approximately 2 minutes maximum.
If you have not got another slack notification from me (<@me>),\nplease tell the creator for a bug fix."""

    except Exception as e:
        msg = "There was an error with your submission"
        logger.error(f"Error responding to 'Fill Missing Times' button click: {e}")

    finally:
        # Message the user
        try:
            client.chat_postEphemeral(channel=view['private_metadata'], text=msg, user=slack_user_id, link_names=True)
        except Exception:
            client.chat_postMessage(channel=slack_user_id, text=msg, link_names=True)```

Expected results shall be the bot user clickable, as a normal <@mention>.

**Comment by seratch** [comment]
Hi @tomerbsentinel thanks for asking the question!

>a bot mentioning itself

You can use [`context.bot_user_id`](https://github.com/slackapi/bolt-python/blob/v1.2.1/slack_bolt/context/base_context.py#L59-L61) for mentioning your bot user in a message. In other words, `f"<@{context.bot_user_id}>"` should work for you.

If your app's context does not have bot_user_id for some reason (e.g., your app has its own authorize logic), you can fetch bot_user_id by calling https://api.slack.com/methods/bots.info with bot_id.

>I'm trying to send a msg in a "only visible to you", but if I fail, I will send it as a normal chat msg.

When sending a message using either [`ack()`](https://github.com/slackapi/bolt-python/blob/v1.2.1/slack_bolt/context/ack/ack.py#L22) or [`respond()`](https://github.com/slackapi/bolt-python/blob/v1.2.1/slack_bolt/context/respond/respond.py#L21), you can set "response_type" as "ephemeral" (although the default is ephemeral). If you use a Web API call for it, [chat.postEphemeral](https://api.slack.com/methods/chat.postEphemeral) is available for it.

If these information are helpful to you, would you mind closing this?

**Comment by tomerbsentinel** [comment]
Hi @seratch,
Thanks for the answer,
I think I understand it correctly, but for all, I would like to know if I right here.

1. I'm waiting for a specific command.
2. The command is fired - I'm opening a modal to fill some details.
3. (my understanding ) I need to pass the relevant "channel_ID" to the modal, for the next phase.
```app.command("/fill_time")
def open_modal(ack, command, client, logger):
ack()
    try:
        fill_time_modal = {
            "private_metadata": command['channel_id'],
            "type": "modal",```
4. I'm handling the submission of my form.
```@app.view("Fill_Missing_Times")
def handle_submission(ack, body, client, view, logger):
    ```

You're saying that I need also to pass the _respond_ to steps 3 and 4, and then, instead of using the
```    finally:
        # Message the user
        try:
            client.chat_postEphemeral(channel=view['private_metadata'], text=msg, user=slack_user_id, link_names=True)
        except Exception:
            client.chat_postMessage(channel=slack_user_id, text=msg, link_names=True)```
to use only respond(text="something")?

See here the entire process.
https://github.com/tobenary/slack_bolt_timewatch/blob/92f32351da342370a498d20668aeca8e01f17f18/time_bolt.py#L314

**Comment by seratch** [comment]
>(my understanding ) I need to pass the relevant "channel_ID" to the modal, for the next phase.

Yes, it works.

**Comment by tomerbsentinel** [comment]
Hi @seratch ,

Could you please elaborate more on the way of sending the "respond" to my commands?

**Comment by tomerbsentinel** [comment]
Thank you very much for the detailed response.
