### ISSUE TITLE
How do I ensure that a bot/app can not be installed in a workspace twice?

### ISSUE THREAD

**Issue by korymath** [slackapi/bolt-python#209]
Apologies for the second naive question! I appreciate your incredible work so much 💯 

So, I want to be able to block the 'second' installation of an app in a workspace. 

### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
slack-bolt==1.2.1
slack-cleaner==0.7.4
slack-sdk==3.2.0
slackclient==2.9.3
slacker==0.14.0
Python 3.8.6
ProductName:	macOS
ProductVersion:	11.1
BuildVersion:	20C69
Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64
```

#### Steps to reproduce:

For instance, running the example in https://github.com/slackapi/bolt-python/blob/main/examples/oauth_sqlite3_app.py

```sh
# pip install slack_bolt
# export SLACK_SIGNING_SECRET=***
# export SLACK_BOT_TOKEN=xoxb-***
# export SLACK_CLIENT_ID=111.111
# export SLACK_CLIENT_SECRET=***
# export SLACK_SCOPES=app_mentions:read,channels:history,im:history,chat:write
# python oauth_app.py
```

### Expected result:

I do not want to overwrite the installation in the database with the new installation information which is the default behaviour pulled in from the `slack_sdk.oauth.installation_store`.

Reference:

https://github.com/slackapi/python-slack-sdk/blob/919febeaf660d001f0c81c961fb1ed29255a0162/slack_sdk/oauth/installation_store/sqlalchemy/__init__.py#L153-L158

Rather, I want either:
1) to be able to access all of the users ids who have installed the app
2) to block the double installation problem

### Actual result:

When multiple users (workplace administrators) install the app sequentially, then the one who ran the most recent installation becomes the `user_id` returned with a `...installation_store.find_installation`. 

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @korymath, I am really glad to know that you are happy with Bolt for Python!

> 1. to be able to access all of the users ids who have installed the app

At this point, `Installation` does not act as a dict value, it's not possible to have additional fields such as `installed_user_ids` in it. I think having custom fields in the class on a developer side is a common use case. I will create a task for it. With the change, you can go with overridden find_installation method.

As of today, an approach I can suggest is to implement your own `authorize` function and set any custom values in `context` object for following middleware and listeners. https://github.com/slackapi/bolt-python/blob/v1.2.1/slack_bolt/authorization/authorize.py#L44

For implementing `authorize`, please refer to [this document](https://slack.dev/bolt-python/concepts#authorization) and [test code](https://github.com/slackapi/bolt-python/blob/v1.2.1/tests/scenario_tests/test_authorize.py). Although `context` does not exist in the argument list in docs and tests, you can have `context` in `authorize` method arguments.

> 2. to block the double installation problem

The only way is to inherit `OAuthFlow` to customize the handling. Specifically, you can add your own check logic before [issuing an access token and storing it](https://github.com/slackapi/bolt-python/blob/v1.2.1/slack_bolt/oauth/oauth_flow.py#L254-L280).

**Comment by seratch** [comment]
>At this point, Installation does not act as a dict value, it's not possible to have additional fields such as installed_user_ids in it. I think having custom fields in the class on a developer side is a common use case. I will create a task for it. With the change, you can go with overridden find_installation method.

Hey @korymath , I just released python-slack-sdk v3.2.1, which supports custom fields in `Bot` / `Insallation` objects. You can set any additional fields by implementing find/save methods in `InstallationService`.

See also: https://github.com/slackapi/python-slack-sdk/blob/v3.2.1/tests/slack_sdk/oauth/installation_store/test_models.py

Let me know if you have anything further to discuss here. As I do not have any further action to take here, I will close this issue after waiting for your response for a few more days.

**Comment by korymath** [comment]
Hey @seratch -- thank you for the followup. Sorry I didn't respond sooner. This is a brilliant answer and a fantastic amount of support for an open source library. I wish that I could give you a massive +1 on this. 

Please do feel free to close this and I will work my way through this with ongoing development. I might ping again with more questions as I stumble through if this is an alright flow?

**Comment by korymath** [comment]
Beautiful solution btw. Very elegant.
