### ISSUE TITLE
How to handle validation that takes longer than 3 seconds?

### ISSUE THREAD

**Issue by haggaret** [slackapi/bolt-python#218]
I had previously asked about how to handle validation after view submission (see here: https://github.com/slackapi/bolt-python/issues/156) and you pointed me in the right direction, and I've been able to use that method for everything up until this point. However, I'm now running into a problem where for one particular case, I'm not always able to complete the validation within the 3 second time limit. Curious how you would handle this.

In this specific case, in order to validate some of the input (on view submission), I am actually invoking another lambda and waiting for a reply from it. Sometimes that takes a little longer, and I end up exceeding the 3 second time limit for acking the submission. To make things worse, since I am running the validate function during the ack method, and again during my 'handle submission' method, I get an error in the modal after view submission (since the validate didn't return a response within 3 seconds) but there are actually no errors (it just took too long in the ack) and the action that is to be performed after submission actually occurs, but the modal is still present with a generic 'something went wrong' error displayed. If the user clicks submit again, it will actually be invoked AGAIN.

Hope all that made sense.

So the basic question is how to handle validation in the case where it will take longer than the 3 seconds you have to respond back?

**Comment by seratch** [comment]
Hello again @haggaret 👋 

> how to handle validation in the case where it will take longer than the 3 seconds you have to respond back

Unfortunately, there is no way to enable your app to spend more than 3 seconds for input validation on a modal.

An alternative way to deal with this is:

* Your app responds with" response_action: update" and a new view with a message like  "the system is currently checking your inputs..." 
* Once the validation complete, your app calls `views.update` API method with the result view. You can have section blocks for displaying error messages but it's not possible to bind errors to input blocks.

Hope this suggestion is helpful to you.

**Comment by haggaret** [comment]
Hmmm...ok - I think should work for me. I'll play around with it and see what I can come up with. Thanks, as always, for the speedy replies!

Possible feature request:
I wonder if a new ack would be a possibility where you respond with 'validation pending' to give you more time? And then when validation is complete, you respond back with the errors object somehow (using the ack object)

**Comment by seratch** [comment]
Thanks for sharing this. I will share your feedback with the platform engineering teams 👍 

As I've provided an answer, let me close this issue now.
