### ISSUE TITLE
SLACK_BOT_TOKEN export: not valid in this context:

### ISSUE THREAD

**Issue by tonywang531** [slackapi/bolt-python#222]
I tried to test the examples of but all of them results in an error. The actual application error is 
```
raise BoltError(error_auth_test_failure(err.response))
slack_bolt.error.BoltError: `token` is invalid (auth.test result: {'ok': False, 'error': 'not_authed'})
```

I think something is wrong with my token or my secret. Which should not be the case because I used the same credentials for my slack_api_app. So I tried to redefine the slack bot token again and I get the error:

`export: not valid in this context: xoxb-2546086460-
`
I tried different code samples and all got the same response.

#### The `slack_bolt` version

slack-bolt==1.2.3
slack-sdk==3.2.0
slackclient==2.9.3
slackeventsapi==2.2.1

#### Python runtime version

Python 3.9.0

#### OS info

ProductName:	macOS
ProductVersion:	11.1
BuildVersion:	20C69
Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64

#### Steps to reproduce:

(Share the commands to run, source code, and project settings 

1. pip install bolt-python
2. export SLACK_BOT_TOKEN
3. export SLACK_SIGNING_SECRET
4. python app.py

### Expected result:

The app starts and listen for events

### Actual result:
App error and token not valid in this context

**Comment by tonywang531** [comment]
Sorry I tried to inspect my export command and it turns out I cannot put space between the equal sign and the value. My previous assignment turned out to be empty values.

**Comment by sneha2310** [comment]
> I tried to test the examples of but all of them results in an error. The actual application error is
> 
> ```
> raise BoltError(error_auth_test_failure(err.response))
> slack_bolt.error.BoltError: `token` is invalid (auth.test result: {'ok': False, 'error': 'not_authed'})
> ```
> 
> I think something is wrong with my token or my secret. Which should not be the case because I used the same credentials for my slack_api_app. So I tried to redefine the slack bot token again and I get the error:
> 
> `export: not valid in this context: xoxb-2546086460- ` I tried different code samples and all got the same response.
> 
> #### The `slack_bolt` version
> slack-bolt==1.2.3 slack-sdk==3.2.0 slackclient==2.9.3 slackeventsapi==2.2.1
> 
> #### Python runtime version
> Python 3.9.0
> 
> #### OS info
> ProductName: macOS ProductVersion: 11.1 BuildVersion: 20C69 Darwin Kernel Version 20.2.0: Wed Dec 2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64
> 
> #### Steps to reproduce:
> (Share the commands to run, source code, and project settings
> 
> 1. pip install bolt-python
> 2. export SLACK_BOT_TOKEN
> 3. export SLACK_SIGNING_SECRET
> 4. python app.py
> 
> ### Expected result:
> The app starts and listen for events
> 
> ### Actual result:
> App error and token not valid in this context

Hey, I am having same issue. Did you get solution. Like I am not giving space but it still shows {'ok': False, 'error': 'missing_scope', 'needed': 'chat:write:bot', 'provided': 'incoming-webhook'}

**Comment by hello-ashleyintech** [comment]
Hi, @sneha2310! Thanks for reaching out! Based on the error message you provided, it looks like the bot token you are using for your application is missing a scope. Based on the error, I believe you'll need to add the `chat:write` Bot scope to your application. You'll need to go to your app settings (`https://api.slack.com/apps/[APP-ID]`) > `OAuth & Permissions` > Add `chat:write` under Bot Token Scopes > If prompted, reinstall application. You should be able to then make the API call. If you run into further issues, please open an issue [here](https://github.com/slackapi/bolt-python/issues) and we can assist you further!
