### ISSUE TITLE
Is it possible to integrate this API to SlackEventAdapter?

### ISSUE THREAD

**Issue by tonywang531** [slackapi/bolt-python#223]
My app needs to listens for message.app_home event. Somehow I set up SlackEventAdapter listener yet nothing happens. Then I saw bolt-python API. However this API seems to have its own build in method? The usage also seems to be different from SlackEventAdapter API. My app is already built in with SlackEventAdapter and dialogflow_fulfillment. Is there a way to integrate this into SlackEventAdapter?

The slack_bolt version
slack-bolt==1.2.3
slack-sdk==3.2.0
slackclient==2.9.3
slackeventsapi==2.2.1

Python runtime version
Python 3.9.0

OS info
ProductName: macOS
ProductVersion: 11.1
BuildVersion: 20C69
Darwin Kernel Version 20.2.0: Wed Dec 2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64

**Comment by seratch** [comment]
Hi @tonywang531,

> Is there a way to integrate this into SlackEventAdapter?

There is no simple way to run your `slackeventsapi` code as-is in a Bolt app. If you want to use Bolt for further development, you can migrate your code this way:

```python
app = App()

@app.event("message")
def react_to_messages(client, event):
    client.dialog_open(...)
```

**Comment by tonywang531** [comment]
I see. I am trying the Flask example in the examples. My code (test_event.py) is as follows :

```
# ------------------------------------------------
# instead of slack_bolt in requirements.txt
import sys
import os

sys.path.insert(1, "../..")
# ------------------------------------------------

import logging

logging.basicConfig(level=logging.DEBUG)

from slack_bolt import App
from slack_bolt.adapter.flask import SlackRequestHandler


# Initializes your app with your bot token and signing secret
app = App(
    token=os.environ.get("SLACK_BOT_TOKEN"),
    signing_secret=os.environ.get("SLACK_SIGNING_SECRET")
)


@app.middleware  # or app.use(log_request)
def log_request(logger, body, next):
    logger.debug(body)
    return next()


@app.event("app_mention")
def event_test(body, say, logger):
    logger.info(body)
    say("What's up?")


# Listens to incoming messages that contain "hello"
@app.message("hello")
def message_hello(message, say):
    # say() sends a message to the channel where the event was triggered
    say(
        blocks=[
            {
                "type": "section",
                "text": {"type": "mrkdwn", "text": f"Hey there <@{message['user']}>!"},
                "accessory": {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "Click Me"},
                    "action_id": "button_click",
                },
            }
        ],
        text=f"Hey there <@{message['user']}>!",
    )


@app.action("button_click")
def action_button_click(body, ack, say):
    # Acknowledge the action
    ack()
    say(f"<@{body['user']['id']}> clicked the button")


from flask import Flask, request

flask_app = Flask(__name__)
handler = SlackRequestHandler(app)


@flask_app.route("/slack/events", methods=["POST"])
def slack_events():
    print(1)
    return handler.handle(request)

if __name__ == '__main__':
    flask_app.run(debug=True)
```

Now I start the process using command `FLASK_APP=test_event.py FLASK_ENV=development flask run -p 3000`. Now I get: 
```
DEBUG:slack_bolt.App:Applying slack_bolt.middleware.ssl_check.ssl_check.SslCheck
DEBUG:slack_bolt.App:Applying slack_bolt.middleware.request_verification.request_verification.RequestVerification
INFO:slack_bolt.RequestVerification:Invalid request signature detected (signature: v0=68715bc4df3ff7ab7fa4616c8a323c8de85069ba597e54541224a6b79133272d, timestamp: 1611538480, body: {"token":"eDkkqmye3afW9GIkyOUaePke","challenge":"sTO9OCetj6bVzb1lvMi61z8nLjgFK1aEkNvmp2QFjcCKt3yFTEFq","type":"url_verification"})
INFO:werkzeug:127.0.0.1 - - [25/Jan/2021 10:34:40] "POST /slack/events HTTP/1.1" 401 -

```

**Comment by seratch** [comment]
Hey @tonywang531, I am happy to help you out but this issue tracker is available mainly for discussing and managing the issues of bolt-python library itself.

I think for this Q&A, using the community Slack workspace may be smoother. If you don't mind, could you join community.slack.com from [here](https://j.mp/community-slack-com), join #lang-python channel, and mention me (`@seratch`) in the channel? We can use a thread for more real-time conversation and I will be available (probably in the same timezone).

**Comment by seratch** [comment]
As we started a conversation at https://community.slack.com/archives/CHL4CLRCZ/p1611556473002500, let me close this question here.

**Comment by AlexHasMe** [comment]
Hey @tonywang531! Did you find a solution to your problem (https://github.com/slackapi/bolt-python/issues/223#issuecomment-766485586)? I have the same and can't resolve it nohow.
