### ISSUE TITLE
What does next() do in middlewares

### ISSUE THREAD

**Issue by Techno-Disaster** [slackapi/bolt-python#228]
Quick small question: 

I have been trying to understand one of the examples, but coudn't get this one part. In the messages_event example what does [this](https://github.com/slackapi/bolt-python/blob/ab9619630281b0563c7ae95068f89fd72602bf76/examples/message_events.py#L37) next() exactly do?

**Comment by seratch** [comment]
>Both global and listener middleware must call next() to pass control of the execution chain to the next middleware.

Reading https://slack.dev/bolt-python/concepts#global-middleware may be helpful. If you do not call `next()` in a middleware, Bolt stops calling the following middleware for the request. Check the following code examples as well.

* global middleware example: https://github.com/slackapi/bolt-python/blob/v1.2.3/slack_bolt/middleware/ssl_check/ssl_check.py#L20-L32
* listener middleware example: https://github.com/slackapi/bolt-python/blob/v1.2.3/docs/_advanced/listener_middleware.md

**Comment by Techno-Disaster** [comment]
> > Both global and listener middleware must call next() to pass control of the execution chain to the next middleware.
> 
> Reading https://slack.dev/bolt-python/concepts#global-middleware may be helpful. If you do not call `next()` in a middleware, Bolt stops calling the following middleware for the request. Check the following code examples as well.
> 
> * global middleware example: https://github.com/slackapi/bolt-python/blob/v1.2.3/slack_bolt/middleware/ssl_check/ssl_check.py#L20-L32
> * listener middleware example: https://github.com/slackapi/bolt-python/blob/v1.2.3/docs/_advanced/listener_middleware.md

Yes, thank you had a hunch it was this.  So it iterates over the middleware list in an app event and the Callable ```next=Callable```  in a custom middleware should also return next()

Thanks again.
