### ISSUE TITLE
Inviting bot to private channel issue

### ISSUE THREAD

**Issue by korymath** [slackapi/bolt-python#229]
I am unable to invite a bot to a private channel from a DM. The message is uninformative and the response messages are contradictory. 

Apologies as this is not exactly a `bolt-python` question, but I have a feeling you'd know what is going on and how to best handle this if it is on the bot or OAuth side. Otherwise, I'd love help triaging this issue.

### Reproducible in:

```bash
# pip freeze | grep slack
slack-bolt==1.2.1
slack-cleaner==0.7.4
slack-sdk==3.2.0
slackclient==2.9.3
slacker==0.14.0

# python --version
Python 3.8.6

# sw_vers && uname -v # or `ver`
ProductName:	macOS
ProductVersion:	11.1
```

#### Steps to reproduce:

1. Install app
2. type `/invite @bot #private_channel` 
3. response is ephemeral post: `Only visible to you.  Slackbot  10:35 AM @bot is already in this channel.`
4. in private channel, write `@bot Hello!` 
5. response is ephemeral post: `Only visible to you. Slackbot  10:39 AM You mentioned @Coach, but they’re not in this private channel.` Invite Them or Do Nothing
6. type `/invite @bot` in #private_channel
7. response: `bot  10:44 AM was added to private_channel by korymath. 

### Expected result:

I'd expect to be able to /invite bots to public and private channels.
I'd expect the error messages to be informative.

### Actual result:

As described in the steps above, bot doesn't join the channel unless invited directly from inside the channel.

**Comment by seratch** [comment]
>3. response is ephemeral post: Only visible to you. Slackbot 10:35 AM @bot is already in this channel.

This means that the bot user is **in the DM, not #private_channel**. You cannot invite a user to a private channel using the argument. The option is only available for public channels.

Thanks for asking this question here but as you mentioned, this is an issue tracker for Bolt for Python library. Let me close this issue 🙇 

For general questions, more folks can help you at the community Slack workspace. If you are not in the workspace, you can join from [this URL](https://j.mp/community-slack-com). For the questions that are specific to your workspace, our customer support team can help you out: https://my.slack.com/help/requests
