### ISSUE TITLE
What might be causing latency for processing event listener code for a Python Bolt app using the Flask adapter and uWSGI?

### ISSUE THREAD

**Issue by akowtko** [slackapi/bolt-python#231]
I'm having a latency issue with my Slack Python Bolt app using the Flask Adapter.

### Reproducible in:
```
slack-bolt==1.2.3
slack-sdk==3.2.1
ProductName:	Mac OS X
ProductVersion:	10.15.6
BuildVersion:	19G73
Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64
```

#### The `slack_bolt` version
slack_bolt 1.2.3

#### Python runtime version

Python 3.8.7

#### OS info
```
ProductName:	Mac OS X
ProductVersion:	10.15.6
BuildVersion:	19G73
Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64
```

#### Steps to reproduce:

I took a Slack app that previously used the `slack_sdk` and `slackeventsapi` and rewrote it with Bolt utilizing a Flask adapter and using uWSGI as my server. The staging and production versions are hosted in AWS ECR and run in Elastic Container Service. The external urls are hosted by API Gateway which redirects traffic to the Task Definitions in ECS. It's a distributed app and I wrote a custom InstallationStore for Mongo where I host the workspace tokens. I pass the Bolt app into `SlackRequestHandler` and use that handler for the flask `/slack/events` route to pass the request into Bolt. I haven't created the `/slack/install` route and `/slack/oauth_redirect` routes to pass requests into bolt for the oauth flow because I already had the workspace tokens saved properly before I rewrote with Bolt (aka it's on my todo list but the app still works currently because the app was already installed before with the working tokens stored in my mongo database).

I use `ack()` at the beginning of any `@app.action` but did not use it for `@app.message` or `@app.event` since I didn't see `ack` used for those in the Python Bolt documentation. 

The app responds to messages sent in the messages tab of the app. It recognizes words like `help`. For `help` it will then `chat.postEphemeral` in response with some text describing what the app does. The app has other functionalities but I don't think I'm allowed to disclose that by my company so I'm just going to use the case where someone sends `help` in the messages tab. I am listening to `app_mention` and am subscribed to that event and the appropriate permissions for it. The app works, but it takes a minute for the app to respond to messages.

Looking at the logs the app immediately starts going through the listeners until it finds the correct one that matches the event (in this case `message`). It appears to go through the lines of code inside the message listener pretty quickly and ends with trying to post the ephemeral message back to the user in the messages tab via `client.postEphemeral`. I am using the `client` object that Bolt gives me access to in the event listener. However it takes a minute or more to get a response back from Slack. So I'm unsure if the process of me trying to send the `client.postEphemeral` is the delay, or if the delay is in Slack processing and responding? 

At any rate there is a long delay between `Sending a request - url: https://www.slack.com/api/chat.postEphemeral,` and `DEBUG:slack_sdk.web.slack_response:Received the following response - status: 200, headers: {'date': 'Thu, 04 Feb 2021 21:30:37 GMT'` at which point I finally see the ephemeral message posted by the slack app in the messages tab of the slack app. I've included screenshots of the logs from when I first type `help` in the messages section and when I see the ephemeral message response by the app. 

When the app was only written in Bolt with no flask adapter, there was no latency. But I had to add the flask adapter back in with uWSGI because I know the Bolt default `HTTPServer` is only for dev purposes not for production.

Do you know what could be causing this latency when I use Python Bolt with a Flask adapter and uWSGI hosted on AWS ECS?

### Expected result:

Low latency from when Bolt processes the event listener and the event listener code finishes running. 

### Actual result:

A minute or more between when the event listener is triggered and the event listener code finishes running. The end of the code in most cases for the app is `client.chatEphemeral` which takes 1 minute to get a response back from Slack for.
<img width="1425" alt="LogsPart1" src="https://user-images.githubusercontent.com/9166875/106958584-6a80af00-66ee-11eb-84fa-0f5219a3014b.png">
<img width="1406" alt="LogsPart2" src="https://user-images.githubusercontent.com/9166875/106958595-6eaccc80-66ee-11eb-982e-de4046180431.png">

`app.py` and my installation store:
[Archive.zip](https://github.com/slackapi/bolt-python/files/5928717/Archive.zip)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @akowtko, thanks for asking the question!

>When the app was only written in Bolt with no flask adapter, there was no latency. But I had to add the flask adapter back in with uWSGI because I know the Bolt default HTTPServer is only for dev purposes not for production.

Have you tried the built-in server app in ECS environment too? I do not think Flask can be a contributing factor but I'm curious about whether this is specific to uWSGI or not. To narrow down the issue, how about trying other adapters and/or WSGI servers like gunicorn (also, with different WGSGI server configuration)? https://github.com/slackapi/bolt-python/tree/main/examples/docker

**Comment by akowtko** [comment]
@seratch Here's what I've tried that has latency (all hosted on AWS):
- Bolt + Flask adapter (with default flask development server)
  - Note: the latency only happens when deployed to AWS in this case. When run locally via tunneling or SocketMode there is no latency
- Bolt + Flask adapter + uWSGI
- Bolt + Flask adapter + uWSGI + nginx

I have deployed Bolt to AWS on its own (aka running its default `HTTPServer`) and there is no latency. The issue is that default server is not intended for production use. 

I'm not sure if it would make sense to try a server besides uWSGI since even when deployed with Bolt + Flask on its own there is latency. With regards to other adapters, I have 5 existing applications I've inherited at work that are all written in Flask and I'd prefer to not have to rewrite them with a completely different adapter.

I will go through and modify my settings to match those in the flask uWSGI example and see if that helps at all, but any insight as to what might be going on? 

Thanks!

**Comment by seratch** [comment]
@akowtko Probably, your `uwsgi.ini` does not have this configuration: https://github.com/slackapi/bolt-python/blob/v1.3.0/examples/docker/flask-uwsgi/uwsgi.ini#L7

As Bolt for Python utilizes threads, this setting is required.

**Comment by akowtko** [comment]
@seratch You're correct; I didn't have threads enabled. I updated my `Dockerfile` and `uwsgi.ini` to model it after the example you provided and it works now (and the image is much smaller than my previous Dockerfile). Thank you so much for the help!

**Comment by srajoo** [comment]
@seratch I'm facing latency issues when running Bolt + Flask (with default flask development server). Like mentioned previously, it works fine on my local, it's only when I deploy this to AWS that I get latency issues. My file_shared event takes 3 minutes to run. 

I'm using Flask to serve requests from a web app. Here's my code:

```
from multiprocessing import Process

app = App(token=os.environ.get("SLACK_BOT_TOKEN"))
app2 = flask.Flask(__name__)

def run_slack_socket(slack_app_token):
    logger.info("Starting the Slack Bolt App")
    SocketModeHandler(app, slack_app_token).start()
    
def run_from_custom_handler():
    logger.info("Starting the Custom Handler")
    port = os.environ.get('PORT', 5000)
    app2.run(host='0.0.0.0', port=port, debug=True, threaded=False)

# Start your app
if __name__ == "__main__":
    import argparse
    logger.info('Slack bolt is running successfully.')
    parser = argparse.ArgumentParser()
    parser.add_argument('--org_id', help='Organization that this points to', default='local')
    args = parser.parse_args()
    
    process1 = Process(target=run_from_custom_handler)                
    process2 = Process(target=run_slack_socket, args=(slack_app_token,))
    process1.start()
    process2.start()
    process1.join()
    process2.join()
```

I understand that Bolt for Python utilizes threads, does this mean that if I deploy the default flask development server without uWSGI on AWS, I will consistently have latency issues?

**Comment by seratch** [comment]
@srajoo It seems you're using Socket Mode, which connects to Slack via a WebSocket connection. Thus, you cannot use uWSGI for running the process. If your app server does not allow utilizing threads, the restriction can affect the Socket Mode process too, but it is not a common situation. If you want to use Socket Mode for Slack event handling while running a different Flask web app, I'd suggest having two dedicated app instances: 1 - Docker container that runs Socket Mode client 2 - Flask web app to serve public endpoints (e.g., web pages, Slack installation flow). Even when you run two instances, it'd be possible to share InstallationStore among them as long as the underlying database is accessible via network.

Your question is a different one from the original question here. If you need more help, please create a new question issue for it. I hope you'll figure the cause of your situation out soon!

**Comment by srajoo** [comment]
@seratch Ah yes, I understand the difference now. Thank you. I'll keep digging and create a new question if need be.
