### ISSUE TITLE
Using loguru logger is not supported

### ISSUE THREAD

**Issue by eddyg** [slackapi/bolt-python#234]
#### The `slack_bolt` version

```
❯ pip list | grep -E 'slack|loguru'
Python 3.8.7
loguru            0.5.3
slack-bolt        1.3.0
slack-sdk         3.3.0
```

#### Python runtime version

```
❯ python --version; pip list | grep -E 'slack|loguru'
Python 3.8.7
```

#### OS info

```
❯ sw_vers; uname -v
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H114
Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64
```

#### Steps to reproduce:

I'm new to `bolt-python` (having extensively using `slackclient` previously) so I apologize if I'm missing something obvious.

**Note:** you'll need [Loguru](https://loguru.readthedocs.io) installed in your venv.

I tried to run this simple example:

```python
import os

from loguru import logger

from slack_bolt import Say, BoltResponse
from slack_bolt.app.async_app import AsyncApp
from slack_bolt.adapter.socket_mode.async_handler import AsyncSocketModeHandler

app = AsyncApp(token=os.environ["SLACK_BOT_TOKEN"])


@app.message("test")
async def reply_to_test(say: Say) -> BoltResponse:
    await say("Yes, testing is important")


async def main():
    handler = AsyncSocketModeHandler(
        app=app,
        app_token=os.environ["SLACK_APP_TOKEN"],
        logger=logger
    )
    await handler.start_async()

if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
```

but it does not process any events.

### Expected result:

App connects and processes events.

### Actual result:

```
❯ python bolt-test.py
2021-02-08 16:02:54.012 | INFO     | slack_sdk.socket_mode.aiohttp:connect:172 - A new session has been established
⚡️ Bolt app is running!
2021-02-08 16:03:14.021 | INFO     | slack_sdk.socket_mode.aiohttp:monitor_current_session:107 - The session seems to be already closed. Going to reconnect...
2021-02-08 16:03:14.245 | INFO     | slack_sdk.socket_mode.aiohttp:connect:172 - A new session has been established
2021-02-08 16:03:14.246 | INFO     | slack_sdk.socket_mode.aiohttp:connect:184 - The old session has been abandoned
2021-02-08 16:03:34.254 | INFO     | slack_sdk.socket_mode.aiohttp:monitor_current_session:107 - The session seems to be already closed. Going to reconnect...
2021-02-08 16:03:34.852 | INFO     | slack_sdk.socket_mode.aiohttp:connect:172 - A new session has been established
2021-02-08 16:03:34.853 | INFO     | slack_sdk.socket_mode.aiohttp:connect:184 - The old session has been abandoned
2021-02-08 16:03:54.860 | INFO     | slack_sdk.socket_mode.aiohttp:monitor_current_session:107 - The session seems to be already closed. Going to reconnect...
2021-02-08 16:03:55.085 | INFO     | slack_sdk.socket_mode.aiohttp:connect:172 - A new session has been established
2021-02-08 16:03:55.085 | INFO     | slack_sdk.socket_mode.aiohttp:connect:184 - The old session has been abandoned
```

For the longest time, this is all I could get anything I tried with Bolt to do! I *finally* figured out that if I remove `logger=logger` when calling `AsyncSocketModeHandler`, the app runs, and events are processed.

I'm not sure if this is an issue in **Loguru** or not; it claims to be _"Asynchronous, Thread-safe, Multiprocess-safe"_, so I'm opening the issue here.

P.S. It's kind of odd (to me) that `get_boot_message()` is sometimes `print`ed instead of just always being logged.

**Comment by seratch** [comment]
@eddyg Thanks for taking the time to share this!

At this point, this library supports only the standard `logging` module inside the framework. Supporting loguru is not a priority for us but we are open to any ideas to enhance Bolt. Probably, if we have an internal logger wrapper instead of directly relying on `logging` module interface, we can support non standard logging libraries as well.

>I'm not sure if this is an issue in Loguru or not; it claims to be "Asynchronous, Thread-safe, Multiprocess-safe", so I'm opening the issue here.

The issue you faced is Loguru specific but checking https://github.com/slackapi/bolt-python/issues/219 should be helpful to understand more about the current state around logging in asyncio-based apps.

>P.S. It's kind of odd (to me) that get_boot_message() is sometimes printed instead of just always being logged.

This is due to your logging configuration. If Bolt cannot find a valid logging settings (for instance, you use loguru instead here), the framework falls back to stdout.

**Comment by eddyg** [comment]
Thank you for taking the time to reply, and for linking to the other logging issue. I should have thought to search through closed issues related to async logging before wasting time with a new, similar issue. My apologies.

At least now I understand about the boot message going to stdout. :wink: Thanks again. Feel free to close this issue. (I would close it myself, but because of the tags you applied I'm not sure if you prefer to do it yourself, etc. so I'll leave it open.)

**Comment by seratch** [comment]
Thanks for your response. You can close your issues (the labels will be automatically updated)
