### ISSUE TITLE
Is there a way to use global middleware to stop event processing?

### ISSUE THREAD

**Issue by eddyg** [slackapi/bolt-python#235]
The docs for [Global middleware](https://slack.dev/bolt-python/concepts#global-middleware) say:

> Both global and listener middleware must call `next()` to pass control of the execution chain to the next middleware.

I'm looking for a way to use global middleware as a type of "event filter". For example, one use case is checking a list of users that the bot should ignore. Having a way to do this globally (basically, a way to "stop event processing, don't continue") would be easier than having to set a flag in the `context` dict and checking it in every event handler.

Thanks for any insight.

**Comment by seratch** [comment]
@eddyg You can use global middleware for the purpose!

```python
allowed_user_ids = ["U12345XYZ"]

@app.middleware  # or @app.use
def verify_allowed_users(context: BoltContext, next):
    if context.user_id in allowed_user_ids:
        # continue only when an event generated by a known user
        return next()
    return BoltResponse(status=401, body="unknown user detected")

@app.event("app_mention")
@app.event("message")
def handle_events(event, say):
    # do something here
    pass
```

**Comment by eddyg** [comment]
Ah, that's the part I was missing! Thanks for the example. Does the value of the `status` code have any effect?

I have a couple somewhat related questions, so I'm going to ask here (if you'd prefer a new issue, let me know):

When I asked our Slack Admins to approve my app development instance for installation in our Workspace, I selected all of the scopes that I expected to need for the complete project. (This is much easier and has much less administrative overhead than adding each scope individually as-needed and submitting a new request to re-install the app each time.)

Since I am in the early stages of implementation, obviously there are scopes that aren't implemented yet. Is there some way to create a global "catch all" for unhandled events so my app can log `"Not yet implemented: {event_type}"` (and acknowledge the event to the API)? I know this situation is handled by Bolt internally, but I'd like to be able to just catch everything and log it as a reminder. (I know I can see an "Unhandled request" warning logged by Bolt's `async_dispatch`, but it would be nice to have a catch-all in the app.) 

Also, I've noticed that sometimes the API is re-sending events to my app with a "timeout" `retry_reason`, incrementing the `retry_attempt` value. Specifically, I've noticed this with "app mentions", where I process the `app_mention` event, but I _also_ receive `message` events, and those are the ones that the API is re-sending. What is the "best practice" for dealing with this in Bolt?

Thanks again for taking the time to answer my questions as I come up to speed on using Bolt!

**Comment by seratch** [comment]
> Does the value of the status code have any effect?

Your app returns the HTTP status code as long as you use [HTTP mode](https://api.slack.com/apis/connections).

>Is there some way to create a global "catch all" for unhandled events so my app can log "Not yet implemented: {event_type}" (and acknowledge the event to the API)? I know this situation is handled by Bolt internally, but I'd like to be able to just catch everything and log it as a reminder. (I know I can see an "Unhandled request" warning logged by Bolt's async_dispatch, but it would be nice to have a catch-all in the app.)

As long as your app already has `commands` scope, your app can add slash commands / shortcuts after the app installation. Adding new commands does not re-installation. It's the same for event subscriptions. You need to have all necessary scopes before installation but you do not need to turn subscriptions on if your app is not ready for it. So, my primary recommendation is to enable a functionality when it's ready.

If you really need to add functionalities in advance, you can use a global middleware for acknowledging requests from Slack. You can have a line `return BoltResponse(status=200, body="")` to do this. As long as your app returns 200 OK in response to incoming requests, you won't receive retried requests.

But the situation where an end-user does not get any response from the app may be confusing or awkward. For interactivity features such as slash commands, shortcuts, app_mention events, your app should send a reply message or open a modal in response to user actions.

```python
@app.command("/run-something")
def run_something(ack):
    ack("Thanks for using this command! We're still working on this feature. Stay tuned!")

@app.shortcut("submit-request")
def submit_request(client):
    # open a modal, which tells end-users the feature is not ready yet
    client.views_open(...)
```

>What is the "best practice" for dealing with this in Bolt?

You can have multiple event listeners. As long as your listeners match the event types, Bolt automatically acknowledges the incoming requests for you.

```python
@app.event("app_mention")
def handle_app_mention_events(event, say):
    # do something meaningful here

@app.event("message")
def handle_app_message_events(event):
    # do something meaningful here
```

If you do not have anything to do at the moment (say, you're going to implement the feature later), you can disable the event subscriptions in [the Slack app admin pages](https://api.slack.com/apps) or have a simple listener which just matches and does nothing.

```python
@app.event("message")
def just_ack(event):
    # do nothing - just for acknowledgement
    pass
```

**Comment by eddyg** [comment]
> Your app returns the HTTP status code as long as you use HTTP mode.

Oops, I should have clarified: does the `status` value returned by my app have any effect in [Socket Mode](https://api.slack.com/apis/connections#socket)?

> Adding new commands does not re-installation. It's the same for event subscriptions. You need to have all necessary scopes before installation but you do not need to turn subscriptions on if your app is not ready for it.

A-ha! 💡 Now I understand the difference between scopes and subscriptions! Thanks.

> So, my primary recommendation is to enable a functionality when it's ready.

Yes, this makes sense and is less work than trying to (temporarily) deal with unwanted event types. 😄

> As long as your app returns 200 OK in response to incoming requests, you won't receive retried requests.

Great to know. 👍

> But the situation where an end-user does not get any response from the app may be confusing or awkward.

A very good point!

*Re: `app_mention` and `message` events with the same message contents:*

> You can have multiple event listeners.

It seems like if a bot has `message:*` scopes, there's probably not much need to subscribe to `app_mention` events? (Trying to think of a case where it would be beneficial/useful to deal with processing both.)

> If you do not have anything to do at the moment (say, you're going to implement the feature later), you can disable the event subscriptions in the Slack app admin pages or have a simple listener which just matches and does nothing.

Appreciate the insight here.

Out of curiosity, your `just_ack` example made me think of another question: when is it necessary to *explicitly* call `ack()`? Is that only if there's a chance my event handler won't return within ~3 seconds, or are there other reasons to explicitly call it? For example, I was looking at [this test code](https://github.com/slackapi/bolt-python/blob/main/tests/scenario_tests/test_app_using_methods_in_class.py#L166-L209) and noticed it always calls `ack()`.

As always, thanks for your time!

**Comment by seratch** [comment]
>Oops, I should have clarified: does the status value returned by my app have any effect in Socket Mode?

Yes, it does if it's not 200.

>It seems like if a bot has message:* scopes, there's probably not much need to subscribe to app_mention events? (Trying to think of a case where it would be beneficial/useful to deal with processing both.)

It depends what you want to do but in general, your app may not need to subscribe to `app_mention` along with `message` events. Subscribing to `app_mention` events can be beneficial for apps that are interested in only mentioned messages.

>when is it necessary to explicitly call ack()? Is that only if there's a chance my event handler won't return within ~3 seconds, or are there other reasons to explicitly call it?

Only Bolt does automatic acknowledgement for `app.event` listeners. For other types of listeners, having `ack()` calls in a listener is required.

**Comment by seratch** [comment]
Sorry, the above comment was initially confusing. I've updated it.

**Comment by eddyg** [comment]
Thank you, Kazuhiro-san, for your time and explanations!
