### ISSUE TITLE
Req: Support matching multiple message events

### ISSUE THREAD

**Issue by eddyg** [slackapi/bolt-python#239]
If a message contains multiple matches, it seems that Bolt will only call the first message handler that matches, and then stop processing the `message` event.

I would like to see Bolt have a way to continue handling other message events. 

### Category

* [X] **slack_bolt.App** and/or its core components
* [X] **slack_bolt.async_app.AsyncApp** and/or its core components

### Example

```python
    @app.message("ping")
    async def message_ping(self, message: Dict, say: AsyncSay):
        await say("Pong!")

    @app.message("pong")
    async def message_pong(self, message: Dict, say: AsyncSay):
        await say("Ping!")
```

If I send the message **Testing ping pong responders**, I expect Bolt to respond _twice_, `say`ing both **Pong!** and **Ping!**, but it only returns **Pong!**

This is a silly example meant to demonstrate the issue, but there are real-world use cases where a message can contain multiple "triggers" that should all be processed by the app.

I'm thinking that this could be implemented like middleware, where message handlers could (optionally) call `next()` to have Bolt continue processing _other_ message handlers.

_(Unfortunately this is a blocking issue for me, so if you have any ideas on how to work around it, I'm open to suggestions!)_

**Comment by seratch** [comment]
Bolt intentionally ignores events generated by the same app's bot user. This is useful for preventing a common infinite-loop situation where your bot user endlessly replies to its own messages in a channel.

For instance, if the following code works, the Bolt app get stuck in a loop. A similar situation may easily arise.

```python
@app.message("ping")
def handle_ping(event, say):
    say(f"pong >{event['text']}")

@app.message("pong")
def handle_pong(event, say):
    say(f"ping >{event['text']}")
```

The safeguard for this is implemented as a built-in middleware.

* https://github.com/slackapi/bolt-python/blob/v1.3.2/slack_bolt/app/async_app.py#L290
* https://github.com/slackapi/bolt-python/blob/v1.3.2/slack_bolt/middleware/ignoring_self_events/async_ignoring_self_events.py

>there are real-world use cases where a message can contain multiple "triggers" that should all be processed by the app.

If the message is not for your end-users, I don't recommend posting the message in a channel. As your app already know the current state of the task, the app should be able to manage it without posting unnecessary messages in Slack.

For kicking off or running multiple operations, you can use [lazy listener functions](https://slack.dev/bolt-python/concepts#lazy-listeners) as a handy way. The feature is implemented mainly for FaaS support but it's useful for non-FaaS apps too (it uses threads by default). Although the document says it's in beta, it just means we haven't decided to implement the same feature in other Bolt frameworks (JavaScript, Java). 

```python
def accept(say):
    say("We'll update you when the task is completed!")

def start_new_task(entity, say):
    # pseudo code
    task_database.insert(entity)
    # another thread watches the database updates

app.message("trigger something")(
    ack=accept,
    lazy=[start_new_task]
)

def run_task():
    # check if there is a new row in task database
    pass

task_processor = Thread(run_task)
task_processor.start()
```

or 

```python
def accept(say):
    say("We'll update you when the task is completed!")

def run_multi_step_task(event, say):
    # step 1
    # step 2
    say("Completed!")

app.message("trigger something")(
    ack=accept,
    lazy=[run_multi_step_task]
)
```

Another solution is that simply continuing to run your workflow after `ack()` call. For Events API, `ack()` call is automatically done by Bolt at the beginning of listener execution. This does not cause 3 second timeout errors.

```python
def run_task(event, say):
    say("We'll update you when the task is completed!")
    # step 1
    # step 2
    say("Completed!")

app.message("trigger something")(run_task)
```

If you need to run multi-step operations, as the above pseudo code shows, your app may want to have a kind of task manager or task queue in your app. In any case, posting a message only for triggering your app's code is not the only way to go and I don't recommend the approach from user experience perspective.

**Comment by eddyg** [comment]
Wow, thanks for the comprehensive reply. 👍 

I totally understand the importance of a bot not responding to its own messages! 🤖

I think I may have explained my issue poorly, or at least used a bad example. 😮 I'm going to try again:

-----

Let's say I have handlers for two keywords, _both_ of which generate different publicly-visible in-channel responses when they are detected in a message.

```python
@app.message(re.compile(r"\bBug \d+\b", re.I))
...

@app.message(re.compile(r"\bCase \d+\b", re.I))
...
```

i.e. if somebody say `Can somebody look at bug 314?`, the bot replies with a message linking to "bug 314". Similarly if somebody says `Check case 2778 first`, the bot replies with a link to "case 2778". The problem is, the bot I'm trying to replace will respond to **both** triggers when somebody says them _in the same message_: `Need 👀 on bug 456 (which is related to case 5150)` would result in links to the bug **and** case being posted to the channel by the bot.

_However_, with the way Bolt processes listeners, it's "first match wins", so as soon as a listener returns a response, _it stops processing any further listeners_. (I think it's [this code](https://github.com/slackapi/bolt-python/blob/main/slack_bolt/app/async_app.py#L427-L428) that's exiting the loop.)

So, this feature request is to have some way for listeners to indicate to he `for listener in self._async_listeners` loop to continue, and run the other listeners, _even if the listener generated a response_.

Does that make more sense?

**Comment by seratch** [comment]
Thanks for elaborating on your need. I'm sure now I understand your use case. 

>So, this feature request is to have some way for listeners to indicate to he for listener in self._async_listeners loop to continue, and run the other listeners, even if the listener generated a response.

In Bolt for Python, we are not planning to apply this change at this point. Of course, it's possible to loosen the limit. However, fundamentally speaking , only one listener should be responsible for responding to an incoming request. In other words, `ack()` should be done only once (in the case of Events API, it's done under the hood). Changing this assumption may cause confusion (say, your secondary matched function wanted to respond with 400 Bad Request but the primary one already returned a successful response).

Therefore, my suggestion for this use case is to use a pattern that matches both "bug" and "case" like `@app.message(re.compile(r"(Bug|Case)\b+\d+", re.I))` and to extract multiple bug/case numbers inside the listener.

**Comment by eddyg** [comment]
Thanks for the prompt reply!

Given that Bolt is the only Events API library I've found with Socket Mode and Async support, I'm thinking of how to work around this for my use case. (I _really_ don't want to roll my own Socket Mode Async Event API library if I can help it!)

The bot I'm trying to modernize has (literally) _dozens and dozens_ of individual classes, each with a unique purpose and several message listeners. It would be _very_ messy to combine them all.

Given the "single `ack()` per event" architecture of Bolt, I'm thinking one approach might be something like this:

_Don't_ use any `@app.message` listeners at all. Instead, I'm thinking I could use a single `@app.event("message")` listener. I would register each of the internal keyword handlers to my own list of "matchers", then have the single "message" handler test for matches, call all the handlers that trigger a match, and then finally, combine multiple responses into a _single_ Block Kit-based response so I only send _one_ message.

**Comment by seratch** [comment]
I do not know about your app but probably the approach may work well.

One thing I can suggest is that your app may want to filter subtypes this way:

```python
@app.event({"type": "message", "subtype": (None, "bot_message")})
def handle_only_new_messages(event):
    your_own_message_processor.handle(event)

@app.event("message")
def acknowledge_other_message_subtypes():
    # just for acknowledging other subtypes
    pass
```

The `handle_only_new_messages` handler matches only newly posted messages. If you want to handle others as well, you can add more subtypes to the tuple in the constraints. See https://api.slack.com/events/message#message-event-type__message-subtypes for the list of available subtypes.

**Comment by eddyg** [comment]
I'm going to go ahead and give this approach a try. Thanks for the tip about filtering out messages!

Can you provide any context about [this comment](https://github.com/slackapi/bolt-python/blob/v1.3.2/slack_bolt/app/async_app.py#L564)?
```
    # As of Jan 2021, most bot messages no longer have the subtype bot_message.
```


If I want to ignore any events from a "bot", is there an easy way to look at the `is_bot` field in the `authorizations` section of the Events [metadata](https://api.slack.com/apis/connections/events-api#receiving_events)? Would it be possible to use global middleware to just "skip" all events where `is_bot` is `True`?

**Comment by seratch** [comment]
>Can you provide any context about this comment?

The second line in the comment was a bit unclear. I just updated the line. The reason why there are two patterns is Slack app's permission model migration: https://api.slack.com/authentication/token-types#bot

Messages posted by most apps with the current permission model don't have the subtype. On the other hand, messages by ["classic" apps](https://api.slack.com/authentication/migration) always have the subtype. Other apps in a workspace may send a message with the subtype.

>If I want to ignore any events from a "bot", is there an easy way to look at the is_bot field in the authorizations section of the Events metadata? Would it be possible to use global middleware to just "skip" all events where is_bot is True?

The `is_bot` flag under `authorizations` is not suitable for the purpose. The flag tells whether an event is a **bot event**. Here is a screenshot of Slack app configuration page: 
<img width="600" src="https://user-images.githubusercontent.com/19658/107893538-34a1bd00-6f6f-11eb-9f83-c88e6a19e7c9.png">
Most apps utilize bot events to receive notifications from Slack. In this case, `is_bot` is always true. If an event is the one on behalf of users, the field is false.

If you want to have a global middleware that does the same with the listener matcher I shared above, the code can be like this:

```python
from slack_bolt import BoltResponse

@app.middleware
def skip_bot_message_events(body, logger, next):
    event = body.get("event", {})
    is_message_event = event.get("type") == "message"
    is_bot_message = event.get("subtype") is None and event.get("bot_id") is not None
    is_classic_bot_message = event.get("subtype") == "bot_message"
    if is_message_event and (is_bot_message or is_classic_bot_message):
        # just acknowledge the request
        logger.debug("Skipped a message from a bot user")
        return BoltResponse(status=200, body="")
    # continue processing
    next()
```

**Comment by eddyg** [comment]
Thank you (as always!) for the informative reply.

I also very much appreciate you taking the time to provide a working `skip_bot_message_events` global middleware example! (One less thing to worry about in all the individual listeners. 🎉)

Your time is _very_ much appreciated.

The question in my original issue has been answered, and it has now drifted off-course (my fault!) so I'm going to close it. _Thanks again!_
