### ISSUE TITLE
Multi-select menu element initial_options fail to load options in different option_groups

### ISSUE THREAD

**Issue by tmvy** [slackapi/bolt-python#242]
#### The `slack_bolt` version

slack-bolt==1.3.2
slack-sdk==3.3.2

#### Python runtime version

Python 3.7.2

#### OS info

Microsoft Windows [Version 10.0.19042.685]

#### Steps to reproduce:

Copy the self-contained example below to a new file and run (i.e. `python reproducible_example.py`). No additional setup required. As in the [Bolt for Python tutorial](https://slack.dev/bolt-python/tutorial/getting-started), set the `SLACK_BOT_TOKEN` and `SLACK_SIGNING_SECRET` environment variables for a Slack app that has the home tab and event subscriptions enabled.

The example below responds to the [`@app.event("app_home_opened")`](https://api.slack.com/events/app_home_opened) event, so trigger it by switching focus back and forth from the app's home tab to another channel.

```py
# reproducible_example.py

import os

from slack_bolt import App
from slack_sdk.models.blocks.basic_components import Option, OptionGroup
from slack_sdk.models.blocks.block_elements import StaticMultiSelectElement
from slack_sdk.models.blocks.blocks import InputBlock
from slack_sdk.models.views import View

app = App(
    token=os.environ.get("SLACK_BOT_TOKEN"),
    signing_secret=os.environ.get("SLACK_SIGNING_SECRET"),
)

option_1 = Option(label="Option 1", value="option_1")
option_2 = Option(label="Option 2", value="option_2")
option_3 = Option(label="Option 3", value="option_3")

options_without_group = [option_1, option_2]

options_with_groups = [
    OptionGroup(label="Group A", options=[option_1, option_2]),
    OptionGroup(label="Group B", options=[option_3]),
]

# ✔ Works as expected
initial_options_in_no_groups = {
    "options": options_without_group,
    "initial_options": [option_1, option_2],
}

# ✔ Works as expected
initial_options_in_same_group = {
    "option_groups": options_with_groups,
    "initial_options": [option_1, option_2],
}

# ❌ Fails with SlackApiError
# [ERROR] must be one of the provided options
# [json-pointer:view/blocks/0/element/initial_options]
initial_options_not_in_same_group = {
    "option_groups": options_with_groups,
    "initial_options": [option_1, option_3],
}


# inputs = initial_options_in_no_groups
# inputs = initial_options_in_same_group
inputs = initial_options_not_in_same_group

"""
Uncomment the inputs above to test the alternate scenarios

Note that initial_options is type Sequence[Option] so passing
an initial option group is not supported.
This is also consistent with the Block Kit reference:

initial_options: An array of option objects that exactly match
one or more of the options within options or option_groups.
https://api.slack.com/reference/block-kit/block-elements#static_multi_select
"""

home_tab = View(
    type="home",
    blocks=[
        InputBlock(
            label="Static multi select element",
            element=StaticMultiSelectElement(**inputs),
        ),
    ],
)


@app.event("app_home_opened")
def event_app_home_opened(client, event, ack):
    client.views_publish(user_id=event["user"], view=home_tab)
    ack()


if __name__ == "__main__":
    app.start(port=3000)

```

### Expected result:

The expected behaviour is for the static multi-select element in the app home, on loading, to be populated with the provided `initial_options` arguments, as described at [Block Kit > Reference: Block elements > Multi-select menu element > Static options> `initial_options`](https://api.slack.com/reference/block-kit/block-elements#:~:text=match%20one%20or%20more%20of%20the%20options%20within%20options%20or%20option_groups).

> An array of option objects that exactly match one or more of the options within `options` or `option_groups`. These options will be selected when the menu initially loads.

This works as described/expected for options with no groups (in the example, set `inputs = initial_options_in_no_groups`), or options in the same group (`inputs = initial_options_in_same_group`, the result of which is shown below).

![image](https://user-images.githubusercontent.com/61309188/108432811-df023480-723c-11eb-8c31-4ea7895cca28.png)

The expected result for the scenario where `inputs = initial_options_not_in_same_group` would be as in the image above, except for Option 1 and Option 3 to be ticked. However the actual result for this scenario is as below.

### Actual result:

The app fails to load the `initial_options` and a `SlackApiError` is raised. This creates an obstacle for apps that depend on stateful multi-select elements that use option groups. Note that this only happens when one or more initial options is in a different group to another initial option, as shown in the alternate scenarios of the example.

![image](https://user-images.githubusercontent.com/61309188/108432773-d578cc80-723c-11eb-80f8-9230cea722ea.png)

```log
slack_sdk.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'invalid_arguments', 'response_metadata': {'messages': ['[ERROR] must be one of the provided options [json-pointer:view/blocks/0/element/initial_options]']}}
```

The severity of the impact that this can have on an app might not be clear here, however it is significant in my use case which requires the state of the selected options to be loaded each time the user leaves and returns to the app. In my app `initial_options` is repopulated dynamically based on the user's choices, which are persisted between visits. At present I have been able to implement this by using  `options` rather than `option_groups` , but the quality of the user experience suffers where several options are not grouped in the menu drop-down list.

The issue here is that multi-select element initial options appear not to support multiple options that belong to different groups.

A related question to this issue is: would it be correct to assume that `initial_options` is the optimal way to load a multi-select element with predefined state (as I had been doing when encountering this issue), or is there another method intended for this?

**Comment by mwbrooks** [comment]
Hi @tmvy, thanks a lot for taking the time to share the detailed issue! We've been able to reproduce your issue and @seratch also reproduced it using the [Block Kit Builder app](https://app.slack.com/block-kit-builder/).

This is a server-side issue and **I've escalated it to the Slack Platform team** (linking back to this issue).

**If you're okay with it, I'd like to close this issue.** We're unable to fix the issue with the Bolt Framework and we're unable to estimate when the Slack Platform team will release the fix. The best way to stay informed of an update is to [subscribe to the Slack API Changelog](https://api.slack.com/changelog) - you can even subscribe to the feed inside Slack.

**Comment by tmvy** [comment]
Great, many thanks. Yes, happy to close this issue and await a resolution from the Slack Platform team.
