### ISSUE TITLE
Issues with bolt, flask, python, and socket mode

### ISSUE THREAD

**Issue by Roblrobl** [slackapi/bolt-python#249]
Apologies for the newbie question, I tried feedback@slack.com for our paid plan, and they referred me here.

I'm trying to use bolt with python and socket mode for some internal apps, as our company is behind a firewall. After hacking for a bit with bolt and socket mode, I was only able to get it to work if I did:

```python
from slack_bolt.adapter.socket_mode import SocketModeHandler
app = App(token=token, signing_secret=signing_secret)
handler = SocketModeHandler(app, app_token)
```

Realizing I needed to make this handle web requests, I decided to learn Flask and have started with:

```python
from slack_bolt.adapter.flask import SlackRequestHandler
app = App()
from flask import request
from flask import Flask
flask_app = Flask(__name__)
handler = SlackRequestHandler(app)
```

But here I appear to be stuck. I'm getting:

>DEBUG:slack_sdk.web.slack_response:Received the following response - status: 200, headers: {'date': 'Mon, 01 Mar 2021 02:15:03 GMT', 'server': 'Apache', 'x-xss-protection': '0', 'pragma': ....

But I'm not getting the hello message that Socket mode sees. Same issue occurs with "out of the box" example from https://github.com/slackapi/bolt-python/blob/main/examples/flask/app.py. Running flask in development mode is showing the simple web page I described for /, so that part seems to be working ok.

Any ideas on what I'm doing wrong or how to fix it? Thank you for any help!

**Comment by seratch** [comment]
HI @Roblrobl , the part is not included in your code snippet but probably you're using `SocketModeHandler#start()` method to start your Socket Mode app. This method blocks the current thread. If you want to run a web app server in the same process, you can use `SocketModeHandler#connect()` instead. 

Here is a simple example to run Socket Mode event handlers along with OAuth flow web endpoint hosting in a single process: https://github.com/slackapi/bolt-python/blob/v1.4.1/examples/socket_mode_oauth.py#L123-L124

Also, if you are going to use `slack_bolt.adapter.flask.SlackRequestHandler` only for OAuth flow handling, that's totally fine! However, if you are planning to use [Events API over HTTP (Flask) and Socket Mode](https://api.slack.com/apis/connections) at the same time, unfortunately it's not possible. If you just want to serve web pages in the same app, you don't need to use the Flask adapter. This means running a Flask app without any adapters. You can run Flask app after calling `SocketModeHandler#connect()`.

**Comment by Roblrobl** [comment]
Hi @seratch , thank you for the quick response! 

Correct, I left some bits out for brevity and was using SocketModeHandler.start() for my socket mode testing. The socket mode example you have looks good, but I'm confused a bit on your statement that it's not possible to use events api over http (flask) and socket mode at the same time. But then you mention I can without adapters and not sure what that means. 

The Flask example at https://github.com/slackapi/bolt-python/blob/v1.4.1/examples/flask/app.py uses the SlackRequestHandler as you note - I take it that is different than SocketMode? If so, any idea on why that isn't working for me? Or is it not functional yet? What do you mean by Flask adapter? Apologies for my newness, just starting with Flask too. :) That doesn't have a handler.start() function so I'm not sure what kicks things off to get stuff started with Flask then looping and kicking slack connection open.

You're correct that I want to handle slack, socketmode, python, bolt in an easy fashion, and serve up web pages. Likely to place it under WSGI and Apache, along with some simple LDAP authentication and session handling. Just not sure what you mean by a Flask app without any adapters??

**Comment by seratch** [comment]
@Roblrobl Thanks for sharing more about what you're struggling to understand.

Before talking about the details of Bolt for Python, understanding the difference between Socket Mode and Events over HTTP (a.k.a. HTTP Mode) should be helpful for you.

Socket Mode allows your app to receive any Slack events (Events API data, user actions such as button click, modal data submission, and slash command invocation) **through a WebSocket connection**. Thus, when you run a simple Socket Mode app, your app doesn't need to serve any web endpoints. 

On the other hand, Events over HTTP (or HTTP Mode) requires to set up a web app server and host a public web endpoint to receive data from Slack. This endpoint is **Request URL** in the Slack app configuration pages. If you switch to HTTP Mode, you will set the Request URL to `https://{your public domain}/slack/events` (`/slack/events` is the default path by Bolt). For this use case, you can use Flask web framework along with Bolt's Flask adapter (`slack_bolt.adapter.flask.SlackRequestHandler`). 

>I'm confused a bit on your statement that it's not possible to use events api over http (flask) and socket mode at the same time. 

This means you have to choose either of these two ways to connect to Slack. Your app cannot receive events as both WebSocket messages and HTTP requests at the same time. Thus, `slack_bolt.adapter.flask.SlackRequestHandler` is useless as long as you go with Socket Mode.

>But then you mention I can without adapters and not sure what that means
> Just not sure what you mean by a Flask app without any adapters??

This means, if you want to run a web app which does not handle any HTTP requests related to Slack, you can run a plain Flask web app without any extra configuration or anything specific to Slack. For instance,

> serve up web pages. Likely to place it under WSGI and Apache, along with some simple LDAP authentication and session handling.

for this requirements, the web app does not require `slack-bolt` and its underlying `slack-sdk` PyPI packages.

I hope this is helpful to you.

**Comment by Roblrobl** [comment]
@seratch , awesome, thank you so much for the clarification! This really helps a lot. Can I check to see if I understand?

1. My slack bot will only run under socket mode and never through a request URL due to our corporate firewall. I'll listen to many different events and make web calls to write back to the user, have an app home tab, etc.
2. I'd like to host a web app associated with the bot, and ideally combine the 2 processes. Combined app would then be apache, WSGI, python, bolt, flask and some other junk ... sounds like your suggestion here is to slack_bolt.adapter.socket_mode, get that going, and then do the Flask initialization. Is this correct? It seems to me that using SocketModeHandler.start() starts the event loop. Would that not prevent Flask's event loop from running? I see some bits about async mode there too, but not sure how that fits in.
3.  One issue I had with my first test with slack_bolt.adapter.socket_mode is that the code seems to call Event().start(). I'd like to register other events - timers, perhaps listen to another socket for command line access, etc. But as Event() was not assigned to anything by the slack library, I didn't see a way to access it. Do you know of a way?
4. Perhaps multiple event loops are not too bad, but I envision needing to save/restore state, and that could require file locking. Multiple event loops could then deadlock on it. ie: consider the slack/bolt stuff needing to lock for write and then the flask stuff needs to do the same, and they step on each other perhaps?
5. Are there any python version dependencies? Right now I have WSGI setup with Apache and Python 3.6, upgrading all of that is a bit painful. (and I'm sure I'll have to sometime, just postponing the pain)
6. For socket mode examples, I see socket_mode, as well as _async and _oath versions. Do you know what the difference is between these 3? Any suggestions for which I should pick based on my use case?

Thank you again for the great help and advice! Now I can drop all the tests on the flask code examples and focus on the socket_mode examples with flask.

**Comment by Roblrobl** [comment]
Aha ... perhaps I need the async version, then wait on the first callback and call asyncio.get_running_loop() and extend that?

I see the open modal and favorite-animal code, any suggestions on how to invoke those from within slack?

Sorry for all the questions & thank you so much for the help!

**Comment by seratch** [comment]
Great to know you've figured your issue out! Let me close this issue now.
