### ISSUE TITLE
How to save variable in python when message is called?

### ISSUE THREAD

**Issue by mae5357** [slackapi/bolt-python#258]
Overview: make a Slack Bot that listens for a message, "Hi". Once the message "Hi" is typed, SlackBot prompts the user ("What's your name: "). The user enters their name. SlackBot reads this input. SlackBot then prompts user ("Where do you live: ") The user enters their location. SlackBot reads this input. Then the bot no longer takes input until the user calls "Hi" again. 

Issue: I am using @app.message("Hi") to listen for a message. Once this message is triggered, the response is all done in a function. I am trying to use a variable as a switch so that when the message is triggered the variable gets updated. But because this is done in a function I am not sure how to have this output. Does anyone have any suggestions or workarounds?

### my code

```python
switcher = 0

#### This will match any message that contains "Hi"
@app.message("Hi")
def message_B(message, say):
  say(
      "what's your name: "
  )
  switcher = 1

    
@app.message("")
def switcher(message, say):
  if switcher ==1: 
    say(
      "where do you live: "
      )
    switcher = 0
```    

### Expected result:

```
user:: "Hi
bot:: "What is your name:"
user:: Sam
Bot:: "Where do you live:"
user:: right here!
```

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by misscoded** [comment]
Hi @mae5357! One possible approach to this scenario would be to store the user responses and use the presence/absence of those values determine what has been answered and which question should be posed next. 

For development using data in memory, using a global `dict` is a suitable option and might look something like the following:

```
user_states = {
  "U0G9QF9C6": { "name": "Alice", "area": None }
 }
```

In the example above, at the top level of the `dict`, we've used the ID of the user ("U0G9QF9C6") as the key. Once we locate the user, if we cycle through the stored responses, we see that `area` has yet to be answered, so we know which question should be served up to them next. 

(One thing to note about the ID that you select as the key: we recommend creating a combination of the user's `team_id` and `user_id`. The reason for this is that `user_id` is _not_ a universal unique identifier, but if you wanted to use `user_id` as you develop locally, it will work just fine.)

We ultimately recommend using a production-ready database to store these records, but this should suffice if you want to prove it out beforehand.

Let me know if that helps and if you have any further questions!

**Comment by mae5357** [comment]
I completely overlooked this option. Thanks!
