### ISSUE TITLE
Getting "Unhandled requests" when a relevant event listener does not exist

### ISSUE THREAD

**Issue by vv-grinko** [slackapi/bolt-python#264]
I'm trying to develop a bot, that wiil be listening new messages from a channel and then do something with a message. For the beggining i want that events like 

```python
@app.event("app_mention")
def event_test(say):
    say("Hi there!")
```
response to Slack. 
But after launch my script and mention the Bot in Slack, i'm getting this:
```
As you gave `client` as well, `token` will be unused.
Unhandled request ({'token': '2oXzB3W1OY2m7ZSHjxUyauVU', 'team_id': 'T01KL149WNB', 'api_app_id': 'A01LC1RAMGA', 'event': {'client_msg_id': '03b37d45-19f4-46b4-9243-62bebd557c3e', 'type': 'message', 'text': '<@U01LCC6NX9Q> hello Bot', 'user': 'U01L10HG1NF', 'ts': '1616407309.002200', 'team': 'T01KL149WNB', 'blocks': [{'type': 'rich_text', 'block_id': 'P3+', 'elements': [{'type': 'rich_text_section', 'elements': [{'type': 'user', 'user_id': 'U01LCC6NX9Q'}, {'type': 'text', 'text': ' hello Bot'}]}]}], 'channel': 'C01L8TGMNMT', 'event_ts': '1616407309.002200', 'channel_type': 'channel'}, 'type': 'event_callback', 'event_id': 'Ev01SQASSEGG', 'event_time': 1616407309, 'authorizations': [{'enterprise_id': None, 'team_id': 'T01KL149WNB', 'user_id': 'U01L10HG1NF', 'is_bot': False, 'is_enterprise_install': False}], 'is_ext_shared_channel': False, 'event_context': '1-message-T01KL149WNB-C01L8TGMNMT'})
```

(after a few seconds i get another 2  same unhandled request)
```
Unhandled request ({'token': '2oXzB3W1OY2m7ZSHjxUyauVU', 'team_id': 'T01KL149WNB', 'api_app_id': 'A01LC1RAMGA', 'event': {'client_msg_id': '03b37d45-19f4-46b4-9243-62bebd557c3e', 'type': 'message', 'text': '<@U01LCC6NX9Q> hello Bot', 'user': 'U01L10HG1NF', 'ts': '1616407309.002200', 'team': 'T01KL149WNB', 'blocks': [{'type': 'rich_text', 'block_id': 'P3+', 'elements': [{'type': 'rich_text_section', 'elements': [{'type': 'user', 'user_id': 'U01LCC6NX9Q'}, {'type': 'text', 'text': ' hello Bot'}]}]}], 'channel': 'C01L8TGMNMT', 'event_ts': '1616407309.002200', 'channel_type': 'channel'}, 'type': 'event_callback', 'event_id': 'Ev01SQASSEGG', 'event_time': 1616407309, 'authorizations': [{'enterprise_id': None, 'team_id': 'T01KL149WNB', 'user_id': 'U01L10HG1NF', 'is_bot': False, 'is_enterprise_install': False}], 'is_ext_shared_channel': False, 'event_context': '1-message-T01KL149WNB-C01L8TGMNMT'})
Unhandled request ({'token': '2oXzB3W1OY2m7ZSHjxUyauVU', 'team_id': 'T01KL149WNB', 'api_app_id': 'A01LC1RAMGA', 'event': {'client_msg_id': '03b37d45-19f4-46b4-9243-62bebd557c3e', 'type': 'message', 'text': '<@U01LCC6NX9Q> hello Bot', 'user': 'U01L10HG1NF', 'ts': '1616407309.002200', 'team': 'T01KL149WNB', 'blocks': [{'type': 'rich_text', 'block_id': 'P3+', 'elements': [{'type': 'rich_text_section', 'elements': [{'type': 'user', 'user_id': 'U01LCC6NX9Q'}, {'type': 'text', 'text': ' hello Bot'}]}]}], 'channel': 'C01L8TGMNMT', 'event_ts': '1616407309.002200', 'channel_type': 'channel'}, 'type': 'event_callback', 'event_id': 'Ev01SQASSEGG', 'event_time': 1616407309, 'authorizations': [{'enterprise_id': None, 'team_id': 'T01KL149WNB', 'user_id': 'U01L10HG1NF', 'is_bot': False, 'is_enterprise_install': False}], 'is_ext_shared_channel': False, 'event_context': '1-message-T01KL149WNB-C01L8TGMNMT'})
```

#### The `slack_bolt` version

```
aiohttp==3.7.4
astroid==2.5
async-timeout==3.0.1
attrs==20.3.0
certifi==2020.12.5
chardet==3.0.4
colorama==0.4.4
idna==2.10
isort==5.7.0
lazy-object-proxy==1.5.2
mccabe==0.6.1
multidict==5.1.0
pylint==2.7.1
requests==2.25.1
six==1.15.0
slack-bolt==1.4.1
slack-sdk==3.4.0
slackclient==2.9.3
toml==0.10.2
typing-extensions==3.7.4.3
urllib3==1.26.3
websocket-client==0.54.0
wrapt==1.12.1
yarl==1.6.3
```

#### Python runtime version

3.9.1

#### OS info

Microsoft Windows [Version 10.0.17763.1757]

#### Steps to reproduce:

```python
import os
import logging
import re
from typing import Callable
from threading import Event
import signal
from slack_bolt import App, Say, BoltContext
from slack_sdk.web import WebClient
from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler

proxy_wired_client = WebClient(
    token=os.environ["SLACK_BOT_TOKEN"],
    proxy="(redacted)"
)
# Install the Slack app and get xoxb- token in advance
app = App(
    client=proxy_wired_client
)


if __name__ == "__main__":
    # Use #connect() instead of #start() here
    SocketModeHandler(app, os.environ["SLACK_APP_TOKEN"]).connect()
    
    signal.signal(signal.SIGINT, signal.SIG_DFL)
    Event().wait()

text = SlackResponse.get(text)

# print(text)
def extract_subtype(body: dict, context: BoltContext, next: Callable):
    context["subtype"] = body.get("event", {}).get("subtype", None)
    next()

@app.command("/hello-socket-mode")
def hello_command(ack, body):
    user_id = body["user_id"]
    ack(f"Hi, <@{user_id}>!")

@app.event("app_mention")
def event_test(say):
    say("Hi there!")
```

### Expected result:

Get 1 hendled request in CMD

### Actual result:

I'm getting 3 unhandled request and the events doesn't work for me.
And what is the meaning "As you gave `client` as well, `token` will be unused."?

P.S. How can i get parametr 'text': '<@U01LCC6NX9Q> hello Bot' from the request?

**Comment by seratch** [comment]
@vv-grinko 
>'type': 'message'

As you can see in the payloads, the events are `message` type ones: https://api.slack.com/events/message
Your app should be subscribing to not only `app_mention` but also `message` events.

>Expected result:
>Get 1 hendled request in CMD

Remove the subscription if you don't need it. If you need both, add the event handler for `message` events.

```python
@app.event("message")
def handle_message_events():
    pass
```

**Comment by andremsousa** [comment]
Hello @seratch,
I'm getting a similar issue (at least with the similiar behavior) but when subscribing to a button click event.
```
@app.action("rating_5")
def action_button_click(body, ack, respond):
    task = get_taskkey_regex(body['message']['blocks'][0]['text']['text'])
    feedbacktoken = get_feedback_token(task)
    response = {
        "response_type": "ephemeral",
        "replace_original": True,
        "text": f"Awesome, we got it! Leave us a comment <{url_string(task,feedbacktoken,'5')}|here!>"
    }
    ack()
    respond(response)
    post_rating(task, '5')
```
When the button is pressed i get a 404 and more 2 404's in the next minutes.
![image](https://user-images.githubusercontent.com/6112942/111981656-dcc31c80-8aff-11eb-9199-3278a0b594a0.png)

How can i avoid this?
Everything is working as expected because the respond function is working properly. I just wanted to get rid of those "false" 404 for logging sake.
Thanks!

**Comment by seratch** [comment]
@andremsousa You issue is not the same one.

>@app.action("rating_5")

Please make sure if the `action_id` which is attached to the button is `rating_5`. If you don't have `action_id` in the block, Slack automatically assign a random ID for it.

Also, enabling debug-level logging may help you understand what's happening in your app. Add the following lines at the beginning of your source code:

```python
import logging
logging.basicConfig(level=logging.DEBUG)
```

**Comment by andremsousa** [comment]
The `action_id` is correctly attached to the button.
This only happens with the `response()` method.
If i use `say()` instead it works correctly.

Will try to debug using the logs.
Thanks!

**Comment by seratch** [comment]
@vv-grinko I'm sure I've provided an answer to your question. If you don't mind, can we close this issue?
@andremsousa Probably, reusing this issue for your question could be confusing for others.

I'm keen to help you both but, using GitHub issue tracker for this type of Q&A may not be an optimal way to use our time. Would you mind continuing our conversations in [**the community Slack workspace**](https://community.slack.com/)? If you are not in the workspace, you can join from [this URL](https://j.mp/community-slack-com).

In the workspace, more and more folks can help you out (of course, I'm also in the workspace!). The channels like [#lang-python](https://app.slack.com/client/TG4KUE8JV/CHL4CLRCZ) or [#tools-bolt](https://app.slack.com/client/TG4KUE8JV/CHY642221) would be good places for Q&A. Please feel free to mention me there. I would appreciate it if you could understand this.

**Comment by vv-grinko** [comment]
> @vv-grinko I'm sure I've provided an answer to your question. If you don't mind, can we close this issue?
> @andremsousa Probably, reusing this issue for your question could be confusing for others.
> 
> I'm keen to help you both but, using GitHub issue tracker for this type of Q&A may not be an optimal way to use our time. Would you mind continuing our conversations in [**the community Slack workspace**](https://community.slack.com/)? If you are not in the workspace, you can join from [this URL](https://j.mp/community-slack-com).
> 
> In the workspace, more and more folks can help you out (of course, I'm also in the workspace!). The channels like [#lang-python](https://app.slack.com/client/TG4KUE8JV/CHL4CLRCZ) or [#tools-bolt](https://app.slack.com/client/TG4KUE8JV/CHY642221) would be good places for Q&A. Please feel free to mention me there. I would appreciate it if you could understand this.

i added  event handler for message events bit it didn't cange anything. Can you show me an axample of how i can work with Slack socket mode?

**Comment by seratch** [comment]
@vv-grinko
Probably, moving the following part to the bottle of your source code should work for you.

```python
if __name__ == "__main__":
    # Use #connect() instead of #start() here
    SocketModeHandler(app, os.environ["SLACK_APP_TOKEN"]).connect()
    
    signal.signal(signal.SIGINT, signal.SIG_DFL)
    Event().wait()
```

Also, you can use `start()` method with the latest version (slack-bolt>=1.4.4).

**Comment by seratch** [comment]
As I've provided an answer to all the questions here, let me close this issue.
