### ISSUE TITLE
Unable to find the documents data types to collect 'User who clicked the workflow' field from the workflow steps.

### ISSUE THREAD

**Issue by Shadrocks** [slackapi/bolt-python#265]
Unable to find the documents data types to collect 'User who clicked the workflow' field from the workflow steps.

### Reproducible in:
python 3.8

#### The `slack_bolt` version

slack-bolt==1.3.1
slack-sdk==3.3.1
slackclient==2.9.3
slackeventsapi==2.2.1

Windows 10

#### Steps to reproduce:
Trying to gather the input needed to collect the "User who selected the <workflow name>" data to respond in future steps but do not know the data type. Continue to get "Type" errors.

```python
blocks = [
        {
            "type": "input",
            "block_id": "slack_user_input", # This is the user_select type from this page https://api.slack.com/reference/block-kit/block-elements#users_select but gives me the type error. 
            "element": {
                "type": "users_select",
                "action_id": "slack_user",
                "placeholder": {"type": "plain_text_input", "text": "Slack User Mention"},
            },
            "label": {"type": "plain_text_input", "text": "Requester Slack account"},
        },
```

### Expected result:

Be able to print the mention name of the user who clicked to open the workflow.

### Actual result:

The server responded with: 

>{'ok': False, 'error': 'invalid_arguments', 'response_metadata': {'messages': ['[ERROR] ust be a valid enum value [json-pointer:/view/blocks/0/label/type]', '[ERROR] failed to match all allowed schemas [ valid enum value [json-pointer:/view/blocks/0/element/placeholder/type]']}}

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
>ailed to match all allowed schemas [ valid enum value [json-pointer:/view/blocks/0/element/placeholder/type]']

For this specific error message, the reason is the invalid `type` for `placeholder` field. Use `"type": "plain_text"` instead of `"type": "plain_text_input"`

>'User who clicked the workflow' field

If this means a user who triggered the workflow (e.g., a user who used the global shortcut as the trigger of the workflow), your custom workflow step needs to ask the workflow creator to embed the variable into one of your app's inputs on the edit modal.

**Comment by seratch** [comment]
@Shadrocks 👋 Let me know if you have something further to ask here. I will close this issue after waiting for your response for a few more days (If this issue is done, please close the issue!).
