### ISSUE TITLE
bot to save a pdf uploaded by the user to host computer

### ISSUE THREAD

**Issue by mae5357** [slackapi/bolt-python#266]
Hello. I would like to create a bot that can read in an uploaded file (pdf) uploaded by the user and save it to a server (for now on the host computer). I am thinking the ```files.info``` method might work, but I am not sure how to get to the specific file. Could you post an example of how to do this?

```
import os
from slack_bolt import App

app = App(
    token= os.environ.get('SLACK_BOT_TOKEN'),
    signing_secret=os.environ.get("SLACK_SIGNING_SECRET")
)


# # # LISTENING FUNCTIONS # # # 
# This will matc h any message that contains "Hi!"
@app.message("Hi!")
def initial_message_func(message, say):
	say("please upload your pdf")


@app.message("")
def message_to_sam_func(client,message):
    client.file.info(file = file_ID)    #not sure how to get file_ID
                                        
```

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
@mae5357 If the `message` argument in `app.message` listeners has attached files, they should have their file IDs. You can pass an ID to [files.info](https://api.slack.com/methods/files.info) for fetching detailed metadata. The files.info response provides url_private_download etc. You can download the content from the URL as long as your HTTP requests have a valid `Authorization: Bearer {your token here}` header. 

Bolt for Python and its underlying Slack SDK do not offer any out-of-the-box module for downloading file data at this point. Please use your favorite HTTP client (say, `requests`?) for it.

**Comment by seratch** [comment]
For your information, the Java SDK project has a simple example demonstrating how to download the file form a file URL.

**Comment by seratch** [comment]
@mae5357 You asked another question. Can you close this issue?

**Comment by mae5357** [comment]
Thank you for posting this code. The only part I cannot make sense of in python is how to get the private url when a file is uploaded? I am trying to do something like this:
```
#!/usr/bin/env python3
# Usage: python3 download_files_from_slack.py <URL>

import sys
import re
import requests

url = " ".join(sys.argv[1:])

token = 'SLACK_TOKEN'
resp = requests.get(url, headers={'Authorization': 'Bearer %s' % token})

headers = resp.headers['content-disposition']
fname = re.findall("filename=(.*?);", headers)[0].strip("'").strip('"')

assert not os.path.exists(fname), print("File already exists. Please remove/rename and re-run")
out_file = open(fname, mode="wb+")
out_file.write(resp.content)
out_file.close()
```
[https://stackoverflow.com/questions/36144761/access-slack-files-from-a-slack-bot](url)


However I am not sure what the url is suppose to be?

**Comment by seratch** [comment]
@mae5357 As the Java SDK example I've shared above demonstrates, a file object has `url_private_download` and you can use the URL for it. You can call files.info with file ID for knowing the URL at any time.

**Comment by mae5357** [comment]
Hello, this is the function I am trying to use. 
```
@app.event("file_shared")
def file_func(payload, client):
    my_file = payload.get('file').get('id')
    print("THIS IS MY INFO:"+ client.files_info(imy_file))
```

however when I run I get this error:
```
ERROR:slack_bolt.App:Failed to run listener function (error: files_info() missing 1 required keyword-only argument: 'file')
```

I am not sure what to try next.

**Comment by seratch** [comment]
@mae5357 
> files_info() missing 1 required keyword-only argument: 'file'

As this error message says, you can use keyword arguments for the method call.

```python
client.files_info(file=my_file)
```

**Comment by mae5357** [comment]
Thank you for the help. Posted final code in case others had issues
```
@app.event("file_shared")
def file_func(payload, client, ack):
    ack()

    #get the file id every time someone uploads a pdf
    my_file = payload.get('file').get('id')
    
    #get the json using files_info
    url = client.files_info(file = my_file).get('file').get('url_private')
    file_name = client.files_info(file = my_file).get('file').get('title')

    # save file
    resp = requests.get(url, headers={'Authorization': 'Bearer %s' % token})
    save_file = Path(file_name)
    save_file.write_bytes(resp.content)
```

**Comment by mauriciogracia** [comment]
In case you need your slack bot to recieve a file shared by DM here a starting point

```
@app.event("message")
def handle_message_events(body, logger):
    # Unhandled request({'type': 'event_callback', 'event': {'type': 'message', 'subtype': 'file_share'}})
    Util.logWarning(body)
```

You need `ngrok` to be running (when in development mode) and you need to enable Event Subscriptions with the URL that ngrok generates automatically.

![imagen](https://user-images.githubusercontent.com/2321661/160003792-b824cebd-0d59-44c6-8d16-3ca3d8d9e6d1.png)

Keep in mind that if you restart ngrok a new URL will be generated

**Comment by masaki-kumamoto** [comment]
Hi @seratch , I am facing a similar but different issue.

```
#Slack download 
def downloadFile():  
        headers = {
            'Authorization': 'Bearer {0}'.format("{{SLACK_OAUTH_TOKEN}}")
        }
        resp = requests.get("https://files.slack.com/files-pri/XXXX/download/modified_image_with_correct_red_circle.png", headers)
        save_file = Path("test.png")
        save_file.write_bytes(resp.content)

downloadFile()
```

resp_content is an HTML file saying below

![image](https://github.com/slackapi/bolt-python/assets/48271717/18274548-3b09-4487-8f0f-dc211c7d7468)

Is there anyway to get the actual target file?

**Comment by seratch** [comment]
@masaki-kumamoto Double-check if the token has the access to the file content. To verify it, you can use https://api.slack.com/methods/files.info/test with the token and file ID. If it works, something in your code could be wrong.

If you need more help from our team, you can create a new issue with more details (e.g., complete code and steps to reproduce the situation) instead of replying further here. Hope you will figure the cause out soon!

**Comment by masaki-kumamoto** [comment]
@seratch Thank you so much for the prompt response!
You were indeed right, I was missing "files:read" permission.

{
    "ok": false,
    "error": "missing_scope",
    "needed": "files:read",
    "provided": "incoming-webhook,app_mentions:read,channels:join,chat:write,conversations.connect:write,reminders:write,channels:history,commands,emoji:read,im:write,files:write,groups:write,links:write,mpim:write,remote_files:write,usergroups:write,users:read,users:read.email,usergroups:read,users.profile:read,workflow.steps:execute,team:read,pins:write,pins:read,reactions:write,reactions:read,channels:read,channels:manage,reminders:read"
}

I saw it in OAuth & Permissions page but I think I need to re-install the app.

![image](https://github.com/slackapi/bolt-python/assets/48271717/1c7603b9-12cb-4365-9fd2-c0c229191ca2)

Thank you so much!

**Comment by masaki-kumamoto** [comment]
Hi @seratch 
I'm now facing another issue after confirming https://api.slack.com/methods/files.info/test is working with the token and file id.

![image](https://github.com/slackapi/bolt-python/assets/48271717/b43cba57-792f-4297-9f7b-253455b7fc71)

It now returns this blank HTML.

![image](https://github.com/slackapi/bolt-python/assets/48271717/4f92eb93-0848-4583-b26d-a23f3d127f79)

Do you have any idea why I can not get the original file? (It is a png file )
