### ISSUE TITLE
None values from event Slack

### ISSUE THREAD

**Issue by vv-grinko** [slackapi/bolt-python#269]
I have event listener:
```
@app.event("message")
def message(payload):
    event = payload.get("event", {})
    channel_id = event.get("channel")
    user_id = event.get("user")
    text = event.get("text")
    user_id = event.get("user")
    print(user_id,text,channel_id)
```

When i type something in Slack i'm getting None values from the event, why?

**Comment by seratch** [comment]
Hi @vv-grinko, `payload` is already the `event` in the whole `body`. If you want to have the whole request body data, you can use `body` instead.

See also: https://slack.dev/bolt-python/api-docs/slack_bolt/kwargs_injection/args.html
