### ISSUE TITLE
Add custom HTTP listener in PYTHON

### ISSUE THREAD

**Issue by santiagomoneta** [slackapi/bolt-python#271]
Hello team, I'm starting to use BOLT for python and wanted to add a custom http listener to trigger a message, not a slash command or an event since my slackbot will receive a call from another api that will start a flow.. I notice that in JAVASCRIPT you could use this:

```
receiver.router.post('/sampleEndpoint', async(req, res) => {
  let input = req.body;
...
```

and was not able to find any reference of that in the [PYTHON](https://slack.dev/bolt-python/concepts) documentation but yes on the [JAVASCRIPT](https://slack.dev/bolt-js/concepts) one... can I get some pointers here please?

**Comment by seratch** [comment]
Hi @santiagomoneta, thanks for asking the question!

In Bolt for Python, we don't have the "receiver" concept. Instead, it provides a plenty of "adapter"s for supporting many Web frameworks: https://slack.dev/bolt-python/concepts#adapters

As the above document shows, if you use Flask, you can use Flask's routing feature without anything specific to Bolt. 

```python
@flask_app.route("/slack/events", methods=["POST"])
def slack_events():
    # handler runs App's dispatch method     
    return handler.handle(request)

@flask_app.route("/your-custom-endpoint", methods=["GET"])
def custom():
    return "Hello world!"
````

Also, there are many examples in this repository. If you are looking for the adapter for other framework or runtime, check the [examples](https://github.com/slackapi/bolt-python/tree/main/examples) directory.

**Comment by santiagomoneta** [comment]
Thanks!! I will give it a shot

**Comment by santiagomoneta** [comment]
sorry, one last n00b question... so I got this code:

```
import os
import re
from slack_bolt import App
from flask import Flask, request
flask_app = Flask(__name__)

# Initializes your app with your bot token and signing secret
app = App(
    token=os.environ.get("SLACK_BOT_TOKEN"),
    signing_secret=os.environ.get("SLACK_SIGNING_SECRET")
)

@flask_app.route("/slack/events", methods=["POST"])
def slack_events():
    # handler runs App's dispatch method
    return handler.handle(request)

@flask_app.route("/your-custom-endpoint", methods=["GET"])
def custom():
    return "Hello world!"

# Start your app
if __name__ == "__main__":
    app.start(port=int(os.environ.get("PORT", 3000)))
```

I run the app and do a simple `curl http://localhost:3000/your-custom-endpoint` .. I was expecting a "hello word" is response but I get nothing... but I do see a `127.0.0.1 - - [25/Mar/2021 18:12:52] "GET /your-custom-endpoint HTTP/1.1" 404 -` in the paycharm console.. I missed something?

**Comment by santiagomoneta** [comment]
(I will replace the Hello world response to a message to the proper user with the proper message from the incoming payload)

**Comment by seratch** [comment]
@santiagomoneta 
When you use the Flask adapter, you can use Flask's utility for running your app: https://github.com/slackapi/bolt-python/blob/v1.4.4/examples/flask/app.py#L39-L42

```bash
FLASK_APP=app.py FLASK_ENV=development flask run -p 3000
```

**Comment by santiagomoneta** [comment]
is working now, thanks again!
