### ISSUE TITLE
Enable developers to customize the way to handle unmatched requests 

### ISSUE THREAD

**Issue by seratch** [slackapi/bolt-python#273]
If an incoming request does not match with any listeners in a Bolt app, the Bolt app responds to the request with 404 response status. The following lines of code are relevant parts in `App` / `AsyncApp`:

* https://github.com/slackapi/bolt-python/blob/v1.4.4/slack_bolt/app/app.py#L399-L400
* https://github.com/slackapi/bolt-python/blob/v1.4.4/slack_bolt/app/async_app.py#L438-L439

There is no way to append custom logic for the patterns. A common use case can be to customize the logging in the scenario.  

To improve this, I'm thinking to change the behavior as below:

* Add a new Bolt specific exception `BoltUnhandledRequestError(BoltError)` [here](https://github.com/slackapi/bolt-python/blob/v1.4.4/slack_bolt/error/__init__.py) and enable `@app.error` listener to handle the pattern
* Change `App` / `AsyncApp` internals. If a request is unhandled, `App`/`AsncApp` raises `BoltUnhandledRequestError` and lets `@app.error` listener  handle it. If `@app.error` listener does not return any `BoltResponse` or set status to the `response` argument, `App`/`AsncApp` falls back to the current logic, which outputs simple log message and returns 404 status anyway.
* As with the current implementation, non-200 responses are ignored in Socket Mode

If there is no concern about this change, we'll apply the change in the next minor version (1.5.0).

### Category (place an `x` in each of the `[ ]`)

* [x] **slack_bolt.App** and/or its core components
* [x] **slack_bolt.async_app.AsyncApp** and/or its core components
* [ ] Adapters in **slack_bolt.adapter**
* [ ] Others

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by eddyg** [comment]
This proposal sounds great to me, Kaz. I like that it uses the existing `@app.error` listener.

**Comment by Shadrocks** [comment]
I have a lot of these filling up my logs also. Is there documentation that can just help me to understand what the root cause of this is?

**Comment by seratch** [comment]
@Shadrocks Your app does not have the listeners for incoming requests. I would recommend enabling debug-level logging (https://slack.dev/bolt-python/concepts#logging) and checking what types of payloads to your app. If you have questions regarding this topic, please file a new GitHub issue for the question (we are using this issue for a feature development - it'd be appreciated if you could understand this).

**Comment by seratch** [comment]
I was going to modify the internals of bolt-python not to bring any breaking changes to the existing apps but I found that it's not feasible as a single bolt app can have only one `@app.error` listener function.

For this reason, I'd propose introducing a new flag to explicitly turn the new behavior on - `raise_error_for_unhandled_request`. As I will submit the pull request, see the details in the PR changes.
