### ISSUE TITLE
Getting "BoltError: `token` is invalid" while starting a Bolt app

### ISSUE THREAD

**Issue by daneasterman** [slackapi/bolt-python#277]
### Reproducible in:

First, I followed all non-code steps in the official getting started tutorial here: https://api.slack.com/start/building/bolt-python, including:
1. Create a Slack app
2. Requesting scopes
3. Installing app
4. Enabling app home
5 Installed Ngrok and got it running fine.

6. Created virtual environment using `virtualenv` - using Python 3.7.6 (64bit).

7. Added app credentials including Bot User OAuth token and Signing Secret to environment variables. Added breakpoint and printed out these variables to confirm being pulled through correctly into the code. Also temporarily hardcoded these values for sanity check.

This is the code I'm running from the tutorial in`app.py`:

```
import os
from slack_bolt import App

# Initializes app with bot token and signing secret
app = App(
    token=os.environ.get("SLACK_BOT_TOKEN"),
    signing_secret=os.environ.get("SLACK_SIGNING_SECRET")
)

# Start your app
if __name__ == "__main__":
    app.start(port=int(os.environ.get("PORT", 3000)))
```

#### The `slack_bolt` version

```
slack-bolt==1.4.4
slack-sdk==3.4.2
```

#### Python runtime version

`Python 3.7.6`

#### OS info

```
ProductName:    Mac OS X
ProductVersion: 10.15.7
BuildVersion:   19H15
Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64
```

#### Steps to reproduce:

Simply run:

`python3 app.py` or `python app.py` (both work in virtual environment)

### Expected result:

This code is so minimal I expect no output in terminal. If the command is run and nothing happens we can conclude that everything is fine.

### Actual result:

It is saying the token is invalid. The error is not clear enough to clarify 100% if the problem is with the `Bot User OAuth Token` or the `Signing Secret` 

```
Traceback (most recent call last):
  File "/Users/danpro12/.virtualenvs/stoxbot/lib/python3.7/site-packages/slack_bolt/app/app.py", line 266, in _init_middleware_list
    auth_test_result = self._client.auth_test(token=self._token)
  File "/Users/danpro12/.virtualenvs/stoxbot/lib/python3.7/site-packages/slack_sdk/web/client.py", line 834, in auth_test
    return self.api_call("auth.test", json=kwargs)
  File "/Users/danpro12/.virtualenvs/stoxbot/lib/python3.7/site-packages/slack_sdk/web/base_client.py", line 134, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
  File "/Users/danpro12/.virtualenvs/stoxbot/lib/python3.7/site-packages/slack_sdk/web/base_client.py", line 177, in _sync_send
    additional_headers=headers,
  File "/Users/danpro12/.virtualenvs/stoxbot/lib/python3.7/site-packages/slack_sdk/web/base_client.py", line 305, in _urllib_api_call
    status_code=response["status"],
  File "/Users/danpro12/.virtualenvs/stoxbot/lib/python3.7/site-packages/slack_sdk/web/slack_response.py", line 201, in validate
    raise e.SlackApiError(message=msg, response=self)
slack_sdk.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'invalid_auth'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 14, in <module>
    signing_secret=os.environ.get("SLACK_SIGNING_SECRET")
  File "/Users/danpro12/.virtualenvs/stoxbot/lib/python3.7/site-packages/slack_bolt/app/app.py", line 250, in __init__
    token_verification_enabled=token_verification_enabled
  File "/Users/danpro12/.virtualenvs/stoxbot/lib/python3.7/site-packages/slack_bolt/app/app.py", line 271, in _init_middleware_list
    raise BoltError(error_auth_test_failure(err.response))
slack_bolt.error.BoltError: `token` is invalid (auth.test result: {'ok': False, 'error': 'invalid_auth'})
```

But after reinstalling app, refreshing page and testing `Bot User OAuth Token` with: https://api.slack.com/methods/auth.test/test it shows:

```
{
    "ok": true,
    "url": "https://ptj-tech-services.slack.com/",
    "team": "PTJ Technology Services",
    "user": "stoxbot",
    "team_id": "T01RDL85BHR",
    "user_id": "U01S3C8J3CY",
    "bot_id": "B01QYQSFKB9",
    "is_enterprise_install": false
}
```

Note: I just tried it first thing today using the auth test site and it first printed invalid token error, then I reinstalled the app again, refreshed the page and got the correct `ok: true` output as above.

**Comment by seratch** [comment]
Hi @daneasterman, thanks for asking the question!

I'm thinking that your env variable `SLACK_BOT_TOKEN` may have additional space or line break. Could you run the following command to see if there is no extra character in the value? (needless to say, but you don't need to share the outputs with us)

```python
python3 -c 'import os;token=os.environ.get("SLACK_BOT_TOKEN");print(f"\"{token}\"")'
```

**Comment by daneasterman** [comment]
> Hi @daneasterman, thanks for asking the question!
> 
> I'm thinking that your env variable `SLACK_BOT_TOKEN` may have additional space or line break. Could you run the following command to see if there is no extra character in the value? (needless to say, but you don't need to share the outputs with us)
> 
> ```python
> python3 -c 'import os;token=os.environ.get("SLACK_BOT_TOKEN");print(f"\"{token}\"")'
> ```

Hi @seratch thanks for the quick reply! I ran this and don't see any spaces or line breaks. Just the alphanumeric characters for the token in double quotation marks. Fyi: I also hardcoded this value temporarily in app.py as sanity check and same invalid token error.

**Comment by seratch** [comment]
@daneasterman Thanks. Does the value for SLACK_BOT_TOKEN start with `xoxb-`? I don't think there is a difference with the API tester as long as you use the same value.

**Comment by seratch** [comment]
To narrow your issue down, performing the Web API call outside the Bolt app may be helpful. You can see what's happening with your bot token by running the following script:

```python
import logging
logging.basicConfig(level=logging.DEBUG)

import os
from slack_sdk import WebClient

token = os.environ["SLACK_BOT_TOKEN"]
client = WebClient(token=token)
response = client.auth_test()
```

**Comment by daneasterman** [comment]
Many apologies for this, above helped me debug the issue, I can't believe I missed this but somehow for token incorrectly put xoxb= with "=" instead of "-". Closing ticket now. Apologies once again.
