### ISSUE TITLE
Block Actions Interactions Payload Inquiry

### ISSUE THREAD

**Issue by CSP197** [slackapi/bolt-python#278]
Hello,

I'm experimenting with the Slack Bolt Python API and its block actions interaction. In the function decorator, what is the value or string that the decorator should attempt to match?

`@app.block_action("________")`

#### The `slack_bolt` version

```
slack-bolt==1.4.4
slack-sdk==3.4.2
slackclient==2.9.3
```

#### Python runtime version

`Python 3.8.5`

#### OS info

`Nah`

#### Steps to reproduce:
Source Code
```
app = AsyncApp(token="...")

blocks = [
{
            "type": "actions",
            "elements": [
                {
                    "type": "button",
                    "text": {
                        "type": "plain_text",
                        "emoji": True,
                        "text": "Approve"
                    },
                    "style": "primary",
                    "value": "click_me_1"
                },
                {
                    "type": "button",
                    "text": {
                        "type": "plain_text",
                        "emoji": True,
                        "text": "Deny"
                    },
                    "style": "danger",
                    "value": "click_me_2"
                }
            ]
        }]

@app.event("app_mention")
async def app_mention(client, event, say):
    channel = event['channel']
    ts = event['ts']
    await client.chat_postMessage(
                    channel=channel,
                    thread_ts=ts,
                    blocks=blocks
                )

@app.block_action("________")                        <-- What should this decorator check for?
async def deny(ack, respond):
    await ack()
    await respond("Deny")

async def main():
    handler = AsyncSocketModeHandler(app, "...")
    await handler.start_async()

if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
```

### Expected result:

Slack Bolt API to register the listener and handle the block_action request via apt listener

### Actual result:

Logs:
```
DEBUG:slack_bolt.AsyncApp:Checking listener: app_mention ...
DEBUG:slack_bolt.AsyncApp:Checking listener: deny ...
WARNING:slack_bolt.AsyncApp:Unhandled request ({'type': 'block_actions', ...
```

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

Thanks all,

**Comment by stevengill** [comment]
Hey @CSP197,

You need to add an action_id on the block elements. That is what you would match with on `@app.block_action("________")`

**Comment by CSP197** [comment]
Thank you!
I used the Slack Block Builder Kit to create the block elements, which doesn't append any action_id by default.


```
...
"style": "primary",
"value": "click_me_1",
"action_id": "test_1"
},
```
`@app.block_action("test_1")`

Please feel free to close this issue 👍

**Comment by CSP197** [comment]
Also, I have a follow up question regarding the block actions interactions payload.

Are there any parameters that I can pass in a `block_action` decorated function, that would allow me to view the `username` or `user_id` of the person, or perhaps the metadata of the slack message from which the block action would have originated?

```
@app.block_action("test_1")
async def deny(ack, respond, _____ ):)                        <-- Are there any additional parameters that can be passed here?
    ....

    user_id_who_triggered_action = ...
    original_slack_message_thread_ts = ...
    return
```

Thanks all,

**Comment by seratch** [comment]
@CSP197 You can access `context.user_id` to know the user's ID who is associated with an incoming request. To know more info about the user, you can perform [users.info](https://api.slack.com/methods/users.info) API method with the user ID.

See also:
* https://slack.dev/bolt-python/api-docs/slack_bolt/kwargs_injection/async_args.html
* https://slack.dev/bolt-python/api-docs/slack_bolt/context/async_context.html#slack_bolt.context.async_context.AsyncBoltContext
* https://slack.dev/bolt-python/api-docs/slack_bolt/context/base_context.html#slack_bolt.context.base_context.BaseContext.user_id

**Comment by CSP197** [comment]
The docs above really helped!
Please feel free to close this issue 👍

**Comment by seratch** [comment]
We're glad to hear that the documents are helpful to you 👍

**Comment by DataGreed** [comment]
How do you set an action_id if it's generated at runtime?

**Comment by seratch** [comment]
@DataGreed If you don't set action_id for a block element, a random value would be set. We highly recommend setting your own unique value for easily handling interactivity events.

**Comment by DataGreed** [comment]
E.g. how do I get trigger_id in the listener? The vent argument is set to None all the time

**Comment by seratch** [comment]
I just answered at https://github.com/slackapi/bolt-python/issues/337#issuecomment-837702200 (if you have further to ask, please use the issue instead)

Regarding the trigger_id, it's only available at the top level of request body. For this reason, your listener functions need to access `body` instead of `payload`/`action` for it.
