### ISSUE TITLE
Question on forcing Link preview in response

### ISSUE THREAD

**Issue by ttback** [slackapi/bolt-python#282]
I want to be able to preview links in bot's response to user because the Slack workspace seems to have Link preview turn-off by default. Is there any way to do that?

**Comment by misscoded** [comment]
Hi @ttback! From the subsequent issue you've opened (#283), you appear to have already discovered the answer to this, but for those reviewing this issue at a later date, the way to provide custom previews for link unfurls is to use the [`chat.unfurl`](https://api.slack.com/methods/chat.unfurl) method, paired with a subscription to the [`link_shared` event](https://api.slack.com/events/link_shared).

I'm going to close this issue as the discussion and more in-depth implementation details are being handled over in #283.
