### ISSUE TITLE
link_shared event not captured

### ISSUE THREAD

**Issue by ttback** [slackapi/bolt-python#283]
Trying to use link_shared event to respond to urls in messages

#### The `slack_bolt` version
slack-bolt==1.4.4
slack-sdk==3.4.2

#### Python runtime version

Python 3.9.1

#### OS info

ProductName:    Mac OS X
ProductVersion: 10.15.7
BuildVersion:   19H524
Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1. Type a link in DM to the bot
2. Bot code: 
```
@app.event("link_shared")
def message_link_shared(message, say):
    say("link shared")
```
3. "link shared" should be responded to the user

### Expected result:

"link shared" should be responded to the user

### Actual result:

nothing happened, on the backend there is an 
(status: 404, body: {"error": "unhandled request"})

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by eddyg** [comment]
Just a quick hint to mention that `link_shared` events are intended to be responded to with a [chat.unfurl](https://api.slack.com/methods/chat.unfurl) response. Slack takes the "unfurls" you provide for the shared link(s) and attaches them to message containing the link(s). You can read more about [link unfurling here](https://api.slack.com/reference/messaging/link-unfurling). `link_shared` events can be generated from a variety of sources in your workspace, _not_ just from direct interaction with your bot.

You also need to _acknowledge_ the `link_shared` event in the listener, similar to what is shown for [responding to commands](https://slack.dev/bolt-python/concepts#commands) in the docs.

**Comment by seratch** [comment]
@eddyg Thanks for answering (as always 🙌 )

@ttback 
>(status: 404, body: {"error": "unhandled request"})

This indicates that your app has received the event but `@app.event("link_shared")` is not enabled for some reason. A common pattern I've observed in the past is that if you place the listener function after `app.start()` call, the listener won't be added to the `App` instance. Can you check the source code again?

**Comment by ttback** [comment]
@seratch I simplified the code down to just one handler, and the issue can be reproduced with following code
and if you DM with a link, it will show unhandled request. Don't know if Oath scopes need to be adjusted, but I have link related oath scopes, such as links:read, links:write

```
import os
from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler
import asyncio

app = App(token=os.environ["SLACK_BOT_TOKEN"])

@app.event("link_shared")
def message_link_shared(message, say):
    say("link shared")
    
if __name__ == "__main__":
    # Create an app-level token with connections:write scope
    handler = SocketModeHandler(app, os.environ["SLACK_APP_TOKEN"]) 
    handler.start()
```

**Comment by ttback** [comment]
@eddyg not sure how to make a chat.unfurl response from bolt. I just realize that the handler functions for app.event in the doc you referenced, may work a little differently, with (client, event, logger). Is there a place where we know which parameters are available to the handler functions for different type of app.event vs. app.message.

**Comment by eddyg** [comment]
Bolt uses [kwarg injection](https://slack.dev/bolt-python/api-docs/slack_bolt/kwargs_injection/args.html) so you specify exactly which arguments your listeners needs. For example, you'll want to include `ack` (and then call it from your listener), just like in the "respond to commands" documentation I linked earlier.

Calling `chat.unfurl` is accomplished just like calling any other Slack API method, as demonstrated in the call to `chat.postEphemeral` in the [global middleware](https://slack.dev/bolt-python/concepts#listener-middleware) example.

**Comment by ttback** [comment]
@seratch the code i pasted is all of the sample test code I have so there are no other handlers.

- Enable Event Subscriptions, this is enabled

- Add link_shared bot events
I suppose this is for 
```
@app.event("link_shared")
def message_link_shared(ack, say, logger):
    ack()
    say("link shared")
 ```
 
 - Add the domain to App unfurl domains at the bottom of the same page
 This I am not sure how to do.
 
 
 The event on the link message is 
 ```
 "event":{"client_msg_id":"hash","type":"message","text":"<https:...>
 ```

**Comment by seratch** [comment]
@ttback 

>Add the domain to App unfurl domains at the bottom of the same page
>This I am not sure how to do.

You can set up to 5 domains at the bottom of the Event Subscriptions page.

<img width="600" src="https://user-images.githubusercontent.com/19658/114105014-e96cb080-9906-11eb-982c-4c32b1a8c711.png">

>"type":"message"

This is a ["message" event](https://api.slack.com/events/message). Your Slack app configuration should have message events in the Event Subscriptions page. If it's not intentional, you can remove it from the list. If you wanted to handle the events too, you can have `@app.event("message")` listener as well.

It seems everything should be clear now. Do you mind closing this issue?
