### ISSUE TITLE
Question regarding socket mode slash commands

### ISSUE THREAD

**Issue by jcastro-sfdc** [slackapi/bolt-python#285]
I'm using https://github.com/slackapi/bolt-python/blob/main/examples/socket_mode.py as you have written it and I am unable to get the modal to fire.

### Reproducible in:

```DEBUG:slack_bolt.App:A new message enqueued (current queue size: 1)
DEBUG:slack_bolt.App:A message dequeued (current queue size: 0)
DEBUG:slack_bolt.App:Message processing started (type: slash_commands, envelope_id: f3c87b47-e572-4a0b-a93f-8ea057e643b0)
DEBUG:slack_bolt.App:Applying slack_bolt.middleware.ssl_check.ssl_check.SslCheck
DEBUG:slack_bolt.App:Applying slack_bolt.middleware.request_verification.request_verification.RequestVerification
DEBUG:slack_bolt.App:Applying slack_bolt.middleware.authorization.single_team_authorization.SingleTeamAuthorization
DEBUG:slack_bolt.App:Applying slack_bolt.middleware.ignoring_self_events.ignoring_self_events.IgnoringSelfEvents
DEBUG:slack_bolt.App:Applying slack_bolt.middleware.url_verification.url_verification.UrlVerification
DEBUG:slack_bolt.App:Checking listener: hello_command ...
DEBUG:slack_bolt.App:Running listener: hello_command ...
DEBUG:slack_bolt.App:Responding with status: 200 body: "Hi <@blahblah>!" (0 millis)
DEBUG:slack_bolt.App:Sending a message (session id: 1de4cd23-8d25-401d-bc1c-c3cd2d480625, message: {"envelope_id": "f3c87b47-e572-4a0b-a93f-8ea057e643b0", "payload": {"text": "Hi <@blahblah>!"}})
DEBUG:slack_bolt.App:Response time: 1 milliseconds
DEBUG:slack_bolt.App:Message processing completed (type: slash_commands, envelope_id: f3c87b47-e572-4a0b-a93f-8ea057e643b0)
```

#### The `slack_bolt` version

slack-bolt==1.4.4

#### Python runtime version

3.8.5

#### OS info

ProductName:    Mac OS X
ProductVersion: 10.14.6
BuildVersion:   18G8022
Darwin Kernel Version 18.7.0: Tue Jan 12 22:04:47 PST 2021; root:xnu-4903.278.56~1/RELEASE_X86_64

#### Steps to reproduce:

1. /hello-socket-mode

### Expected result:

where is my modal?

### Actual result:

ack(f"Hi <@{user_id}>!")

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by misscoded** [comment]
Hi @jcastro-sfdc! In the code sample you've linked, the listener associated with `/hello-socket-mode` only responds with a message. The opening of the modal (by way of the `open_modal` function) is associated with [Line 82](https://github.com/slackapi/bolt-python/blob/efab0105fd3ff9359a2f669eda46bbed2f6c3bec/examples/socket_mode.py#L82): a Shortcut with a callback ID of `socket-mode`. 

If you want to open the modal when the `/hello-socket-mode` command is used, call the `open_modal` function directly from within the `/hello-socket-mode` listener's function, as such:

```
@app.command("/hello-socket-mode")
def hello_command(ack, body, client):
    user_id = body["user_id"]
    ack(f"Hi <@{user_id}>!")

    open_modal(body, client)
```

Let me know if that solves the issue!

**Comment by jcastro-sfdc** [comment]
Thanks @misscoded.  That was a noob question for sure but I am learning!
