### ISSUE TITLE
Bolt vs python-slack-sdk

### ISSUE THREAD

**Issue by dashmug** [slackapi/bolt-python#291]
Hi,

This is just a question: 

What's the relationship of bolt to [python-slack-sdk](https://github.com/slackapi/python-slack-sdk)? When should I use bolt over python-slack-sdk?

Thank you.

**Comment by seratch** [comment]
Hi @dashmug, thanks for asking the question!

>What's the relationship of bolt to python-slack-sdk?

Bolt is a full-stack Slack app development framework, which is built on top of slack-sdk. 

>When should I use bolt over python-slack-sdk?

For building interactive Slack apps, using Bolt should make your app development much more effortless. Bolt provides a great abstraction for the key features such as shortcuts, modals, slash commands, and custom steps in Workflow Builder.

On the other hand, if you want to use only a particular feature such as chat.postMessage API and Incoming Webhooks, your app can rely on only slack-sdk. Just instantiating `WebClient` and call chat_postMessage` method is the right way for the purpose.

I hope this was helpful to you. If everything is clear, would you mind closing this issue?

**Comment by dashmug** [comment]
Thank you very much @seratch for the clear explanation.

I'm closing this.
