### ISSUE TITLE
Is Slack App required to be listed on App directory to be used for sign in with slack

### ISSUE THREAD

**Issue by sudhir512kj** [slackapi/bolt-python#292]
I have developed a web app using Strapi+React. I want a button for Sign in with Slack. Is it necessary to list my Slack app on the App directory to be used for Sign in with Slack integration?
I am getting error `Method not allowed`

#### The `slack_bolt` version

1.1.2

#### Python runtime version

3.7

#### OS info

Microsoft Windows [Version 10.0.19042.906]

**Comment by mwbrooks** [comment]
Hey @sudhir512kj 👋🏻 Sign-in with Slack is available to all Slack apps and you don't need to be listed on the Slack app directory. There are a few [exceptions](https://api.slack.com/docs/sign-in-with-slack#exceptions) with guest accounts and Slack admins turning the feature.

Could you provide a code sample that reproduces the `Method not allowed` error?

**Comment by seratch** [comment]
Hi @sudhir512kj , let us know if you need further help here. I will close this issue after waiting for your response for a few more days.

**Comment by sudhir512kj** [comment]
Thank you @mwbrooks @seratch, my problem is solved now. Thank you for your response.
