### ISSUE TITLE
Why does Bolt handle requests in new threads?

### ISSUE THREAD

**Issue by olestourko** [slackapi/bolt-python#294]
I'm using Flask for my production app with Gunicorn as the HTTP server. Bolt is [handling requests in independent threads](https://github.com/slackapi/bolt-python/blob/dafc833e9cbc39edb87528e8e782422e87fefc5b/slack_bolt/app/app.py#L390) and there doesn't appear to be a way to disable this. This causes issues with pooled SQLAlchemy DB connections for me which I use an inconvenient workaround for.

There's probably a good reason why Bolt spins off new threads to handle requests but I can't figure out why. Behind a production HTTP server like Gunicorn each request is handled by its own worker anyways so blocking shouldn't be an issue? I'm just curious why it does this.

**Comment by seratch** [comment]
Hi @olestourko, thanks for asking the question!

>There's probably a good reason why Bolt spins off new threads to handle requests but I can't figure out why. 

The reason why this framework runs your listener functions in a different thread is **to enable your apps to return an HTTP response immediately when your app calls the` ack()` method in a listener**. 

As you may know, the interactions with Slack API servers requires your app to respond to any incoming requests within less than 3 seconds:

>All apps must, as a minimum, acknowledge the receipt of a valid interaction payload.
>To do that, your app must reply to the HTTP POST request with an HTTP 200 OK response.
>This must be sent within 3 seconds of receiving the payload. If your app doesn't do that, the Slack user who interacted with the app will see an error message. Make sure your app responds quickly.

https://api.slack.com/interactivity/handling#acknowledgment_response

To easily make your apps compatible with this requirement, the Bolt framework (for JavaScript as the first one) is designed to immediately respond to requests with 200 OK responses while doing other remaining tasks asynchronously. For implementing the same in Python, bolt-python framework utilizes threads for `App` and `Future` value generation for `AsyncApp` (an asyncio compatible version), respectively.

> there doesn't appear to be a way to disable this

If you pass `process_before_response=True` in the `App` constructor, you can turn the execution in threads off. However, please note that, with this option enabled, your listener functions must complete in less than 3 seconds to avoid timeout errors. You may need to move some time-consuming parts of your code to a background job or an async execution in threads.

> This causes issues with pooled SQLAlchemy DB connections for me which I use an inconvenient workaround for.

I assume you're using the [thread-local session feature](https://docs.sqlalchemy.org/en/14/orm/contextual.html). If so, please consider not reusing the thread-local ones generated outside your Bolt listener functions. Instead, starting a scoped session and cleaning it up inside a listener execution should work for you. Perhaps, you may want to have a simple utility method for doing (say, using `with listener_session(engine) as session:` or something like that at the top level of your listener function methods).

I hope this was helpful to you. If everything is clear and there is nothing further to discuss here, would you mind closing this issue?

**Comment by olestourko** [comment]
Thanks @seratch, makes sense! And yeah I'm using thread-local sessions. I'm closing the connection at the end of my listener methods and in exception catchers, but probably should switch to using a context manager as you mentioned. Anyways, closing issue.
