### ISSUE TITLE
Timepicker integration

### ISSUE THREAD

**Issue by tomeszmh** [slackapi/bolt-python#298]
Hey! Just a short question. I know that timepicker in beta stage, but is it possible to use it via slack-bolt? I gave it a try, but slack denies my attempt to use it. And also i enabled beta features on my app website.  Is there a workaround for it? Many thanks

slack-bolt 1.4.4

#### Python runtime version
3.7.4

#### OS info

ProductName:    macOS
ProductVersion: 11.2.3
BuildVersion:   20D91
Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64

### Expected result:

(Tell what you expected to happen)

### Actual result:
I got unexpected type timepicker, skipping....

**Comment by seratch** [comment]
Hi @tomeszmh, thanks for asking the question! Of course, you can use the feature as long as you configured your Slack app properly. 

I've created an example Bolt app that utilizes timepicker. Check the source code in the repository should be helpful for you.

* https://github.com/seratch/send-it-later-for-slack/blob/e5f3555f347826576099f2f8551b03089ba7479d/README.md
* https://github.com/seratch/send-it-later-for-slack/blob/e5f3555f347826576099f2f8551b03089ba7479d/app/modals.py#L141-L151
* https://github.com/seratch/send-it-later-for-slack/blob/e5f3555f347826576099f2f8551b03089ba7479d/app/listeners.py#L135

**Comment by tomeszmh** [comment]
Thank you so much. I tried, but same error. I investigated and found something. i

[link to code in slack-sdk](https://github.com/slackapi/python-slack-sdk/blob/450d600e052235ee5ef35b80adf4ca86eb38e48f/slack_sdk/models/blocks/block_elements.py#L60)
In this method if type does not exist it will be skipped. 
I always get   Unknown element detected and skipped message. I think my code runs into the else block.
Many thanks, Tamas

**Comment by seratch** [comment]
@tomeszmh As it's still in beta, we haven't merged the change for it: https://github.com/slackapi/python-slack-sdk/pull/876 I do understand you prefer using classes for building blocks but please use dict values for the time being.

**Comment by seratch** [comment]
@tomeszmh Thanks for your positive reaction to my last comment. It seems everything is clear now. Would you mind closing this issue?

**Comment by tomeszmh** [comment]
Yes, sure, thx
