### ISSUE TITLE
Local testing when utilizing WebSocket

### ISSUE THREAD

**Issue by tehreet** [slackapi/bolt-python#300]
Writing a slackbot, pretty basic so far. To avoid exposing a public endpoint, I'm trying to use WebSocketMode to listen for events etc.

I have a container running the listener, and it works well. However, when doing development locally, having two listeners open seems to be an issue. Do you all have a way you do development with websocketmode?

**Comment by seratch** [comment]
Hi @tehreet, thanks for asking the question?
> However, when doing development locally, having two listeners open seems to be an issue. Do you all have a way you do development with websocketmode?

Does this mean you have two connections for a single Slack app - 1) deployed app's connection 2) connection on your local machine (local dev)? If so, as you are experiencing, the Slack server-side sends events to your connections in a round-robin manner. 

If you want to have development version of your app, the current recommendation is to create a new app for development/testing with the same set of OAuth scopes and functionalities.

I hope this was helpful to you. If everything is clear, may I ask you to close this issue?
