### ISSUE TITLE
Creating custom buttons using emojis

### ISSUE THREAD

**Issue by rkoniuta** [slackapi/bolt-python#302]
I am looking for a way to create a custom "button" using an emoji in my app. Some emojis, such as 👍, 👎, ✅, ❌, imply feedback that might be shared on a given message block (for example, ❌ might be used to dismiss a block). In order to create a UI that is as simple and uncluttered as possible, I am hoping to use an arbitrary emoji effectively as a button, without adding a larger button accessory. 

Ostensibly, this would involve adding a link to the emoji <(url)|👍>, such that clicking the emoji would send a signal to my app and delete the block. However, I am not sure how/if this can be implemented:

1) as I am not sure what that link should look like, and where it should post

2) would selecting this emoji always open the link in a new window?

Any recommendations would be much appreciated.

#### The `slack_bolt` version

slack-bolt==1.5.0
slack-sdk==3.5.0

#### Python runtime version

3.9.2

#### OS info

ProductName:    macOS
ProductVersion: 11.2.3
BuildVersion:   20D91
Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64

**Comment by seratch** [comment]
Hi @rkoniuta, thanks for asking the question!

Unfortunately, there is no way to make links or text functioning like a button. 

The only way is to use button components in Block Kit. Our recommendation for your use case is to use [an "actions" block](https://api.slack.com/reference/block-kit/blocks#actions). With the block, you can have multiple buttons in a single block. Here is the [Block Kit Builder URL demonstrating how it works](https://app.slack.com/block-kit-builder/#%7B%22blocks%22:%5B%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22If%20everything%20looks%20good,%20click%20the%20:check_green:%20button.%20Otherwise,%20click%20the%20:x:%20button%20and%20let%20us%20know%20what%20else%20you%20need%20%20by%20submitting%20the%20modal%20:bow:%22,%22emoji%22:true%7D%7D,%7B%22type%22:%22actions%22,%22elements%22:%5B%7B%22type%22:%22button%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22:x:%22,%22emoji%22:true%7D,%22value%22:%22ng%22,%22action_id%22:%22ng%22%7D,%7B%22type%22:%22button%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22:check_green:%22,%22emoji%22:true%7D,%22value%22:%22ok%22,%22action_id%22:%22ok%22%7D%5D%7D%5D%7D).

<img width="500" src="https://user-images.githubusercontent.com/19658/115816087-31292700-a433-11eb-87f5-6c173af4955d.png">

```json
{
  "blocks": [
    {
      "type": "section",
      "text": {
        "type": "plain_text",
        "text": "If everything looks good, click the :check_green: button. Otherwise, click the :x: button and let us know what else you need  by submitting the modal :bow:"
      }
    },
    {
      "type": "actions",
      "elements": [
        {
          "type": "button",
          "text": {
            "type": "plain_text",
            "text": ":x:"
          },
          "value": "ng",
          "action_id": "ng"
        },
        {
          "type": "button",
          "text": {
            "type": "plain_text",
            "text": ":check_green:"
          },
          "value": "ok",
          "action_id": "ok"
        }
      ]
    }
  ]
}
```

If you would like to navigate your end users to an external URL, you can set the URL to a button element. Of course, you can include this as one of the elements in an "actions" block.

```json
{
  "type": "button",
  "text": {
    "type": "plain_text",
    "text": "Update your settings"
  },
  "value": "1",
  "url": "https://www.example.com/your-own-url",
  "action_id": "link-button"
}
```

I hope this was helpful to you. This may not be a solution for your use case but if there is nothing else to ask here, may I ask you to close this issue?

**Comment by seratch** [comment]
👋 Hey @rkoniuta, let us know if you have something further to ask/discuss here. Let me close this issue after waiting for your response for a few more days.

**Comment by seratch** [comment]
Let me close this issue but please feel free to write in if you have something further to discuss here.

**Comment by Muskan19577** [comment]
can we add buttons to our message with slack-bolt in python
