### ISSUE TITLE
Socket Mode with Flask App

### ISSUE THREAD

**Issue by mariebarrramsey** [slackapi/bolt-python#303]
Is there a way to use socket mode with a flask app? I'm going through https://slack.dev/bolt-python/concepts#adapters and don't see an example with socket mode. 

#### The `slack_bolt` version

slack-sdk==3.5.0
slack-bolt==1.5.0

#### Python runtime version

python==2.7.16

#### OS info

ProductName: Mac OS X
ProductVersion: 10.15.7
BuildVersion: 19H524
Darwin Kernel Version 19.6.0

#### Steps to reproduce:
1. slackApp = App(token = "xxxxx")
2. flaskApp = Flask(__name__)
2. handler = SocketModeHandler(slackApp, "xxxx")
3. handler.start()
4. app.main() where app runs stuff for the flaskApp

### Expected result:

Both the slack app and flask app to run at the same time/ communicate

### Actual result:

Only the slack app runs and the flask app never starts. The slack app seems like it is blocking the flask app from starting.

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @mariebarrramsey, thanks for asking the question!

Checking https://github.com/slackapi/bolt-python/issues/255#issuecomment-792363549 should be helpful for this. You can use `SocketModeHandler#connect()`, which does not block the current thread. You can start a Flask web app in the same process this way.

As this is a clear answer to this question, let me close this issue now!

**Comment by mariebarrramsey** [comment]
Thanks, connect() worked. I am trying to send info from the slack app to the flask app though. Is there a way to do this?

**Comment by seratch** [comment]
@mariebarrramsey hmm, it sounds a bit unusual design. I don't think there is a single answer for it and it seems to be out of this library's scope. 

You may want to have a queue system or database in between your Socket Mode app and the Flask web app. Your Socket Mode app can store event data for the asynchronous execution in other apps. It depends on the preferable architecture for your goal.

If you would like to have more discussion about this with others, I'd recommend joining [the community Slack workspace](https://community.slack.com/). If you're not a member yet, you can join from [this URL](https://j.mp/community-slack-com). I think [#slack-api](https://app.slack.com/client/TG4KUE8JV/C0K8617D5) or [#lang-python](https://app.slack.com/client/TG4KUE8JV/CHL4CLRCZ) would be the best channel for this topic.
