### ISSUE TITLE
accessing the functionality inside AsyncWebClient from slack_bolt.async_app

### ISSUE THREAD

**Issue by master0v** [slackapi/bolt-python#305]
When I receive an image from a user in a private message, I want to make it accessible to the other users and channels, therefore I need to be able to call `public_url = await web_client.files_sharedPublicURL(file=event['files'][0]['id'])

How do I do this from inside the slack_bolt.async_app?

**Comment by seratch** [comment]
Hi @master0v, thanks for asking the question!

You can use the `client` argument in your listener functions. Here is an example code using `client` for opening a modal view: https://github.com/slackapi/bolt-python/blob/v1.5.0/examples/readme_async_app.py#L40-L44
Also, the list of all listener arguments (for async apps) is available:
https://slack.dev/bolt-python/api-docs/slack_bolt/kwargs_injection/async_args.html

**Comment by master0v** [comment]
Thanks.  I tried the following:

`public_url = await client.files_sharedPublicURL(file=event['files'][0]['id'])`

and I got: 

```
slack_sdk.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'not_allowed_token_type'}
```

Do I need to pass the token to the client again somehow?

**Comment by seratch** [comment]
@master0v The API method requires a user's token, which starts with `xoxp-`, not a bot token startingwith `xoxb-`: https://api.slack.com/methods/files.sharedPublicURL

<img width="400" src="https://user-images.githubusercontent.com/19658/115977372-52645180-a5b2-11eb-83bf-7baf02db0551.png">

If you are installing your app from the Slack app admin page, you can use your own user token. After adding `files:write:user` & `files:write` to the user scopes in the **OAuth & Permissions** page, you can the installation again. Your installation result page, you will see two types of tokens then. You can set the user token as another env variable (say, `SLACK_USER_TOKEN`) and refer to the value for this API call. You can pass a different token as `token` argument for any API method calls.

**Comment by master0v** [comment]
Thanks, that's really helpful.  Now I am able to call this method and get `permalink_public`

Then I try to send a message with that image in block

 ```
 image_block = {"text": "Image",
    "blocks": [{
      "type": "image",
      "image_url": "https://slack-files.com/T01UY2HQ8DU-F020N5BPCCQ-ceb6a12418",
      "alt_text": "Boto Image"
    }]
  }
  await say(image_block)
```

and I get this:

```
slack_sdk.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'invalid_blocks', 'errors': ['downloading image failed [json-pointer:/blocks/0/image_url]'], 'response_metadata': {'messages': ['[ERROR] downloading image failed [json-pointer:/blocks/0/image_url]']}}
```

I verified (using incognito window), this image is now accessible publically.  Why does it fail to download?  Does it need to be downloaded? perhaps I can embed it in the block using its ID?  In any case this problem is sorted, so I should probably create a new one.

**Comment by seratch** [comment]
@master0v Unfortunately, as far as I know, no public API provides a way to fetch the pub_secret parameter without accessing the URL via a web browser. Thus, there is no way to properly use the permalink for this purpose (directly using the URL as `image_url` in an image block).

Your app can access the file content with a valid token for reading files (e.g., https://github.com/slackapi/bolt-python/issues/266). I know this suggestion may not be ideal for your use case, but one possible idea is:

* Download the file content and upload it to somewhere else (other cloud storage services)
* Use the public URL as `image_url` in an image block

This limitation may be removed in the future, but I don't have anything I can tell at this point.

**Comment by master0v** [comment]
Thanks for your help!
