### ISSUE TITLE
Trigger Id Expired--Socket Mode

### ISSUE THREAD

**Issue by mariebarrramsey** [slackapi/bolt-python#306]
I want to open a modal (a dropdown menu) in socket mode using the slash command and collect the data that users enter. However, no matter what I do, I keep getting a "trigger_id expired" error when I run the slash command. Sometimes the command will work the first time and open up the menu, but the second time I run the command it will say trigger_id expired. At first I thought this was because it was taking more than 3 seconds for my modal to open, but then I simplified the view a lot just to test this and got the same error. I also tried to follow this example (in case it is just a timeout issue): https://github.com/slackapi/node-slack-sdk/issues/1131 but it might be helpful if you could post what this would look like in python if possible. Thank you!

#### The `slack_bolt` version

slack-sdk==3.5.0
slack-bolt==1.5.0

#### Python runtime version

python==2.7.16

#### OS info

ProductName: Mac OS X
ProductVersion: 10.15.7
BuildVersion: 19H524
Darwin Kernel Version 19.6.0

#### Steps to reproduce:

1. Use socket mode
2. Have the following listener
```python
app.command("/mycommand")
def open_modal(ack, body, client):
  ack()
  client.views_open(
    # Pass a valid trigger_id within 3 seconds of receiving it
    trigger_id=body["trigger_id"],
    # View payload
    view= {
      "type": "modal",
      "title": {
        "type": "plain_text",
        ....}
})
```

### Expected result:

The modal to open

### Actual result:

Slack says dispatch_failed and I get the error:
The server responded with: 
```
{'ok': False, 'error': 'invalid_arguments', 'response_metadata': {'messages': ['[ERROR] `trigger_id` expired [json-pointer:/trigger_id]']}}
```

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by stevengill** [comment]
Hey @mariebarrramsey 

I just tested this and couldn't reproduce the issue you describe. Here is my simple code sample

```
import os
from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler
import logging

# Set log level to debug so you get verbose output in terminal
logging.basicConfig(level=logging.DEBUG)

# Initializes your app with your bot token and signing secret
app = App(
    token=os.environ["SLACK_BOT_TOKEN"],
)

@app.command("/bolt-test-slash")
def repeat_text(ack, client, body):
    print(body["trigger_id"])
    # Acknowledge command request
    ack()

    client.views_open(
        # Pass a valid trigger_id within 3 seconds of receiving it
        trigger_id=body["trigger_id"],
        # View payload
        view={
            "type": "modal",
            # View identifier
            "callback_id": "view_1",
            "title": {"type": "plain_text", "text": "My App"},
            "submit": {"type": "plain_text", "text": "Submit"},
            "blocks": [
                {
                    "type": "section",
                    "text": {"type": "mrkdwn", "text": "Welcome to a modal with _blocks_"},
                    "accessory": {
                        "type": "button",
                        "text": {"type": "plain_text", "text": "Click me!"},
                        "action_id": "button_abc"
                    }
                },
                {
                    "type": "input",
                    "block_id": "input_c",
                    "label": {"type": "plain_text", "text": "What are your hopes and dreams?"},
                    "element": {
                        "type": "plain_text_input",
                        "action_id": "dreamy_input",
                        "multiline": True
                    }
                }
            ]
        }
    )

# Start your app
if __name__ == "__main__":
    handler = SocketModeHandler(app, os.environ["SLACK_APP_TOKEN"])
    handler.start()
  
  ```
  
  Let me know if this solves your problem!

**Comment by mariebarrramsey** [comment]
I ran your code and still get the same error about the trigger_id. It works the first time I run the slash command, but any time after that it has the trigger_id expired error. I'm using handler.connect() if that makes any difference.

**Comment by stevengill** [comment]
I chatted with @seratch and he is able to reproduce your code if he has multiple socket connections. Do you have multiple connections via websocket? Maybe a colleague is also connected or a server somewhere? 

This is because events are spread out through the sockets. So if one version of the code is has the listener for the slash command and one connection doesn't, if the event is sent to the version of the app that doesn't have the listener, the event will eventually be sent to the next connection if it doesn't get a timely response. At that point, I think trigger_id is expired.

**Comment by mariebarrramsey** [comment]
Thank you for looking into this! Do you mean multiple socket connections to the slack app or multiple socket connections to anything in general? There aren't any other socket connections to my slack app (or places where there'd be another version). There's a connection to a flask app (nothing to do with slack) in the same file, which is why I'm using handler.connect(). I even tried taking the flask app out and just using handler.start(), but get the same issue. Some things I've noticed: after starting the bolt app, it takes a while for slack to recognize my command (start the connection I assume) and says dispatch_failed for a minute or two. Also, the debugger says DEBUG:slack_bolt.App:on_message invoked: (message: {"type":"hello","num_connections":5,... I'm not sure what the num_connections is for or if this is related. Just trying everything! Is there any other reason this could be happening? Or any possible solutions to this I could try? Thank you!

**Comment by seratch** [comment]
@mariebarrramsey 

>Also, the debugger says DEBUG:slack_bolt.App:on_message invoked: (message: {"type":"hello","num_connections":5,... I'm not sure what the num_connections is for or if this is related

This indicates that your app have other active connections at the moment. If you are not sure where the other connections live, I would recommend trying the following steps:

* Create a new app-level token with [connections:write](https://api.slack.com/scopes/connections:write)
* Switch to the new token for the connection you're currently working on
* Revoke the existing app-level token that can be used by other connections

You can configure app-level tokens at **Settings** > **Basic Information** > **App-Level Tokens** section.

**Comment by mariebarrramsey** [comment]
Wow that was the problem!! Thank you so much! I have no idea how those other connections happened. All I can think is maybe some process was still running in the background or never got properly terminated.
