### ISSUE TITLE
Ephemeral button -- Socket mode

### ISSUE THREAD

**Issue by De1f364** [slackapi/bolt-python#308]
I want to send an ephemeral message with a button to slack, but I get an internal error, I can't figure out what the problem is?

#### The `slack_bolt` version

slack-bolt==1.4.4
slack-sdk==3.4.2

#### Python runtime version

Python 3.8.2

#### OS info

ProductName:    Mac OS X
ProductVersion: 10.15.7
BuildVersion:   19H2
Darwin Kernel Version 19.6.0

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1. Use socket mode
2. Have the following listener

```bash
results_button = {
    "blocks": [
        {
            "type": "actions",
            "block_id": "results_button",
            "elements": {
                "type": "button",
                "action_id": "results",
                "text": {"type": "plain_text", "text": "Results"},
                "value": "click_me_123",
            }
        }
    ]
}

@app.command("/poker")
def go_poker(ack, client, body, respond):
    ack()
    client.chat_postEphemeral(channel=#random, blocks=results_button["blocks"], user=body["user_id"])
```

### Expected result:

I want to send an ephemeral message with a button to slack

### Actual result:

```bash
slack_sdk.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'internal_error'}
```

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by stevengill** [comment]
hey @De1f364,

The code looks fine on first look.

The `internal_error` code is hard to debug from our end. I suggest contacting customer support team as they can help look into the specific error log. You can reach them via https://api.slack.com/support

**Comment by seratch** [comment]
As Steve mentioned, we are unable to do deeper investigation as the internal error code does not provide any other information to the SDK. As suggested above, please contact the support team with your app / workspace information.

This issue may not be resolved yet but as we don't have anything further we can do for you, let me close this issue now. Please feel free to write in whenever you have something further on this.
