### ISSUE TITLE
Any examples of setting up a proxy for k8s?

### ISSUE THREAD

**Issue by jcastro-sfdc** [slackapi/bolt-python#317]
I have the web client connected with no issue but having a bit of trouble getting slack bolt in socket mode to work.  Was wondering if anyone had an example of how to do this.  Thanks

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
👋 Was the above answer helpful to you? Let us know if you have something further to ask/discuss here! I will close this issue after waiting for your response for a few more days.

**Comment by FukkenShit** [comment]
Today I faced the same issue and socket_mode_proxy.py fixed it.

**Comment by jcastro-sfdc** [comment]
thank you @stevengill @seratch @FukkenShit !
