### ISSUE TITLE
how to test liveness with websocket?

### ISSUE THREAD

**Issue by yamlCase** [slackapi/bolt-python#318]
Does websocket have a way for a local user to hit an endpoint for liveness and readyness probes?  with http listener mode this is easy, just curl an endpoint and it works.  But I have no idea how to interact with the SocketModeHandler from the machine running the script.

**Comment by eddyg** [comment]
Have you looked at the [auth.test](https://api.slack.com/methods/auth.test) endpoint? It is one of the recommended ways to check for [availability](https://api.slack.com/faq#availability).

**Comment by yamlCase** [comment]
It looks like auth.test is for testing availability to slack.  I need to test the slack_bot availability for the local user.

**Comment by seratch** [comment]
@yamlCase You can access the underlying WebSocket client's `is_connected(): bool` method.

```python
import logging
logging.basicConfig(level=logging.DEBUG)

import os
from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler

app = App(token=os.environ["SLACK_BOT_TOKEN"])

if __name__ == "__main__":
    handler = SocketModeHandler(app, os.environ["SLACK_APP_TOKEN"])

    # Unlike start() method, connect() method does not block the current thread
    # You can come up with your own way to keep this process
    handler.connect()

    # You can access the following method to check if the WS client is active
    # Ideas for monitoring:
    # 1) start another thread to check this periodically
    # 2) expose this bool value as a Web API and let other service to check the value periodically
    handler.client.is_connected()  # bool
```

**Comment by yamlCase** [comment]
> @yamlCase You can access the underlying WebSocket client's `is_connected(): bool` method.
> 
> ```python
> import logging
> logging.basicConfig(level=logging.DEBUG)
> 
> import os
> from slack_bolt import App
> from slack_bolt.adapter.socket_mode import SocketModeHandler
> 
> app = App(token=os.environ["SLACK_BOT_TOKEN"])
> 
> if __name__ == "__main__":
>     handler = SocketModeHandler(app, os.environ["SLACK_APP_TOKEN"])
> 
>     # Unlike start() method, connect() method does not block the current thread
>     # You can come up with your own way to keep this process
>     handler.connect()
> 
>     # You can access the following method to check if the WS client is active
>     # Ideas for monitoring:
>     # 1) start another thread to check this periodically
>     # 2) expose this bool value as a Web API and let other service to check the value periodically
>     handler.client.is_connected()  # bool
> ```

**Comment by yamlCase** [comment]
oops, didn't mean to close, was trying to cancel a comment.

Thanks for the idea.  so it appears setting up a webapi is going to be the best option for me.
