### ISSUE TITLE
Custom Select Menu in Socket Mode

### ISSUE THREAD

**Issue by mariebarrramsey** [slackapi/bolt-python#319]
I'm trying to create a custom select menu in Socket Mode with external data. Is there a way to send in a precomputed options array to the options listener (https://slack.dev/bolt-python/concepts#options)? Right now, I'm having to create the options array each time my listener is invoked, with something like: options = [{"text": {"type": "plain_text", "text": str(value)}} for value in values] which is taking a long time to load the menu for users. Or is there a better way to return this options list? Thank you!

**Comment by mariebarrramsey** [comment]
I figured this out by storing my options list at a url and pulling the data with requests.get().

**Comment by mariebarrramsey** [comment]
Actually I do have a question on this still. I'm pulling the options list from my url, but the time it takes to make this request is almost 3 seconds (around 2.2). So I guess I do still wonder if there's a way to send in the request as a parameter ahead of time to avoid timing out if this becomes an issue later. Thank you!

**Comment by seratch** [comment]
Hi @mariebarrramsey, the fundamental solution for your issue should be improving the performance of the backend. Also, having a cache layer may mitigate the slow performance of your app. 

In my understanding, there is nothing we can do on the bolt-python side for this. Would you mind closing this issue?

**Comment by mariebarrramsey** [comment]
Ok good to know, thanks!
