### ISSUE TITLE
Error Message Not Showing for Multiselect Menu Modal

### ISSUE THREAD

**Issue by mariebarrramsey** [slackapi/bolt-python#321]
I would like to display an error message in a modal similar to this example: https://api.slack.com/surfaces/modals/using#displaying_errors. Right now I'm using this code for a multiselect menu: https://slack.dev/bolt-python/concepts#view_submissions. 

I do something like this:
```python
client.views_open(
    view={
        "type": "modal",
        "callback_id": "view_1",
        "title": {
          "type": "plain_text",
          "text": "My App",
          "emoji": True
        },
        "submit": {
          "type": "plain_text",
          "text": "Submit",
          "emoji": True
        },
        "close": {
          "type": "plain_text",
          "text": "Cancel",
          "emoji": True
        },
        "blocks": [
          {
            "type": "section",
            "block_id": "block1",
            "text": {
              "type": "mrkdwn",
              "text": "*Select channel*"
            },
            "accessory": {
              "type": "multi_conversations_select",
              "placeholder": {
                "type": "plain_text",
                "text": "Select Channels",
                "emoji": True
              },
              "action_id": "multi_conversations_select-action"
            }
          }
        ]
    }
  )
```
Then later:
```python
@slackApp.view("view_1")
def handle_submission(ack, body, client, view):
  errors = {}

  channels = view["state"]["values"]["block1"]["multi_conversations_select-action"]["selected_conversations"]
  if not channels:
    errors["block1"] = "Please Select a Channel"
  if len(errors) > 0:
    print(errors)
    ack(response_action="errors", errors=errors)
    return 
```

But no red error message shows up on my view saying "Please Select a Channel." I have tried the same thing with a simple input text box (no drop down menu) with "type": "plain_text_input" and the red error box _does_ pop up. Is there something I'm missing here? 

Another thing I've noticed: whenever I choose something from the select menu, I always have this little exclamation point next to the selection box (I assume this means something's going wrong, I'm just not sure what). I don't get any error messages and the submission is able to go through successfully though. 
 
![image](https://user-images.githubusercontent.com/46730081/116760547-13773700-a9ca-11eb-83ae-780069d50d9d.png)

Thank you!

**Comment by seratch** [comment]
Hi @mariebarrramsey, thanks for asking the question!

> I have tried the same thing with a simple input text box (no drop down menu) with "type": "plain_text_input" and the red error box does pop up. Is there something I'm missing here?

As described in [the document](https://api.slack.com/surfaces/modals/using#displaying_errors),

>Upon receiving a view_submission event, your app may want to validate any inputs from the submitted view.

Displaying errors is available only for input blocks. Any non-input blocks are not supported.

>Another thing I've noticed: whenever I choose something from the select menu, I always have this little exclamation point next to the selection box (I assume this means something's going wrong, I'm just not sure what). I don't get any error messages and the submission is able to go through successfully though.

I guess your app is ignoring `block_actions` events from the non-input blocks. You can add `@app.action` event listeners for those blocks as necessary.

I believe I've provided answers to all your questions here. May I ask you to close this issue?

**Comment by mariebarrramsey** [comment]
I see, thank you! Followed your tip and used the "Listening to actions using a constraint object" code at https://slack.dev/bolt-python/concepts#action-listening and got the exclamation to go away.

**Comment by Tannair** [comment]
Somebody already make the validation for sections in blocks slack? Still not supported?

**Comment by seratch** [comment]
@Tannair Unfortunately, it's still unsupported. The only thing that I can suggest at this moment is to fully re-render your `blocks` with an additional error message block in response to a block_actions request.

**Comment by arnav13081994** [comment]
@seratch Is it possible to do `Validation` checks for every `block input` instead of validating all inputs at once on form submission?

I'm currently using a hacky solution where I set `dispatch_action: True` and then listen to the `block_actions` payload. In case of any error, I re-render the view with a `text` appended below the `input group` that was incorrect. I would like to build the same experience as re-rendering errors on `form-submission`. Any help would be greatly appreciated.

**Comment by seratch** [comment]
@arnav13081994 No, it isn't. The workaround that you are already doing is the only thing that I can suggest.

**Comment by arnav13081994** [comment]
Is this feature planned?

**Comment by seratch** [comment]
I don’t have anything that I can share at this moment.
