### ISSUE TITLE
best way of URL handling

### ISSUE THREAD

**Issue by tomerbsentinel** [slackapi/bolt-python#322]
I wonder if there is a "best practice" or everyone is building their own URL parsing mechanism.
Slack are formatting the text into hyperlinks, and I need to overcome this.

I'm getting URLs like: (depends who entered it to the text input)
only text -  google.com
short URL - <google.com|google.com>
Long URL - \<https://google.com|google.com>
 
1. I didn't see it, but, do we have the exact input of the end-user
2. Do anyone have a good practice of how to get only the text out of the pre-formatted command?

**Comment by seratch** [comment]
Hi @tomerbsentinel , thanks for asking the question!

>I didn't see it, but, do we have the exact input of the end-user

No, we don't. Only the top-level `text` property in a payload is available for apps.

>Do anyone have a good practice of how to get only the text out of the pre-formatted command?

We're still consulting other experts but, as far as I know, there is no standard way to do so. For your use case, the current recommendation would be writing your own parser. 🙇

**Comment by seratch** [comment]
👋 I will close this issue soon. Let us know if you have something further to ask/discuss here!
