### ISSUE TITLE
Scope and Permissions to install Application under oAuth in Django Example

### ISSUE THREAD

**Issue by ManuelBuri** [slackapi/bolt-python#324]
(Describe your issue and goal here)

#### The `slack_bolt` version

django-slack-app==1.0.40
django-slack-oauth==1.5.0
slack-bolt==1.5.0
slack-sdk==3.5.1
slackclient==2.9.3

#### Python runtime version

Python 3.8.2

#### OS info

ProductName:    macOS
ProductVersion: 11.1
BuildVersion:   20C69
Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

python manage.py runserver

### Expected result:

I expect the app to install with the requested scope & permissions and are set in the Slack App settings in: https://api.slack.com/apps/

### Actual result:

It tells me that there are no redirect URL and scopes set...
<img width="533" alt="Screenshot 2021-05-05 at 20 54 34" src="https://user-images.githubusercontent.com/28053069/117270636-b52ed600-ae59-11eb-93ae-9bb5bed8acde.png">

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @ManuelBuri , thanks a lot for taking the time to write in!

In the example app, the default env variable `SLACK_SCOPES` works for you but there is no clear guide about it in the app. Sorry about the confusion. I've updated the example app at https://github.com/slackapi/bolt-python/commit/ed7ef1f1bc5fe20f63da41eef8d8a58584e44e0c 

Let me close this issue now but please feel free to write in if you have something further to clarify or ask.

**Comment by ManuelBuri** [comment]
Thank you so much seratch!! Could you also add an example how to add a modal to the app?

**Comment by seratch** [comment]
@ManuelBuri As Bolt is a framework-agnostic framework, [the code in this example](https://github.com/slackapi/bolt-python/blob/main/examples/modals_app.py) should work as-is in your Django app!

**Comment by seratch** [comment]
When it comes to required scopes and configuration, only [commands](https://api.slack.com/scopes/commands) scope is required for handling interactivity through modals. Also, you can enable the **Interactivity & Shortcuts** and set a valid **Request URL** in the Slack app configuration page (`https://api.slack.com/apps/{your app id}/interactive-messages`)

**Comment by ManuelBuri** [comment]
@seratch  if I want to add 

`# This will match any message that contains 👋
@app.message("hello")
def say_hello(message, say):
    # user = message['user']
    say('Hello')`

where do I need to put it?

**Comment by seratch** [comment]
@ManuelBuri You can addd the lines of code at the bottom of `models.py`. Also, the listener utilizes Events API. Your app needs to subscribe to `message` bot events and the app needs to be installed with sufficient OAuth scopes to receive the events.

**Comment by ManuelBuri** [comment]
Thank you @seratch !

**Comment by ManuelBuri** [comment]
@seratch how is it possible to do a custom install page for my slack app?

e.g. replacing the URL slack/install with my own template as seen below:

<img width="388" alt="Screenshot 2021-05-06 at 14 16 17" src="https://user-images.githubusercontent.com/28053069/117296696-a5bd8600-ae75-11eb-9a86-41f23951ebc4.png">

**Comment by seratch** [comment]
@ManuelBuri 
If your app does not need to render the page, you can set `install_page_rendering_enabled=False` (see also https://github.com/slackapi/bolt-python/issues/248)

If you would like to have your own web page, you can override `build_install_page_html` method in `OAuthFlow` class: https://github.com/slackapi/bolt-python/blob/v1.5.0/slack_bolt/oauth/oauth_flow.py#L194-L195 
If you go with this way, you can pass your own `OAuthFlow` in the `App` constructor: https://github.com/slackapi/bolt-python/blob/v1.5.0/slack_bolt/app/app.py#L104

**Comment by ManuelBuri** [comment]
> When it comes to required scopes and configuration, only [commands](https://api.slack.com/scopes/commands) scope is required for handling interactivity through modals. Also, you can enable the **Interactivity & Shortcuts** and set a valid **Request URL** in the Slack app configuration page (`https://api.slack.com/apps/{your app id}/interactive-messages`)

Are you able to indicate which URLs and views I need (in the Django Application) to handle interactivity?

**Comment by ManuelBuri** [comment]
@seratch sorry to bother you, but I just quickly wanted to follow up regarding the URLs and views I need (in the Django Application) to handle interactivity? Thank you so much for your help. Great support!!!!

**Comment by seratch** [comment]
@ManuelBuri You can use `https://{your public domain}/slack/events` for all **Request URL**s in the Slack app configuration: https://github.com/slackapi/bolt-python/blob/c6ec722da8bebb9feb0aef735b2877b5594f99b8/examples/django/slackapp/urls.py#L6
