### ISSUE TITLE
oAuth flow in Django Example: NameError: name 'is_naive' is not defined

### ISSUE THREAD

**Issue by ManuelBuri** [slackapi/bolt-python#325]
There is a NameError within the oAuth flow of the django example...

Reproducible in:
The slack_bolt version
django-slack-app==1.0.40
django-slack-oauth==1.5.0
slack-bolt==1.5.0
slack-sdk==3.5.1
slackclient==2.9.3

Python runtime version
Python 3.8.2

OS info
ProductName: macOS
ProductVersion: 11.1
BuildVersion: 20C69
Darwin Kernel Version 20.2.0: Wed Dec 2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101

Steps to reproduce:

python manage.py runserver

### Expected result:

```
    def save(self, installation: Installation):
        i = installation.to_dict()
        if is_naive(i["installed_at"]):
            i["installed_at"] = make_aware(i["installed_at"])
        i["client_id"] = self.client_id
        SlackInstallation(**i).save()
        b = installation.to_bot().to_dict()
        if is_naive(b["installed_at"]):
            b["installed_at"] = make_aware(b["installed_at"])
        b["client_id"] = self.client_id
        SlackBot(**b).save()
```

### Actual result:

`NameError: name 'is_naive' is not defined`

How do I define is_naive?

**Comment by seratch** [comment]
@ManuelBuri Thanks for reporting this. When I updated the example recently, I failed to add required imports in `models.py `. Fixed by https://github.com/slackapi/bolt-python/commit/33bb0252a84094151d0ef079e850ebeb90a02516

**Comment by ManuelBuri** [comment]
@seratch may I ask how I can retrieve the email address of a user e.g. within the context of a message or event:

````
@app.message(":wave:")
def say_hello(message, say):
    user = message['user']
    say(f"Hi there, <@{user}>!")
````
or

```
# The echo command simply echoes on command
@app.command("/echo")
def repeat_text(ack, say, command):
    # Acknowledge command request
    ack()
    say(f"{command['text']}")
```

so that in the end I get the email address of a user that he/she used to register to slack ?
