### ISSUE TITLE
AWS Lambda adapter is not compatible with AWS event data format v1.0

### ISSUE THREAD

**Issue by matteobaldelli** [slackapi/bolt-python#332]
I am not an expert of AWS lambda but I'm trying to make my first lambda function with bolt but I think this line is wrong

https://github.com/slackapi/bolt-python/blob/31436f729871c38f596a1363aa1d61a5b4c15d0d/slack_bolt/adapter/aws_lambda/handler.py#L81

`cookies: Sequence[str] = event.get("cookies", [])` cookies will be always `[]` because with AWS cookies are not inside event but inside headers, so I think you should do something like that:
`cookies: Sequence[str] = event.get("headers", {}).get("Cookie", [])`

**Comment by seratch** [comment]
Hi @matteobaldelli, thanks for writing in!

The AWS Lambda adapter supports only payload format v2.0. As you can see at [AWS's Developer Guide](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html), the `cookies` exists in the v2.0 format. Perhaps, your app should be using v1.0.

If we receive many requests for supporting both 1.0 and 2.0, we may update the handler code to be compatible with both.

**Comment by matteobaldelli** [comment]
Hi @seratch, I did not know about different version of payload, thanks for the information!

I checked the documentation and now I understand what I was doing wrong with my lambda, maybe you are already aware of it but I still want describe the problem that could be useful to others.
I am using API Gateway to launch my lambda, when you create a new endpoint with API Gateway, you can choose between REST API and HTTP API, I had chosen REST API.
The problem is that REST API don't support payload format v2.0, so since the adapter not support payload format v1.0 I can't use REST API for hit my lambda.
I migrated my endpoint from REST API to HTTP API and now everything works, if you use payload format v1.0 the oauth_flow pages in GET (`/slack/install` and `/slack/oauth_redirect`) will not work.
I opened this issues for the same problem https://github.com/slackapi/bolt-python/issues/330

Maybe I miss that but will be useful to write in the documentation to use payload format v2.0 or support both.

Thanks for the support!

**Comment by seratch** [comment]
@matteobaldelli Thanks a lot for sharing your knowledge with others! 

[The HTTP API was GAed in March, 2020](https://aws.amazon.com/about-aws/whats-new/2020/03/api-gateway-private-integrations-aws-elb-cloudmap-http-apis-release/). In most cases, the HTTP API would be a great fit for building Slack apps. For this reason, we generally recommend using HTTP API and its payload format (2.0). If we see more demands for supporting REST API (format 1.0), we may work on supporting both.

>Maybe I miss that but will be useful to write in the documentation to use payload format v2.0 or support both.

Great idea! I've added a comment mentioning that only 2.0 is now supported: https://github.com/slackapi/bolt-python/commit/6bc0fca14884682032ddc62f555ffe67568b2c69
