### ISSUE TITLE
Passing External Data Selections Between Select Menus 

### ISSUE THREAD

**Issue by mariebarrramsey** [slackapi/bolt-python#336]
I have one form for users with 2 blocks that are external select menus. The first block has a user select one option (call this option 1) and the second block depends on option 1 to show a multi-select menu corresponding to option 1. The user then submits the form. My problem is that I can't access the value the user inputted in the first block within the second block. 

Code Example:

```python
@slackApp.options("block1")
def show_option1(ack, body):
  // CODE DISPLAYS EXTERNAL OPTIONS HERE
  ack(options=options)

@slackApp.options("block2")
def show_option2(ack, body):
  // CODE NEEDS TO GET SELECTED OPTION FROM BLOCK 1 HERE. HOW?
  ack(options=options)


@slackApp.action({
    "block_id": "block1",
    "action_id": "option1"
})
def ack_block1(ack, body, client):
  ack()

@slackApp.action({
    "block_id": "block2",
    "action_id": "option2"
})
def ack_block2(ack, body, client):
  ack()
```

I have tried something like body["view"]["state"]["values"] to grab the view's value from block1, but it seems like the view's state doesn't persist throughout blocks.  

#### The `slack_bolt` version

slack-sdk==3.5.0
slack-bolt==1.5.0

#### Python runtime version

python==2.7.16

#### OS info

ProductName: Mac OS X
ProductVersion: 10.15.7
BuildVersion: 19H524
Darwin Kernel Version 19.6.0

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by mariebarrramsey** [comment]
Whoops I'm using Python 3.7.9! Sorry about that. There was a difference in my local python vs. which one I was using when I ran the code

**Comment by mwbrooks** [comment]
Hey @mariebarrramsey,

I think you'll be able to use the [payload from `block_actions` to find the state of each block](https://api.slack.com/changelog/2020-09-full-state-on-view-submisson-and-block-actions).

For example:
```
@app.action("external_action")
def handle_some_action(ack, body, logger):
    ack()
    logger.info(body["view"]["state"]["values"]["section_1"])
```

**Comment by mariebarrramsey** [comment]
That's what I've been trying, but it doesn't have the value from the previous block (it's just an empty values list even though I can see it successfully submitted by printing values in ack_block1 for example). I think it isn't persisting for some reason because it's all on the same form.

**Comment by mwbrooks** [comment]
Hey @mariebarrramsey, thanks for following up and sorry I misunderstood the issue!

I've re-created your problem as well. The state is included in the `body` while interacting inside the first block (`@app.options("option1")` and `app.action("option1")`). However, when interacting in the second block, the state of the first is not included in the `body`.

This appears to be an API issue, so I've gone ahead and reported this to the Slack Platform API team. Unfortunately, we don't know when it will be fixed but you can [subscribe to the Slack API Changelog](https://api.slack.com/changelog) to get notified when it lands:

```
/feed subscribe https://api.slack.com/changelog.rss
```

Thanks for reporting this issue 🤞🏻 Hope it's resolved soon!

**Comment by mariebarrramsey** [comment]
Is there any update on this? Or maybe a workaround in the meantime? Thank you!

**Comment by nicolas-carlier-ls** [comment]
@mwbrooks Can you confirm if this issue is resolved or not? it looks like not but I could have missed something.
