### ISSUE TITLE
How do I subscribe to block_action using bolt?

### ISSUE THREAD

**Issue by DataGreed** [slackapi/bolt-python#337]
How do I subscribe to `block_action` using bolt? 

I've found the decorator in the source code, but there are no comprehensive examples and the docs omit it. The decorator takes constrains argument, what do I pass there? I tried "button" and the value that I use for my action blocks, but nothing changes. I am just frustrated at this point.

What I am trying to do:
I am trying to open a modal when user clicks on a button in an ephemeral message.

**Comment by seratch** [comment]
Hi @DataGreed, thanks for trying Bolt out!

[This example](https://github.com/slackapi/bolt-python/blob/main/examples/modals_app.py) is not the exact one you're looking for but it should be helpful. 

You can pass the `action_id` of the button in your ephemeral message to handle its click events. The complete example would look like this:

```python
@app.command("/socket-mode-run")
def handle_command(body, ack, logger):
    logger.info(body)
    ack(
        text="You can add a button alongside text in your message.",
        blocks=[
            {
                "type": "section",
                "block_id": "some-block",
                "text": {
                    "type": "mrkdwn",
                    "text": "You can add a button alongside text in your message.",
                },
                "accessory": {
                    "type": "button",
                    "action_id": "button-id",
                    "text": {"type": "plain_text", "text": "Button"},
                    "value": "click_me_123",
                },
            }
        ],
    )

@app.action("button-id")
def button_click(ack, body, logger, client):
    ack()
    res = client.views_open(
        trigger_id=body["trigger_id"],
        view={
            "type": "modal",
            "callback_id": "view-id",
            "title": {
                "type": "plain_text",
                "text": "My App",
            },
            "submit": {
                "type": "plain_text",
                "text": "Submit",
            },
            "close": {
                "type": "plain_text",
                "text": "Cancel",
            },
            "blocks": [
                {
                    "type": "input",
                    "block_id": "title",
                    "element": {
                        "type": "plain_text_input",
                        "action_id": "text-input",
                    },
                    "label": {
                        "type": "plain_text",
                        "text": "Title",
                    },
                },
            ],
        },
    )
    logger.info(res)


@app.view("view-id")
def view_submission(ack, body, logger):
    ack()
    logger.info(body["view"]["state"]["values"])
```

**Comment by DataGreed** [comment]
Oh, thank you so much! I think this really should be documented, as it quite not obvious how to set it up just using the bolt's documentation. I tried to use `event` argument instead of `body` - I really thing that the listener function signature should be documented, too.

**Comment by seratch** [comment]
@DataGreed The current recommendation is to check the module documents:
* More detailed information about listeners: https://slack.dev/bolt-python/api-docs/slack_bolt/app/app.html
* All available listener arguments: https://slack.dev/bolt-python/api-docs/slack_bolt/kwargs_injection/args.html

You can the documents from "API Documents" in the left section of https://slack.dev/bolt-python

**Comment by DataGreed** [comment]
@seratch thanks, although this is kind of a guessing game at this point on what arguments are passed to which listeners :( 

Having a full list helps to narrow down the possible options, though.

**Comment by DataGreed** [comment]
@seratch thank you! That's good to know the decision behind the design, helps to understand what's going on better.
