### ISSUE TITLE
Mention user with user_id insertion not working

### ISSUE THREAD

**Issue by ManuelBuri** [slackapi/bolt-python#343]
I would like to tag a user like this `@user`. Therefore I am creating the following `block` and post it via `client.chat_postMessage(token=token, channel=user_id,  block=myblock)`

```
token = 'xxxxxxxxx'

user_id =U01M828QQJZ

myblock = [
		{
			"type": "section",
			"text": {
				"type": "plain_text",
				"text": "Hello <@"+user_id+">, how are you today?",
				"emoji": true
			}
		}
	]
```

Result:
`Hello <@U01M828QQJZ>, how are you today?`

Why is the user not properly tagged in my example?

**Comment by mwbrooks** [comment]
Hey @ManuelBuri 👋🏻 

I believe you'll need to change the type from `plain_text` to `mrkdwn` to support [advanced formatting such as mentioning users](https://api.slack.com/reference/surfaces/formatting#mentioning-users).

Would you mind trying the following (note: `emoji` must also be removed):

```
{
    "type": "section",
    "text": {
        "type": "mrkdwn",
        "text": "Hello <@"+user_id+">, how are you today?"
    }
}
```

**Comment by ManuelBuri** [comment]
Working! Thanks so much @mwbrooks
