### ISSUE TITLE
Action not getting triggered, 404 response.

### ISSUE THREAD

**Issue by LucasLundJensen** [slackapi/bolt-python#345]
I'm having an issue with actions.
I have my blocks, but every time I click the button, I get a 404 through ngrok:

```Python
{
        "type": "section",
        "text": {
          "type": "mrkdwn",
          "text": f"Hi, {user_name} Welcome to NAME for Slack \n*We can help you get instant recommendations for different types of stressful situations happening at work, here is how it works.*"
        }
      },
      {
        "type": "section",
        "text": {
          "type": "mrkdwn",
          "text": "👉Tell us what’s going on\n🔠 What word or sentence describe better how you feel\n😊 NAME will propose a session, activity or advice for you to follow"
        }
      },
      {
        "type": "actions",
        "elements": [
          {
            "type": "button",
            "text": {
              "type": "plain_text",
              "text": "Ask NAME for help."
            },
            "value": "get_help_button",
            "action_id": "get_help_button"
          }
        ]
      }
```

```Python

@app.action("get_help_button")
def handle_get_help_button(ack, say):
  ack()
```

I have my Interactivity Request URL set to: https://*SOMETHING*.ngrok.io/slack/interactive-endpoint
as it's displayed in the Placeholder text on the website, but I still keep getting 404.
`POST /slack/interactive-endpoint 404 Not Found`

I assume it's because my Request URL isn't what the bolt-python library expects? But I can't see anywhere in any documentation or the code that it has a reference to any /slack/ endpoints besides /slack/events

### Reproducible in:

```bash
slack-bolt==1.6.0
slack-sdk==3.5.1
Python 3.9.2
Microsoft Windows [Version 10.0.19042.928]
2020-08-22 17:48
```

#### The `slack_bolt` version

slack-bolt==1.6.0
slack-sdk==3.5.1

#### Python runtime version

Python 3.9.2

#### OS info

Microsoft Windows [Version 10.0.19042.928]
2020-08-22 17:48

#### Steps to reproduce:

Source code was posted earlier, but I'll post the whole code if needed :)

### Expected result:

I'd expect my @app.action to get triggered.

### Actual result:

My @app.action() doesn't get triggered, and I get a 404 from NGROK.
![image](https://user-images.githubusercontent.com/1708115/119165196-8883dc80-ba5d-11eb-873f-af1655f07d1a.png)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hey @LucasLundJensen, thanks for using Bolt for Python! 

Bolt handles all types of requests from Slack at the same path `/slack/events` by default. If using the default path is fine for you, can you update the **Request URL** in your Slack app configuration? 

If you use a single customized path for all incoming requests, 

* The default development server: `app.start(path="/slack/interactive-endpoint")`
* Flask example: https://github.com/slackapi/bolt-python/blob/v1.6.0/examples/flask/app.py#L34

If you have some reason to serve multiple paths for a single Slack app (say, `"/slack/interactive-endpoint"` for Interactivity, "/slack/events-endpoint" for Events API), you can instantiate multiple `App` with relevant listeners.

```python
from slack_bolt import App

events_app = App()
@events_app.event("app_mention")
def handle_mentions():
    pass

interactivity_app = App()
@interactivity_app.action("foo")
def handle_actions(ack):
    ack()

from flask import Flask, request
from slack_bolt.adapter.flask import SlackRequestHandler

flask_app = Flask(__name__)
events_handler = SlackRequestHandler(events_app)
interactivity_handler = SlackRequestHandler(interactivity_app)

@flask_app.route("/slack/events-endpoint", methods=["POST"])
def handle_events_api_requests():
    return events_handler.handle(request)

@flask_app.route("/slack/interactivity-endpoint", methods=["POST"])
def handle_interactivity_api_requests():
    return interactivity_handler.handle(request)

# export SLACK_SIGNING_SECRET=***
# export SLACK_BOT_TOKEN=xoxb-***
# FLASK_APP=app.py FLASK_ENV=development flask run -p 3000
```

As I've provided an answer for your question here, let me close this issue now. Please feel free to write in if you have anything further to discuss/ask.
