### ISSUE TITLE
How to use bolt with django?

### ISSUE THREAD

**Issue by Tijani-Dia** [slackapi/bolt-python#347]
Hello, I've been trying to use bolt-python with django following [this example](https://github.com/slackapi/bolt-python/tree/main/examples/django). 
I am not an experimented programmer so as is, I found that there is not enough documentation for the example.

Some steps are indicated in the comments - like [this](https://github.com/slackapi/bolt-python/blob/51daa120da1d10d0fff3b937099eaa0fca563b96/examples/django/slackapp/settings.py#L108-L118), does it mean one can use both mysql and sqlite as databases or what does it exactly mean.

Moreover, the following indication in README:
> Follow the instructions here for configuring OAuth flow supported Slack apps

is a bit confusing for me. The same steps are outlined in the example's models.py file.

Also, there isn't a clear explanation of what does what and why so it's very hard to understand the code.

I've been trying to run a django app following your example, I have inspected and reinspected the example, but when send a message or mention the app in Slack, nothing happens.

I will be happy to improve the documentation for the  Django example, if first I get a better sense of how does it work. I have these questions for example:

How does the request/response cycle happen? 
Why listeners are defined on models.py ?

I guess the Django example assumes one is comfortable with both Slack API and django. It would be nice if general guidelines or a guide indicating which steps are necessary to setup bolt with django were provided for all Django apps in addition of having to go through the code to see how to make it happen.

This is a beginner question but I'm struggling with it and there aren't many topics on bolt and django out there.

Thanks in advance.

**Comment by seratch** [comment]
Hi @Tijani-Dia, thanks for trying bolt-python out! 

>I guess the Django example assumes one is comfortable with both Slack API and django. It would be nice if general guidelines or a guide indicating which steps are necessary to setup bolt with django were provided for all Django apps in addition of having to go through the code to see how to make it happen.

I appreciate the suggestion. As you guessed, in the Django example, we don't guide the basics about the Django framework itself. However, I agree that the README file can be more beginner-friendly. 

>Some steps are indicated in the comments - like this, does it mean one can use both mysql and sqlite as databases or what does it exactly mean.

For running the app immediately, using SQLite would be much handier. I'll update the example to use SQLite by default and will have more comments about MySQL.

>Follow the instructions here for configuring OAuth flow supported Slack apps is a bit confusing for me. The same steps are outlined in the example's models.py file.
>Also, there isn't a clear explanation of what does what and why so it's very hard to understand the code.

Thanks for the helpful feedback. I will organize them a bit later. 

>I've been trying to run a django app following your example, I have inspected and reinspected the example, but when send a message or mention the app in Slack, nothing happens.
>How does the request/response cycle happen?
>Why listeners are defined on models.py ?

I can suggest that learning from the Getting Started guide & Slack OAuth basics without the Django adapter may be a quicker way to figure out the Bolt framework:
* https://slack.dev/bolt-python/tutorial/getting-started
* https://slack.dev/bolt-python/concepts#authenticating-oauth

Thanks again for your feedback. I will update the README to make it somewhat better. If you have more suggestions, sending pull requests / sharing your ideas would be appreciated.

Lastly, I wanted to mention that we are not planning to have a thorough guide about Django app development itself. If you don't agree with some parts of it (say, modifying `views.py` for it), that's totally fine. The example should be reasonable and good enough, but it's not necessarily the only way to go with Bolt.

**Comment by seratch** [comment]
@Tijani-Dia Thanks for your great feedback here. I've updated the Django example a lot. I hope the updated ones are easier to understand for you. Let me close this issue now but please feel free to write in if you have something further to ask/discuss.

**Comment by Tijani-Dia** [comment]
@seratch I would not dream of a better feedback than this! 
Everything is so clear now. Thanks a lot!

**Comment by tomdyson** [comment]
@seratch this is such a helpful response! Thank you. FYI @Tijani-Dia is researching this as part of his work on `wagtail-live`, which is his Google Summer of Code project for this year:

https://github.com/wagtail/wagtail/wiki/Google-Summer-of-Code-2021#wagtail-live
