### ISSUE TITLE
Re: External Data Selection in Select Menu

### ISSUE THREAD

**Issue by mariebarrramsey** [slackapi/bolt-python#349]
I posted an issue: https://github.com/slackapi/bolt-python/issues/336 where I'm unable to access external data from different blocks within the same form. 

Is there a workaround to this? I think there must be some way to use the action block (we're able to access the input data from the first block here) to somehow update the view with a list of options for the next block? A solution similar to this is mentioned [here](https://stackoverflow.com/questions/61789719/slack-dialog-external-data-source-filtering) but some input here would be helpful.

Thank you!

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by mariebarrramsey** [comment]
I've also tried some nesting to access the first block's selection:

@slackApp.action({
        "block_id": "block1",
        "action_id": "action1"
    })
    def ack_block1(ack, body):
      ack()
      dashboard_name = body["view"]["state"]["values"]["block1"]["action1"]["selected_option"]["value"]
      options = list()
      
      # assume my external data is in some list called my_data
      for item in my_data:
          options.append({
              "text": { "type": "plain_text", "text": str(item) },
              "value": str(item)
          })
          
      @slackApp.options("block2")
      def show_options(ack, body):
      # this options never gets updated if the selection in block1 is ever changed. No way to access the state from body here (it's just an empty array).
        ack(options=options)
        
      @slackApp.action({
        "block_id": "block2",
        "action_id": "action2"
      })
      def ack_block2(ack, body, client):
        ack()
        
   Which doesn't work because if you change the first block's selection the results shown in the second block never get updated to reflect this (they will always be the results from the first choice that was ever selected in block 1). There's also no way to access the state in block 2 even in this nested format.

**Comment by seratch** [comment]
Hi @mariebarrramsey , thanks for asking the question!

> this options never gets updated if the selection in block1 is ever changed. No way to access the state from body here (it's just an empty array).

If I understand this correctly, this is an intended behavior of the platform. The only thing I can suggest here is to initialize the `options` value (perhaps, it's a global variable) before the initial `block_actions` request. 

>@slackApp.options("block2")

I guess the `block2` here is a block ID. If so, this code doesn't work as you expect. Either `@app.options("action-id")` or `@app.options({"block_id": "block2", "action_id": "action-id"})` works for you.

Also, one thing I noticed here is that, if the `options` is a global object, your app may need to consider possible race conditions. If the app will be used by only a single person (say, the admin of the workspace or a specific person), that's totally fine. But if multiple users can simultaneously use your app, the global scope data on the server-side (= `options` here) can be shared among multiple end users and that may cause data corruptions or misbehaviors. Hope the design is fine for your use case and I was too much worrying about it. 

With the given information, I don't have any further suggestions here. Do you have something else to ask here? If everything is clear, would you mind closing this issue?

**Comment by mariebarrramsey** [comment]
"block2" there is supposed to be the action-id, sorry. Is there no way to access the value from a previous block then? My intended use case is to have the user enter a value in block1, and then have options show up in block2 depending on what was entered in block1. In the previous thread where I asked the question, I was told there is a bug in the api.

**Comment by seratch** [comment]
@mariebarrramsey 
>In the previous thread where I asked the question, I was told there is a bug in the api.

The issue mentioned in the previous issue is the one about `block2` value in the `view.state.values` in a `block_actions` request for `block1`.

>My intended use case is to have the user enter a value in block1, and then have options show up in block2 depending on what was entered in block1.

If your app can update the `block2`'s select menu options **only considering the state for `block1`**, the above `state` value issue does not affect your app. You can receive the selected item in the listener's `action` argument.

Let me share another way to update the select menu. In the `@app.action({"block_id": "block1", "action_id": "action1"})` listener, your app can **update the whole modal** by calling [views.update API method](https://api.slack.com/methods/views.update). In the updated modal, the block2 select menu can have `initial_options`.

I hope this was helpful to you.

**Comment by mariebarrramsey** [comment]
Can you elaborate on how to "receive the selected item in the listener's action argument"? My app will have the user choose ONE option in block1, and this one option will create a LIST of choices for the multi-select menu in block2.

As for the initial_options argument, this won't work for me because I'm going to have a multi-select menu and it would be tedious to have to uncheck all of the initial_options the user didn't want.

Thanks

**Comment by seratch** [comment]
@mariebarrramsey 
>Can you elaborate on how to "receive the selected item in the listener's action argument"? My app will have the user choose ONE option in block1, and this one option will create a LIST of choices for the multi-select menu in block2.

Never mind about the details here. I wanted to say that your app can know which item in the block1 select menu from the payload. And, the value for block1 should always exist while the one for other blocks may not.

>As for the initial_options argument, this won't work for me because I'm going to have a multi-select menu and it would be tedious to have to uncheck all of the initial_options the user didn't want.

In this case, I don't have any further suggestions. I'm sorry for the inconvenience regarding this.

**Comment by mariebarrramsey** [comment]
I see, so there is no solution until accessing the state from different blocks is fixed in the api?

**Comment by mariebarrramsey** [comment]
One last solution I thought of was having the results of block2 appear after a "submit" button is hit and try to access the state somehow in this way, but I think this may run into the same issues I'm facing now/ is also not ideal for my application.

**Comment by seratch** [comment]
>I see, so there is no solution until accessing the state from different blocks is fixed in the api?

There is no other workaround as far as I know.

>One last solution I thought of was having the results of block2 appear after a "submit" button is hit and try to access the state somehow in this way, but I think this may run into the same issues I'm facing now/ is also not ideal for my application.

If you are okay to ask your end-users click the "Submit" button for updating block2, it should work for you. I've never heard of the situation where some of the inputs in a `view_submission` payload are missing. You can expect all the state values surely exist. 

Also, as you may know, doing this way is a very common pattern to implement complex modals. I understand this approach is not ideal for you but I think it's not so bad.

**Comment by mariebarrramsey** [comment]
For the button option, can you give an example of how to grab the value from block1 in block2? I've tried adding a button block and accessing the state but I can't seem to come up with the correct approach. Thank you!

**Comment by seratch** [comment]
> can you give an example of how to grab the value from block1 in block2

The approach I mentioned in my previous comment is a different approach. The "Submit" button I mean here is the one in the footer part of a modal. It's not a button block you place in `blocks`. 

Your app can handle the submission event, which includes all the inputs in `view.state.values`, by `@app.view` listener. You can respond to the `view_submission` request by `ack(response_action="update", view=updated_modal)`. Perhaps, this is not the one you want, though.

**Comment by mariebarrramsey** [comment]
I've tried the ack(response_action="update", view=updated_modal) for the view_submission of view_1, but am still unable to access the state to display options in @app.options("action-id-2") for example. I really don't see how to access the state here, is there something I'm missing? Thanks

**Comment by seratch** [comment]
@mariebarrramsey 
If the block is an `input` typed block, you should be able to access its value by `view["state"]["values"]["block-id-2(your actual one)"]["action-id-2"]`. The `view` is a possible argument in your `@app.view` listener. 

Again, this is not exactly the same thing you wanted to build. If this does not work for you, I don't have anything further I can share at this point.

**Comment by mariebarrramsey** [comment]
Ok, thank you. I was able to find a solution using the private_metadata field to send data from one view to the next (to get the selection from block1 to block2).
