### ISSUE TITLE
Is there a way to send "bot is typing" event?

### ISSUE THREAD

**Issue by master0v** [slackapi/bolt-python#351]
Is there a way to have the following message appear to make the bot appear more human-like?

<img width="154" alt="Screen Shot 2021-05-25 at 6 42 26 PM" src="https://user-images.githubusercontent.com/18746987/119577715-27c01100-bd89-11eb-8edb-c7e83ef880bf.png">

**Comment by stevengill** [comment]
Hey @master0v 

This functionality is not possible with the events API. It was possible with the old RTM API but RTM will be deprecated soon so it isn't recommended using it. 

If you don't mind, what is your usecase for it?

**Comment by master0v** [comment]
The bot that we are building is a deep conersational bot.  User studies have shown that it works better with delays between messages, so I need to "fill" these delays with "Bot typing".  I already do it on other platforms, and it works well.

**Comment by seratch** [comment]
@master0v Thanks for sharing that. As Steve mentioned, unfortunately we no longer support the feature in the latest event subscription model. The only thing I personally can suggest is to use [ephemeral messages](https://api.slack.com/messaging/managing#ephemeral) as below.

<img src="https://user-images.githubusercontent.com/19658/119591377-70bba800-be11-11eb-91b2-1a4fe113f989.gif" width=600/>

Here is a simple example code. As ephemeral ones eventually disappear, using both [chat.postMessage](https://api.slack.com/methods/chat.postMessage) and [chat.postEphemeral](https://api.slack.com/methods/chat.postEphemeral) may make the app experience better.

```python
@app.event("app_mention")
def event_test(event, client: WebClient):
    client.chat_postEphemeral(
        channel=event["channel"],
        user=event["user"],
        text=":wave: Hi there! Let me start the conversation. Please wait a sec... :stopwatch:",
    )

    # preparing the next question depending on the context
    time.sleep(2)

    # To keep this question in the DM, chat_postMessage may be better
    client.chat_postEphemeral(
        channel=event["channel"],
        user=event["user"],
        text="Okay, first of all, can you tell me a bit more details about the story?",
    )
```

This may not be a good solution for the use case, but I hope this was helpful to you.

**Comment by seratch** [comment]
I will share your feedback with the teams concerned. Once the feature is added to the platform, the update will be announced in [our changelog website](https://api.slack.com/changelog). And then, we will add the support to all the SDKs. 

Thanks a lot for your great inputs here. As we are unable to track the progress of product updates in this issue tracker, let me close this issue.
