### ISSUE TITLE
Sign in with Slack in Django App

### ISSUE THREAD

**Issue by ManuelBuri** [slackapi/bolt-python#352]
Hi, I am looking for a well documented example or django library that helps to handle ['Sign in with Slack' ](https://api.slack.com/docs/sign-in-with-slack). Any ideas/suggestions?

Thank you very much.

**Comment by seratch** [comment]
Hi @ManuelBuri , thanks for asking the question! We don't have Python examples but checking the example app I shared at https://github.com/slackapi/bolt-js/issues/840#issuecomment-822246907 should be helpful to you too!

**Comment by ManuelBuri** [comment]
Thank you for your feedback @seratch. Would you also recommend e.g. using [`django-allauth` package](https://django-allauth.readthedocs.io/en/latest/installation.html)? Any experiences, feedback etc.?

**Comment by ManuelBuri** [comment]
@seratch I am using `django-allauth`now but get a bad_redirect_uri eventough I have specified everything in a right way it seems. Have you ever heard of this problem?

**Comment by seratch** [comment]
@ManuelBuri As mentioned in [the API document](https://api.slack.com/methods/oauth.v2.access#errors),
>Value passed for redirect_uri did not match the redirect_uri in the original request.

Your authorize URL redirection should have the exactly same redirect_uri with the one set in your Slack App configuration page (`https://api.slack.com/apps/{your app id}`).

> django-allauth

I don't have any experience with this package. If you encounter something unexpected, implementing plain Django endpoints like I did with Express.js may be easier to debug: https://github.com/slackapi/bolt-js/issues/840#issuecomment-822246907

**Comment by ManuelBuri** [comment]
Yes, so I am having exactly the same redirect_uri as in the `OAuth & Permissions` section of the Slack App Configurations. Any ideas why it is not working?
Thank you very much @seratch

**Comment by amadeann** [comment]
Old issue, but I ran into the same problem today, and it was one of the first Google results, so I post a solution:

In addition to adding request_uri to Slack app in the dashboard, you need to send that URL in both the Authorization Request (that part where the user accepts scopes you're requesting), and Authorization Grant request (where you pass the code you got from Slack in the previous request, and ask for something like "incoming webhook" for example).

Based on the docs it seemed to me like I only had to pass redirect_uri in the Authorization Request, and it even worked with just that until I added multiple request_uris to Slack dashboard (different ones for local, staging, and production).
