### ISSUE TITLE
How to send a voice/audio to a user from the app?

### ISSUE THREAD

**Issue by master0v** [slackapi/bolt-python#353]
How do I send an audio/voice to a user from the app so that it appears like this:

<img width="436" alt="Screen Shot 2021-05-27 at 3 11 03 PM" src="https://user-images.githubusercontent.com/18746987/119887092-b3f54400-bf01-11eb-814a-0c2d4c32d28f.png">

video would be good too.

**Comment by seratch** [comment]
Hi @master0v, as long as you use common file formats, all you need to do is just to upload your audio/video files using `files.upload` API!

```python
import logging, os
logging.basicConfig(level=logging.DEBUG)

from slack_sdk.web import WebClient
client = WebClient(token=os.environ["SLACK_BOT_TOKEN"])

channels = ",".join(["#random"])

# Upload an audio file to #random channel
filepath = "./test-recording.m4a"
response = client.files_upload(channels=channels, file=filepath)

# Upload a video file to #random channel
filepath = "./test-video.mov"
response = client.files_upload(channels=channels, file=filepath)
```

By doing above, you will see the preview as below:

<img width="300" src="https://user-images.githubusercontent.com/19658/119918863-2f0f3680-bfa4-11eb-8c86-6597e71b2879.png">

If the automatic file format detection does not work for your files, you can set `type` etc. in the files.upload` API call. Refer to https://api.slack.com/methods/files.upload for available parameters and more details.

If everything is clear, would you mind closing this issue?

**Comment by master0v** [comment]
Hi Kazuhiro Sera,

Thank you for the explanation and for the code sample.  My app is going to be sending the same file to thousands of users.  Is there a way to upload it to slack once, and then send it to users in a message by file id?

Thanks,
Alexei

**Comment by seratch** [comment]
@master0v As [Block Kit supports only remote files](https://api.slack.com/reference/block-kit/blocks#file) so far, the only way I can suggest is to have a file's permalink in your message:

```python
from slack_sdk.web import WebClient
client = WebClient(token=os.environ["SLACK_BOT_TOKEN"])

upload_response = client.files_upload(file="./tmp.txt")
file_permalink = upload_response["file"]["permalink"]

message_response = client.chat_postMessage(
    channel="C12345",
    text=f"Here is the uploaded file: {file_permalink}",
)
```

This should work as you expect. Let me know if you have anything further to ask.

**Comment by master0v** [comment]
That unfortunately shows the full url of the permalink, which is kind of ugly.  Is there any way to hide it?

<img width="751" alt="Screen Shot 2021-05-28 at 6 53 33 PM" src="https://user-images.githubusercontent.com/18746987/120048821-35be9d80-bfe6-11eb-95c0-4cf8523868f7.png">

**Comment by seratch** [comment]
You can use a special syntax in message formatting: https://api.slack.com/reference/surfaces/formatting#linking-urls
Doing like `f"Here is <{file_permalink}|the uploaded file>"` can improve this.

**Comment by master0v** [comment]
Thanks.  Do you think I can use files_remoteAdd and files_remoteShare to improve the visual presentation?

**Comment by seratch** [comment]
>(i.e. pretend that the permalink is actually a remote file)

First off, the `files.remote.*` APIs are designed for external (=not slack.com) URLs. For this reason, we don't recommend it. 

Also, trying to do so won't improve the presentation as the remote file API allows having only [preview image](https://api.slack.com/methods/files.remote.add#arg_preview_image). The audio/video players are not supported, and, as far as I know, there is no plan to add them in the short term.

**Comment by master0v** [comment]
understood.  Thanks for your help.   Will try to do something with markdown to hide the URL as you suggested.
