### ISSUE TITLE
Is there a cleaner way to use user tokens to call user scope APIs?

### ISSUE THREAD

**Issue by akshatd** [slackapi/bolt-python#356]
I am a newbie to the slack API and web programming in general and was trying to understand how OAuth works in bolt.
From what I gather, if I use the flow described [here](https://slack.dev/bolt-python/concepts#authenticating-oauth), I should be able to add my app to any workspace and get a bot_token corresponding to the workspace.

In addition, every time a user clicks on the /slack/install URL for my app, their user_token will also be generated and stored in the `App.installation_store`.

It seems like once my App has been installed using this flow, I do not need to get the bot token by doing `installation_store.find_bot` and use it with `token=` to call `client.views_publish` to publish a view on my homepage, the bot token seems to be implicitly attached when the request is sent.

However, I cannot use any APIs that require any user scopes implicitly, I have to query `installation_store.find_installation` to get the user token which i can then use to call client APIs that require any user scopes. In particular, I would like to have a personalized welcome screen for every user, but I have to resolve their user name by doing 
``` python
@app.event("app_home_opened")
def update_home_tab(client, event, logger):
  try:
    installation = app.installation_store.find_installation(user_id=event["user"], team_id=event["view"]["team_id"], enterprise_id=event["view"]["enterprise_id"])
    user_profile = client.users_profile_get(token=installation.user_token, user=event["user"])
    # views.publish is the method that your app uses to push a view to the Home tab
    client.views_publish(
      # the user that opened your app's app home
      user_id=event["user"],
      # the view object that appears in the app home
      view={
        "type": "home",
        "callback_id": "home_view",

        # body of the view
        "blocks": [
          {
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": "*Welcome to your Meeterbot's Home_* :tada:"
            }
          },
          {
            "type": "divider"
          },
          {
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": "Hi " + user_profile["profile"]["real_name"]
            }
          },
          {
            "type": "actions",
            "elements": [
              {
                "type": "button",
                "text": {
                  "type": "plain_text",
                  "text": "Connect your Slack"
                },
                "url": "google.com"
              }
            ]
          }
        ]
      }
    )

  except Exception as e:
    logger.error(f"Error publishing home tab: {e}")

```

I tried to read all the bolt documentation, but cannot figure out how to call APIs that use user scopes implicitly based on the user triggering the event without doing a lookup everytime.

Apologies in advance if this is the correct way of doing things and I wasted everyone's time

### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version

slack-bolt==1.6.0
slack-sdk==3.5.1

#### Python runtime version

Python 3.8.5

#### OS info

(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)
I am working with WSL2
- uname -a: 
Linux aperturelabs 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- ver: Microsoft Windows [Version 10.0.19042.985]
#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1.
2.
3.

### Expected result:

(Tell what you expected to happen)

### Actual result:

(Tell what actually happened with logs, screenshots)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @akshatd, thanks for asking the question! In this scenario, your listener function should be able to access the relevant user token by `context.user_token`.

```python
@app.event("app_home_opened")
def update_home_tab(client, event, logger, context):
  try:
    user_profile = client.users_profile_get(token=context.user_token, user=event["user"])
```

If you would like to know how the value is set to the `context`, check the following code:
* https://github.com/slackapi/bolt-python/blob/v1.6.0/slack_bolt/authorization/authorize.py#L133-L167
* https://github.com/slackapi/bolt-python/blob/v1.6.0/slack_bolt/authorization/authorize.py#L212
* https://github.com/slackapi/bolt-python/blob/v1.6.0/slack_bolt/middleware/authorization/multi_teams_authorization.py#L55-L62
* https://github.com/slackapi/bolt-python/blob/v1.6.0/slack_bolt/context/base_context.py#L92-L93
* https://github.com/slackapi/bolt-python/blob/v1.6.0/slack_bolt/context/base_context.py#L77-L80

I hope this was helpful to you. If everything is clear now, would you mind closing this issue?

**Comment by akshatd** [comment]
Thank you so much for the quick response!

So if I understand correctly, all of the things mentioned [here](https://github.com/slackapi/bolt-python#making-things-happen) can be accessed from the callback function as long as they are in the arguments?

Would be really great if you could point me to the documentation for them where I can see what attributes and methods all the arguments have. Otherwise, I'll close the issue, thanks! :)

**Comment by seratch** [comment]
@akshatd 
>So if I understand correctly, all of the things mentioned here can be accessed from the callback function as long as they are in the arguments?

You're right. 

>Would be really great if you could point me to the documentation for them where I can see what attributes and methods all the arguments have. Otherwise, I'll close the issue, thanks! :)

Checking [this API document](https://slack.dev/bolt-python/api-docs/slack_bolt/kwargs_injection/args.html) should be helpful to you. As we recently started providing the API document, there aren't enough navigation to this API document page. I will create a new issue for updating API document website and fix it later. Thanks for your inputs! Let me close this issue.
