### ISSUE TITLE
How to listen for a block action payload

### ISSUE THREAD

**Issue by surajreddykarra** [slackapi/bolt-python#357]
I'm experimenting with slack API to implement an approval mechanism.

### Scenario
The bot listens for the word "aws" in a private channel and sends a block message to a manager (same user in the code for simplicity).
The block contains two buttons - Approve/Deny. 
If the manager approves using the Button, the bot has to send a confirmation message back  to the original channel.

### Issue
After sending the block message, **how do I receive the payload if someone clicks on the block_action button**.
I've used the Block Kit Builder for the block. It doesn't append an action_id by default.

I've tried listening for a particular button using the `@app.block_action("action_id")`. However, it doesn't return me the complete payload like it shows in the Block Kit Builder. I need the full Action Preview for message context. 

### Reproducible in:

```bash
slack-bolt==1.6.0
slack-sdk==3.5.1
Python 3.8.5
#60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021
```

#### The `slack_bolt` version

slack-bolt==1.6.0
slack-sdk==3.5.1

#### Steps to reproduce:

````
import os
import json
from slack_bolt import App

app = App(
    token=os.environ.get("SLACK_TOKEN"),
    signing_secret=os.environ.get("SLACK_SIGNING_SECRET")
    )

def get_approval(client, message):
    user = message['user']
    blocks =[
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": "You have a new request:\n*<fakeLink.toEmployeeProfile.com|Fred Enriquez - New resource request>*"
            }
        },
        {
            "type": "actions",
            "elements": [
                {
                    "type": "button",
                    "text": {
                        "type": "plain_text",
                        "text": "Approve"
                    },
                    "action_id": "res_approve",
                    "style": "primary",
                    "value": "approved"
                },
                {
                    "type": "button",
                    "text": {
                        "type": "plain_text",
                        "text": "Deny"
                    },
                    "action_id": "res_reject",
                    "style": "danger",
                    "value": "rejected"
                }
            ]
        }
    ]
    client.chat_postMessage(
        channel = user,
        text = "Request block sent",
        blocks = blocks
    )
    
    #_____________________________________________

    @app.button_action("res_approve") #            <---------- This will only return me the specific button actions
    def agree(payload, ack):
        ack()
        print(payload)
    
    #_____________________________________________



    #                    <-------- How can I listen for the complete payload like it's mentioned in BLOCK KIT BUILDER 

    # return true/false based on the payload received




@app.message("aws")
def cloud_resource_request(client, message, say):
    user = message['user']
    decision = get_approval(client, message)
    if decision:
        client.chat_postMessage(
            channel = user,
            text = "your manager has approved your resource Cloud Resource Request"
        )
    else:
        client.chat_postMessage(
            channel = user,
            text = "your manager has declined your resource Cloud Resource Request"
        )



if __name__ == "__main__":
    app.start(port=int(os.environ.get("PORT",5400)))

````

### Expected result:
I'm expecting to receive something like this, so I can get the entire context to the message.
This is a snapshot of the Block Kit Builder's action preview
![Screenshot from 2021-06-01 00-04-13](https://user-images.githubusercontent.com/64362314/120230838-c78c0c00-c26d-11eb-8468-b16cc6df8b5f.jpg)

### Actual result:
I get this when I specifically listen to the APPROVE button.
**Is this how it is supposed to run or is there something I'm missing out?** 
````
{
    'action_id': 'res_approve', 
    'block_id': '1//b', 
    'text': {
        'type': 'plain_text',
        'text': 'Approve',
        'emoji': True
     },
     'value': 'approved',
     'style': 'primary',
     'type': 'button',
     'action_ts': '1622478526.721625'
 }

````

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by misscoded** [comment]
Hi @surajreddykarra!

> After sending the block message, how do I receive the payload if someone clicks on the block_action button.

To listen for a button click, you pass in the `action_id` of the button to the **`@app.action()`** listener. In the case you've provided, that `action_id` would be `res_approve` or `res_reject`. 

Also to note, if you didn't want to have two listeners for each button, you can use `re.Pattern` to handle both cases (`@app.action(re.compile("(res_approve|res_reject)"))`).

> However, it doesn't return me the complete payload like it shows in the Block Kit Builder. I need the full Action Preview for message context. [...] Is this how it is supposed to run or is there something I'm missing out?

To get the full payload that you're after, use the `body` argument instead of `payload`. [This table](https://github.com/slackapi/bolt-python#making-things-happen) has a nice breakdown as to the difference between the two. 

Let us know if the above resolves the issue! 🙂

**Comment by surajreddykarra** [comment]
> To get the full payload that you're after, use the body argument instead of payload.

### ^
### This is what I'm looking for. Thanks a lot.

I didn't know I can directly use body as a parameter.
