### ISSUE TITLE
Custom user selector

### ISSUE THREAD

**Issue by tomeszmh** [slackapi/bolt-python#361]
Hey!

I am currently using slack API's user_select component for user selection.

Is it possible to create a user selector with one ot two more additional options? All of the users of course should be an option, but i want to add some "roles". Roles are just static strings for my the slack app. I haven't found any built in solutions yet but I think it might  be a custom selector implementation. Should I implement the whole user list functionality handled by slack client? (I mean user pagination, filtering for keypress event  n  the text area and so on?)

Reproducible in:
pip freeze | grep slack
python --version
sw_vers && uname -v # or ver
The slack_bolt version
slack-bolt==1.5.0
slack-sdk==3.5.0

Python runtime version
3.8.5
(Paste the output of python --version)

OS info
Darwin Kernel Version 20.4.0:

(Tell what actually happened with logs, screenshots)

Requirements
Please read the Contributing guidelines and Code of Conduct before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by misscoded** [comment]
Hi @tomeszmh! Yes, it's definitely possible and you're correct: to accomplish this, you'll have to implement your own custom selector. 🙂 

Using an `external_select` element, when the user clicks on the select, you can populate the options as you see fit. To make things quicker and more efficient, you might consider grabbing the entire list of users and storing those beforehand. No need to implement the keypress and text area that displays the character the user is searching the list on: you get those out of the box!

[Here is an example](https://github.com/slackapi/bolt-python/blob/3622b6810fd87a1c69483cfef3c3de2cbb07e084/examples/socket_mode.py#L101) of `external_select` that might be useful. Let us know if this helps!
