### ISSUE TITLE
Running Bolt for Python apps on IBM Cloud Functions (FaaS)

### ISSUE THREAD

**Issue by ac427** [slackapi/bolt-python#362]
I am trying to use IBM cloud faas. I tried some steps, but failed :( . Any help with an example will be appreciated. 

IBM cloud faas documentation https://cloud.ibm.com/docs/openwhisk?topic=openwhisk-prep#prep_python_local_virtenv

**Comment by seratch** [comment]
Hi @ac427, thanks for asking this question!

Although we don't have the bandwidth to add built-in support IBM Cloud Functions in the short term, you can write your own adapter! Making a custom adapter is quite simple. You should be able to do it with small efforts. Refer to the following documents and AWS Lambda examples:

* https://slack.dev/bolt-python/concepts#custom-adapters
* https://github.com/slackapi/bolt-python/blob/v1.6.0/slack_bolt/adapter/aws_lambda/handler.py

I'm not an expert of the IBM Cloud, but according to the documents, you can extract request headers and raw request body by accessing these context properties.

* https://cloud.ibm.com/docs/openwhisk?topic=openwhisk-actions_web#actions_web_context

For building a valid response, you can have these properties in the JSON data your function returns to the IBM runtime.

* https://cloud.ibm.com/docs/openwhisk?topic=openwhisk-actions_web#web_action_properties

I hope this was helpful to you. As I mentioned above, we are not planning to add the adapter in this project for now. Thus, if you don't have anything further to ask here, would you mind closing this issue?

**Comment by seratch** [comment]
👋 @ac427, let us know if you have something further to ask/discuss. If everything is clear, would you mind closing this issue?
