### ISSUE TITLE
App is missing argument for enabling token revocation handlers

### ISSUE THREAD

**Issue by fwump38** [slackapi/bolt-python#365]
### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version

slack-bolt==1.6.0
slack-sdk==3.5.1

#### Python runtime version

Python 3.9.0

#### OS info

ProductName:    macOS
ProductVersion: 11.4
BuildVersion:   20F71
Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1. Setup an app with an installation store
2. Add the `token_revocation__handlers_enabled=True keyword argument

I'm using the setup described in the v1.5.0 release notes (with an installation store too):

```
app = App(
    token_revocation_handlers_enabled=True
)  # installation_store required

```

### Expected result:

This enables the automatic handling of token revocation and app uninstall

This works as a workaround: 

`app.enable_token_revocation_listeners()`

### Actual result:

During initialization, App complains that this is not a valid keyword argument

```
File "/app/slackapp/slack.py", line 40, in <module>
    app = App(
TypeError: __init__() got an unexpected keyword argument 'token_revocation_handlers_enabled'
```

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @fwump38, thanks for pointing this out! I was a document bug in the release notes 🤦 I just fixed [it](https://github.com/slackapi/bolt-python/releases/tag/v1.5.0). As you mentioned, calling `app.enable_token_revocation_listeners()` is the right way to enable the feature.
