### ISSUE TITLE
dynamically configure App object or use a router

### ISSUE THREAD

**Issue by finete** [slackapi/bolt-python#367]
How can I configure an `App` inside a function? 
In my local dev environment I am loading a `yaml` file for the `token` kwarg, however in prod I am getting env variables.

In other frameworks I would user a `Router` object for the decorators and then attach it to the `App`.

Is there a similar method ?

**Comment by seratch** [comment]
HI @finete, thanks for asking the question!

As a simple solution, my comment at https://github.com/slackapi/bolt-python/issues/245#issuecomment-783836164 may be helpful.  In the example, I didn't use decorator methods in `register_listeners` method. But, if you have the listener function as an inner method inside the `register_listeners` method, you can use decorator too.

Also, we had a discussion about a kind of plugin systems on the `App` side at https://github.com/slackapi/bolt-python/issues/320 . The idea mentioned in the issue may be something you may prefer. However, as I responded in the issue, we haven't decided any plans for something like that yet.

I hope this was helpful to you.

**Comment by seratch** [comment]
Hi @finete, let us know if you have something further to ask/discuss. If everything is clear, would you mind closing this issue?
