### ISSUE TITLE
AsyncAdapter for Django

### ISSUE THREAD

**Issue by GabDug** [slackapi/bolt-python#368]
Django now supports [async views](https://docs.djangoproject.com/en/3.2/topics/async/). However, the Slack Bolt SDK for Python only has a synchronous adapter for Django. 

I'm unsure creating an AsyncHandler would be possible, but it definitively would be a nice thing.

### Category (place an `x` in each of the `[ ]`)

* [ ] **slack_bolt.App** and/or its core components
* [X] **slack_bolt.async_app.AsyncApp** and/or its core components
* [X] Adapters in **slack_bolt.adapter**
* [ ] Others

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @GabDug, thanks for taking the time to write in! 

The short answer is that we are not planning to add async support in the short term.

The biggest reason is the lack of the ORM support. As mentioned in [the document](https://docs.djangoproject.com/en/3.2/topics/async/),

>We’re still working on async support for the ORM and other parts of Django. You can expect to see this in future releases. For now, you can use the sync_to_async() adapter to interact with the sync parts of Django. There is also a whole range of async-native Python libraries that you can integrate with.

async apps have to carefully use the `sync_to_async` adapter for all the database access and whatever incompatible with async apps. As this project dealt with at https://github.com/slackapi/bolt-python/issues/280, Django ORM heavily relies on threads and thread-local variables. I don't know the internals of the Django framework at all but I'm guessing that implementing a completely safe async support for the ORM may take long.

Gong back to the Bolt adapter implementation, perhaps, it would be relatively easy to provide something for non-OAuth apps like [this](https://github.com/slackapi/bolt-python/blob/v1.6.1/examples/django/simple_app/urls.py). Just writing simple converters of request/response should work. However, I am not sure how many developers are actually using async mode Django without smooth ORM integration.

As I mentioned at the beginning, we won't have out-of-the-box async Django adapter until the stable ORM support is release. If we receive this request from many developers (say, 10+ reactions or comments here), we may revisit the plan. What do you think?

**Comment by seratch** [comment]
Hi @GabDug, do you have any comments on my above response? For the reason I mentioned in the previous comment, we are not planning to add async Django support in the short term. Let me close this issue after waiting for your response for a while.

**Comment by seratch** [comment]
Let me close this issue now. If Django project provides the out-of-the-box asyncio support of its ORM, we may want to revisit this.
