### ISSUE TITLE
The `next` in middleware args overwrites Python built-in one

### ISSUE THREAD

**Issue by leblancfg** [slackapi/bolt-python#370]
### `slack_bolt` version

Current [`HEAD`](https://github.com/slackapi/bolt-python/blob/66aad210faeed75c04941dfb635a4556952a8868/slack_bolt/middleware/middleware.py).

### Description
The keyword `next` used in `slack_bolt.middleware.middleware.process()` overwrites the [Python builtin `next()`](https://docs.python.org/3/library/functions.html#next), used to produce the next item in iterables and generators. We are currently trying to pass a generator to a custom middleware, having us resorting in using a hack to use the generator as middleware.

Please consider using another variable name, or `next_`.

Cheers, and thank you for your great work! ❤️

C.C. @nikodraca

**Comment by leblancfg** [comment]
Update: I see [the same variable name is also used in a few other places in the codebase](https://github.com/slackapi/bolt-python/search?l=Python&q=%22def+next%22).

**Comment by seratch** [comment]
Hi @leblancfg, thanks for taking the time to report this!

Indeed, this is possibly an issue when you use the built-in `next` in a listener function. As removing the `next` is a breaking change, we'll add an alias `next_` for it. The change will be included in the next minor version.

**Comment by mwbrooks** [comment]
Really great suggestion @leblancfg, thanks for creating an issue for this! ❤️

**Comment by leblancfg** [comment]
Thank you for this quick response @seratch! Much appreciated.
