### ISSUE TITLE
Add ability to add patterns for app_mentions

### ISSUE THREAD

**Issue by azizmb** [slackapi/bolt-python#371]
Currently, I can only subscribe to a generic app mention event using `@app.event("app_mention")`, but if I'm building an app that has multiple actions, the function can become unmaintainable. Instead, using a similar interface as `app.message` would make this much more usable in my opinion.

Examples:

```python

@app.mention("hello")
def say_hello(say):
    say("Hey there")!

@app.mention("status of [0-9]+")
def handle_status(...)
    ...
```

### Category (place an `x` in each of the `[ ]`)

* [x] **slack_bolt.App** and/or its core components
* [ ] **slack_bolt.async_app.AsyncApp** and/or its core components
* [ ] Adapters in **slack_bolt.adapter**
* [ ] Others

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by mwbrooks** [comment]
Cool idea and thanks for the example that starts to inch toward real-world requirements!

If we added support for this functionality, it would likely be a Bolt concept that would be implemented by Python, Java, and JavaScript. So we'll need to discuss it more.

At the moment, without built-in support, would you implement this by subscribing to `@app.event("app_mention")` and then using [a series of regex matchers](https://github.com/slackapi/bolt-python/blob/99ed6a6c1bb09c8f186b916eaf54e963073a112c/slack_bolt/listener/listener.py#L17-L28)?

**Comment by mwbrooks** [comment]
**Following up after talking with the other maintainers:**

Normally, our current recommendation is to use [the listener middleware](https://slack.dev/bolt-python/concepts#listener-middleware) to check the message text. I think this approach would give you what you need without Bolt adding a new built-in handler. In this case, you could listen for the `app_mention` event and then inspect the text using your regexp. 

If it works for you, I'd love to see a small code sample! It would be helpful to others as well 🙇🏻

**Comment by azizmb** [comment]
Yes, that's what I'm doing at the moment, but, I do find that it's a little inconsistent, given that `message` is a type of event, and is a "first class citizens" ie, has its own interface, but, `mentions` which is also a type of (similar) event, doesn't.

I don't think the middleware approach would work, here's what I think it would look like,

```python

def only_hello(message, next):
    text = message.get('text')
    if text == 'hello': 
        next() 

def only_status(message, next):
    text = message.get('text')
    if re.search("status of [0-9]+"):
        next() 

​@​app.event(​"app_mentions"​, middleware=[only_hello])​
​def​ ​say_hello​(​say​):
    ​say​(​"Hey there"​)!

​@​​app.event(​"app_mentions"​, middleware=[only_status])​
​def​ ​handle_status​(...)
    ...
```

I don't think is particularly elegant and is more boilerplate than code.

**Comment by mwbrooks** [comment]
@azizmb Thanks for the response and code sample! I had a chat with @seratch. There is actually a simpler version of listener middleware called `matchers` that we haven't had a chance to document. We'll be adding the documentation in https://github.com/slackapi/bolt-python/issues/372

Using the method approach (code sample courtesy of @seratch):

```python
def is_hello(message) -> bool:
    return message.get('text') == "hello"

@app.event("app_mention", matchers=[is_hello])
def handle_app_mention_events(event, say):
    say("Hey there!")
```

I know it's not as elegant as a built-in `@app.mention` method, but it works today out-of-the-box!

Using Lambda, it would look like:
```python
@app.event(
   "app_mention",
   matchers=[lambda message: message.get('text') == "hello"]
)

def handle_app_mention_events(event, say):
    say("Hey there!")
```

**Comment by mwbrooks** [comment]
Good to hear @azizmb! We'll definitely take your mention API suggestion into consideration. However, it would become a Bolt concept and need to be consistently implemented across all three frameworks (JS, Python, and Java). So, it'll naturally take longer for that go through.

**Comment by azizmb** [comment]
Hey @mwbrooks! Tried this out today, but, receiving `message` as `None` in the matcher function.

Any ideas?

**Comment by seratch** [comment]
@azizmb The `message` argument is available only for `app.message` listener: https://slack.dev/bolt-python/api-docs/slack_bolt/kwargs_injection/args.html#slack_bolt.kwargs_injection.args.Args.message You can use either `event` or `payload` for `app.event` listeners.

**Comment by davidolrik** [comment]
I just tried this in a async app, and when trying to inline the matcher with a lambda I get the following error:

```
TypeError: object bool can't be used in 'await' expression
```

Which means I must create a seperate matcher function for each command.

**Comment by seratch** [comment]
@davidolrik You are right that lambda syntax is not available for async functions (it's Python's limitation). But you still can pass an async method as one of listener matchers in AsyncApp. Checking the example like `is_eyes` in this comment: https://github.com/slackapi/bolt-python/issues/284#issuecomment-815471920 may be helpful for you!

**Comment by davidolrik** [comment]
Yeah, that is what I'm doing - It's just a lot of boilerplate.

Having a `keywords` for `app_mention` events would eliminate all that boilerplate.
