### ISSUE TITLE
client.chat_postMessage is not working in my django application

### ISSUE THREAD

**Issue by ManuelBuri** [slackapi/bolt-python#373]

**Comment by seratch** [comment]
Hi @ManuelBuri, this question sounds like something specific to your app. The example app in this repo does not have `SlackAccountMatching` model. The lack of message delivery is not the cause of the issue but the result.

One thing I can suggest is that checking how your queries and their results are different in the Django REPL may be helpful. As you may know, you can start the REPL by hitting `python manage.py shell`. Running the query like this should be far easier than verifying all the lines of code in your app.

```python
>>> from yourapp.models import SlackAccountMatching
>>> SlackAccountMatching.objects.values('slack_team_id').distinct()
```

For general questions about Python apps, I'd recommend joining [`#lang-python`](https://community.slack.com/archives/CHL4CLRCZ) channel in our [Slack Developer Community workspace](https://join.slack.com/t/community/shared_invite/enQtNzYxNzM5NzU0Mzg3LWFhZjE3ZjY1M2JhM2MzNGNmMmE0Zjc4Y2E5NDc2NGJiODAxNDMzN2Y1MjVlYWU3ZGVlYzhlMDVhNzA0Nzg1OGY). More Python developers can help you out threre. We'd greatly appreciate it if you could understand the limited capacity of the SDK maintainer team.

**Comment by ManuelBuri** [comment]
@seratch thanks for getting back to me. I am getting everything right, all variables all queries.
Could it be something with RateLimiting?
