### ISSUE TITLE
Failing Event API Challenge in Py, Passes in JS

### ISSUE THREAD

**Issue by khalidsharmarke** [slackapi/bolt-python#376]
(Filling out the following details about bugs will help us solve your issue sooner.)

### Reproducible in:
python 3.9.5

#### The `slack_bolt` version
slack-bolt==1.6.1
slack-sdk==3.6.0

#### Python runtime version
python 3.9.5

#### OS info
Microsoft Windows [Version 10.0.19041.985]

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

![image](https://user-images.githubusercontent.com/59586491/121471647-0b79c200-c98e-11eb-86e5-dd3766e037e1.png)
run app.py with code above
open port using ngrok
post ngrok url + slack/events to Events API verification

### Expected result:
running the same tokens in the JS version of Bolt passes with 
200 OK - {challenge: xxx}
so the Python version should also pass

### Actual result:
401 - Unauthorized
{
    "error": "invalid request"
}
## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @khalidsharmarke, thanks for asking the question!

Can you make sure if you've set the valid signing secret for the app? In other words, make sure if the env variable `SLACK_SIGNING_SECRET` is the correct one for the app.

**Comment by khalidsharmarke** [comment]
I confirmed it and it is correct.

**Comment by seratch** [comment]
@khalidsharmarke Thanks for your reply. However, still the only suggestion I can provide is the possibility of invalid signing secret. To narrow down the issue, how about temporarily changing your code to have the signing secret value in code and seeing how it goes? If the modified one works, the issue should be related to the part loading .env / env variables.

**Comment by khalidsharmarke** [comment]
the env variables are loading correctly, this is an issue with the library

**Comment by khalidsharmarke** [comment]
also, hard coding the api tokens doesnt change the outcome

**Comment by seratch** [comment]
Just in case, I've verified the url verification behavior with the same version (1.6.1) but I didn't observe any issues. Also, we haven't received any similar bug reports.

> hard coding the api tokens doesnt change the outcome

I do understand your frustration with the behavior, but please make sure if you've hard-coded the app's signing secret as well. The `token` argument in the `App` constructor is not related to the url verification error. Only the `signing_secret` argument is used for verifying requests. As long as the expected signing secret is set, the verification should pass. 

If hard-coding the signing secret still does not help, compare the value with the one at **Settings** > **Basic Information** > **Signing Secret** in your Slack app configuration page (https://api.slack.com/apps) again.

I hope this was helpful to you.

**Comment by seratch** [comment]
The bolt-python maintainers do not have anything further for helping you out here. For this reason, let us close this issue now bu t please feel free to write in whenever you need more help!

**Comment by pinghedm** [comment]
I have the same issue - I am certain my signing token is correct, but I can only get the same 401 `{'error': 'invalid request'}` trying to add a request url for event subscription

Has there been any new developments since this was closed?
