### ISSUE TITLE
How is Respond() supposed to be accessed?

### ISSUE THREAD

**Issue by JasonDykstraSelectStar** [slackapi/bolt-python#382]
I want to use the `respond()` function to replace the body of a previous message sent by my slack app, but `respond()` is not recognized. `say()` and `ack()` work fine since I'm doing `from slack_bolt import app`. Should I be using a different import to access `respond()`? I tried doing `from slack_bolt.kwargs_injection.args import Args` then typing `Args.respond("test")` but again `respond()` was not recognized. Thanks in advance for any help!

### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version

slack-bolt==1.6.1
slack-sdk==3.7.0
slackclient==2.9.3
slackeventsapi==2.2.1

#### Python runtime version

Python 3.8.2

#### OS info

ProductName:	macOS
ProductVersion:	11.4
BuildVersion:	20F71
Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1. Create new python script
2. `from slack_bolt import App`
3. see that `app()` is recognized, `respond()` is not

### Expected result:

`respond()` should be recognized :(

### Actual result:

ide tells me `respond()` is not recognized

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @JasonDykstraSelectStar, thanks for asking the question!

Can you visit [this document page](https://slack.dev/bolt-python/concepts#action-respond) and click "Using respond()" there? 

<img width="600" src="https://user-images.githubusercontent.com/19658/122493622-f999be00-d022-11eb-89ec-a090ba4705ca.png">

The `respond()` is a utility for easily use `response_url` in Slack payloads. Refer to https://api.slack.com/interactivity/handling#message_responses for more details.

**Comment by JasonDykstraSelectStar** [comment]
The docs are actually what brought me here to ask the question 😅 I saw the example where they simply use `respond(f"you...` but whenever I try to use respond it is unrecognized. I understand how it is _supposed_ to work, but can't seem to actually get it working. Are there any extra `import` statements I would need to include?

**Comment by seratch** [comment]
@JasonDykstraSelectStar I'm glad to hear that you've figured it out!
