### ISSUE TITLE
Open a short cut modal from a button

### ISSUE THREAD

**Issue by finete** [slackapi/bolt-python#383]
I am trying to have a shortcut modal screen open from a button, couldn't find how to .

I have the following shortcut modal

```python
@app.shortcut("initial_screen")
async def open_modal(ack, body, client):
    # Acknowledge the command request
    await ack()
    # Call views_open with the built-in client
    await client.views_open(
        trigger_id=body["trigger_id"],
        # View payload
        view={
            "type": "modal",
            # View identifier
            "callback_id": "view_1",
            "title": {"type": "plain_text", "text": "initial_screen"},
            "blocks": [
                {
                    "type": "section",
                    "text": {"type": "mrkdwn", "text": f"hi there"},
                    "accessory": {
                        "type": "button",
                        "text": {"type": "plain_text", "text": "Click me"},
                        "action_id": "next_screen"
                    }
                }
            ]
        }
    )
```

how would I open it with a button (on the home screen or in message)?
I have tried this but it didnt work:
```python
@app.message("help")
async def message_hello(message, say):
    await say(
        blocks=[
            {
                "type": "section",
                "text": {"type": "mrkdwn",
                         "text": f"open the initial screen"},
                "accessory": {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "Click Me"},
                    "action_id": "initial_screen"
                }
            }
        ],
    )
```

It opens fine from the shortcut BTW.

**Comment by misscoded** [comment]
Hi @finete! To listen for actions with interactive elements (like button clicks), you use the `@app.action` listener, passing into it the `action_id` of the button:

```
# Listen for an interaction with an element that has 'initial_screen' as the action_id
@app.action("initial_screen")
def open_modal(ack, body, client):
    ack()
    # ... Code here to open the modal
```

If you'd like to see another example, as well as how to specify more constraints, you can find the documentation on listening for actions [here](https://slack.dev/bolt-python/concepts#action-listening).

Also, if it's the case that you're interested in opening up the _exact_ same modal with both the shortcut and the button click, you can always stack the listeners to keep things tidy:

```
@app.action("initial_screen")
@app.shortcut("initial_screen")
def open_modal(ack, body, client):
    ack()
    # ... Code here to open the modal
```

Hope that helps! Let us know if that resolves the issue 🙂

**Comment by seratch** [comment]
As Alissa answered, you can have a `@app.action` listener to handle block_actions requests from a button in the UI. Let us close this issue now but please feel free to write in if you have anything further to ask here.

**Comment by joacorma** [comment]
Is there any way to get the trigger_id from the action payload? 
I'm not being able to do so! At least not using the bolt library.

Maybe there's other way to get that id. Any idea?
