### ISSUE TITLE
How to Update Permissions/Scope without Installing App again

### ISSUE THREAD

**Issue by ManuelBuri** [slackapi/bolt-python#385]
Hi team, I am wondering how I could update my existing OAuth scopes with this [method](https://api.slack.com/methods/apps.permissions.request) `app.client.
apps_permissions_request`? I tried to run it with this code
 ````
@app.action("update_permission")
def update_message(ack, client, body):
    ack()
    client.apps_permissions_request(token=os.environ.get('SLACK_BOT_TOKEN_DEV'), trigger_id=body["trigger_id"], scopes='mpim:read')
````
however, I get the following response:
`Failed to run listener function (error: 'WebClient' object has no attribute 'apps_permissions_request')`

How can I fix/workaround this?

Thanks for your help/input :)

**Comment by seratch** [comment]
Hi @ManuelBuri, the method you found is for deprecated workspace apps. It’s no longer usable. Also, I'm sorry to say this but there is no way to update an app's scopes etc at the moment. Doing the installation in browser is the only way to add new scopes to your app.
