### ISSUE TITLE
Listener for button in attachements not working

### ISSUE THREAD

**Issue by catherineyu2** [slackapi/bolt-python#388]
The listener I've written for an interactive button doesn't do anything when it's clicked in Slack. I'm developing with Bolt and using socket mode.

#### The `slack_bolt` version

slack-bolt==1.6.1
slack-sdk==3.7.0
slackclient==2.9.3

#### Python runtime version

Python 3.9.5

#### Steps to reproduce:

<img width="776" alt="Screen Shot 2021-07-01 at 3 03 25 PM" src="https://user-images.githubusercontent.com/86801333/124177000-a7728700-da7d-11eb-8f49-001a929135e1.png">

### Expected result:

Message sent back to user saying "You have successfully been opted out from receiving future messages."

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by misscoded** [comment]
Hi @catherineyu2! Thanks for bringing this question to us and love to hear that you're making use of Bolt and Socket Mode to develop! 🙂 

Unfortunately, using actions in `attachments` is not compatible with Socket Mode. The attachments-style approach is an outdated/deprecated way of introducing interactivity for users. 

Luckily, migrating the above to make use of the recommended approach (via `blocks`) is fairly straightforward! I've gone ahead and refactored the code you've provided to use `blocks` instead, which I'm providing below:

```
@app.message("opt out")
def confirm_opt_out(say):
    blocks = [
        {
            "type": "actions",
            "elements": [
                {
                    "type": "button",
                    "style": "primary",
                    "text": {
                        "type": "plain_text",
                        "emoji": True,
                        "text": "Opt-out of messages"
                    },
                    "confirm": {
                        "title": {
                            "type": "plain_text",
                            "text": "Are you sure?"
                        },
                        "text": {
                            "type": "mrkdwn",
                            "text": "Are you sure you'd like to opt out?"
                        },
                        "confirm": {
                            "type": "plain_text",
                            "text": "Yes"
                        },
                        "deny": {
                            "type": "plain_text",
                            "text": "No"
                        }
                    },
                    "style": "primary",
                    "value": "click_me_123",
                    "action_id": "confirm_opt_out"
                }
            ]
        }
    ]
    say(text="Opt-out of messages", blocks=blocks)


@app.action("confirm_opt_out")
def process_opt_out(ack):
    ack()
    print("Successfully opted out!")
``` 

In the above case, your `app.action()` listener will only receive an event if the user has selected confirm.

If you're curious or want to read more, you can check out the [documentation about Block Kit elements](https://api.slack.com/reference/block-kit/block-elements), as well as the [confirmation dialog documentation](https://api.slack.com/reference/block-kit/composition-objects#confirm).

Anyway, hope that's helpful! Let us know if the above solves the issue and if you have any further questions!

**Comment by catherineyu2** [comment]
Thank you so much for your help @misscoded!

I had a question about the usage of `app.message("opt out")`. The user would have to reply with "opt out" to initiate the button but is there a way to have a button attached to the previous message or sent as a new message using blocks? I'd like for the user to have the option to click the button without having to type/reply with anything.
