### ISSUE TITLE
[Local Development] Watch and restart service on changes.

### ISSUE THREAD

**Issue by Olshansk** [slackapi/bolt-python#390]
Is there a recommended approach or configuration to automatically restarting the bolt server when any changes take place in the python API?

[Watchdog](https://pypi.org/project/watchdog/) is a great candidate for this, but I couldn't find any previous threads about it. Wanted to check before I either roll my own or submit a PR.

**Comment by seratch** [comment]
Hi @Olshansk, thanks for asking this question! 

Using the `watchmedo` command should work if your command properly terminates the currently running process before starting a new one. This means that simply having `--command='python app.py'` does not work. The `command` argument can be a bit more complex.

If you use any of the following frameworks along with Bolt, their (or their app server's) app reloading feature is a good way to go.

* [AIOHTTP](https://github.com/slackapi/bolt-python/tree/v1.6.1/examples/aiohttp_devtools): `adev runserver --port 3000 --app-factory app_factory async_app.py`
* [Django](https://github.com/slackapi/bolt-python/tree/v1.6.1/examples/django): `python manage.py runserver 0.0.0.0:3000`
* [Falcon](https://github.com/slackapi/bolt-python/blob/v1.6.1/examples/falcon/app.py): `gunicorn app:api --reload -b 0.0.0.0:3000`
* [FastAPI](https://github.com/slackapi/bolt-python/blob/v1.6.1/examples/fastapi/app.py) : `uvicorn app:api --reload --port 3000`
* [Flask](https://github.com/slackapi/bolt-python/blob/v1.6.1/examples/flask/app.py): `FLASK_APP=app.py FLASK_ENV=development flask run -p 3000 `
* [Sanic](https://github.com/slackapi/bolt-python/blob/v1.6.1/examples/sanic/async_app.py): `uvicorn async_app:api --reload --port 3000`

As of today, we don't have any recommendation for simple Socket Mode apps. If someone knows a great solution for it, we would like to know it too.

**Comment by Olshansk** [comment]
Thanks for the response @seratch! I actually ended up switching to FastAPI regardless and noticed that I got the reloading feature for free :)
