### ISSUE TITLE
Using Checkboxes to get Input and respond depending on the selection

### ISSUE THREAD

**Issue by alecrevangelista** [slackapi/bolt-python#392]
I have the a message block with a checkbox set to display in the chat when a key-word is detected. I want the user to be able to select options and then my bot to respond accordingly, depending on the option selected (i.e: Sensitive Data, Malware, Vulnerability Severity etc ... ).
### Reproducible in:
```
slack-bolt==1.6.1
slack-sdk==3.6.0
```
#### Python runtime version
Python 3.7.2
#### OS info
Microsoft Windows [Version 10.0.17763.1999]
#### Steps to reproduce:
(Share the commands to run, source code, and project settings (e.g., setup.py))
```
{
	"blocks": [
		{
			"type": "section",
			"text": {
				"type": "mrkdwn",
				"text": "I noticed you mentioned a failed scan ... Please select which control is failing the Scan:\n\n"
			}
		},
		{
			"type": "input",
			"element": {
				"type": "checkboxes",
				"options": [
					{
						"text": {
							"type": "plain_text",
							"text": "Vulnerability Severity",
							"emoji": true
						},
						"value": "value-0"
					},
					{
						"text": {
							"type": "plain_text",
							"text": "Sensitive Data",
							"emoji": true
						},
						"value": "value-1"
					},
					{
						"text": {
							"type": "plain_text",
							"text": "Malware",
							"emoji": true
						},
						"value": "value-2"
					}
				]
			},
			"label": {
				"type": "plain_text",
				"text": "Please select all relevant options:",
				"emoji": true
			}
		}
	]
}
```

### Expected result:
I am looking for a way to get the bot to display specific messages, depending on the checkbox option selected in the message above.

What are my options in trying to achieve this? Any help would be much appreciated!

### Actual result:
(Tell what actually happened with logs, screenshots)

## Requirements
Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by mwbrooks** [comment]
Hi @alecrevangelista,

Thanks for the code sample! It helps a lot.

I think you're on the right track. To respond to a checkbox selection, you'll need to [add an `action_id`](https://api.slack.com/reference/block-kit/block-elements#checkboxes). For example,

```
{
	"type": "input",
	"element": {
		"type": "checkboxes",
		"action_id": "security_action_id",
		"options": [ ... ],
		...
}
```

After declaring an `action_id` you can [listen and respond to the action using Bolt](https://slack.dev/bolt-python/concepts#action-respond):

```python
@app.action("security_action_id")
def security_action(ack, say):
    # Acknowledge action request
    ack()
    say("Security report received 👍")
```

Hope that helps and please let me know how it goes!
Michael

**Comment by alecrevangelista** [comment]
Hi @mwbrooks ,

Thank you for the response! So far, I have got it to a point where I have my checkbox and three options, with an ```action_id``` = ```action1``` just as you have described above:

```
{
	"type": "input",
	"element": {
		"type": "checkboxes",
		"action_id": "action1",
		"options": [ ... ],
		...
}
```

I want the app to have a distinct response for each of the three checkbox responses -- So I have my listener is defined as follows:
```
@app.block_action("action1")
async def handle_options(ack, respond, body, say, logger):
    await ack()
    for i in body["actions"][0]["selected_options"]:
        if i["text"]["text"] == "Vulnerability Severity":
            await say(text="Message 1!!")
        elif i["text"]["text"] == "Malware":
            await say(text="Message 2!!")
        elif i["text"]["text"] == "Sensitive Data":
            await say(text="Message 3!!")
```

The problem in my code here is that every time a checkbox item is selected, the message will repeat for the options that are already selected. I am wondering if there is a better way for me to handle each option selection here?

Also, using the ```say()``` here is displaying a new message, but ideally, I want it to reply as a thread to the original message with the checkbox. or only visible to the person selecting the options --  Is that possible?

**Comment by mwbrooks** [comment]
Hey @alecrevangelista,

It's good to hear that you've making some progress!

> The problem in my code here is that every time a checkbox item is selected, the message will repeat for the options that are already selected. I am wondering if there is a better way for me to handle each option selection here?

Checkboxes used directly inside messages could make this more difficult. While the API allows you to do this, it wasn't necessarily designed around this use-case. Normally, checkboxes would be found in views (app home screen or modals).

It's also challenging to store metadata and state inside a Slack message. The closest way to store state is the [`private_metadata`](https://api.slack.com/reference/surfaces/views) value available to views. Normally, we'd recommend that you try to persist data in your own database and use something like the message timestamp as a unique identifier.

A more traditional approach would be to display a message with an "Edit" button. Pressing the button would open a modal with the checkboxes selected based on your database. When the modal is submitted, the database can be updated and - if you want - the original Slack message could also be updated.

> Also, using the say() here is displaying a new message, but ideally, I want it to reply as a thread to the original message with the checkbox. or only visible to the person selecting the options -- Is that possible?

One of the easiest ways it to use the `chat.postMessage` method available with `client`:

```python
@app.action("action1")
def approve_request(ack, body, say, client):
    ack()
    client.chat_postMessage(channel=body["channel"]["id"], thread_ts=body["message"]["ts"], text="Request approved 👍")
```

**Comment by alecrevangelista** [comment]
Hi @mwbrooks,

Thanks for the info!

I have decided to take a different approach with this. So I am now using a "multi_static_select" object instead of the "checkbox ", which prompts the user to select some options as follows:

```
{
	"blocks": [
		{
			"type": "section",
			"block_id": "section678",
			"text": {
				"type": "mrkdwn",
				"text": "Pick items from the list"
			},
			"accessory": {
				"action_id": "action1",
				"type": "multi_static_select",
				"placeholder": {
					"type": "plain_text",
					"text": "Select items"
				},
				"options": [
					{
						"text": {
							"type": "plain_text",
							"text": "OPTION 1"
						},
						"value": "value-0"
					},
					{
						"text": {
							"type": "plain_text",
							"text": "OPTION 2"
						},
						"value": "value-1"
					},
					{
						"text": {
							"type": "plain_text",
							"text": "OPTION 3"
						},
						"value": "value-2"
					}
				]
			}
		}
	]
}
```
 
I have defined my listener as follows -- This will look at the selections made in the object above, and will output a specific message when the "Confirm" button is clicked (i.e ```"action_id": "action1"```). I want this message to be sent as a "thread" and have used ```chat.postMessage``` as you have suggested above. 

```python
@app.block_action("action1")
async def func(ack, respond, body, say, logger, client):

    logger.info(body["actions"][0]["selected_options"])

 
    for i in body["actions"][0]["selected_options"]:
   
        await client.chat_postMessage(channel=body["channel"]["id"], thread_ts=body["message"]["ts"], text="You have selected{}\n".format(i["text"]["text"]))
```

However, when I do this, the app sends an entirely new message, and does not reply to the original thread where the prompt was asked in the first place. Is there something I am doing wrong here? 

Thanks!

**Comment by seratch** [comment]
@alecrevangelista 
>However, when I do this, the app sends an entirely new message, and does not reply to the original thread where the prompt was asked in the first place. Is there something I am doing wrong here?

The `body["message"]` can have `body["message"]["thread_ts"]` in addition to `body["message"]["ts"]`. In this case, your app needs to set the `thread_ts`, not the `ts` of the message.
