### ISSUE TITLE
"message" event does for private channels where bot is participating

### ISSUE THREAD

**Issue by DataGreed** [slackapi/bolt-python#393]
#### The `slack_bolt` version

slack-bolt==1.6.0
slack-sdk==3.5.1

#### Python runtime version

Python 3.8.2

#### OS info

macOS 10.15.7

#### Steps to reproduce:

My app has the following bot scopes:
```
commands
chat:write
chat:write
chat:write.customize
channels:history
channels:read
users.profile:read
channels:join
groups:history
im:history
mpim:history
team:read
```

and following user scopes:

```
chat:write
```

I have the following listener set up:

```
@app.event("message")
def message_posted(client, event, logger):
    """
    Message was posted in a channel where bot is participating
    """
    print(event)
```

### Expected result:

I expect to receive `message_posted` to fire every time a message is posted to a channel where bot is participating

### Actual result:

`message_posted` is fired only for publich channels where bot is a member, it does not fire for private channels to which the bot was invited to

Please advise. Is there something wrong with permissions or am I doing something wrong?

**Comment by srajiang** [comment]
Hi @DataGreed 👋  It looks like you do have the [required scopes](https://api.slack.com/events/message.groups) to be receiving message events posted in private channels (that your bot belongs to!). Let me take a look at this and see whether I'm able to reproduce the behavior you're seeing!

**Comment by srajiang** [comment]
I wonder if you've added the right scopes but not subscribed your app to the `message.groups` bot event? You can do this by heading to your app configuration page then under **Event Subscriptions** > Subscribe to bot events > Search `message.groups` in the dropdown menu. 

<img width="916" alt="7-7-2021_event-subs" src="https://user-images.githubusercontent.com/55667998/124702627-00399800-df34-11eb-83df-ba25f4c09444.png">

**Comment by DataGreed** [comment]
@srajiang oh, I am officially an idiot. I did not realize there two different event you can subscribe for in "Event subscriptions" section on Slack App dashboard (since it's just one type of event in the SDK).

My app was not subscribed.

Thank you for the help, much appreciated!

**Comment by froman23** [comment]
Is there any other configuration that I should consider for this to work? I have a similar issue, in my case my scopes are
on the bot side 

     ```
    "bot": [ 
                "groups:history", 
            ]
```

And I'm subscribe to the event of `message.groups`. I can listen to events in private channel where the bot has been added but only in my own workspace, in other workspace I have doens't work
