### ISSUE TITLE
Set dynamic Request callback URL in the app settings

### ISSUE THREAD

**Issue by deepanshu11madan** [slackapi/bolt-python#397]
I have a slack app with interactions like a button and I understand that when the user clicks this button, Slack performs a callback to my "request URL" (set in the slack app Interactive settings) which invokes the lambda and it takes care of the slack events. Can I somehow specify this Request URL dynamically or is there a plan to allow to set more than 1 URL there? 

If not, what is the best practice to handle the case where the lambda to be invoked can be in a different AWS region or when we generally want to test it?  I can create two different slack apps with two different Request URLs but doesn't sound right thing to do.

**Comment by seratch** [comment]
Hi @deepanshu11madan , thanks for asking the question here!

> Can I somehow specify this Request URL dynamically or is there a plan to allow to set more than 1 URL there?

Both are not available and we don't have any future plans regarding the enhancement.

>If not, what is the best practice to handle the case where the lambda to be invoked can be in a different AWS region or when we generally want to test it?

I think the most straight-forward approach should be having a load balancer (ALB/ELB or something equivalent) in front of your lambda functions. We don't have a working example in this project but checking AWS's document can be helpful for you.
https://docs.aws.amazon.com/lambda/latest/dg/services-alb.html

I hope this was helpful to you.

**Comment by deepanshu11madan** [comment]
Thank you for the response. Load balancer could be another way, but, I was trying to avoid that solution, because for that, I would need to maintain a different database somewhere which will have some kind of mapping for Slack Team id and AWS region/env, in order to know what lambda to invoke based on the team ID value in the slack event. For instance, for our customers in the EU region, we would want to call the AWS lambda in the EU region.

**Comment by seratch** [comment]
@deepanshu11madan Thanks for sharing more details. However, I don't have any other ideas for it. To meet your app's requirements without a single Request URL, the only solution I can think of is, as you already mentioned, creating multiple Slack apps. Asking your end users to install the right AWS region app would be the easiest way to go.

I hope you will find a reasonable solution for your use case. If there is nothing further to discuss here, would you mind closing this issue?

**Comment by deepanshu11madan** [comment]
thank you for your help, will do!
