### ISSUE TITLE
Update Getting Started tutorial to use SocketMode as default

### ISSUE THREAD

**Issue by srajiang** [slackapi/bolt-python#398]
With [#990](https://github.com/slackapi/bolt-js/pull/990), we have updated Getting Started guide to use Socket Mode as default. Task would involve:
 
* Making corresponding updates to the Getting Started in Python guide.  
* Update the `examples/getting_started/app.py to use Socket Mode as well. 

### The page URLs

* https://slack.dev/bolt-python/tutorial/getting-started

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Fixed by https://github.com/slackapi/bolt-python/pull/405
