### ISSUE TITLE
Action buttons not working after using chat_update 

### ISSUE THREAD

**Issue by walidchikha** [slackapi/bolt-python#411]
When I use postMessage Bolt function and I insert action buttons, everything is working as expected.
However, when I first upload a file using files_upload function and then update it using chat_update to insert some blocks (title, action buttons). The blocks are displayed fine but when you click the buttons, nothing happens.

### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version

slack_bolt      ~= 1.2.3

#### Python runtime version

Python 3.8.10

#### OS info

#86-Ubuntu SMP 

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1. Uploading the file
```
upload_response = slack_client.files_upload(
        channels=message["channel_id"],
        initial_comment=uploadfiles["initial_comment"],
        file=uploadfiles["file"],
        filename=uploadfiles["filename"],
        filetype=uploadfiles["filetype"],
        title=uploadfiles["title"]
        )
```

2. Blocks
```
blocks = [
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": "*Hi !*" ,
                }
            },
            {
                "type": "divider"
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": "*Title*"
                }
            }
            ,{
                "type": "actions",
                "block_id": "actionblock",
                "elements": [
                    {
                        "type": "button",
                        "action_id" : "rerun_action",
                        "text": {
                            "type": "plain_text",
                            "text": "Rerun",
                            "emoji": True
                        },
                        "style": "primary",
                        "value": "rerun"
                    },
                    {
                        "type": "button",
                        "action_id" : "launch_wizard",
                        "text": {
                            "type": "plain_text",
                            "text": "Launch Wizard",
                            "emoji": True
                        },
                        "style": "primary",
                        "value": "launch"
                    }
                ]
            }
        ]
```

3. Update the file blocks
```
update_response = slack_client.chat_update(
       ts=ts,
       channel=upload_channel,
        text=uploadfiles["initial_comment"],
        blocks=message["blocks"]
        )
```

### Expected result:

I expect the buttons to work same way I use postMessage function (call my action callback)

### Actual result:

Nothing happens. Button doesn't show any indication that a request was sent.
In the app console, no request is received and no logs are printed

**Comment by walidchikha** [comment]
@seratch @misscoded @mwbrooks Any idea why this happens? Is it a bug or am I doing something wrong? Thanks

**Comment by stevengill** [comment]
hey @walidchikha,

Your example is a little confusing to me. First you use `slack_client.files_upload` to upload a file, and then you use `slack_client.chat_update` to update the file? Or update a different message? Could you provide more info?

**Comment by walidchikha** [comment]
Hi @stevengill,

So I was not able to post a message to Slack with Slack Blocks and a file attached to the message at the same time.
Since I wanted my blocks and file to be in the same message. So what I do is uploading a file using `slack_client.files_upload` (which doesn't support sending blocks with it) and then I update that message I just posted with the blocks I need using `slack_client.chat_update`.

As far as I know:
- `slack_client.postMessage` doesn't support sending a file.
- `slack_client. files_upload ` doesn't support sending blocks.

I hope this is a bit less confusing.

**Comment by seratch** [comment]
Hi @walidchikha, thanks for sharing more details and I'm sorry for our slow response here.

As you noticed, blocks are not available when your app uploads files. Indeed, this can make the message modification challenging in some situations.

One thing I would suggest is to unfurl file content later on instead of posting a message when uploading the file. The steps are:

* Call `files.upload` API and receive the file metadata including its permalink URLs
* Call `chat.postMessage` to post a new message that includes the file URL with unfurl options enabled
* Slack renders the blocks plus unfurled file content will be available as attachments

I know this may not be an ideal approach for your use case but I hope this was helpful to you.

**Comment by seratch** [comment]
As we provided answers and workarounds, let us close this issue now. But please feel free to write in if you have anything further to ask/discuss here.
