### ISSUE TITLE
Make "events" in the document even clearer

### ISSUE THREAD

**Issue by seratch** [slackapi/bolt-python#412]
Currently, we are using the term "event" for both Events API data and any incoming payload requests from Slack in the Bolt document. For example,

* There is the "Listening to events" section: https://slack.dev/bolt-python/concepts#event-listening which is referring to the Events API
* Then there is the "Acknowledging events" section: https://slack.dev/bolt-python/concepts#acknowledge which is referring to actions, shortcuts, commands, and options. Also, Bolt acknowledges the "events" for Events API under the hood.

This can be confusing for developers especially when they are not yet familiar with the Slack Platform yet.

To improve this, we can consistently use the term "request" for incoming requests from Slack. Specifically, 

* We can rename the section "Acknowledging events" to "Acknowledging requests"
* We can replace all the phrases like "acknowledging events" to "acknowledge requests" in all sections

### The page URLs

* https://slack.dev/bolt-python/concepts#acknowledge and others

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by RhnSharma** [comment]
I would like to take this one.

In the documentation, I couldn't find the exact phrase "acknowledge an event".

**Comment by seratch** [comment]
Indeed, there is no exact phase in the document. I meant we should replace all the phrases like that. Updated.

**Comment by RhnSharma** [comment]
Okay
