### ISSUE TITLE
Load testing an app - is there a way to disable or pass authorization

### ISSUE THREAD

**Issue by DataGreed** [slackapi/bolt-python#419]
I am trying to implement load-testing for my Django app that utilizes Bolt.

I want to stress test it using Locust framework - basically firing http requests to the server running the app to see the response times. The app does not really have to call any requests to Slack API for that – I am planning to patch `App.client` (not sure if it's possible, though) so it will just sleep a little imitating call to slack API.

I managed to sign requests properly, but the problem I am facing is that I cannot get past authorization middleware.

Whenever I use multi-workspace installation I always get `Please install this app into the workspace` response. I've also tried single-workspace setup, but I am getting a similar error.

I see the following in logs:
```
The stored bot token for enterprise_id: None team_id: T111 is no longer valid. (response: {'ok': False, 'error': 'invalid_auth'})
```
does Bolt try to communicate with Slack API to check the token?  

If so, is there a way to disable it temporarily for test purposes?

I've tried passing `request_verification_enabled=False` and `token_verification_enabled=False` when initializing App, but it didn't change anything.

Could you please advise?

**Comment by seratch** [comment]
Hi @DataGreed, thanks for asking the question!

Yes, the default authorize function that works along with your `InstallationStore` performs `auth.test` API call to verify the stored token's validity. We are not planning to add an option to turn off the `auth.test` API call in the built-in middleware at least in the short term mainly for the consistency with other Bolt frameworks. 

I know that this is not ideal for you but, if you would like to customize this behavior for the load testing, our recommendation is to have your own custom `authorize` function that returns [an `AuthorizeResult` data](https://github.com/slackapi/bolt-python/blob/v1.7.0/slack_bolt/authorization/authorize_result.py) for the purpose. You can pass your custom implementation for testing as `authorize` argument in the `App` constructor.

Refer to the following resources:

* https://slack.dev/bolt-python/concepts#authorization
* https://github.com/slackapi/bolt-python/blob/v1.7.0/slack_bolt/authorization/authorize.py#L254-L262

I hope this was helpful to you!

**Comment by DataGreed** [comment]
@seratch thanks! That seemed to help, although I am getting a strange behaviour with it.

When sending a test event that I took from one of the Bolt's tests, I get this in the output:

```
Skipped self event: {'type': 'message', 'text': 'Here is your file!',... {the whole event goes here}
```

The comment of the part of code in `middleware/ignoring_self_events.py` that logs it says the following: 
```
# Its an Events API event that isn't of type message,
# but the user ID might match our own app. Filter these out.
# However, some events still must be fired, because they can make sense.
```

Which confuses me even more, because the sent event *was* of type  `message`. Could you please explain what self-events are and why Bolt is skipping this event?

The whole event that I am trying to send just in case:

```
{
        "token": "verification-token",
        "team_id": "T111",
        "api_app_id": "A111",
        "event": {
            "type": "message",
            "text": "Here is your file!",
            "files": [
                {
                    "id": "F111",
                    "created": 1610493713,
                    "timestamp": 1610493713,
                    "name": "test.png",
                    "title": "test.png",
                    "mimetype": "image/png",
                    "filetype": "png",
                    "pretty_type": "PNG",
                    "user": "U111",
                    "editable": False,
                    "size": 42706,
                    "mode": "hosted",
                    "is_external": False,
                    "external_type": "",
                    "is_public": False,
                    "public_url_shared": False,
                    "display_as_bot": False,
                    "username": "",
                    "url_private": "https://files.slack.com/files-pri/T111-F111/test.png",
                    "url_private_download": "https://files.slack.com/files-pri/T111-F111/download/test.png",
                    "thumb_64": "https://files.slack.com/files-tmb/T111-F111-8d3f9a6d4b/test_64.png",
                    "thumb_80": "https://files.slack.com/files-tmb/T111-F111-8d3f9a6d4b/test_80.png",
                    "thumb_360": "https://files.slack.com/files-tmb/T111-F111-8d3f9a6d4b/test_360.png",
                    "thumb_360_w": 358,
                    "thumb_360_h": 360,
                    "thumb_480": "https://files.slack.com/files-tmb/T111-F111-8d3f9a6d4b/test_480.png",
                    "thumb_480_w": 477,
                    "thumb_480_h": 480,
                    "thumb_160": "https://files.slack.com/files-tmb/T111-F111-8d3f9a6d4b/test_160.png",
                    "thumb_720": "https://files.slack.com/files-tmb/T111-F111-8d3f9a6d4b/test_720.png",
                    "thumb_720_w": 716,
                    "thumb_720_h": 720,
                    "original_w": 736,
                    "original_h": 740,
                    "thumb_tiny": "xxx",
                    "permalink": "https://xxx.slack.com/files/U111/F111/test.png",
                    "permalink_public": "https://slack-files.com/T111-F111-3e534ef8ca",
                    "has_rich_preview": False,
                }
            ],
            "upload": False,
            "blocks": [
                {
                    "type": "rich_text",
                    "block_id": "gvM",
                    "elements": [
                        {
                            "type": "rich_text_section",
                            "elements": [
                                {"type": "text", "text": "Here is your file!"}
                            ],
                        }
                    ],
                }
            ],
            "user": "U111",
            "display_as_bot": False,
            "ts": "1610493715.001000",
            "channel": "G111",
            "subtype": "file_share",
            "event_ts": "1610493715.001000",
            "channel_type": "group",
        },
        "type": "event_callback",
        "event_id": "Ev111",
        "event_time": 1610493715,
        "authorizations": [
            {
                "enterprise_id": None,
                "team_id": "T111",
                "user_id": "U111",
                "is_bot": True,
                "is_enterprise_install": False,
            }
        ],
        "is_ext_shared_channel": False,
        "event_context": "1-message-T111-G111",
    }
```

**Comment by DataGreed** [comment]
Oopps, nevermind, that was because I was returning tokens or user ids in a wrong format (the message was confusing though).

In case anyone needs it, this `authorize` method seems to do the trick for testing:

```
from slack_bolt.authorization import AuthorizeResult

def bypass_authorization(*args, **kwargs):

    return AuthorizeResult(
        enterprise_id=None,
        team_id="Test",
        bot_id="Utest",
        bot_user_id="Btest",
        user_id="test",
        bot_token="xoxb-test",
        user_token="xoxp-test",
    )
```

**Comment by seratch** [comment]
@DataGreed Great to know you've figured the issue out yourself! Let us close this issue now but please feel free to write in whenever you have more to ask/discuss regarding this topic.
