### ISSUE TITLE
Disable slack button once clicked

### ISSUE THREAD

**Issue by Cyb-Nikh** [slackapi/bolt-python#421]
### To disable the slack button once it is clicked.
**Question**: Is there any parameter or an API that can help in updating the button field to something unclickable

**Description**
To begin with, let's say as a user I'm presented with a question and a few button type options:
What we are trying to achieve here is,
-  Once an option is selected, change the colour of the button (**Achieved it** using [chat.update](https://api.slack.com/methods/chat.update), by updating the style of the current message)
-  Afterwards, we are trying to disable all the buttons, so that the user won't be able to click them again and again.

Any possible way through which we can achieve them or we can change the button fields to be something more similar such that a user won't see any content styling change at his hand.

**Comment by misscoded** [comment]
Hi @Cyb-Nikh! Unfortunately, there isn't a way to make a button unclickable/disabled. 

I did a little digging and what is most often recommended in the past for similar scenarios has been to remove the buttons once you want to prevent the user from clicking them again. Then, depending on the design of the message/layout you're after, the button selected might be replaced with bolded text or some other stylized text that indicates which selection was made.

Though not exactly what you were aiming to achieve, I hope the above is helpful. Let us know if we can further assist in implementing the above or some variation thereof! 🙂

**Comment by Cyb-Nikh** [comment]
Hi @misscoded! Thank you so much for your response. 🙂 

Okay, but basically I want buttons to be there, Is there something like I can write a plain text with a styling similar to a button i.e. inside a rectangle box a static text. 

Additionally, it would be really helpful if you could help me with a relatable query which is if I can use markdown in the button field.  Such that I want the text inside a button to be bold once it is clicked.

**Comment by seratch** [comment]
Hi @Cyb-Nikh 

>Is there something like I can write a plain text with a styling similar to a button i.e. inside a rectangle box a static text.

Unfortunately, there is no way to do this. The only way we can suggest is to use Block Kit's button component.

>Such that I want the text inside a button to be bold once it is clicked.

The only way to do this is to update the whole message by either `chat.update` API call or sending an updated message via `repsonse_url`.

I hope this was helpful to you. If everything around this topic is clear so far, would you mind closing this issue?

**Comment by seratch** [comment]
Let us close this issue now but please feel free to write in whenever you have something to ask regarding this topic!
