### ISSUE TITLE
Using AWS S3 for persistent storage of OAuth tokens giving ClientError (Access Denied)

### ISSUE THREAD

**Issue by JasonDykstraSelectStar** [slackapi/bolt-python#423]
Hello again! 😅 I have had some success implementing the S3 storage for OAuth tokens and installation, however have run into an issue I'm not quite sure how to solve. I come across this issue when trying to navigate to the `.../slack/install` link: `An error occurred (AccessDenied) when calling the PutObject operation: Access Denied`

I thought this might be a permissions issue so I added these permissions to the bucket: 
```
{
    "Version": "2012-10-17",
    "Id": "redacted",
    "Statement": [
        {
            "Sid": "redacted",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::user-num:my-user-name"
            },
            "Action": "s3:*",
            "Resource": "arn:aws:s3:::my-bucket-name"
        }
    ]
}
```

I also tried setting actions to:
```
"s3:PutObject",
"s3:PutObjectAcl",
"s3:GetObject",
"s3:GetObjectAcl",
"s3:DeleteObject"
```
And this allowed me to manually add and remove files and folders from the bucket, but the slack application was still giving me an access denied error.

I have my code setup like this:

```
s3_client = boto3.client("s3", aws_access_key_id=AWS_ACCESS_KEY_ID, aws_secret_access_key=AWS_SECRET_ACCESS_KEY)
state_store = AmazonS3OAuthStateStore(
        s3_client=s3_client,
        bucket_name=os.environ["SLACK_STATE_S3_BUCKET_NAME"],
        expiration_seconds=600,
    )
oauth_settings = ...,
        installation_store=AmazonS3InstallationStore(
                s3_client=s3_client,
                bucket_name=os.environ["SLACK_INSTALLATION_S3_BUCKET_NAME"],
                client_id=os.environ["SLACK_CLIENT_ID"],
           ),
        ...

app = App(
    process_before_response=True,
    signing_secret=os.environ.get("SLACK_SIGNING_SECRET"),
    oauth_settings=oauth_settings,
    oauth_flow=LambdaS3OAuthFlow(),
)
```

My `settings.py` file looks like this (though I only reference a few things from here, I normally reference straight from `.env` file:
```
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID", None)
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY", None)
SLACK_STATE_S3_BUCKET_NAME = os.getenv("SLACK_STATE_S3_BUCKET_NAME", None)
SLACK_INSTALLATION_S3_BUCKET_NAME = os.getenv(
    "SLACK_INSTALLATION_S3_BUCKET_NAME", None
)
SLACK_LAMBDA_PATH = os.getenv("SLACK_LAMBDA_PATH", None)
```
The slack application `.settings` portion of the error page shows that all of these variables are being initialized correctly.

Any help understanding my issue would be much appreciated!

### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version

slack-bolt==1.6.1
slack-sdk==3.8.0
slackclient==2.9.3
slackeventsapi==2.2.1

#### Python runtime version

Python 3.9.6

#### OS info

Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101

#### Steps to reproduce:

Currently this is running on a docker container, but I imagine any slack application would reproduce the issue if the code setup was the same as I have pasted above.

### Expected result:

The application should be able to store OAuth tokens and installation data to the AWS S3 bucket.

### Actual result:

:(
<img width="817" alt="Screen Shot 2021-07-27 at 12 43 46 PM" src="https://user-images.githubusercontent.com/85132374/127217720-290e7021-0afa-4870-b8bf-73f725805d8b.png">

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by filmaj** [comment]
Hello @JasonDykstraSelectStar !

This definitely looks like an S3 bucket permission issue.

Your permissions look fine, though one thing that jumped out at me: it seems like there are two S3 buckets at play : SLACK_STATE_S3_BUCKET_NAME and SLACK_INSTALLATION_S3_BUCKET_NAME. Are you sure your user has permissions to both of these buckets?

**Comment by JasonDykstraSelectStar** [comment]
Hey @filmaj ! Thanks for the quick reply! I have both of these names initialized to the same bucket, as I was following [this](https://github.com/slackapi/bolt-python/blob/main/examples/aws_lambda/aws_lambda_oauth_config.yaml#L27-L34) example. I suppose I could change those two variables to both be the same thing for the sake of confusion.

**Comment by filmaj** [comment]
Do you have the `aws` CLI tool installed by any chance? It would be nice to confirm via another method that your AWS credentials have access to the buckets. If you don't have them installed, installation instructions for the AWS CLI are [here](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html).

Then you can run something like this to list buckets for your account:

```
AWS_ACCESS_KEY_ID="<your-access-key>" AWS_SECRET_ACCESS_KEY="<your-access-secret>" AWS_DEFAULT_REGION="your-aws-region" aws s3 ls
```

First check if the bucket(s) you are setting as your state and installation locations is listed via the `aws s3 ls` command. If you can see the bucket names you specified for the state/installation locations, next let's test if you can upload to these buckets by running:

```
AWS_ACCESS_KEY_ID="<your-access-key>" AWS_SECRET_ACCESS_KEY="<your-access-secret>" AWS_DEFAULT_REGION="your-aws-region" aws s3 cp some-file s3:///name-of-your-bucket
```

**Comment by JasonDykstraSelectStar** [comment]
So I have permissions `s3:*` so I should be able to list buckets, however upon executing `aws s3 ls` I get `An error occurred (AccessDenied) when calling the ListBuckets operation: Access Denied`. Also when I try the second command, when I enter the bucket name or the ARN, I get `Invalid bucket name "": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]+:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"` Perhaps I need to look elsewhere to set permissions?

**Comment by filmaj** [comment]
> So I have permissions s3:* so I should be able to list buckets, however upon executing aws s3 ls I get An error occurred (AccessDenied) when calling the ListBuckets operation: Access Denied.

OK, given the assumption you gave your user all permissions, let's focus on solving listing buckets first.

Let's check which user is associated with the access key you are using. You can do that by running:

```
AWS_ACCESS_KEY_ID="<your-access-key>" AWS_SECRET_ACCESS_KEY="<your-access-secret>" aws iam get-user
```

The `Arn` output of the above command MUST exactly match your policy statement's `Principal.AWS` property. Looking at your Principal AWS property as you posted in your original post, you have `arn:aws:iam::user-num:my-user-name` - I assume this is a placeholder, but usually user ARNs are prefixed with `user/` before the username, i.e. `arn:aws:iam::account-num:user/my-user-name`. Perhaps that is it?

I also noticed something just now that the `Resource` section of your policy only references the bucket name, and not any path within the bucket. This may also be the issue. Usually to provide general sweeping permissions to S3 buckets, including the ability to upload to any key within the bucket, I use a policy that looks like this:

```
        Statement: [ {
          Effect: 'Allow',
          Action: [
            's3:*'
          ],
          Resource: [
            'arn:aws:s3:::my-bukkit',
            'arn:aws:s3:::my-bukkit/*'
          ]
        } ]
```

Maybe try using a similar approach to the `Resource` property in your policy as well?

**Comment by JasonDykstraSelectStar** [comment]
Hey! So an update on the problem: my user (from doing `aws iam get-user`) is the same as on the `Principal.AWS` policy. The address was indeed `arn:aws:iam::account-num:user/my-user-name` I just didn't properly convey that in the original comment. The action section of the bucket policy is set to `s3:*` and the resources matches what you have above, with both `...my-bukkit` and `...my-bukkit/*`.

I've called AWS since I still get an access denied issue when trying to list buckets with my account, even after given admin status on AWS. Support told me the issue was probably related to the CLI so they will look into it and get back to me.

**Comment by filmaj** [comment]
OK, sounds good. 🤞

**Comment by JasonDykstraSelectStar** [comment]
So the issue was that another permission `Force-MFA` was taking priority, and since commands issued through the CLI did not have multi-factor authentication by default, it was returning a permission denied error. My solution for this was to create a custom permission in AWS that does not require MFA, but perhaps there is a solution for this through Bolt if someone happens to stumble across this issue in the future?

**Comment by seratch** [comment]
@JasonDykstraSelectStar Thanks for sharing your updates here! Yes, as you corrected yourself, if you set the `OAuthFlow` to `App`, the initialization of `OAuthFlow` requires the properly configured `OAuthSettings` values.

If I understand correctly, it seems that everything is clear now. Would you mind if we close this issue now?

**Comment by JasonDykstraSelectStar** [comment]
Yep, sounds good! Thanks again for your help @filmaj
