### ISSUE TITLE
How to send a snippet to channel?

### ISSUE THREAD

**Issue by YAMLcase** [slackapi/bolt-python#425]
how do I send a text snippet to the channel?  I'm using websockets if that matters.

**Comment by seratch** [comment]
Hi @YAMLcase, thanks for asking the question! You can upload the text data using files.upload API. Refer to https://github.com/slackapi/bolt-js/issues/636#issuecomment-697077498 for more details 👋

**Comment by YAMLcase** [comment]
Would this require scope "files:write"?

**Comment by seratch** [comment]
@YAMLcase Yes, the scope is required for calling the API! It seems that everything is clear now. Let me close this issue now but please feel free to write in when you have anything further to ask.

**Comment by YAMLcase** [comment]
@seratch I'm having difficulty knowing where to call files.upload (the link you gave sends me to a javascript example).  Here's the code I'm working with:

```python
from slack_bolt import Say, App
from slack_bolt.adapter.socket_mode import SocketModeHandler

app = App(token=bot_token)
handler = SocketModeHandler(app)
handler.app_token = app_token]
handler.connect()

content = "here's some snippit text"
#upload content how?
```

**Comment by srajiang** [comment]
HI @YAMLcase - There's a great set of sample code within the `examples` folder of this repo which might be helpful to you as a reference. 

For example, here is the python [socketmode](https://github.com/slackapi/bolt-python/blob/main/examples/socket_mode.py) simple app example. You'll notice in the `open_modal` method, there's a usage of `client.views_open` which in that case is accessing the `views.open` API.

In your case, for using`files.upload`, you'd want to use `client.files_upload`. Hope that helps!
