### ISSUE TITLE
Japanese: Make "events" in the document even clearer (#412)

### ISSUE THREAD

**Issue by seratch** [slackapi/bolt-python#427]
We can apply the updates in #415 to the Japanese version of the documents. See also #412 

### The page URLs

* https://slack.dev/bolt-python/ja-jp/concepts#basic

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by Shoryu-N** [comment]
I would like to take this one.
