### ISSUE TITLE
How can I stop the logging of HTTP requests to the app?

### ISSUE THREAD

**Issue by cole-wilson** [slackapi/bolt-python#430]
Currently my app writes the following to the console:
```
172.18.0.1 - - [08/Aug/2021 03:13:53] "GET / HTTP/1.1" 404 -
```
There are messages like this for every request to my app. I would not like to see this printed to the console.

Is there a way to disable this? The default python logging module does not seem to work.
Thank you!

**Comment by cloudguruab** [comment]
Hey, to help with your issue I am assuming you'd like to suppress the output of stdout to the console. To do so: 

```
from contextlib import contextmanager
import sys, os

@contextmanager
def suppress_stdout():
    with open(os.devnull, "w") as devnull:
        old_stdout = sys.stdout
        sys.stdout = devnull
        try:  
            yield
        finally:
            sys.stdout = old_stdout
```

with this 

```
print("Now you see it")
# with suppress_stdout():
    print("Now you don't")
```

**Comment by seratch** [comment]
Hi @cole-wilson, thanks for asking this question. As you are already aware of, there is no way to customize it at the moment. I'll add a new option to configure it in the next version: https://github.com/slackapi/bolt-python/pull/431

If you need more granular configuration on logging, I would recommend using a different web framework/sever for your app development. Here is a Flask app example:

* https://github.com/slackapi/bolt-python/blob/main/examples/flask/app.py
* https://slack.dev/bolt-python/concepts#adapters

@cloudguruab Thanks for jumping in and helping other developers!

**Comment by cole-wilson** [comment]
Thank you so much for both of your quick responses!
