### ISSUE TITLE
Add an app argument to disable suggestion for unhandled events.

### ISSUE THREAD

**Issue by jgengo** [slackapi/bolt-python#433]
Hello!

Would it be possible to add the possibility to disable suggestions for unhandled events?

I've added `message.channels` events to my slack app, and I'm receiving "message_changed" that I would like to ignore, so I thought about adding this:

```python
 def no_ignore_list(message, next):
      if not message.get('subtype') in ['message_changed']
          next()

@app.event(event="message", middleware=[no_ignore_list])
def message_handler(payload, say, context):
    pass
```

But with this, I can't use anymore `@app.message("")`

Thanks!

### Category

* [x] **slack_bolt.App** and/or its core components
* [x] **slack_bolt.async_app.AsyncApp** and/or its core components
* [ ] Adapters in **slack_bolt.adapter**
* [ ] Others

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @jgengo, thanks for asking the question!

If you have `raise_error_for_unhandled_request=True` in the `App` constructor, you can handle the unmatched patterns in the global error handler: 
* https://slack.dev/bolt-python/concepts#errors 
* https://github.com/slackapi/bolt-python/pull/290

However, I don't think that it's a straight-forward solution in this case. 

The listeners for an `App` can be evaluated in the order where they are registered to the `App` instance. Therefore, the following code should work for you.

```python
@app.message("")
def handle_message_events():
    # do something here

@app.event("message")
def message_handler():
    # just for acknowledging the rest
    pass
```

I hope this was helpful to you!

**Comment by jgengo** [comment]
Hi @seratch and thanks for the quick reply!

I just try to re-order my @app.message and @app.event. It works pretty well now 👍🏻 

I assume that this question can be closed.

Thanks again!
