### ISSUE TITLE
Adding matches into context when using @app.action

### ISSUE THREAD

**Issue by jgengo** [slackapi/bolt-python#435]
Hello 👋🏻 

While using @app.message() with re.compile, we can find matches added into the context. 

That would be great to add this also when using @app.action()

Here is an example:

```python
@app.action(re.compile('open_downstair|open_upstair|open_gates|open_bocal'))
def open_door(ack, body, respond):
    ack()
    action_id = body['actions'][0]['action_id']
```
That would probably be cleaner to be able to use `context['matches'][0]`

Thanks!

* [x] **slack_bolt.App** and/or its core components
* [x] **slack_bolt.async_app.AsyncApp** and/or its core components
* [ ] Adapters in **slack_bolt.adapter**
* [ ] Others
**^ I don't know :'(**

**Comment by seratch** [comment]
Hi @jgengo, thanks for taking the time to share this feedback!

Indeed, capturing the string in context's matches can be useful also in other listener use cases. However, as the team has been focusing on other priorities right now, we cannot tell whether we will implement this and when it may happen if we decide to have it. Just adding this to a specific listener type is relatively quick but we maintain three language/runtime versions of Bolt framework (Node.js / Python / JavaVM). Implementing and maintaining the same functionalities in all of them in a great quality can take longer.

If you want the functionality immediately, you can add a middleware that captures the string to your app.

As a reference, `app.message` listener have a listener middleware for it: https://github.com/slackapi/bolt-python/blob/v1.7.0/slack_bolt/app/app.py#L782
You can reuse the most parts of the middleware but the target text value extraction can vary depending on the payload data structure. https://github.com/slackapi/bolt-python/blob/v1.7.0/slack_bolt/middleware/message_listener_matches/message_listener_matches.py#L24

I hope this was helpful to you. To see if there are a lot of demands for built-in support of this functionality in communities, we won't close this issue for now.

**Comment by jgengo** [comment]
Thanks a lot @seratch for the quick response :) 

It's not important that it's implemented any time soon for me, I was thinking it was worth it to share :) 

Thanks and good luck!

**Comment by seratch** [comment]
In the last half year, we haven't received any similar feature requests not only for bolt-python but for other bolt projects. Also, as implementing this feature can bring more complexity to the internals of the bolt framework, we are not lean towards implementing it at least in the short term.

As a workaround, please go ahead with your own listener middleware to capture the matching results. With that, you can set the result to `context` object. 

Thanks again for your feedback here!
