### ISSUE TITLE
Healthcheck

### ISSUE THREAD

**Issue by Leem0sh** [slackapi/bolt-python#439]
Hello, deploying the slack application into kubernetes and since I'm using EC2 and ECR from AWS with built-in heathchecks I'd appreciate to have built-in health check enpoint in the slack application as well. Or is there a way of adding a simple enpoint when using Bolt Application? Not using socket mode, just simply
```
from slack_bolt import App

app = App()

@app.command("/echo")
...
```

Similar to https://github.com/slackapi/bolt-js/issues/283

**Comment by seratch** [comment]
👋 @Leem0sh, let us know if you have anything further to ask/discuss on this topic! We'll close this issue after waiting for your response for a few more days.

**Comment by Leem0sh** [comment]
Hello @filmaj and @seratch! 

Thanks for your replies. So if I understood correctly... 

If I'm gonna use Flask like in your example: 
```
@app.command("/echo")
def echo(ack, say):
    do_this_and_this()
    say("done")


from flask import Flask, request

flask_app = Flask(__name__)
handler = SlackRequestHandler(app)


@flask_app.route("/slack/events", methods=["POST"])
def slack_events():
    return handler.handle(request)

@flask_app.route("/healthcheck", methods=["GET"])
def heathcheck():
    return "OK"
# run
if __name__ == "__main__":
    app.start(port=int(settings.get('SLACK_PORT', 3000)))
```
Does that mean that I don't want to use the `app.start(...)` bcs that would only start the Slack App and not the whole flask application ? So what is needed is that basically I'll be running flask application but with `/slack/events` endopoint that is gonna handle all the slack events (like @app.command(...)) and then I can create any other enpoint (like `/healthcheck`)? Do I understand that correctly now?

**Comment by seratch** [comment]
@Leem0sh Your app code is fine but it seems that you can consult Flask / Python web server documentation to learn more about the common ways.

You don't need to (and you cannot) use `app.start()` if you go with Flask web framework. A common way to run a Flask app as a production server is to use a web app server such as [Gunicorn](https://gunicorn.org/) to run the WSGI app (=Flask app): https://github.com/slackapi/bolt-python/blob/v1.8.0/examples/docker/flask-gunicorn/Dockerfile#L14

Also, refer to Flask's documentation:
* https://flask.palletsprojects.com/en/2.0.x/quickstart/
* https://flask.palletsprojects.com/en/2.0.x/quickstart/#deploying-to-a-web-server

Was this helpful to you?

**Comment by Leem0sh** [comment]
@seratch oh of course, I just used the "easy way" since I was just testing the app. Okay thanks a lot for help! The main thing I needed to understand was that I had to run the Flask application with /slack/events handler and not the app itself with app.start(). 

Thanks a lot!

**Comment by seratch** [comment]
Glad to hear that this thread has been helpful to you! Let me close this issue now.
