### ISSUE TITLE
How to update view on submission.

### ISSUE THREAD

**Issue by naruhodou** [slackapi/bolt-python#447]
I want to call views_update inside @app.views when submitting. I have seen people implementing response_action: update solution. But that doesn't work. I am using socket mode unlike any previous issue. I can't send payload because there is no response url.

**Comment by seratch** [comment]
@naruhodou This might be a bit confusing but, in response to view_submission (=`@app.view` patterns), using response_action in `ack()` is the recommended way. 

```python
@app.view("callback-id")
def handle_first input(ack):
    ack(response_action="update", view=build_updated_view())
```
See also:
* https://slack.dev/bolt-python/concepts#view_submissions

The `views.update` API method (=`client.views_update(...)` in your Python code) can be used for `block_actions` / `block_suggestion` listeners (= `@app.action` , `@app.options` patterns).

See also:
* https://slack.dev/bolt-python/concepts#updating-pushing-views

Hope this helps.

**Comment by seratch** [comment]
@naruhodou 👋 Let us know if you need more help here! We may close this issue after waiting for your response for a while.

**Comment by naruhodou** [comment]
Thanks for the input.
