### ISSUE TITLE
can I have multiple sockets connection with one app

### ISSUE THREAD

**Issue by jgengo** [slackapi/bolt-python#448]
Hello 👋🏻 

I read the Slack documentation regarding the Socket and it seems to says that it can works up to 10 simultaneous socket per app.

I tried today, and it acts quite weirdly, it seems that I receive some of the events, but not all of them. It might dispatch one to my first slack-bolt socket and not the other one, and the other way around some time.

Do you know if there is something that could be preventing slack-bolt to work with simultaneous connection with the same app?

I would like if possible to receive the events to all the listening sockets.

Thanks

**Comment by seratch** [comment]
>Thus, from bolt-python project maintenance perspective, I'm leaning toward closing this issue.

For this reason, let us close this issue. Thanks for starting this conversation!
