### ISSUE TITLE
Can I make the text input field in modal not mandatory?

### ISSUE THREAD

**Issue by RachelDong** [slackapi/bolt-python#450]
Hello,

I open a modal view with *client.views_open* function, here is my code:
```
view = {
    "type": "modal",
    "title": {
        "type": "plain_text",
        "text": "My App",
        "emoji": True
    },
    "submit": {
        "type": "plain_text",
        "text": "Submit",
        "emoji": True
    },
    "close": {
        "type": "plain_text",
        "text": "Cancel",
        "emoji": True
    },
    "blocks": [
        {
            "type": "input",
            "element": {
                "type": "plain_text_input",
                "action_id": "plain_text_input-action"
            },
            "label": {
                "type": "plain_text",
                "text": "Please leave feedback here",
                "emoji": True
            }
        }
    ]
    }
slack_client.views_open(trigger_id=body['trigger_id'],view=view)
```
And the modal is like:
![图片](https://user-images.githubusercontent.com/34002808/131134399-8697b5b4-9aa1-4708-9c57-261a7e9d8669.png)

The user cannot submit the view if they just leave the input field blank. I want to know can I make the input optional? That is, even though the user leaves it blank, they can still submit the modal. Does anyone have idea? Thanks in advance:)

**Comment by seratch** [comment]
Hi @RachelDong, thanks for asking the question! You can have `"optional": true` as an additional property in the input block. Refer to the document for details: https://api.slack.com/reference/block-kit/blocks#input

**Comment by RachelDong** [comment]
That's solving my problem! Thanks a lot!
