### ISSUE TITLE
Bolt very delayed or not working at all

### ISSUE THREAD

**Issue by marktdonnelly** [slackapi/bolt-python#456]
(Filling out the following details about bugs will help us solve your issue sooner.)

### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version

(Paste the output of `pip freeze | grep slack`)

#### Python runtime version

(Paste the output of `python --version`)

#### OS info

(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1.
2.
3.

### Expected result:

(Tell what you expected to happen)

### Actual result:

(Tell what actually happened with logs, screenshots)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @marktdonnelly, thanks for taking the time to write in! Can I ask you to provide a bit more details about the issue you're facing?

**Comment by seratch** [comment]
Let us close this issue now but please feel free to write in whenever you have anything further to ask about this SDK!

**Comment by marktdonnelly** [comment]
I don't know what more I can provide you.

When you click on the "Bolt" and fill it out. it takes 3+ minutes for it to
appear or it does not appear at all.

On Thu, Sep 2, 2021 at 7:50 PM Kazuhiro Sera ***@***.***>
wrote:

> Hi @marktdonnelly
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_marktdonnelly&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=21P6CSxRNOi-IIz0HJF4bVIZNyKOrGhVnjtuuXKk1uc&m=_LPFn8gm7ECXjHQ70IuZ26hsAmy3Y3KfoXybY3S3oAA&s=Iu9ZJIBkSvdlWcAQ3NYZn0EbSVOJUaCf55Qy9_mOOY0&e=>,
> thanks for taking the time to write in! Can I ask you to provide a bit more
> details about the issue you're facing?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_slackapi_bolt-2Dpython_issues_456-23issuecomment-2D912136559&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=21P6CSxRNOi-IIz0HJF4bVIZNyKOrGhVnjtuuXKk1uc&m=_LPFn8gm7ECXjHQ70IuZ26hsAmy3Y3KfoXybY3S3oAA&s=asEj-XoC6OJslvhn9kTZKDxt6hzLPqpgeJgf_y52RMs&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AVOVIOERLCWDUWOD66BYQLLUAAETXANCNFSM5DJXXCPA&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=21P6CSxRNOi-IIz0HJF4bVIZNyKOrGhVnjtuuXKk1uc&m=_LPFn8gm7ECXjHQ70IuZ26hsAmy3Y3KfoXybY3S3oAA&s=TPJyeZhHazJQ8sObYMhV8z9i4Qe6d5zqbTUFVB9MkeA&e=>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=21P6CSxRNOi-IIz0HJF4bVIZNyKOrGhVnjtuuXKk1uc&m=_LPFn8gm7ECXjHQ70IuZ26hsAmy3Y3KfoXybY3S3oAA&s=TTKxK3rvmx7KW-q9A_nHbJeE-QATovJd15LeNyYxQ_8&e=>
> or Android
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=21P6CSxRNOi-IIz0HJF4bVIZNyKOrGhVnjtuuXKk1uc&m=_LPFn8gm7ECXjHQ70IuZ26hsAmy3Y3KfoXybY3S3oAA&s=BT6xC1LNQiuzpsL9WwUWIhLtQnpPmfv_0rAPA6Jp-7E&e=>.
>
>


-- 
<http://www.verizon.com>

Mark T. Donnelly

Local Manager
FiOS I&M
Verizon Consumer Group

O 631 864 9910
M 516 639 6372
720 Larkfield Rd.
Commack GWC
East Northport, NY 11731


*Notice:* This message contains information that may be confidential,
proprietary and/or privileged. The information is intended solely for the
individual or entity named above and access by anyone else is unauthorized.
If you are not the intended recipient, any disclosure, copying or
distribution of this information is prohibited and may be unlawful. Please
reply back to me immediately if you have received this email in error and
then delete it.
