### ISSUE TITLE
How to make the listener full-matched?

### ISSUE THREAD

**Issue by RachelDong** [slackapi/bolt-python#458]
Hello,

The bot can listen to messages and give response by:
```
@app.message("knock knock")
def ask_who(message, say):
    say("_Who's there?_")
```
Then all messages containing "knock knock" will be replied with "Who's there?", but I want the bot to only respond to the message which exactly is "knock knock", other messages, such as "knock knock heyheyhey", will not be responded. Is there any method I can realize this? Thanks in advance.

**Comment by seratch** [comment]
Hi @RachelDong, the following code should work for you!

```python
import re

@app.message(re.compile("^knock knock$"))
def ask_who(say):
    say("_Who's there?_")
```

**Comment by RachelDong** [comment]
That's really nice, thank you :)!

**Comment by RachelDong** [comment]
That's really nice, thank you :)!
