### ISSUE TITLE
App decorator methods (e.g., action, command) have incorrect return type annotation

### ISSUE THREAD

**Issue by chrisbouchard** [slackapi/bolt-python#459]
Methods on `App` that are intended to be used as decorators have an incorrect return type annotation. E.g., for `App.command`,

```python
def command(
    self,
    command: Union[str, Pattern],
    matchers: Optional[Sequence[Callable[..., bool]]] = None,
    middleware: Optional[Sequence[Union[Callable, Middleware]]] = None,
) -> Optional[Callable[..., Optional[BoltResponse]]]:
```

As written, this is actually the return type for the `__call__` function (the function returned by `command`). I believe the actual return type annotation for this method should be

```python
-> Callable[..., Optional[Callable[..., Optional[BoltResponse]]]]
```

I believe this same bug exists for all decorator methods. I've just used `command` as an example because it's the one I was using in my code.

### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version

```
slack-bolt @ file:///home/chris/.cache/pypoetry/artifacts/07/a4/dc/0ff1b9
e40910182628c62f696f06a685006e9bbebde8e0fbbf8dc2aa6c/slack_bolt-1.9.0-py2
.py3-none-any.whl
slack-sdk @ file:///home/chris/.cache/pypoetry/artifacts/54/72/e4/1b7d076
acf9c2a6c8175154452e38c8cd43f48c7f2c987c804b32c8a8c/slack_sdk-3.10.1-py2.
py3-none-any.whl
```

#### The `mypy` version

```
mypy @ file:///home/chris/.cache/pypoetry/artifacts/36/49/09/f6ff69bf72a4
3d56fd882450780491cf84523aa3cb39b1d0e3f2c6c9a4/mypy-0.910-cp39-cp39-manyl
inux2010_x86_64.whl
```

#### Python runtime version

```
Python 3.9.6
```

#### OS info

(I ran `uname -av` because neither of the commands listened work on Fedora.)
```
Linux **** 5.13.12-200.fc34.x86_64 #1 SMP Wed Aug 18 13:27:18 UTC 2021 x86
_64 x86_64 x86_64 GNU/Linux
```

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1. Create an `App` instance called `app`.
2. Register a listener:
    ```python
    app.command(COMMAND_NAME)(listener_function)
    ```
3. Run `mypy` on the code.

### Expected result:

`mypy` returns no type errors.

### Actual result:

`mypy` returns an error for the line registering the listener function.

```
error: "None" not callable
```

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @chrisbouchard, thanks for taking the time to report this issue! And you are right that those type hints are not correct. We'll fix this issue in the next release.

**Comment by chrisbouchard** [comment]
Thank you for addressing this so quickly!
