### ISSUE TITLE
Socket Mode Multiple Connections

### ISSUE THREAD

**Issue by mariebarrramsey** [slackapi/bolt-python#462]
Hello, I'd like to have multiple connections within the same slack app in socket mode that can receive different events. I saw the issue here: https://github.com/slackapi/bolt-python/issues/448 stating that this may not be possible but the documentation wording is confusing me.

It states: 

```
Socket Mode allows your app to maintain up to 10 open WebSocket connections at the same time.

When multiple connections are active, each payload may be sent to any of the connections. 
It's best not to assume any particular pattern for how payloads will be distributed across multiple open connections.
```

Does this refer to the 10 app-level tokens a slack app can have or the number of connections attached per each slack app token? I'm trying to see if this is possible at all within one app or if it would be necessary to create multiple apps or implement the job queueing solution mentioned.

**Comment by seratch** [comment]
Hi @mariebarrramsey, thanks for asking the question!

The 10 connections per app means that your Socket Mode app can be scaled out up to 10 instances for large traffic. For instance, if your Socket Mode app can receive 10K requests from Slack per day and you establish 10 connections for the app, each connection (=Bolt app instance) can handle only 1K requests. Also, in the case where one of the connections is not working, the Slack server-side send retried requests to one of other active connections.

In a nutshell, this is only for robust app operations.

>Hello, I'd like to have multiple connections within the same slack app in socket mode that can receive different events

I might not fully understand what you would like to achieve yet but if this means that customizing the way to dispatch events (say, Interactivity to instance A while Events API to instance B), the 10 connections per app is not for the use case. As I mentioned in #448, you need to come up with your own solution to assign a work to a specific host/instance.

I hope this helps! Is everything clear now?

**Comment by mariebarrramsey** [comment]
Hi, thanks. I don't want to customize dispatching events, but rather I'd like to run the slack app in different environments which may be receiving different requests. For example, if multiple developers are running the code with the same slack app, I'd like each of those developers to be able to receive their own messages and not run into the problem of the random payloads being sent to any of them. It seems like the different tokens may be for load balancing instead of this use case.

**Comment by seratch** [comment]
@mariebarrramsey Sending any of the available connections is the intentional behavior of Socket Mode. Also, it's not per app-level token but per app. 

The only approach we can suggest for your use case, is to share the App Manifest (you can find the YAML data at **Settings** > **App Manifest* in your app configuration page) with the other developers and create a copied app for each developer for local development.

**Comment by seratch** [comment]
@mariebarrramsey Let us know if you need further help here 👋

**Comment by mariebarrramsey** [comment]
Thank you! That makes more sense now
