### ISSUE TITLE
[python] How to display input error in modal?

### ISSUE THREAD

**Issue by RachelDong** [slackapi/bolt-python#463]
Hello,

I want to collect user info via modal view, when the user click the 'add-info' button, the following code will execute:
```python
@app.action('action-id-add-info')
def open_modal(ack,body,client):
    ack()
    client.views_open(trigger_id = body["trigger_id"], view = {some playloads})
```
the modal is openned like:
<img src="https://user-images.githubusercontent.com/34002808/132824745-746bad27-0c2f-4ee9-959e-f4849c791bbc.png" width=400/>

When the user complete the form, he/she will click the submit button on the view, and the app can capture the view submission by:
```python
@app.view("modal_submitted")
def handle_submission(ack, view):
    ack()
    email = view["state"]["values"]["block_c"]["dreamy_input"]
    ......
```
Here, I add some logic to validate the email address, when it is invalid, I want the modal display the error as:
<img src="https://user-images.githubusercontent.com/34002808/132825252-10aec4c6-b0b1-4cd2-9ef7-becd3f6b9c30.png" width=400/>
The image is from https://api.slack.com/surfaces/modals/using#displaying_errors
I don't really understand the content in this webpage, which function should I use to send the following json? 
```json
{
  "response_action": "errors",
  "errors": {
    "ticket-due-date": "You may not select a due date in the past"
  }
}
```

**Comment by seratch** [comment]
Hi @RachelDong, the following resources should be helpful for understanding how to implement this in Python:

* https://slack.dev/bolt-python/concepts#view_submissions
* https://github.com/seratch/apidays-workshop-2020/blob/87f623356f90fbdb9f5112e114dc51c157698ac7/python/app.py#L272-L283

I hope this helps! If everything is clear now, would you mind closing this issue?

**Comment by RachelDong** [comment]
Yes that really helps! Thank you:)
