### ISSUE TITLE
Calling "complete()" in execute workflow step takes longer than 3 seconds to finish when running in AWS Lambda

### ISSUE THREAD

**Issue by mcroft246** [slackapi/bolt-python#465]
### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version

slack-bolt==1.9.0
slack-sdk==3.10.1

#### Python runtime version

Python 3.8.11

#### OS info

Lambda Python 3.8

#### Steps to reproduce:

1. Code below is configured as Lambda function with API gateway in front.
2. Execute the workflow.

```python
import os
import logging
from slack_bolt import App
from slack_bolt.workflows.step import WorkflowStep
from slack_bolt.adapter.aws_lambda import SlackRequestHandler

logging.getLogger().setLevel(logging.INFO)

app = App(
    token=os.environ.get("SLACK_BOT_TOKEN"),
    signing_secret=os.environ.get("SLACK_SIGNING_SECRET"),
    process_before_response=True,
)


def edit(ack, step, configure):
    ack()

    blocks = [
        {
            "type": "input",
            "block_id": "task_name_input",
            "element": {
                "type": "plain_text_input",
                "action_id": "name",
                "placeholder": {"type": "plain_text", "text": "Add a task name"},
            },
            "label": {"type": "plain_text", "text": "Task name"},
        },
        {
            "type": "input",
            "block_id": "task_description_input",
            "element": {
                "type": "plain_text_input",
                "action_id": "description",
                "placeholder": {"type": "plain_text", "text": "Add a task description"},
            },
            "label": {"type": "plain_text", "text": "Task description"},
        },
    ]
    configure(blocks=blocks)


def save(ack, view, update):
    ack()

    values = view["state"]["values"]
    task_name = values["task_name_input"]["name"]
    task_description = values["task_description_input"]["description"]

    inputs = {
        "task_name": {"value": task_name["value"]},
        "task_description": {"value": task_description["value"]}
    }
    outputs = [
        {
            "type": "text",
            "name": "task_name",
            "label": "Task name",
        },
        {
            "type": "text",
            "name": "task_description",
            "label": "Task description",
        }
    ]
    update(inputs=inputs, outputs=outputs)


def execute(step, complete, fail):
    try:
        inputs = step["inputs"]
        task_name = inputs["task_name"]
        complete(outputs={})
        logging.info(f"{task_name} complete!!")
    except Exception as err:
        fail(error={"message": f"Error: {err}"})


def handler(event, context):
    """Lambda handler"""
    # Create a new WorkflowStep instance
    ws = WorkflowStep(
        callback_id="alert",
        edit=edit,
        save=save,
        execute=execute,
    )
    # Pass Step to set up listeners
    app.step(ws)

    slack_handler = SlackRequestHandler(app=app)
    result = slack_handler.handle(event, context)
    return result
```

### Expected result:

"complete()" call in "execute" step should finish in less than 3 seconds so Slack doesnt retry the step.

Things I have tried:

- Have put timers around the "complete()" and can see that it takes 3+ seconds.
- Enabled provisioned concurrency to rule out cold starts.
- Provisioned more memory for the function.

Is there any way around this?

### Actual result:

The "complete()" call takes longer than 3 seconds for the first event but eventually succeeds. Because the complete call takes longer than 3 seconds Slack resends the event and the second run fails with:

"ERROR:slack_bolt.App:Failed to run listener function (error: The request to the Slack API failed. (url: https://www.slack.com/api/workflows.stepFailed)
The server responded with: {'ok': False, 'error': 'trigger_exchanged'})"

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by srajiang** [comment]
Thanks for writing in @mcroft246 - Let me try to reproduce what you're seeing and get back to you on this issue.

**Comment by srajiang** [comment]
@mcroft246 - Would the workaround using a lazy listener mentioned [here](https://slack.dev/bolt-python/concepts#lazy-listeners) work for your situation?

**Comment by mcroft246** [comment]
Thanks for the response. I saw this [example](https://github.com/slackapi/bolt-python/blob/main/examples/workflow_steps/steps_from_apps_decorator.py) of a lazy listener for workflow steps however it seems to be the "complete()" call that takes up the time so i was unsure of how the lazy listener would assist as that call is still in the execute step?

**Comment by seratch** [comment]
Hi @mcroft246, the following example should work for you!

```python
def run_the_step(logger: logging.Logger, step: dict, complete: Complete, fail: Fail):
    logger.info("execute called")
    try:
        complete(
            outputs={
                "taskName": step["inputs"]["taskName"]["value"],
                "taskDescription": step["inputs"]["taskDescription"]["value"],
                "taskAuthorEmail": step["inputs"]["taskAuthorEmail"]["value"],
            }
        )
    except Exception as err:
        fail(error={"message": f"Something wrong! {err}"})


@copy_review_step.execute(lazy=[run_the_step])
def execute():
    # If you don't have anything to do within 3 seconds,
    # Just having `pass` or logging works here
    pass

**Comment by mcroft246** [comment]
Hi @seratch. I tested the above and it works. Thanks for your help!

**Comment by gnohgnij** [comment]
Hi @seratch, how do I import `@copy_review_step`?

**Comment by Amarnathchode** [comment]
Hi Seratch, we had same issue, but the solution is not working because we used different workflow builders like below, could please provide an alternative way to overcome the issue 
the primary issue is with ""copy_review_step = WorkflowStep.builder("copy_review")"", when we used the copy review step the Workflow builder steps trying to find execute command but changed from "execute " to "kendra_step_execute" that is not in workflow builder step.

The execute step are in Kendrastep.py we are importing in this module 

from .kendrastep import *
def run():
    """
    Entry and starting point for execution of the slack app steps execution where we configure the steps with ids
    and starts the slack app in socket mode to access across the network.
    :return: None
    """
    secret_string = SecretManagerProxy.get_secrets()
    SLACK_BOT_TOKEN = secret_string['SLACK_BOT_TOKEN']
    SLACK_APP_TOKEN = secret_string['SLACK_APP_TOKEN']

    helpcentral_step = WorkflowStep(
        callback_id=os.environ.get('HELPCENTRAL_STEP_ID'),
        edit=helpcentral_step_edit,
        save=helpcentral_step_save,
        execute=helpcentral_step_execute,
    )

    kendra_step = WorkflowStep(
        callback_id=os.environ.get('KENDRA_STEP_ID'),
        edit=kendra_step_edit,
        save=kendra_step_save,
        execute=kendra_step_execute,
    )
    bot_app = App(token=SLACK_BOT_TOKEN)
    bot_app.step(helpcentral_step)
    bot_app.step(kendra_step)
    bot_app.event("app_mention")(app_mention)
    handler = SocketModeHandler(bot_app, SLACK_APP_TOKEN)
    handler.start()

**Comment by Amarnathchod** [comment]
Hi Seratch, we ran into similar issue were we called two API's using web socket connection like below in AWS Kubernetes The __init__.py consist of below code 

from slack_bolt.workflows.step import WorkflowStep
from secret import SecretManagerProxy
from .2_step import *
from .1_step import *
from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler
from logger import log
from logger.cloudwatchlogging import cloudwatches_logstream



def app_mention(body, say):
    pass

def run():
    """
    Entry and starting point for execution of the slack app steps execution where we configure the steps with ids
    and starts the slack app in socket mode to access across the network.
    :return: None
    """
    secret_string = SecretManagerProxy.get_secrets()
    SLACK_BOT_TOKEN = secret_string['SLACK_BOT_TOKEN']
    SLACK_APP_TOKEN = secret_string['SLACK_APP_TOKEN']

    1_step = WorkflowStep(
        callback_id=os.environ.get('1_STEP_ID'),
        edit=1_step_edit,
        save=1_step_save,
        execute=1_step_execute,
    )

    2_step = WorkflowStep(
        callback_id=os.environ.get('2_STEP_ID'),
        edit=2_step_edit,
        save=2_step_save,
        execute=2_step_execute,
    )
    bot_app = App(token=SLACK_BOT_TOKEN)
    bot_app.step(1_step)
    bot_app.step(2_step)
    bot_app.event("app_mention")(app_mention)
    handler = SocketModeHandler(bot_app, SLACK_APP_TOKEN)
    handler.start()

once we receive the API call the below 2_step.py  code triggered 

def 1_step_execute(step, complete, fail):
    """
    this step for executing the step code below once edit and save step completed
    :param step: receiving step configuration
    :param complete: completing the step
    :param fail: hadling failures
    :return: None
    """
    details = {
        "question": step["inputs"]["question"]["value"],
        "noanswer": step["inputs"]["noanswer"]["value"],
        "channel": step["inputs"]["channel"]["value"],
        "accountid": step["inputs"]["accountid"]["value"],
        "category": step["inputs"]["category"]["value"],
        "environment": step["inputs"]["environment"]["value"],
    }

    try:
        answer = getAnswer(details)

    except Exception as error:
        if str(error).find(" The character count must be less than or equal to 1000.")!=-1:
            answer = "Please refine your Question to a more basic format. Use Additional Details to add more information"
        else:
            log.info("Error_character", error)
            answer = error

    cloudwatches_logstream(
        {"timestamp": int(round(time.time() * 1000)),
         "message": str({"question": details['question'],
                         "channel_name": details['channel'], "account_id": details['accountid'],
                         "category": details['category'], "environment": details['environment']})})
    outputs = {"answer": answer}

    try:
        start = time.time()
        #log.info("Complete step start time" + str(start))
        complete(outputs=outputs)
        end = time.time()
        #log.info("Complete step end time" + str(end))
        #time_taken = end - start
        time_taken = start - end
        pass
    except Exception as e:
        log.info("Error in complete step:- " + str(e))


# @copy_review_step.execute(lazy=[run_the_step])
# def execute():
#     # If you don't have anything to do within 3 seconds,
#     # Just having `pass` or logging works here
#     pass
