### ISSUE TITLE
How to get a parent message id by reaction to threaded message

### ISSUE THREAD

**Issue by abadd00d** [slackapi/bolt-python#466]
Hi.

I'm trying to write an app which will post something when somebody has reacted to a message in thread.
So there is a code:

```
@app.event("reaction_added")
def reply_to_emoji(event, say):

    thread = event["item"]["ts"]
    if event["reaction"] == "harold_thumb":
      text = f"Boom!"
      say(text=text, thread_ts=thread)
```

It works perfect when somebody adding reaction to parent message, but it doesn't when somebody adding reaction to threaded message.

How to get proper thread_ts?

**Comment by srajiang** [comment]
Hi @abadd00d - thanks for writing in!
It would really be nice if [`reaction_added`](https://api.slack.com/events/reaction_added) would return the `thread_ts` along with `ts`. I've put that feedback in to the team to see if that's a field that can be included in the event payload.  

For now, a workaround you could use is to call the [`conversations.replies`](https://api.slack.com/methods/conversations.replies) method supplying the`ts` returned from the `reaction_added`. From there you can get the `thread_ts` for the message. 

If that helps, feel free to close this message out!

**Comment by abadd00d** [comment]
Thank you! It works.

My code:

```
...
from slack_sdk import WebClient

...

@app.event("reaction_added")
def reply_to_emoji(event, say, client: WebClient):
    thread = event["item"]["ts"]
    channel = event["item"]["channel"]

    if event["reaction"] == "harold_thumb":
      response = client.conversations_replies(ts=thread, channel=channel)

      if 'thread_ts' in response['messages'][0]:
        thread = response['messages'][0]['thread_ts']
      text = f"Boom!"
      say(text=text, thread_ts=thread)
```
