### ISSUE TITLE
How can I get the "display name" of the user through message event?

### ISSUE THREAD

**Issue by YAMLcase** [slackapi/bolt-python#467]
I'm trying to get the username or "display name" from a message my slack bot is listening to.  Here's a snippet:

```python

app = App(token=options["SLACK_BOT_TOKEN"])

handler = SocketModeHandler(app)
handler.app_token = options["SLACK_APP_TOKEN"]
handler.connect()

...

@app.event({"type": "message"})
def event_listener(body, say: Say, client):
    print("this is where I'd like to print the username of who sent the message")
```

`body` only gives user_id and I'm not familiar enough with bolt to know what other objects I can bring in.  Thanks!

**Comment by srajiang** [comment]
@YAMLcase - Hey there! Thanks for writing in.

If you're trying to just reference the user and have their actual name show up in for example a followup message, you can directly reference the `user` that's return in the message payload (typically starts with a `U`) using the following  format. 

```python
@app.message("ping")
def event_listener(message, say):
    say(f"Hey <@{message['user']}>, pong!")
```


When this gets sent back to Slack, Slack will known to turn that value into the user's display name in your message.


<img width="354" alt="Screen Shot 2021-09-16 at 4 08 39 PM" src="https://user-images.githubusercontent.com/55667998/133696818-bb3528c5-bcc2-4e58-bbfe-fcdaa194c122.png">

If you want to know exactly what the username is at the point in time where your code is printing, you can call the [users.info](https://api.slack.com/methods/users.info) method which returns the users name. Note: You'll have to have the required scopes listed. 

If this was helpful, feel free to give this issue a close.

**Comment by YAMLcase** [comment]
I need the username for external logging.  When I add that scope will the user's name key just show up? Or is there a different object I need to reference?

**Comment by srajiang** [comment]
@YAMLcase - Sure, in that case you'll need to make that separate call to users.info and get the return value of that call. You can do this via the `client` which is an available argument on all listeners. It could look something like this: 

```python
@app.message("ping")
def event_listener(message, say, client):
    user_info = client.users_info(user=message['user'])
    print(user_info)
```

**Comment by seratch** [comment]
@YAMLcase Let us know if you need more help here 👋

**Comment by YAMLcase** [comment]
This did the trick.  Thank you!
