### ISSUE TITLE
issues in making HTML body and redirects in custom success handlers

### ISSUE THREAD

**Issue by akshatd** [slackapi/bolt-python#471]
I am trying to replicate the success handler after the oauth flow in my program so i can add some custom logic there and still be able to make it look like the default

I took the example from [here](https://slack.dev/bolt-python/concepts#authenticating-oauth) in the customizing section that follows.

I can see that the default success handler is being created by the `CallbackResponseBuilder` class, in `_build_callback_success_response`

I tried to put a breakpoint to inspect the body there, but when i put the breakpoint in that file, it never reaches it, so no luck there.

I tried to copy the HTML from the webpage like so, but it still doesnt work, just displays the text as-is

```
def slack_oauth_success(args: SuccessArgs) -> BoltResponse:
    assert args.request is not None
    # do stuff here
    response =  BoltResponse(
        status=200,  # you can redirect users too
        body="<h2>Thank you!</h2><p>Redirecting to the Slack App... click <a href='slack://app?team=asdf&amp;id=asdf'>here</a>. If you use the browser version of Slack, click <a href='https://app.slack.com/client/asdf' target='_blank'>this link</a> instead.</p>"
    )
    return response
```

would really like to know how to set up the header and body so that the web page is displayed nicely and it redirects to open the link in the desktop application, given that it is mentioned in the comment that a redirect is possible

**Comment by srajiang** [comment]
Hey @akshatd - Would something like this work for you??

```python
import os
from slack_bolt import App
from slack_bolt.oauth.oauth_settings import OAuthSettings
from slack_sdk.oauth.installation_store import FileInstallationStore
from slack_sdk.oauth.state_store import FileOAuthStateStore

from slack_bolt.oauth.callback_options import CallbackOptions, SuccessArgs, FailureArgs
from slack_bolt.response import BoltResponse

def build_custom_html_success() -> str:
    return f"""<html>
<head>
<meta http-equiv="refresh" content="0; url='https://www.example.com'" />
<link rel="icon" href="data:,">
<style>
body {{
  padding: 10px 15px;
  font-family: verdana;
  text-align: center;
}}
</style>
</head>
<body>
<h2>Thank you!</h2><p>Redirecting to the Slack App... click <a href='slack://app?team=asdf&amp;id=asdf'>here</a>. If you use the browser version of Slack, click <a href='https://app.slack.com/client/asdf' target='_blank'>this link</a> instead.</p>
</body>
</html>
"""

def build_custom_html_failure() -> str:
    return f"""<html>
<head>
<meta http-equiv="refresh" content="0; url='https://www.example.com'" />
<link rel="icon" href="data:,">
<style>
body {{
  padding: 10px 15px;
  font-family: verdana;
  text-align: center;
}}
</style>
</head>
<body>
<h2>Oops! Something went wrong</h2>
</body>
</html>
"""

def success(args: SuccessArgs) -> BoltResponse:
    assert args.request is not None
    # do your custom logic here!
    html=build_custom_html_success()
    return BoltResponse(
        status=200,
        headers={
            "Content-Type": "text/html; charset=utf-8",
        },
        body=html,
    )

def failure(args: FailureArgs) -> BoltResponse:
    assert args.request is not None
    assert args.reason is not None
    html=build_custom_html_failure()
    return BoltResponse(
        status=200,
        headers={
            "Content-Type": "text/html; charset=utf-8",
        },
        body=html,
    )

callback_options = CallbackOptions(success=success, failure=failure)


# Initializes your app with your bot token and signing secret
oauth_settings = OAuthSettings(
    client_id=os.environ.get("SLACK_CLIENT_ID"),
    client_secret=os.environ.get("SLACK_CLIENT_SECRET"),
    scopes=["chat:write"],
    installation_store=FileInstallationStore(base_dir="./data"),
    state_store=FileOAuthStateStore(expiration_seconds=600, base_dir="./data"),
    callback_options=callback_options,
)

app = App(
    signing_secret=os.environ["SLACK_SIGNING_SECRET"],
    oauth_settings=oauth_settings
)

# Start your app
if __name__ == "__main__":
    app.start(port=int(os.environ.get("PORT", 3000)))
```

**Comment by srajiang** [comment]
One issue with the above that we're handling the redirect_url in the`meta` tag ourselves. Depending on your apps install use case that may be a limitation for you. The full logic for the redirect url handling can be found in the [here](https://github.com/slackapi/python-slack-sdk/blob/main/slack_sdk/oauth/redirect_uri_page_renderer/__init__.py). I will doublecheck whether there are any other workarounds we can suggest.

**Comment by srajiang** [comment]
Just following up here, after double-checking, best option for you here would be to use the custom callback options as you've done and handle the html response / redirects yourself. The code sample above should be helpful in getting started!

**Comment by seratch** [comment]
Hey @akshatd, were @srajiang's comments helpful to you? Let us know if you need more help here 👋 If we don't hear back for a few days, we will close this issue.

**Comment by akshatd** [comment]
Hi @srajiang thank you for the help! this worked for my use case.
Really appreciate it :)
