### ISSUE TITLE
Need help in setting the oAuth Flow for installing the app using the URL from manage distributions

### ISSUE THREAD

**Issue by mohan-raheja** [slackapi/bolt-python#473]
I have followed the approach given in the github docs https://github.com/slackapi/bolt-python/blob/4e0709f0578080833f9aeab984a778be81a30178/examples/django/oauth_app/slack_listeners.py

My redirect URL hitting the end point but after passing the request to the oauth handler, I am getting Not Found message "{"message": "Not Found: /slack/oauth", "status_code": 404, "request": "<WSGIRequest: GET. ,,."}

### Reproducible in:

slack-bolt==1.9.1
slack-bot==0.0.7
slack-sdk==3.11.1
slackclient==1.3.1
#### Python runtime version
python3.9.1
(Paste the output of `python --version`)

#### OS info
macOs
(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1.
2.
3.

### Expected result:
Adding app to the workspace
(Tell what you expected to happen)

**Comment by srajiang** [comment]
Hi @mohan-raheja - The default redirect_uri_path is `/slack/oauth_redirect`. I noticed the error you included says `/slack/oauth`. Have you set a custom redirect uri path for your installation flow?

**Comment by mohan-raheja** [comment]
I have set a redirect URL under oAuth & Permissions in the dashboard as https://cbd3......./.ngrok.io/slack/oauth
and in the url path I maintained it as path("slack/oauth, slack_oauth_handler, name="oauth")

**Comment by seratch** [comment]
@mohan-raheja Can you make sure if you've configured the Django URL routing correctly? Here is the example using the default path: https://github.com/slackapi/bolt-python/blob/4e0709f0578080833f9aeab984a778be81a30178/examples/django/oauth_app/urls.py#L24

**Comment by mohan-raheja** [comment]
Hi @seratch, thank you for your response.
I have changed the URL as you have mentioned above. Now I am getting the browser not supported error
Oops, Something Went Wrong!
Please try again from here or contact the app owner (reason: invalid_browser)

I have set the https url in app configuration

**Comment by seratch** [comment]
@mohan-raheja Please read the document section about the OAuth flow implementation: https://slack.dev/bolt-python/concepts#authenticating-oauth

The reason of the error here is that your OAuth flow is missing a valid `state` parameter. As mentioned in the document, initiate your app's OAuth flow from `/slack/install` URL to have a valid state parameter in your app's OAuth flow. It's also possible to disable the validation (`oauth_settings.state_validation_enabled = False`). However, having the state parameter is crucial for security (see [the RFC section](https://datatracker.ietf.org/doc/html/rfc6749#section-10.12) for details). We highly recommend going with the default settings.

With this, your app should work. If you encounter more errors, I would recommend checking the difference between your app and the example Django app and check the document again. Good luck!

**Comment by mohan-raheja** [comment]
Hi @seratch @srajiang , thank you for your help. I am able to setup the oAuth Flow. we can close this issue.
