### ISSUE TITLE
auth.test API call result is unexpectedly None

### ISSUE THREAD

**Issue by RachelDong** [slackapi/bolt-python#474]
Hello,

I created an app and made it publicly distributed, here is my code:

```python
import os
from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler

from slack_bolt.oauth.oauth_settings import OAuthSettings

app = App(
    signing_secret="...",
    oauth_settings=OAuthSettings(
        client_id="...",
        client_secret="...",
        scopes=["chat:write","channels:history","groups:history","im:history","mpim:history"],
    ),
)


# Listens to incoming messages that contain "hello"
@app.message("hello")
def message_hello(message, say):
    # say() sends a message to the channel where the event was triggered
    say(
        blocks=[
            {
                "type": "section",
                "text": {"type": "mrkdwn", "text": f"Hey there <@{message['user']}>!"},
                "accessory": {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "Click Me"},
                    "action_id": "button_click"
                }
            }
        ],
        text=f"Hey there <@{message['user']}>!"
    )

@app.action("button_click")
def action_button_click(body, ack, say):
    # Acknowledge the action
    ack()
    say(f"<@{body['user']['id']}> clicked the button")

# Start your app
if __name__ == "__main__":
    SocketModeHandler(app, "xapp-...").connect()
    app.start()
```
But when I send "hello" to the app (either in the workspace where the app is created, or another workspace where the app is installed), the terminal throws the error:
```
auth.test API call result is unexpectedly None
```
I have no idea why I got this issue, is there anything wrong with my code? Thanks in advance.

**Comment by seratch** [comment]
Hi @RachelDong, thanks for asking the question!

The situation is that your `InstallationStore` did not return a valid installation information for an incoming request even though the request came from Slack (= the app is installed into the workspace for sure). Refer to the following source code if you want to learn how it works:

* https://github.com/slackapi/bolt-python/blob/v1.9.1/slack_bolt/middleware/authorization/multi_teams_authorization.py#L55-L72
* https://github.com/slackapi/bolt-python/blob/v1.9.1/slack_bolt/authorization/authorize.py#L98

The possible causes are:
* You've installed the app from the "Install to Workspace" button in the api.slack.com/apps/{your app id} and haven't run the OAuth flow with the workspace.
* You've installed the app through the OAuth flow but your installation store didn't save (or lost) the installation data.

Thus, I would recommend running the OAuth flow from `https://{your public domain}/slack/install` (again) and see if there is a difference. I hope this helps!

**Comment by RachelDong** [comment]
Hi @seratch ! Thank you for the reply. That really helps a lot:)
