### ISSUE TITLE
Not able to redirect command to function (404 error)

### ISSUE THREAD

**Issue by MathieuFavreau** [slackapi/bolt-python#475]
#### The `slack_bolt` version
slack-bolt==1.9.1
slack-sdk==3.11.2

#### Python runtime version
Python 3.6.9

#### OS info
Ubuntu 18.04.6 LTS
#166-Ubuntu SMP Fri Sep 17 19:37:52 UTC 2021

#### Steps to reproduce:
I'm not able to get my command to call my python function.
I looked at multiple examples and github issues, without success.
Please guide me in what I'm doing wrong.

Here is my python script:
```
import os
from flask import Flask
from slack_sdk import WebClient
from slack_bolt import App

app = Flask(__name__)

client = WebClient(token=os.environ.get("SLACK_BOT_TOKEN"))
bolt_app = App(token=os.environ.get("SLACK_BOT_TOKEN"), signing_secret=os.environ.get("SLACK_SIGNING_SECRET"))

@bolt_app.command("/sky")
def command(say, ack): 
  ack()
  say(text="sky")

if __name__ == '__main__':
  app.run(host='127.0.0.1', port=5000, debug=True)
```

And the command I set on my app:

![sky_command](https://user-images.githubusercontent.com/29899133/134817881-95a0a44c-4325-44f5-a38a-fa2cd7aa8e1b.jpg)

And the result I get:

![Screenshot from 2021-09-26 13-32-37](https://user-images.githubusercontent.com/29899133/134817955-9fb2f389-3dfa-44bc-8e5d-e825ae5569e7.png)

### Expected result:

I would expect my function to get called.
I was able to make it work without the **slack bolt** sdk prior to this, but I wanted to migrate to bolt as it looks very user friendly.

### Actual result:

It can't find the `/sky` path for some reason.
I tried to root directly to `/sky` and many other combinations, in vain.

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by MathieuFavreau** [comment]
I found the issue I didn't use `bolt_app`... I tried too many tutorials today

**Comment by seratch** [comment]
Hey @MathieuFavreau, checking the following resources may help. Good luck!

* https://github.com/slackapi/bolt-python/tree/main/examples/flask
* https://slack.dev/bolt-python/concepts#adapters

**Comment by MathieuFavreau** [comment]
I followed this tutorial which was wrong, https://python.plainenglish.io/lets-create-a-slackbot-cause-why-not-2972474bf5c1
