### ISSUE TITLE
Any way to persist user modal form selections after submit?

### ISSUE THREAD

**Issue by daneasterman** [slackapi/bolt-python#478]
### What I am trying to achieve:

I've been struggling for a while to figure out how to persist a user's form selection using Slack's modal "surface". In other words, once they have clicked submit, and return to the modal form, their selections are not saved by default.

In my example I have some radio buttons with a multi select menu:

<img width="509" alt="Screenshot 2021-09-27 at 11 10 37" src="https://user-images.githubusercontent.com/4712052/134889466-fbf1abdf-ec30-45a1-86f8-68ae0782b027.png">

### What I tried:

I'm coding only in Python, and using the Python Bolt SDK so have been using these docs primarily: https://slack.dev/bolt-python/concepts. 

I thought the **"Updating and pushing views** section in the docs might help me solve this problem - by passing in the value selected by the user to the `initial_option` json object. But I'm getting an error (with no detail / explanation) when trying to use the `@app.view`decorator` for modal submissions to update the modal. So, I don't think this the right approach, and I may be grasping at straws here to assume that updating the modal will solve my persistence problem.

I've also tried googling to see if anyone else is trying to solve a similar problem, even across different programming languages like Javascript but could not find anything relevant.

Many thanks in advance for your help!

**Comment by misscoded** [comment]
Hi @daneasterman! You're correct in that the values will not automatically persist on their own. 

In the case you've described above, upon submission, you're going to want to first save the values that the user has selected somewhere. When the view is re-opened at a later time, you'll pre-populate the elements with those saved values (your intuition about `initial_option` was correct, but the setting of these values will occur when the modal is opened via `views_open()` and presented to the user the subsequent times).

The blocks belonging to the view you've attached in the screenshot would roughly look like the following:

```
"blocks": [
    {
        "type": "section",
        "text": {
            "type": "mrkdwn",
            "text": "*Switch your real-time notifications off or on:*"
        },
        "accessory": {
            "type": "radio_buttons",
            "options": [
                {
                    "text": {
                        "type": "plain_text",
                        "text": "Off",
                        "emoji": True
                    },
                    "value": "off"
                },
                {
                    "text": {
                        "type": "plain_text",
                        "text": "On",
                        "emoji": True
                    },
                    "value": "on"
                }
            ],
            "initial_option": {
                "text": {
                    "type": "plain_text",
                    "text": "On",
                    "emoji": True
                },
                "value": "on"
            },
            "action_id": "radio_buttons-notifications"
        }
    },
    {
        "type": "input",
        "element": {
            "type": "plain_text_input",
            "action_id": "plain_text_input-stocks",
            "initial_value": "This is a pre-populated user input value!"
        },
        "label": {
            "type": "plain_text",
            "text": "Select your stocks to receive real-time filing notifications:",
            "emoji": True
        }
    }
  ]
```

From the above snippet, you can see that `radio_buttons` includes an `initial_option` key that is set to the same `option` object that the user previously selected. For a `plain_text_input`, `initial_value` is similarly set to the text value the user previously entered. I've hard-coded these pre-populated values for the sake of brevity, but you would need to set these to either use the value previously saved or a blank/default value if the user has no saved preferences.

Additional details about both of these block elements (and more!) can be found [here](https://api.slack.com/reference/block-kit/block-elements).

Let us know if that resolves the issue! 🙂

**Comment by daneasterman** [comment]
Hey @misscoded yep that is really useful and solves the problem. Thanks v. much!

**Comment by daneasterman** [comment]
Just to confirm @misscoded - this means setting up my own external database outside of Slack and saving the user's values to that?

**Comment by misscoded** [comment]
Yep! For development and quick testing purposes as you work out the functionality, you can always use an object in the global scope to save and pull records from, but beyond that, a proper database is the way to go to ensure persistence.
