### ISSUE TITLE
View sometimes failing to update

### ISSUE THREAD

**Issue by naruhodou** [slackapi/bolt-python#481]
I am working with modal and I am using the following steps in order to implement it.
Initial view: creating initial view
```
@app.view('handle-submit')
def func(ack, body, client, view, logger):
    ack({"response_action": "clear"})
    # creating a new view
    sleep(10);
    # updating the view
```
doing above sometimes doesn't open that new view after clearing stack or it doesn't update the view. I get the response that the view payload was successfully made but it doesn't come on the channel where it is supposed to come. Is this a bug from slack? Or am I doing anything wrong?
Thanks

**Comment by seratch** [comment]
Hi @naruhodou, thanks for writing in!

>I get the response that the view payload was successfully made but it doesn't come on the channel where it is supposed to come.

Opening a new modal in response to view_submission request is not recommended. As the `views.open` API method does not know if there are already existing modal view, the call itself may succeed in some situations but it's not guaranteed to work properly. At least, it does not work with mobile clients.

`ack({"response_action": "clear"})` means that your app closes all the modal views with the user. If your app still continues communicating with the user using a modal in the scenario, you can use `ack({"response_action": "update", view: buildLoadingView() })` first, and then call `views.update` API to show the next state of the view a few seconds later.

I hope this helps!

**Comment by naruhodou** [comment]
Thanks for the response. Very well explained.
