### ISSUE TITLE
Passing data as arguments to the slack action listeners invoked by block elements

### ISSUE THREAD

**Issue by mohan-raheja** [slackapi/bolt-python#485]
In my app I have configured the slack interaction using the button click, on clicking the button I am calling the corresponding listener(identified by action_id mentioned in the button). In the listener I am getting the block_actions payload which contains all the state values of the event, but in addition to that I want to send some values as arguments to the listener function. Is it possible in any way that we can send arguments to the listeners
```

@app.action("change_time_period")
def handle_change_time_period(ack, context, body, client, logger, message, say):
   # want the arguments here such as passing email_id from post_data

def post_data(user_id, email_id):
    client = WebClient(token=os.environ.get("SLACK_BOT_TOKEN"))
    result = client.chat_postMessage(
        channel=user_id,
        `blocks=[`

            {
                "type": "actions",
                "elements": [
                    {
                        "type": "button",
                        "text": {
                            "type": "plain_text",
                            "emoji": True,
                            "text": "Change time period"
                        },
                        "style": "primary",
                        "value": "time_period",
                        "action_id": "change_time_period"
                    }
                ]
            }
        ]

    )

```

In the code above, I will be calling the post_data which will post the message containing the block kit, once the user clicks the button the handle_change_time_period will be called.

My scenario requires to maintain some state such as the value picked in an action should be maintained in the subsequent flow of interaction. Is there a way I can achieve this?

**Comment by seratch** [comment]
Hi @mohan-raheja, thanks for writing in! 

The only parts of the payload that you can use in the scenario would be the string values in `elements[].action_id` and `elements[].value`. If you go with action_id, you can have suffix like `change_time_period_SOME_VALUE_HERE` and use regular expression to match in your `@app.action` listener. However, perhaps the most straight-forward way would be to embed the value that you would like to pass in the `value` property in a block element.

>My scenario requires to maintain some state such as the value picked in an action should be maintained in the subsequent flow of interaction. Is there a way I can achieve this?

To do this, you can update the message when a user clicks a button in it. For a publicly visible messages (= in_channel ones), you can use `chat.update` API method to replace the data in `blocks`. For ephemeral messages, you can use `respond` to post an ephemeral message and use `respond(replace_original=True)` to update it when receiving a block_actions request.

I hope this helps.

**Comment by seratch** [comment]
👋 @mohan-raheja  Let us know if you need more help here! If we don't hear back for a few more days, we'll close this issue.

**Comment by seratch** [comment]
Let us close this issue now but please feel free to write in whenever you have anything further to ask/discuss here 👋
