### ISSUE TITLE
Would it be possible to get the payloads without using decorators?

### ISSUE THREAD

**Issue by rcsrao** [slackapi/bolt-python#493]
Hello Team,

Would it be possible to get the all payloads without using decorators(@app.event(event_type)) once we make the connection?

app = App(token="xoxb-******")
SocketModeHandler(app, "xapp-*******").start()

**Comment by mwbrooks** [comment]
Hi @rcsrao,

You should be able to use [Global middleware](https://slack.dev/bolt-python/concepts#global-middleware) to receive all payloads and decide what to do with each request.

Let me know how that goes! And thanks for using Bolt Python 🙂

**Comment by seratch** [comment]
@rcsrao Let us know if @mwbrooks's comment was helpful to you 👋

**Comment by seratch** [comment]
👋 Let us close this issue due to inactivity but please feel free to write in whenever you have anything further to ask/discuss regarding this topic!
