### ISSUE TITLE
External multi-select menu: Is there a way to ack request and update response later?

### ISSUE THREAD

**Issue by prziborowski** [slackapi/bolt-python#501]
My external menu request might exceed 3 seconds to load all the results, so I'd like to acknowledge the request and populate the items later.

### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version

slack-bolt==1.9.1
slack-sdk==3.10.1
#### Python runtime version

Python 3.8.10

#### OS info

`#36~20.04.1-Ubuntu SMP Fri Aug 27 08:06:32 UTC 2021`

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))
Similar steps as issue #468 with slightly modified script (sleep statement).
Because of the sleep statement the ack with results doesn't return to the user.
Also it seems like if the user tries to type another message (add or remove characters), slack doesn't send my app the message as if my app is temporarily blacklisted because it didn't acknowledge in time.
```python
#!/usr/bin/env python3
import json
import os
import tempfile
import time

from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler

bot_token = os.environ['BOT_TOKEN']
app = App(token=bot_token)
count = 0


@app.shortcut('test-open')
def test_open(ack, shortcut, client):
    ack()
    client.views_open(
        trigger_id=shortcut['trigger_id'],
        view={
            'type': 'modal',
            'callback_id': 'view-response',
            'title': {'type': 'plain_text', 'text': 'Test update'},
            'close': {'type': 'plain_text', 'text': 'Close'},
            'submit': {'type': 'plain_text', 'text': 'Send'},
            'blocks': [
                {
                    'type': 'section',
                    'block_id': 'test-section',
                    'text': {
                        'type': 'plain_text',
                        'text': 'Enter something'
                    },
                    'accessory': {
                        'action_id': 'action',
                        'type': 'multi_external_select',
                        'placeholder': {
                            'type': 'plain_text',
                            'text': 'Type something'
                        },
                        'min_query_length': 1
                    }
                }
            ],
        }
    )


@app.options('action')
def handle_options(ack, body):
    opts = []
    for i in range(3):
        opts.append({
            'text': {
                'type': 'plain_text',
                'text': f'Sample {i}'
            },
            'value': f'sample-{i}'
        })
    time.sleep(3)
    ack(options=opts)


if __name__ == '__main__':
    handler = SocketModeHandler(app, os.environ["APP_TOKEN"])
    handler.start()
```

### Expected result:

I'd like a way to do an `ack()` at the beginning of handle_options to avoid the 3 second limit, and then be able to do an ack with an update at the end.

What I tried:
ack with a single response (e.g. "Loading..."). Followed with another ack with more results. First response shows, 2nd does not. Also tried with a response_type="update" in hopes that would update the results.

ack with no response, followed with another ack with more results. This just has #468 behavior.

Also I'd be happy to be able to send a partial list first, perhaps something cached, followed with more items later (based on external queries).

### Actual result:

Not able to send a second update with results. Not able to send the results in time, which seems to mean user gets no feedback.

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @prziborowski, thanks for writing in! 

>I'd like a way to do an ack() at the beginning of handle_options to avoid the 3 second limit, and then be able to do an ack with an update at the end.

Unfortunately, as long as you use external-select block for this use case, there is no way to do this. The only approach that I can suggest is to optimize your backend's performance in some way (e.g., scaling up the server, having cache for common queries) to always return results within 3 seconds.

An alternative way is to ask your end-users to input keyword and "Submit" button at the bottom of your app's modal. With this way, your app can show "Loading..." view first. And then, once the search results are ready, your app can perform `views.update` API method to display the search results in the same modal. Here is [an example app](https://github.com/seratch/deepl-for-slack#shortcut-to-run-deepl-translate-api) demonstrating how it works. To build select menu, you can use either static-select or external-select along with the search result items. 

The UI design with this way is far different from the one you wanted to build. But this is the most common approach to display search results that require a few seconds to collect.

I know that these might not be your desired solutions but I hope this was helpful to you.
