### ISSUE TITLE
When I run the default app example I get an undocumented error/warning

### ISSUE THREAD

**Issue by peterlharding** [slackapi/bolt-python#502]
When I run the app I get the message:

As `installation_store` or `authorize` has been used, `token` (or SLACK_BOT_TOKEN env variable) will be ignored.

### Reproducible in:

```
 % cat ./app.py
#!/usr/bin/env python3
"""
App ID - A02JY6S8JMS
"""

import os

from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler

SLACK_BOT_TOKEN = 'xoxb-***'
SLACK_APP_TOKEN = 'xapp-1-***'

# token=os.environ.get("SLACK_BOT_TOKEN")
bot_token = SLACK_BOT_TOKEN
app_token = SLACK_APP_TOKEN

app = App(token=bot_token)

@app.message("hello")
def message_hello(message, say):
    # say() sends a message to the channel where the event was triggered
    say(f"Hey there <@{message['user']}>!")

if __name__ == "__main__":
    SocketModeHandler(app, SLACK_APP_TOKEN).start()


% ./app.py 
As `installation_store` or `authorize` has been used, `token` (or SLACK_BOT_TOKEN env variable) will be ignored.
⚡️ Bolt app is running!

```

#### The `slack_bolt` version

(Paste the output of `pip freeze | grep slack`)

#### Python runtime version

(Paste the output of `python --version`)

#### OS info

(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)

#### Steps to reproduce:

See above

### Expected result:

Expected to be able to get response from SlackBot channel linked to the App

### Actual result:

No response seen in Slack.  I have not been able to find any information about this message and suspect that it is not using the token I provided to connect to the Slack App I specified.

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

Regards,
Peter Harding
peter.harding@latitudefinancial.com

**Comment by bendjango** [comment]
Just had the same experience. Experimented with Oauth, then deleted that code and couldn't figure out why I kept getting the error. It's been a year but I don't see the Slack OAuth docs say explicitly that it checks for the ENV variables to decide to implement Oauth without you.
