### ISSUE TITLE
delete action_button_click(body, ack, say) in Japanese on docs/_tutorials/ja_getting_started.md .

### ISSUE THREAD

**Issue by TORIFUKUKaiou** [slackapi/bolt-python#505]
delete action_button_click(body, ack, say) in Japanese on docs/_tutorials/ja_getting_started.md .
The document of getting_started.md has not already been implemented action_button_click at this time.

### The page URLs

* https://slack.dev/bolt-python/ja-jp/tutorial/getting-started

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @TORIFUKUKaiou, thank you for taking the time to report this issue. And you're right. The part https://github.com/slackapi/bolt-python/blame/v1.9.4/docs/_tutorials/ja_getting_started.md#L231-L236 should be removed. If you don't mind use your time a little more, your pull request for fixing this would be appreciated.
