### ISSUE TITLE
app-level (xapp) token can be gotton from the Basic Information page, but docs/_tutorials/ja_getting_started.md has wrong.

### ISSUE THREAD

**Issue by TORIFUKUKaiou** [slackapi/bolt-python#506]
(Describe your issue and goal here)
app-level (xapp) token can be gotton from the Basic Information page, but docs/_tutorials/ja_getting_started.md has wrong.
I'd like to fix it.
https://github.com/slackapi/bolt-python/blob/e112c7e75f743b2cef619946903237a4f526ce23/docs/_tutorials/ja_getting_started.md?plain=1#L98
typo(?) OAuth & Permissions ページ => Basic Information page

### The page URLs

* https://slack.dev/bolt-python/ja-jp/tutorial/getting-started

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
@TORIFUKUKaiou Thanks for pointing this out! You're right here. I'm happy to be a reviewer of your PR 🙌

**Comment by TORIFUKUKaiou** [comment]
Great!
I see to update v1.9.3 -> v1.9.4 on https://slack.dev/bolt-python/ja-jp/tutorial/getting-started.
:rocket::rocket::rocket:

**Comment by seratch** [comment]
Thanks a lot for your contributions!
