### ISSUE TITLE
HTML escapes and actions

### ISSUE THREAD

**Issue by ahnolds** [slackapi/bolt-python#513]
When getting the body of a message in response to a user interaction (e.g. a button press), the `&`, `<`, and `>` characters are HTML escaped (that is, replaced with `&amp;`, `&lt;`, and `&gt;` respectively). As far as I can tell, this isn't documented anywhere, so I don't actually know if this is the expected behavior or not.

### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version

slack-bolt==1.9.1
slack-sdk==3.11.2

#### Python runtime version

Python 3.8.10

#### OS info

`#94-Ubuntu SMP Thu Aug 26 20:27:37 UTC 2021`

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1. Submit a message (using `client.chat_postMessage`) that contains buttons and & characters, for example the following set of blocks:
```json
[
  {
    "text":{
      "text":"*Question*",
      "type":"mrkdwn"
    },
    "type":"section"
  },
  {
    "elements":[
      {
        "action_id":"choice_1",
        "text":{
          "text":"Answer & 1",
          "type":"plain_text"
        },
        "type":"button"
      },
      {
        "action_id":"choice_2",
        "text":{
          "text":"Answer > 2",
          "type":"plain_text"
        },
        "type":"button"
      }
    ],
    "type":"actions"
  }
]
```
2. Click on the first button
3. The body of the response looks like (mildly simplified/redacted):
```json
{
  "actions":[
    {
      "action_id":"choice_1",
      "action_ts":"1635890917.489813",
      "block_id":"SSxj",
      "text":{
        "emoji":true,
        "text":"Answer &amp; 1",
        "type":"plain_text"
      },
      "type":"button"
    }
  ],
  "api_app_id":"REDACTED",
  "channel":{
    "id":"REDACTED",
    "name":"redacted"
  },
  "container":{
    "channel_id":"REDACTED",
    "is_ephemeral":false,
    "message_ts":"1635890867.000100",
    "type":"message"
  },
  "enterprise":"None",
  "is_enterprise_install":false,
  "message":{
    "blocks":[
      {
        "block_id":"soKPS",
        "text":{
          "text":"*Question*",
          "type":"mrkdwn",
          "verbatim":false
        },
        "type":"section"
      },
      {
        "block_id":"SSxj",
        "elements":[
          {
            "action_id":"choice_1",
            "text":{
              "emoji":true,
              "text":"Answer ""&amp; ""1",
              "type":"plain_text"
            },
            "type":"button"
          },
          {
            "action_id":"choice_2",
            "text":{
              "emoji":true,
              "text":"Answer ""&gt; ""2",
              "type":"plain_text"
            },
            "type":"button"
          }
        ],
        "type":"actions"
      }
    ],
    "bot_id":"REDACTED",
    "team":"REDACTED",
    "text":"Question",
    "ts":"1635890867.000100",
    "type":"message",
    "user":"REDACTED"
  },
  "response_url":"https://hooks.slack.com/actions/REDACTED/REDACTED/REDACTED",
  "state":{
    "values":{
      
    }
  },
  "team":{
    "domain":"redacted",
    "id":"REDACTED"
  },
  "token":"REDACTED",
  "trigger_id":"REDACTED",
  "type":"block_actions",
  "user":{
    "id":"REDACTED",
    "name":"redacted",
    "team_id":"REDACTED",
    "username":"redacted"
  }
}
```

### Expected result:

The `&` and `>` characters should appear in the body rather than the HTML escapes. Or, alternatively, there should be some documentation of when/where these escapes will happen.

### Actual result:

The html escape replacements appear in the body.

**Comment by srajiang** [comment]
Hi @ahnolds - Thanks for bringing this up. I'm going to verify whether this is a bug or intended behavior and update you on what I find.

**Comment by srajiang** [comment]
@ahnolds 👋 
So, back to confirm that this is intended behavior. It's a byproduct of Block Kit input sanitization done on the backend for validation purposes. It's not super well-documented, I agree. I've given that feedback internally.

Something I was able to find which may be useful to you is the [`verbatim` property ](https://api.slack.com/reference/block-kit/composition-objects#text) which can be set as true for `mrkdwn` and will skip the pre-processing. For `plain_text` elements, unfortunately there isn't a similar field - the pre-processing is run when `emoji = true` though, so depending on your use case you might try playing around with those fields.

**Comment by ahnolds** [comment]
👍 Thanks for the information, and especially for the timely responses! I think for my purposes the easiest thing to do is just to manually handle the unescaping with `html.unescape`, so no need to mess around with `verbatim` or `emoji` or other properties. Just would be awesome to have it documented for the future, and as you say, you've already given that feedback, so nothing more to do on this ticket.
