### ISSUE TITLE
Event to listen for edited message?

### ISSUE THREAD

**Issue by YAMLcase** [slackapi/bolt-python#517]
Is there an event to listen to an edited message in the channel?  For instance, if my bot listens for `!help` but I accidentally type `help`.

I would like to hit the up arrow in slack edit the message to `!help` and have the slack app take this as an event.

Thanks!

**Comment by eddyg** [comment]
Yep. You will get a `message` event with a [message_changed](https://api.slack.com/events/message/message_changed) subtype.

**Comment by YAMLcase** [comment]
Thanks @eddyg !

**Comment by eddyg** [comment]
FWIW, you can expand "Filtering on message subtypes" in the [docs](https://slack.dev/bolt-python/concepts#event-listening) for a simple example.

**Comment by filmaj** [comment]
Thanks for the helpful tip, @eddyg! Looks like the question here is squared away, so I will close the issue.
