### ISSUE TITLE
How to know team_id in app_home_opened event listeners

### ISSUE THREAD

**Issue by Cyb-Nikh** [slackapi/bolt-python#520]
Unable to see view in app_home_opened event:

- When someone opens a home tab,  I am fetching the team_id from the Event payload (inside view) to identify the workspace and sending the corresponding home tab but It seems like there is no view section in the Event payload. 

```python
@bolt_app.event("app_home_opened")
def handle_home_tab(client, event, logger):
    print('Event: ', event)
    # get event['view']
```
```bash
Event: {'type': 'app_home_opened', 'user': 'U0*********', 'channel': 'D0*********', 'tab': 'home', 'event_ts': '163*****.*******'},
```

No view is there, what I read is for first time when this event occur since no view was there we didn't get view field but I need team_id to identify that workspace in my backend. Is there any way I can fetch team_id before I publish my home view for the first time

**Comment by seratch** [comment]
Hi @Cyb-Nikh, thanks for writing in! You can use `context.team_id` for it.

**Comment by Cyb-Nikh** [comment]
Hi @seratch Thank you for the response. 

```context.team_id``` is what I was needed. Thanks for the help.

I'm closing it as the issue has been resolved.
