### ISSUE TITLE
Error when implementing lazy listener example with AWS Lambda

### ISSUE THREAD

**Issue by joshight** [slackapi/bolt-python#526]
Testing the example to implement a lazy listener for long running tasks with AWS Lambda. 

Getting an error without stack trace: [ERROR] 2021-11-18T03:10:15.994Z ebb119ae-e4ab-4f61-a609-39e1804c7415 Failed to run an internal function ('text')

### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version: 1

(Paste the output of `pip freeze | grep slack`)

$  pip3 freeze | grep slack
slack==0.0.2
slack-bolt==1.6.1
slack-sdk==3.6.0
slackclient==2.9.3

#### Python runtime version

python 3.9

(Paste the output of `python --version`)

#### OS info

(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)

AWS Lambda

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

Code:
```python
# process_before_response must be True when running on FaaS
APP = App(
    token=SLACK_BOT_TOKEN,
    signing_secret=SLACK_SIGNING_SECRET,
    process_before_response=True)

def respond_to_slack(ack):
    ''' Respond to slack within 3 seconds'''
    ack('trying')

def run_long_process(respond, body):
    ''' Post ack long running process'''
    time.sleep(5)  # longer than 3 seconds
    respond(f"Completed! (task: {body['text']})")


APP.message('help')(
    ack=respond_to_slack,  # responsible for calling `ack()`
    lazy=[run_long_process]  # unable to call `ack()` / can have multiple functions
)
```

### Expected result:

Expect the ack to work and then the long process function to execute after
### Actual result:

Failed to run an internal function ('text')  (No stack trace)

(Tell what actually happened with logs, screenshots)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @joshight, thanks for writing in!

Perhaps, you copied the code from the example for slash command handling. As for the message event handling, the payload data structure is not the same. Instead of `body['text']`, you can use `body['event']['text']`. A safe code would be:

```python
# have event or payload argument here
# refer to https://slack.dev/bolt-python/api-docs/slack_bolt/kwargs_injection/args.html to see the list of available args
def run_long_process(respond, event):
    ''' Post ack long running process'''
    if 'text' in event:
        time.sleep(5)  # longer than 3 seconds
        respond(f"Completed! (task: {event['text']})")
```

I hope this helps! If everything is clear now, would you mind closing this issue?

**Comment by joshight** [comment]
Hi @seratch, thanks for the help. That resolved my issue. Closing it now.
