### ISSUE TITLE
Personalised Slack bot Installation link

### ISSUE THREAD

**Issue by Cyb-Nikh** [slackapi/bolt-python#533]
Is there a way to integrate extra parameters in Slack Installation Oauth Process or if we can make a personalised link. Such that we can identify is this the same user to whom we have shared the app distribution (installation) link.

**Comment by seratch** [comment]
Hi @Cyb-Nikh, thanks for asking the question!

There are two ways to achieve your goal:

* Set values in cookies (= set-cookie headers in response)
* Embed extra values in the `state` parameter when redirecting to authorize URL

In general, I would recommend the first one (=using cookie values to store a user-specific value). With this approach, your `/slack/oauth_redirect` (callback) handler can receive the value via request cookie values.

To take full control of the OAuth flow, you can implement your `OAuthFlow` class:

* Set cookie value in this method: https://slack.dev/bolt-python/api-docs/slack_bolt/oauth/oauth_flow.html#slack_bolt.oauth.oauth_flow.OAuthFlow.handle_installation
* Receive the value here: https://slack.dev/bolt-python/api-docs/slack_bolt/oauth/oauth_flow.html#slack_bolt.oauth.oauth_flow.OAuthFlow.handle_callback

I hope this helps!

**Comment by Cyb-Nikh** [comment]
Hi @seratch, thanks for the reply.

Yes, it would help. The second approach you suggested is the one I tried and it is what I was looking for, though I would definitely try out the first one too.

Thanks one again. As I have my answer, hence, I'm closing this out.
