### ISSUE TITLE
Asynchio & Bolt  General Guidance Questions.

### ISSUE THREAD

**Issue by paulingit** [slackapi/bolt-python#540]
Slack Support suggested that we post these bolt-python specific questions here on Github:
1.Can you clarify the practical benefits of using Python ASYNCIO within Bolt ? Our needs are long term & complex, will ASYNCIO give us better control of Slack Channels and tighter integration with Amazon Lex conversation flows? In general, is the complexity of using ASYNCIO within Bolt worth the effort or is it there purely to accommodate organizations who already have a large investment in existing ASYNCIO code? We're at the very beginning of our Slack integration, so we have no legacy code to worry about. Is ASYNCIO recommended for a brand new project like ours?
2. Is ASYNCIO an "all or nothing" decision? If we use it, does it then preclude us from NOT using it within the same Slack App in other sections of the code?

**Comment by srajiang** [comment]
Hello @paulingit! I am assuming you are referring to `AsyncApp` vs. the regular `App`.

Here are a couple response to your questions:

> Will ASYNCIO give us better control of Slack Channels and tighter integration with Amazon Lex conversation flows?

WIth respect to control over Slack Channels you have access to all the same Slack API methods and functionality with an async app as you would have with a regular app. Perhaps you could elaborate on what kind of control you are looking for. Also, I’m not familiar with Amazon Lex conversation flow so I’m afraid I don’t have a great answer for you there. 

> In general, is the complexity of using ASYNCIO within Bolt worth the effort or is it there purely to accommodate organizations who already have a large investment in existing ASYNCIO code? We’re at the very beginning of our Slack integration, so we have no legacy code to worry about. Is ASYNCIO recommended for a brand new project like ours?

This is probably not the answer you’re looking for, but it really depends on your use case requirements - such as whether you need non-blocking runtime to accomplish your projects goals, as well as your team’s familiarity with async (which can be tricky to work with). 

> is it there purely to accommodate organizations who already have a large investment in existing ASYNCIO code?

Yes, this is an accommodation for app developers who use async

> Is ASYNCIO an “all or nothing” decision? If we use it, does it then preclude us from NOT using it within the same Slack App in other sections of the code

Yes, you cannot mix asyncio based code in app code, so you do need to choose either to use `AsyncApp` or `App` - and you might want to check whether other libraries or frameworks you're intending to use would be compatible with async (many aren't). 

The way you would _design_ a Slack App overall with `AsyncApp` vs. `App`  is the same. You might want to [check out the async examples](https://github.com/slackapi/bolt-python/tree/main/examples) in our repo’s sample apps to get a feel for this.

So what direction to go does boil down a bit to what your application requirements are, whether having an async runtime would be the best fit. Usually if you need async to make your app work, you probably already know it, so if you’re not sure whether you need it, perhaps a good default would be to start working with App and adjust as you prototype / build out.

I hope that this is useful to you - and thanks for considering to use our frameworks as you scope out your build!

**Comment by paulingit** [comment]
Thanks for this feedback on Bolt & asyncio. We're running Slack in Lambda, so it looks like there won't be a performance benefit in running asyncio. As you've clarified that there's no specific feature benefit with asycnio, we'll work without it in our development.

**Comment by srajiang** [comment]
Nice - We'll go ahead and close this out then. If future questions come up, feel free to submit another issue.
