### ISSUE TITLE
FastAPI: passing SQLAlchemy Session through SlackRequestHandler

### ISSUE THREAD

**Issue by kafejo** [slackapi/bolt-python#542]
In the FastAPI documentation they suggest to pass db session in following fashion:
```python
@api.post("/slack/events")
async def endpoint(req: Request, db: Session = Depends(get_db)):
    return await app_handler.handle(req)
```

Is there suggested way to handle this? Couldn't find anything in documentation or examples and can't make it work.

See https://fastapi.tiangolo.com/tutorial/sql-databases/#create-a-dependency

Thanks for your help.

**Comment by seratch** [comment]
Hi @kafejo, thanks for taking the time to write in!

The only solution that I can think of is to enable `context` objects to include the additional values this way: https://github.com/slackapi/bolt-python/pull/544 With the solution, you can pass the `db` object as below:

```python
@api.post("/slack/events")
async def endpoint(req: Request, db: Session = Depends(get_db)):
    return await app_handler.handle(req, {"db": db})
```

Your listeners/middleware can access the "db" data by `context.get("db")` method call.

Let us know if you have any different suggestions for better support of the use case.

**Comment by kafejo** [comment]
Amazing, thanks for the quick response and solution! ❤️
