### ISSUE TITLE
The block action listener example in the Getting Started guide doesn't work with modals / Home tabs

### ISSUE THREAD

**Issue by meekrosoft** [slackapi/bolt-python#550]
I'm trying to follow the getting started tutorial, but can't get the button response to work.

This is the code I'm using:
```
@app.action("l7wM")
def handle_some_action(body, ack, say):
    ack()
    say(f"<@{body['user']['id']}> hhhhhh the button")
```

And when I click the button I get this error:

```
⚡️ Bolt app is running! (development server)
127.0.0.1 - - [20/Dec/2021 17:15:22] "POST /slack/events HTTP/1.1" 200 -
Failed to run listener function (error: say without channel_id here is unsupported)
Traceback (most recent call last):
  File "/Users/mikelong/tmp/merkely/slack-app/.venv/lib/python3.8/site-packages/slack_bolt/listener/thread_runner.py", line 124, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/mikelong/tmp/merkely/slack-app/.venv/lib/python3.8/site-packages/slack_bolt/listener/custom_listener.py", line 49, in run_ack_function
    return self.ack_function(
  File "app.py", line 72, in handle_some_action
    say(f"<@{body['user']['id']}> hhhhhh the button")
  File "/Users/mikelong/tmp/merkely/slack-app/.venv/lib/python3.8/site-packages/slack_bolt/context/say/say.py", line 58, in __call__
    raise ValueError("say without channel_id here is unsupported")
ValueError: say without channel_id here is unsupported
```

I think it looks the same as the example:
https://github.com/slackapi/bolt-python/blob/6df6bba62ba26ac0917472efc3a30240d98eeda6/examples/getting_started/app.py#L36

Am I missing a permission?

**Comment by seratch** [comment]
Hi @meekrosoft, thanks for writing in!

Perhaps, you're reusing the lines of code for modals or Home tabs. In the case, the `say()` method call in `app.action` listener does not work as the error message says.

If you want to post a message in a channel from modals / Home tabs, a recommended way is to embed the channel ID in the button element's value or to have the channel ID in private_metadata in modal view object.

I hope this helps.

**Comment by seratch** [comment]
As I've provided an answer to this question, let us close this issue. If you have any follow-ups, please feel free to write in.
