### ISSUE TITLE
How to create WebClient with user token?

### ISSUE THREAD

**Issue by SamarpanRai-TomTom** [slackapi/bolt-python#551]
I want to use the user token to send DM to respond to DM. 

### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version

(Paste the output of `pip freeze | grep slack`)
slack-bolt==1.11.0
slack-sdk==3.11.2

#### Python runtime version

(Paste the output of `python --version`)
Python 3.8.0

#### OS info

(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)
ProductName:	macOS
ProductVersion:	12.1
BuildVersion:	21C52
Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1. Setup authentication 
2. Install the app
3. User sends a message

### Expected result:

Send DM to user

### Actual result:

Sends a message to the bot

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @SamarpanRai-TomTom, thanks for writing in!

The simplest way would be to instantiate `WebClient` with a user token value.

```python
from slack_sdk import WebClient

# pesudo database
database = Database()

def resolve_user_token(user_id: str) -> Optional[str]:
      return database.find(user_id)

user_id = "W1111111111"
user_token = resolve_user_token(user_id)
client = WebClient(token=resolve_user_token(user_id))
client.chat_postMessage(channel=dm_id, text="Hi!")
```

If your bolt-python implements the OAuth flow with user scopes, plus an incoming request is associated with a user who already installed the app, you can access the user's user token via `context.user_token`:

```python
@app.event("message")
def handle_message_events(context):
    user_token = context.user_token
    if user_token is not None:
        user_token_client = WebClient(user_token)
        user_token_client.chat_postMessage(....)
     else:
         say("Install this app first")
```

I hope this helps.

**Comment by SamarpanRai-TomTom** [comment]
I am using bolt-python OAuth flow but i cannot get access to the user token. How do i get access to `say` when i only use 
```python
@app.event("message")
def handle_message_events(context):
   ...
```

**Comment by seratch** [comment]
@SamarpanRai-TomTom 

> how do I get access to say when I only use

You can add `say` to the listener function's argument list:

```python
@app.event("message")
def handle_message_events(context, say):
   ...
```

> The user_token is None. The app successfully installs but I think the flow is not storing the user token?

If your OAuth flow includes not only scopes but also user_scopes (at least `chat:write` in this case), your `InstallationStore` saves user tokens as well.

**Comment by SamarpanRai-TomTom** [comment]
@seratch 

> You can add say to the listener function's argument list:

Thanks! 

> If your OAuth flow includes not only scopes but also user_scopes (at least chat:write in this case), your InstallationStore saves user tokens as well.

I do have the user_scopes and I inspected the log during the installation process there is `user_token` is available. My problem seems to be something more subtle. Maybe it's best to show what I want to do:

1. User A installs the App so the user token is captured by the app 
2. User B sends a message to User A. 
3.  The Slack app sends a DM to user B on behalf of user A 

The problem occurs in step 3. The library tries to find `context.user_token` for user B and **not** user A. However, user B hasn't installed the application so the token doesn't exist. This means that `context.user_token` is not defined. Therefore, can I force to get the `user_token` of the receiving user i.e, user A?

**Comment by seratch** [comment]
@SamarpanRai-TomTom 
As you've already noticed, the `context.user_token` exists only when an incoming request is associated with a user who installed the app with user scopes.

Thus, in this case, you need to have your own code to fetch user A's user token from your database. The code can be just a utility method and/or a [global middleware](https://slack.dev/bolt-python/concepts#global-middleware).

**Comment by SamarpanRai-TomTom** [comment]
HI @seratch,

Thank you for the suggestion. I want to fetch the user token of the receiving user A but for that, I need to know that the `message` event is meant for user A. I looked into the `event` variable but i didn't find any information about it. 

```python
@app.event("message")
def direct_message(event, say):
    logger.info(event)

    user_id = event["user"]
    text = (
        f"Welcome to the team {user_id}, 🎉 You can introduce yourself in this channel."
    )
    say(text=text, channel=user_id)

```

Can you guide me where I should look?

**Comment by seratch** [comment]
@SamarpanRai-TomTom 
Using `event["user"]` in this scenario looks good to me. For general guidance, there is no simple document about it yet but my reply here https://github.com/slackapi/java-slack-sdk/issues/909#issuecomment-998419043 may be helpful to understand how you can work with Events API payloads.

I've answered your original question here and it seems that everything is clear now. Would you mind closing this issue?

**Comment by samarpan-rai** [comment]
Of course, thank you!
