### ISSUE TITLE
Pass non-slack arguments when using handlers

### ISSUE THREAD

**Issue by tom0010** [slackapi/bolt-python#559]
Looking at https://github.com/slackapi/bolt-python/issues/542 
I'd like to do something similar, I'd like to pass extra args into my function. 
bolt already gives you `body`, `ack` and `logger` as some examples, I'd like to also pass my own ones. 
However, as this is done automatically, I can't pass any args as python then complains about the positional args missing. 
Here is some more context: https://community.slack.com/archives/CHL4CLRCZ/p1640959405021200 
One of the args I'd like to pass is actually an sqlalchemy object. Because after my slack action (button) is clicked, I want to double check my DB to make sure the user has been authed and there is an entry in the DB for said user. Now I have this working already when using a big file, but I'm trying to move away from having huge files, and have it more modular by importing different files using handlers as per @seratch's example (https://community.slack.com/archives/CHL4CLRCZ/p1634250648022400?thread_ts=1633856012.019600&cid=CHL4CLRCZ):
```
# handlers.py
class HiCommand:
    def handle(self, ack, body):
        ack()

    def add_to(app: App):
        app.command("/hi")(self.handle)

# main.py
from handlers import HiCommand

app = App()
HiCommand().add_to(app)

app.start()
```
 
### Category (place an `x` in each of the `[ ]`)

* [x] **slack_bolt.App** and/or its core components
* [ ] **slack_bolt.async_app.AsyncApp** and/or its core components
* [ ] Adapters in **slack_bolt.adapter**
* [x] Others

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @tom0010, thanks for asking the question!

As you've already noticed, there is no way to add custom arguments to listener functions. The recommended way is to add your additional values to the `context` object. A common way is to use a global middleware to resolve the custom values before listener execution.

https://slack.dev/bolt-python/concepts#global-middleware

```python
@app.middleware
def set_db_object(context, body, next):
    context["db"] = acquire_database_session(body)
    next()
```

Hope this helps.

**Comment by tom0010** [comment]
Hey @seratch thanks for the info and the quick response! 
How would I do that using handlers like below with flask on top?


**app.py:**
```
from slack_bolt.adapter.socket_mode import SocketModeHandler
from slack_bolt.app import App
from handlers.message import Message

from flask import Flask

app = Flask(__name__)

BOT_TOKEN = os.environ["SLACK_TOKEN"]
APP_TOKEN = os.environ["SLACK_APP_TOKEN"]
SIGNING_SECRET = os.environ["SLACK_SIGNING_SECRET"]

bolt = App(token=BOT_TOKEN, signing_secret=SIGNING_SECRET)
Message().add_to(bolt)
SocketModeHandler(bolt, APP_TOKEN).connect()

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=10325, threaded=True)
```


**handlers/message.py:**
```
from handlers.messages import assign


class Message():
    def add_to(self, app):
        app.message("!assign to <@(\S+)>"))(assign.assign_ticket)
 ```
**handlers/messages/assign.py**
```
def assign_ticket(message, say, logger):
    logger.info(f"{message['text']} by {message['user']}")
    user = message["text"][24:-1:]
    text = "my message"
    return say(f"{user} you have been assigned {text}")
```

Tree:
```
.
├── handlers
│   ├── __init__.py
│   ├── message.py
│   ├── messages
│   │   ├── __init__.py
│   │   ├── assign.py
└── app.py
```

**Comment by seratch** [comment]
@tom0010 You can register global middleware in a similar way:

```python
bolt = App(token=BOT_TOKEN, signing_secret=SIGNING_SECRET)

class Middleware():
    def _set_db_object(self, context, body, next):
        context["db"] = acquire_database_session(body)
        next()

    def add_to(self, app):
        app.middleware(self._set_db_object)

Middleware().add_to(bolt)
Message().add_to(bolt)
```

Regarding the original question here, everything is clear now. Would you mind closing this issue?

**Comment by tom0010** [comment]
@seratch thanks, even though this works, it's not really something I was looking for. I was hoping that I could pass the db into the class which would be a new file. It doesn't seem possible? It would mean I would have to have that Middleware class inside the `app.py`? Ideally I would like to avoid that. 
As I said, your solution above does work and it does minimize the overall code by having a `handlers` folder with the code inside, but I was trying to do something like this:

**app.py:**
```python
bolt = App(token=BOT_TOKEN, signing_secret=SIGNING_SECRET)

something = "1234345345"

Middleware().add_to(bolt, something)
Message().add_to(bolt)
```
**handlers/middleware.py:**
```python
class Middleware():
    def _set_db_object(self, context, body, next, something):
        context["db"] = something
        next()

    def add_to(self, app, something):
        app.middleware(self._set_db_object(something))
```

This gives me this error:
```python
Traceback (most recent call last):
  File "/Users/tom/scripts/netadminsbottest/./app.py", line 35, in <module>
    Middleware().add_to(bolt, something)
  File "/Users/tom/scripts/netadminsbottest/handlers/middleware.py", line 8, in add_to
    app.middleware(self._set_db_object(something))
TypeError: _set_db_object() missing 3 required positional arguments: 'body', 'next', and 'something'
```
But this turns out that it is pretty much the same as before when I tried to pass arguments in my previous post. 
Also, I know you're keen to close this, but I'm still trying to figure out if this is possible. 
Thanks again.

**Comment by seratch** [comment]
@tom0010 As you saw, you cannot add the `something` to the global middleware. How about doing like this?

```python
class Middleware():
    def _set_db_object(self, context, body, next):
        context["db"] = self.something
        next()

    def add_to(self, app, something):
        self.something = something
        app.middleware(self._set_db_object)

Middleware().add_to(bolt, init_something())
```

I would recommend using constructor argument for `something` though:

```python
class Middleware():
    def __init__(self, something):
        self.something = something

    def _set_db_object(self, context, body, next):
        context["db"] = self.something
        next()

    def add_to(self, app):
        app.middleware(self._set_db_object)

Middleware(init_something()).add_to(bolt)
```

Either is fine.

**Comment by tom0010** [comment]
Oh yes, using `self` works fine, not sure why I didn't think of that! 
Thanks a lot - will close this now :)
