### ISSUE TITLE
How to get the channel that invoked a modal from modal submission handler @app.view("")

### ISSUE THREAD

**Issue by imageschool** [slackapi/bolt-python#560]
1.
Hi, I am trying to `say()` (send message) to a channel on modal submission (`@app.view('')`) without using hard-coded channel id.

So far, I can only access to the user with `body["user"]["id"]`

Is there a proper way to grab the channel id that invoked modal to open ? (`@app.action`)

2. 
Not related to above problem, but what is a right way to use both `@app.event('message')` and  `@app.message("word")`?

#### The `slack_bolt` version
slack-bolt==1.11.1

#### Python runtime version
Python 3.9.7

#### OS info
ProductName:	macOS
ProductVersion:	12.0.1
BuildVersion:	21A559
Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101

**Comment by seratch** [comment]
Hi @imageschool 

>Is there a proper way to grab the channel id that invoked modal to open ? (@app.action)

There are two options. The first one is to use `private_metadata` in your modal view. Refer to our responses below:

* https://github.com/slackapi/bolt-python/issues/550#issuecomment-998430750
* https://github.com/slackapi/bolt-python/issues/486#issuecomment-935920573
* https://github.com/slackapi/bolt-python/issues/392#issuecomment-874371844

The second is to use `response_url_enabled` and `default_to_current_conversation` in conversations_select block element in a modal. The channel ID can be absent if you use global shortcuts for opening the modal (global shortcuts are available everywhere, not only in the channel view). If you make the block input required, you can know where the end-user would like to receive a message in a channel.

Refer to the document for details: https://api.slack.com/reference/block-kit/block-elements#conversation_multi_select

>Not related to above problem, but what is a right way to use both @app.event('message') and @app.message("word")?

It's fine but if you place `@app.event('message')` before `@app.message("word")` in your source code, `@app.event('message')` catches all the messages. If you prioritize `@app.message("word")` (I'm sure this is what you want to do), you can place it before `@app.event('message')` listener:

```python
app = App()

@app.message("word")
def handle_specific_words():
    pass

@app.event('message')
def handle_the_rest_of_message_events():
    pass
```

I hope this helps.

**Comment by imageschool** [comment]
Hi @seratch 

Thank you for your quick response!

I absolutely had no idea that placing orders could matter for both @app.message() & @app.event('message')

I have now resolved both of the issues following your guide!

Thank you once again!
