### ISSUE TITLE
How to correctly format input to app.client.chat_unfurl?

### ISSUE THREAD

**Issue by djunGD** [slackapi/bolt-python#563]
I am trying to use the URL unfurling method "app.client.chat_unfurl', but keep running into issues even when trying to unfurl a URL that does not require authentication. I believe it may be because I am not correctly formatting my input parameter to app.client.chat_unfurl, but I'm having trouble finding any alternative. In particular, I see an error "TypeError: chat_unfurl() takes 1 positional argument but 2 were given ", which is troubling since I believe that my code only tries to pass 1 parameter to the method. I would be open to any possible suggestions on resolving.

### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version

3.12.0

#### Python runtime version

Python 3.9.7

#### OS info

macOS

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1. Build a Slack app using template (https://github.com/slackapi/bolt-python/blob/main/examples/flask/app.py) and install to a channel
2. Start ngrok server
3. Enable event listener link:shared. Enable Bot Token Scopes: links:read, links:write, channels:history. Link to the ngrok server
4. Add https://codebeautify.org to list of App unfurl domains
5. Add event listener to app: 
`@app.event("link_shared")
def unfurl_url(event, client, say, ack):
  '''
  Unfurls a discovered GoodData URL
  '''
  ack()
  say("link shared")
  channel = event["channel"]
  ts = event["message_ts"]
  unfurl_hash = {
    "channel": channel,
    "ts": ts,
    "unfurls": {
      "https://codebeautify.org/jsonviewer": {
        "blocks": [{
          "type": "image",
          "image_url": "https://appdevelopermagazine.com/images/news_images/Making-Application-Testing-a-First-Class-Citizen-App-Developer-Magazine_gd5jd6gn.jpg",
          "alt_text": "inspiration"
        }]
      }
    }
  }
  client.chat_unfurl(unfurl_hash)`
6. Run the app on the ngrok server
7. Add the app to its installed channel
8. As a user, manually enter "https://codebeautify.org/jsonviewer" as a message in the channel and submit.

```python
@app.event("link_shared")
def unfurl_url(event, client, say, ack):
    '''
    Unfurls a discovered GoodData URL
    '''
    ack()
    say("link shared")
    channel = event["channel"]
    ts = event["message_ts"]
    unfurl_hash = {
        "channel": channel,
        "ts": ts,
        "unfurls": {
            "https://codebeautify.org/jsonviewer": {
                "blocks": [{
                    "type": "image",
                    "image_url": "https://appdevelopermagazine.com/images/news_images/Making-Application-Testing-a-First-Class-Citizen-App-Developer-Magazine_gd5jd6gn.jpg",
                    "alt_text": "inspiration"
                }]
            }
        }
    }
    client.chat_unfurl(unfurl_hash)
```

### Expected result:

Unfurling of URL by displaying image "https://appdevelopermagazine.com/images/news_images/Making-Application-Testing-a-First-Class-Citizen-App-Developer-Magazine_gd5jd6gn.jpg"

### Actual result:

[link_shared_log.txt](https://github.com/slackapi/bolt-python/files/7825300/link_shared_log.txt)
I see an error come back:
TypeError: chat_unfurl() takes 1 positional argument but 2 were given 

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @djunGD, thanks for writing in!

Passing kwargs to use the method. You can call the method this way:

```python
client.chat_unfurl(**unfurl_hash)
```

Let me close this issue now but please feel free to write in if you have follow up questions on this!
