### ISSUE TITLE
How to achieve idempotence for incoming events

### ISSUE THREAD

**Issue by hyzyla** [slackapi/bolt-python#564]
I would like to write a bot that will listen to events from Slack and will guarantee that event will be handled not more than one time. For that I need some key  idempotent key, some unique key. In documentation to SlackAPI, I've found that each event has `event_id` as unique identifier:
> A unique identifier for this specific event, globally unique across all workspaces.

I think I can use that identifier to guarantee that an event will be handled not more than one time. But I haven't found any way to extract that `event_id` from an event that I receive in function decorated by `app.event` decorator: 

```python

@app.event(event="message")
def event_handler(logger, event):
    print(event)

```

1) How to extract `event_id` from event?
2) Or is there another way to achieve idempotence by using `slack_bolt` library?

#### The `slack_bolt` version

`1.11.1`

**Comment by seratch** [comment]
Hi @hyzyla, thanks for writing in!

You can use [`body` argument](https://slack.dev/bolt-python/api-docs/slack_bolt/kwargs_injection/args.html#slack_bolt.kwargs_injection.args.Args.body) instead of `event` to access `event_id` property.

```python
@app.event(event="message")
def event_handler(body, logger):
    logger.info(body.get('event_id'))
```

**Comment by hyzyla** [comment]
Thanks, it exactly what I'm looking for! Looks like a magic when arguments to handler passed by function signature.
