### ISSUE TITLE
Receiving 'channel_not_found' when trying to start conversation with postMessage(channel=userId) within an action handler

### ISSUE THREAD

**Issue by thebillington** [slackapi/bolt-python#565]
#### The `slack_bolt` version

slack-bolt==1.11.1
slack-sdk==3.13.0
slackclient==2.9.3

#### Python runtime version

Python 3.9.6

#### OS info

ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H1519
Darwin Kernel Version 19.6.0: Tue Oct 12 18:34:05 PDT 2021; root:xnu-6153.141.43~1/RELEASE_X86_64

#### Steps to reproduce:

I am trying to start a message with a user when receiving an action from the `Home` tab. The action is triggering, but the line `client.chat_postMessage(channel=user, text=response)` is triggering an error:

```
Error publishing home tab: The request to the Slack API failed. (url: https://www.slack.com/api/conversations.open)
The server responded with: {'ok': False, 'error': 'channel_not_found'}
```

I believe I have permissions set correctly (afaik) in order to create a new DM. My bot has both bot and user permissions for `chat:write` and `im:write`.

```python
@app.action("find-tasker")
def findTasker(ack, body, logger, client):
    try:
        ack()
        logger.info(body)

        user = body['user']['id']

        response = "..."
            
        client.chat_postMessage(channel=user, text=response)

    except Exception as e:
        logger.error(f"Error publishing home tab: {e}")
```

### Expected result:

I expect a new DM to be sent to my user with the response.

### Actual result:

I receive an error:

```
Error publishing home tab: The request to the Slack API failed. (url: https://www.slack.com/api/conversations.open)
The server responded with: {'ok': False, 'error': 'channel_not_found'}
```

**Comment by seratch** [comment]
Hi @thebillington, thanks for writing in!

>Error publishing home tab: The request to the Slack API failed. (url: https://www.slack.com/api/conversations.open)
>The server responded with: {'ok': False, 'error': 'channel_not_found'}

Your app's error message says the API call is `conversations.open`, not `chat.postMessage`. If your code fails to perform `conversations.open` API, check the parameters of the call. You can pass user IDs as `users`, not `channel`.

I hope this helps.

**Comment by thebillington** [comment]
@seratch thanks for getting back.

Apologies, I was testing other functions shortly before sending the bug report and included the wrong error. The actual error I receive for `chat.postMessage` is:

```
Error publishing home tab: The request to the Slack API failed. (url: https://www.slack.com/api/chat.postMessage)
The server responded with: {'ok': False, 'error': 'channel_not_found'}
```

Similarly when I tried:

```python
@app.action("find-tasker")
def findTasker(ack, body, logger, client):
    try:
        ack()
        logger.info(body)

        user = body['user']['id']

        response = "..."
            
        client.conversations_open(users=user)

    except Exception as e:
        logger.error(f"Error publishing home tab: {e}")
```

I get the error:

```
Error publishing home tab: The request to the Slack API failed. (url: https://www.slack.com/api/conversations.open)
The server responded with: {'ok': False, 'error': 'user_not_found'}
```

Thanks,

Billy

**Comment by seratch** [comment]
@thebillington 
Thanks for the reply! However, with the given information, I cannot tell anything helpful about what's happening with your app.

I'd recommend simply checking the API call here first: https://api.slack.com/methods/chat.postMessage/test 

I hope that you'll figure out the cause of your issue.

**Comment by thebillington** [comment]
@seratch thanks for the help, I managed to fix it. The error was a stupid oversight that I didn't actually include in my code.

Here is my full working code:

```python3
@app.action("find-tasker")
def findTasker(ack, body, logger, client):
    try:
        ack()
        logger.info(body)

        channel = body['user']['id']

        selectedAreas = []
        for filter in body['view']['state']['values']['task-area']['task-area']['selected_options']:
            selectedAreas.append(filter['value'])
            
        selectedProficiencies = []
        for filter in body['view']['state']['values']['software-proficiencies']['software-proficiencies']['selected_options']:
            selectedProficiencies.append(filter['value'])

        response = "Top Taskers:\n"
        for user in getUsers(selectedAreas, selectedProficiencies)[0:5]:
            response += "{0}: https://marketplace.paperound.com/en-GB/{0}\n".format(user)
            
        client.chat_postMessage(channel=channel, text=response)
```

As you can see I'm actually creating a loop iterator variable called `user` which in my previous code was overwriting the `user_id` set with `user = body['user']['id']`. Renaming this variable to channel did the trick.

Thanks!
