### ISSUE TITLE
Issues with deploying python bot to Heroku? Error saying no module named 'fcntl'

### ISSUE THREAD

**Issue by utsang** [slackapi/bolt-python#569]
I was following this guide here: 
https://github.com/slackapi/bolt-python/pull/441/commits/42633e78455a0c8ca66e16b439f13d3fde66de78
After initializing my git, I made a directory and tried running the code in the cmd: 
` gunicorn --bind :$PORT --workers 1 --threads 2 --timeout 0 main:flask_app`

But I get an error saying 
`File "c:\workfin\workfin_env\lib\site-packages\gunicorn\util.py", line 8, in <module>
    import fcntl`

I don't know whats wrong, I also had another questions, when its saying root directory, if in my case my .py files are under 
 C:\workfin\demofin
the root directory in this case would be  C:\workfin correct?

The guide I followed was kind of confusing, I was wondering if there is another guide?

**Comment by mwbrooks** [comment]
Hi @utsang,

Sorry to hear that you're hitting issues with the guide. This guide is still a work-in-progress and isn't officially published, so it's understandable that you may have have issues following it.

It looks like commit 42633e7 is out-of-date. You could try following the latest guide on the [190-heroku-deployment-guide branch](https://github.com/slackapi/bolt-python/tree/190-heroku-deployment-guide). Here is the [guide's markdown file](https://github.com/slackapi/bolt-python/blob/190-heroku-deployment-guide/docs/_deployments/heroku.md). However, you may still find that it doesn't work with your system and commands.

> I also had another questions, when its saying root directory...

The "app root directory" is your application's folder. In your example, it would be `C:\workfin\demofin`.

> The guide I followed was kind of confusing, I was wondering if there is another guide?

We're actually considering to not publish the Heroku guide because we haven't seen high demand from our community. **Do you find this example app to be more helpful to you?** https://github.com/slackapi/bolt-python/tree/main/examples/heroku

**Comment by utsang** [comment]
Thank you for responding, I used the last link as well but I feel kind of lost following it. Since its my first time ever using heroku and pushing to git its a little bit confusing. for example 

I am fully lost around this part

# heroku config:set SLACK_BOT_TOKEN=$SLACK_BOT_TOKEN
# heroku config:set SLACK_SIGNING_SECRET=$SLACK_SIGNING_SECRET
# git checkout -b main
# git add .
# git commit -m'Initial commit for my awesome Slack app'
# git push heroku main

and as well as the requirement, for the gunicorn, I see that its not available on windows so I don't know what to use in my case

**Comment by seratch** [comment]
@utsang 
Here is Heroku's official document for Python apps:
https://devcenter.heroku.com/articles/getting-started-with-python?singlepage=true

Indeed, gunicorn is not available for Windows OS, but you can use alternatives such as [waitress](https://pypi.org/project/waitress/). Refer to https://stackoverflow.com/questions/11087682/does-gunicorn-run-on-windows for more details.

Also, the following tutorial by us would be helpful. It's for Node.js developers but it should be helpful for learning the general ideas of Heroku platform in the Slack app development context.
https://slack.dev/bolt-js/deployments/heroku

I hope this helps!

**Comment by utsang** [comment]
> @utsang Here is Heroku's official document for Python apps: https://devcenter.heroku.com/articles/getting-started-with-python?singlepage=true
> 
> Indeed, gunicorn is not available for Windows OS, but you can use alternatives such as [waitress](https://pypi.org/project/waitress/). Refer to https://stackoverflow.com/questions/11087682/does-gunicorn-run-on-windows for more details.
> 
> Also, the following tutorial by us would be helpful. It's for Node.js developers but it should be helpful for learning the general ideas of Heroku platform in the Slack app development context. https://slack.dev/bolt-js/deployments/heroku
> 
> I hope this helps!

Thank you for responding, I just had the time to re work on this and its going good, I just have a question though, since I was running this on ngrok, I had this code:

```
@flask_app.route("/slack/events", methods=["POST"])
def slack_events():
  return handler.handle(request)

if __name__ == "__main__":
  app.start(3000)  # POST http://localhost:3000/slack/events

```
but when i use heruko I guess I'll have to use something else for this correct? I'm following the guide for python and it seems that the example uses a sockethandler, I was just confused about that

**Comment by seratch** [comment]
@utsang To run your apps on Heroku, your deployment must include `Procfile`, which tells how to bootstrap your app to the Heroku platform. 

If you go with gunicorn, `Procfile` can be like this: https://github.com/slackapi/bolt-python/blob/main/examples/heroku/Procfile 
If your requirements.txt includes gunicorn & flask plus your source file is named "main.py" and you have `flask_app` variable in it, the Procfile should work as-is.

**Comment by utsang** [comment]
@seratch  Thank you for responding, I followed a different guide posted online and gunicorn seemed to work for windows, and my procfile does contain that script. I just checked my requirement and I do have flask as well as gunicorn in it. 

> If you go with gunicorn, `Procfile` can be like this: https://github.com/slackapi/bolt-python/blob/main/examples/heroku/Procfile If your requirements.txt includes gunicorn & flask plus your source file is named "main.py" and you have `flask_app` variable in it, the Procfile should work as-is.

The source file that has the slack event functions is named sending.py, so all I have to do would be change 
`if __name__ = "__sending__":`

that should work correct?

**Comment by seratch** [comment]
No, in this case, the last part of the Procfile can be `sending:flask_app`. No need to have the if statement.

**Comment by utsang** [comment]
cool thank you very much
