### ISSUE TITLE
Event subscription setup instructions is outdated

### ISSUE THREAD

**Issue by pfcodes** [slackapi/bolt-python#570]
Part of the guide says:

```
Go to "Event Subscriptions"
Turn the feature on
```

But this has been replaced by the app manifest. New instructions are needed.

### The page URLs
* https://github.com/slackapi/bolt-python
* https://slack.dev/bolt-python/tutorial/getting-started-http#setting-up-events-over-http

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by mwbrooks** [comment]
Hi @pfcodes,

Thanks for point this issue out in the guide!

You're correct that "Event Subscriptions" has been removed from the App Configuration page and developers are expected to use App Manifest now.

I'll look into whether the "Event Subscription" will be coming back. If not, then we will need to update our guides.

For context, below is a screenshot of the freshly created Slack App (the same is displayed for my existing Slack apps):

![image](https://user-images.githubusercontent.com/21328/149022016-6aacf0c2-45c6-41bc-bed3-1a9060bca4bb.png)

**Comment by mwbrooks** [comment]
@pfcodes Hey, I just wanted to follow-up and let you know that you can also revert back to the original UI by selecting "Revert to the old design" on the side bar:

![image](https://user-images.githubusercontent.com/21328/149029584-7b48087b-37b1-4d6a-98ee-8819fb06e107.png)

**Comment by pfcodes** [comment]
> @pfcodes Hey, I just wanted to follow-up and let you know that you can also revert back to the original UI by selecting "Revert to the old design" on the side bar:
> 
> ![image](https://user-images.githubusercontent.com/21328/149029584-7b48087b-37b1-4d6a-98ee-8819fb06e107.png)

Yup, I realized that after the fact. Thank you!

**Comment by mwbrooks** [comment]
@pfcodes Sheer luck and good timing, today Slack's Platform Team released an update that now displays "Event Subscriptions" and other App Manifest UI in the [App Configuration Page](https://api.slack.com/apps).

So, we won't need to update our guides and no one will need to select the "Revert to the old design" anymore 🎉
