### ISSUE TITLE
Updating modal views with new initial_options does not update the view state

### ISSUE THREAD

**Issue by zhaodongw** [slackapi/bolt-python#572]
Hi team, I was trying to use `client.views_update` to update a view of a modal (i.e., using API `views.update`). 

In this update I updated a `multi_static_select` with a new list of `options` as well as new `initial_options`. Intuitively, this should update the `state` of the `view` as well by adding `initial_options` to `selected_options`. However, after updating the view and clicking "Submit" I found that the `selected_options` is still empty, which will cause an error "You need to select an option". This is definitely weird to users: they will see in the UI there are multiple options already selected but still see this error of "You need to select an option".

I know from the [API doc](https://api.slack.com/methods/views.update) there is a note: 
> Preserving input entry
Data entered or selected in input blocks can be preserved while updating views. The new view object that you use with `views.update` should contain the same input blocks and elements with identical `block_id` and `action_id` values.

which indicates that the `state` might not be updated after `views.update`, so is there any walk around for this or is it possible to fix this behavior on the API side?

Thanks!

**Comment by seratch** [comment]
Hi @zhaodongw, thanks for taking the time to write in here!

Unfortunately, this is a known issue on the server-side: https://github.com/slackapi/bolt-js/issues/1258 and we don't have have any updates after that. For now, please consider going with a workaround that I shared here: https://github.com/slackapi/bolt-js/issues/1073#issuecomment-903599111

I hope this helps.

**Comment by zhaodongw** [comment]
@seratch Thank you for letting me know! I will try this workaround.

**Comment by seratch** [comment]
Thanks for your reply! 

I know this issue is not fixed but as the maintainers of the SDKs, we don't have any further actions at this moment. Let us close this issue now.
