### ISSUE TITLE
How to update previous view in the stack after submission of current view

### ISSUE THREAD

**Issue by zhaodongw** [slackapi/bolt-python#575]
I am using `views.push` to push a new view on top of another view, after the submission of this newly pushed view, I got some input and want to use this input to update the previous view. I can get the `previous_view_id` from the `view_submission` payload, but I also need to know the view hash and view blocks of the previous view in order to update it. Is there a way to fetch the view payload using the view ID?

**Comment by seratch** [comment]
Hi @zhaodongw, thanks for asking the question!

>but I also need to know the view hash and view blocks of the previous view in order to update it. Is there a way to fetch the view payload using the view ID?

Unfortunately, there is no endpoint to know the current state of a view by view_id. The only thing that we can suggest is to store the view data in your database when you open and update a modal view. `views.open`, `views.update` API methods return `view` object data in response.

I know this is not an ideal answer for you but I hope this helps.

**Comment by zhaodongw** [comment]
@seratch Thanks for the quick response! Got it, I will use my own database for this use case then.
