### ISSUE TITLE
Does socket mode support broadcasting event to multiple instances?

### ISSUE THREAD

**Issue by ranlu** [slackapi/bolt-python#579]
Our group use slack as an interface to run various tasks. The current design uses a single slack bot as the entry point, and triggers various workers based on the commands. Each worker runs a local bot instance to listen to slack channels. The approach worked well using RTM bots, and we can add new commands to the bot by adding new workers. I recently tried to switch to socket mode, but it seems every event is only send to one instance in a random order. The workers are isolated for security reasons, so we cannot merge all the workers to use a single bot instance. Is there a way to broadcast the messages to all bot instances?
I think #548 is a similar issue, different motivation though.

**Comment by stevengill** [comment]
Hey @ranlu,

By design, socketmode randomizes sending the event between the socket connections. For your usecase, would it be possible to have 1 socket connection and then implement a job queue to spread the events to their respective workers? A similar discussion was had at https://github.com/slackapi/bolt-python/issues/448#issuecomment-906006586

**Comment by ranlu** [comment]
Hi @stevengill, thanks for the suggestion, I am considering doing that, but it is going to negate much of the advantage of using slack for our case, as it is more or less equal to implementing our own service to serve messages to each worker.
Do you mind explaining a little more about the reason behind the design decision, since socket mode already allows multiple connections, randomly rotating the receivers but disallow broadcasting seems a rather odd decision.

**Comment by seratch** [comment]
Hi @ranlu, the purpose of the design is mentioned at the beginning of the Socket Mode document:
>Socket Mode allows your app to use the Events API and interactive components of the platform—without exposing a public HTTP Request URL. Instead of sending payloads to a public endpoint, Slack will use a WebSocket URL to communicate with your app. Socket Mode helps developers working behind a corporate firewall, or who have other security concerns that don't allow exposing a static HTTP endpoint.
https://api.slack.com/apis/connections/socket

As described above, Socket Mode is designed to enable developers to switch the communications with Slack server-side from public HTTP endpoint style to outgoing WebSocket connection. The Slack server-side sends data to one recipient in the same manner with HTTP requests. 

Aside from that, the more important reason behind this is the necessity of request acknowledgement. The RTM API supports only event delivery, which does not require acknowledgement. On the other hand, Socket Mode supports all the available platform features such as slash commands, shortcuts, and interactions (button clicks, modal data submissions, etc.) in addition to Events API. Taking advantage of these features means that your app must acknowledge incoming requests **only once** (technically it's possible to acknowledge twice in Socket Mode but the second one will be just ignored) within 3 seconds. 

The acknowledgement sometimes makes visible effects in the end-user UI. For instance, displaying validation error messages in a modal UI can be done only by passing errors in request acknowledgement. There are a few similar use cases.

Considering the characteristics of the communications required for these features, we don't think there is a feasible way to safely duplicate event delivery to all the active hosts on the platform side. Thus, there is no plan to add an option to customize this behavior in the roadmap.

This is why I suggested having one dedicated instance that handles user interactivity in the linked comment. If you're going to use only Events API, a slightly simpler way can work. Front-end single Socket Mode clients can acknowledge all the events anyways and they can relay the events to all the active backend workers. 

I know this is not an ideal answer for you but I hope this helps. If everything is clear here, would you mind closing this issue? Lastly, I hope you'll find an acceptable solution for your use case.

**Comment by ranlu** [comment]
Thanks for the detailed explanation @seratch, sorry my bot was built with RTM api so I did not realized the needs for acknowledge events.  I will stay with RTM API for now. Close the issue.
