### ISSUE TITLE
Wrong user_token assigned to new user (affected versions: v1.11.2, v1.11.3)

### ISSUE THREAD

**Issue by stantonius** [slackapi/bolt-python#584]
After updating to v1.11.3 I was experiencing that the user token was not being reassigned to `None` if the requesting user has not yet had an installation. This fix was part of issue [#576](https://github.com/slackapi/bolt-python/pull/576).

What happens now is if a user does not currently have an installation, the App assumes it was the latest user and assigns it their `user_token`.

I have created a simple PR to fix this, however I am no longer sure [#576](https://github.com/slackapi/bolt-python/pull/576) actually fixed my initial issue [#574](https://github.com/slackapi/bolt-python/issues/574). I could be missing something though.

#### The `slack_bolt` version

git+git@github.com:stantonius/bolt-python.git@805e976308db198f324e63008c3d71d8b9c6350f#egg=slack_bolt

#### Python runtime version

Python 3.9.2

#### OS info

ProductName:    macOS
ProductVersion: 12.0.1
BuildVersion:   21A559
Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101

#### Steps to reproduce:

As described in [#574](https://github.com/slackapi/bolt-python/issues/574) and fix [#576](https://github.com/slackapi/bolt-python/pull/576):

1. The App is assigned at the organization level. A `bot_token` is generated and stored
2. One user looks at the app, understands what it does, and then installs user permissions, generating and storing a `user_token`
3. A second user does the same as the first. The app recognizes it is a new user, and asks for user permissions again

### Expected result:

No `user_token` for second user. App asks for this to be generated via Oauth flow 

### Actual result:

The previous user's `user_token` is assigned to this second user.

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
@stantonius Thanks again for reporting this issue! We've released a new patch version including the fix for this issue. Please try the latest version out 👋
