### ISSUE TITLE
Django Bolt Python Example Doesn't Run w/o Oauth_Flow Object 

### ISSUE THREAD

**Issue by ghabs** [slackapi/bolt-python#589]
I believe the Django examples for the oauth flow are incomplete. Currently, when running the app, it returns a page "Not Found", which seems to be because the Bolt Python app is initialized without self.app.oauth_flow, which per the code below returns a 404.

```python
def handle(self, req: HttpRequest) -> HttpResponse:
    if req.method == "GET":
        if self.app.oauth_flow is not None:
            oauth_flow: OAuthFlow = self.app.oauth_flow
            if req.path == oauth_flow.install_path:
                bolt_resp = oauth_flow.handle_installation(to_bolt_request(req))
                return to_django_response(bolt_resp)
            elif req.path == oauth_flow.redirect_uri_path:
                bolt_resp = oauth_flow.handle_callback(to_bolt_request(req))
                return to_django_response(bolt_resp)
    elif req.method == "POST":
        bolt_resp: BoltResponse = self.app.dispatch(to_bolt_request(req))
        return to_django_response(bolt_resp)

    return HttpResponse(status=404, content=b"Not Found")
```

#### The `slack_bolt` version

slack-bolt==1.11.4

#### Python runtime version

Python 3.10.2

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1. Clone the django oauth example app
2. Visit /slack/install

### Expected result:

Option to install Slack

### Actual result:

Receive a page with the text "not found"

**Comment by seratch** [comment]
Hi @ghabs, thanks for writing in!

As mentioned in the README of the example,
> If you want to switch to OAuth flow supported one, modify myslackapp/urls.py.
https://github.com/slackapi/bolt-python/blob/v1.11.4/examples/django/README.md#oauth_app---multiple-workspace-app-example-oauth-flow-supported

You can switch the URL routings by setting [this flag](https://github.com/slackapi/bolt-python/blob/v1.11.4/examples/django/myslackapp/urls.py#L20) to False or just removing the simple app pattern.

I hope this helps!

**Comment by ghabs** [comment]
Hi there! I have done that, and I believe the error still occurs because the django handler requires an Oauth_Flow to be set for the `app` else it returns a 404 on the /slack/install path. Here is a reproduction of the code from the tutorial:
`
app = App(
    signing_secret=signing_secret,
    oauth_settings=OAuthSettings(
        client_id=client_id,
        client_secret=client_secret,
        scopes=scopes,
        # If you want to test token rotation, enabling the following line will make it easy
        # token_rotation_expiration_minutes=1000000,
        installation_store=DjangoInstallationStore(
            client_id=client_id,
            logger=logger,
        ),
        state_store=DjangoOAuthStateStore(
            expiration_seconds=120,
            logger=logger,
        ),
    ),
)
`
and when the /slack/install url is visited, it returns not found

**Comment by ghabs** [comment]
> Hi @ghabs, thanks for writing in!
> 
> As mentioned in the README of the example,
> 
> > If you want to switch to OAuth flow supported one, modify myslackapp/urls.py.
> > https://github.com/slackapi/bolt-python/blob/v1.11.4/examples/django/README.md#oauth_app---multiple-workspace-app-example-oauth-flow-supported
> 
> You can switch the URL routings by setting [this flag](https://github.com/slackapi/bolt-python/blob/v1.11.4/examples/django/myslackapp/urls.py#L20) to False or just removing the simple app pattern.
> 
> I hope this helps!

And to be specific, when the flag is set to False in the tutorial, the 404 'not found' response occurs when visiting the /slack/install page

**Comment by seratch** [comment]
Hi @ghabs, thanks for your quick reply here! 

I tried to reproduce your situation on my end just in case, however I didn't manage to see the same error yet. The example app should still be valid.

Also, I'm unsure about possible causes of your situation.

>and I believe the error still occurs because the django handler requires an Oauth_Flow to be set for the app else it returns a 404 on the /slack/install path. Here is a reproduction of the code from the tutorial:

As long as you pass a valid oauth_settings, `App` constructor generates `app.oauth_flow` internally. Thus, this guess is not the cause of your issue.

I hope you'll figure the cause out soon.

**Comment by ghabs** [comment]
Note: I was able to make some progress by changing the django handler.py file from

> if self.app.oauth_flow is not None:

to

> if self.app._oauth_flow is not None:

as the Class App __init__ function sets a private _oauth_flow property in line 275 
```python
           self._oauth_flow = OAuthFlow(
                client=self.client, logger=self.logger, settings=oauth_settings
            )
```
but afaict not a public one

**Comment by seratch** [comment]
I don't recommend doing so. I guess the passed `oauth_settings` in your app may have some issues.

**Comment by ghabs** [comment]
hmm yes maybe I'm doing something weird - ok well if its not reproducible I must have introduced some type of bug on my own. Thanks for investigating

**Comment by ghabs** [comment]
> Hi @ghabs, thanks for your quick reply here!
> 
> I tried to reproduce your situation on my end just in case, however I didn't manage to see the same error yet. The example app should still be valid.
> 
> Also, I'm unsure about possible causes of your situation.
> 
> > and I believe the error still occurs because the django handler requires an Oauth_Flow to be set for the app else it returns a 404 on the /slack/install path. Here is a reproduction of the code from the tutorial:
> 
> As long as you pass a valid oauth_settings, `App` constructor generates `app.oauth_flow` internally. Thus, this guess is not the cause of your issue.
> 
> I hope you'll figure the cause out soon.

For my own education as I learn the library, do you know where/can you point out where the App constructor sets app.oauth_flow? I see it sets app._oauth_flow in line 237 of app/app.py but I don't see self.oauth_flow

**Comment by seratch** [comment]
It's a property of the class: https://github.com/slackapi/bolt-python/blob/v1.11.4/slack_bolt/app/app.py#L401-L404

**Comment by ghabs** [comment]
Cool, then I'm not sure what I passed in that caused it not to be set. Appreciate the help

**Comment by hustlefueled** [comment]
@ghabs, I am where you were with this. Were you able to get around this? Anything specific that helped?

**Comment by hustlefueled** [comment]
Got it to work. Btw, there should be a warning in the demo application to pass `install_path` and `redirect_uri_path` when using it in an existing codebase.

Spent an entire day to only fix it by adding this. 🤷‍♂️
