### ISSUE TITLE
How an app is deleted from Installation Store

### ISSUE THREAD

**Issue by dsharma522** [slackapi/bolt-python#590]
I have subscribed to `app_uninstalled` event and it is being called (verfied from custom logs). Also the installation store is setup properly (the installation,  bot info are getting written into the store). Also i have implimented the `delete_all`, `delete_bot`, `delete_installation` methods along with `save` and `find_installation` . The problem is that , these methods are not being called nor deleting the data from stores.

```
installation_store=MongoInstallationStore()

app = App(
    signing_secret=os.environ.get("SLACK_SIGNING_SECRET"),
    installation_store=installation_store,
    oauth_settings=OAuthSettings(
        client_id=os.environ.get("SLACK_CLIENT_ID"),
        client_secret=os.environ.get("SLACK_CLIENT_SECRET"),
        scopes=['channels:history', 'channels:read', 'files:read', 'reactions:read',
                'team:read',
                'users.profile:read', 'users:read',
                'conversations.connect:read',
                'users:read.email'],
        user_scopes=[],
        redirect_uri=None,
        install_path="/slack/install",
        redirect_uri_path="/slack/oauth_redirect",
        state_store=MongoOAuthStateStore(expiration_seconds=600),
        callback_options=CallbackOptions(success=success, failure=failure),
    ),
)
```

And in the `MongoInstallationStore`, all the methods are implimented. But deletions ones not being called. But`save` method on fresh installations is being called. 

Event suscribed as 
```
@app.event(
    event={"type": "app_uninstalled"}
)
def handler(body: dict, client: WebClient, context: BoltContext, logger: logging.Logger):
   #####
```

How to propely handle this `app_uninstalled` event and deletion from Installation store

❯ pip freeze | grep slack              
slack-bolt==1.11.4
slack-sdk==3.13.0

Python is 3.7

**Comment by seratch** [comment]
Hi @dsharma522, thanks for asking the question!

bolt-python supports those events out-of-the-box. Just calling `App#enable_token_revocation_listeners()` enables the built-in listeners to clean data up for you.

```python
app = App(
  # Enabling installation_store required
)
app.enable_token_revocation_listeners()
```

The method call is equivalent to:

```python
app = App()  # installation_store required
app.event("tokens_revoked")(app.default_tokens_revoked_event_handler)
app.event("app_uninstalled")(app.default_app_uninstalled_event_handler)
```

These methods properly call your installation store's deletion method. If you need more control on the data cleanup, you can customize what bolt-python does in `default_tokens_revoked_event_handler` and `default_app_uninstalled_event_handler`. Refer to https://github.com/slackapi/bolt-python/releases/tag/v1.5.0 for more details.

If your `MongoInstallationStore` still does not clean installation data in the deletion method as you expect, I would recommend checking the internals of the built-in InstallationStore implementations: https://github.com/slackapi/python-slack-sdk/tree/main/slack_sdk/oauth/installation_store 

I hope this helps!

**Comment by dsharma522** [comment]
So just doing `app.enable_token_revocation_listeners()` will call the Installation store's method ? `delete_bot`, `delete_installation` and `delete_all`? 
Though i have subscribed to only one event of them

**Comment by seratch** [comment]
@dsharma522 Yes, enabling those listeners means the event listeners automatically call [these methods](https://github.com/slackapi/bolt-python/blob/v1.11.4/slack_bolt/listener/builtins.py#L15-L35) for you. 

>Though i have subscribed to only one event of them

I would recommend subscribing to the two events for safety.

If you encounter any issues with the built-in support, please let us know with a working example.

**Comment by seratch** [comment]
I believe that all the questions here were answered. Let us close this issue now but please feel free to write in if you have anything to ask more!
