### ISSUE TITLE
How to listen to more than one step in the same app?

### ISSUE THREAD

**Issue by r4ibOm** [slackapi/bolt-python#591]
I created a custom step for my app and it works perfectly, but the step name needs to be fixed in the code. For example:

```
def edit
def save
def run

ws = WorkflowStep(
     callback_id="first_modal",
     edit=edit,
     save=save,
     execute=execute,
)
# Pass Step to set up listeners
app.step(ws)
```

If my app has about 20 custom steps for example, how would I handle this within the code?

When I remove the code I get an indication that the event was found like in the image below, but I don't know how to get this callback_id

![image](https://user-images.githubusercontent.com/44219005/153776782-78a0a73b-ce50-4255-b474-d87c680b7cb9.png)

If I could get the callbackId I could pass it as a parameter and call the function like this:

```
ws = WorkflowStep(
     callback_id=callback_id,
     edit=get_edit(callback_id),
     save=get_save(callback_id),
     execute=get_execute(callback_id),
)
```

But like I said, I don't know how to get the callback id. can you help me?

**Comment by seratch** [comment]
Hi @r4ibOm, thanks for asking the question!

The `callback_id` is the string value that you decide when you add workflow steps in your Slack app configuration page. Your app should already have the one with "first_modal".

<img width="500" src="https://user-images.githubusercontent.com/19658/153777561-81a2e504-496c-4027-a8d8-86ddaa19ea65.png">

If you are going to add more, you can add other unique string values for other steps. Also, in the bolt-python code, you can create `WorkflowStep` for each. If you have 10 custom workflow steps in an app, your app needs to have 10 `WorkflowStep` objects, which are added by `app.step(obj)` method.

I hope this helps!

**Comment by r4ibOm** [comment]
Hi @seratch ,

Thanks for the prompt reply, my question is exactly that.
Is there no other way to call the WorkflowStep, without having to repeat it 10 times in the main script? Through a class or something?

I started developing a slack app at the company I work for and I'm seeing that the features will grow a lot over time, so I'm thinking of a way to make it as organized as possible, without having to create more apps.

**Comment by seratch** [comment]
@r4ibOm None of the 20 custom steps is not the same with one another, right? So, I don't think that calling `app.step` 20 times is necessary for enabling 20 different custom step code in your bolt-python app.

To organize those steps, you may want to separate the custom step code to different files and import them in the `main.py` source code.

```
├── main.py
└── steps
    ├── step1.py
    └── step2.py
```

Perhaps, we are unable to provide any other further suggestions here. If everything is clear now, would you mind closing this issue?

**Comment by r4ibOm** [comment]
@seratch , I was able to better organize my code according to your suggestions.
Thanks.
