### ISSUE TITLE
Cancel message sending to the chat

### ISSUE THREAD

**Issue by koren-v** [slackapi/bolt-python#595]
Hi, I'm new to the Slack API and wanted to ask for your help. 

I just want to know is it possible to catch the user's message and prevent it's sent to the chat if needed? (e.g I want to filter some messages by content)

Maybe, there are some alternatives I can do?

**Comment by seratch** [comment]
Hi @koren-v, I'll answer this question at https://github.com/slackapi/python-slack-sdk/issues/1186 ! (please avoid cross-posting)

**Comment by koren-v** [comment]
@seratch Sorry, thanks for your answer!
