### ISSUE TITLE
Avoiding using global variables

### ISSUE THREAD

**Issue by mkollaro** [slackapi/bolt-python#597]
How to avoid using global variables when using Bolt? If I use function decorators like in the examples, I need to make the App global.

I would also like to pass some handles to the function reacting to a Slack command (not just ack, response, and command). Right now I have to make those variables global to do so. Any way to avoid this?

**Comment by misscoded** [comment]
Hi @mkollaro! 👋🏼 

Great question. The suggested solution and accompanying pseudo code provided in [this past response](https://github.com/slackapi/bolt-python/issues/245#issuecomment-783836164) might be of interest to you as an alternative approach to decorators:

> One possible easy way would be having register_listeners(App) method and using it in main.py (the entry point of your app). With this approach, you can separate the App initialization from listener methods and whatever you have for the application logic.

Have a look and let us know if that enables you to structure the code in the way you're aiming for!

**Comment by seratch** [comment]
As this question is answered by Alissa already, let us close it now. If you have any follow-up comments, please feel free to write in after that!
