### ISSUE TITLE
How to use the python bolt decorator function inside a class

### ISSUE THREAD

**Issue by mohan-raheja** [slackapi/bolt-python#598]
Hi, 
I am using slack_bolt for development, I found that slack commands and events can be handled by passing a decorator function like `@app.events("event_name")` or `@app.command("/command_name")`, I want to module the handler as class methods, but the decorator function seems not supported for the class Methods, I have tried calling it as a function also 

```
class A:
  .....
   def calc():
     pass
```
app.action("/command_name")(A().calc), but still my endpoint is not hitting. Is there a way  I can achieve this?I appreciate any help over here.

**Comment by eddyg** [comment]
As one possible solution, you can look at my approach [in this similar issue](https://github.com/slackapi/bolt-python/issues/236#issuecomment-776713756).

**Comment by misscoded** [comment]
Thanks for surfacing this, @eddyg! Super helpful and much appreciated.

@mohan-raheja, have a look at the proposed solution in the linked thread and let us know if it resolves the issue you're facing.

**Comment by seratch** [comment]
As @mohan-raheja added a reaction, I think that this issue can be closed now. That being said, if you have any follow-up comments, please feel free to write in after that!
