### ISSUE TITLE
Doubt about using an app via AWS Lambda with many simultaneous requests

### ISSUE THREAD

**Issue by r4ibOm** [slackapi/bolt-python#599]
It's been 2 months since I started in the slack world in a new job and started developing an application in Slack to automate tasks and perform integrations with other systems from workflows, modals etc.

People liked it a lot and several demands have already arisen but I'm a little worried about the stability of this application in the cloud.
I am currently using an API Gateway + Lamda + Slack Bolt on AWS and it has worked well in my tests.
The point is that the company has more than 2 thousand employees and I'm afraid of what can happen when many people are using the application's features at the same time.

When there are many simultaneous requests on the same url for events and shotcurts. Is there any possibility of having a problem and having a conflict/loss of requests? Do I have any concerns about this?

Thanks

**Comment by seratch** [comment]
Hi @r4ibOm, thanks for asking the question!

>When there are many simultaneous requests on the same url for events and shotcurts. Is there any possibility of having a problem and having a conflict/loss of requests? Do I have any concerns about this?

You don't need to worry about any issues on how Bolt handles incoming requests from Slack. As long as your code does not have a kind of global state, the individual requests are completely isolated from one another. No risk that those requests can be ignored or mixed up.

The only concern that I can think of is the risk to exceed the quotas of API Gateway and/or Lambda function executions:

* https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-request-throttling.html
* https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html

Please note that we are not experts on AWS services. As for the details of throttling and possible solutions for it, please contact your AWS account manager / support agents for more details of the massive scale usage of HTTP triggered Lambda functions. Also, this topic should not be specific to Slack apps.

I hope this was helpful to you. Is everything clear now?

**Comment by r4ibOm** [comment]
Hi @seratch, Thanks for the clarifications. 
This question came to me because I took some old projects in the company and I realized that they were using SQS to put all the requests in a queue and I didn't understand.
But knowing that requests are handled in isolation, I am at peace. Regarding AWS request limits, I'm confident I won't have any problems.
About this global state, can you tell me more specifically what it would be? I am faithfully following the examples in the documentation.

**Comment by seratch** [comment]
@r4ibOm 
>This question came to me because I took some old projects in the company and I realized that they were using SQS to put all the requests in a queue and I didn't understand.

I'm not sure why those apps use SQS but if the purpose is to avoid 3 second timeouts before responding to Slack (=`ack()` call in 3 seconds in bolt apps), you can use [Lazy listeners](https://slack.dev/bolt-python/concepts#lazy-listeners) for achieving the same goal.

>About this global state, can you tell me more specifically what it would be? I am faithfully following the examples in the documentation.

The most common pattern would be having global variables in your Python code and accessing those data from your bolt-python listeners. This naive way to manage data can easily cause data corruption or data privacy issues. This usually does not happen in Lambda apps but if Lambda's [Reserved Concurrency](https://docs.aws.amazon.com/lambda/latest/dg/configuration-concurrency.html) can allow your code to access shared memory among Lambda executions, having global objects in your code can be a cause of similar issues. Actually, I've never checked this out yet, though.

Also, the similar situation can arise if your app does not properly manage end-user data in database such as DynamoDB.

Do these make sense to you?
