### ISSUE TITLE
trigger_exchanged error using AWS Lambda + Workflow Steps

### ISSUE THREAD

**Issue by r4ibOm** [slackapi/bolt-python#600]
Hi,

I created a workflow step at the company where I work to automate the approval of requests without having to open a ticket. Basically I have a workflow where the user fills in some information and after submitting the form, a message arrives for the manager with a button to approve or deny the request.

The issue is that I need to validate the information entered in the workflow and for that I need to connect to other APIs etc, and this can all take up to 10 seconds before validating the data and sending the request.

I believe that due to slack's response time, as I can't respond within 3 seconds, slack repeats requests, and with that I have repeated request messages being sent.

These are the AWS logs where requests are repeated and the error occurs:

![image](https://user-images.githubusercontent.com/44219005/155593324-235abe46-5f26-478c-9ccb-b39c07aa2f75.png)

If this is really the problem and I can solve it using Lazy listeners, I would like to understand how to use them in workflow steps.

This is the part of my project where I do the validations in the execute method of the workflow:

```
St = SlackTools()

def execute(step, complete, fail):
    inputs = step["inputs"]

    sendername = inputs["senderName"]["value"].strip()
    sendermail = inputs["senderEmail"]["value"].strip()
    sendermention = inputs["senderMention"]["value"].strip()
    senderid = sendermention[2:len(sendermention)-1]
    awsname = inputs["awsName"]["value"].strip()
    awsrole = inputs["awsRole"]["value"].strip()
    squad = inputs["squad"]["value"].strip()
    reason = inputs["reason"]["value"].strip()
    managermail = inputs["managerMail"]["value"].strip()

    outputs = {
        "senderName": sendername,
        "senderEmail": sendermail,
        "senderMention": sendermention,
        "awsName": awsname,
        "awsRole": awsrole,
        "squad": squad,
        "reason": reason,
        "managerMail": managermail
    }

    checkinputname = Ot.check_inputs(inputs, INPUT_AWS_NAME)
    checkinputmanager = Ot.check_inputs(inputs, INPUT_MANAGER_MAIL)

    # Check inputs
    if not checkinputname or not checkinputmanager:
        if not checkinputname:
            errmsg = {"message": f"Acesso {awsname} não encontrado! Olhar no Pin fixado do canal o nome de cada AWS."}
            blocklayout = FAIL_MSG_AWS_NAME
        else:
            errmsg = {"message": f"Gestor {managermail} não encontrado no ambiente!"}
            blocklayout = FAIL_MSG_MANAGER_MAIL

        fail(error=errmsg)
        blockfail = get_workflow_block_fail(sendermention, managermail, awsname, awsrole, blocklayout)
        send_block_fail_message(blockfail, senderid) # Send fail block message to user
    else:
        try:
            manager = St.app().client.users_lookupByEmail(email=managermail)
            managerid = manager["user"]["id"]

            blocksuccess = get_workflow_block_success(sendermention, awsname)

            send_request_aws_message(sendername, sendermail, sendermention,
                                     awsname, awsrole, squad, reason, managermail, managerid) # Send block message to manager
        except Exception as e:
            if "users_not_found" in str(e):
                error = {"message": f"Gestor {managermail} não encontrado no ambiente!"}
                fail(error=error)
                blocklayout = FAIL_MSG_MANAGER_MAIL
                blockfail = get_workflow_block_fail(sendermention, managermail, awsname, awsrole, blocklayout)
 
                send_block_fail_message(blockfail, senderid) # Send fail block message to user
            else:
                error = {"message": "Just testing step failure! {}".format(e)}
                fail(error=error)
                St.webhook_directly(WEBHOOK_LOGS_URI_FAIL, e, FAIL)
        else:
            St.app().client.chat_postMessage(text="Envio com sucesso de solicitação de acesso AWS", blocks=blocksuccess,
                                             channel=senderid) # Send success block message to user

            complete(outputs=outputs)
```

**Comment by seratch** [comment]
Hi @r4ibOm, thanks for asking the question!

I am pretty sure that your situation is exactly the same with https://github.com/slackapi/bolt-python/issues/465 I've already provided an answer there. Check the lazy listener solution 👋

**Comment by BSouzaDock** [comment]
@seratch Thanks for the example!

I set up a structure similar to the one informed but I'm getting a strange error when calling the execute() function:

> [ERROR]	2022-02-25T14:30:18.190Z	f845a60e-5999-4956-8a22-0a8529c0a8fe	Failed to run listener function (error: execute() missing 1 required positional argument: 'self')
> Traceback (most recent call last):
>   File "/var/task/slack_bolt/listener/thread_runner.py", line 65, in run
>     returned_value = listener.run_ack_function(
>   File "/var/task/slack_bolt/listener/custom_listener.py", line 49, in run_ack_function
>     return self.ack_function(
> TypeError: execute() missing 1 required positional argument: 'self'

I don't understand this required argument "self".

My structure is like this:

```
class AwsRequestSlackSteps:
    step_builder = WorkflowStep.builder(CALLBACK_ID_AWS_REQUEST)

    def __init__(self, app):
        self.app = app

        # Pass Step to set up listeners
        self.app.step(step_builder)

    def execute_step(self, step: dict, complete: Complete, fail: Fail):
        .........

    # Abre o bloco de edições do app step
    @step_builder.edit
    def edit(self, ack: Ack, configure: Configure):
        .........

    # Salva o bloco de edições
    @step_builder.save
    def save(self, ack: Ack,  view: dict, update: Update):
        .........

    # Executa o workflow step
    @step_builder.execute(lazy=[execute_step])
    def execute(self):
        pass
```

**Comment by r4ibOm** [comment]
@seratch Thanks for the example!

I set up a structure similar to the one informed but I'm getting a strange error when calling the execute() function:

> [ERROR]	2022-02-25T14:30:18.190Z	f845a60e-5999-4956-8a22-0a8529c0a8fe	Failed to run listener function (error: execute() missing 1 required positional argument: 'self')
> Traceback (most recent call last):
>   File "/var/task/slack_bolt/listener/thread_runner.py", line 65, in run
>     returned_value = listener.run_ack_function(
>   File "/var/task/slack_bolt/listener/custom_listener.py", line 49, in run_ack_function
>     return self.ack_function(
> TypeError: execute() missing 1 required positional argument: 'self'

I don't understand this required argument "self".

My structure is like this:

```
class AwsRequestSlackSteps:
    step_builder = WorkflowStep.builder(CALLBACK_ID_AWS_REQUEST)

    def __init__(self, app):
        self.app = app

        # Pass Step to set up listeners
        self.app.step(step_builder)

    def execute_step(self, step: dict, complete: Complete, fail: Fail):
        .........

    # Abre o bloco de edições do app step
    @step_builder.edit
    def edit(self, ack: Ack, configure: Configure):
        .........

    # Salva o bloco de edições
    @step_builder.save
    def save(self, ack: Ack,  view: dict, update: Update):
        .........

    # Executa o workflow step
    @step_builder.execute(lazy=[execute_step])
    def execute(self):
        pass
```

**Comment by seratch** [comment]
@r4ibOm Instance methods in a different class are unsupported for the listeners for WorkflowStep functions, and we don't have plans for the enhancement in the short term. 

Instead of your current way, please consider building the step in __init__ or a new method for initialization:

```python
class AwsRequestSlackSteps:

    def __init__(self, app):
        self.app = app
        step_builder = WorkflowStep.builder(CALLBACK_ID_AWS_REQUEST)

        def execute_step(step: dict, complete: Complete, fail: Fail):
            pass

        @step_builder.edit
        def edit(ack: Ack, configure: Configure):
            pass

        @step_builder.save
        def save(ack: Ack, view: dict, update: Update):
            pass

        @step_builder.execute(lazy=[execute_step])
        def ack_execute():
            pass

        self.app.step(step_builder)
```

**Comment by r4ibOm** [comment]
Hi @seratch 

I had managed to make it work by putting the execute method in the global scope. But as you said it was much better.

Thanks.
