### ISSUE TITLE
Route socket exceptions through the custom exception handler

### ISSUE THREAD

**Issue by gpiks** [slackapi/bolt-python#605]
### Reproducible in:

```
slack_bolt >= 1.11.1
slack_sdk>=3.9.0,<4
```

#### Python runtime version

`python3.9`

#### OS info

Not relevant

#### Steps to reproduce:

```python
import json
import logging
import os
import re
from typing import Optional

from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler
from slack_bolt.error import BoltUnhandledRequestError
from slack_bolt.response import BoltResponse
from slack_sdk import WebClient

app_token = os.environ.get("SLACK_APP_TOKEN")
bot_token = os.environ.get("SLACK_BOT_TOKEN")
http_proxy = os.environ.get("SLACK_HTTP_PROXY")
signing_secret = os.environ.get("SLACK_SIGNING_SECRET")


client = WebClient(
    token=bot_token,
    proxy=http_proxy,
)

app = App(
    client=client,
    token=bot_token,
    ssl_check_enabled=False,
    signing_secret=signing_secret,
    raise_error_for_unhandled_request=True,
)

logger = logging.getLogger("blinkbot")


@time_metric("message")
@app.message(re.compile("{.*}"))
def decorate_link(message, say, body) -> None:
    ...


@app.event("message")
def handle_message_events():
    """Stub to avoid warnings."""
    ...


@app.error
def custom_error_handler(error: Exception) -> Optional[BoltResponse]:
    if isinstance(error, BrokenPipeError) or isinstance(error, BlockingIOError):
        logger.warning("Socket issues: %s", error)
        return BoltResponse(status=200, body="")
    elif isinstance(error, BoltUnhandledRequestError):
        # This may be noisy
        logger.info("BoltUnhandledRequestError: %s", error, exc_info=True)
        return BoltResponse(status=200, body="")

    logging.exception("Uncaught exception: %s", error)
    return None


if __name__ == "__main__":
    handler = SocketModeHandler(app, app_token, proxy=http_proxy)
    handler.start()
```
### Expected/Actual result:

We expect the `custom_error_handler` to catch all configured exceptions but these exceptions leak through.

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by gpiks** [comment]
For example the traceback we see is 
```
2022-02-15T12:58:55.675397+0000 ERROR [21:Thread-2] connection.py:293 Failed to check the state of sock (session id: cf3ec9a6-bb59-449a-a770-3a9f54ed0ce3, error: BrokenPipeError, message: [Errno 32] Broken pipe)
Traceback (most recent call last):
  File "/bb/libexec/blinkbot/dependencies/site-packages/slack_sdk/socket_mode/builtin/connection.py", line 258, in check_state
    self.ping(f"{self.session_id}:{time.time()}")
  File "/bb/libexec/blinkbot/dependencies/site-packages/slack_sdk/socket_mode/builtin/connection.py", line 207, in ping
    self.sock.send(data)
  File "/opt/bb/lib/python3.9/ssl.py", line 1173, in send
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by seratch** [comment]
Hi @gpiks, thanks for writing in! 

This connection related error occurs background and under the hood in the low-level Socket Mode client in slack-sdk package. Therefore, it is not supposed to catch the error in your bolt-python event listeners. The `app.error` handlers are only responsible for the exceptions that occur in bolt-python middleware and listeners.

If you often observe the `BlockingIOError` in your Socket Mode app, something wrong with WebSocket connections might be happening in your network or environment. However, even in this scenario, I believe that the underlying `SocketModeClient` should automatically recover (in other words, reconnect to Slack) without restarting the app. If not, the issue should be resolved. 

If you think that this error logs are noise for your app monitoring, the latest version of slack-sdk (3.15.1) improved the error to have only single line: https://github.com/slackapi/python-slack-sdk/pull/1185

I hope this helps.

**Comment by gpiks** [comment]
> something wrong with WebSocket connections might be happening in your network or environment

Yeah sadly we are stuck with this issue in our network. 

The rest sounds good. We will ignore those errors for now.
