### ISSUE TITLE
Setting the logger for the Slack Bolt APP with a NullHandler still seems to log

### ISSUE THREAD

**Issue by mwilli20** [slackapi/bolt-python#612]
## Reproducible in:

```
slack_bolt >= 1.11.1
slack_sdk>=3.9.0,<4
```

## Python runtime version

`python3.9
`

## OS info

Not relevant

## Steps to reproduce:

```python
import logging
import os

from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler
from slack_sdk import WebClient

app_token = os.environ.get("SLACK_APP_TOKEN")
bot_token = os.environ.get("SLACK_BOT_TOKEN")
http_proxy = os.environ.get("SLACK_HTTP_PROXY")
signing_secret = os.environ.get("SLACK_SIGNING_SECRET")


# Our Logger
logger = logging.getLogger("our_logger")

# Logger passed into slack to silence internal noise
slack_logger = logging.getLogger("internal_slack")
slack_logger.addHandler(logging.NullHandler())


def create_app() -> App:
    client = WebClient(
        token=bot_token,
        proxy=http_proxy,
    )

    app = App(
        client=client,
        token=bot_token,
        ssl_check_enabled=False,
        signing_secret=signing_secret,
        logger=slack_logger,  # Expected this would silence the internal logs
    )

    @app.event("message")
    def handle_other_message_events(message, say) -> None:
        logger.info("Expect to see this as it is my logger")

        # ... Some Logic

    return app


if __name__ == "__main__":
    app = create_app()
    handler = SocketModeHandler(app, app_token, proxy=http_proxy)
    handler.start()
```

## Expected/Actual result

As a follow up to https://github.com/slackapi/bolt-python/issues/605 we decided to set our own logger and pass that into the app like what is shown here https://github.com/slackapi/bolt-python/blob/main/slack_bolt/app/app.py#L90 but this still lead to us seeing internal logs when running:

```
2022-03-04T18:56:25.130465+0000 WARNING [1:MainThread] app.py:203 As you gave `client` as well, `token` will be unused.
2022-03-04T18:56:25.763592+0000 INFO [1:MainThread] client.py:197 A new session has been established (session id: 719380c4-be12-4d31-80b7-2c4bacbfa608)
2022-03-04T18:56:25.763798+0000 INFO [1:MainThread] base_handler.py:50 ⚡️ Bolt app is running!
2022-03-04T18:56:25.800199+0000 INFO [1:Thread-1] client.py:278 Starting to receive messages from a new connection (session id: 719380c4-be12-4d31-80b7-2c4bacbfa608)
```

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @mwilli20, thanks for writing in!

I ran your script on my end. However, as expected, the `slack_logger` (null handler logger) does not print anything for me. 

I'm guessing that other parts of your app might affect your logging. For example, if your app has global configuration somewhere (= `logging.basicConfig(...)`), all your loggers may behave differently because a different handler can be enabled in addition to the null handler.

If you figure out the cause of your situation and it is due to this SDK, please let us know.

**Comment by mwilli20** [comment]
Totally right, when I explicitly set propagate to false on the logger passes in fixes it.
