### ISSUE TITLE
How to declare a new event on a different py file ?

### ISSUE THREAD

**Issue by DanielSalama1** [slackapi/bolt-python#613]
Hey !
i have 2 python files :

1) app.py [ the app.start() is located there ]
2) message_events.py

I want to add a new event ( for example : app.message('hello') ), but i want to put it in message_events.py ( not in my app.py where it initiates ).

how do i make the file being recognized when there are incoming events ?
doesn't seem to work for me when i do :

`from app import app

@app.message("hello")
def handle_message(body, logger):
    logger.info(body)`

When i did it, it ignored the file with it's code and told me that @app.message("hello") is missing.

how can i divide my app into multiple files ?

**Comment by filmaj** [comment]
Hey @DanielSalama1,

Thanks for writing in. Perhaps an example is the easiest way to describe how to split your app up across multiple files. Check out my colleague's app code: https://github.com/seratch/send-it-later-for-slack/tree/main/app

In particular, the main initialization logic is contained in `app.py`, which imports `app_oauth.py` and `listeners.py`. `app_oauth.py` [defines the Bolt for Python `App` class instance](https://github.com/seratch/send-it-later-for-slack/blob/main/app/app_oauth.py#L23). `listeners.py` defines a [`register_listeners` method](https://github.com/seratch/send-it-later-for-slack/blob/main/app/listeners.py#L21) that takes an `App` instance as an argument and defines the listener methods that are decorated with the `@app.message` decorators.

Using this pattern you should be able to separate your listeners across multiple files.

Hope this is helpful!
