### ISSUE TITLE
Questions on how to run a bolt-python app on AWS Lambda

### ISSUE THREAD

**Issue by imageschool** [slackapi/bolt-python#615]
(Describe your issue and goal here)

Using FastAPI with bolt-python

**Question 1.**

1. Within app.message("xxx") listener, I am sending 3 API requests to receive some status
2. Using the responses, I am sending combined summary into slack channel with Say().

![image](https://user-images.githubusercontent.com/29969006/158349166-b6446209-f5f6-418c-8c31-35b6f2823045.png)

4. For ReadTimeOut Error Exception, it sends error message fine
5. But When other exceptions (e.g) TypeError) is catched, say() function spits below exception message 
`
Traceback (most recent call last):
  File "/opt/anaconda3/envs/slack-lambda-api/lib/python3.9/site-packages/slack_bolt/listener/asyncio_runner.py", line 67, in run
    returned_value = await listener.run_ack_function(
  File "/opt/anaconda3/envs/slack-lambda-api/lib/python3.9/site-packages/slack_bolt/listener/async_listener.py", line 120, in run_ack_function
    return await self.ack_function(
  File "/Users/xxx/Workspace/slack-lambda-api/app/slack/handler/messages.py", line 40, in message_status
    await say(
TypeError: __call__() got multiple values for argument 'text'
`

- Above Exception was catched on my local environment where I deliberately turned off API Server

**Question2 (perhaps related to above error).**

1. In production, I am deploying bolt-python in AWS Lambda
2. I am trying to use lazy listener to bypass 3 seconds limit on slack api, I moved above listener logic to lazy parameter then used respond_to_slack_within_3_seconds() to ack() as written in documentation. (as below)

![image](https://user-images.githubusercontent.com/29969006/158350575-b4a249d4-c162-4619-9176-09cd93efa2e3.png)
![image](https://user-images.githubusercontent.com/29969006/158350397-38a4e308-79b4-46a3-8443-810ac85d894e.png)
![image](https://user-images.githubusercontent.com/29969006/158350513-520e8426-45eb-4c6d-b07b-bd46b446c9e4.png)

3. When I test in local above seems to work fine, but when deployed to AWS Lambda (using Mangum handler), it gives following errors ( same error as Question 1)
![image](https://user-images.githubusercontent.com/29969006/158351542-ff6d29e6-f8e8-4c40-a63d-8a7c9ff20f3f.png)

Thank you in advance!!

#### The `slack_bolt` version

slack-bolt==1.11.1
slack-sdk==3.13.0

#### Python runtime version
Python 3.9.7

#### OS info

ProductName:	macOS
ProductVersion:	12.0.1
BuildVersion:	21A559
Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101

### Expected result:

- Regarding Question 1, it should send message instead of exception
- Regarding Question 2, lazy function should be executed followed by ack function but only ack is run in AWS Lambda 

### Actual result:

(Included in descriptions)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @imageschool, your code in the exception-handling part is missing `blocks=` keyword for the first argument.

This means that your code should look like this:

```python
await say(
    blocks=Blocks.get_failed_....,
    text="msg",
)
```

If you have similar issues with other parts in your code, please double-check if your method calls have argument names for all arguments.

**Comment by imageschool** [comment]
> Hi @imageschool, your code in the exception-handling part is missing `blocks=` keyword for the first argument.
> 
> This means that your code should look like this:
> 
> ```python
> await say(
>     blocks=Blocks.get_failed_....,
>     text="msg",
> )
> ```
> 
> If you have similar issues with other parts in your code, please double-check if your method calls have argument names for all arguments.

Hi @seratch, oh.. silly me :\ for mixing up the keywords.. now I resolved the first issue and thank you very much!

Following on the second question,
I am still having an issue that await say() function is not responding when ran on AWS Lambda.
When I run in my local environment, it works great and send a message a test slack channel however, in production, AWS Lambda seems to ignore it. 

Do you have any idea what is happening?

- Screenshots are attached below!
![image](https://user-images.githubusercontent.com/29969006/158514126-fb8575aa-3faa-4fe5-a077-542d170bd1a1.png)
![image](https://user-images.githubusercontent.com/29969006/158514197-e2b43884-7bd3-4dff-b59a-e22aee1a7d07.png)

Many Thanks!

**Comment by seratch** [comment]
@imageschool with the given information, I cannot suggest anything helpful. I would suggest adding more try/catch for he say() method calls and checking the details for the raised errors.

**Comment by imageschool** [comment]
> @imageschool with the given information, I cannot suggest anything helpful. I would suggest adding more try/catch for he say() method calls and checking the details for the raised errors.

@seratch I have also tried adding bare except: ( which is against PEP8 ) if it can catch anything but i could not catch it.

- Weird thing is sometimes it is catched and sometimes it is not.
- I was only able to get that error message just a single time and it somehow does not raise anymore. (Also notice how the error was catched in different request, like after 2 mins from line logging `inf_res`)
- When I try multiple times to log what is happening it just weirdly seems to skip that await say() method.

- Also sometimes it is executed also in different request after some delay ( without error, screenshot below)
![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/776a9f9b-4096-460f-a052-077cb6f36895/Untitled.png)

Thank you for fast response!

**Comment by imageschool** [comment]
@seratch Do you mind having a look at above and let me know anything! I am quite stuck :/

**Comment by seratch** [comment]
@imageschool Having only screenshots is a bit hard to check your situation. Would you mind sharing your code as text? Ideally, sharing a minimal reproducible example code would be helpful for others.

**Comment by seratch** [comment]
@imageschool One thing that I just noticed is that you are trying to use `AsyncApp` and `AsyncSlackRequestHandler` for your Lambda app, right? We don't provide any built-in adapter for the combination of `AsyncApp` and asyncio on AWS Lambda. So, probably, you are using some of the built-in `AsyncSlackRequestHandler`s in this SDK. However, it's not a recommended way for running your apps on Lambda and I am afraid that it may not work as you expect.

My suggestions would be:

* Use [this built-in adapter](https://github.com/slackapi/bolt-python/blob/v1.13.0/slack_bolt/adapter/aws_lambda/handler.py) instead and stop implementing in the asyncio compatible way (if you have a certain reason to use Lamabda)
* Switch to other runtime such as container services (EKS or ECS in AWS) to run your asyncio-compatible app as-is

I hope this helps.

**Comment by imageschool** [comment]
@seratch I have just pushed an example code (https://github.com/imageschool/slack-bolt-python-aws-lambda-error-example) for anyone to reproduce my issue.

Now I will try to apply what you have pointed out and let you know.

Thanks!

**Comment by seratch** [comment]
@imageschool Thanks for sharing the code (I didn't know `mangum` pacakage - the one is super cool!).

There are a few things that I can suggest:

* The `message_status` method execution (including the overhead of cold-start on AWS Lambda) can take longer than 3 seconds. I would suggest moving the method to lazy listeners.

```python
async def just_ack():
    pass

def register_listeners(app: AsyncApp):
    # Messages
    # app.message("status")(message_status)
    app.message("status")(ack=just_ack, lazy=[message_status])
    app.message("magic")(
        ack=respond_to_slack_within_3_seconds,
        lazy=[message_magic]
    )
```

* If you have two `app.message` listeners and the text matches both, only the first defined one (in the case of your example, "magic status" matches only `app.message("status")`) can be executed. If you have a bit complex matching pattern, we suggest dispatching requests inside your listener, not by the matching conditions


Is everything clear now?

**Comment by imageschool** [comment]
@seratch Thanks for letting me know both matching cases! I didn't have much thought on it before!

Actually `message_status()` method and `message_magic()` method have the exact same functionality
(I just separated them, sorry for the confusion ).

I was using `message_status()` method execution without lazy listener, intentionally to show that it works okay without lazy listener (I am going to only use lazy listener as soon as the problem is solved)

![image](https://user-images.githubusercontent.com/29969006/159470365-6c8d8c88-b454-4670-82e8-59dfd6a1f65b.png)
My issue was `say()` method (within `message_magic()` method) not being executed while using lazy function as above.

Following your first suggestion (In case I am not switching to container runtime in AWS),
1. I removed asyncio comfortable implementations
  - `AsyncApp` -> `App`
  - `AsyncSlackRequestHandler` -> `SlackRequestHandler(aws_lambda one)`
  - Removed `await` / `async` keywords
2. Also, as you mentioned, I am using `mangum` as an adapter for running FastAPI with bolt-python.
3. While `slack_bolt.adapter.aws_lambda.SlackRequestHandler` is a handler itself for for AWS Lambda function, how can I integrate them in my design? (While using mangum as a handler for AWS Lambda)

**Comment by imageschool** [comment]
@seratch You are right, I don't need mangum anymore!

Thank you so much for your follow-ups, help and insights!

I have now used `slack_bolt.adapter.aws_lambda.SlackRequestHandler` handler instead of mangum and now everything works as intended!

This made my day, thanks once again!!

p.s, updated pushed working example to https://github.com/imageschool/slack-bolt-python-aws-lambda-error-example for anyone having similar issue!
