### ISSUE TITLE
Delay in opening modals/shortcuts for application hosted in aws lambda + api gateway

### ISSUE THREAD

**Issue by r4ibOm** [slackapi/bolt-python#625]
I have an application hosted on aws using lambda + api gateway and I'm having a delay problem when opening modals, shortcuts etc

This happens when I open some functionality right after uploading to the cloud. After I open it for the first time, all app features start to open quickly. It looks like some kind of cache and then it crashes again like in the gif presented.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/44219005/159803346-07ff0a71-d814-4922-a604-e5bc1b3adf0b.gif)

I tried to debug in several ways but I still couldn't understand the source of the problem. I don't know if it's in the gateway api (I even tried to enable the api cache but it didn't work), or in the application or in some other type of slowness along the way that I couldn't identify.

I put several prints with the execution time to try to identify if it was in some part of my code, but as you can see, when I click to open a sortcut for example, the load time is less than 2 seconds until the modules are full loaded. 
When I open it for the second time, only the print of "start" appears, suggesting that it opened directly from some cache.

![image](https://user-images.githubusercontent.com/44219005/159802363-05a0539b-2215-4660-95b2-10b984349910.png)

![image](https://user-images.githubusercontent.com/44219005/159802307-d8a50cf4-624e-4b0f-aeb5-d0bcef1802db.png)

I've already tested it in two different AWS accounts and the same problem occurs.

**Comment by seratch** [comment]
Hi @r4ibOm, thanks for asking the question!

With the limited information given here, I cannot guess what the exact reason of your issue. However, probably your issue may be related to common "cold-start" issue (=overhead for spinning up a new Lambda runtime and loading resources). Refer to my response to a past question here: https://github.com/slackapi/bolt-js/issues/816#issuecomment-786360926

Also, searching past issues under slackapi org may be helpful too: https://github.com/search?q=org%3Aslackapi+aws+lambda&type=issues

I hope this was helpful to you and you will figure the cause out soon!

**Comment by r4ibOm** [comment]
Hi @seratch ,
Thank you for the tips. I'm new to this cloud world and I didn't know about this cold start.
I did some research and analysis on my project.
In my requirements, there is only slack bold and requests libraries  As you can see my project is small and has only 2.3 MB:

![image](https://user-images.githubusercontent.com/44219005/159934544-e41e4006-fc5f-4b21-9004-95373224ea25.png)

Being able to reduce even more by removing some libraries that already come native to aws such as boto 3 and botocore, even so the problem persists. I'm still researching to try to understand what might help.
