### ISSUE TITLE
Cannot update a message in DM

### ISSUE THREAD

**Issue by jimmymaise** [slackapi/bolt-python#626]
(Filling out the following details about bugs will help us solve your issue sooner.)

### Reproducible in:

```python
        ts_new = client.chat_postMessage(
            channel='UF0LMSUDT',
            text='eeee'
        )

        client.chat_update(
            channel='UF0LMSUDT',
            ts=ts_new['ts'],
            blocks=[],
            text=f'update success')
```

Try to add as_user=True but still doesn't work

```python
        client.chat_update(
            as_user=True,
            channel='UF0LMSUDT',
            ts=ts_new['ts'],
            blocks=[],
            text=f'update sucess')
```
Try to change  client.chat_delete, message will be deleted ==> There is no problem with ts

```python
        client.chat_delete(
            as_user=True,
            channel='UF0LMSUDT',
            ts=ts_new['ts'],
            blocks=[],
            text=f'update sucess')
 ```

#### The `slack_bolt` version

(Paste the output of `pip freeze | grep slack`)
slack-bolt==1.13.0
slack-sdk==3.15.2
slackeventsapi==3.0.1

#### Python runtime version

(Paste the output of `python --version`)
Python 3.7.4

#### OS info

(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)
Darwin Kernel Version 19.6.0: Sun Nov 14 19:58:51 PST 2021; root:xnu-6153.141.50~1/RELEASE_X86_64
#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1. Create a message and get ts
2. Update message with this ts

### Expected result:
Message is updated

(Tell what you expected to happen)

### Actual result:
Got error:
The server responded with: {'ok': False, 'error': 'message_not_found'})

(Tell what actually happened with logs, screenshots)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @jimmymaise, thanks for asking the question.

`chat.postMessage` API can accept a user ID instead of a channel ID and the API automatically starts a new DM with the given user for you. However, `chat.update` does not work in the same way as it needs a valid channel ID to identify the message to update. 

The API response from `chat.update` should have the message's channel ID (it should start with D prefix). Please use the ID instead of the user ID.

I hope this helps!

**Comment by jimmymaise** [comment]
@seratch: Thank you for your support. Just have a question why I still can use the user_id as a channel id to delete the message?

**Comment by seratch** [comment]
@jimmymaise Oh, honestly I didn't know that you can use user_id for `chat.delete` too. 

Either way, we generally recommend always using channel ID. For DMs, you can call `conversations.open` at any time for knowing a DM's channel ID. If there is no DM yet, it opens a new DM. If the DM already exists, the API just returns the ID.

Is everything clear now?

**Comment by jimmymaise** [comment]
Yes. It's clear now

**Comment by nil12285** [comment]
Hi @seratch 
I am facing a similar issue. Getting **cant_update_message** error when using `client.chat_update`.
Can you help me with this?

# Environment
Slack Free Plan
Python 3.11.4
slack-bolt==1.18.0
slack-sdk==3.21.3

# App Bot Scopes

- app_mentions:read
- channels:join
- chat:write
- im:write
- reactions:write
- commands

```
from slack_sdk import WebClient
from .models import SlackInstallation

@slack_app.event(event="message")
def scann_message(logger, message, context: BoltContext):
    text = message.get('text','')
    bot_app = SlackInstallation.objects.filter(client_id=settings.SLACK['CLIENT_ID']).order_by('-installed_at').first()
    slack_client = WebClient(token=bot_app.bot_token)
    
    slack_client.chat_update(
                channel=message['channel'],
                ts=message['ts'],
                as_user=True,
                text=f"::::{text}::::"
            )
```

**Comment by seratch** [comment]
@nil12285 Your question is a different one. The message you're attempting to update was posted by a human user (or a bot user from a different app). Naturally, your app can't modify this message since it was not posted by the app itself. If your app has received a user token with the `chat:write` scope from the human who posted the message, your app can update the message on their behalf. Without this, there is no way to update other people's messages solely using a bot user token.

**Comment by nil12285** [comment]
@seratch thanks for getting back to me this quickly and for clarification.  Really appreciated.

I have `chat:write`  in my scope,  but I don't get user_token in the payload for the message event. Can you please guide me on how can I get the user token?


Values for scope are mentioned above and user_scope = chat:write

```
slack_app = App(
    signing_secret=settings.SLACK["SIGNING_SECRET"],
    oauth_settings=OAuthSettings(
        client_id=settings.SLACK["CLIENT_ID"],
        client_secret=settings.SLACK["CLIENT_SECRET"],
        scopes=settings.SLACK["SCOPES"].split(","),
        user_scopes=settings.SLACK.get("USER_SCOPES","search:read").split(","),
         installation_store=DjangoInstallationStore(
            client_id=settings.SLACK["CLIENT_ID"],
            logger=logger,
        ),
        state_store=DjangoOAuthStateStore(
            expiration_seconds=120,
            logger=logger,
        ),
        callback_options=callback_options
    ),
)
```

**Payload  of message in @slack_app.event(event="message")**
```
{
	'client_msg_id': '1099ac7d-57d2-4429-8drb-ca2a5f3c07e7',
	'type': 'message',
	'text': 'hi',
	'user': 'U01HFY2JQ84',
	'ts': '168949568.523379',
	'blocks': [{
		'type': 'rich_text',
		'block_id': 'LRA',
		'elements': [{
			'type': 'rich_text_section',
			'elements': [{
				'type': 'text',
				'text': 'hi'
			}]
		}]
	}],
	'team': 'T01H9AB99MH',
	'channel': 'C01LA3RHV98',
	'event_ts': '1689181568.561079',
	'channel_type': 'channel'
}
```

**Comment by nil12285** [comment]
@seratch thanks
