### ISSUE TITLE
Decouple logic from events

### ISSUE THREAD

**Issue by dschinkel** [slackapi/bolt-python#627]
I do not want a bunch of logic in my app.ts where I define my slack events.  For example:

```js
app.view('create_crafter_submission', async ({ ack, body, view }) => {
  const email = view.state.values.email.email_input.value;
  if (!emailIsValid(email)) {
    await sendEmailValidationError(ack);
    return;
  }
}
```

The problem here is the `return;`.  You have to return in the case of an invalid email so that you don't submit the form.  

If I move in the email contstant and the if statement into `sendEmailValidationError()` the problem is we aren't returning anymore.

```js
export async function sendEmailValidationError(ack: any) {
  const errors: any = {};
  errors.email = 'Invalid Email, try again';
  await ack({
    response_action: 'errors',
    errors,
  });
}
```

So consequently it breaks my event.

Any ideas how I can move the related logic into my centralized `sendEmailValidationError` function and still satisfy the event here?

**Comment by seratch** [comment]
@dschinkel Let me transfer this issue to bolt-js repo first.

**Comment by dschinkel** [comment]
yea sorry doing that now.
