### ISSUE TITLE
Add adapter for Zappa (flask) or example

### ISSUE THREAD

**Issue by rezen** [slackapi/bolt-python#628]
Zappa is a commonly used lambda framework that smushes your Flask app into a lambda. It also provisions and sets up related AWS resources for running the app which is super helpful. I tried leveraging the Flask example and deploying with Zappa, but it didn't work, which isn't surprising since "under the hood" it's actually a lambda invoking the Flask routes. I tried tweaking the flask example with this bit below, but it wasn't quite right. It seemed like events were not being properly processed, I'm not sure.

```python
app = App(
    process_before_response=True,
# ...
```
https://github.com/zappa/Zappa

### Category (place an `x` in each of the `[ ]`)

* [ ] **slack_bolt.App** and/or its core components
* [ ] **slack_bolt.async_app.AsyncApp** and/or its core components
* [x] Adapters in **slack_bolt.adapter**
* [ ] Others

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @rezen, thanks for writing in!

Zappa looks so cool! If I understand correctly, Zappa runs Flask, Django, and so on as-is on FaaS. As long as your Flask app works along with Zappa on FaaS, your bolt-python app should not need any adapter on the bolt-python side.

> process_before_response=True

Yes, this option must be enabled for FaaS use case.

Can you share a bit more details such as your current source code, the errors that you are facing with us? In the same reason with https://github.com/slackapi/bolt-python/issues/619#issuecomment-1073182688 for Quart framework, supporting Zappa is not our high priority. We are happy to help you out as much as possible but we don't have the bandwidth to create a new example in the short term.

Also, I know that you are planning to use Zappa for your app management but in general, we highly recommend our simple aws-lambda adapter. With the adapter, you can more easily take advantage of built-in features such as lazy listeners: https://slack.dev/bolt-python/concepts#lazy-listeners For FaaS use cases, lazy listeners are so powerful. Implementing the same on your own would require more efforts and research.

I hope this was helpful to you!
