### ISSUE TITLE
Utilising slack-bolt to perform token rotation and question on InstallationStore

### ISSUE THREAD

**Issue by gkeown03** [slackapi/bolt-python#631]
Hi,

Please bear with with me as I'm brand new to both slack apps and bolt...we have an app that previously was able to authenticate via slack-bolt using a Bot User OAuth Token. All that was required was a SLACK_BOT_TOKEN and SLACK_SIGNING_SECRET in the environment and everything worked fine. This is all the setup I can see in the current code:

```
app = App(
    signing_secret=os.environ.get("SLACK_SIGNING_SECRET")
)
```

However token rotation has been turned on (not sure why, developer who did this no longer around) and in the last week we can no longer authenticate using this. I have been looking into Slack token rotation in the last couple of days and found that I could generate access tokens based on a refresh token (under OAuth & Permissions) in Postman (POST / https://slack.com/api/oauth.v2.access) and then update SLACK_BOT_TOKEN to this new access token value to get the app working temporarily (token expires after 12 hours).

This obviously isn't desirable as according to the docs, slack-bolt can handle this for me:

https://slack.dev/bolt-python/concepts#token-rotation
https://slack.dev/bolt-python/concepts#authenticating-oauth

I am struggling to figure out how to do this though, I copied and pasted the example code from the link above and updated my environment variables to include client_id and client_secret:

```
oauth_settings = OAuthSettings(
    client_id=os.environ["SLACK_CLIENT_ID"],
    client_secret=os.environ["SLACK_CLIENT_SECRET"],
    scopes=["channels:read", "groups:read", "chat:write"],
    installation_store=FileInstallationStore(base_dir="./data/installations"),
    state_store=FileOAuthStateStore(expiration_seconds=600, base_dir="./data/states")
)

app = App(
    signing_secret=os.environ["SLACK_SIGNING_SECRET"],
    oauth_settings=oauth_settings
)
```

But running into the following error when handling event in our app:

> WARNING:slack_sdk.oauth.installation_store.file:Failed to find an installation data for enterprise: none, team: T01DCRQM72B: [Errno 2] No such file or directory: '/Users/gkeown/.bolt-app-installation/1454874721079.2172634096818/none-T01DCRQM72B/installer-latest'
> WARNING:slack_sdk.oauth.installation_store.file:Failed to find bot installation data for enterprise: none, team: T01DCRQM72B: [Errno 2] No such file or directory: '/Users/gkeown/.bolt-app-installation/1454874721079.2172634096818/none-T01DCRQM72B/bot-latest'
> DEBUG:slack_bolt.oauth.oauth_settings:No installation data found for enterprise_id: None team_id: T01DCRQM72B
> ERROR:slack_bolt.MultiTeamsAuthorization:auth.test API call result is unexpectedly None

I've tried to find out more information about the FileInstallationStore and the FileOAuthStateStore but it's really unclear to me what these are used for and what I need to do to set up token rotation via slack-bolt correctly. Complete newbie, so do forgive me.

Any help much appreciated.

#### The `slack_bolt` version

slack-bolt==1.7.0

#### Python runtime version

Python 3.10.3

#### OS info
ProductName:	macOS
ProductVersion:	12.2.1
BuildVersion:	21D62

Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by srajiang** [comment]
@gkeown03 - The error appears to be related to trying to lookup an installation that doesn't exist. Is it possible you are trying to handle an event for a workspace that you haven't completed the full OAuth flow for yet?

FileInstallationStore is the default implementation of the `installationStore` - it uses your local file system to save and fetch installation data. It's fine to use in development (so looks like that's the case since you're just trying to get things up and running at the moment).

**Comment by srajiang** [comment]
@gkeown03 - Also, zooming out here to doublecheck, does your app need to be installed in multiple workspaces (oauth-enabled) or do you just need it to be installed in one directory? I ask since previously your app just used a Bot Token and Signing Secret. 

 If your app doesn't need to be oauth-enabled, perhaps you don't need Token Rotation turned on.

**Comment by srajiang** [comment]
@gkeown03 - Nice! I'll go ahead and close this issue up.
