### ISSUE TITLE
aws_lambda example fails due to missing role

### ISSUE THREAD

**Issue by cp2423** [slackapi/bolt-python#632]
Following the aws_lambda readme (see link below) the app does not work. In slack I got a an error message, and the CloudWatch logs reported found [user id redacted]:

b'{
    "Message": "User: arn:aws:sts::************:assumed-role/bolt_python_lambda_invocation/bolt_py_function is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:eu-west-2:************:function:bolt_py_function because no identity-based policy allows the lambda:InvokeFunction action"
}'

I resolved this by adding the "AWSLambdaRole" to the user. So I suggest the following line in the docs needs to be updated, from:

* Check the "AWSLambdaBasicExecutionRole" and "AWSLambdaExecute" policies

to:

* Check the "AWSLambdaBasicExecutionRole", "AWSLambdaExecute" and "AWSLambdaRole" policies

Please note I am no AWS expert, it might be that this extra role renders one of the others redundant, I do not know! But I know this change is sufficient to make the example work :)

### The page URLs

* https://github.com/slackapi/bolt-python/blob/main/examples/aws_lambda/README.md

**Comment by filmaj** [comment]
Hey @cp2423, thanks for pointing this out! Indeed you are right, Invoke is a requirement. I will update the docs shortly!
