### ISSUE TITLE
Can someone help me debug my code for this event listener & say function? 

### ISSUE THREAD

**Issue by irrational-labs** [slackapi/bolt-python#637]
Hey all! I'm new to this package and have been working on a slackbot to auto-reply to all posts in a specific channel. I've been trying this for like 5 hours now and am not making any progress, so I figured I'd share with this community & see if anyone had some pointers. It says that the bolt app has been working in the terminal. 

### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version

slack-bolt==1.13.0
slack-sdk==3.15.2

#### Python runtime version

Python 3.8.5

#### OS info

ProductName:	macOS
ProductVersion:	11.5.2
BuildVersion:	20G95
Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64
#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1. Enable socket mode on the app
2. allow slackbot to have access to message.channels event
3. Run app.py file (see below)

```python 
import os
# Use the package we installed
from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler
import re

# Initializes your app with your bot token and signing secret
app = App(
    token=os.environ["SLACK_BOT_TOKEN"]
)

# Add functionality here

@app.event("message.channels")
def auto_reply(event, say):
    try:
        if event['channel'] == 'C03DB6U9U8Y': #if statement clarifying channel to watch for
            say("An IL specialist will be with you shortly")
    except Exception as e:
        logger.error(f"Error publishing home tab: {e}")


# Start your app
if __name__ == "__main__":
    SocketModeHandler(app, os.environ["SLACK_APP_TOKEN"]).start()
```

### Expected result:

Error log telling me what's going on or a successful auto-reply to the messages

### Actual result:

No error logged in the terminal, no auto-reply. 

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by srajiang** [comment]
@irrational-labs Can you turn on [debug logging ](https://slack.dev/bolt-python/concepts#logging)and share the output that you see when you trigger this event in your workspace?

**Comment by irrational-labs** [comment]
@srajiang thank you for the super fast reply! here you go :) 

'''DEBUG:slack_bolt.App:Sending a request - url: https://www.slack.com/api/auth.test, query_params: {}, body_params: {}, files: {}, json_body: None, headers: {'Content-Type': 'application/x-www-form-urlencoded', 'Authorization': '(redacted)', 'User-Agent': 'Bolt/1.13.0 Python/3.8.5 slackclient/3.15.2 Darwin/20.6.0'}
DEBUG:slack_bolt.App:Received the following response - status: 200, headers: {'date': 'Fri, 22 Apr 2022 22:13:24 GMT', 'server': 'Apache', 'x-powered-by': 'HHVM/4.153.1', 'access-control-allow-origin': '*', 'referrer-policy': 'no-referrer', 'x-slack-backend': 'r', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'access-control-allow-headers': 'slack-route, x-slack-version-ts, x-b3-traceid, x-b3-spanid, x-b3-parentspanid, x-b3-sampled, x-b3-flags', 'access-control-expose-headers': 'x-slack-req-id, retry-after', 'x-oauth-scopes': 'app_mentions:read,channels:history,channels:join,channels:manage,channels:read,chat:write.customize,chat:write.public,chat:write,files:read,files:write,groups:history,groups:read,groups:write,im:history,im:read,im:write,links:read,links:write,mpim:history,mpim:read,mpim:write,pins:read,pins:write,reactions:read,reactions:write,reminders:read,reminders:write,team:read,usergroups:read,usergroups:write,users:read,users:write,users.profile:read', 'expires': 'Mon, 26 Jul 1997 05:00:00 GMT', 'cache-control': 'private, no-cache, no-store, must-revalidate', 'pragma': 'no-cache', 'x-xss-protection': '0', 'x-content-type-options': 'nosniff', 'x-slack-req-id': '62406de6621cf3cba0afa3292e9944b4', 'vary': 'Accept-Encoding', 'content-type': 'application/json; charset=utf-8', 'x-envoy-upstream-service-time': '17', 'x-backend': 'main_normal main_bedrock_normal_with_overflow main_canary_with_overflow main_bedrock_canary_with_overflow main_control_with_overflow main_bedrock_control_with_overflow', 'x-server': 'slack-www-hhvm-main-iad-wadv', 'x-slack-shared-secret-outcome': 'no-match', 'via': 'envoy-www-iad-gn7k, envoy-edge-iad-k0yh', 'x-edge-backend': 'envoy-www', 'x-slack-edge-shared-secret-outcome': 'no-match', 'connection': 'close', 'transfer-encoding': 'chunked'}, body: {"ok":true,"url":"https:\/\/behavioral-design-bc.slack.com\/","team":"Behavioral Design Bootcamp","user":"il_autoreply_coach","team_id":"T018T2H4T1T","user_id":"U03C5Q4BSB1","bot_id":"B03CZ1A20JV","is_enterprise_install":false}
INFO:slack_bolt.App:⚡️ Bolt app is running! (development server)'''

**Comment by irrational-labs** [comment]
@srajiang this was the initial debug screen, when I trigerred the event from the workspace nothing happened :( 
I'm using the bot & app tokens I was given, so not too sure what the issue is

**Comment by srajiang** [comment]
Okay let's check that you've subscribed to the message.channels event. Can you head to your Slack App configuration page > Event Subscriptions and check that you're subscribed to the event that you want to listen for?

Sarah

**Comment by irrational-labs** [comment]
hmm i tried doing that as well and it still didn't work or show a bug on the log. my workplace is the free version, do you think that would affect anything? @srajiang

**Comment by irrational-labs** [comment]
@srajiang i made a rookie mistake and accidentally was drawing from a blank template file... used the real code and it works now. thanks for your help!

**Comment by srajiang** [comment]
@irrational-labs - Oh sweet, glad to know you were able to get it working!
