### ISSUE TITLE
is_enterprise_install does not exist in context object

### ISSUE THREAD

**Issue by Sadisms** [slackapi/bolt-python#639]
Hi, I configured the bot for the entire grid, installed it, and when I receive the payload in the body, I have the status is_enterprise_install as True, but when I try to pull the current from SQLite (AsyncOAuthFlow.sqlite3) find_installation, context.is_enterprise_install is passed there, although this argument is not set in the context itself, and therefore I get a message that the bot is not installed, because it tries to find a bunch of team_id and enterprise_id, but when installed on the entire grid, the team_id remains empty. AsynSocketHandler is used to get the payload.

![image](https://user-images.githubusercontent.com/63108004/165730561-8c5f320c-4e08-4f07-b98d-e31bb018b155.png)

```py
app = AsyncApp(
    token=SlackData.BOT_TOKEN,
    signing_secret=SlackData.SIGNING_SECRET,
    oauth_flow=AsyncOAuthFlow.sqlite3(
        database='._.db',
        client_id=SlackData.CLIENT_ID,
        client_secret=SlackData.CLIENT_SECRET,
        scopes=...
    )
)
```

In addition, I can say that context.context.is_enterprise_install returns None everywhere, not only during authorization

> Python 3.8
> Windows Server 2016
> Slack-Sdk 3.15.2
> Slack-Bolt 1.13.0

**Comment by Sadisms** [comment]
I think I need to add a line

```py
context['is_enterprise_install'] = body['is_enterprise_install']
```

 in `slack_bolt.request.async_iternals(and iternals).build_async_context(and build_context)`

**Comment by seratch** [comment]
Hi @Sadisms, thank you very much for taking the time to report this issue. I just submitted a pull request resolving this issue. We will ship a new patch version as early as possible.
