### ISSUE TITLE
say() doesn't with some events  (e.g., "reaction_added")

### ISSUE THREAD

**Issue by seratch** [slackapi/bolt-python#64]
`say()` method may fail due to the proper extraction of channel ID inside Bolt for Python. One example we detected is "reaction_added" but we should check if there are any other patterns. We can find all the patterns that should be supported in [Bolt for JS's test code](https://github.com/slackapi/bolt-js/blob/f8c25ffb5cd91827510bbc689e97556d2d5ad017/src/App.spec.ts#L1123).

#### The `slack_bolt` version

version 0.4.0a0

#### Python runtime version

any

#### OS info

any

#### Steps to reproduce:

```python
@app.event("reaction_added")
def foo(say):
    say("foo")
```

```
DEBUG:slack_bolt.App:Checking listener: foo ...
DEBUG:slack_bolt.App:Running listener: foo ...
ERROR:slack_bolt.App:say without channel_id here is unsupported
Traceback (most recent call last):
  File "/path-to-project/app/app.py", line 375, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/path-to-project/listener/custom_listener.py", line 46, in run_ack_function
    return self.ack_function(
  File "samples/app.py", line 31, in foo
    say("foo")
  File "/path-to-project/context/say/say.py", line 52, in __call__
    raise ValueError("say without channel_id here is unsupported")
ValueError: say without channel_id here is unsupported
```

### Expected result:

The app can post a message in the channel.

### Actual result:

`ValueError` shared above.

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by Nowado** [comment]
I've run into the same issue attempting

```
@app.view('name')
async def name(say):
    say('text')
```

I'm not sure if I should open new issue, since it seems like the same exact problem.
