### ISSUE TITLE
Slack Slash Command using Azure function

### ISSUE THREAD

**Issue by sprider** [slackapi/bolt-python#641]
Hi Team,

Do you have any samples for Slack Slash Commands using Azure Function(HTTP Trigger), Slack bolt, and python?

Thank you for the time to review this question!

**Comment by seratch** [comment]
Hi, it is possible but I don’t recommend it. When I tried it two years ago, Azure Function’s cold start bootstrapping time tended to take a few seconds. This is a critical blocker for Slack apps.

That being said, the platform may be improved after that. If you still want to try, please feel free to reuse my example here: https://github.com/seratch/bolt-python/commit/b64eaa05d927cc85ec9f360eb1e3a5c12530d5b7

As for the slash command example code, refer to our documents at https://slack.dev/bolt-python/

I hope this helps!

**Comment by sprider** [comment]
@seratch, Thank you so much for your reply! I am trying to find how to acknowledge the slash command within 3 seconds as per Slack requirement. 

Is it possible to send acknowledgment as below: 

```
import logging
import time
from urllib.parse import parse_qs

import azure.functions as func
import requests


def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')

    req_body_bytes = req.get_body()
    req_body = req_body_bytes.decode("utf-8")

    text = parse_qs(req_body)["text"][0]
    response_url = parse_qs(req_body)["response_url"][0]

    # post a acknowledgement to slack
    requests.post(response_url, json={"text": "Processing your request..."})

    time.sleep(5)

    return func.HttpResponse(
        f"You submitted this information: {text}",
        status_code=200,
    )

```

**Comment by seratch** [comment]
@sprider The message "Processing your request..." will be successfully posted in the channel but the acknowledgment never suceeds.

**Comment by sprider** [comment]
> @sprider The message "Processing your request..." will be successfully posted in the channel but the acknowledgment never suceeds.

@seratch Yes, that is what happened. Any other ways we can acknowledge and wait for other operations to complete?

**Comment by seratch** [comment]
@sprider We provide [lazy listeners](https://slack.dev/bolt-python/concepts#lazy-listeners) for AWS Lambda but it's not available for Azure Functions. Also, we don't have any plans to support Azure Functions. 

The only approach that I can suggest is to asynchronously run the time-consuming task in a different Azure function. Is everything clear now?

**Comment by sprider** [comment]
Sure, I will do that. Thank you so much!
