### ISSUE TITLE
Slackbot + Docker + ngrok results in Dispatch_failed

### ISSUE THREAD

**Issue by sharathsridhar** [slackapi/bolt-python#642]
Running the slackbot (built in python + flask) within PyCharm works fine, as in commands are executed and payloads/modals are being sent received. And so does running the command `gunicorn --bind 0.0.0.0:5000 wsgi:flaskApp -w 4` within PyCharm's termnal (Please note, ngrok is running on mac's terminal via `./ngrok http 5000`). The url in "Interactivity & Shortcuts" AND "Slash Commands" both point to https://...ngrok.io/slack/events. Again, the app, the commands, ngrok, everything works fine.

But when I move the slack app to within Docker and start Docker up with `docker-compose up --build` which in turns runs `ENTRYPOINT ["gunicorn", "--bind", "0.0.0.0:5000", "wsgi:flaskApp", "--workers", "4"]`, the slackbot fails with `dispatch_failed` when a command is executed and ngrok terminal shows `502 Bad Gateway`. The docker command/image, itself runs fine without any errors, but for some reason it isn't able to recognize the url exposed by ngrok. Any ideas what's wrong?

Sorry, this is not a Slack-bolt issue itself, but any help would be appreciated.

Dockerfile

```FROM python:3.7
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt ./

COPY Main.py wsgi.py EmailSender.py AppConfig.py CompareCopyFgData.py SlackPayload.py Queries.py ./

RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

ENV FLASK_APP=Main.py
ENV FLASK_ENV=production

ENTRYPOINT ["gunicorn", "--bind", "0.0.0.0:5000", "wsgi:flaskApp", "--workers", "4"]
```

docker-compose.yml
```
version: "3.9"
services:
  slackbot:
    build: 
      context: App/
      dockerfile: Dockerfile
    env_file:
      - ./App/.env
```

### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version

slack-bolt==1.8.0
slack-sdk==3.10.1

#### Python runtime version

Python 3.9.6
Python in Docker (3.7)

#### OS info

(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)
ProductName:    macOS
ProductVersion: 12.3.1
BuildVersion:   21E258

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1. Start ngrok in a terminal using `ngrok http 5000`
2. Set up docker-compose.yml and Dockerfile with the appropriate files and run commands
3. In a new terminal, point to the folder containing docker-compose.yml image and run command `docker-compose up --build`
4. If no errors, go to slack and run a slash command and wait to see logs in Docker Terminal window

### Expected result:

Docker to accept incoming slack commands and print logs, send modal(s) to slack and receive user inputs etc

### Actual result:

Nothing happens in docker. The 4 workers are started and keep waiting/listening for a payload/data to come in, even though ngrok is running.

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.
<img width="739" alt="Screen Shot 2022-05-01 at 2 17 27 PM" src="https://user-images.githubusercontent.com/13225331/166165982-f6151d13-d8f3-4d88-a761-756df42ae3f6.png">
<img width="848" alt="Screen Shot 2022-05-01 at 2 17 45 PM" src="https://user-images.githubusercontent.com/13225331/166165983-10f8d49c-f4ac-45e4-8770-4592e88bfff6.png">

**Comment by seratch** [comment]
Hi @sharathsridhar, your docker-compose.yml needs the part to expose ports.

```yaml
    ports:
      - "5000:5000"
```

If you would like to check a complete example, refer to my example: https://github.com/seratch/send-it-later-for-slack/blob/b35d55aa2d06dd0df03ab4483d0a0dd4234c15f8/docker-compose.yml#L21-L22

Is everything clear now?

**Comment by sharathsridhar** [comment]
@seratch This is beautiful! I just wanna cry, Thank you so much, this was the issue and its fixed now. I thought, that since docker initially said "| [2022-05-01 22:49:42 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)", the 5000 port was already exposed.

Thanks again!
