### ISSUE TITLE
403 response (Received an unexpected response for handshake) when running socket handler in AWS ECS inside VPC

### ISSUE THREAD

**Issue by chris104957** [slackapi/bolt-python#643]
When I try to run my slack bot in AWS ECS, inside a VPC, I get a 403 error on attempting to start the handler. I am running the exact same code locally where it works fine. I have double checked that my local and AWS instances of my bot are using identical tokens.

#### The `slack_bolt` version
slack-bolt==1.13.1

#### Python runtime version
Python 3.9.1

#### OS info

Can't provide - its running in an AWS ECS container 

#### Steps to reproduce:

I have the below file deployed to ECS in a very simple docker container:

```python
from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler
from loggers import LOGGER

SLACK_BOT_TOKEN = os.environ['SLACK_BOT_TOKEN']
SLACK_APP_TOKEN = os.environ['SLACK_APP_TOKEN']

app = App(
    token=SLACK_BOT_TOKEN,
)

if __name__ == "__main__":
    LOGGER.debug('Attempting to start Slack socket handler')
    handler = SocketModeHandler(app, SLACK_APP_TOKEN, logger=LOGGER, trace_enabled=True)
    LOGGER.debug(f'Created handler: {handler}')
    handler.start()
```

### Expected result:

The handler should connect successfully, as it does locally

### Actual result:

The handler fails to connect and I get a 403 error. Here's the traceback I am getting from Cloudwatch:
![image](https://user-images.githubusercontent.com/24718987/167628136-a2278ad1-cc72-4047-87bc-5cf18a583d03.png)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @chris104957, thanks for writing in.

I cannot guess the exact reason of your issue yet but I can suggest a few things for narrowing your issue down a bit more:
* Do you see the same situation when running a Docker container process configured by the same Dockerfile in your local machine? If yes, the way to run your container or image configuration can be improved.
* If you see the issue only with the ECS container, any of load balancers or a proxy server between your app and Slack server might be preventing the WebSocket upgrade request. Double-checking anything specific to the VPC environment may help.
* The openssl version or something related might be outdated when the issue arises. The Slack server does not accept TLS 1.0/1.1 requests.

I hope that you will figure the cause out soon!

**Comment by chris104957** [comment]
It works locally when I run the same docker container locally. The same docker container does not work in ECS.

When I first saw that it was a 403 response, I assumed that I'd not set some of the variables correctly, but I have checked this many times now and the configuration is identical. I've tried manually setting the app token to something that I know is invalid, but this produces a different error, so the token being wrong does not appear to be the issue here.

There are no load balancers/proxy servers in play here

**Comment by seratch** [comment]
Since your app successfully received the WSS URL in an [`apps.connections.open`](https://api.slack.com/methods/apps.connections.open) API response, your app-level token should be valid even in the ECS container. Also, an interesting fact here is that the outgoing `apps.connections.open` API call is successful while the WSS connection establishment fails. I am still unsure about the possible cause of this but something may be preventing only requests to the Slack WSS endpoint.

How about creating an EC2 instance in the VPC and then making sure if the same Python app works outside the ECS environment? If it works, something specific to ECS would be the cause.

**Comment by filmaj** [comment]
Hey @chris104957, I'm following up to get some awareness on when and how we return a 403 in these circumstances. Might take some time so appreciate your patience.

In the mean time, can you describe how you are storing the token and how your container accesses it? Long shot but I do recall that in my own experience using different AWS services for storing secrets, it can be tricky.

**Comment by chris104957** [comment]
So everything is deployed via terraform - relevant part of the container definition looks like this:
![image](https://user-images.githubusercontent.com/24718987/167655677-6de36848-08b1-4f26-b2bc-d082494a93af.png)

As you can see, there's nothing particularly tricky in there. I will eventually move these to AWS secrets manager but for now I'm just trying to get it working

**Comment by filmaj** [comment]
Hey @chris104957, sorry for the lack of response here. Are you still experiencing this? If so, any chance you can log out the the contents of the HTTP 403 response? Judging by your logs you are getting about ~5kb worth of content in the HTTP 403 response. I wonder what's in there? Perhaps that could help us get to the bottom of it.
