### ISSUE TITLE
Deploy WebSocketMode App in Google Cloud Run

### ISSUE THREAD

**Issue by lautaropacellaDR** [slackapi/bolt-python#650]
Hello! I'm sorry to be asking this, I know there is a couple of examples about deploying in GCP but I cant seem to get it right. I'm pretty new to this.

First I tried copy pasting the exact code to make it work in FastAPI but I wasnt able.
I did a slack bot that I'm happy with using socketmode, but to deploy bots on as a Cloud Run service I only see an example using Flask. Is there a way to deploy it directly by keeping the SocketMode?

Thanks a lot!

**Comment by filmaj** [comment]
Hi @lautaropacellaDR,

What you want should be possible, but please note that we can't help you with the hosting side of things, especially on third party hosting services, as we don't have the expertise using platforms like GCP.

In theory, as long as you can properly containerize your application in e.g. docker, then deploying your app to GCR while the app is configured in socket mode should be possible. Again, I don't have GCR experience, so I don't know for sure, but it is worth noting that GCR will automatically shut down inactive containers after 15 mins. It is unclear to me whether a container with an open socket connection (like a Slack app using socket mode would have) would be considered inactive by GCR. If GCR does consider it inactive, it looks like they support ["always on" containers](https://cloud.google.com/blog/products/serverless/cloud-run-gets-always-on-cpu-allocation), which may help you in your endeavour, but I would think this would only be applicable if an open socket connection makes a container "active" on GCR.

**Comment by filmaj** [comment]
> From what I understand from docs, and previous questions made here, I should be able to run it via socketmode by starting the app using socket_app.start(), and instantiate an unrelated fastAPI webapp in the same google cloud run service to make it work? does this makes sense?

I apologize but I honestly am the wrong person to ask about hosting things on GCR - I've never done it. As for running your bolt app in socket mode, you need to create a `SocketModeHandler` and attach it to your bolt app before starting the app by calling the `handler.start()` method - that should be all that's required. Have a look at the [Socket Mode section of our Bolt for Python docs](https://slack.dev/bolt-python/concepts#socket-mode) for details.

**Comment by lautaropacellaDR** [comment]
I understand. Thanks for your help anyways, much appreciated!
