### ISSUE TITLE
app_home_opened event listener doesn't trigger the listener function

### ISSUE THREAD

**Issue by rodiali1** [slackapi/bolt-python#652]
### Description
The app_home_opened event listener doesn't trigger the listener function. I can see that I have received the payload in the logs and all other events are working just fine. I have all sorts of event listeners that are just working as expected, but not this one. I have tested to run this event listener as both a decorator or a method.

#### The `slack_bolt` version

slack-bolt==1.14.0
slack-sdk==3.16.2

#### Python runtime version

Python 3.7.4

#### OS info

ProductName:    macOS
ProductVersion: 12.3.1
BuildVersion:   21E258
Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

I followed the instructions [here](https://slack.dev/bolt-python/concepts#app-home) to add the functionality to my bot.

### Expected result:

I tested with both the instructions above, but even doing logger.info doesn't output anything

### Actual result:

The listener function doesn't execute, not sure if this will help but I get None if printing out the value of app.event("app_home_opened")

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by eddyg** [comment]
> I get None if printing out the value of `app.event("app_home_opeened")`

Is it possible the problem is as simple as the misspelling quoted here?

**Comment by rodiali1** [comment]
> > I get None if printing out the value of `app.event("app_home_opeened")`
> 
> Is it possible the problem is as simple as the misspelling quoted here?

Sorry, no it is not. It is just misspelled here.

**Comment by eddyg** [comment]
The only other thing I can think of is that your app isn't subscribed to the `app_home_opened` event under "Event Subscriptions".

<img width="548" alt="Screenshot 2022-05-20 09 19 31@2x" src="https://user-images.githubusercontent.com/3235109/169536499-08bf1394-61ea-4d62-9d38-75f172e39b12.png">

**Comment by rodiali1** [comment]
> 

Thx! I have that too actually since the beginning. I have even tried to remove it, re-install the app, re-add, and re-install again.

**Comment by eddyg** [comment]
Bummer. Was hoping that was it.

FWIW, listening for the `app_home_opened` event does work for me with Bolt, and since you say you have other events working, I'm not sure why this one would behave differently. 😐

**Comment by rodiali1** [comment]
> Bummer. Was hoping that was it.
> 
> FWIW, listening for the `app_home_opened` event does work for me with Bolt, and since you say you have other events working, I'm not sure why this one would behave differently. 😐

Do you mind sharing the snippet where you set the event listener and listener function? 

Here is mine..
`app.event("app_home_opened")(ack=respond_to_slack_within_3_seconds, lazy=[app_home_opened])
app.event("member_joined_channel")(ack=respond_to_slack_within_3_seconds, lazy=[handle_bot_join, handle_new_joiner])`

The member_joined_channel one is working as expected

**Comment by eddyg** [comment]
I don't use lazy listeners, so mine is simply `@app.event("app_home_opened")`.

Are you able to come up with some minimal code (by modifying [this](https://github.com/slackapi/bolt-python/blob/main/examples/aws_lambda/lazy_aws_lambda.py), for example, with an `app_home_opened` listener instead of a slash-command) that illustrates the behavior you're seeing?

**Comment by rodiali1** [comment]
Alright, I feel a bit embarrassed now :D 
After following your request to come up with a minimal code, I tried to follow my functions to have an identical scenario. 
And suddenly there I found that I was filtering anything not member_joined_channel out and hence the event listener function was not executing.
