### ISSUE TITLE
403 Forbidden with slack bolt Auth API

### ISSUE THREAD

**Issue by balma8f** [slackapi/bolt-python#653]
### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version
1.10.0

#### Python runtime version
3.6

#### OS info
linux VM

#### Steps to reproduce:
1. Start up Python server, python3 app.py
2. 'botToken' is stored in DB, where we are successfully getting a valid token
3. Runs code: "app = App(token=botToken)"
4. Returns back 403

### Expected result:
```
, {"ok":true,"url":"https://vz-gnt.slack.com/","team":"VZ-GNT","user":"atlasbot","team_id":"xxx","user_id":"xxx","bot_id":"xxx","enterprise_id":"xxx","is_enterprise_install":false}
```
We expect this response to be returned back after calling the above code snippet.

### Actual result:
```
ERROR:slack_bolt.App:Failed to send a request to Slack API server: <urlopen error Tunnel connection failed: 403 Forbidden>
INFO:slack_bolt.App:Going to retry the same request: POST https://www.slack.com/api/auth.test
ERROR:slack_bolt.App:Failed to send a request to Slack API server: <urlopen error Tunnel connection failed: 403 Forbidden>
When we manually test our Bot Token with this API, we get the valid response. Its only when we run this code in our Linux VM this error appears.
```

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @balma8f, thanks for asking the question.

> urlopen error Tunnel connection failed: 403 Forbidden

The Slack API server never returns 403 even if your request data is invalid. It can return 200 OK with error information in its response body data. In your Python app, you will see SlackApiError exception with the error information.

I am confident that your corporate / data center network does not allow this type of outgoing HTTP requests by their policies. Perhaps, you need to pass proxy settings to your bolt app. 

Please consult with your admins about the details of the proxy or outgoing request restrictions. If there is an HTTP proxy, you can pass the URL to your app this way: https://github.com/slackapi/bolt-python/blob/v1.14.0/examples/socket_mode_proxy.py#L16

I hope this was helpful and you will figure out what to do soon.

**Comment by balma8f** [comment]
so the example you gave, we gave it a try and for some reason it throws an error of us not providing the right "WebClient" even though we have it exactly as your code snippet has. Also for the proxy topic, in the VM if we manually test the auth test API, we get a valid response (either invalid auth or ok: true), could this issue be from anything else?

**Comment by seratch** [comment]
@balma8f With the given information, I don't have any other suggestions. 

> urlopen error Tunnel connection failed

Again, this error message indicates the error is not returned from the Slack server. By googling the error message, you can find a few resources as below:
* https://stackoverflow.com/questions/29744418/urllib2-urlerror-urlopen-error-tunnel-connection-failed-403-tunnel-or-ssl-for
* https://kktechinnovation.wordpress.com/2014/05/21/proxy-tunneling-failed-forbiddenunable-to-establish-ssl-connection/
* https://www.pythonanywhere.com/forums/topic/8902/

I hope that you will resolve the problem soon!
