### ISSUE TITLE
Issue with block kit multi static select input behavior

### ISSUE THREAD

**Issue by kamalesh1810** [slackapi/bolt-python#654]
I'd like to report an issue we are facing with the behavior of the [multi static input](https://api.slack.com/reference/block-kit/block-elements#multi_select) block element. I've observed that the dropdown with the options which shows up initially does not come back when the user removes a selected option by clicking on the X mark of the option. For the dropdown to show up again, you'll have to click out of the input bar and then click back in.
#### The `slack_bolt` version
slack-bolt==1.9.1 
slack-sdk== 3.11.1

#### Python runtime version
Python 3.7.2

#### OS info
Microsoft Windows [Version 10.0.19044.1706]

#### Steps to reproduce:

1. Initial view of multi static input
![image](https://user-images.githubusercontent.com/61874657/169652844-540f096f-0e7b-47ba-a4f5-a7bb2bcaa7bd.png)

2. User selects 3 options
![image](https://user-images.githubusercontent.com/61874657/169652894-3a768a5c-04ed-4cfc-bbaf-ff5085c96367.png)

3. User wants to remove option 3 and add option 4 instead (only way to do this is to click on the X mark on the input bar as you cannot de-select options from the dropdown)
![image](https://user-images.githubusercontent.com/61874657/169652935-0423df71-d58a-4c9e-90f0-d57b319ac634.png)

### Expected result:

Dropdown to be visible whenever the input bar is in focus, or an option to de-select options from the dropdown.

### Actual result:
As seen in step 3, the input bar is in focus, but the dropdown isn't visible making it look like a glitch. To add new options from this point on, the user has to focus out and into the input bar again for the options to be seen, or has to search for the option. (But both these options are inconvenient from the user experience point of view).

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @kamalesh1810, thank you very much for taking the time to report this issue 🙇 

This has been an intentional behavior of the multi-select menu, but we will share your feedback with the product/engineering teams. As a workaround, you can reopen the select menu dialog to see the rest of the options again.

Thanks again for your input here.
