### ISSUE TITLE
Loading SLACK_BOT_TOKEN and SLACK_APP_TOKEN from Key Vault 

### ISSUE THREAD

**Issue by sprider** [slackapi/bolt-python#655]
Hi Team,

We use an internal key vault to save SLACK_BOT_TOKEN and SLACK_APP_TOKEN values. We will load these values at run time which may take 2 to 3 seconds to retrieve. Is it possible to wait in line 7 until the token values are loaded? 

Thank you for reviewing this question! 

![Screen Shot 2022-05-23 at 9 10 50 AM](https://user-images.githubusercontent.com/21008316/169838753-478b23c7-b7e3-4b89-aa81-7d742e1056ce.png)

**Comment by misscoded** [comment]
Hi @sprider! Without knowing more details about the key vault being used, our general suggestion would be to load the variables as quickly as possible, then pass those values to the constructor. 

Something like the following, which separates the loading step from the instantiation:

```
# load credentials as fast as possible here
bot_token, app_token = load_credentials_from_vault()
app = App(token=bot_token)
```

Hope that helps. Let us know if that resolves the issue!

**Comment by sprider** [comment]
@misscoded, Thank you so much for your input. I am doing the same using a module. Looks good now. If I come across any issues, I will post a new query.
