### ISSUE TITLE
Issue: "Your URL didn't respond with the value of the challenge parameter."

### ISSUE THREAD

**Issue by dongwangdw** [slackapi/bolt-python#656]
when I followd doc of [http](https://github.com/slackapi/bolt-python/blob/main/docs/_tutorials/getting_started_http.md), I started
the app service from my VM and of cource it got a Public IP. I composed the url as http://my-ip/slack/events. But I got error then to verify the url for the event subscription. Is there anything I missed?

**Comment by seratch** [comment]
@dongwangdw Your URL must be an `https://` URL. Also, you need to have publicly accessible domain URL, not an IP address.

**Comment by dongwangdw** [comment]
@seratch Thanks for the info. I did not find these in the doc. I will try with these fixed.

**Comment by dongwangdw** [comment]
I did not get luck after I used a public domain and https. Are there any other tricks ?
I just followed the doc. Should I consider other things, like ssl certs etc?

**Comment by dongwangdw** [comment]
> @dongwangdw Your URL must be an `https://` URL. Also, you need to have publicly accessible domain URL, not an IP address.

This is definitely wrong from my side. I did not use ngrok. I have to use http and port. 
If I use https, then  I got some error from backend
```
code 400, message Bad request syntax

```

At last, I fix this with http://my-domain:3000/slack/events.

@seratch Did I miss any config here? Please help verify. Or it is may be a bug. 
It is of course an issue for doc side right now.

**Comment by seratch** [comment]
@dongwangdw 
>If I use https, then I got some error from backend

As mentioned [in this page](https://stackoverflow.com/questions/49389535/problems-with-flask-and-bad-request) and many others, the reason why you saw the error is that your Flask app is unable to directly handle SSL requests.

I have two suggestions for you:

1. Use [Socket Mode](https://slack.dev/bolt-python/tutorial/getting-started) instead
2. Have a front-end load balancer (e.g., AWS ELB) / HTTP server (e.g., nginx, Apache) in front of your Flask app

If you go with 1. Socket Mode, your app does not need to have a public endpoint. You can remove Flask from your app and you won't be bothered by the error.

As for 2. approach, this is the right way to achieve your goal if you would like to run your app on an HTTP endpoint. This is common design for running a web service:
```
Slack <--- HTTPS (port 443) ---> LB/nginx <--- HTTP (port 3000) ---> Flask App
```

I am unable to help you out for the details. If you have infra admins, you can talk to them for the proper ways to manage the public HTTPS endpoint and forward requests to the backend Flask app.

I hope this helps.

**Comment by dongwangdw** [comment]
@seratch No problem. I can manage this.  But the doc here is a little confusing, which should contain all the stuff you mentioned above.

So I need a LB in front of my service.

Thanks.

**Comment by dongwangdw** [comment]
Followup: And the ip works fine here if I did not have a https enabled.
