### ISSUE TITLE
How to identify listener inside middleware?

### ISSUE THREAD

**Issue by jessejoe** [slackapi/bolt-python#657]
I'm trying to keep track of what listener has replied to what message/thread so I can only respond once per listener. Is there a way to figure out which listener is calling the middleware? Example below:

```python
already_replied = []

def only_reply_once(message, logger, next):
    ts = message.get('thread_ts') or message['ts']
    listener = # How?
    if (ts, listener) not in already_replied:
        already_replied.append((ts, listener))
        next()

@app.message("test1", middleware=[only_reply_once])
def reply_test1(message, say, logger):
    say(text='something1', thread_ts=message.get('thread_ts') or message['ts'])

@app.message("test2", middleware=[only_reply_once])
def reply_test2(message, say, logger):
    say(text='something2', thread_ts=message.get('thread_ts') or message['ts'])
```

I can't find anyway inside the `only_reply_once()` middleware to figure out which listener is calling it. Am I missing this, or is there another way to avoid sending more than 1 reply from a listener to a message/thread? I figured middleware was a good way to do this to avoid duplicate code in each listener, and using another decorator seems to break the existing `@app.message` decorator.

Thanks for the help!

**Comment by seratch** [comment]
Hi @jessejoe, thanks for writing in!

If your goal is to ensure if only one listener is invoked for a message event, you don't need to have the only_reply_once middleware. bolt-python executes only the first listener that matches the payload pattern. In your example, if `reply_test1` matches, `reply_test2` won't be executed. If you would like to run both, a suggested way is to have a unified listener that matches both patterns.

Is everything clear now?

**Comment by jessejoe** [comment]
Hi @seratch, thanks for the quick reply! That's not actually what I'm looking for. I'm looking to ensure that each listener (`reply_test1` and `reply_test2`) only reply once to a specific message/thread. For example: someone posts "test1" and `reply_test1` replies in thread. Then someone in the same thread posts `test1`, I **don't** want `reply_test1` to reply again because it already replied once. Does that make sense?

**Comment by seratch** [comment]
@jessejoe Thanks for the reply! Now I think I understand what you would like to here.

In this case, you can use [`conversations.replies` API method](https://api.slack.com/methods/conversations.replies) for checking if there is already a reply posted by your app.

Here is a similar app that I created in the past. The app is written in TypeScript but you can easily implement something similar in Python:
* https://github.com/seratch/deepl-for-slack/blob/f866d56a6bca4495a36711804eb4312a98bf41ae/src/index.ts#L84-L96
* https://github.com/seratch/deepl-for-slack/blob/f866d56a6bca4495a36711804eb4312a98bf41ae/src/reacjilator.ts#L20-L38

I hope this helps.

**Comment by jessejoe** [comment]
Thanks @seratch, but I think that would be overly complex. I don't want to just check if the app replied to the thread, but also if it posted a specific reply (so it can reply with more than 1 listener, but only once for each). So I would have to add another API library outside of `bolt`, query all the messages in a thread (which could be hundreds), and check and see if any of them are a specific message from my app. I think I'd rather just call a function in each listener to store the thread ID and listener name, I was just trying to do it inside the decorator so it was easier to see.

**Comment by seratch** [comment]
Before talking about the main point, let me clarify one thing first:

>I would have to add another API library outside of bolt

No need to add an additional library. You can use [slack-sdk](https://pypi.org/project/slack-sdk), which is an underlying low-level SDK in bolt-python.

If you prefer a more light-weight approach that does not require any API calls, the only approach I can suggest is to have a common utility function and call it inside your listeners. bolt-python does not provide any ways to know the listener function name in its listener middleware, Also, we are not planning to add the feature at least in the short term.

I'm sorry that I was not able to provide useful information here but I hope you will find a reasonable solution for your use case.
