### ISSUE TITLE
Getting multiple request when Cloud Run is on Cold-Start

### ISSUE THREAD

**Issue by lautaropacellaDR** [slackapi/bolt-python#658]
Hello! I managed to deploy a Slack Bot via Fasti API as a google cloud run service, it works well but everytime the container is not active, and the app gets called by a @mention, it receives the same POST 3 times, so it answers 3 times. If its called when its active, it only answers one time.
This is the code I'm using:

```python
from slack_bolt import App as SlackApp
from slack_bolt.adapter.fastapi import SlackRequestHandler
from slack_bolt.adapter.socket_mode import SocketModeHandler

slack_app = SlackApp(
    token=SLACK_BOT_TOKEN,
    signing_secret=SLACK_SIGNING_SECRET,
)

app_handler = SlackRequestHandler(slack_app)
socket_handler = SocketModeHandler(slack_app, app_token=SLACK_APP_TOKEN)

socket_handler.connect()

@slack_app.event("app_mention")
def do_something(say):
    say(text="Hello there")

from fastapi import FastAPI, Request

app = FastAPI()

@app.post("/slack/events")
async def endpoint(req: Request):
    return await app_handler.handle(req)

@app.get("/slack/install")
async def install(req: Request):
    return await app_handler.handle(req)

@app.get("/slack/oauth_redirect")
async def oauth_redirect(req: Request):
    return await app_handler.handle(req)

@app.post("/")
async def oauth_redirect(req: Request):
    return await SocketModeHandler.handle(req)
````

**Comment by seratch** [comment]
Hi @lautaropacellaDR, thanks for asking the question!

This is a classic question for the on-demand cloud service use cases. The Slack API server expects your endpoint to respond within less than 3 seconds, so slow bootstrap of your on-demand runtime can be a blocker for Slack apps.


If the cold-start overhead is problematic for your app, the only option to consider is always running at least one instance for stable response time. Google Cloud Run service offers [the "always-on CPU" option](https://cloud.google.com/blog/products/serverless/cloud-run-gets-always-on-cpu-allocation) for your use case. Enabling this option can eliminate the issue.

Is everything clear now?

**Comment by lautaropacellaDR** [comment]
I see, thanks for such quick answer Seratch!

I found [this resource](https://slack.dev/bolt-python/concepts#lazy-listeners) and was wondering if this could also help? but I'm not completely sure this is helpful for the coldstart, sorry I'm still learning a lot about this app and how they combine with others.

Thanks in advance!

**Comment by seratch** [comment]
@lautaropacellaDR Lazy listeners can be a solution for your issue! but unfortunately, the feature is only available for AWS Lambda (and non-FaaS runtimes). We don't have any short-term plans to add Google Cloud service supports to the feature (due to the lack of equivalent features in Google Cloud).
