### ISSUE TITLE
Update "AWS Lambda Bolt Python Examples" page to include Lambda URL

### ISSUE THREAD

**Issue by Globart1337** [slackapi/bolt-python#659]
On 6th of April AWS added new feature - Lambda Function URLs: Built-in HTTPS Endpoints for Single-Function Microservices
It's cheaper, simpler and faster to setup, than API Gateway. If you don`t require the advanced functionality, such as request validation, throttling, custom authorizers, custom domain names, usage plans, or caching. So, my suggestion is to replace "Set up AWS API Gateway" part with steps to set up Lambda URL, or atleast mention it as an alternative.

### Category (place an `x` in each of the `[ ]`)

* [ ] **slack_bolt.App** and/or its core components
* [ ] **slack_bolt.async_app.AsyncApp** and/or its core components
* [ ] Adapters in **slack_bolt.adapter**
* [x] Others

**Comment by seratch** [comment]
Hi @Globart1337, thanks for the suggestion! I agree with you that the [Lambda Function URLs](https://docs.aws.amazon.com/lambda/latest/dg/lambda-urls.html) would be a much easier way for developers.

Although we don't have the bandwidth to work on the content updates right now, we may revise the content in the near future. If someone is interested in working on it, any contributions for it would be greatly appreciated 🙇

**Comment by Globart1337** [comment]
@seratch Can I fork the repo, make the changes and create a PR for this?

**Comment by Globart1337** [comment]
@seratch Okay than, so I should completely remove Set up AWS API Gateway section and replace it with Set up AWS Lambda Function URL?

**Comment by seratch** [comment]
Yes, we can simplify [the part](https://github.com/slackapi/bolt-python/tree/main/examples/aws_lambda#set-up-aws-api-gateway) as long as the updated one works for everyone.

**Comment by Globart1337** [comment]
@seratch I`ve created PR for this issue, please check

**Comment by seratch** [comment]
Fixed by #661
