### ISSUE TITLE
Fix "&gt;" instead of ">" on "concepts" documentation page

### ISSUE THREAD

**Issue by Globart1337** [slackapi/bolt-python#660]
On https://slack.dev/bolt-python/concepts at line 12 of "Example with AWS Lambda" there is "\&gt;" displayed, instead of ">" symbol. To fix this you have to remove "\<span class="p">;\</span>" after it

### Category (place an `x` in each of the `[ ]`)

* [ ] **slack_bolt.App** and/or its core components
* [ ] **slack_bolt.async_app.AsyncApp** and/or its core components
* [ ] Adapters in **slack_bolt.adapter**
* [x] Others

**Comment by seratch** [comment]
Hi @Globart1337, thanks for taking the time to report this issue. This may be due to the Jekyll rendering system. If anyone knows the way to properly resolve it, sharing the knowledge and/or sending a pull request fixing it would be appreciated.

**Comment by Globart1337** [comment]
@seratch what file is used to generate the page? I can try to fix it, if I know where it`s located

**Comment by seratch** [comment]
@Globart1337 The markdown files under docs directory are used for generating the website contents. If you are not familiar with GitHub Pages, please refer to their documents first.

**Comment by seratch** [comment]
Resolved by  #690
