### ISSUE TITLE
One user gets "Although the app should be installed into this workspace", while other does not.

### ISSUE THREAD

**Issue by DataGreed** [slackapi/bolt-python#664]
#### The `slack_bolt` version

```
slack-bolt==1.11.1
slack-sdk==3.17.0
```
_(same bug with slack-bolt=1.6.0, I've updated hoping it was resolved)_

#### Python runtime version

```Python 3.8.9```
#### OS info

```
ProductName:	macOS
ProductVersion:	12.3.1
BuildVersion:	21E258
Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64
```

#### Steps to reproduce:

1. Create Django App that uses OAuth based on a template in this repo
2. Register `app.event("message")` listener
3. Install the app with two users using `/slack/install` view – by a _regular user_ and a _workspace owner_
4. Add a bot to `#some-channel`. 
5. Post some messages in channel by _both users_, see `app.event("message")` listener being triggered properly. 
6. Remove the app by _workspace owner_ through a config page. 
7. Reinstall the app by _regular user_ (not a workspace owner). 
8. Add a bot to `#some-channel` by _regular user_. 
9. Post a message by _regular user_, see `app.event("message")` listener being triggered properly. 
10. Post a message by _workspace owner_ — get a slack middleware error. 

### Expected result:
`app.event("message")` listener being triggered properly for all users when message is posted, not just the one who installed the app again

### Actual result:

Workspace owner gets slack midleware error:

```
Applying slack_bolt.middleware.ssl_check.ssl_check.SslCheck
Applying slack_bolt.middleware.request_verification.request_verification.RequestVerification
Applying slack_bolt.middleware.authorization.multi_teams_authorization.MultiTeamsAuthorization
Sending a request - url: https://www.slack.com/api/auth.test, query_params: {}, body_params: {'team_id': 'REDACTED'}, files: {}, json_body: None, headers: {'Content-Type': 'application/x-www-form-urlencoded', 'Authorization': '(redacted)', 'User-Agent': 'Python/3.8.9 slackclient/3.17.0 Darwin/21.4.0'}
Received the following response - status: 200, headers: {'date': 'Wed, 01 Jun 2022 20:17:16 GMT', 'server': 'Apache', 'x-powered-by': 'HHVM/4.153.1', 'access-control-allow-origin': '*', 'referrer-policy': 'no-referrer', 'x-slack-backend': 'r', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'access-control-allow-headers': 'slack-route, x-slack-version-ts, x-b3-traceid, x-b3-spanid, x-b3-parentspanid, x-b3-sampled, x-b3-flags', 'access-control-expose-headers': 'x-slack-req-id, retry-after', 'expires': 'Mon, 26 Jul 1997 05:00:00 GMT', 'cache-control': 'private, no-cache, no-store, must-revalidate', 'pragma': 'no-cache', 'x-robots-tag': 'noindex,nofollow', 'x-xss-protection': '0', 'x-content-type-options': 'nosniff', 'x-slack-req-id': '3097ad69461e3cbeb1e9ddb962672219', 'vary': 'Accept-Encoding', 'content-type': 'application/json; charset=utf-8', 'x-envoy-upstream-service-time': '90', 'x-backend': 'main_normal main_bedrock_normal_with_overflow main_canary_with_overflow main_bedrock_canary_with_overflow main_control_with_overflow main_bedrock_control_with_overflow', 'x-server': 'slack-www-hhvm-main-iad-592u', 'x-slack-shared-secret-outcome': 'no-match', 'via': 'envoy-www-iad-g14r, envoy-edge-lhr-aqga', 'x-edge-backend': 'envoy-www', 'x-slack-edge-shared-secret-outcome': 'no-match', 'connection': 'close', 'transfer-encoding': 'chunked'}, body: {"ok":false,"error":"invalid_auth"}
The stored bot token for enterprise_id: None team_id: REDACTED is no longer valid. (response: {'ok': False, 'error': 'invalid_auth'})
Although the app should be installed into this workspace, the AuthorizeResult (returned value from authorize) for it was not found.
"POST /slack/events HTTP/1.1" 200 52
```

**Comment by DataGreed** [comment]
Also tried inviting a completely new user who didn’t interact with the app in this scenario in slack and adding her in the same channel - event listener gets called without any problems (and she clearly does not have any associated slack installation objected in the database)

**Comment by DataGreed** [comment]
@srajiang could you please specify what kind of info do you need?

**Comment by DataGreed** [comment]
BTW, I am not sure why is this marked as question and not a bug, since this is clearly a problem on the library side since it does not give any option to the developer, it basically crashes in the `MultiTeamsAuthorization` middleware using wrong credentials. 

BTW, if remove the old not-working SlackInstallations it will work properly (obviously, since it will then probably use the proper bot_token from the recent installation) - the problem is I cannot do it programmatically, because middleware does not give me any control over it and, frankly, I think Bolt should handle it automatically.

**Comment by DataGreed** [comment]
I've come up with a temporary fix.
I've modified `DjangoInstallationStore.find_installation` and made it user_id-agnostic.
Basically I've reduced [this part](https://github.com/slackapi/bolt-python/blob/3457fb143310afa9acaf6c1bc5d2893c39267a8c/examples/django/oauth_app/slack_datastores.py#L130):

```python
    if user_id is None:
          rows = (
              SlackInstallation.objects.filter(client_id=self.client_id)
              .filter(enterprise_id=e_id)
              .filter(team_id=t_id)
              .order_by(F("installed_at").desc())[:1]
          )
      else:
          rows = (
              SlackInstallation.objects.filter(client_id=self.client_id)
              .filter(enterprise_id=e_id)
              .filter(team_id=t_id)
              .filter(user_id=user_id)
              .order_by(F("installed_at").desc())[:1]
          )
```

to this:

```python
            rows = (
                SlackInstallation.objects.filter(client_id=self.client_id)
                .filter(enterprise_id=e_id)
                .filter(team_id=t_id)
                .filter(user_id=user_id)
                .order_by(F("installed_at").desc())[:1]
            )
```

I am not sure if it will cause any problems, though – it seems like it could if the token won't have the same permission scope as expected.

Is there any way to fix this properly?

**Comment by seratch** [comment]
@DataGreed Thanks for letting us know the details of the issue that you encountered. And I agree that this is a bug on the installation store implementation in the Django example app. Also, the same potential issue can arise even with all the built-in installation store [available here](https://github.com/slackapi/python-slack-sdk/tree/main/slack_sdk/oauth/installation_store).

Changing the query to be user_id agnostic does not work for the use cases where the OAuth flow has both bot scopes and user scopes. Thus, I am thinking of the following changes:
* Run two queries with the installation database table
  * 1 - run a query without user_id to fetch the latest bot token data
  * 2 - run a query with user_id to fetch the latest user token for the user (if exists)
Merging these query results into one unified Installation data should resolve the issue described here.

Also, as an improvement that you can immediately do, I would suggest subscribing token revocation / uninstallation events and enabling built-in event listeners to properly maintain installation data. Please refer to my comment at https://github.com/slackapi/bolt-python/issues/663#issuecomment-1143386352 for more details.

Thanks again for sharing this. I will work on the fix later today (in my local time Japan Standard Time +09:00)

**Comment by DataGreed** [comment]
@seratch first of all, thank you so much for a quick response and proposed fix, I really appreciate this.

> Changing the query to be user_id agnostic does not work for the use cases where the OAuth flow has both bot scopes and user scopes. Thus, I am thinking of the following changes:
> 
> * Run two queries with the installation database table
>   
>   * 1 - run a query without user_id to fetch the latest bot token data
>   * 2 - run a query with user_id to fetch the latest user token for the user (if exists)
>     Merging these query results into one unified Installation data should resolve the issue described here.

@seratch could you please suggest the best way to merge them to avoid any potential problems? Should I get `user_id`, `user_token` and `user_scopes` from the `Installation` found by `user_id` and get all other fields from the most recent `Installation`?

Something like this:

```python
return Installation(
              app_id=recent_installation.app_id,
              enterprise_id=recent_installation.enterprise_id,
              team_id=recent_installation.team_id,
              bot_token=recent_installation.bot_token,
              bot_id=recent_installation.bot_id,
              bot_user_id=recent_installation.bot_user_id,
              bot_scopes=recent_installation.bot_scopes,

              # user-specific fields
              user_id=user_installation.user_id if user_installation else recent_installation.user_id,
              user_token=user_installation.user_id.user_token  if user_installation else recent_installation.user_token,
              user_scopes=user_installation.user_scopes if user_installation else recent_installation.user_scopes,

              incoming_webhook_url=recent_installation.incoming_webhook_url,
              incoming_webhook_channel_id=recent_installation.incoming_webhook_channel_id,
              incoming_webhook_configuration_url=recent_installation.incoming_webhook_configuration_url,
              installed_at=recent_installation.installed_at.timestamp(),
          )
```

> Also, as an improvement that you can immediately do, I would suggest subscribing token revocation / uninstallation events and enabling built-in event listeners to properly maintain installation data. Please refer to my comment at [#663 (comment)](https://github.com/slackapi/bolt-python/issues/663#issuecomment-1143386352) for more details.
> 
> Thanks again for sharing this. I will work on the fix later today (in my local time Japan Standard Time +09:00)

Thanks! I somehow overlooked this, I will definitely subscribe to these events.

**Comment by seratch** [comment]
Hi @DataGreed, here is a fix for this issue: https://github.com/slackapi/bolt-python/pull/665 Could you verify if it works for your use case?

**Comment by DataGreed** [comment]
@seratch sorry for the late answer, I am in UTC+1 and had a sleepless night 😅 Yes, it does fix the problem, thank you!
