### ISSUE TITLE
How do I share remote files in threads?

### ISSUE THREAD

**Issue by DataGreed** [slackapi/bolt-python#666]
Hi, three questins about remote files:

1. I found a method `files_remote_share` (https://api.slack.com/methods/files.remote.share), but it seems to only post in the root of the channel, how do I post a remote file as a reply to a thread?

2. How do I add text to a message with remote files, the same way users do it when uploading files in slack?

3. I am trying to reshare a file that user shared in chat. I receive a message event with `file_share` subtype, get `files` dictionary from it and try to share it in a channel like this:

```
for file in event['files']:
    print(f"Trying file {file}...")
    client.files_remote_share(channels=[event['channel']], external_id=file['id'])
    print("...succeed (?)")
```

but I always get an error:

```
Traceback (most recent call last):
  File "/Users/REDACTED/.venv/lib/python3.8/site-packages/slack_bolt/listener/thread_runner.py", line 124, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/REDACTED/.venv/lib/python3.8/site-packages/slack_bolt/listener/custom_listener.py", line 49, in run_ack_function
    return self.ack_function(
  File "/Users/REDACTED/threads/slack_listeners.py", line 984, in message_posted
    raise exc
  File "/Users/REDACTED/threads/slack_listeners.py", line 974, in message_posted
    client.files_remote_share(channels=[event['channel']], external_id=file['id'])
  File "/Users/REDACTED/.venv/lib/python3.8/site-packages/slack_sdk/web/client.py", line 2960, in files_remote_share
    return self.api_call("files.remote.share", http_verb="GET", params=kwargs)
  File "/Users/REDACTED/.venv/lib/python3.8/site-packages/slack_sdk/web/base_client.py", line 160, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
  File "/Users/REDACTED/.venv/lib/python3.8/site-packages/slack_sdk/web/base_client.py", line 197, in _sync_send
    return self._urllib_api_call(
  File "/Users/REDACTED/.venv/lib/python3.8/site-packages/slack_sdk/web/base_client.py", line 331, in _urllib_api_call
    return SlackResponse(
  File "/Users/REDACTEDo/.venv/lib/python3.8/site-packages/slack_sdk/web/slack_response.py", line 205, in validate
    raise e.SlackApiError(message=msg, response=self)
slack_sdk.errors.SlackApiError: The request to the Slack API failed. (url: https://www.slack.com/api/files.remote.share)
The server responded with: {'ok': False, 'error': 'file_not_found'}
```

I've also tried using `file` kwarg instead, but I also receive the same error:
```
client.files_remote_share(channels=[[event['channel']], file=file['id'])
```

am I doing something wrong? The permalinks to the files are working and I can see user's message with this files posted in a public channel where bot is also added, I am confused. Should I use something else for id?

**Comment by seratch** [comment]
@DataGreed 

>I found a method files_remote_share (https://api.slack.com/methods/files.remote.share), but it seems to only post in the root of the channel, how do I post a remote file as a reply to a thread?
>How do I add text to a message with remote files, the same way users do it when uploading files in slack?
>I am trying to reshare a file that user shared in chat. I receive a message event with file_share subtype, get files dictionary from it and try to share it in a channel like this:

If I understand your questions, I think that the following reply should answer all the three:

Once you perform a files.remote.add API call, you can share the remote file as part of blocks in your channel message. So, you can post chat.postMessage with thread_ts for your use case. To have a remote file in blocks, you can use a file typed block. Refer to https://github.com/slackapi/python-slack-sdk/blob/v3.17.0/integration_tests/web/test_remote_file_replacement.py#L48-L52 to learn how to use it in Python.

I hope this helps.

**Comment by DataGreed** [comment]
> Once you perform a files.remote.add API call, you can share the remote file as part of blocks in your channel message

@seratch can I do it without calling `files.remote.add`? I don't need to upload any file, **_I just want to reshare a file already uploaded by a user in another thread_**, without having to download and upload it again by my bot. And I want _**a preview of the file to be displayed**_.

I also tried just posting a permalink, but slack won't show a preview for it. 

Here's a screenshot of bot sharing the same link as a user as a simple message, the problem is that in case of user there's a preview for it and in case of bot there is no preview.

![screenshot slack](https://user-images.githubusercontent.com/2033163/172068984-c25ed5cb-5683-4bf3-8069-151dbc6d28aa.jpg)

I tried using `unfurl_links` and `unfurl_media` for `client.chat_postMessage`, but it does not make any difference.

> To have a remote file in blocks, you can use a file typed block. Refer to https://github.com/slackapi/python-slack-sdk/blob/v3.17.0/integration_tests/web/test_remote_file_replacement.py#L48-L52

According to the documentation, `file` block is _read-only_ – https://api.slack.com/reference/block-kit/blocks#file
I actually tried to send a message with it just in case the docs are wrong about it and received an "invalid block" response from API. Are you saying that this type of block can actyally be added to a message, but only using an ID of the file uploaded by bot? Can I use an id of a file uploaded by user?

**Comment by seratch** [comment]
@DataGreed 
>can I do it without calling files.remote.add? I don't need to upload any file, I just want to reshare a file already uploaded by a user in another thread, without having to download and upload it again by my bot. And I want a preview of the file to be displayed.

OK, in this case, you don't need to use files.remote.* APIs at all. Since your original question is about remote files, I've mentioned the proper way to use it. However, in your use case, the files are not "remote" files. Examples of "remote" files are Google Drive URLs, Box URLs, and whatever stored outside Slack.

Instead, you can use chat.postMessage withe the file URL. I know that you are already doing this.

>I also tried just posting a permalink, but slack won't show a preview for it.

If you are trying to display the preview of a URL in the same thread / channel right after the same URL is posted, unfortunately, 3rd party apps are unable to take control of the behavior. Slack UI automatically skips repeating the exactly same preview in a short period of time. 

>According to the documentation, file block is read-only – https://api.slack.com/reference/block-kit/blocks#file
I actually tried to send a message with it just in case the docs are wrong about it and received an "invalid block" response from API. Are you saying that this type of block can actyally be added to a message, but only using an ID of the file uploaded by bot? Can I use an id of a file uploaded by user?

As I mentioned above, you don't use "remote" files in this case and the file blocks are available only for "remote" files. So, you cannot use the block in this use case and you won't be bothered by this anymore. Instead, you can share an uploaded file's URL in your Slack message.

As you may already notice, the way to handle remote files is quite different from the way to handle uploaded files. If you have questions for both remote and uploaded files, perhaps having conversations for each separately would be easier.

**Comment by DataGreed** [comment]
> However, in your use case, the files are not "remote" files. Examples of "remote" files are Google Drive URLs, Box URLs, and whatever stored outside Slack.

@seratch  Oh, my bad. Thank you for clarification, I guess I was confused by the documentation. For some reason I thought that any uploaded file is called remote.

My use case ideals only with files  directly uploaded to Slack.

> If you are trying to display the preview of a URL in the same thread / channel right after the same URL is posted, unfortunately, 3rd party apps are unable to take control of the behavior. Slack UI automatically skips repeating the exactly same preview in a short period of time.

Interestingly enough, this is not the case.

Here's the screenshot of the thread. As you can see, bot posts links to files and there is no preview at all:

![screenshot_bot_only](https://user-images.githubusercontent.com/2033163/172239801-c6cc60d1-c27a-4a26-a85e-cea4451c29ed.png)

_(the bot is the same one, nevermind different avatars)_


---
But once a user posts the same link, the preview appears:

![screenshot_bot_and_user](https://user-images.githubusercontent.com/2033163/172239986-ab3b5eae-fa8d-4f56-9a58-f1f27625d36b.png)


---
How do I fix that? I want the previews be shown as sooner in the thread as possible (in this case, when the bot posts them). Right now it seems that any of the links posted by bot don't trigger Slack client to display previews at all.

**Comment by seratch** [comment]
@DataGreed 

>I tried using unfurl_links and unfurl_media for client.chat_postMessage, but it does not make any difference.

Settings these flags to True is the only approach that we can suggest. I am not sure why it didn't work for you.

**Comment by DataGreed** [comment]
@seratch 
> Settings these flags to True is the only approach that we can suggest. I am not sure why it didn't work for you.

They are set to `True`, I send send the following request:

```
client.chat_postMessage(channel=original_message_channel_id,
                                        text=f"<{file['permalink']}|{file['name']}>",
                                        thread_ts=[response['ts']],  # ts of original top-level message
                                        unfurl_links=True,
                                        unfurl_media=True
                                        )
```

Please advise, what should I do? I there anyone I we redirect the issue to if it's an API problem and not an SDK one?

**Comment by seratch** [comment]
@DataGreed I've checked the issue now and found that the Slack API server prevents repeated requests to unfurl the same URL in a short period of time **even when a request set the unfurl_links flag to true**. This behavior is not customizable on the 3rd party app side. This should be mentioned somewhere in the document. We will work on it in the future. 

Thanks again for asking this question. I think that everything is clear here (I know the answer is not ideal for you, though), so let us close this issue now. If you have other questions, please feel free to open a new issue for it.
