### ISSUE TITLE
Unable to set true in a modal

### ISSUE THREAD

**Issue by BMonsalvatge** [slackapi/bolt-python#667]
I am having issues using `true` anywhere in the view payload.   Instead I am getting the following error in the console when trying to open the view: `NameError: name 'true' is not defined`

### Reproducible in:

```python
@app.shortcut("request")
def open_modal(ack, shortcut, client):
    ack()
    client.views_open(
        trigger_id=shortcut["trigger_id"],
        # A simple view payload for a modal
        view={
            "type": "modal",
            "callback_id": "request_view",
            "title": {"type": "plain_text", "text": "Submit Request"},
            "close": {"type": "plain_text", "text": "Close"},
            "submit": {"type": "plain_text", "text": "Submit"},
            "blocks": [
                {
                    "type": "input",
                    "element": {
                        "type": "plain_text_input",
                        "action_id": "subject"
                    },
                    "label": {
                        "type": "plain_text",
                        "text": "Subject",
                        "emoji": true
                    }
                },
            ]
        }
    )
```

#### The `slack_bolt` version

(Paste the output of `pip freeze | grep slack`)
1.14.0

#### Python runtime version

(Paste the output of `python --version`)
Python 3.9.10

#### OS info

ProductName:    macOS
ProductVersion: 11.5.2
BuildVersion:   20G95
Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021

#### Steps to reproduce:

1. Run example and try to open the shortcut.

### Expected result:

The input should have the ability to add emojis in text input.

### Actual result:
```
Error in console:
2022-06-05 20:20:12,499 Failed to run listener function (error: name 'true' is not defined)
Traceback (most recent call last):
  File "/Users/user/Dev/myslackapp/.venv/lib/python3.9/site-packages/slack_bolt/listener/thread_runner.py", line 65, in run
    returned_value = listener.run_ack_function(
  File "/Users/user/Dev/myslackapp/.venv/lib/python3.9/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/user/Dev/myslackapp/./handler.py", line 45, in open_modal
    "emoji": true
NameError: name 'true' is not defined
```
## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @BMonsalvatge, thanks for asking the question!

>NameError: name 'true' is not defined

This error message means that you cannot use `true` for boolean values in Python. You can use `True` instead.

**Comment by BMonsalvatge** [comment]
Thanks, my mistake.
