### ISSUE TITLE
invalid additional property: response_url_enabled

### ISSUE THREAD

**Issue by triggspy** [slackapi/bolt-python#670]
Hello,

I am new to the Slack API & Slack Bolt. I am trying to use `respond` and when I set `response_url_enabled` to `true` I get a Slack API error. 

```
The request to the Slack API failed. (url: https://www.slack.com/api/views.open)
The server responded with: {'ok': False, 'error': 'invalid_arguments', 'response_metadata': {'messages': ['[ERROR] failed to match all allowed schemas [json-pointer:/view]', '[ERROR] invalid additional property: response_url_enabled [json-pointer:/view/blocks/1/element]']}})
```

#### The `slack_bolt` version

slack-bolt==1.11.4

#### Python runtime version

3.9

#### OS info

AWS Lambda

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1. My modal is:
```json
{
  "type": "modal",
  "callback_id": "click-button-yes-view",
  "submit": {
    "type": "plain_text",
    "text": "Submit"
  },
  "close": {
    "type": "plain_text",
    "text": "Cancel"
  },
  "title": {
    "type": "plain_text",
    "text": "Tell us a little more..."
  },
  "blocks": [
    {
      "type": "divider"
    },
    {
      "block_id": "block_id",
      "type": "input",
      "dispatch_action": true,
      "label": {
        "type": "plain_text",
        "text": ":wave:"
      },
      "element": {
        "response_url_enabled": true,
        "type": "plain_text_input",
        "action_id": "yes-submission-input",
        "placeholder": {
          "type": "plain_text",
          "text": "Please enter your text here"
        }
      }
    }
  ]
}
```

3. This leads to the error. According to your documentation I believe it is in the correct place in my input block. https://api.slack.com/reference/interaction-payloads/views#view_submission
### Expected result:

I'd expect to get a response url in my submission event and be able to reply back.

### Actual result:

SlackAPI Error. 

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @triggspy, thanks for asking the question!

This is not an issue with bolt-python but an error about the way to use the option. response_url_enabled can be set only in either `conversations_select` or `channels_select` block elements. You are trying to set the flag to `plain_text_input` block element but it is not available for the block type. This is what the error message returned from the Slack server-side. Refer to https://api.slack.com/reference/block-kit/block-elements#conversation_select for more details.

If everything is clear now, would you mind closing this issue?

**Comment by triggspy** [comment]
Awesome thanks for the quick reply. What would you recommend as a best practice to respond after a view submission event?

**Comment by seratch** [comment]
Do you mean the best practice to send a message after modal data submission? If so, there are two approaches.

`response_url_enabled` is a recommended way but the downside of this approach is that you have to have a conversations/channels_select block element. 

If your app opens this modal only from a channel (=meaning via button in a message, message shortcut, or slash command; in other words, you don't use global shortcut, buttons in Home tab), you can pass the channel ID as the modal's private_metadata. With this way, your app can memorize where to post a message afterwards without exposing the data to the end-user.

I hope this was helpful to you! Let me close this issue now but please feel free to write in or create a new issue whenever you have a different question!
