### ISSUE TITLE
Possbile to authenticate with OAuth for an app installed via console?

### ISSUE THREAD

**Issue by gfang-work** [slackapi/bolt-python#671]
Hi there, I wonder if there is a way to install an org-wide app via console (api.slack.com/apps) and still authenticate with OAuth (using OAuthSettings) with Bolt framework?

My main objective is to enable built-in token rotation without the hustle of going through OAuth programmatically because my app is org-wide and will only be installed once by an org owner in an enterprise grid.

THANK YOU!

[I deleted all prompts about sys setup because this is a question and none of them is relevant.]

**Comment by seratch** [comment]
Hi @gfang-work, thanks for writing in. When you use token rotation, the installation from the app configuration page does not work for you. Your app needs to serve the OAuth flow endpoints and app installing users have to go through the OAuth flow.
