### ISSUE TITLE
Work in progress view in App home page

### ISSUE THREAD

**Issue by juliocanares** [slackapi/bolt-python#674]
Hey guys 👋, I am experiencing an issue with the app home page, even if I handle the app_home_opened event by just acknowledging the request slack will show a work in progress view sometimes, why does this happen?
here is an screenshot:
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/5007653/175396412-0cb8f507-e5d1-49e1-9732-539177993368.png">

**Comment by neptunel** [comment]
Hey @juliocanares,
Thanks for your question!
Is your app hosted or running on socket mode? If it's using the socket mode you need to enable the socket mode on your app's config website. 
<img width="1468" alt="image" src="https://user-images.githubusercontent.com/63646687/175430947-09912bcd-8e16-4214-8b20-bd1115ea06c1.png">

**Comment by juliocanares** [comment]
Hi @neptunel, my app is not running in socket mode, it's actually showing the app home page to some users but couple of them see this work in progress view.
If my backend only acks the app_home_opened event why would it fail? does the app home page expects a 200 response in order to show the ui?

**Comment by neptunel** [comment]
Hello @juliocanares,
Can you turn on [debug logging ](https://slack.dev/bolt-python/concepts#logging) and share the output that you see when you trigger the app_home_opened event in your workspace? Also, sharing your setup code for the app_home_opened may help us to understand what's going on with the triggered event on your backend.

**Comment by seratch** [comment]
To display the Home tab, your app needs to perform a views.publish API call with valid user ID and view data. Refer to https://api.slack.com/methods/views.publish for more details.
