### ISSUE TITLE
How do I get my application to respond to a workflow submission thread?

### ISSUE THREAD

**Issue by cli7** [slackapi/bolt-python#677]
The Slack app I'm currently trying to create has a step in a workflow, following a send form step. After the send form step, the app receives the form's input information. I'd like the app to also respond to the workflow thread that was started in the channel to acknowledge that it has received the submission. I've tried different ways to get the workflow message's `ts` to post in the channel, but no luck so far.

I've tried:
- To get a `response_url` through the `modal` configuration in `edit`, but I realized that `edit` was for adding a workflow only.
- To get the message `ts` through `conversations.history`, using the `latest`/`oldest` parameters. However,  I was having trouble sifting through to get the exact message. For example, the timestamp given by the workflow when it starts is in the format `Tue, 28 Jun 2022 22:24:28`, not Unix timestamp. I'm not sure if different timezones would also be a problem.

Any ideas? Thank you so much!

#### The `slack_bolt` version
`slack_bolt==1.14.0`

**Comment by WilliamBergamin** [comment]
Hi @cli7 thanks for writing in!

I've looked into your question, and I believe you are correct the default `Send a form` workflow step does not currently support passing message metadata to the following steps if the `Send submitted responses to a channel or to someone in a DM` is set as true.
Here are some ideas that could allow you to accomplish this feature:

- You can build your own custom `Send a form` step that allows to pass the message metadata as output to a next step.
- If you know the title or pattern of the message being posted you can leverage the Message Event to allow your bot to trigger an action (post a message to a thread) when this pattern is posted in a channel something resembling this:
```python
app = App(
    token=os.environ.get("SLACK_BOT_TOKEN"),
    signing_secret=os.environ.get("SLACK_SIGNING_SECRET")
)
logging.basicConfig(level=logging.DEBUG)


def workflow_message_callback(context: BoltContext, client: WebClient, say: Say, logger: Logger):
    if (context.user_id != None):
        return
    try:
        conversations_history_resp = client.conversations_history(
            channel=context.channel_id,
            limit=5
        )
        message_tss = [float(message["ts"]) for message in conversations_history_resp["messages"]
                       if message["text"] == context.matches[0]]
        message_ts = max(message_tss)
        client.chat_postMessage(
            text="hello from thread",
            channel=context.channel_id,
            thread_ts=message_ts
        )
    except Exception as e:
        logger.error(e)

# Register Listeners
app.message(re.compile("(\*My Form Title\*.*)"))(workflow_message_callback)

# Start Bolt app
if __name__ == "__main__":
    SocketModeHandler(app, os.environ.get("SLACK_APP_TOKEN")).start()
```

Hopefully this helps you on your journey!

**Comment by cli7** [comment]
Hi @WilliamBergamin thanks for looking into it! Definitely helpful 👍
