### ISSUE TITLE
Slack Web Socket Connection

### ISSUE THREAD

**Issue by Tavofn** [slackapi/bolt-python#680]
I'm working on a slack bot that requires a web socket connection. I have a restart script that restarts the web socket connection  every 2 hours, however, I would like to know is there a recommended time interval to restart a web socket connection?

**Comment by seratch** [comment]
Hi @Tavofn, thanks for writing in! 

bolt-python (more precisely speaking, its underlying socket mode client module) has a robust heartbeat mechanism, which deliberately monitors the WS connection. If an issue with the connection is detected, bolt automatically reconnects to the server for you. Thus, if your purpose is for connection stability, you don't need to restart your app. If you see any issues with the reconnection logic, sharing what happened to you and debug-level log outputs would be appreciated.

If you would like to restart your app for some other reason, two hour interval is okay.

**Comment by Tavofn** [comment]
Awesome! Just what I needed! Thank you!
