### ISSUE TITLE
Is lazy listeners available for cloud functions?

### ISSUE THREAD

**Issue by andrewkaldani30** [slackapi/bolt-python#687]
(Describe your issue and goal here)

### Reproducible in:
Using Bolt Python with cloud function 

#### The `slack_bolt` version
1.14.2

#### Python runtime version

3.10

Hi,
I am using Slacks api to build a slack slash command and deploying it to cloud functions. I need to acknowledge the http post request within the 3 seconds and process my other code. My other code will take longer than the 3 second requirement, so ideally I would like to acknowledge the slack request first then continue the process of my function. I noticed that you have lazy listeners feature for AWS and was wondering if this is something for use in cloud functions or something similar to use for cloud functions?

**Comment by seratch** [comment]
Hi @andrewkaldani30, thanks for writing in. 

Unfortunately, Lazy Listeners feature is not available for Google Cloud Functions. Also, we don't have plans to implement the feature for Cloud Functions at least in the short term. Refer to https://github.com/slackapi/bolt-python/issues/46#issuecomment-930048433 for more context. 

As for Google Cloud use cases, we'd suggest going with either Cloud Run or App Engine. I hope this helps.
