### ISSUE TITLE
Plain-text input element for Modal — Numeric values only

### ISSUE THREAD

**Issue by smbock42** [slackapi/bolt-python#692]
HI all, I have a modal with a plain-text input element where I want only numbers to be inputted. Is there a way to do this? I searched for an answer with JSON and on all sites, but with no luck. Thank you. 

I am using Slack Bolt Python. 

#### Python runtime version

Python --3.7.10

#### OS info

macOS

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1.
2.
3.

### Expected result:

When you type in a letter or special character, you either get an error, or it won't let you type it in. Only numeric values expected. 

### Actual result:

Plain-text input works as normal. Any character is inputted and allowed. 

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by mwbrooks** [comment]
Hi @smbock42 👋🏻 

The Slack API only supports the `string` type for plain-text input elements. However, to require only numbers, you can implement your own input field validation on a view submission and display custom errors under the field.

Here is the [Bolt Python documentation to listen for view submissions](https://slack.dev/bolt-python/concepts#view_submissions). After your validation, you can [return an `errors` response action](https://api.slack.com/surfaces/modals/using#displaying_errors) with a custom error message for your plain-text input element.

Hope that helps!

**Comment by smbock42** [comment]
@mwbrooks Perfect -a an errors response action is exactly what I am looking for. Thank you!
