### ISSUE TITLE
Slack Bolt: Unable to receive slack message using bolt from Oauth installation

### ISSUE THREAD

**Issue by davidmartinsutc** [slackapi/bolt-python#695]
Hello,
I'm building a Slack app that I would like to share across multiple workspaces.

So I used the Oauth2 process: from a page, you can click on the button "Add to Slack" (available inside "Manage Distribution"). Then from the redirect URL, I get the code, and exchange it for an access_token xoxb-13.....

Then, I want to use bolt to receive the messages sent by an user to the bot. If I initialize the app using the bot token, everything works great.

Example:
```python
app = App(token="xoxb-1...")
    
@app.message("Go")
def start(message, say):
    print('It works')

if __name__ == "__main__":
    # Create an app-level token with connections:write scope
    handler = SocketModeHandler(app, "xapp-1-ABC....")
    handler.start()
```

But since I want to listen to messages coming from multiple workspaces, I would like to use the "[Authenticating with OAuth](https://slack.dev/bolt-python/concepts#authenticating-oauth)"

So, I do something similar, but instead of the bot token, I use:
```python
oauth_settings = OAuthSettings(
    client_id='13.......',
    client_secret='26.....',
    scopes=["channels:read", "channels:history", "channels:manage", "chat:write.customize", "im:history", "im:write", "users.profile:read", "users:read", "groups:read", "chat:write"]
)

app = App(
    signing_secret='70.....',
    oauth_settings=oauth_settings
)
    
# Add functionality here
@app.message("Go")
def start(message, say):
    print('It does not work')

    
if __name__ == "__main__":
    # Create an app-level token with connections:write scope
    handler = SocketModeHandler(app, "xapp-1-ABC....")
    handler.start()
```
(I also tried to add the installation_store and state_store parameters, although I don't really understand how they are fed.)

And every time I trigger the bot (by saying "Go" in by example) in its slack channel, I've got the error message: `Although the app should be installed into this workspace, the AuthorizeResult (returned value from authorize) for it was not found.`

Could someone tell me what I missed?
Thanks a lot!

#### The `slack_bolt` version

slack-bolt==1.14.3
slack-sdk==3.18.1

#### Python runtime version

Python 3.9.12

### Expected result:

I was expecting the app to handle the messages sent from slack. In my example, when I say "Go" to my bot.

### Actual result:

Instead, I've got this error message:
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/7838509/183091797-3b94bde2-efc9-4118-8d84-1068c7113734.png">

**Comment by seratch** [comment]
Hi @davidmartinsutc, thanks for asking the question.

>So I used the Oauth2 process: from a page, you can click on the button "Add to Slack" (available inside "Manage Distribution"). Then from the redirect URL, I get the code, and exchange it for an access_token xoxb-13.....

This is an easy-to-use way that app configuration page offers for single-workspace apps. When you enable the OAuth flow for your Bolt app, you no longer can use this way.

>Bolt for Python will also create a slack/install route, where you can find an Add to Slack button for your app to perform direct installs of your app. If you need any additional authorizations (user tokens) from users inside a team when your app is already installed or a reason to dynamically generate an install URL, you can pass your own custom URL generator to oauth_settings as authorize_url_generator.

As mentioned in the document like this, your app now has the OAuth endpoints `/slack/install` and `/slack/oauth_redirect` (if you go with the default paths). To install your app into a workspace through the OAuth flow, your workspace user (or yourself) needs to initiate the OAuth process from `https://{your bolt app's public domain}/slack/install` and complete it at `/slack/oauth_redirect`. For the app's public domain, you can use ngrok or something similar for local development.

I hope this was helpful to you.

**Comment by davidmartinsutc** [comment]
Hello Seratch,

Thank you for the answer. In my case, I cannot use bolt for the Oauth process.
I've created a webapp, within which users can click on the button "Add to slack".
Then, the redirect URL moves them back to the webapp because I need to know their internal team_id (team in the webapp).  Then, I exchange the code for a token, using the [oauth.v2.access](https://api.slack.com/methods/oauth.v2.access).

But, to handle the conversation of users inside the workspace, I would prefer to use bold (since it's a separate module / code).

What does the `/slack/install` endpoint do, that the oauth.v2.access doesn't? Is there a way to fill the gap?
Thank you !

**Comment by seratch** [comment]
@davidmartinsutc I still highly recommend using Bolt's OAuth flow as it is the easiest and the most secure way to implement the Slack OAuth flow. That being said, if you have to go with a different way, it's still feasible. In this case, you need to store the installation data using your `InstallationStore`'s save method plus your Bolt app has to use the same `InstallationStore`. Please refer to the underlying OAuth module's document for more details: https://slack.dev/python-slack-sdk/oauth/index.html

**Comment by davidmartinsutc** [comment]
Thank you, I'll give it a try !

**Comment by seratch** [comment]
>Can I use/is it recommended to use the metadata to forward information from my webapp to the redirect handler? (For example, internal team_id)

The best way we suggest is to use a browser cookie to transfer your service's user state. Since this should be quite straight-forward, you won't have any Bolt specific questions on this.

>When installing with the bold Oauth, if the workspace owner installs the app, can everybody in the workspace interact with the bot, or does every user has to do the installation?

This depends on the functionalities that you app requires. If your app needs only bot token scopes such as commands, chat:write as a bot user, only one person in a workspace needs to install the app. Perhaps, this would be your use case. Contrarily, if your app requires user token scopes as well, all the end-users in a workspace that would like to use the app have to install the app but I am guessing that this is not your use case.

I think that I've answered all your questions here. Would you mind closing this issue?

**Comment by davidmartinsutc** [comment]
Thank you for all the answers.
I'm doing more tests to dig into these use cases, but you answered all the blurry things.
