### ISSUE TITLE
How can I respond to a OPTIONS request with bolt-python?

### ISSUE THREAD

**Issue by Apollorion** [slackapi/bolt-python#699]
Im using bolt-python 1.14.3.
Im using the OAuthFlow and changing `handle_installation`.

I want to respond to `handle_installation` with:

```python
    return BoltResponse(
        status=200,
        body=json.dumps({"install_url": url}),
        headers=flow.append_set_cookie_headers(
            {
                "Content-Type": "text/html; charset=utf-8",
                "access-control-allow-origin": "*",
                "access-control-allow-methods": "*",
                "access-control-allow-headers": "*"
            },
            state_cookie,
        ),
    )
```

But I need the application to also respond with CORS on the preflight check in the browser. Is this possible to do? Basically need a way to return a response to an OPTIONS request.

**Comment by Apollorion** [comment]
Realized theres probably something around the OAuth spec that makes this not possible to do. Got around the issue by proxying the request through a second server that can respond with CORS, got it all working, but on the oauth redirect I get `invalid_browser` which I think has something to do with the referrer being different than what slack was expecting???

Either way, I engineered this and generated the html in bolt so I can just send users to the `/slack/install` url and it will retain the same look/feel as everything else.

**Comment by seratch** [comment]
Hi @Apollorion, I'm glad to hear that you've come up with a solution for the CORS request handling. 

Another way to handle an OTIONS method request would be using along with a web framework, which enables you to handle any HTTP requests. For instance, you can add any Flask routes as [this example demonstrates](https://github.com/slackapi/bolt-python/blob/main/examples/flask/oauth_app.py). You can find the list of all supported ones here:
* https://github.com/slackapi/bolt-python/tree/main/examples
* https://github.com/slackapi/bolt-python/tree/main/slack_bolt/adapter

>on the oauth redirect I get invalid_browser which I think has something to do with the referrer being different than what slack was expecting?

When installing your app through the OAuth flow served by a Bolt app, you need to start the OAuth flow at `/slack/install` path, not the slack.com authorize URL. Refer to [the past similar issues](https://github.com/slackapi/bolt-python/issues?q=is%3Aissue+invalid_browser+is%3Aclosed) as well.

I hope this helps!
