### ISSUE TITLE
Say() does not provide a response_url for the message it posts

### ISSUE THREAD

**Issue by ChrisPage-AT** [slackapi/bolt-python#700]
#### The `slack_bolt` version

1.14.3

#### Python runtime version

Python 3.10.4

#### OS info

ProductName:	macOS
ProductVersion:	12.5
BuildVersion:	21G72

#### Steps to reproduce:

I am making a bot to create release notes within our slack environment.  

1. The user enters the triggering command in slack.
2. The bot uses the Say() method to post the release notes.
3. The bot does additional processing, and I would like to modify the release notes post with a link to the pull request.  The Say() return value doesn't seem to provide enough information to call Respond() with "replace_original = True".
4. There is a Refresh button on the release notes post, and clicking calls a Respond() that does work.

### Expected result:

I would expect that Say() returns whatever is needed to modify the said message.  I need to be able to modify a message that hasn't received any user interaction.

### Actual result:

Say() does not return the necessary information.  I get the following error when trying to update the original message without any user interaction: "respond is unsupported here as there is no response_url"

**Comment by WilliamBergamin** [comment]
Hi @ChrisPage-AT thanks for witting in!

Under the hood `Say()` uses the `client.chat_postMessage` method this returns an [object containing information about the message](https://api.slack.com/methods/chat.postMessage#examples)

What I believe you are looking for is the `"ts"` value  in this payload, this allows slack to identify your message in a channel and perform various operations on it like [deleting](https://api.slack.com/methods/chat.delete) and [updating](https://api.slack.com/methods/chat.update).

Hopefully this helps you on your journey 🧭

**Comment by ChrisPage-AT** [comment]
How do I go about using that "ts" value to update a message?  I know how to use "ts" to reply in a thread but trying to use app.client.chat_update requires the channel id, and that isn't returned by Say() either.

**Comment by WilliamBergamin** [comment]
Bolt python uses [keyword injection](https://slack.dev/bolt-python/api-docs/slack_bolt/kwargs_injection/index.html) to parse the request and provide functions and data to the developers, here are 2 parameters that allow you to recover the `channel_id`, first through the [context](https://slack.dev/bolt-python/api-docs/slack_bolt/context/index.html) or directly with its parameter [channel_id](https://slack.dev/bolt-python/api-docs/slack_bolt/context/base_context.html)
here is an example:  
```python
@app.command("sample")
def sample_command(command, context, channel_id, ack: Ack, say: Say, logger: Logger):
    try:
        ack()
        say(
          f"this is my channel {context.channel_id} and here it is again {channel_id}"
        )
    except Exception as e:
        logger.error(e)
```
