### ISSUE TITLE
Failed to get interactive blocks response by action_id using bolt

### ISSUE THREAD

**Issue by mormasa** [slackapi/bolt-python#701]
Hi,
I have the following interactive blocks message which contains 2 buttons:
```python
[
    {
        "type": "actions",
        "elements": [
            {
                "type": "button",
                "text": {
                    "type": "plain_text",
                    "text": ":white_check_mark: Valid",
                },
                "style": "primary",
                "action_id": "a",
                "value": "click_me_123",
            },
            {
                "type": "button",
                "text": {
                    "type": "plain_text",
                    "text": ":x: Invalid",
                },
                "style": "danger",
                "action_id": "b",
                "value": "click_me_123",
            },
        ],
    }
]
```

However when I try to get the data using the action_id (upon a button click) it does nothing and doesn't seems to enter the handle_button_clicks method at all.
App code below (connecting using web socket):

```python
import os
from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler

bot_token = os.get("BOT_TOKEN")
app_token_level = os.get("APP_TOKEN")

app = App(token=bot_token)

@app.action("a")
def handle_button_clicks(ack, body, respond):
    ack()
    user_id = body["user"]["id"]
    respond(
        {
            "response_type": "in_channel",
            "replace_original": False,
            "text": f"<@{user_id}> clicked a button! (in_channel)",
        }
    )

@app.message("test")
def ask_who(message, say):
    print(message)
    say("_Who's there?_")

if __name__ == "__main__":
    handler = SocketModeHandler(app, app_token_level)
    handler.start()
```

The issue is only when I try to get the button press based on the action_id. The "test" message reply works good so it's not something with the websocket. Maybe I'm missing a permission in my Slack's app settings?
I subscribed my app to the following events types:

- message.channels
- message.groups
- message.im
- message.mpim

Not sure what I'm doing wrong or why it doesn't works...
Please advise.
Thanks!

**Comment by WilliamBergamin** [comment]
Hi @mormasa thanks for writing in!

I see a few things that could cause some issues, it seems like you may be passing the `bot_token` value as the `app_token`
```python
app_token_level = os.get("BOT_TOKEN")
```
should probably be something like
```python
app_token_level = os.get("APP_TOKEN_VARIABLE_NAME")
```

Also you don't seem to have implemented the action handler for `"b"` but this should not affect the behavior of `"a"`

**Comment by mormasa** [comment]
@WilliamBergamin you are right about the TOKENs.
Actually I was running it hardcoded locally butn't did want to post them here so I made this quick change but had this mistake :)

I don't think the missing "b" implementation should affect action "a".
In addition I added it and rerun but still nothing so I guess it's not that... :(

**Comment by WilliamBergamin** [comment]
Can you ensure you have enabled interactivity ([Step 5, Configure a Request](https://api.slack.com/tutorials/tracks/actionable-notifications))

If this is done would you be able to provide me more information/context on what the error is, a stack trace or error message.

**Comment by mormasa** [comment]
Yes, it's enabled. 
I don't get any stack trace or error message, when I click the button nothing happens and no logs are being generated.
On the other hand when I submit the message 'test' it gets it, log is being printed and it replies with the response message.

**Comment by WilliamBergamin** [comment]
I would try using the client directly and printing something to see if the event gets triggered, something like this:
```python
@app.action("a")
def handle_button_clicks(ack, client):
    print("I received the event")
    ack()
    client.post_message(channel_id=A_SPECIFIC_CHANNEL_ID, text="hello I'm the event")
    
```

**Comment by mormasa** [comment]
Thanks but already tried all of that and as mentioned above, it doesn't seems to enters the `handle_button_clicks` at all upon a button click.
No prints, no postback messages. Nothing happens..

**Comment by seratch** [comment]
@mormasa How do you post the channel message with buttons? If the message is not posted by your app's bot user, your app is unable to handle the click events. Also, I would suggest you to double-check your app configuration at **Features** > **Interactivity & Shortcuts** and the feature is enabled for sure. Creating a new simple Socket Mode app and checking how it works for you may be also a good approach to narrow your issue down.

**Comment by mormasa** [comment]
@seratch the message was posted to the channel by the app (seperate script) so the interaction response should work...
Here is what my Interactivity & Shoutcuts looks like...
Socket mode is enabled so ignore the request URL.
Also attached the Event Subscriptions settings of the app.
![image](https://user-images.githubusercontent.com/51478618/185552027-c8089284-473b-4c24-8678-2fd658957b44.png)
![image](https://user-images.githubusercontent.com/51478618/185552112-d9dd75b1-6d07-4956-aac7-0adc4f419565.png)

**Comment by seratch** [comment]
@mormasa I remember that, in the past, the app admin UI had a bug where the Socket Mode settings sometimes do not properly work when the app developer switched from Request URL endpoint way to Socket Mode without removing the Request URL settings. The issue may still remain. I would suggest trying the following:
* Temporarily switch back to HTTP endpoint mode from Socket Mode
* Remove the Request URL for interactivity
* Enable Socket Mode again

If the above does not help, sorry to say this but please consider creating a brand-new app with Socket Mode from the beginning.

**Comment by mormasa** [comment]
@seratch  - WOW! I don't believe it worked!
Steps to fix:

1. Disabled socket mode
2. Disabled interactive mode
3. Enabled socket mode
4. Enabled interactive mode so it will be without request URL

Thank you very much for your help!
I can't believe I spent a full day on this :)

**Comment by seratch** [comment]
Glad to hear that!
