### ISSUE TITLE
Seeing "Sorry, That hasn't worked. Try again?" Error even though there are no error logs in AWS Lambda

### ISSUE THREAD

**Issue by infinitetrooper** [slackapi/bolt-python#705]
#### The `slack_bolt` version

slack_bolt-1.14.3

#### Python runtime version

(Python 3.9)

#### OS info

AWS Lambda x86_64

#### Steps to reproduce:

My app has a message shortcut that schedules a response based on message content. When I click the message shortcut, the below error is shown on Slack even though the functioning of my app is perfect and there are no errors in AWS logs.

Can anyone help me with any patterns I need to look out for where this error occurs?

<img width="460" alt="Screenshot 2022-08-21 at 12 00 27 AM" src="https://user-images.githubusercontent.com/16632903/185761925-bd8a3d1d-3346-4a11-a842-551eb7cb588f.png">

**Comment by WilliamBergamin** [comment]
Hi @infinitetrooper, thanks for writing in!

A common reason slack will display this error message is to tell the user it was unable to reach your running application. Ensure you have set up the proper endpoint in your app configuration or that `socket mode` is running as intended.

Do you have some logs that indicate that your application is receiving the request from slack?

**Comment by infinitetrooper** [comment]
Hi @WilliamBergamin  - Thanks for replying.

I'm getting the logs from API Gateway and Lambda (shown below). After observing for a couple of days, this looks to be a Lambda Cold start issue as subsequent actions after the first action don't show errors. Do you have any advice to deal with cold starts where I'm not able to acknowledge under 3 seconds?

`{
    "requestId": "XRglDiCrBcwEMVA=",
    "ip": "44.192.27.204",
    "requestTime": "22/Aug/2022:16:26:08 +0000",
    "httpMethod": "POST",
    "routeKey": "POST /slack/events",
    "status": "200",
    "protocol": "HTTP/1.1",
    "responseLength": "0"
}`

**Comment by WilliamBergamin** [comment]
This might be an issue AWS is better suited to answer, lambda is not something I've used extensively in the past.

That being said you could try sending a test request from your local machine to manually trigger the `start issue` you are seeing. Another solution could be to use [slack socket-mode](https://api.slack.com/apis/connections/socket) this should establish a socket connection between your instance and slack during the [init stage of the lambda](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtime-environment.html#runtimes-lifecycle-ib) effectively creting a connection between slack and your application before a user triggers a request.

**Comment by infinitetrooper** [comment]
Thanks a lot @WilliamBergamin, Will go through your suggestions. Closing this for the moment, will reopen if necessary.
