### ISSUE TITLE
Migration path from slack-sdk to slack bolt

### ISSUE THREAD

**Issue by yashvesikar** [slackapi/bolt-python#711]
(Describe your issue and goal here)

i am working on a slack application built entirely using [python-slack-sdk](https://github.com/slackapi/python-slack-sdk) and have started running into performance issues relating to the 3 second timeout.

i am looking to migrate to bolt-python but am having trouble finding guidance on how to migrate an existing application to this sdk. my apologies if this documentation already exists somewhere - i was just unable to find it.

my questions are:
- is there any official guidance on migrating from a python-slack-sdk application to bolt-python?
- is it possible to run 2 applications concurrently so i can write new features using bolt-python and slowly migrate existing features to bolt-python over time?

#### Python runtime version

3.9.10

#### OS info

MacOS/Linux

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @yashvesikar, thanks for writing in!

>is there any official guidance on migrating from a python-slack-sdk application to bolt-python?

No, there isn't but bolt-python project has a plenty of [example code](https://github.com/slackapi/bolt-python/tree/main/examples) and [scenario tests](https://github.com/slackapi/bolt-python/tree/main/tests/scenario_tests). You can learn how to use bolt-python for your use cases by checking those code.

>is it possible to run 2 applications concurrently so i can write new features using bolt-python and slowly migrate existing features to bolt-python over time?

The answer depends on the structure of your app but generally running two apps may not be easy. More specifically, having two different Request URLs for interactivity, Events API, and so on is not feasible while you can have a different Request URL for each slash command and external select menu's option URL.

Contrarily, migrating a simple app step by step is much easier. Since bolt-python itself internally depends on slack-sdk, you can use bolt-python handlers only for newly added slash commands, modal submissions, and so on.

If you run your app with Flask, your Flask endpoint can be something like this during the migration period:

```python
from slack_bolt import App
app = App()

@app.event("app_mention")
def event_test(say):
    say("What's up?")

from flask import Flask, request
from slack_bolt.adapter.flask import SlackRequestHandler

flask_app = Flask(__name__)
handler = SlackRequestHandler(app)

@flask_app.route("/slack/events", methods=["POST"])
def slack_events():
    if _is_legacy_endpoint_request(request):
        return _your_own_existing_code_here(request)
    else:
        return handler.handle(request)
```

I hope this helps.

**Comment by yashvesikar** [comment]
@seratch thank you for the speedy reply!

> while you can have a different Request URL for each slash command and external select menu's option URL.
would you be able to explain this a bit more? my understanding is that an application can only have a single request url. 
so based on the sample code you provided above is there a simple way to implement `_is_legacy_endpoint_request(request)` such that a single endpoint can handle both kinds of requests? or does that function need to be coupled to business logic i.e. something like this for interactive messages?:

```python
@flask_app.route("/slack/events", methods=["POST"])
def slack_events():
    if _is_legacy_endpoint_request(request):
        return _your_own_existing_code_here(request)
    else:
        return handler.handle(request)

def _is_legacy_endpoint_request(request):
    payload = json.loads(request.form["payload"])
    message_type = payload.get("type")
    actions = payload.get("actions")
    if message_type == "block_actions" and actions and actions[0].get("action_id) in {SOME LIST OF ACTION IDS}:
        return True
    return False
```

my apologies for not mentioning this beforehand (github didn't save my original question 😕) but the application i am considering migrating is quite large and being used in production so uptime is critical for us.

do you have any other suggestions or pitfalls to avoid when considering migrating a large codebase to slack-bolt?
if it would be beneficial to you and your team i am happy to document the process of migrating a large codebase from python-slack-sdk to slack-bolt as long as there is a migration path that is incremental 🙂

**Comment by seratch** [comment]
@yashvesikar 
>my understanding is that an application can only have a single request url

Indeed, using a single Request URL for everything is generally recommended as it is easy to manage. However, technically it's possible to use different Request URLs per a Slack Platform feature. You can find **Request URL** in each feature's configuration part (if you are not sure about this, please go to your Slack App configuration page and visit all the pages there). For instance, if your app provides 3 slash commands, you can use three different endpoints for each if you would like to do. If you would like to handle external select menu at a different path (e.g., /slack/select-menu-options), it's also possible. Similarly, you can go with different ones for Interactivity, Events API, and so on.

>_is_legacy_endpoint_request(request) such that a single endpoint can handle both kinds of requests? or does that function need to be coupled to business logic i.e. something like this for interactive messages?:

This depends on how you want to manage your app. If you are using a single Request URL, dispatching requests inside the URL handler. Looking at your pseudo code, perhaps, it would be your situation.

>do you have any other suggestions or pitfalls to avoid when considering migrating a large codebase to slack-bolt?

I cannot think of any hardships for the migration but if your app enables the OAuth flow on your way and does not use `InstallationStore` etc. at all, sharing the installation data with the `/slack/events` endpoint may require some efforts to make the way to fetch tokens and installation data from your database. If you simply use a single bot token that you've acquired by the steps from "Install the App" button in your app configuration page, no need to worry about this at all.

>if it would be beneficial to you and your team i am happy to document the process of migrating a large codebase from python-slack-sdk to slack-bolt as long as there is a migration path that is incremental 

Thanks for saying this. We are not planning to add the section to our own documents but sharing your knowledges in your blog would be beneficial for others!

Would you mind closing this issue now? Whenever you get a specific question for the migration, please feel free to create a new question issue for each.

**Comment by yashvesikar** [comment]
will close the issue for now, i am sure i will have more questions in this journey - thank you very much for the information so far!
