### ISSUE TITLE
"message_deleted" subtype not detected as a "self event"?

### ISSUE THREAD

**Issue by eddyg** [slackapi/bolt-python#724]
Unless I'm missing something, it seems that when an app calls `chat.delete` to delete one of its messages, and the app is configured to listen for messages with the `message_deleted` subtype, the `message_deleted` event from the app gets sent to the listener, even though it's from the app.

I was thinking this should've been handled automatically by the [ignoring_self_events](https://slack.dev/bolt-python/api-docs/slack_bolt/middleware/ignoring_self_events/ignoring_self_events.html) middleware (since `ignoring_self_events_enabled=True` is the default).

Is there any logic that could be added to [is_self_event](https://github.com/slackapi/bolt-python/blob/main/slack_bolt/middleware/ignoring_self_events/ignoring_self_events.py#L40) to ignore a `message_deleted` event from the app? (I looked at an example event, and I didn't see a `user_id` object, which seems to be a requirement for `is_self_event`.)

If not, I'm wondering if [adding a bit of metadata](https://api.slack.com/metadata/publishing#sending_metadata) to each message from the app would make it easy to filter them via some custom middleware?

Thanks! 

### Reproducible in:

```
slack-bolt==1.14.3
slack-sdk==3.18.3
Python 3.10.6
```

**Comment by seratch** [comment]
Hi @eddyg, thanks for writing in! In the scenario, your app knows the channel and ts of the message when deleting it. So, I think that calling `conversations.history` API method with the message's ts plus limit=1 to fetch the message metadata before deleting it sounds more straight-forward.

If the above does not work for you, it's technically possible to add more granular configuration on the bolt side. However, this specific use case sounds like a common one to me. I would suggest setting `ignoring_self_events_enabled=False` and having your own logic to filter in your custom global middleware as this approach should be more flexible and easier to maintain. What do you think?

**Comment by eddyg** [comment]
Hi @seratch, thanks for the quick reply!

I guess the point of my inquiry was to confirm that, based on the information contained in a `message_deleted` subtype event, there is no "easy" way to _directly_ know _who_ caused the deletion (e.g. the app itself). It sounds like some extra information is required, which is what I suspected but was curious about.

I appreciate your suggestions, and think I have a good path path forward now. Thanks again! 🙇
