### ISSUE TITLE
Add slack reaction, edit previous message even possible ?

### ISSUE THREAD

**Issue by sielaq** [slackapi/bolt-python#728]
Hi fellows,

I'm not sure, might be bolt api does not support it, I cant find any similar examples
Is it possible to do such things like:

1. Add slack reaction to the message that my bot have just send, like adding:  1️⃣ 2️⃣  ... ✅   as reactions ( I don't want to spam slack messages)
2. Edit slack message, that just have been send by my bot, and append "dots" every minute -  to show that "progress" is still ongoing ...

thx in advance

**Comment by e-zim** [comment]
Hey @sielaq! Adding reactions and updating the message your bot sends can be done using [reactions.add](https://api.slack.com/methods/reactions.add) and [chat.update](https://api.slack.com/methods/chat.update) respectively. Both of these will require the timestamp and channel id of the original message, so if you're keeping track of these you should be golden! I hope this paints a promising picture of what's possible!

**Comment by sielaq** [comment]
@e-zim thx a lot. That was super helpful. I had to add extra bot-permissions like `reactions:write` and works fine.
