### ISSUE TITLE
Calling another app from my app's code

### ISSUE THREAD

**Issue by dmellonielet** [slackapi/bolt-python#729]
Hi, Is it possible to call another app from my app's code in response to an incoming message?

Example- I'd like my app to call the JIRA app and perform an action.

Pseudo- 

```
@app.message(re.compile("(new API)"))
def say_auto_response(say, context):
    req = context['matches'][0]
    say(f"@Jira do xyz")
```

**Comment by e-zim** [comment]
It appears so! One app can listen to messages from another using [the bot_message event](https://api.slack.com/events/message/bot_message), a sub-category of [the message event](https://api.slack.com/events/message). In Python, you can [check the subtype](https://slack.dev/bolt-python/concepts#event-listening) like so:

```
@app.event(event="message")
def serve_customer(event, message, say):
    if message.get("subtype") == "bot_message":
        say(text="Not with that attitude!", channel="C007733")
    else:
        user = event["user"]
        text = f"What's brewin' <@{user}>"
        say(text=text, channel="C007733")
```

**Proof!**
<img width="500" alt="a conversation between one person and two bots" src="https://user-images.githubusercontent.com/18134219/193171406-933ad64c-80db-4976-9b34-b09602a6569e.png">

**Comment by e-zim** [comment]
However.. many apps make use of [slash commands](https://api.slack.com/interactivity/slash-commands) which must be called by an actual person, so calling a Jira command from your app will unfortunately not work. In this case, you would likely want to make direct API calls from the event/message handler or use other libraries to accomplish what this other app can do.

**Comment by hello-ashleyintech** [comment]
@dmellonielet Thanks for the thumbs up response to @e-zim's reply! It looks like this issue has been resolved, so I'll be closing it. If you run into any other issues, please feel free to [submit a new issue](https://github.com/slackapi/bolt-python/issues/new/choose) and we'd be happy to help! :)
