### ISSUE TITLE
How to use app-at-mention with AWS Lambda Bolt Python

### ISSUE THREAD

**Issue by vumdao** [slackapi/bolt-python#730]
The example of aws_lambda said that Both respond to the Slash Command `/hello-bolt-python-lambda` and both respond to app at-mentions but I don't see any where show how to test with app@ mention
```
@app.event("app_mention")
def handle_app_mentions(body, say, logger):
    logger.info(body)
    say("What's up?")
```

### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version
slack-bolt 1.15.0

#### Python runtime version
3.9

#### OS info
AWS Lambda with python runtime

**Comment by e-zim** [comment]
Hi @vumdao! 👋  The above function looks like it should be listening for app mentions, but there may be an event subscription missing. Before your app can listen for mentions, you will have to subscribe to the `app_mention` bot event ([Your Apps](https://api.slack.com/apps) > Event Subscriptions > Subscribe to bot events).

With this event subscribed to, you can check if things are working by sending a message such as "hello @yourbotname" to a channel that your bot is a member of (sending this message will give you the option to add your bot to the channel too). If everything is working, you should get a response in channel from your bot! Hope this helps!

**Comment by vumdao** [comment]
Thanks @e-zim for your help, I can now use app_mention successfully!
