### ISSUE TITLE
Q: Does 'respond()' support a parameter like 'parse'?

### ISSUE THREAD

**Issue by eddyg** [slackapi/bolt-python#733]
I recently noticed that I can't pass a `parse` argument to `respond()`.

Looking at [the code](https://github.com/slackapi/bolt-python/blob/b637c298/slack_bolt/context/respond/async_respond.py#L29-L36) it's not listed as an argument.

I thought this was potentially just a simple oversight, but even in my testing where I _manually_ hacked in support for `parse`, Slack still seemed to linkify the contents of the message. I was curious if there was a way to prevent the extra parsing (and would be willing to submit a PR if there's something that could be added).

I couldn't find anything [in the docs](https://api.slack.com/interactivity/handling#message_responses) that said `parse` _wasn't_ available, but perhaps it's not?

Basically, my question: is there any way to respond to something like a slash-command and _not_ have the contents of the message "parsed"? In particular, I'm trying to avoid email addresses and phone numbers from being turned in to links.

### Reproducible in:

```bash
slack-bolt==1.15.0
slack-sdk==3.18.4
```

#### Steps to reproduce:

Setup a slash-command responder that includes an email address and phone number:

```python
@app.command("/support")
async def command(ack, body, respond):
    await ack()
    await respond(
        f"Hi <@{body['user_id']}>! You can contact support via email at support@example.com "
        "or by calling 888-555-1212"
    )
```

### Expected result:

I'd like to be able to specify something like `parse=False` (or, if necessary, `parse="none"`) and _not_ have `support@example.com` or `888-555-1212` converted to "links".

### Actual result:

email addresses and phone numbers are turned into links.

**Comment by WilliamBergamin** [comment]
Hi @eddyg thanks for writing in 💯 

Have you tried using blocks instead of the default `text` parameter?
From my tests using a `plain_text` `section` block seems to fit your needs, here is an example of what I've implemented
```python
@app.command("/support")
def sample_command_callback(ack: Ack, respond: Respond, logger: Logger):
    try:
        ack()
        respond(
            blocks=[
                {
                    "type": "section",
                    "text": {
                        "type": "plain_text",
                        "text": " You can contact support via email at support@example.com or by 888-555-1212",
                        "emoji": False
                    }
                }])
    except Exception as e:
        logger.error(e)
```

This is what gets posted to slack
<img width="691" alt="Screen Shot 2022-10-04 at 1 20 29 PM" src="https://user-images.githubusercontent.com/25348381/193884911-ede75116-93eb-455f-b94c-16bd914956bd.png">

I use the [block kit builder](https://app.slack.com/block-kit-builder/) to help me view and create the various blocks

Let me know if this answers your question 🗺️

**Comment by eddyg** [comment]
_D'oh!_ I didn't even think about trying a plain-text block. Thanks for the suggestion! 🎉 

Do you know if [this limitation with blocks](https://api.slack.com/messaging/composing/layouts#limitations) still poses a concern?

**Comment by WilliamBergamin** [comment]
That is a great question 🥇  I have personally never encountered this limitation and most slack bots use `blocks` in some way, but I am asking around to see if this is still valid

**Comment by eddyg** [comment]
Great! I have been wondering if it was "safe" to start using blocks; based on your comment it sounds like it should be, and perhaps that doc page is just are out-of-date.

Thanks again!

**Comment by WilliamBergamin** [comment]
From the internal feedback I obtained the above limitation section in the `blocks` documentation is not valid anymore and will be updated soon 🔖
