### ISSUE TITLE
Question: How to start a HTTPS connection using Slack Bolt Framework

### ISSUE THREAD

**Issue by kenho811** [slackapi/bolt-python#735]
(Describe your issue and goal here)

<img width="635" alt="image" src="https://user-images.githubusercontent.com/57944769/194371255-f5631311-2ac7-47c7-a9d6-619d6f733f74.png">

According to the documentation, setting up HTTP connection is quite easy. 

Is there a way to create HTTPS connection by passing something like ssl_context to the app.start() method?

I found some resources as follows

<img width="669" alt="image" src="https://user-images.githubusercontent.com/57944769/194371746-89b3e8f4-62d1-4d59-8ef6-53fcc4f3492a.png">

https://stackoverflow.com/questions/59808346/python-3-slack-client-ssl-sslcertverificationerror

It seems that the Slack Python SDK allows passing the ssl_context parameter, but I am not sure if the Slack Bolt Framework allows that as well?

Can anyone advise?

THank you

\

**Comment by WilliamBergamin** [comment]
Hi @kenho811 thanks for writing in!

The client used in the Bolt framework is actually the one defined in the SDK, it is possible to create your own `client` with your specific additional fields and pass it to the `Bolt App`, below is an example of what passing the ssl context could look like

```python
import os
import logging
import ssl
import certifi

logging.basicConfig(level=logging.DEBUG)

from slack_bolt import App
from slack_sdk import WebClient

ssl_context = ssl.create_default_context(cafile=certifi.where())
# Install the Slack app and get xoxb- token in advance
app = App(client=WebClient(token=os.environ['SLACK_BOT_TOKEN'], ssl=ssl_context))

# Add functionality here

if __name__ == "__main__":
    app.start(3000)
```

Hopefully this helps you on your journey 🗺️

**Comment by kenho811** [comment]
That's very helpful.

Thank you so much ;))
