### ISSUE TITLE
Listening for a dynamically named interactive element

### ISSUE THREAD

**Issue by IronicTrout** [slackapi/bolt-python#737]
Hi. I'm trying to write a bot that does polls (among other things) where the user can define a poll and has buttons that correspond the multiple options of the poll, however I'm experiencing an issue when trying to listen for the button clicks on a poll and determine which button is clicked.

Thank you for any help in advance!

#### The `slack_bolt` version

slack-bolt==1.15.1
slack-sdk==3.19.1

#### Python runtime version

Python 3.9.13

#### OS info

ProductName:    macOS
ProductVersion: 12.5.1
BuildVersion:   21G83

#### Steps to reproduce:

```python
@app.block_action("") #<------- What goes here, I understand it's an action ID, but I have multiple actions with variable ids
def doTheThing(ack, body, logger):
    print("do the thing")


def constructPollblock(title, options, num_members = 0):

    global empty_bubble

    elements = []
    fields = []
    for option in options:

        elements.append({
            "type": "button",
            "text": {
                "type": "plain_text",
                "text": option
            },
            "value": option,
            "action_id": title.replace(' ', '_') + '_' + option
        })

        fields.append({
            "type": "mrkdwn",
            "text": "*"+option+"*"
        })

        fields.append({
            "type": "plain_text",
            "text": empty_bubble*num_members + " " + str(num_members)
        })

    return [
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": title
            }
        },
        {
            "type": "divider"
        },
        {
            "type": "section",
            "fields": fields
        },
        {
            "type": "actions",
            "block_id": "poll_answers",
            "elements": elements
        }
    ]
```

### Expected result:

I want that to be called when any interactive button is clicked and determine its id

### Actual result:

```bash
Unhandled request ({'type': 'block_actions', 'block_id': 'poll_answers', 'action_id': 'poll_1_option_1'})
---
[Suggestion] You can handle this type of event with the following listener function:

@app.action("poll_1_option_1") #<-----this id is dynamically made
def handle_some_action(ack, body, logger):
    ack()
    logger.info(body)
```

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @IronicTrout, thanks for asking the question! You can use regular expression for the matching patterns like `app.message` listener example in the document does: https://slack.dev/bolt-python/concepts#message-listening In the same way, you can use reg exp for any listener constraints.

<img width="500" src="https://user-images.githubusercontent.com/19658/195467255-1e9b93dc-8760-4fcd-94f4-36be0430d044.png">

**Comment by IronicTrout** [comment]
That works perfectly! Thank you!
