### ISSUE TITLE
Is it possible to set reply_broadcast in say() function?

### ISSUE THREAD

**Issue by jacklowrie** [slackapi/bolt-python#738]
Looking in the [api docs at the `Say` class](https://slack.dev/bolt-python/api-docs/slack_bolt/context/say/say.html#slack_bolt.context.say.say.Say), it seems like this might not be supported, since `reply_broadcast`isn't a possible parameter, but wanted to check in case I missed something.

If it's not, what would be a better way to send a broadcast reply message from a listener function?

Thanks!

**Comment by seratch** [comment]
Hi @jacklowrie, thanks for asking this! Indeed, reply_broadcast is not in the keyword arguments but passing it actually works: https://github.com/slackapi/bolt-python/blob/v1.15.1/slack_bolt/context/say/say.py#L47 We will update the code for more clarity.

**Comment by jacklowrie** [comment]
Thanks so much! works like a charm.
