### ISSUE TITLE
Modal not invoking in my app

### ISSUE THREAD

**Issue by dmellonielet** [slackapi/bolt-python#739]
I am trying to create a modal in my app that can be invoked as a shortcut.
I've configured this in the app setting and my code looks like this (I referred the bolt docs.)

I'm not seeing the modal invoked when I execute the shortcut from the Slack UI. What am I missing?

```python
@app.shortcut("open_modal")
def open_modal(ack, body, client):
    # Acknowledge the command request
    ack()

    # Call views_open with the built-in client
    client.views_open(
        # Pass a valid trigger_id within 3 seconds of receiving it
        trigger_id=body["trigger_id"],
        # View payload
        view={
            "type": "modal",
            # View identifier
            "callback_id": "intake", #configured in app setting
            "title": {"type": "plain_text", "text": "My App"},
            "submit": {"type": "plain_text", "text": "Submit"},
            "blocks": [
                {
                    "type": "section",
                    "text": {"type": "mrkdwn", "text": "Welcome to a modal with _blocks_"},
                    "accessory": {
                        "type": "button",
                        "text": {"type": "plain_text", "text": "Click me!"},
                        "action_id": "button_abc"
                    }
                }
            ]
        }
    )
```

**Comment by seratch** [comment]
Hi @dmellonielet, thanks for asking the question! I'd suggest a few things to try:

* Turn debug-level logging on to get more detailed information about your app's behavior: https://slack.dev/bolt-python/concepts#logging
* Double-check if your global shortcut is configured with callback_id: open_modal
* If your app enables Socket Mode, your app may have outdated connections somewhere. Try the steps [here](https://github.com/slackapi/java-slack-sdk/issues/803#issuecomment-895768180) to resolve the situation
* If your app does not enable Socket Mode, double-check the Request URL in your Slack app configuration page (Interactivity & Shortcuts section)

Also, if you can share anything furthers, others may be able to help you identify what's wrong with your app more easily. I hope you will figure out the cause soon!

**Comment by dmellonielet** [comment]
<img width="641" alt="Screen Shot 2022-10-14 at 5 04 36 PM" src="https://user-images.githubusercontent.com/9063664/195959504-15b17135-4237-4f75-a741-f985b218c26d.png">

@seratch I didn't quite understand what you meant by 'double-check if your global shortcut is configured with callback_id: open_modal'. The above is how my global shortcut is configured.

Also, from debug logs:

```
DEBUG:slack_bolt.App:A new message enqueued (current queue size: 1)
DEBUG:slack_bolt.App:A message dequeued (current queue size: 0)
DEBUG:slack_bolt.App:Message processing started (type: interactive, envelope_id: f59bb71b-d181-4f19-9cdc-05c8e137bf72)
DEBUG:slack_bolt.App:Applying slack_bolt.middleware.ssl_check.ssl_check.SslCheck
DEBUG:slack_bolt.App:Applying slack_bolt.middleware.request_verification.request_verification.RequestVerification
DEBUG:slack_bolt.App:Applying slack_bolt.middleware.authorization.single_team_authorization.SingleTeamAuthorization
DEBUG:slack_bolt.App:Applying slack_bolt.middleware.ignoring_self_events.ignoring_self_events.IgnoringSelfEvents
DEBUG:slack_bolt.App:Applying slack_bolt.middleware.url_verification.url_verification.UrlVerification
DEBUG:slack_bolt.App:Checking listener: say_auto_response ...
DEBUG:slack_bolt.App:Checking listener: repeat_text ...
DEBUG:slack_bolt.App:Checking listener: repeat_text ...
DEBUG:slack_bolt.App:Checking listener: ask_for_introduction ...
DEBUG:slack_bolt.App:Checking listener: update_home_tab ...
DEBUG:slack_bolt.App:Checking listener: open_modal ...
DEBUG:slack_bolt.App:Checking listener: action_button_click ...
DEBUG:slack_bolt.App:Checking listener: handle_app_mention_events ...
DEBUG:slack_bolt.App:
DEBUG:slack_bolt.App:Sending a message (session id: 38d962c5-2ca3-4d20-8fc0-53ae8fda20e2, message: {"envelope_id": "f59bb71b-d181-4f19-9cdc-05c8e137bf72", "payload": {"text": "failed"}})
```
It shows the error I've configured with :

```
@app.error
def handle_errors(error, logger):
    if isinstance(error, BoltUnhandledRequestError):
        # you may want to have some logging here
        logger.debug(error)
        return BoltResponse(status=200, body="failed")
    else:
        # other error patterns
        return BoltResponse(status=500, body="Something Wrong")
```

**Comment by seratch** [comment]
@dmellonielet It seems that you've set "intake" for the global shortcut's callback ID. In this case, your bolt-python code needs to be consistent with it. Your code should have a `@app.shortcut("intake")` listener for handling the pattern. Does this make sense? 

Also, for local development, the built-in error handler can provide more useful information for you. Disabling your own one when you are stuck with something may be helpful too.

**Comment by dmellonielet** [comment]
@seratch This was exactly it. My code did not reflect the call back id as part of the `@app.shortcut`.
Now it works. Thank you for helping me figure this out.

This part would be good to clarify in the docs too.
