### ISSUE TITLE
Testing slack bot events to our chatbot in Python

### ISSUE THREAD

**Issue by jdimapilis02** [slackapi/bolt-python#742]
Issue: We are currently unable to receive the payloads from the Slackbot. We reached out to Slack Support via Feedback and Aubrey from the support desk executed a test and they notified us about below: 

`Your configured Event Subscriptions Request URL endpoint is not successfully acknowledging the Slack event callbacks meaning that even after receiving the event callback, your endpoint is not sending back the expected HTTP 200 status code, but rather it's sending back HTTP 403 which indicates that the callback requests were "Forbidden" so it seems that your endpoint is rejecting our event callbacks.`

Goal: Our goal is for the slack events to be registered properly in the chatbot, currently we are not receiving it so we are also exploring other ways to be able to test this and identify what is wrong. 

#### The `slack_bolt` version

slack==0.0.2
slack-bolt==1.6.0
slack-sdk==3.18.4
slackblocks==0.2.5
slackclient==2.7.2
slackeventsapi==3.0.1

#### Python runtime version

Python 3.7.11

#### OS info

#1 SMP Sat Aug 27 02:44:20 EDT 2022

#### Problem: The chatbot does not seem to receive the payload from slack.
Current situation: Once we attempt to trigger an event, the chatbot remains the same saying "⚡Bolt App is Running"

#### What we have tried: 
•	Reinstalling the application to ensure that all my changes were saved and were reflected properly in my Slack Environment
•	Testing the communication by curling through to the URL (it responded with challenge parameter). 
•	Testing the communication by entering some text via DM / channel communication and opening the homepage.

Since we wanted to test the below events, we tried executing appropriate actions for these: 

- app_home_opened
- message.channels
- message.groups
- message.im

##### For the items that the team asked us for earlier, it is included below: 
•	Slack API ID: A043X1Y2MK6
•	URL of Slack Workspace: https://docomo-data-strategy.slack.com/
•	What event type are you expecting to get? We subscribed to below events. We wanted to try app_home_opened, message.im, message.channels, etc.

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @jdimapilis02, thanks for asking the question.

First off, bolt-python's framework code can send any of 200, 401, 500 but it never sends 403 HTTP status responses. Thus, I cannot tell anything further from a bolt-python maintainer's perspective.

If your code built on top of bolt-python also does not respond with 403 at all, the only cause that I can think of is, perhaps, your load balancer, proxy, WAF(Web Application Firewall), or something equivalent in front of the bolt-python app process might be rejecting HTTPS requests from Slack. Here is a simple diagram that describes what I'm guessing:

>Slack API server -(internet)-> Your public endpoint `https://{your domain}/slack/events` -> ??? -> bolt-python app server instance

I would suggest checking what's happening at the `???` part by adding more tracing logs on your infra. I hope this was helpful to you.
