### ISSUE TITLE
How to retrieve the value from a conversation drop down?

### ISSUE THREAD

**Issue by bg339** [slackapi/bolt-python#743]
(Describe your issue and goal here)
Have the following code below. This shows a list of the channels. I want to get the value of the channel selected, ex: if a user selects general, I want to be able to get that value. I have the following code after it. A little bit confused on how to approach this.

### Reproducible in:
slack-bolt==1.15.1
slack-sdk==3.19.1
Python 3.7.10

### Steps to reproduce:

```python
{
                    "type": "section",
                    "block_id": "channel_selection_list",
                    "text": {
                    "type": "mrkdwn",
                    "text": "Pick channel from the list"
                    },
                    "accessory": {
                    "action_id": "channel_selection_action",
                    "type": "multi_conversations_select",
                    "placeholder": {
                        "type": "plain_text",
                        "text": "Select channel",
                        "emoji": True
                    }
                    }
            },

@app.action("channel_selection_action")
def show_multi_options(body, ack, logger):
    ack()
    logger.info(body)
```

#### OS info

#1 SMP
Amazon Linux 2

### Expected result:

When a user selects a conversation from the drop down menu, I want to be able to retreive which channel was selected and be able to store in a local variable.

### Actual result:

When the the channel is selected and the confirm button is clicked, no action is done because I am unsure of how to approach this. Ive already created a function for the action_id I just do not know what logic to use to approach this

**Comment by srajiang** [comment]
Hi @bg339, Have you made sure to subscribe to Interactivity in your apps App Config page? It's possible that Slack doesn't know to send your app events for user actions on your apps drop down menu . 

You can head to https://api.slack.com/apps --> select your app -->  Interactivity and Shortcuts
<img width="872" alt="Screen Shot 2022-10-19 at 9 23 15 AM" src="https://user-images.githubusercontent.com/55667998/196748898-02c3ebef-4e1f-4021-a30b-7681a7102bfd.png">

**Comment by bg339** [comment]
Yes I have interactivity and shortcuts enabled! Im able to do other functions i.e clicking a button and it being able to send a message. I am designing the UI/UX right now. The screenshot below is what the UI looks like for the survey creator. My issue is related to the portion where it says create survey. I have an action_id associated with the channel selection but I am not able to retreive which channel is selected. I also attached a screenshot of the code.

![Screen Shot 2022-10-19 at 12 51 42 PM](https://user-images.githubusercontent.com/98499966/196756287-485c9a02-1494-4b04-a22d-a2ca0754553b.png)

<img width="750" alt="Screen Shot 2022-10-19 at 1 01 38 PM" src="https://user-images.githubusercontent.com/98499966/196756959-e5763186-202e-4a5b-aa25-aba6e6e519b0.png">
