### ISSUE TITLE
How to respond to Events API challenge from a Google Cloud Function?

### ISSUE THREAD

**Issue by bmckerry** [slackapi/bolt-python#750]
I'm trying to deploy a locally hosted app into a Google Cloud Function. When locally hosting the app via ngrok, I was able to set up the events API by just pointing the `Request URL` to `https://{ngrok-id}.ngrok.io/slack/events`. I've deployed the source code to a 1st gen cloud function, but when I try setting the slack app's `Request URL` to my function's Trigger URL (`https://us-central-1-{project_name}.cloudfunctions.net/{function_name}/slack/events`), it responds with an HTTP error instead of the challenge token. How can I respond with the challenge token from my function?

### Reproducible in:

```bash
pip freeze | grep slack
slack-bolt==1.15.1

python --version
Python 3.10.6

sw_vers && uname -v # or `ver`
ProductName:	macOS
ProductVersion:	12.5.1
```

#### Steps to reproduce:

Abbreviated source code:
```python
from slack_bolt import App
from slack_bolt.adapter.google_cloud_functions import SlackRequestHandler
from flask import Request
import logging

logging.basicConfig(level=logging.DEBUG)

app = App( 
    token=os.environ.get("SLACK_BOT_TOKEN"),
    signing_secret=os.environ.get("SLACK_SIGNING_SECRET"),
    process_before_response=True
)
handler = SlackRequestHandler(app)

@app.event("app_mention")
def event_test(body, say, logger):
    logger.info(body)

@app.command("/test")
def test(body, client, logger):
    logger.info(body)
    convo_list = client.conversations_list()
    print(convo_list['channels'])

###CLOUDRUN
def opsbot_cloudrun(request: Request):
    """HTTP Cloud Function.
    Args:
        req (flask.Request): The request object.
        <https://flask.palletsprojects.com/en/2.2.x/api/#incoming-request-data>
    Returns:
        The response text, or any set of values that can be turned into a
        Response object using `make_response`
        <https://flask.palletsprojects.com/en/2.2.x/api/#flask.make_response>.
    """
    return handler.handle(request)

###LOCAL DEVELOPMENT
if __name__ == "__main__":
    app.start(port=int(os.environ.get("PORT", 3000)))

```

1. Deploy above code to a google cloud function
2. Try and set the events API Request URL as described above
3. Get an HTTP error

### Expected result:

The function responds with the challenge token.

### Actual result:

The URL responds with an HTTP error.

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by misscoded** [comment]
Hi @bmckerry! Sorry you've run into this issue. 

I haven't used Google Cloud Functions personally, but having a look at the [example](https://github.com/slackapi/bolt-python/blob/v1.15.2/examples/google_cloud_functions/simple_main.py#L76-L79) we've provided and conferring with the colleague that built it, I've been informed that **Google Cloud Functions don't support nested paths**. 

This means the Request URL should be just `https://us-central-1-{project_name}.cloudfunctions.net/{function_name}`, less the additional `/slack/events`.

Let us know if that solves the problem!
