### ISSUE TITLE
Running a function on app start?

### ISSUE THREAD

**Issue by IronicTrout** [slackapi/bolt-python#753]
I am making a slack app the makes polls. We're using redis to keep track of polls in progress so they persist through a restart of the app (server goes down, code is published, etc.). Because polls have an amount of time they are allowed to run for I want to close the polls that should have ended while the bot was down as well as re-add the currently running ones to threads to they can end at the appropriate time. Is there a way to run the given function when the app starts? I feel like this is super easy and I'm just making it more difficult than it is. Thanks!

#### The `slack_bolt` version

slack-bolt==1.15.1
slack-sdk==3.19.1

#### Python runtime version

Python 3.9.13

#### Steps to reproduce:

```python
def cleanup():
    
    if r.exists('polls'):
        
        polls = json.loads(r.get('polls'))
        for index, poll in enumerate(polls):
            
            timer = poll['timer']
            end_time = int(poll['timestamp']) + (int(timer) * 60)
            print(end_time)
            print(time.time())
            if end_time > time.time():
                endPoll(WebClient, index)
                polls.pop(index, None)
                r.set('polls', json.dumps(polls))
            else:
                add(WebClient, index, int(end_time - time.time()))
```

### Expected result:

Run the given function when the app starts

### Actual result:

Trying to bind it to app.start predictably throws an error as it overrides the function

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by WilliamBergamin** [comment]
Hi @IronicTrout thanks for writing in!

If I understand correctly you should be able to accomplish this between the `app` creation and calling `start()`, The `App` object has property `client` of type `WebClient` that can be used in your `cleanup()` function.

Here is an example of an `app.py` that illustrates this
```python
import os
import logging

from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler
from slack_sdk import WebClient

from listeners import register_listeners


# Initialization
app = App(token=os.environ.get("SLACK_BOT_TOKEN"))
logging.basicConfig(level=logging.DEBUG)

# Register Listeners
register_listeners(app)


def cleanup(client: WebClient):
    
    if r.exists('polls'):
        
        polls = json.loads(r.get('polls'))
        for index, poll in enumerate(polls):
            
            timer = poll['timer']
            end_time = int(poll['timestamp']) + (int(timer) * 60)
            print(end_time)
            print(time.time())
            if end_time > time.time():
                endPoll(client, index)
                polls.pop(index, None)
                r.set('polls', json.dumps(polls))
            else:
                add(client, index, int(end_time - time.time()))


# Start Bolt app
if __name__ == "__main__":
    cleanup(app.client)
    SocketModeHandler(app, os.environ.get("SLACK_APP_TOKEN")).start()
```

Let me know if this resolves your issue 🗺️

**Comment by IronicTrout** [comment]
Oh awesome, I think the problem I had was not putting the `cleanup()` call before `SocketModeHandler()`, which caused the function not to be called. Sorry if this is a silly question, but Is there a reason for that?

**Comment by WilliamBergamin** [comment]
When `.start()` is called the app sets up a connection with Slack and then actively listens for incoming requests. This "listening" keeps the main python process busy, it is similar to the [busy waiting concept](https://www.baeldung.com/cs/os-busy-waiting#what-is-busy-waiting) of operating systems.

[Multithreading](https://docs.python.org/3/library/threading.html) and [asynchronous processing](https://docs.python.org/3/library/asyncio.html) are options that can get around this concept, but I don't feel like your issue is a use case for these.

This is a good question, someone may stumble on this thread at some point and find it helpful 🥇

**Comment by IronicTrout** [comment]
Gotcha. That makes perfect sense. Thank you so much!
