### ISSUE TITLE
Question on how to run my AsyncApp app with Request URLs

### ISSUE THREAD

**Issue by ItzSylex** [slackapi/bolt-python#759]
Hi, 

I have followed the following [guide](https://slack.dev/bolt-python/tutorial/getting-started-http) to create the slack app and enable the necessary scopes to reproduce the example given in that guide, however I did not use ngrok as the guide suggested. I created my own endpoint to handle the POST request on my domain. 

I copied the example code provided [here](https://slack.dev/bolt-python/api-docs/slack_bolt/app/async_app.html) and also followed the examples on the readme and while the bot says its running, I get no response from the bot. I even tested using no tokens at all and the bot would say that its running when in reality it wouldn't make sense (or at least for me) since the correct tokens are not being passed.

I also attempted using the SocketModeHandler but not sure how to approach it (main reason why I was using the events through http) since its not async and therefore produces an error.

So I wanted to know if there are any getting started or quick-start guides on using the AsyncApp module. Or if you could point me into a right path to get it running.
#### The `slack_bolt` version

`slack-bolt==1.15.2`

#### Python runtime version

Python 3.11.0

#### OS info

```
ProductName:	macOS
ProductVersion:	12.6
BuildVersion:	21G115
Darwin Kernel Version 21.6.0
```

##### app.py

```py
from slack_bolt.async_app import AsyncApp
import config


app = AsyncApp(
    token = config.token,
    signing_secret= config.secret
)

@app.event("app_mention")
async def handle_mentions(event, client, say):
    await say("What's up?")

if __name__ == "__main__":
    app.start(3000)
```

##### console

```
┌ sylex TestingBot 
└ $ python3 app.py
⚡️ Bolt app is running!
======== Running on http://0.0.0.0:3000 ========
(Press CTRL+C to quit)
```

### Expected result:

Response after mentioning
<img width="599" alt="image" src="https://user-images.githubusercontent.com/42503343/200203060-3183041f-a911-4bbd-93d3-d24c94106a28.png">

### Actual result:

Nothing in chat or in console. Also not getting unhandled requests on the console.

### Disclaimer

Sorry I had to open an issue for this, I wasn't able to find much information online for this specific situation.

**Comment by ItzSylex** [comment]
Hi, 

Thanks for replying!

I have made sure that the app is subscribed to the `app_mention` event and that the app is in the channel.

I am a bit confused regarding the endpoint. I understand that everytime theres an event the bot is subscribed to an HTTP POST request will be sent to the given endpoint. Now, when doing the initial handshake, I had to return the `challenge` parameter to verify my url. Would I need to handle the actual event POST request in some way? Or as long as I return a HTTP 200 it should work?

I am getting the correct event on the url as I can see it on my web server console logs
![image](https://user-images.githubusercontent.com/42503343/200226914-7695491b-c32d-46fd-9988-630e3f181842.png)

But the bot is still not responding on the slack app. 

I tried using the AsyncSocketModeHandler and got it working. 

But I am curious as why its not working with this other method.

**Comment by seratch** [comment]
> Now, when doing the initial handshake, I had to return the challenge parameter to verify my url. Would I need to handle the actual event POST request in some way? Or as long as I return a HTTP 200 it should work?

As long as your public endpoint is live, bolt-python framework handles the url_verification request (meaning challenge param response when you set the Request URL) under the hood. Also, after that, your public endpoint can receive subscribed event data in the same URL. I am not sure why your app didn't reply with the HTTP endpoint mode but it usually works without any issues.

Anyways, I am glad to hear that your app works witch Socket Mode so far. If everything is okay so far, would you mind closing this issue?
