### ISSUE TITLE
Filter messages with attachments

### ISSUE THREAD

**Issue by chr-b** [slackapi/bolt-python#760]
I have to process channel messages that use the old attachments structure, see example below. 
I noticed that the `app.message(...)` filter does not seem to work with those though - I never get a hit for any message where the text I am looking for is in the attachment. I do get a hit for messages where the actual message is in the `text` field though.

I guess I could always use `app.event()` with `"type": "message"` to receive all messages and then filter myself for those that I am interested in.

Is there a built-in way to do this? What is the best way to listen and filter for messages where the text payload I am looking for is only available in an attachment block?

### Reproducible in:

Example message:
```
{
    'type': 'message', 
    'subtype': 'bot_message', 
    'text': '', 
    'ts': '1667706749.962369', 
    'username': 'another-bot', 
    'bot_id': 'XYZ', 
    'attachments': [{
      'id': 1, 
      'color': 'a30200', 
      'fallback': 'message ....', 
      'text': 'message ...', 
      'title': 'Title of this message, 
      'mrkdwn_in': ['pretext', 'text']
    }], 
    'channel': 'channel_id', 
    'event_ts': '1667706749.962369', 
    'channel_type': 'group'
  }
```

#### The `slack_bolt` version

`1.15.1`

#### Python runtime version

`3.9.2`

#### OS info

`#1 SMP Debian 5.10.149-2 (2022-10-21)`

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @chr-b, thanks for asking the question!

In this case, you can use lister matchers to more easily filter events. Please refer to https://slack.dev/bolt-python/concepts#listener-middleware for more details. I hope this was helpful to you!

**Comment by chr-b** [comment]
Ok, thanks.  

I still have to implement this myself, but the middleware will at least make it simpler to do so.
