### ISSUE TITLE
Add documentation related to how to handle `view_closed` events

### ISSUE THREAD

**Issue by filmaj** [slackapi/bolt-python#762]
While there are docs for handling `view_submission` events (https://slack.dev/bolt-python/concepts#view_submissions), there are none for handling `view_closed` events.

In order to handle those events in your Bolt python app, two things need to be done:

- Add a `notify_on_close` property to your view payload when creating a view (see https://github.com/slackapi/bolt-python/issues/624)
- Use the `@app.view_closed('modal-callback-id')` decorator to define a view_closed handler

So we should document that! Can compare to the bolt-js docs for how bolt documents handling the view_closed event (bottom of https://slack.dev/bolt-js/concepts#view-submissions)

**Comment by seratch** [comment]
Fixed by #792
