### ISSUE TITLE
Lazily instantiation of `AsyncApp` and `App` objects

### ISSUE THREAD

**Issue by kevgliss** [slackapi/bolt-python#773]
Hi, I have a use case where I'd like to instantiate the `App` object lazily. Right now, it's assumed that the object is fully initialized before being decorated.  For my use case, the slack app configuration is saved in a database and will need to be set up on application start (instead of at import time).

I tried to view all of the examples including the sqlalchemy examples but they assume that all configuration information is available at import time:

https://github.com/slackapi/bolt-python/blob/main/examples/sqlalchemy/async_oauth_app.py#L174

**Comment by seratch** [comment]
Hi @kevgliss, thanks for asking this question!

The approach that we suggest for your use cause is to define a method to initialize an `App`/`AsyncApp` instance with given arguments:

```python
from slack_bolt import App

def initialize_bolt_app(args) -> App:
    app = App(signing_secret=args["signing_secret"])
    
    @app.event("app_mention")
    def handle_app_mentions():
        pass
    
    return app
```

I'm not sure if this approach works for you, but I hope this was helpful to you!

**Comment by kevgliss** [comment]
This seems a bit awkward we we may have functionality in multiple modules (that all import/register with the same app instance). 

Poking around a bit, it seems that the only hard requirement for token data on initialization is required here:
https://github.com/slackapi/bolt-python/blob/main/slack_bolt/app/app.py#L352

We don't use Oauth for our particular use case, so having a flag that disables that check out unlock this use case for us.

**Comment by seratch** [comment]
@kevgliss If you want to eliminate the auth.test API call during the initialization, you can pass `token_verification_enabled: False` in App constructor to stop it.

**Comment by kevgliss** [comment]
It looks like AsyncApp doesn't support that flag? 
https://github.com/slackapi/bolt-python/blob/ace3cb842257bcdb3cd0d3894c4db6bf46af952a/tests/scenario_tests_async/test_app_dispatch.py#L60

**Comment by seratch** [comment]
@kevgliss Since Python language does not allow calling async/await in a constructor, AsyncApp does not do the same. Thus, you don't need to worry about it if you go with AsyncApp. Is everything clear now?

**Comment by kevgliss** [comment]
Yes, this seems to work as expected thanks.
