### ISSUE TITLE
Listening for message metadata

### ISSUE THREAD

**Issue by jimenezj8** [slackapi/bolt-python#774]
I'm hoping to take advantage of message metadata to trigger actions in my app. As an example, consider the following flow:

1. Application schedules a message for the following day
2. Message is posted the following day with metadata
3. Listener picks up the message with metadata and performs an action

The reason for the scheduled message is because my application would be chaining together several of these flows, but is otherwise not important.

Using `slack_bolt==1.15.5` on Linux (Pop!_OS 22.04), I would expect that using
```python
@app.event("message_metadata_posted")
def handle_metadata_action(...):
    ...
```
would allow me to filter out messages with no metadata. However, it doesn't seem like that event is being handled at all. I've tried making my handler as simple as possible, such as below:
```python
@app.event("message_metadata_posted")
def handle_metadata_action(logger):
    logger.info("Metadata posted")
```
and the logs never reach this point.

My question is, does Bolt support this event type? From the documentation, it almost appears that the only application type that supports metadata in this way are applications defined through manifests, which I'm unfamiliar with.

**Comment by seratch** [comment]
Hi @jimenezj8, thanks for asking the question!

The reason why your event listener functions are not executed is that bolt-python automatically skips most self events to avoid infinite loop of listener code execution. What's the infinite loop? The most common pattern is to respond to a message posted by the app itself (post a message -> reply to the message -> reply ... reply). [A built-in middleware](https://github.com/slackapi/bolt-python/blob/v1.15.5/slack_bolt/middleware/ignoring_self_events/ignoring_self_events.py) prevents this situation from happening.

Probably, the message with metadata should be posted by your app's bot user itself, right? In this case, your bolt-python app receives the event but it does not invoke any app.event listeners. If you desire to change this behavior, you can pass [`ignoring_self_events_enabled: False` in the `App` constructor](https://github.com/slackapi/bolt-python/blob/v1.15.5/slack_bolt/app/app.py#L110). As mentioned above, your code is responsible to avoid infinite loops if you disable the built-in middleware.

Alternatively, you can create a different app that send scheduled message with metadata. In this case, your current app is just a subscriber of the metadata message events, so you don't need to disable IgnoringSelfEvents middleware. Also, this can be a cleaner app design if the message metadata can be subscribed by several apps and workflows.

I hope this was helpful to you. If everything is clear now, would you mind closing this issue?

**Comment by jimenezj8** [comment]
@seratch that was very helpful info, thank you! I had a suspicion that could be the case but I'm glad to confirm. And thank you very much for such a quick response, have a great week!
