### ISSUE TITLE
Multiple Listener Dispatching

### ISSUE THREAD

**Issue by kevgliss** [slackapi/bolt-python#786]
I'm curious if there is any guidance around running multiple functions against the same event. I have a use case that checks each message for a variety of conditions; the conditions don't depend on the text of the message itself, so passing patterns don't really help here. 

Is the expectation that we have one listener and create our own function dispatcher? Or is there a better way to maybe create a custom Listener? 

As an example:

```
@app.event({"type": "message")
def tag_message():
     # finds and associates tags with the current channel
     
@app.event({"type": "message"})
def activity_monitor():
     # increments activity of the user sending the message

....

```

In this example, the second function is never called.

**Comment by WilliamBergamin** [comment]
Hi @kevgliss thanks for asking the question!

For this use case, where multiple events are triggered from the same message match, I would recommend setting up one listener and create your own dispatcher.

This should provide more liberty to match on 3rd party sources and manage the processes that resolve the event. For example the `message` event could match and put an item in a [synchronized queue](https://docs.python.org/3/library/queue.html) or [multiprocessing queue](https://docs.python.org/3/library/multiprocessing.html#pipes-and-queues) that gets picked up and resolved by a process listening to this queue. Implementing a basic version of a job queue pattern.

Let me know if this resolves your issue

**Comment by kevgliss** [comment]
It does answer my question. IMO it would be nice if that API supported denoting that an event could be sent to multiple listeners, as the ability to decorate each function individually is a nice pattern. But I understand that may be outside the scope of this library.

**Comment by WilliamBergamin** [comment]
@kevgliss I created a feature request to see if this is something that should be expected of Bolt, and see if others would use bolt this way, thanks for bringing it up 💯
