### ISSUE TITLE
Slack Bolt for Python not acknowledging fast enough

### ISSUE THREAD

**Issue by GeekyAndDangerous** [slackapi/bolt-python#787]
Hey all, long time listener, first time caller. I am working through developing a slack bot using slack bolt and AWS Lambda. I am attempting to implement slash commands and have used the 'lazy listener' method. My problem is that the acknowledgement isn't being sent back to Slack fast enough to avoid the 'operation timeout'. I have given the Lambda the invoke permissions.

### Reproducible in:

```
app = App(
    process_before_response=True,
    token= os.getenv('BOT_TOKEN'),
    signing_secret=os.getenv('SIGNING_SECRET')
    )

command = "/test-prompt"


def respond_to_slack_within_3_seconds(body, ack):
    ack()


def process_request(say, body, command):
    # time.sleep(5)
    question = command['text']
    text = ai_response(question)
    
    person = app.client.users_info(
    user = command['user_id']
    )
    # respond(f'*{person["user"]["profile"]["real_name"]}* asks "*_{question}_*"')
    # say(command['text'])
    say(f'{text}______________________________________________________')


app.command(command)(ack=respond_to_slack_within_3_seconds, lazy=[process_request])
```

#### Python runtime version

3.9

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))
As above code.
1.
2.
3.

### Expected result:

I would expect that the ack would be sent faster (when I remove the processing of the external http request found in the ai_response() method, the ack gets through quickly enough)

### Actual result:

It seems to be processing all of the request still before sending the ack. 

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by filmaj** [comment]
Hi @GeekyAndDangerous,

Have you taken a look at the [AWS Lambda example](https://github.com/slackapi/bolt-python/blob/main/examples/aws_lambda/aws_lambda.py)? One thing that's unclear to me in your example is where is the Lambda entrypoint? Typically there is a `handler` exported/available in your Lambda function code (just like in the AWS Lambda example we have in the bolt-python repository](https://github.com/slackapi/bolt-python/blob/main/examples/aws_lambda/aws_lambda.py#L25)).

I am able to deploy the above example to Lambda and have it respond without issue.

**Comment by kevinfaganworkday** [comment]
I'm experiencing the exact same issue. Running both the [standard](https://github.com/slackapi/bolt-python/blob/main/examples/aws_lambda/aws_lambda.py) and [lazy](https://github.com/slackapi/bolt-python/blob/main/examples/aws_lambda/lazy_aws_lambda.py) sample apps, I receive the same response. i..e 

```python
import logging

from slack_bolt import App
from slack_bolt.adapter.aws_lambda import SlackRequestHandler

# process_before_response must be True when running on FaaS
app = App(
    token="xoxb-....",
    signing_secret="....",
    process_before_response=True,
)


@app.event("app_mention")
def handle_app_mentions(body, say, logger):
    logger.info(body)
    say("What's up?")


@app.command("/foo")
def respond_to_slack_within_3_seconds(ack):
    ack()


SlackRequestHandler.clear_all_log_handlers()
logging.basicConfig(format="%(asctime)s %(message)s", level=logging.DEBUG)


def lambda_handler(event, context):
    slack_handler = SlackRequestHandler(app=app)
    return slack_handler.handle(event, context)

```



```
/foo failed with the error "operation_timeout"
```

One thing I had noticed from the lambda logs is that the command function returns a 200 so the `ack()` seems to be working however it has its content type is set to `text/plain;charset=utf-8` which doesn't seem right?

**Comment by filmaj** [comment]
One thing I notice in both of your code is that the entry point / handler into your code is called `lambda_handler` - this is different from the example provided in the repo (the example uses `handler`, which is an AWS Lambda default for all languages). If you are using the `config.yaml` in the example to set up your Lambda, then make sure this function name matches the `handler` property in the config file; see [here in the example](https://github.com/slackapi/bolt-python/blob/main/examples/aws_lambda/aws_lambda_config.yaml#L4).

You can also double check this configuration directly on AWS Console by opening up the AWS Lambda instance in your Console, flipping to the Code tab, scroll down to Runtime settings and see what value you have under Handler. Here is a screenshot of that on my own personal AWS account for a working bolt-python Lambda function:
<img width="653" alt="Screenshot 2022-12-14 at 08 30 57" src="https://user-images.githubusercontent.com/52645/207609248-6b93bb4d-57f4-4257-90d4-e7ed8a46c2ae.png">

Please take a look at the [AWS Lambda documentation on what this value refers to in the context of a Python function](https://docs.aws.amazon.com/lambda/latest/dg/python-handler.html). The term before the `.` is the file name, and the term after the `.` is the function or method name.

**Comment by kevinfaganworkday** [comment]
Thanks @filmaj, I appreciate you taking a look. I made sure to check this and the entry point maps correctly to my cloud formation template

```
Resources:
  SlashCommandFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: slash_command/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        SlashCommand:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /slash_command
            Method: post
```


I'm almost 100% this isn't the issue. I can see the request being routed to my entry point and the `ack()` command does result in a response to slack however it seems slack doesn't like what it receives.


This is the response from my lambda function which shows it exiting correctly and returning a 200 response:

```
Mounting /Users/kevin/Development/python/repo_config/.aws-sam/build/SlashCommandFunction as /var/task:ro,delegated inside runtime container
START RequestId: 0fc183ad-e8c6-4ffc-b8ed-59b086ab2458 Version: $LATEST
lambda_handler
respond_to_slack_within_3_seconds
END RequestId: 0fc183ad-e8c6-4ffc-b8ed-59b086ab2458
REPORT RequestId: 0fc183ad-e8c6-4ffc-b8ed-59b086ab2458	Init Duration: 0.99 ms	Duration: 2787.85 ms	Billed Duration: 2788 ms	Memory Size: 128 MB	Max Memory Used: 128 MB	
2022-12-14 13:47:56 127.0.0.1 - - [14/Dec/2022 13:47:56] "POST /slash_command HTTP/1.1" 200 -
```

And this is what ends up going over the wire to slack

```
==================== REQUEST ====================
Received at: 2022-12-14T13:47:53Z
Request ID: 31470e77-28df-4447-9b25-99fd64a694d9
URI: /slash_command
Method: POST
Headers: 
  - [X-Forwarded-Port] = 443
  - [X-Forwarded-Proto] = https
  - [X-Slack-Request-Timestamp] = 1671025673
  - [Accept] = application/json,*/*
  - [Accept-Encoding] = gzip,deflate
  - [Content-Length] = 491
  - [Via] = 1.1 b467a4a34e9f37bba6d2f0aba8257b5e.cloudfront.net (CloudFront)
  - [Content-Type] = application/x-www-form-urlencoded
  - [User-Agent] = Slackbot 1.0 (+https://api.slack.com/robots)
Body: 
token=....(omitted for security)
==================== RESPONSE ====================
Responded at: 2022-12-14T13:47:56Z
Request ID: 31470e77-28df-4447-9b25-99fd64a694d9
Status: 200
Headers: 
  - [Server] = Werkzeug/2.0.3 Python/3.8.16
  - [Date] = Wed, 14 Dec 2022 13:47:56 GMT
  - [Content-Type] = text/plain;charset=utf-8
  - [Content-Length] = 0
Body: [EMPTY]
```

**Comment by filmaj** [comment]
While the specific content of the response does matter to respond in different ways, at the most basic of levels, any HTTP 200 response is considered acceptable for Slack (see our [docs on the subject here](https://api.slack.com/interactivity/slash-commands#responding_basic_receipt)).

@kevinfaganworkday are the following logs you posted from the relevant handlers?

```
lambda_handler
respond_to_slack_within_3_seconds
```

I.e. the first one is something being logged out from the `lambda_handler` method, the second one from the `respond_to_slack` method, etc.? Or is that coming from the debug logging configuration?

Another thing I noticed: the timing is awfully close / right at the 3 second timeout:

```
==================== REQUEST ====================
Received at: 2022-12-14T13:47:53Z
...
==================== RESPONSE ====================
Responded at: 2022-12-14T13:47:56Z
```

Exactly three seconds. Add to that any transit time from AWS to Slack, maybe we are legitimately hitting the timeout?

Last thing I noticed: the Lambda seems to be hitting its memory limit. Looks like your Lambda has 128MB assigned to it, and based on the AWS Lambda logs, all 128MB are being consumed:

```
Duration: 2787.85 ms	Billed Duration: 2788 ms	Memory Size: 128 MB	Max Memory Used: 128 MB
```

Are you able to bump up the memory allocation at all? I wonder if some kind of memory thrashing as the RAM is completely used up is happening, slowing down the response?

Here is me running the AWS Lazy Lambda example on my account, and the relevant details, and the example works as expected:

```
Duration:
297.93 ms Billed Duration: 298 ms Memory Size: 512 MB Max Memory Used:
70 MB Init Duration: 539.78 ms
```

**Comment by kevinfaganworkday** [comment]
Thanks @filmaj. So after debugging some more on this end I'm pretty sure this is an issue on my side.
Originally I was testing locally with ngrok setup to route the slack response to my localhost. I've since deployed the changes to aws and tested there and it's working without issue. 

I'm not entirely sure why a local setup wouldn't work but I suspect there's some networking issues at play somewhere through the stack.

Apologies for the red herring and I really appreciate you taking some time out to help me debug.
