### ISSUE TITLE
Configuring Bolt for slash commands

### ISSUE THREAD

**Issue by rhacer63** [slackapi/bolt-python#788]
I am using the default Bolt configuration (other than the port is 5151) I have the app setup to interact with https://mysite.com:5151/slack/events.

My app correctly handles @app.messages()

but when setting up a slash command /my-slash-command

```
@app.command("/my-slash-command")
def my_slash_command(ack, say):
    ack()
    say("my-slash-command shortcut")
```

I get 

```
10.3.3.231 - - [14/Dec/2022 10:45:33] "POST /911_snooze HTTP/1.1" 404 -
```

I start the app this way.
```
if __name__ == "__main__":
    app.start(port=5151)
```

#### The `slack_bolt` version
slack-bolt         │ 1.16.0 

#### Python runtime version
Python 3.9.16

#### OS info
CentOS Linux release 7.9.2009 (Core)
#1 SMP Wed Feb 23 16:47:03 UTC 2022

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1. Start the App listening on the default path "/slack/events"
2. use the slash command /my-slash-command

### Expected result:
a message in the channel saying "my-slash-command shortcut"

### Actual result:
 a 404
 ```
10.3.3.231 - - [14/Dec/2022 10:45:33] "POST /911_snooze HTTP/1.1" 404 -
```

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by rhacer63** [comment]
I'm going to answer my own question as a coworker and I have resolved this issue. The issue is not with my code but the way the "/" command is configured within Slack. I had set the command to have it's very own endpoint "https://myserver.com:5151/slack/events/my-slash-command".

THAT is incorrect. Slack should be setup to use the generic "https://myserver.com:5151/slack/events" endpoint.

**Comment by srajiang** [comment]
Hey @rhacer63, really appreciate you posting a followup with the solution you found. For others who have a similar issue, when you configure a slash command Request URL to work with Bolt, the base url with `/slack/events` appended is all that is needed.

You do not need to also include your slash command name at the end. Docs [here](https://slack.dev/bolt-js/concepts#commands)

I'll close this out now!

**Comment by rhacer63** [comment]
@srajiang I think the docs are very unclear on this. I have looked at this many times over the last couple of days and this could mean many different things:
![image](https://user-images.githubusercontent.com/27306556/207951573-84456d58-c80f-4120-ad9d-3740196f5258.png)

**Comment by rhacer63** [comment]
Perhaps something like 
When configuring commands within your app configuration, and if you are using the default settings, you only need to append "/slack/events" to the URL. No matter what you're configuration the Slash Command does not need to be included.
