### ISSUE TITLE
Is there an async handler for Flask?

### ISSUE THREAD

**Issue by jjasperting** [slackapi/bolt-python#800]
Hello,

Apologies if the answer to this is obvious; I'm still learning the ropes. I built a Slack app using the async version of Bolt and only realized that there is no async handler for Flask after deploying to Heroku. Why is this? And should I attempt to write an async handler or would it make more sense to switch to another framework? I see that Django doesn't have one either. Any guidance is very much appreciated! Thanks for making the dev experience great.

**Comment by seratch** [comment]
Hi @jjasperting, thanks for asking the question!

The biggest reason we don't provide asyncio compatible adapters for Flask and Django is that these frameworks do not support asyncio in a great way. More specifically, they internally use thread-local variables a lot (e.g., request for Flask, many parts on Django ORM), and thread locals do not work in an asyncio event loop as expected. See also: https://github.com/slackapi/bolt-python/issues/368

If you're already done with the AsyncApp coding and you're not planning to switch back to ordinary Python coding (meaning no async/await), you can use any of built-in ASGI, Falcon, FastAPI, Sanic, Starlette, and Tornado: https://github.com/slackapi/bolt-python/tree/main/tests/adapter_tests_async All these frameworks are great but if you need some recommendations, I would suggest either the built-in ASGI or FastAPI.

I hope this helps.

**Comment by jjasperting** [comment]
Thank you so much for your guidance!
