### ISSUE TITLE
Problem with adding custom routes to slack_bolt.async_app.AsyncApp

### ISSUE THREAD

**Issue by arvitus** [slackapi/bolt-python#801]
When using the `AsyncApp.start()` method, routes added via `app.web_app().add_routes(route)` return a `404: Not Found`.
But when using `aiohttp.web.run_app(app.web_app())` instead and add routes like above the routes work properly.
In both cases the routes seem to be registered properly but in the first example all routes except the one passed to `app.start()` return a `404: Not Found` when trying to access it route via a web browser or e.g. Postman.
It doesn't make any sense to me and I'm very confused why it's not working. Please help :)

#### The `slack_bolt` version

slack-bolt==1.16.0
slack-sdk==3.19.5

#### Python runtime version

Python 3.11.1

#### OS info

Microsoft Windows [Version 10.0.19044.1889]

#### Steps to reproduce:

a.py
```py
import os

import dotenv
from aiohttp import web
from slack_bolt.async_app import AsyncApp


async def callback(request):
    return web.Response(text="callback")


def main():
    app = AsyncApp()

    app.web_app().add_routes([web.get("/callback", callback)])
    
    app.start(25573)


if __name__ == "__main__":
    os.chdir(os.path.dirname(__file__))
    dotenv.load_dotenv()
    main()
``` 
`ngrok http 25573`

b.py
```py
import os

import dotenv
from aiohttp import web
from slack_bolt.async_app import AsyncApp


async def callback(request):
    return web.Response(text="callback")


def main():
    app = AsyncApp()

    app.web_app().add_routes([web.get("/callback", callback)])
    
    web.run_app(app.web_app(), port=25573)


if __name__ == "__main__":
    os.chdir(os.path.dirname(__file__))
    dotenv.load_dotenv()
    main()
``` 
`ngrok http 25573`

### Expected result:

When executing `a.py` or `b.py` and going to `https://a85b-....eu.ngrok.io/callback` (in any browser) it should show this: 
![grafik](https://user-images.githubusercontent.com/34866314/211683697-0f9f3b59-59a5-439d-9415-18d346e52ff4.png)

### Actual result:

When executing `a.py` and going to `https://a85b-....eu.ngrok.io/callback` (in any browser) it shows this: 
![grafik](https://user-images.githubusercontent.com/34866314/211683788-eed2e7b5-0851-4532-9fa6-98c6f4f2ae6b.png)
When executing `b.py` and going to `https://a85b-....eu.ngrok.io/callback` (in any browser) it shows this: 
![grafik](https://user-images.githubusercontent.com/34866314/211683697-0f9f3b59-59a5-439d-9415-18d346e52ff4.png)

**Comment by seratch** [comment]
Hi @arvitus, thanks for asking the question!

I do understand that `app.start()`'s behavior could be confusing, but we are unable to change it for backward compatibility and aihttp's server initialization process. The following code is the right way to add additional routes to your aiohttp web server:

```python
app = AsyncApp()
server = app.server(port=25573)
server.web_app().add_routes([web.get("/callback", callback)])
server.start()
```

I hope this was helpful to you.

**Comment by arvitus** [comment]
Oh wow that was fast, thank you very much, it works!
