### ISSUE TITLE
Make `aiohttp` an optional dependency

### ISSUE THREAD

**Issue by steve-marmalade** [slackapi/bolt-python#802]
Currently, `AsyncApp` requires `aiohttp` to be installed, since it is imported [here](https://github.com/slackapi/bolt-python/blob/main/slack_bolt/app/async_app.py#L7).

However, the [docs imply](https://github.com/slackapi/bolt-python#creating-an-async-app) that while `aiohttp` is used as the default server, others can be used via the adapters. Given that I am using this library in a `starlette` app, am I correct to say that `aiohttp` is not necessary for my use-case? If so, it would be great to have the option to install (and use) `bolt-python` without it.

Thanks!

### Category (place an `x` in each of the `[ ]`)

* [ ] **slack_bolt.App** and/or its core components
* [x] **slack_bolt.async_app.AsyncApp** and/or its core components
* [ ] Adapters in **slack_bolt.adapter**
* [ ] Others

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @steve-marmalade, thanks for writing in! 

Indeed, you can go with any asyncio compatible web framework to serve the apps' endpoints to receive requests from Slack. 

However, your app still needs aiohttp's HTTP client module for Slack API calls. The aiohttp project offers both web server and HTTP client features. bolt-python's `AsyncWebClient` depends on aiohttp: https://slack.dev/python-slack-sdk/web/index.html#asyncwebclient 

You may be curious about the future plans of enhancement. Unfortunately, we are not planning to add a different HTTP client that does not rely on aiohttp at least in the short term.

Does this make sense to you? If everything is clear now, would you mind closing this issue?

**Comment by seratch** [comment]
I've provided an answer to this question, so let me close this issue now. But please feel free to write in whenever you have further questions on this topic. Thanks again for asking the question!
