### ISSUE TITLE
Is it still not possible to use the `app` for multiple files?

### ISSUE THREAD

**Issue by 0417taehyun** [slackapi/bolt-python#803]
I want to manage the `app` object globally just like the `APIRouter` does in FastAPI.
I saw that there was a discussion before( #320 ) and is it still not possible to use the `app` object globally?

I currently use `register` method to connect the event handlers as a function.

Thanks.

**Comment by seratch** [comment]
Hi @0417taehyun, thanks for asking this question!

As you guessed, there is no update on the #320 issue. Our latest recommendation is to organize your app like this template does: https://github.com/slack-samples/bolt-python-starter-template

I hope this helps.

**Comment by 0417taehyun** [comment]
@seratch It is really helpful to me! Thanks. I would close this issue.
