### ISSUE TITLE
How to get the content of a view from a previous modal?

### ISSUE THREAD

**Issue by BSouzaDock** [slackapi/bolt-python#804]
I'm developing a global shortcut where I list some users with the button on each user. After clicking this button, another modal is opened with client.views_push to select an option.
After sending, I want it to go back to the previous modal, but with the button that was clicked now in another style, for example "Chossed".
It turns out that I have the id of that previous modal and I pass it via private_metada for later updating, but I can't access the view of the previous modal, where I need to update only the clicked button. I didn't find any method that brings the content of the view passing the id. 
What would be the best way to do this?

**Comment by BSouzaDock** [comment]
Hello @hello-ashleyintech , thanks for the reply.

The problem is precisely when I call `view_update`. Because I need to inform the view parameter and I no longer have access to the first view. During view_update I only have access to the last view, which is a user selector.
The process I want is as follows:
List users > Select a user (button) > Open a modal where I choose a value coming from a userform > Go back to the start view with this user marked as ✓ Processed

**Comment by hello-ashleyintech** [comment]
@BSouzaDock ahh, I see. In that case, would it work for you to just skip the `view_update` and call `views_push` when the optional-specific modal is submitted? In the `views_push`, you can pass in that `trigger_id` and then a new Block Kit payload that is exactly like the first view, just with the selected user marked. This will not push that initial view updated, but rather a new view that just looks very similar with whatever changes you'd like to make to it.

Let me know if you have further questions!

**Comment by BSouzaDock** [comment]
I'll show you the flow for you to understand:

1. This is the first screen after activating the global shortcut:
![image](https://user-images.githubusercontent.com/96547309/213312005-469145db-d279-4700-a33f-1ad4ed7533cb.png)

2. After selecting the owner, all pending requests on his behalf are listed:
![image](https://user-images.githubusercontent.com/96547309/213312151-67934ce0-bb84-440d-a253-dd67ce523dc3.png)

3. When clicking on change owner, a new modal is opened to change the owner of that request:
![image](https://user-images.githubusercontent.com/96547309/213312201-a92f2841-2654-4ba4-abd2-2d8fa18bb572.png)

4. After sending the last modal, I would like to go back to listing modal with that item marked as processed, for example:
![image](https://user-images.githubusercontent.com/96547309/213313012-3ebf2583-238d-4182-b88a-57d9aba64ad2.png)

It happens that after choosing a new owner in the last modal, what I get is the body of that modal, and I no longer have access to the listing payload, so I lose the reference to which option was processed.
I can access the id of the modal listing to update because I pass it via private_metadata between the modals, but the body of the modal with the listing I cannot pass via private metadata because it has a limit of 3000 characters.

**Comment by hello-ashleyintech** [comment]
Hi, @BSouzaDock! Thanks for providing that information!

With the descriptions and flow you've provided, it seems like the main issues here are 1) Keeping track of the current owner whose info is being surfaced in the listing view, as well as 2) Keeping track of the Block Kit payload for the listing view modal, populated with that owner's information.

Based on my understanding for this, I have a general idea for an approach you could follow:
* `private_metadata`: To preserve information of the current owner's ID as well as the ID(s) of their request(s) that have been assigned to a new owner within that modal session, you could pass these into `private_metadata` along with the ID of the listing modal.
* `Block Kit payloads`: You can break out your Block Kit payloads for each view into separate JSON variables, the important one here being one for your listing view. For views that are dynamically populated, such as that one, you can iterate through this JSON and add in elements (ex: a specific user's assigned requests) as needed before passing it into a `views_open`, `views_update`, or any other function that requires a Block Kit view being passed in.
* When you are looking to call `views_update` to surface the listing modal again, updated with the completed requests, you can fall back on the default listing modal JSON variable, and again dynamically populate the information with the currently selected user (using the ID pulled from `private_metadata`). You can also check, as you populate each request in the JSON, to see if the request IDs match ones that are being stored in `private_metadata` as being assigned to a new owner. If it does, you can surface a button with a "Completed" label.

However, as you mentioned, using `private_metadata` has a limitation with its 3000 character limit, so for long-term use, I recommend using some sort of database column to keep track of "completed" tasks for each user. This way, it can be queried along with the rest of the user's information and surface Block Kit items appropriately without having to use the `private_metadata`.

I hope this helps!

**Comment by BSouzaDock** [comment]
@hello-ashleyintech , Thanks for the answer.

As for storing the JSON payload in other variables, I don't know how that would be possible. Because each iteration of the user generates a new request, so he does not have access to the variables of the previous requests. I'm running this application on an aws lambda.

Unless you save the json body in a database as you mentioned.

**Comment by hello-ashleyintech** [comment]
@BSouzaDock that's a great point! In that case, you could either save the JSON body in a database as you mentioned, or keep those Block Kit payloads in JSON files that you load in wherever you need to access that specific payload.

Please let me know if you have further questions, I would be happy to help. If not, feel free to close out this issue!

**Comment by BSouzaDock** [comment]
Thanks. Another question came up but I'm going to create another topic.
