### ISSUE TITLE
Is it possible to get guest users' token by OAuth flow?

### ISSUE THREAD

**Issue by 0417taehyun** [slackapi/bolt-python#807]
The legacy document [Sign in with Slack](https://api.slack.com/legacy/sign-in-with-slack#prereqs) told that it is not possible to authorize the guest members.

However, there are no guideline for guest members in the new document, [Obtaining access tokens with OAuth 2.0](https://api.slack.com/authentication/oauth-v2#obtaining).

Is it still impossible to use OAuth with guest members?

**Comment by hello-ashleyintech** [comment]
Hi, @0417taehyun1! Thanks for writing in! Before I answer your question, based on the links you provided, I wanted to verify if you were trying to implement the [V2 OAuth 2.0 installation flow](https://api.slack.com/authentication/oauth-v2) or the [new Sign in with Slack flow](https://api.slack.com/authentication/sign-in-with-slack).

Sign in with Slack allows a way for users to grant their Slack profile info for their service, while OAuth installation allows for a user in any Slack workspace install your app - at the end of OAuth, your app gains an access token.

Let me know which one you're trying to implement and I can dig into whether guest users are able to authorize for that specific flow!

**Comment by 0417taehyun** [comment]
Hi, @hello-ashleyintech !

I would like to authorize guest users with OAuth flow to gain an access token because I want to update their messages with my bot on behalf of them. However, when I try to install with OAuth or sign in with Slack by a guest account, I got an error like the image on below.

<img width="520" alt="스크린샷 2023-01-27 11 57 26" src="https://user-images.githubusercontent.com/63915557/215000658-53b27504-a7c8-4e43-8c5e-6136315eb013.png">

Are there any ways to authorize guest members with installing App with OAuth flow to gain their access tokens?
Thanks!

**Comment by seratch** [comment]
Hi @0417taehyun, unfortunately guest users are unable to install any apps (in other words, they cannot go through a 3rd party OAuth flow for Slack). Refer to [this help page](https://slack.com/help/articles/202518103-Understand-guest-roles-in-Slack#permissions-for-guests) to learn the permissions a guest user has.

**Comment by 0417taehyun** [comment]
Thanks for the information, @seratch ! I understand the permissions of a guest user.

How about the OpenID, Sign in Slack flow? There are no limitations about it on the list that you referred. However, I also got same error messages like the one above when I try to sign in Slack with guest accounts.

**Comment by seratch** [comment]
@0417taehyun Since SIWS (OpenID Connect) is also an OAuth flow, the same restriction should be applied.

**Comment by 0417taehyun** [comment]
Thanks @seratch !

Well, I was confused because the [Legacy document](https://api.slack.com/legacy/sign-in-with-slack#exceptions) told that there are some exceptions with guest users. However, the [latest one](https://api.slack.com/authentication/sign-in-with-slack) does not tell anything about it. Thus, I assumed that I can use OAuth or OpenID flows by guest users too.

Are there any reasons that Slack removed the sentence about the exceptions? If it is okay to suggest, I want to tell you that it would be better to add the information again.

BTW, thanks again! I close this issue.
