### ISSUE TITLE
FileExistsError: [Errno 17] File exists when trying the AWS Lambda example app deployment

### ISSUE THREAD

**Issue by asontha** [slackapi/bolt-python#812]
Trying to deploy a LazyListener Slack Bolt App.
Added `lazy_aws_lambda_config.yaml` and `./deploy_lazy.sh` to the root directory of the project.

Set up the app.js file to use the `SlackRequestHandler`

But I'm running into this error when I run `./deploy_lazy.sh`

```
FileExistsError: [Errno 17] File exists: '/var/folders/_7/9xfhtzcs2xx5ppbvjddsk6y00000gn/T/aws-lambdawt5utq2l/slack_bolt'
```

**Comment by seratch** [comment]
Hi @asontha, thanks for trying the example out! The example script works only when you run it under `examples/aws_lambda` in this repo. See https://github.com/slackapi/bolt-python/blob/v1.16.1/examples/aws_lambda/deploy_lazy.sh#L2 to learn what the script does. Thus, if you want to re-use it in your project, please modify the shell script and some other things accordingly. Also, the script uses the latest code in this repo, but if you want to install the latest package from the PyPI registry, `pip install slack-bolt` works without any issues.

I hope this helps.

**Comment by seratch** [comment]
I've provided an answer to this question and it seems that you are no longer using AWS Lambda. Let me close this issue now. Thanks again for asking the question!
