### ISSUE TITLE
Have to reinstall on new deployment

### ISSUE THREAD

**Issue by asontha** [slackapi/bolt-python#815]
Just integrated OAuth into my bot as I'm planning on pushing it to distribution, however, every time I deploy it, I get this error:

<img width="436" alt="image" src="https://user-images.githubusercontent.com/67022327/215928552-122a7d81-a975-4366-95d4-33f8a559f8b9.png">

### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version

slack-bolt==1.16.1
slack-sdk==3.19.5

#### Python runtime version

Python 3.10.9

#### OS info

ProductName:    macOS
ProductVersion: 12.5
BuildVersion:   21G72
Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000

### Expected result:

Deploying updates does not force me to have to reinstall the app in a workspace

### Actual result:

<img width="436" alt="image" src="https://user-images.githubusercontent.com/67022327/215928552-122a7d81-a975-4366-95d4-33f8a559f8b9.png">

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by asontha** [comment]
Added context: Once I reinstall, the app works fine up until I make a new deployment.

**Comment by seratch** [comment]
Hi @asontha, thanks for asking the question. As long as you use a production-grade database for storing installation data, your situation does not arise. The default installation store is a file based one for local development. Perhaps, your app still uses it when being deployed. Am I right? If yes, you can switch to the S3 based one or whatever available here: https://github.com/slackapi/python-slack-sdk/tree/main/slack_sdk/oauth/installation_store It's fine to write your own one too.

**Comment by asontha** [comment]
Ohhhhh I see! Is there an example on how to use `AmazonS3InstallationStore`?

**Comment by seratch** [comment]
If you're running your app on AWS Lambda, using [this](https://github.com/slackapi/bolt-python/blob/v1.16.1/examples/aws_lambda/aws_lambda_oauth.py#L10) is the easiest way. If you're looking for a way to pass installation_store only, you can follow [this document](https://slack.dev/bolt-python/concepts#authenticating-oauth).

**Comment by asontha** [comment]
Got it. I'm not using AWS Lambda due to the constraints around local development and having to maintain a separate code path. I'd highly recommend checking out fly.io!

**Comment by seratch** [comment]
Thanks for sharing flyctl (I didn't know it!) I believe that I've answered your question here. Can we close this issue now?

**Comment by asontha** [comment]
Yes! But one last quick question. Do I have to use the botocore BaseClient for S3? Or can I just pipe in my own AWS.S3() client?
