### ISSUE TITLE
Is there way to send the same request to another endpoint (socket-mode)?

### ISSUE THREAD

**Issue by sammiee5311** [slackapi/bolt-python#816]
### Reproducible in:

```python
import os

from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler

app = App(token=os.environ["SLACK_BOT_TOKEN"])

@app.action("AcknowledgeGroupStep")
def handle_some_action(ack, body, req, action, payload, event, request, context, response, client, logger):
    print(request.headers)
    print(req.headers)
    ack()
    # Try to use request.post("grafana oncall endpoint", headers=request.headers, data=request.body)
    logger.info(body)

    
@app.middleware
def log_request_headers(logger, request, next):
    print(request.headers)
    next()


if __name__ == "__main__":
    handler = SocketModeHandler(app, "token")
    handler.start()
```

This is my code snip and try to get the `HTTP_X_SLACK_SIGNATURE`, `HTTP_X_SLACK_REQUEST_TIMESTAMP` and `HTTP_X_SLACK_RETRY_NUM`, however, I could not get any headers from request, req.

I am trying to use [Grafana Oncall](https://github.com/grafana/oncall) with socket mode so that the url does not to be public but Grafana Oncall does not support socket mode.. So I am trying to send same request to [grafana oncall endpoint](https://github.com/grafana/oncall/blob/dev/engine/apps/slack/views.py#L104).

1. Is there any way to send a same request to another endpoint from bolt ?
2. If not, Is there any way to get `HTTP_X_SLACK_SIGNATURE`, `HTTP_X_SLACK_REQUEST_TIMESTAMP` and `HTTP_X_SLACK_RETRY_NUM` headers ?

Thanks in advance !

#### The `slack_bolt` version

slack-bolt==1.16.1
slack-sdk==3.19.5

#### Python runtime version

python 3.7

#### OS info
SUSE

### Expected result:

Get all headers

### Actual result:
{}
{}
{}

The headers were empty dictionaries.

**Comment by WilliamBergamin** [comment]
Hi @sammiee5311 thanks for asking this question 💯 

I would not recommend duplicating a request to your app and sending it to another app, the Slack API will treat both requests as the same, this can lead to unexpected behavior and race conditions between the applications.

For example `trigger_ids` are used to create interactive components, they can only be used once and expire after some time. If your app and the third party try to use the same instance of this object one of them will get an error.

For this graphana project it seems like they implemented their own libraries to interact with the slackAPI, I would suggest following [their documentation](https://grafana.com/docs/oncall/latest/integrations/chatops-integrations/configure-slack/) to set up a separate application from the one you are working on. This will allow slack to create a request to your app and another to the graphana app preventing unexpected behaviors.

Hope this helps you on your journey 🗺️

**Comment by sammiee5311** [comment]
Hello, @WilliamBergamin, Thanks for the answer !!

However, I don't want to expose my endpoint publicly (= using http request) since `grafana-oncall` slack app does not support `socket mode`.

I guess, I need to request a feature to `grafana-oncall` or add some codes into `grafana-oncall` project.

Thanks again !!

**Comment by seratch** [comment]
Hi @sammiee5311, thanks again for writing in! It seems that grafana/oncall project already has a feature request ticket here: https://github.com/grafana/oncall/issues/628 I also hope the project will support Socket Mode too in the near future!

Let me close this issue on our side now.
