### ISSUE TITLE
Is it possible to catch a workflow message?

### ISSUE THREAD

**Issue by jcastro-sfdc** [slackapi/bolt-python#817]
(Describe your issue and goal here)

Is it possible to catch a workflow message?  when a user clicks submit on a workflow and the channels posts results is the subtype 'bot_message'?

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by e-zim** [comment]
Hey @jcastro-sfdc! 👋  Messages from a workflow **do** contain the `bot_message` subtype and can be listened for by an app.

As a quick plug for a handy tool, [Slack Developer Tools](https://sdt.builtbyslack.com/) can be used to inspect the raw JSON of a message which shows this, as well as the blocks used in constructing a message and some other handy information. Hope this helps!
