### ISSUE TITLE
Scopes required to allow DM-ing bot directly

### ISSUE THREAD

**Issue by asontha** [slackapi/bolt-python#818]
Hello! Got a feature request that users would like to DM the bot directly instead of asking in channels.

<img width="969" alt="image" src="https://user-images.githubusercontent.com/67022327/216746049-0f6e4c82-b95f-4bff-b74e-3eb665dc79ff.png">

Here are the scopes I have set. Thought adding `im:read` and `im:write` would work but it did not. I did reinstall the app after adding the scopes.
![image](https://user-images.githubusercontent.com/67022327/216746104-19caf94b-9b47-40e2-a2f3-e809a0ae7c0a.png)

**Comment by seratch** [comment]
Hi @asontha, visit Features > App Home page in your https://api.slack.com/apps admin page, and then scroll down to find the following section. When you turn Message Tab on, your end-users can start DM with your app's bot user.

<img width="500" src="https://user-images.githubusercontent.com/19658/216748420-4ff6064d-30ad-44c4-8688-fcf415016d91.png">

Also, to receive DM message events, you need to add [`im:history`](https://api.slack.com/scopes/im:history) scope to your app instead.

**Comment by asontha** [comment]
Got it! Do we also need to keep the `im:write` and `im:read` permissions?

So is this what the end state should look like? 
- Messages Tab: True
- `im:write`
- `im:read`
- `im:history`

**Comment by seratch** [comment]
@asontha It depends on what operations your app does. Having all of them works in any case, but if your app doesn't start a DM conversation until an end-user sends a DM to your app's bot user, the `im:write` scope is not necessary.  Similarly, if all the things that your app does are to receive DM messages sent by an end-user and to send replies to the messages, all the required scopes are `im:history` and `chat:write`. This means that `im:read` is not necessary for this scenario.

For future reference, you can check what web APIs require a scope by checking **Compatible API methods** and **Compatible events** in the scope documents:
* https://api.slack.com/scopes/im:write
* https://api.slack.com/scopes/im:read

Is everything clear now?

**Comment by asontha** [comment]
Yes, thank you!
