### ISSUE TITLE
Python Slack bolt API  - Spitting out all DEBUG log message into logfile by default 

### ISSUE THREAD

**Issue by jambesh** [slackapi/bolt-python#819]
How Do I stop/change the python Slack bolt API default DEBUG  logging  ? Currently I have not log any thing for slack but the moment i am using my own logger, it is spitting out the Slack HTTP response in my log file it is very noisy and there is no way to stop the slack DEBUG log  ?

**Comment by WilliamBergamin** [comment]
Hello @jambesh thanks for writing in!

I have not experienced this on my end yet, bolt python uses the [standard logging module](https://docs.python.org/3/library/logging.html) to do its logging.

You should be able to change the log level by adding these lines in your app
```python
import logging

logging.basicConfig(level=logging.INFO)
```

If this does not help, would you be able to share with me some of your source code so I can better understand how your app is configured?
