### ISSUE TITLE
[Help] No signature/body?

### ISSUE THREAD

**Issue by adam-mrozik** [slackapi/bolt-python#823]
Hey!

Not really sure if it is the place, as it doesn't seem strictly API related, but couldn't find a better spot to look for help.

I have succesfully implemented webhooks with custom buttons for my app. These buttons, on-click, contain URLs to my application. However, the POST messages I receive for them do not contain any of the headers/body that is needed for authentication.
```python
def validate_slack_identity():

    def wrapper(f):
        @wraps(f)
        def wrapped(*args, **kwargs):
            signature = request.headers.get("X-Slack-Signature")
            timestamp = request.headers.get("X-Slack-Request-Timestamp")
            body = request.get_data().decode("utf-8")
            raise ValueError(signature, timestamp, body)
            return f(*args, **kwargs)

        return wrapped

    return wrapper


@my_routes.route("/slack-button/<id>", methods=["POST", "GET"])
@validate_slack_identity()
def my_endpoint(id: strr):
    ...


...
    raise ValueError(signature, timestamp, body)
ValueError: (None, None, '')
```

Do you know what could be the reason? I thought it is enabled by default for any incoming slack request?

**Comment by seratch** [comment]
Hi @adam-mrozik, thanks for asking the question!

It seems that you're trying to implement a Slack app server with Flask framework, right? If yes, 

> However, the POST messages I receive for them do not contain any of the headers/body that is needed for authentication.

this sounds like something specific to your Flask app. I haven't checked how `@validate_slack_identity` works yet, but the Slack-specific request signature header always exists for sure.

We highly recommend using bolt-python along with the built-in Flask adapter instead. The framework does the validation for you under the hood. Also, there is no problem even when you're trying to add Slack app functionalities to an existing Flask app. `App` instance is fully framework-agnostic. Please check https://github.com/slackapi/bolt-python/tree/main/examples/flask to learn how to use the adapter.

I hope this helps!
