### ISSUE TITLE
Question about how to call external APIs after ack() in an app.view listener

### ISSUE THREAD

**Issue by nir750** [slackapi/bolt-python#824]
Hi,

I developed a slack bot to communicate with "atlassian - status page" 

I can see the "view_submition" output in debug.
but, i need the submition to "post" to the "status page" API
i follow the documentation and try to handle this after the "ack()"
but didnt find a way to make it work.
thanks,

In the documentation it asks to be done this way:

```python
# Handle a view_submission request
@app.view("view_1")
def handle_submission(ack, body, client, view, logger):
    # Assume there's an input block with `input_c` as the block_id and `dreamy_input`
    hopes_and_dreams = view["state"]["values"]["input_c"]["dreamy_input"]
    user = body["user"]["id"]
    # Validate the inputs
    errors = {}
    if hopes_and_dreams is not None and len(hopes_and_dreams) <= 5:
        errors["input_c"] = "The value must be longer than 5 characters"
    if len(errors) > 0:
        ack(response_action="errors", errors=errors)
        return
    # Acknowledge the view_submission request and close the modal
    ack()
    # Do whatever you want with the input data - here we're saving it to a DB
    # then sending the user a verification of their submission

    # Message to send user
    msg = ""
    try:
        # Save to DB
        msg = f"Your submission of {hopes_and_dreams} was successful"
    except Exception as e:
        # Handle error
        msg = "There was an error with your submission"

    # Message the user
    try:
        client.chat_postMessage(channel=user, text=msg)
    except e:
        logger.exception(f"Failed to post a message {e}")
```

**Comment by misscoded** [comment]
Hi @nir750! Happy to help 🙂  

Can you provide a snippet of the actual code (less the credentials) that you're trying to run? That would help us in figuring out where things are possibly going wrong.

**Comment by nir750** [comment]
Hi @misscoded ,
basically i tried few ways. non of them works,
but even if i tried to insert "print" in after the ack() it didn't showed in the log info:
this is the code part:
`   # Acknowledge the view_submission request and close the modal
    ack()
    # Do whatever you want with the input data 
    # then sending the user a verification of their submission
    print("*********** inside view-get submition **********")
    result = client.chat_postMessage(
    channel="<my slack channel>",
    text="test"
    )

    # Message to send user`

and this is the log output:
`INFO:app.py:view_submission:{'es_c': {'es_c': {'type': 'external_select', 'selected_option': {'text': {'type': 'plain_text', 'text': 'mte staging', 'emoji': True}, 'value': 'mte staging'}}}, 'es_b': {'es_a': {'type': 'external_select', 'selected_option': {'text': {'type': 'plain_text', 'text': 'Monitoring', 'emoji': True}, 'value': 'Monitoring'}}}}
DEBUG:slack_bolt.App:Responding with status: 200 body: "" (12 millis)`

hope thats help.
10x

**Comment by seratch** [comment]
@nir750 To better understand your situation, we need a full working code that reproduces your situation. If you can share such, we can try to reproduce it. With currently given information, we are unable to guess the cause of your issue.

With that being said, common pitfalls can be:
* The **Requset URL** in Interactivity & Shortcuts section in your app admin page (= https://api.slack.com/apps) is not valid; In this case, the whole app.view listener may not be invoked as you expect.
* If you use Socket Mode instead, some outdated WS connections may be receiving the requests; To resolve this situation, you need to revoke existing app-level tokens and then start a brand-new connection with a new app-level token
* If you're running your app on FaaS such as AWS Lambda, process_before_response=True is necessary to run your listeners in a stable matter; Refer to https://slack.dev/bolt-python/concepts#lazy-listeners for more details

If none of the above suggestions is the case, as I said above, please share the complete app code including the way you initialize bolt-python app with us. With that, we may be able to suggest further. I hope this was helpful to you.

**Comment by nir750** [comment]
thanks you both @seratch , @misscoded ,
i managed to call API using python (without slack-bolt).
but, i need to pull values from the functions: "view_submission" or "handle_submission", in order to use them in my code.
i cant figure it out how can i do this.
as you can see at the output of the submission here:
``
'selected_option': {'text': {'type': 'plain_text', 'text': 'Monitoring', 'emoji': True}, 'value': 'Monitoring'}}}}
``
i the user "select" the option "Monitoring"
and i want to use this value in my "GET" request.
i don't know if i need to preform this inside the function "view_submission" or "handle_submission".
here is my code:
``
@app.view("view-get")
def view_submission(ack, body, view, logger):
    ack()
    logger.info(body["view"]["state"]["values"])
#     get_unresolved_incidents(pageid, apikey)
#     print(get_unresolved_incidents(pageid, apikey))

# Handle a view_submission request
@app.view("view-get")
def handle_submission(ack, body):
    # Assume there's an input block with `es_c` as the block_id and `es_b`
    # logger.info(body["view"]["state"]["values"])
    state = body["text"]["values"]
    print(state)
    ack()
``
you can see that i tried to pull the value inside "handle_submission" function.
with:
``
state = body["text"]["values"]
    print(state)
    ack()
``
without success, 
can you please advice how can i pull value from "view_submission" function or some other solution ? 
10x
