### ISSUE TITLE
Difference between message_ts and trigger_id?

### ISSUE THREAD

**Issue by asontha** [slackapi/bolt-python#826]
Hey! Trying to persist some actions to messages and I want to tie it back to the message. Is it advised to rely on message_ts or trigger_id to identify the message? They both seem to be unique ids but I was a bit worried as message_ts also seems to be some form of timestamp. Is it possible to have two different messages with the same message_ts globally throughout Slack?

**Comment by seratch** [comment]
Hi @asontha, `trigger_id` is associated with an end-user's interactions with your app. For instance, slash command invocations, button clicks and so on can generate `trigger_id`, which allows your app to open a modal with the user. So, it's not available for your use case. To identify a channel/DM message in a specific workspace, you can use a pair of channel ID and message ts. 

I hope this helps. If everything is clear, would you mind closing this issue?

**Comment by asontha** [comment]
Ahhh I see! So in actuality, we're tying reactions back to slash command invocations and message shortcuts, so I think it will make sense to use trigger_id.
