### ISSUE TITLE
Is sequential processing possible?

### ISSUE THREAD

**Issue by Chlorine628** [slackapi/bolt-python#828]
Sometimes, a  new @app.message event comes while the former @app.message process is still running.
I would like to start the new @app.message event after the former @app.message ends.
 
Is there a way to do that?

**Comment by seratch** [comment]
Hi @Chlorine628, thanks for asking the question!

bolt-python itself does not provide such functionality, but if you have a queue / database to manage the events and their order, your app should be able to process events in a sequential order.

Perhaps, your bolt-python app code can be something like this:

```python
@app.message
def receive_message_events(message):
     # your code does not make any side effects here
     enqueue_message(message)
```

and then, offline processor parts in your app can dequeue the message from queue/datastore. This part is not a bolt-python event listener. The code should be complete independent from bolt-python framework while you can utilize foundational components such as `WebClient`.

```python
while True:
    message = dequeue_message()
    do_something_here()
```

I hope this helps.

**Comment by Chlorine628** [comment]
Thanks. I'll try it
