### ISSUE TITLE
Commands Request URL

### ISSUE THREAD

**Issue by Smyja** [slackapi/bolt-python#832]
In the Django example folder, i noticed that there's no views file and no request url in `urls.py` for the commands in `slack_listeners.py` file. Using the commands won't work without specifying a url(I am not using sockets). from what i can see, there's actually no way to use the example command in a `views.py` file.

**Comment by Smyja** [comment]
I think i've figured how to use it, i'll create a pr for it.

**Comment by seratch** [comment]
Hi @Smyja, thanks for asking the question! You can use `/slack/events` endpoint for all slash commands too. So, all you need to do is to set the `/slack/events` URL when creating a slash command.

I hope this helps! I believe that everything should be clear on this, so let me close this issue now.
