### ISSUE TITLE
Getting error 'value field must be less than 151 characters' when using 'static_select'

### ISSUE THREAD

**Issue by AravindPeriasamy** [slackapi/bolt-python#838]
(Describe your issue and goal here)
Im trying to using 'static_select' in my slack bot, when doing so i get an error response saying 'value field must be less than 151 characters'. Is there any other way to increase the max length of the value field or is there any other workaround for this?

#### The `slack_bolt` version

```bash
slack-bolt==1.9.1
slack-sdk==3.11.1
```

#### Python runtime version

Python 3.9.12

#### OS info

ProductName:            macOS
ProductVersion:         13.1
BuildVersion:           22C65

#### Steps to reproduce:

```python
# slack block
blocks = [{
    "block_id": f"plan_select#{user_id}",
                    "type": "section",
                    "text": {"type": "mrkdwn", "text": "Select a payload"},
    "accessory": {
                    "type": "static_select",
                    "placeholder": {
                        "type": "plain_text",
                        "text": "Select payload",
                        "emoji": True,
                    },
                    "options" :[{
                          "text": { "type": "plain_text", "text":"label", "emoji": True },
                          "value":json.dumps(
                                        {
                                            "client_id": client_id,
                                            "email_id": email_id,
                                            "selected_payload": payload_id,
                                            "selected_period": period.strftime("%d/%m/%Y"),
                                        },
                                    ),
                      }],
                    "action_id": "view_by_components",
                },
    }]
result = client.chat_postMessage(
        channel=user_id,
        text="Payload",
        blocks=blocks,
    )
```

### Expected result:

The expected result is to show the selector with the mentioned options

### Actual result:
Im getting a error response as follows

```bash
{'ok': False, 'error': 'invalid_blocks', 'errors': ['must be less than 151 characters [json-pointer:/blocks/1/accessory/options/0/value]'], 'response_metadata': {'messages': ['[ERROR] must be less than 151 characters [json-pointer:/blocks/1/accessory/options/0/value]']}}
```
## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by hello-ashleyintech** [comment]
Hi, @AravindPeriasamy! Thanks for submitting your question!

As far as I know, there is no way to bypass that `value` character limit. However, is there any way to minimize the amount of data you're passing in to the `value` to make it shorter? Maybe try to pass in only one or two pieces of information to that `value` field that can be used to query the other info. For example, if `selected_payload` is a unique identifier and it is the only value being passed in, maybe the `client_id`, `email_id`, and so on can be retrieved by querying your data using that payload ID.

If the above does not work, I recommend revisiting our [Block Kit documentation](https://api.slack.com/reference/block-kit/block-elements) to try to find an element that better suits this use case.
