### ISSUE TITLE
How to get the time stamp of my block post to delete the message once the button is clicked.

### ISSUE THREAD

**Issue by EricStehnach** [slackapi/bolt-python#839]
python 3.11
slack bolt 1.16.2

This is probably a simple question which is why I could not find the answer but How would I use slack bolt sdk to delete an "approval" block that my bot posts. I am able to post the block and the result does return the time stamp. But how do I then pass that specific time stamp into my listener function?

````
def yes_or_no(ack, client):
    """
    Simple function to respond if a user performs an action. Using "app mention" for testing
    """
    ack()
    result = client.chat_postMessage(
        blocks=slackpayload2,
        channel="channel_id",
        text="Please approve the attached information"
    )
    return result


result = app.event("app_mention")(yes_or_no)



@app.action("Approved")
def handle_approval(ack, body, logger, client, context):
    ack()
    logger.info(body)
    client.chat_postMessage(
        channel="channel_id",
        text="Approved!"
    )
    client.chat_delete(
        channel=context["channel_id"],
        ts=???,
    )
````

I looked into being able to pass an additional argument into my handle_approval() function but it seems like that would be overcomplicating the issue. I am probably just missing something but could not find any documentation on how to accomplish this.
(Note if I manually print(result['ts'] and use that as my timestamp in chat_delete this does work. I just need to figure out how to programmatically get it in there.

**Comment by seratch** [comment]
Hi @EricStehnach, thanks for asking the question! I can get the message ts by accessing `body["message"]["ts"]`. Your code is trying to post a new message and delete the existing one, but you can use [chat.update API](https://api.slack.com/methods/chat.update) instead.

I hope this helps.

**Comment by EricStehnach** [comment]
@seratch Thank you so much. I know it seems weird that I am deleting and not updating but that is on purpose. Thank you for the explanation on body. In my first attempt I was using the info on the "payload" and that is clearly where I went wrong. Your suggestion worked perfectly. This can be closed out.

Thanks again!
