### ISSUE TITLE
Getting repeated slack events request in case of failure 

### ISSUE THREAD

**Issue by mohan-raheja** [slackapi/bolt-python#845]
I'm using slack events in my app

@app.event("team_join")
and @app.event("user_change")

to detect any new users added to the team or any updateds for the user

In case of failure in handling the events due to some issues in our internal logic, I'm getting repeated events request from slack, want to know how to avoid these in case of failure in handling the event.

### Reproducible in:

slack-bolt==1.9.1
slack-sdk==3.11.1

**Comment by srajiang** [comment]
Hi @mohan-raheja - Slack Events API will retry (with exponential backoff) all requests that go unacknowledged from your app up to 3 times. There is a way to provide a header to turn off retries, see here: https://api.slack.com/apis/connections/events-api#retries-off. 

Let me see whether Bolt Python provides a way to set that header when you set up the app.

**Comment by srajiang** [comment]
Hey @mohan-raheja - You can register an `app.error` callback, a [global error handler](https://slack.dev/bolt-python/concepts#errors). Errors of type BoltError and others error types (from your app) will cause this middleware to run, and there you may set the BoltResponse status and headers yourself. Here's an [example](https://github.com/slackapi/bolt-python/pull/290)

You can try using this to set `X-Slack-No-Retries` header to turn retries off, for instance. `https://api.slack.com/apis/connections/events-api#retries-off`

Hope that helps!

**Comment by mohan-raheja** [comment]
Thank you, it helped.
