### ISSUE TITLE
Event chain support for the same event?

### ISSUE THREAD

**Issue by chunyang-wen** [slackapi/bolt-python#847]
I just wonder if we can register multiple functions on the same event. And there is some chain logic. for example
> Event -> fn1 -> fn2

The chain will stop if any of the function in the chain accepts the event.

```python
@app.event("app_mention")
def fn1(event):
    ...

@app.event("app_mention")
def fn2(event)
   ...
```

**Comment by seratch** [comment]
Hi @chunyang-wen, thanks for writing in! 

Unfortuantely, bolt-python does not support multiple listeners for the same event / constraints. If you would like to have multiple functions to run for a single event, please consider having internal functions and call them in a listener. If it's fine to run those concurrently, using lazy listeners for those would be an option too. [The document](https://slack.dev/bolt-python/concepts#lazy-listeners) says it's mainly for FaaS use cases but it's available for non-FaaS apps too.

**Comment by chunyang-wen** [comment]
it seems that middleware can help. There is a next function call or we can use the matcher parameter

**Comment by seratch** [comment]
Yeah, a giant global middleware can work for your use case. The built-in middleware for custom workflow steps actually works in such a way: https://github.com/slackapi/bolt-python/blob/main/slack_bolt/workflows/step/step_middleware.py

Do you have anything else to discuss on this topic? If not, would you mind closing this issue?
