### ISSUE TITLE
Can I Use Django instead of Flask to build my bot fully

### ISSUE THREAD

**Issue by suavelad** [slackapi/bolt-python#849]
Can I Use Django instead of Flask to build my bot fully?

**Comment by seratch** [comment]
Hi  @suavelad, thanks for asking the question. Yes, you can! Take a look at the Django example app: https://github.com/slackapi/bolt-python/tree/main/examples/django

**Comment by suavelad** [comment]
Hi Kazuhiro,

Thank you. I later saw this.
But I recently started having an authentication issue 400 error

Also How can I implement the home tab feature

AJAYI Sunday
(+234) 806 771 5394
***@***.*** ***@***.***>*

**Comment by seratch** [comment]
Perhaps, some of the app settings can be wrong. Please double-check the app settings and make sure if you're running the example app as-is.
