### ISSUE TITLE
Update slack_sdk version to fix file_upload_v2

### ISSUE THREAD

**Issue by garymalaysia** [slackapi/bolt-python#850]
Hi Slack API team,

I am experiencing a bug where `file_upload_v2` is not uploading files to Slack when using `slack_bolt` version `1.16.1`. This bug was confirmed by the release of [slack_sdk 3.20.1](https://github.com/slackapi/python-slack-sdk/releases/tag/v3.20.1)

However, I see the latest version on `1.16.3` of `slack_bolt` is not using the latest of `slack_sdk` `3.20.1`
https://github.com/slackapi/bolt-python/blob/57cb04394db44d8572d110d7058c5e101d25208d/setup.py#L61

### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version
slack-bolt==1.16.1

#### Python runtime version

Python 3.10.8

#### OS info

ProductName:	macOS
ProductVersion:	12.6.3
BuildVersion:	21G419
Darwin Kernel Version 21.6.0: Mon Dec 19 20:43:09 PST 2022; root:xnu-8020.240.18~2/RELEASE_ARM64_T6000

### Expected result:

File to upload to slack and show in slack client

### Actual result:
No response from Slack Client

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @garymalaysia, thanks for taking the time to report this. We will change the version range since the next verison. Until then, please explicitly add the slack-sdk dependency in your `requirements.txt` or anything equivalent that you use.
