### ISSUE TITLE
Which slack event should I use to get a request when a member is removed from a workspace

### ISSUE THREAD

**Issue by mohan-raheja** [slackapi/bolt-python#860]
I want to update the slack user data when a member is removed from a workspace

slack-bolt==1.9.1
slack-sdk==3.11.1

**Comment by mohan-raheja** [comment]
Got it, have a question here does the user_change event calls the DjangoInstallationStore.save() method, I have implemented my installation logic inside the save() , because the events, save() is called which is causing the installation unexpectedly

**Comment by seratch** [comment]
@mohan-raheja 
> does the user_change event calls the DjangoInstallationStore.save() method

No, it doesn't. If you want to update some data in your database, you need to have your own event listener and call the save() method inside the function.

**Comment by mwbrooks** [comment]
@mohan-raheja I'm going to close this issue since there's an answer for listening to an user removed event. Feel free to continue to leave comments!
