### ISSUE TITLE
Slack View/Modal updates work, but Slack warning arises

### ISSUE THREAD

**Issue by 0x108** [slackapi/bolt-python#866]
Greetings everyone,

I am having problems with updating a Modal in Slack. While the code successfully updates the Modal content as intended, Slack keeps displaying a warning "We had some trouble connecting. Try again?", even though I immediately answer with an `Ack(response_action="update")`.

I have read several posts/issues regarding this, and was yet not able to find the root cause of the problem.

### Reproducible in:

**The slack_bolt version**
1.16.3

**Python runtime version**
3.11.2

**OS info**
ProductName: macOS
ProductVersion: 13.0.1
BuildVersion: 22A400
Darwin Kernel Version 22.1.0: Sun Oct 9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000

**Steps to reproduce:**
1. Receive View callback
2. Evaluate View callback ID, if callback id action requires view update, answer with `ack(response_action="update"`
3. Update the View using the `client.views_update` method

Code used to update the view:
```python
await ctx.client.views_update(
                view_id=ctx.view_id,
                view=modals.create_modal(
                    ModalContext(
                        callback_id=ctx.callback_id,
                        external_id=ctx.external_id,
                        title=f"Title",
                        submit_text="Submit",
                    ),
                    blocks=card,
                ),
                external_id=answer_ctx.external_id,
            )
```
As required to update the View, I pass an external id to update the view and a view_id (passing view_id should've fixed the problem apparently).

**Expected result:**
The View should update, without displaying any error messages.

**Actual result:**
Slack successfully updates the View as intended, however every View contains a "We had some trouble connecting. Try again?" warning at the top of the modal

Thanks for helping out!

**Comment by seratch** [comment]
Hi @0x108, thanks for asking the question. 

>While the code successfully updates the Modal content as intended, Slack keeps displaying a warning "We had some trouble connecting. Try again?", even though I immediately answer with an Ack(response_action="update").

I am still unsure about the situation.

When you use `ack(response_action="update")`,
* your `app.view` listener must call `ack()` within 3 seconds
* Valid `view` parameter data must be passed along with `response_action="update"`

Please double-check if there is no part violating the above points.

Also, after updating the modal using `ack()` method (a common use case is to display "Loading ..." message on it), it's still possible to use `views.update` API for async updates of the modal view.

By the way, this may not be a cause of your issue but it seems that your views.update API call code sets both view_id and external_id. However, in this case, you can set only view_id.

If you need more helps on this, probably sharing a complete code that reproduces your situation would be helpful for others.
