### ISSUE TITLE
"auth.test API call result is unexpectedly None" error with OAuth-enabled Django app

### ISSUE THREAD

**Issue by mohan-raheja** [slackapi/bolt-python#870]
`ERROR - auth.test API call result is unexpectedly None
`
Getting this error repeatedly in slack bolt app
 This below is my app constructor
```python
app = App(
    signing_secret=signing_secret,
    process_before_response=True,
    oauth_settings=OAuthSettings(
        client_id=SLACK_CLIENT_ID,
        client_secret=SLACK_CLIENT_SECRET,
        install_page_rendering_enabled=False,
        # minutes_before_expiration (by default token expires every 12 hrs, so here for every req new token generated)
        token_rotation_expiration_minutes=1720,
        scopes=["commands", "chat:write", "users:read", "users:read.email"],
        installation_store=DjangoInstallationStore(
            client_id=SLACK_CLIENT_ID,
            logger=logger,
        ),
        state_store=DjangoOAuthStateStore(
            expiration_seconds=120,
            logger=logger,
        ),
    ),
)
```

slack-bolt==1.9.1
slack-sdk==3.11.1

**Comment by WilliamBergamin** [comment]
Hi @mohan-raheja thanks for writing in 💯 

It seems like you are taking from the [Django OAuth_app example](https://github.com/slackapi/bolt-python/tree/main/examples/django/oauth_app). From what I can gather the `auth.test API call result is unexpectedly None` error message can only come from the [single_team_authorization middleware](https://github.com/slackapi/bolt-python/blob/c15141e08efa64270cb587e641263743527ef88d/slack_bolt/middleware/authorization/single_team_authorization.py#L74) this seems to be a catch all error for unexpected behaviors, from what I understand this should only be raised if the result of [auth.test](https://api.slack.com/methods/auth.test) request is somehow `None`

Would you able to clarify why the `process_before_response=True` is set in your app, if your app is deployed on something like AWS Lambda I would suggest using the [aws_lambda SlackRequestHandler](https://github.com/slackapi/bolt-python/blob/main/examples/aws_lambda/aws_lambda_oauth.py#L4) to deploy your app

**Comment by mohan-raheja** [comment]
I get the error even after removing process_before_response=True in app constructor.

**Comment by mohan-raheja** [comment]
I see the error log in multiTeamsAuthorization code as well


My slack version

slack-bolt==1.9.1
slack-sdk==3.11.1

```
class MultiTeamsAuthorization(Authorization):
    authorize: Authorize

    def __init__(
        self,
        *,
        authorize: Authorize,
    ):
        """Multi-workspace authorization.

        Args:
            authorize: The function to authorize incoming requests from Slack.
        """
        self.authorize = authorize
        self.logger = get_bolt_logger(MultiTeamsAuthorization)

    def process(
        self,
        *,
        req: BoltRequest,
        resp: BoltResponse,
        next: Callable[[], BoltResponse],
    ) -> BoltResponse:
        if _is_no_auth_required(req):
            return next()

        if _is_no_auth_test_call_required(req):
            req.context.set_authorize_result(
                AuthorizeResult(
                    enterprise_id=req.context.enterprise_id,
                    team_id=req.context.team_id,
                    user_id=req.context.user_id,
                )
            )
            return next()

        try:
            auth_result: Optional[AuthorizeResult] = self.authorize(
                context=req.context,
                enterprise_id=req.context.enterprise_id,
                team_id=req.context.team_id,
                user_id=req.context.user_id,
            )
            if auth_result is not None:
                req.context.set_authorize_result(auth_result)
                token = auth_result.bot_token or auth_result.user_token
                req.context["token"] = token
                # As App#_init_context() generates a new WebClient for this request,
                # it's safe to modify this instance.
                req.context.client.token = token
                return next()
            else:
                # Just in case
                self.logger.error("auth.test API call result is unexpectedly None")
                return _build_error_response()

        except SlackApiError as e:
            self.logger.error(f"Failed to authorize with the given token ({e})")
            return _build_error_response()

```

**Comment by mohan-raheja** [comment]
Hi @seratch, I have installed the app using the slack/install URL, and I see the installation data in the table slack_installation for django.

**Comment by seratch** [comment]
@mohan-raheja hmm, with given information, I cannot guess anything further. By the way, it seems that you're using a very old version of bolt-python. Upgrading to the latest would be generally recommended while it may not resolve your issue here.
