### ISSUE TITLE
How do I pass variables into lazy functions?

### ISSUE THREAD

**Issue by gnohgnij** [slackapi/bolt-python#872]
I stored my API keys in AWS Secrets Manager. I have a function that gets all secrets in the main lambda function handler.

```
def get_secret():

    secret_name = "xxxx"
    region_name = "xxxx"

    # Create a Secrets Manager client
    session = boto3.session.Session()
    client = session.client(
        service_name='secretsmanager',
        region_name=region_name
    )

    try:
        get_secret_value_response = client.get_secret_value(
            SecretId=secret_name
        )
    except ClientError as e:
        # For a list of exceptions thrown, see
        # https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_GetSecretValue.html
        raise e

    # Decrypts secret using the associated KMS key.
    secret = get_secret_value_response['SecretString']

    return secret
```

I have view handling functions that require the use of these secrets. An example would be:
```
app.view("elevate_permission_view")(ack=elevate_permission.elevate_permission_ack, lazy=[elevate_permission.handle_elevate_permission_submission])

# handle_elevate_permission_submission is in another directory and requires API keys to execute
```

How to I pass the secret variable using the above code?

#### The `slack_bolt` version

slack-bolt         1.16.1

#### Python runtime version

Python3.9

#### OS info

macOS Ventura 13.2.1

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @gnohgnij, thanks for asking the question!

A recommended way to pass your custom variables to lazy listeners is to have a global middleware to set those to a request's context object. With that, your lazy listener can access them. Refer to https://slack.dev/bolt-python/concepts#global-middleware for details.

**Comment by gnohgnij** [comment]
Thanks, I'll check it out!
