### ISSUE TITLE
Slash Commands in threads

### ISSUE THREAD

**Issue by asontha** [slackapi/bolt-python#873]
Hello! Is it possible to have slash commands in threads? I have a few users asking for it.

**Comment by e-zim** [comment]
Hi @asontha! I know this might not be the answer you were hoping for, but slash commands [are not supported in threads](https://api.slack.com/interactivity/slash-commands#enabling-interactivity-with-slash-commands__what-are-slash-commands). Instead, you might consider using [app shortcuts](https://api.slack.com/interactivity/shortcuts), which can be invoked from either the shortcuts button or from the context menu of a message. I hope this can be a suitable workaround for you and your users!

**Comment by asontha** [comment]
Why are slash commands not supported in threads? Is it technically not feasible or is it just something that hasn't been prioritized?

**Comment by seratch** [comment]
@asontha It seems that there is not a single simple reason for that. Also, I am sorry to say this but I don't anticipate some changes on this to come. I hear you on the frustration on this but please consider alternatives like shortcuts or app_mention events for your use case.

Let use close this issue now.

**Comment by agrass** [comment]
There is an update on this? Some apps like Giphy allow use commands on threads, but I'm not sure how they do it, If I use my command on thread I got `"/command is not supported in threads. Sorry!"`. It's there a way to use commands on threads?
