### ISSUE TITLE
Python Bolt display errors in modal window for wrong data entered by user

### ISSUE THREAD

**Issue by zkokelj** [slackapi/bolt-python#878]
Hi,
I am working on an Slack app with Python Bolt framework and one of the things that app needs to do is to allow user to enter start and end date of an event. Everything works for me, except validation of entered data.
I want to check that the first date is before second date, both dates should be in the future and both dates should be selected, otherwise I would like to display an error message to the user.

### Reproducible in:

```python
@app.command("/add_event")
def handle_command(body, ack, respond, client, logger):
    ack()
    modal_view = {
        "type": "modal",
        "title": {"type": "plain_text", "text": "Select a Date"},
        "submit": {"type": "plain_text", "text": "Submit"},
        "close": {"type": "plain_text", "text": "Cancel"},
        "callback_id": "submit-modal",
        "blocks": [
            {
                "type": "section",
                "text": {"type": "mrkdwn", "text": "Select a date:"},
                "accessory": {
                    "type": "datepicker",
                    "initial_date": datetime.now().date().isoformat(),
                    "placeholder": {"type": "plain_text", "text": "Select a date"},
                    "action_id": "date",
                },
            }
        ],
    }
    client.views_open(
      trigger_id=body["trigger_id"],
      view=modal_view)
      

@app.action("submit-modal")
def handle_submission(ack, body):
    selected_date = body["view"]["state"]["values"]["date"]["datepicker"]["selected_date"]
    print(f"{selected_date}")
    if selected_date < datetime.now().date():
        response = {"response_action": "errors", "errors": {"date": "Please select a future date."}}
        ack(response)
    ack()
```

#### The `slack_bolt` version

slack-bolt==1.14.3
slack-sdk==3.18.3

#### Python runtime version

Python 3.8.10

#### OS info

~20.04.1-Ubuntu SMP Wed Jan 25 09:41:30 UTC 2023

#### Steps to reproduce:

Python code above

### Expected result:

I expected a way to be able to show users that the data they entered was not correct if the dates are wrong / in the past

### Actual result:

When I click submit on a modal it closes without any errors.

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by misscoded** [comment]
Hi @zkokelj! In your print statement, can you also include `datetime.now().date()`? What are both of those values when the comparison is hit?

**Comment by seratch** [comment]
In addition to Alissa's comment, let me suggest a few things:
* "input" type blocks are the way to receieve view.state.values properly and displaying error messages for a "section" type block in a modal is not supported. Thus, please use an "input"  type block instead.
* When migrating to an "input" type block, set its "block_id". The key "date" in `"errors": {"date": "Please select a future date."}` needs to be a block_id, not an action_id.
* nit: for the pattern of `ack()` with errors, you can do early return to avoid the following unnecesary code execution.
