### ISSUE TITLE
Best way to handle files?

### ISSUE THREAD

**Issue by lautaropacellaDR** [slackapi/bolt-python#884]
Hi!
I have a slack bot that will take files shared from a channel and I want it to upload these files to a bucket in a google cloud bucket, what is the most efficient way to do this? I see that I can access the content of the file or download it, but is there no direct way to send the file that has been shared to a bucket?
Thanks a lot for your time

**Comment by seratch** [comment]
Hi @lautaropacellaDR, thanks for asking the question! You can download the file content using its URL and then upload the data onto Google Cloud storage. Please refer to the following replies to learn how to download file contents:
* https://github.com/slackapi/bolt-python/issues/266#issuecomment-806197956
* https://github.com/slackapi/bolt-js/issues/1711#issuecomment-1382691560
