### ISSUE TITLE
slack app to trigger github actions

### ISSUE THREAD

**Issue by nir750** [slackapi/bolt-python#887]
hello,
is there a way to use slack-bolt in order to trigger github actions ?
i would like the user to get some kind of menu to choose from which github action to trigger.
thanks

**Comment by filmaj** [comment]
Hello,

You could build a UI using the various Slack UI components like modal views composed of interactive components. Using these two constructs, you should be able to build the UI that you describe.

Once the user has selected an option in the above UI, you could use the GitHub API to [trigger a workflow](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow). In particular, there is a [`repository_dispatch` event](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch) that you can trigger via the GitHub API.

Hope that helps! Good luck.
