### ISSUE TITLE
Oauth bug trying to get download in app directory

### ISSUE THREAD

**Issue by ryanrestivo** [slackapi/bolt-python#890]
(Filling out the following details about bugs will help us solve your issue sooner.)

So I have an app that is working with the /slack/install route when I have a flask app deployed, but when users install it for the OAuth Add to Slack button they get an eror page 

Oops, Something Went Wrong!
Please try again from [here]([LINK to]/slack/install) or contact the app owner (reason: invalid_browser: This can occur due to page reload, not beginning the OAuth flow from the valid starting URL, or the /slack/install URL not using https://)

but I have the proper code to set up the app 

```
## OAUTH functionality...

from slack_bolt import App
from slack_bolt.oauth.oauth_settings import OAuthSettings
from slack_sdk.oauth.installation_store import FileInstallationStore
from slack_sdk.oauth.state_store import FileOAuthStateStore
from slack_bolt.adapter.flask import SlackRequestHandler
from slack_sdk.oauth.installation_store.sqlalchemy import SQLAlchemyInstallationStore
from slack_sdk.oauth.state_store.sqlalchemy import SQLAlchemyOAuthStateStore

from slack_sdk.oauth.installation_store import InstallationStore


import sqlalchemy
from sqlalchemy.engine import Engine

database_url = os.environ["dbURL"]

logger = logging.getLogger(__name__)
client_id, client_secret, signing_secret = (
    os.environ["SLACK_CLIENT_ID"],
    os.environ["SLACK_CLIENT_SECRET"],
    os.environ["SLACK_SIGNING_SECRET"],
)

engine: Engine = sqlalchemy.create_engine(database_url)
installation_store = SQLAlchemyInstallationStore(
    client_id=client_id,
    engine=engine,
    logger=logger,
)
oauth_state_store = SQLAlchemyOAuthStateStore(
    expiration_seconds=120,
    engine=engine,
    logger=logger,
)

try:
    engine.execute("select count(*) from slack_bots")
except Exception as e:
    installation_store.metadata.create_all(engine)
    oauth_state_store.metadata.create_all(engine)

app = App(
    logger=logger,
    signing_secret=signing_secret,
    installation_store=installation_store,
    oauth_settings=OAuthSettings(
        client_id=client_id,
        client_secret=client_secret,
        state_store=oauth_state_store,
        scopes=["channels:join","channels:read","chat:write","chat:write.public","commands","im:read","im:write","mpim:write"],
        user_scopes=["chat:write"] 
    ),
)

app.enable_token_revocation_listeners()


### CORE FLASK APP ###
from flask import Flask, request, render_template, jsonify, abort

flask_app = Flask(__name__)
handler = SlackRequestHandler(app)
@flask_app.route("/slack/install", methods=["GET"])
def install():
    return handler.handle(request)


@flask_app.route("/slack/oauth_redirect", methods=["GET"])
def oauth_redirect():
    return handler.handle(request)
```

but every time they seemingly hit this oauth button they are getting 400 and have to go to the click here slack/install link which updates the state and works for them...

is there a way to use that button on the slack/install or because it always changes the state value, its impossible?

I have implemented what you all said in my previous issue https://github.com/slackapi/bolt-python/issues/782 but now looking at the logs I see 400 errors on that link so I know people will have to stpe through to install it, but I've seen others that havent had to do this step...

The slack app directory is saying that tehy cant seem to install it and I would like to get in there, so I dont know how to resolve. Can you please help? 

I am using 

```
slack-bolt==1.17.0
slack-sdk==3.20.2
```
and my app is a Flask app andI checked that it is on https, so I'm not sure the exact issue.

I'll add more but I used issue 782 to resolve what I needed to get it to install across multiple workspaces, but now the button seems to generate an error eery time I try to hit it...

**Comment by srajiang** [comment]
Hi @ryanrestivo! Can I check that for your app you have enabled App Distribution? Go to **Settings > Basic Information > Installing Your App** and select Install from App Directory - see attached screenshot and supply your full slack/install endpoint. 

![image](https://user-images.githubusercontent.com/55667998/234353187-805dccff-a5e6-4ac8-a00c-a26823911f71.png)

**Comment by ryanrestivo** [comment]
So when I add my link in there I see that Slack says 
> Your application’s redirect URL must return a status code of 302 to a slack.com url.

but that is my install endpoint. I could make a redirect to that page from there but i dont think that would work..

is this waht you meant?

In the logs I see 200 statuses coming through when that URL is being hit.


<img width="843" alt="Screen Shot 2023-04-26 at 12 02 01 PM" src="https://user-images.githubusercontent.com/35313196/234634399-10d23a5d-7a5a-448b-9d9a-300293979dd9.png">

**Comment by srajiang** [comment]
Hey Ryan! Can you try setting `install_page_rendering_enabled=False` in the App constructor under ` oauth_settings`? 

Something like this:

```python
app = App(
    logger=logger,
    signing_secret=signing_secret,
    installation_store=installation_store,
    oauth_settings=OAuthSettings(
        # your other settings
        ...
        install_page_rendering_enabled=False,
    ),
)
```

**Comment by ryanrestivo** [comment]
Is there anything else I can do to prevent this oauth error from showing up? I tried teh first solution but I have heard that people still have errors with it when they try with the button

**Comment by seratch** [comment]
@ryanrestivo 
> https://slack.com/oauth/v2/authorize

To properly use bolt-python's state paraemter validation, you cannot use this slack.com URL as the starting point of the OAuth flow (because it does not provide state parameter, which is highly recommended for general OAuth security; see https://auth0.com/docs/secure/attack-protection/state-parameters for details). You can set your `/slack/install` URL instead of `https://slack.com/oauth/v2/authorize`.

**Comment by ryanrestivo** [comment]
thanks! so that slack/install URL for the button is the proper usage for that spot. thank you! I'll make that change.
