### ISSUE TITLE
Subscribing to threaded replies

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [slackapi/bolt-python#894]
Hey Bolt team! For starters, thank you so much for creating a fantastic SDK. Getting started with development was extremely easy. 

I have a pretty simple setup wherein I have a Slack bot replying to mentions via subscription to the "app_mention" event. I want to be able to automatically detect when the user submits threaded replies to the conversation initially invoked with the mention but I'm unable to find corresponding events in the Events API documentation.

Wondering if you have any suggestions for how to be smart about detecting when threaded replies are provided and programming the bot to reply to these threaded replies. I don't want to have to rely on my threaded replies having to include an app mention for invocation of the bot.

Please let me know if you need clarification!

#### The `slack_bolt` version

1.17.2

#### Python runtime version

python 3.8.9

#### OS info

ProductName:    macOS
ProductVersion: 12.5
BuildVersion:   21G72
Darwin Kernel Version 21.6.0: Sat Jun 18 17:05:47 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8101

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by mwbrooks** [comment]
Hi @SiddhanthUnnithan 👋🏻 Thanks for the kind words! The team really appreciates hearing that you're finding it easy to get started with Bolt! ⚡ 

I agree, it would be better user experience if people can reply to an existing _@Mention_ thread without directly mentioning the bot! 👌🏻 

As far as I know, there is no "get notified about new replies" API, which is unfortunate.

Instead, you will want to listen for messages in the channel and check if it's a threaded reply to an _@Mention_ message:
* [Subscribe to the `message` events](https://api.slack.com/events/message)
    * There is currently a bug, but in the future you can [filter for messages with the subtype `message_replied`](https://api.slack.com/events/message/message_replied) ([Bolt Python docs](https://slack.dev/bolt-python/concepts#event-listening))
* Check if the `payload.thread_ts` exists and not equal to the `payload. ts` value
    * This tells you it was a reply to a thread
* Finally, use the [`conversations.replies` method](https://api.slack.com/messaging/retrieving#pulling_threads) or [`conversations.history` method](https://api.slack.com/messaging/retrieving#individual_messages) to check if the original message mentioned your app
    * Your _@Mention_ will be formatted as your app's user_id, such as `<@U012345>`

Hope that helps!
