### ISSUE TITLE
Pass context from acknowledgement phase to lazy listener

### ISSUE THREAD

**Issue by lukqw** [slackapi/bolt-python#896]
Hey there 👋 
I'm currently facing the following problem:

I've got a message shortcut listener set up, which should open a modal from a lambda running on AWS.
The issue I'm facing is that the lazy listener currently tries to open the model with the given `trigger_id`, but that is expired once the lazy listener is executed.

```
app.shortcut("create_modal")(
    ack=lambda ack:ack(), lazy=[handle_create_modal]
)

def handle_create_modal(shortcut: dict, client: WebClient):
    view = generate_empty_modal_view() #abbreviated for the sake of the sample
    view_response = client.views_open(trigger_id=shortcut["trigger_id"], view=view) 
```

I can see that the init duration of the lambda is 1.9 seconds, which is enough for the `ack` to go through, but not quick enough for the `trigger_id` to be consumed correctly.

Now I have played around a bit with matchers and the ack method and one possible solution would be to create the view in the acknowledgement phase, and updating the view inside the lazy listener.

This would require me to pass the newly generated view_id from the method that's executed in the ack method to the lazy listener. Is there a way of achieving this? Seems like adding to the `body` and / or `context` is not propagated to the lazy listener sadly.

#### The `slack_bolt` version
```
slack-bolt==1.18.0
slack-sdk==3.21.3
```

#### Python runtime version

```
Python 3.9.16
```

process_before_response is set to True

**Comment by mwbrooks** [comment]
Hi @lukqw 👋🏻 

Thanks for the detailed question and explaining your ideal next steps. I'm going to loop in a few folks from the SDK team who are familiar with the Python lazy listeners to see what the recommended approach would be to opening a modal triggered by a shortcut (and whether we can pass additional context to the lazy listener)!
