### ISSUE TITLE
How do I handle view_submissions payloads for custom workflows in slack?

### ISSUE THREAD

**Issue by azizn03** [slackapi/bolt-python#899]
(So the issue I am facing here is, I am trying to implement a solution where I have this form I am trying to implement in a workflow builder, so when I user accesses this form via a shortcut within a specific channel, they can fill in a request and the request gets posted in the channel for us to ack or mark as completed. The reason I am trying to enter the form within a workflow is because currently when a user submits the request via a manually created workflow, there is no data within the reaction_added payload to state who submitted that workflow initially so as you can see in the block of code under all the variable declaration I am grabbing the user_id via the conversation history which is not efficient.

So my issue is, when I chose my custom workflow step within the workflow builder the form shows up without an issue and returns a 200 response, but when I try to save that workflow step it just states Sorry, there was a problem trying to save your step but also returns a 200 response and there is no error output either. So I am curious what I am missing.)

### Reproducible in:

```python
#!/usr/bin/env python3

import os
import re
from slack_bolt import App
from slack_sdk import WebClient
from slack_sdk.errors import SlackApiError
from slackeventsapi import SlackEventAdapter
from slack_bolt.adapter.flask import SlackRequestHandler
from flask import Flask, request, make_response
import json

SLACK_BOT_TOKEN = os.environ["SLACK_BOT_TOKEN"]
client = WebClient(token=SLACK_BOT_TOKEN)
ack_emoji = "ack-party"
completed_emoji = "white_check_mark"
workflows = []
app = Flask(__name__)
slack_event_adapter = SlackEventAdapter(os.environ["SIGNING_SECRET"], '/slack/events', app)

channel_name = "C0567LF0G5S"
results = client.conversations_history(channel=channel_name)

for message in results["messages"]:
    if "Support-request-form" in message["text"]:
        timestamp = message["ts"]
        user_id = re.search("(?:<@)(.*)(>)", message["text"]).group(0)
        user_id = user_id[2:-1]
        workflows.append({"timestamp": timestamp, "user": user_id})

try:
    @slack_event_adapter.on('reaction_added')
    def reaction(reaction_payload):
        event = reaction_payload.get('event', {})
        reaction = event.get('reaction')
        user_reaction = event.get('user')
        workflow_ts = event.get('item', {}).get('ts')

        user_reaction_info = client.users_info(user=user_reaction)
        print(user_reaction_info)
        display_name = user_reaction_info.get('user', {}).get('profile', {}).get('display_name')
        real_name = user_reaction_info.get('user', {}).get('profile', {}).get('real_name')

        if reaction == ack_emoji:
            response = f"Your support ticket has been acknowledged by {real_name} ({display_name})"
        elif reaction == completed_emoji:
            response = f"Your support ticket has been marked as completed by {real_name} ({display_name})"

        for match_ts in workflows:
            if workflow_ts == match_ts["timestamp"]:
                message_user = match_ts["user"]
                client.chat_postMessage(channel=message_user, text=response)


    @app.route("/slack/events", methods=["POST"])
    def slack_events():
      handler = SlackRequestHandler(client)
      return handler.handle(request)


    @app.route("/workflows", methods=["POST"])
    def workflow_step():
        payload = json.loads(request.form.get("payload"))
        payload_data = payload.get('view') or payload

        callback_id = payload_data.get('callback_id')
        trigger_id = payload_data.get('trigger_id')
        if callback_id == 'open_prisma_support_request' and trigger_id:
            open_modal(trigger_id, callback_id)
            
        return make_response("", 200)
    
    def workflow_submission():
        payload = json.loads(request.form.get("payload"))
        print(payload)
        response = client.views_update(view_id=payload["view"]["id"])
        print(response)
    
        return make_response("", 200)

    def open_modal(trigger_id, callback_id):
        response = client.views_open(
            trigger_id=trigger_id,
            view= {
             "type": "workflow_step",
             "callback_id": callback_id,
              "blocks": [
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": "Type of Prisma Support Request",
                    },
                    "accessory": {
                        "type": "radio_buttons",
                        "action_id": "radio_buttons-action",
                        "options": [
                            {
                                "text": {
                                    "type": "plain_text",
                                    "text": "Issue",
                                },
                                "value": "Issue",
                            },
                            {
                                "text": {
                                    "type": "plain_text",
                                    "text": "Exception",
                                },
                                "value": "Exception",
                            },
                        ],
                    },
                },
                {
                    "type": "input",
                    "element": {
                        "type": "plain_text_input",
                        "action_id": "plain_text_input-action",
                    },
                    "label": {
                        "type": "plain_text",
                        "text": "Please fill in more details",
                    },
                },
            ],
        }
    )
          

    
    
except SlackApiError as e:
    print(f"Error: {e}")

# {
#     "message_ts1": 
#         {
#             "ack_timestamp": "blabla",
#             "complete_timestamp": "Toto"
#         },

#     "message_ts2": 
#         {
#              "ack_timestamp": "blabla",
#             "complete_timestamp": "Toto"
#         },
# }

if __name__ == "__main__":
#debug=True if file modified, don't need to restart app.
    app.run(debug=True)
```

#### The `slack_bolt` version
1.18.0
(Paste the output of `pip freeze | grep slack`)

#### Python runtime version
3.10.8
(Paste the output of `python --version`)

#### OS info
Mac OS 13.3.1
(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1. Run Slack App
2. Create custom workflow
3. Try to apply custom step in workflow by clicking the submit button

### Expected result:

(workflow step form sucessfully added into custom workflow)

### Actual result:

(Workflow step does not get added, UI states Sorry, there was a problem trying to save your step.)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @azizn03, thanks for asking the question!

It seems that you're using the `/workflows` path for the workflow custom step handling. You need to consistently set the valid URL that ends with the path for the **Request URL** in your app configuration page's Interactivity & Shortcuts section.

Also, it seems that you're trying to use both bolt-python and the legacy Flask adapter. We don't recommend using them at a time as the Flask one does not work well especially for the workflow steps (timeouts can often occur with it). Please consider using only bolt-python and have a simpler implementation following the document: https://slack.dev/bolt-python/concepts#steps With that, you don't need to have two paths `/slack/events` and `/workflows`. You can use `/slack/events` for communications with Slack API servers.

I hope this helps.
