### ISSUE TITLE
Error: unexpected indent

### ISSUE THREAD

**Issue by AlexPhan90** [slackapi/bolt-python#900]
I run this code and it keep getting error on this line

app = App(token=os.environ.get("SLACK_BOT_TOKEN"),
    signing_secret=os.environ.get("SLACK_SIGNING_SECRET")
)

**Comment by misscoded** [comment]
Hi @AlexPhan90! This error indicates a whitespace issue (Python). 

Can you try the following snippet (source available [here](https://github.com/slackapi/bolt-python/blob/main/examples/getting_started/app.py#L5)) and let us know if that resolves the issue:

```
app = App(
    token=os.environ.get("SLACK_BOT_TOKEN"),
    signing_secret=os.environ.get("SLACK_SIGNING_SECRET"),
)
```

**Comment by AlexPhan90** [comment]
Yes, thanks for your help. Let me try.
