### ISSUE TITLE
How to get slack workspace ( team) token and team data (like team_id) after installing slack using the link

### ISSUE THREAD

**Issue by suavelad** [slackapi/bolt-python#901]
Hi Team,

When slack bot is installed into a workspace using the install button, it saves the bot token, team id and other team data in the data file .

But I will like to get it as a response from an API.

How can I achieve that ?

**Comment by seratch** [comment]
Hi @suavelad, thanks for asking the question!

I guess you've installed your app from the app admin page (`https://api.slack.com/apps/{your app id}`), right? In the case, you can call auth.test API (https://api.slack.com/methods/auth.test) with the issued token. The API returns team_id and some other properties associated with the token.

I hope this helps.

**Comment by suavelad** [comment]
Hi @seratch,

I installed it using the {my domain}/slack/install

**Comment by seratch** [comment]
@suavelad In the case, your installation store has all the information returned by https://api.slack.com/methods/oauth.v2.access API. Of course, it includes team_id and other properties. When it comes to your bolt-python listener code like functions with `@app.event("app_mention")` decorator, you don't need to write any code to know team_id of a request. You can access the string via `context.team_id`.

If you have follow-up questions on this, please let us know more about your use case or code examples you're working on.
