### ISSUE TITLE
Files list not seeing all files shared

### ISSUE THREAD

**Issue by CodyFrank** [slackapi/bolt-python#904]
I created an app that allows users to upload a file and use that file for tasks later. I use a modal with a form and have mapped the file info from files.list to options of an input so the user can select a file from a drop-down. This was working great for over a year until recently newly added files stopped showing up in the dropdown. I viewed the output of files.list and the files uploaded are not being returned by files.list. Users have been uploading files by dragging and dropping the file into a message with the bot and sending the message. I have discovered if you share the file with the app (either by holding shift when uploading or sharing the files feature in Slack) files.list will return all of the files. I am using files.list with the "user" parameter set to the user who is viewing the files in the GUI so files.list should only pull that users files with the bot.

When the file is uploaded wither way it created a file shared event but it seems like files.list does not see them.

I am wondering if there has been an update to the way files need to be shared or if there is anything that can be done to allow the users to not need to hold shift when uploading the files. Many of my users are finding it difficult to remember. 

#### The `slack_bolt` version
slack-bolt==1.3.2
slack-sdk==3.3.2

#### Python runtime version
Python 3.8.5

#### OS info
ProductName:    macOS
ProductVersion: 12.5
BuildVersion:   21G72

#### Steps to reproduce:
file uploads note test #10 and #11 will not show up in GUI. This step triggers a message event and a file shared event if Shift is not held when uploading file. The data for holding shift (which works) and not holding shift (does not work) seems the same
![Screen Shot 2023-05-30 at 5 43 21 PM](https://github.com/slackapi/bolt-python/assets/48265355/03502522-e73a-44b5-bcbf-87188d63ced7)

#### message upload event
```
{
   "type":"message",
   "text":"",
   "files":[
      {
         "id":"xxxxxxxxxxx",
         "created":1685481100,
         "timestamp":1685481100,
         "name":"Auditbull_test_11.csv",
         "title":"Auditbull_test_11.csv",
         "mimetype":"text/csv",
         "filetype":"csv",
         "pretty_type":"CSV",
         "user":"xxxxxxxxx",
         "user_team":"xxxxxxxxx",
         "editable":true,
         "size":203,
         "mode":"snippet",
         "is_external":false,
         "external_type":"",
         "is_public":false,
         "public_url_shared":false,
         "display_as_bot":false,
         "username":"",
         "url_private":"https://files.slack.com/files-pri/xxxxxxxxx-xxxxxxxxxxx/auditbull_test_11.csv",
         "url_private_download":"https://files.slack.com/files-pri/xxxxxxxxx-xxxxxxxxxxx/download/auditbull_test_11.csv",
         "permalink":"https://magnataurconsulting.slack.com/files/xxxxxxxxxxx/xxxxxxxxxxx/auditbull_test_11.csv",
         "permalink_public":"https://slack-files.com/xxxxxxxxx-xxxxxxxxxxx-xxxxxxxxxx",
         "edit_link":"https://magnataurconsulting.slack.com/files/xxxxxxxxxxx/xxxxxxxxxxx/auditbull_test_11.csv/edit",
         "preview":,
         "permalink_public":"https://slack-files.com/xxxxxxxxx-xxxxxxxxxxxx-xxxxxxxxxxxx",
         "edit_link":"https://magnataurconsulting.slack.com/files/xxxxxxxxxx/xxxxxxxxx/auditbull_test_11.csv/edit",
         "preview":"preview_is_truncated":false,
         "has_rich_preview":false,
         "file_access":"visible"
      }
   ],
   "upload":false,
   "user":"U01F43JCFA8",
   "display_as_bot":false,
   "ts":"1685481107.669119",
   "client_msg_id":"f59b2dc5-dcef-4799-8d37-d4abe190fa10",
   "channel":"D01MZHVGHLM",
   "subtype":"file_share",
   "event_ts":"1685481107.669119",
   "channel_type":"im"
}
```

#### file shared event from message upload
```
{
   "type":"file_shared",
   "file_id":"xxxxxxxxxx",
   "user_id":"xxxxxxxxxx",
   "file":{
      "id":"xxxxxxxxx"
   },
   "channel_id":"xxxxxxxxx",
   "event_ts":"1685481107.009000"
}
```

#### file shared event when not holding shift
```
{
   "type":"file_shared",
   "file_id":"xxxxxxxxxxx",
   "user_id":"xxxxxxxxx",
   "file":{
      "id":"xxxxxxxxxx"
   },
   "channel_id":"xxxxxxxxxxx",
   "event_ts":"1685480965.008900"
}
```

![Screen Shot 2023-05-30 at 5 43 21 PM](https://github.com/slackapi/bolt-python/assets/48265355/b38c5781-806b-4adf-9a92-c301607168a5)

#### return from files.list
I shortened the file list for readability
```
{
   "ok":true,
   "files":[
      {
         "id":"F05A1DHGKK7",
         "created":1685464914,
         "timestamp":1685464914,
         "name":"Auditbull_test_7.csv",
         "title":"Auditbull_test_7.csv",
         "mimetype":"text/csv",
         "filetype":"csv",
         "pretty_type":"CSV",
         "user":"U01F43JCFA8",
         "user_team":"TLDQAGEN9",
         "editable":true,
         "size":203,
         "mode":"snippet",
         "is_external":false,
         "external_type":"",
         "is_public":false,
         "public_url_shared":false,
         "display_as_bot":false,
         "username":"",
         "url_private":"",
         "preview_highlight":"",
         "lines":8,
         "lines_more":0,
         "preview_is_truncated":false,
         "channels":[
            
         ],
         "groups":[
            
         ],
         "ims":[
            "xxxxxxxxxxx",
            "the same id as listed above"
         ],
         "comments_count":0
      },
      {
         "id":"xxxxxxxxxxx",
         "created":1685480357,
         "timestamp":1685480357,
         "name":"Auditbull_test_9.csv",
         "title":"Auditbull_test_9.csv",
         "mimetype":"text/csv",
         "filetype":"csv",
         "pretty_type":"CSV",
         "user":"xxxxxxxxxxx",
         "user_team":"xxxxxxxxx",
         "editable":true,
         "size":203,
         "mode":"snippet",
         "is_external":false,
         "external_type":"",
         "is_public":false,
         "public_url_shared":false,
         "display_as_bot":false,
         "username":"",
         "url_private":"https://files.slack.com/files-pri/xxxxxxxxxx-xxxxxxxxxx/auditbull_test_9.csv",
         "url_private_download":"https://files.slack.com/files-pri/xxxxxxxxx-xxxxxxxxxx/download/auditbull_test_9.csv",
         "permalink":"https://magnataurconsulting.slack.com/files/xxxxxxxxxx/xxxxxxxxxxx/auditbull_test_9.csv",
         "permalink_public":"https://slack-files.com/xxxxxxxx-xxxxxxxxxx-xxxxxxxxxxx",
         "edit_link":"https://magnataurconsulting.slack.com/files/xxxxxxxxxxx/xxxxxxxxxxx/auditbull_test_9.csv/edit",
         "preview":"",
         "preview_highlight":""
         "lines":8,
         "lines_more":0,
         "preview_is_truncated":false,
         "channels":[
            
         ],
         "groups":[
            
         ],
         "ims":[
            "xxxxxxxxxxx"
         ],
         "comments_count":0
      }
   ],
   "paging":{
      "count":100,
      "total":15,
      "page":1,
      "pages":1
   }
}
```

**Comment by seratch** [comment]
Hi @CodyFrank, thanks for asking the question!

Probably, since your app has uploaded so many files over the year, it's time to do pagination to fetch file data in files.list API response. Refer to the document https://api.slack.com/methods/files.list to learn the parameters for it.

With the `WebClient` in the SDK, you can use for syntax to fetch all the pages: https://github.com/slackapi/python-slack-sdk/blob/v3.21.3/tests/slack_sdk/web/test_web_client.py#L49-L51

I hope this helps.

**Comment by CodyFrank** [comment]
HI @seratch , Thank you for the response!

Pagination is coming soon but I don't think that is the concern today for a few reasons. 
1) The way files are uploaded changes the results on files.list even with the current number of files
2) The response from files.list says "pages": 1
3) This bug was found by a first time user who uploaded their first file
4) To confirm I cleared my files out in my testing environment so I would only have the 1 file I uploaded this attempt and no files were returned (There should have been only 1)

Are there any other possibilities? Is this the intended UX from Slack?

**Comment by CodyFrank** [comment]
@seratch Thank you for the assistance.

 I have experienced the time delay and accounted for that. That is not the issue here because I can share other files holding shift and get them to return in files.list while still not seeing the first one. 
 
The files are being shared in a conversation with the bot user and the end user. This has been working and still works when holding shift. This makes me think that you are correct there is a bug in the platform side or something is missing in my app. I will be reaching out to them. Thank you!
