### ISSUE TITLE
Unable to Download through "Add to Slack" button.

### ISSUE THREAD

**Issue by Leoputera2407** [slackapi/bolt-python#905]
I'm setting up a FastAPI server Slack App, and used the oauth_app.py example as a referrence. I can't seem to get pass the oauth_redirect path. This is going to be a multi workplace app, and I tested by clicking the "Add to Slack" button in the "Manage Distribution" Section.

Finishing the oauth page, I got redirected to `https://NGROK_URL/slack/oauth_redirect?code=xxxxx&state=`, and got this error 
<img width="1322" alt="Screenshot 2023-06-01 at 3 50 45 PM" src="https://github.com/slackapi/bolt-python/assets/33604451/e25fbcfa-a8fe-4ddd-b513-61774e6e857d">

I set this as my Redirect URL Path
```
https://4599-2600-1700-2f71-4890-e9b4-1af2-b02a-591a.ngrok-free.app/slack/oauth_redirect
```

If I were to install from `https://NGROK_URL/slack/install` (with` install_page_rendering_enabled=True`) and went through the oauth flow, it successfully installed. This is fine, but is not the desired UX. I was wondering if I missed anything in setting the correct `Add to Slack` button? 

If possible I want to set  `install_page_rendering_enabled=False`.

Btw, I've tried to remove ` install_path="/slack/install"` and still got the same error

```
def get_oauth_settings():
    return OAuthSettings(
        client_id=SLACK_CLIENT_ID,
        client_secret=SLACK_CLIENT_SECRET,
        scopes=[
            "app_mentions:read",
            "channels:history",
            "channels:join",
            "channels:read",
            "chat:write",
            "chat:write.customize",
            "commands",
            "users.profile:read",
            "users:read",
        ],
        install_page_rendering_enabled=True,
        install_path="/slack/install",
        redirect_uri_path="/slack/oauth_redirect",
        installation_store=SupabaseInstallationStore(),
        state_store=SupabaseOAuthStateStore(),
        logger=logger,
    )
```

#### The `slack_bolt` version

slack-bolt==1.18.0
slack-sdk==3.21.3
#### Python runtime version

Python 3.11.3

### Expected result:

Clicking "Add to Slack" goes through the auth flow, successfully

### Actual result:

Got Page Error, mentioning I need to start download from `slack/install`

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @Leoputera2407, I'm sorry for our slow response here.

> I tested by clicking the "Add to Slack" button in the "Manage Distribution" Section.

It might be confusing, but the "Add to Slack" button is a simple example to start your OAuth flow in a handier (but less secure) way to test if it works. The button uses `slack.com/authorize` URL without the state parameter to make things simpler, but having the parameter is highly recommended to use for better security. Refer to https://auth0.com/docs/secure/attack-protection/state-parameters for details.

Bolt framework is a bit more opinionated. Your app installers always must start the OAuth flow (=app installation flow) from `/slack/install`, not directly `slack.com/authorize` URL. The `/slack/install` URL sets a cookie value to the accessing web browser to ensure the same person is redirected to `/slack/oauth_redirect` URL.

Also, the importance of starting at `/slack/install` is the same even when you set your custom boolean value for `install_page_rendering_enabled` option.

I hope this helps.
