### ISSUE TITLE
Event filters not working

### ISSUE THREAD

**Issue by mervin-hemaraju-cko** [slackapi/bolt-python#906]
Hello team,

I am trying to send `messages.channels` message to my Python bolt app and it is triggering fine.

I tried adding a filter so that a specific channel would be trigerred but the filter is not working. Despite the filter, when i post in other channels, the event is still being trigerred.

### Reproducible in:

```python
@app.event({
    "type": "message",
    "event": {
        "channel": "XXXXXXX",
    }
})
def message_posted(client, event):
    logging.info('message_posted event triggered')
    logging.info(f"event: {event}")
```

#### The `slack_bolt` version

slack-bolt         1.18.0
slack-sdk          3.21.3

#### Python runtime version

Python 3.10.11

#### OS info

ProductName:            macOS
ProductVersion:         13.3.1
ProductVersionExtra:    (a)
BuildVersion:           22E772610a
Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000

#### Steps to reproduce:

1. Add the above code in the bolt app
2. Send a message in the undesired channel where the bot is subscribed

### Expected result:

Logging info to not be trigerred 

### Actual result:

Logging info was trigerred

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by filmaj** [comment]
Hello @mervin-hemaraju-cko,

I do not think you can constrain down to the channel using `@app.event` and specifying a dict for the `event` key. [The API documentation for `app.event` states](https://slack.dev/bolt-python/api-docs/slack_bolt/app/index.html#slack_bolt.app.App.event):

> Args
> `event`
> The conditions that match a request payload. If you pass a dict for this, you can have type, subtype in the constraint.

Sounds like you can only constrain to `type` or `subtype`, and [this is confirmed by checking the source code for how event constraining works: only `type` and `subtype` are inspected](https://github.com/slackapi/bolt-python/blob/main/slack_bolt/listener_matcher/builtins.py#L147-L169).

You can, however, easily put this filter inside your message event listener function: check the value of the channel ID from the event payload, and if it doesn't match the channel you wish to filter on, simply `pass` in the function. Otherwise, continue with execution.

Hope that helps!

**Comment by mervin-hemaraju-cko** [comment]
Thank you @filmaj :)

**Comment by mervin-hemaraju-cko** [comment]
I need to have multiple channel filtering for example:

```
@app.event({
    "type": "message",
    "subtype": None
})
def channel1(client, event):
    logging.info(f"channel1 trigerred")

    if(event['channel'] != "channel1):
        return

@app.event({
    "type": "message",
    "subtype": None
})
def channel2(client, event):
    logging.info(f"channel2 trigerred")

    if(event['channel'] != "channel2):
        return
```

This is not working because only the first event clause is being trigerred when a message is posted. Is there a way to do this or should all code resides in one events("message") ?

**Comment by seratch** [comment]
@mervin-hemaraju-cko With bolt-python, only the first matched listener is executed. There are two ways to achive your goal:
* As you mentioned, putting everything into a single listener function
* Have listener matcher/middleware to match a request's associated channel; refer to https://slack.dev/bolt-python/concepts#listener-middleware for details 

Let me share a simple code snippet demonstrating the second approach:

```python
@app.event(
    event={"type": "message", "subtype": None},
    matchers=[lambda event: event["channel"] == "C111"],
)
def handle_channel1_only(client, event):
    logging.info(f"channel1 trigerred")


@app.event(
    event={"type": "message", "subtype": None},
    matchers=[lambda event: event["channel"] == "C222"],
)
def handle_channel2_only(client, event):
    logging.info(f"channel2 trigerred")


# This listener must be defined after the above two
@app.event(event={"type": "message", "subtype": None})
def handle_the_rest(client, event):
    logging.info(f"the rest")
```

I hope this helps.

**Comment by mervin-hemaraju-cko** [comment]
@seratch This is exaclty what i was looking for! Thank you :)
