### ISSUE TITLE
Slack Event Subscriptions Error: url/slack/events Not Handled Properly

### ISSUE THREAD

**Issue by ongtw** [slackapi/bolt-python#908]
(Filling out the following details about bugs will help us solve your issue sooner.)

### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version

```
❯ pip freeze | grep slack
slack-bolt==1.18.0
slack-sdk==3.21.3
```

#### Python runtime version

```
❯ python --version
Python 3.9.12
```

#### OS info

```
❯ sw_vers && uname -v # or `ver`
ProductName:	macOS
ProductVersion:	12.6.3
BuildVersion:	21G419
Darwin Kernel Version 21.6.0: Mon Dec 19 20:46:01 PST 2022; root:xnu-8020.240.18~2/RELEASE_ARM64_T8101
```

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1. I followed the instructions in https://api.slack.com/start/building/bolt-python
2. When I got to the section *Subscribing to Events*, I encountered the following error on the Slack API Website:
![slack_api_web](https://github.com/slackapi/bolt-python/assets/13075447/dde87769-259f-4e7c-b2e2-2c163b07773b)
3. The following screenshot shows my terminal windows: the `ngrok` output, the runtime output and the code:
![terminal_windows](https://github.com/slackapi/bolt-python/assets/13075447/72812ef6-22e6-4eb2-9e6a-be6b0e3878ec)

### Expected result:

Expected the Slack API website instructions to work.

### Actual result:

Did not work: either
1) the website instructions are outdated
2) the website backend code is buggy, calling the `ngrok` URL with incorrect credentials
3) the Bolt `App` is buggy, not handling the `slack/events` call correctly

Created a GitHub repo to demo this error at https://github.com/ongtw/slack_bolt_evt_sub_error

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @ongtw, thanks for writing in! 

This is not an error in the document. It seems that your app is not properly loading "Signing Secret" string value, which can be used for verifying a request from Slack. The tutorial uses the "SLACK_SIGNING_SECRET" env variable, but your code tries to load "SLACK_SECRET" instead. Please double-check if you've set a valid signing secret value with the env variable name that you use in your code.

**Comment by ongtw** [comment]
Hi @seratch , appreciate your reply. I double checked the secret key and realised I had been using the wrong one (client secret instead of signing secret). It works now after fixing it.
