### ISSUE TITLE
Action Listener Unresponsive to Interaction in App Home

### ISSUE THREAD

**Issue by dglindner2** [slackapi/bolt-python#909]
I'm working on creating an app that will allow users to select an account from a dropdown list, and the homepage will update with information about the account upon selection. I've gotten interactions to work through a modal, but cannot get any response on the Home Tab of the App. 

I have enabled Interactivity for my application and am testing locally using ngrok. I have the same URL handling requests from the Event Subscription and the Interactivity tab where both URLs are ending with `slack/events`.  

#### The `slack_bolt` version
`slack-bolt==1.18.0`
`slack-sdk==3.21.3`

#### Python runtime version
`Python 3.11.2`

#### OS info

ProductName:            macOS
ProductVersion:         13.3.1
ProductVersionExtra:    (a)
BuildVersion:           22E772610a

#### Steps to reproduce:

```python
app = App(
    token=os.environ.get("SLACK_BOT_TOKEN"),
    signing_secret=os.environ.get("SLACK_SIGNING_SECRET"),
)


@app.action("account-select-action")
def handle_action(body, ack):
    ack()
    print(body)


@app.event("app_home_opened")
def update_home_tab(client, event, logger):
    try:
        user = event["user"]
        client.views_publish(
            user_id=user,
            view={
                "type": "home",
                "blocks": [
                    {
                        "type": "header",
                        "text": {"type": "plain_text", "text": "Account Summary"},
                    },
                    {
                        "type": "input",
                        "element": {
                            "type": "static_select",
                            "action_id": "account-select-action",
                            "placeholder": {
                                "type": "plain_text",
                                "text": "Select an item",
                            },
                            "options": [
                                {
                                    "text": {"type": "plain_text", "text": "Option 1"},
                                    "value": "value_1",
                                },
                                {
                                    "text": {"type": "plain_text", "text": "Option 2"},
                                    "value": "value_2",
                                },
                                {
                                    "text": {"type": "plain_text", "text": "Option 3"},
                                    "value": "value_3",
                                },
                            ],
                        },
                        "label": {
                            "type": "plain_text",
                            "text": "Please Select an Account:",
                        },
                    },
                ],
            },
        )
    except Exception as e:
        logger.error(f"Error publishing home tab: {e}")


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 3000))
    app.start(port=port)
```

### Expected result:

I would expect the body of the response to be printed when I changed the selection in the home tab of the application. I would like to confirm that this interaction is working so that I can update a markdown data table with information related to the selected account in the static dropdown menu.

### Actual result:
There is no response, nothing printed, and nothing to prove to me that this interactivity is functioning properly. There is nothing on the ngrok page either to indicate that this interaction ever happened.

**Comment by seratch** [comment]
Hi @dglindner2, thanks for writing in!

> There is nothing on the ngrok page either to indicate that this interaction ever happened.

This indicates the button click event might not be sent to your public endpoint. Could you double-check if you've enabled "Interactivity" and have configured a valida "Request URL" on the `https://api.slack.com/apps/{your App ID}/interactive-messages` page?

I hope this helps.

**Comment by dglindner2** [comment]
I have the same Request URL that I am using for handling Event Subscriptions (which is working). I am able to receive payloads from events so I know that the URL is valid. Additionally, when I use interactivity from a Modal this is valid. The non-response only occurs when trying to use interactivity in the app home tab.

**Comment by seratch** [comment]
@dglindner2 Ah, you're using input blocks on Home tab. In this case, you need to set dispatch_action: true to trigger block_actions payload events. See https://api.slack.com/reference/block-kit/blocks#input for details. This option is necessary when you use input blocks on either a channel message or Home tab. Another way is to use section / actions blocks instead. With these blocks, user interactions trigger block_actions events. I hope this helps.

**Comment by dglindner2** [comment]
Amazing this worked! Thank you - could not figure out why it is working in Modal but not Home tab. Thanks!
