### ISSUE TITLE
IP address/ endpoint for Slack API

### ISSUE THREAD

**Issue by kheehou** [slackapi/bolt-python#910]
I'm deploying a Slack Bot made with Bolt on Google Cloud Run and will be routing all traffic through a VPC. I've a load balancer that will handle external traffic into my VPC, and I'm wondering how I should configure my ingress controls to only allow IP addresses from Slack to reach my load balancer. Is there any range of IP addresses that I can specify to achieve this? Thanks!

**Comment by seratch** [comment]
HI @kheehou, thanks for asking the question!

> how I should configure my ingress controls to only allow IP addresses from Slack to reach my load balancer. Is there any range of IP addresses that I can specify to achieve this?

Unfortunately, Slack API servers do not guarantee the IP address range to use when sending requests to you app. Thus, as I mentioned at https://github.com/slackapi/python-slack-events-api/issues/92#issuecomment-833141291, verifying a request's headers to make sure if the request is surely from Slack is the recommended (and the only) way to serve your app's endpoint in a secure manner.

This may not be a great answer for your use case, but I hope this helps.
