### ISSUE TITLE
Slack Bolt with Flask and sqlalchemy context 

### ISSUE THREAD

**Issue by krab-skunk** [slackapi/bolt-python#913]
I'm trying to get context for getting access to my Db models using python3  / slack_bolt / flask 

### Reproducible in:

`app.__init__.py`
```python
def create_app(**config_overrides) -> Flask:
    app = Flask(__name__)
    app.config.from_object(get_config())
    with app.app_context():
        from .db import init_db
        db.init_db(app)

        from .views import init_views
        init_views(app, db)

    return app

def create_slack_app():
        from slack_bolt import App
        slack_app = App(
            token=get_env("SLACK_BOT_TOKEN"),
            signing_secret=get_env("SLACK_SIGNING_SECRET")
        )
        return slack_app

slack_app = create_slack_app()
```

`app.db.py`
```python
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

db = SQLAlchemy()

def init_db(app):
    db.init_app(app)
    migrate = Migrate(app, db) 
    
    return db

```

`app.models.py`
```python
from .db import db
....

class User(BaseModel):
    __tablename__ = 'user'

    slack_id = db.Column(db.String, nullable=False)
```

and for example, one of my view 

`app.views.view1.py`
```python
from app import slack_app

handler = SlackRequestHandler(slack_app)

@slack_app.action("multi_ext_select")
def handle_submit(client, body, ack, logger):
     from app.models import User
     User.query.first()
```
```User.query.first()``` will fail with `RuntimeError: working outside of application context`

It seems that i'm not the only one coming accross this issue https://bigbunny.io/handling-flask-application-context-for-slack_bolt.html, but i still quite dunno how to solve it , could you help me out please ?

Thanks a lot 

#### The `slack_bolt` version
```
slack-bolt==1.18.0
slack-sdk==3.21.3
```

#### Python runtime version

```Python 3.11.3```

**Comment by steve-heslouin** [comment]
if i remove all occurences of slack_bolt and use purely my flask app, i get the context to access db, but i would have prefer to try slack_bolt for a chance

**Comment by seratch** [comment]
HI @krab-skunk, thanks for writing in! 

I haven't tried to reproduce your issue in your app design, but we have a simpler example here: https://github.com/slackapi/bolt-python/blob/main/examples/sqlalchemy/oauth_app.py As long as you simply use an Engine object in listeners, you won't be botherred by the thread local related issues (I mean Flask heavily relies on thread local data sharing inside the framework, which prevents async `ack()` mechanism in bolt-python). 

If you still have a certain reason to depend on Flask app context for managing database connections, checking our Django ORM support (https://github.com/slackapi/bolt-python/blob/v1.18.0/slack_bolt/adapter/django/handler.py#L61-L91) may be helpful for you to learn what you can do. That being said, this project does not recommend app context for the use case. Thus, we won't be able to provide further help on this topic. It'd be appreciated if you could understand this.

I hope this helps.

**Comment by samkit-jain** [comment]
Hi @krab-skunk , I am facing the same issue. The only way I was able to resolve it was by using the app context before the query. For example
```python
with flask_app.app_context():
    User.query.first()
```
Have you been able to find a better way?
