### ISSUE TITLE
Limit to # of blocks in the attachments field?

### ISSUE THREAD

**Issue by k24dizzle** [slackapi/bolt-python#914]
Is there a limit to how many blocks can be in the `attachments` field? https://api.slack.com/reference/messaging/attachments#fields

<img width="1112" alt="Screen Shot 2023-06-08 at 11 25 07 AM" src="https://github.com/slackapi/bolt-python/assets/15153943/dc29df15-5159-4903-8bc7-d7d5d2bd7d6f">

In our own testing, we seem to run into an `invalid_attachments` error when the # of blocks exceed 20, but just wanted confirmation.

**Comment by filmaj** [comment]
Is there a specific API you are seeing this with? `chat.postMessage`?

**Comment by filmaj** [comment]
Depending on which API you are using, there is a maximum of 100 attachments, but if you surpass that, a dedicated `too_many_attachments` error would be raised - which is not what you are getting.

I would try to isolate an API call per each attachment you are trying to generate, to see if perhaps one of the specific attachments you are trying to use is not valid.

**Comment by filmaj** [comment]
Oh woops I misread your question: you are asking for maximum number of blocks _per attachment_. I believe it is 50 - but, even if you exceed that, you should receive an `invalid_blocks` error.

Are you logging out the entire error? Depending on the API used and the circumstances of the failure mode, more information may be logged out beyond just the error name.

**Comment by k24dizzle** [comment]
Thanks for the info, let me try doing that ^
