### ISSUE TITLE
App listening to both parent and thread message events instead of just parent

### ISSUE THREAD

**Issue by mervin-hemaraju-cko** [slackapi/bolt-python#915]
Hello team, great work on the SDK! Was easy to get started with it.

My Bolt app is listening to events on a specific channel. However, i want my bot to listen to only parent messages posted  on the channel and not threads. The issue here is that even if someone replies to a thread, the event is getting trigerred.

### Reproducible in:

```
    app.event(
        event={"type": "message", "subtype": None},
        matchers=[lambda event: event["channel"] == di['slack_channel_askitplatform_id']],
    )
def event_ask_it_platform(client, event, say):
    '''
        Function that will trigger when messages are posted
        to the ask_it_platform channel
    '''
    logging.info(f"event_ask_it_platform triggered: {event}")
```

#### Subscribed bot events

- member_joined_channel  
- message.channels
- message.groups 
- reaction_added

#### The `slack_bolt` version

slack-bolt 1.18.0
slack-sdk 3.21.3

#### Python runtime version

Python 3.10.11

#### OS info

ProductName: macOS
ProductVersion: 13.3.1
ProductVersionExtra: (a)
BuildVersion: 22E772610a
Darwin Kernel Version 22.4.0: Mon Mar 6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000

#### Steps to reproduce:

1. Add the above code in the bolt app
2. Send a message in the desired channel where the bot is subscribed
3. Reply in the thread message.

### Expected result:

- Thread replies shouldn't be trigerred.

### Actual result:

- Thread replies are being trigerred

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hey @mervin-hemaraju-cko, thanks for writing in! app.event does not support subtype prop in a dict as only message events have subtype. You can use app.message, which support subtype constraint instead.

**Comment by mervin-hemaraju-cko** [comment]
So, running something like this should solve the issue?

```
    app.message(
        event={"type": "message", "subtype": None},
        matchers=[lambda event: event["channel"] == di['slack_channel_askitplatform_id']],
    )
def event_ask_it_platform(client, event, say):
    '''
        Function that will trigger when messages are posted
        to the ask_it_platform channel
    '''
    logging.info(f"event_ask_it_platform triggered: {event}")
``

**Comment by seratch** [comment]
Also, please use a decorator in the code (meaning @app.message(…))

**Comment by mervin-hemaraju-cko** [comment]
@seratch Using it like this

```
    app.message(
        matchers=[lambda event: event["channel"] == di['slack_channel_askitplatform_id']],
    )
def event_ask_it_platform(client, event, say):
    '''
        Function that will trigger when messages are posted
        to the ask_it_platform channel
    '''
    logging.info(f"event_ask_it_platform triggered: {event}")
```

throws the following exception: `TypeError: App.message() missing 1 required positional argument: 'keyword'`

I cannot listen to a specific keyword as i need to listen to all incoming `parent` messages

**Comment by seratch** [comment]
Ah sorry. having `keyword=''` should work for you. Toe learn other options, please check the API docs: https://slack.dev/bolt-python/api-docs/slack_bolt/app/app.html#slack_bolt.app.app.App.message

**Comment by mervin-hemaraju-cko** [comment]
So i went with this piece of code:

```
    @app.message(
        keyword ='',
        matchers=[lambda event: event["channel"] == di['slack_channel_askitplatform_id']],
    )
def event_ask_it_platform(client, event, say):
    '''
        Function that will trigger when messages are posted
        to the ask_it_platform channel
    '''
    logging.info(f"event_ask_it_platform triggered: {event}")
```

It didn't throw an error anyore but it is still trigerring for both parent and thread messages.

Looking in their payloads, both parent and thread message provides a `'type': 'message'`.

Is there any way from preventing thread messages getting trigerred?

**Comment by seratch** [comment]
You can check the existence of "message_replied" subtype: https://api.slack.com/events/message/message_replied for it. Hope it works for you! 

I will be offline for a while. Please close this issue once you manage to achieve your goal here 👋

**Comment by mervin-hemaraju-cko** [comment]
Thank you @seratch. `thread_ts` worked for me!
