### ISSUE TITLE
View no longer updates on response action update

### ISSUE THREAD

**Issue by rothhwelll** [slackapi/bolt-python#916]
(Filling out the following details about bugs will help us solve your issue sooner.)

#### The `slack_bolt` version: 1.15.2

```python
@app.shortcut("account_unlock")
def open_unlock_modal(ack, body, client):
    ack()
    client.views_open(
        trigger_id=body["trigger_id"],
        view={
            "type": "modal",
            "callback_id": "view_2",
            "title": {"type": "plain_text", "text": "Unlock account"},
            "submit": {"type": "plain_text", "text": "Submit"},
            "blocks": [
                {
                    "type": "input",
                    "block_id": "username_input",
                    "element": {
                        "type": "plain_text_input",
                        "action_id": "plain_text_input-action",
                    },
                    "label": {"type": "plain_text", "text": "Username", "emoji": False},
                }
            ],
        },
    )


@app.view("view_2")
def handle_unlock_submission(ack, body, client, view, logger):
    newProcessingView = {
        "external_id": "processing",
        "type": "modal",
        "callback_id": "view_2.1",
        "title": {"type": "plain_text", "text": "Unlock Account"},
        "blocks": [
            {
                "type": "section",
                "text": {
                    "type": "plain_text",
                    "text": "Processing....",
                    "emoji": False,
                },
            }
        ],
    }
    ack(response_action="update", view=newProcessingView)
```

### Expected result:

Upon hitting submit on the first modal, a new intermediate modal is posted to let some processing work in the background

### Actual result:

The first modal spins and throws a We had some trouble connecting error message.

The message is being acked from what I can see as the processing I have omitted from this post does continue, but the updated modal doesn't show. This is a recent problem and used to work perfectly fine 1 - 2 months ago.

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by srajiang** [comment]
Hi @rothhwelll - Thanks for writing in. 
> The first modal spins and throws a We had some trouble connecting error message.

Usually when we get that error it's because the app hasn't responded to Slack with 200 OK within the required 3 second timeframe. Based on your code provided though, I can't see anything immediate that would prevent that from happening. 

If the other process you were mentioning you omitted is a bit time consuming, like a search, and if its pushing the response time to after 3 seconds, that could be causing the issue.

**Comment by seratch** [comment]
A few things to add:
* If you run the app with process_before_response: True option on AWS Lambda, regardless of the timing of `ack()` call, your whole listener execution must complete within 3 seconds. Your app might be taking longer time for initialization recently and that may be the cause of the timeouts
* If you run the app on Socket Mode, you might have other oudated but active client connections. If the connection does not have a valid listener for the view submission, the first attempt with the invalid connection can fail and then retry requests may be sent to another, which can handle the operation. This may be the case.

Either way, there is no change that can cause your issue on the platform side. The above two possibilities are common, but there may be a different cause for it. Also, I'd suggest checking your app's access log data to see how your app responds to requests from Slack (e.g., does the response time exceed 3 seconds? are retried requests coming? etc.)

**Comment by rothhwelll** [comment]
So its weird. My `ack()` happens straight away when that `@app.view` is called. Any processing I have do, happens below and still goes ahead even with the timeout error slack is throwing. What I am confused by is that this solution was working fine for months and just suddenly stopped without any changes by me. I do run the app in socket mode yes. Any ideas on how I could best troubleshoot no available listeners?

**Comment by seratch** [comment]
As I mentioned above, the only possible cause that I can think of is that your app now has a few active connections but at leat one of them may not respond properly. If this is the cause of your issue, you can try generating a new app-level token (SLACK_APP_TOKEN, which starts xapp-) and revoking the old one. If your app with the new app-level token does not have the issue, my guess is correct.

**Comment by rothhwelll** [comment]
Just to add on the above. If I change my code to just a regular `ack()` with no response action, the view closes and my code in the background keeps going ahead so the ack must be working

**Comment by rothhwelll** [comment]
So the initial model is just

```
view={
            "type": "modal",
            "callback_id": "view_2",
            "title": {"type": "plain_text", "text": "Unlock account"},
            "submit": {"type": "plain_text", "text": "Submit"},
            "blocks": [
                {
                    "type": "input",
                    "block_id": "username_input",
                    "element": {
                        "type": "plain_text_input",
                        "action_id": "plain_text_input-action",
                    },
                    "label": {"type": "plain_text", "text": "Username", "emoji": False},
                }
            ],
        }
```

And the one I was updating to is

```
newProcessingView = {
        "external_id": "ldap_processing",
        "type": "modal",
            "callback_id": "view_2.1",
            "title": {
		        "type": "plain_text",
		        "text": "Unlock LDAP"
	        },
	        "blocks": [
		        {
			        "type": "section",
			        "text": {
				        "type": "plain_text",
				        "text": "Processing....",
				        "emoji": False
			        }
		        }
	        ],
    }
```

The whole section looks like this. I've omitted anything not relevant
```
@app.view("view_2")
def handle_unlock_submission(ack, body, client, view, logger):
    newProcessingView = {
        "external_id": "acc_processing",
        "type": "modal",
            "callback_id": "view_2.1",
            "title": {
		        "type": "plain_text",
		        "text": "Unlock Account"
	        },
	        "blocks": [
		        {
			        "type": "section",
			        "text": {
				        "type": "plain_text",
				        "text": "Processing....",
				        "emoji": False
			        }
		        }
	        ],
    }
    ack(response_action="update", view=newProcessingView)
    data = view['state']['values']
    username = data['username_input']['plain_text_input-action']['value']
    conn = unlock_acc(username)
    if conn.result[u'result'] == 0:
        newViewGood = {
            "external_id": "Account_unlocked",
            "type": "modal",
            "callback_id": "view_2.1",
            "title": {
		        "type": "plain_text",
		        "text": "Unlock Account"
	        },
	        "blocks": [
		        {
			        "type": "section",
			        "text": {
				        "type": "plain_text",
				        "text": "Your account has been unlocked!",
				        "emoji": False
			        }
		        }
	        ],
        }
        client.views_update(view_id=body['view']['id'], view=newViewGood)
    else:
        newViewBad = {
            "type": "modal",
            "callback_id": "view_2.1",
            "title": {
		        "type": "plain_text",
		        "text": "Unlock Account"
	        },
	        "blocks": [
		        {
			        "type": "section",
			            "text": {
				            "type": "plain_text",
				            "text": "Error! Account not found! Please contact support",
				            "emoji": False
			            }
		            }
	            ],
            }
        client.views_update(view_id=body['view']['id'], view=newViewBad)
```

The modals aren't anything special I don't think and as I mentioned, this was working without any issues for a few months. I've also tried it on a few different machines

**Comment by seratch** [comment]
I just quickly ran your code. As long as `conn = unlock_acc(username)` does not take long (like a few seconds), I don't see any issues on the code. This means that it's not an issue related to this SDK.

One more thing you can try is to enable debug-level logging: https://slack.dev/bolt-python/concepts#logging With that, you may be able to figure out what's happening with your app (e.g., not receiving a request from Slack etc.).

If you still observe the issue frequently, I recommend contacting our platform support agents. They can check the server-side logs and metadata of your app/workspace for you. They don't support SDK specific questions, but they can help you out for general issues on the platform. I am sorry for bothering you, but it'd be appreciated if you could understand this. You can contact our support team via either `/feedback` in your Slack workspace or https://my.slack.com/help/requests/new

**Comment by rothhwelll** [comment]
Yeah I'll mess around with the connection result unlocking the account and see if I can get it to budge. I'll also try out the debug level logging and see if I can get any more clues from that. Thank you both for the help. Couldn't find anything similar online to this so was wondering if something had changed. Happy to close this out.
