### ISSUE TITLE
:sunny: emoji is rendered as the  black sun

### ISSUE THREAD

**Issue by lessless** [slackapi/bolt-python#920]
(Filling out the following details about bugs will help us solve your issue sooner.)

### Reproducible in:

```bash
pip freeze | grep slack
slack==0.0.2

python3 --version
Python 3.11.4

sw_vers && uname -v
ProductName:		macOS
ProductVersion:		13.4
BuildVersion:		22F66
Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000
```

#### Steps to reproduce:

1. Create a block with a ☀️  emoji
2. Send it to a user
3. Observe it's being improperly rendered

### Expected result:

I expect to see ☀️ emoji in the message 

### Actual result:

Instead I see  the black sun character

![](https://i.imgur.com/6yZLKzH.png)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by mwbrooks** [comment]
Hi @lessless thanks for sharing this issue!

I see that you asked the same question in our [Slack Community Workspace](https://community.slack.com/archives/C02C28Z3XA7/p1687048012750979?thread_ts=1687044479.018669&cid=C02C28Z3XA7). Just to close the loop, I'll copy the response from @seratch:

> It seems that this is an issue specific to the label for text input block: [Block Kit Builder](https://app.slack.com/block-kit-builder/#%7B%22title%22:%7B%22type%22:%22plain_text%22,%22text%22:%22My%20App%20%E2%98%80%EF%B8%8F%22,%22emoji%22:true%7D,%22submit%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Submit%22%7D,%22type%22:%22modal%22,%22close%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Cancel%E2%98%80%EF%B8%8F%22%7D,%22blocks%22:%5B%7B%22type%22:%22input%22,%22element%22:%7B%22type%22:%22plain_text_input%22,%22action_id%22:%22plain_text_input-action%22%7D,%22label%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Label%20%E2%98%80%EF%B8%8F%22%7D%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22mrkdwn%20text%20%E2%98%80%EF%B8%8F%22%7D%7D%5D%7D)
> Would you mind sharing this with our customer support team? Reports from customers will be shared with engineering teams. You can send an inquiry from either /feedback in your main workspace or https://my.slack.com/help/requests/new

Once you reach out the customer support, they'll submit an issue with the Block Kit Builder team to fix the issue!
