### ISSUE TITLE
Displaying errors in the modal view causes an unexpected error

### ISSUE THREAD

**Issue by hojun-y** [slackapi/bolt-python#922]
#### The `slack_bolt` version
```
slack-bolt==1.18.0
slack-sdk==3.21.3
```
#### Python runtime version
Python 3.11.3
#### OS info
```
ProductName:	macOS
ProductVersion:	12.6.6
BuildVersion:	21G646
Darwin Kernel Version 21.6.0: Mon Apr 24 21:10:53 PDT 2023; root:xnu-8020.240.18.701.5~1/RELEASE_X86_64
```

#### Steps to reproduce:
My view has an input block as below:
```javascript
{
	"block_id": "document",
	"type": "input",
	"element": {
		"type": "plain_text_input",
		"action_id": "document_title",
		"placeholder": {
			"type": "plain_text",
			"text": "e.g., abc.pdf"
		}
	},
	"label": {
		"type": "plain_text",
		"text": "Document file name",
		"emoji": true
	}
}
```
When I open the view, it is displayed correctly, and I can read the value of `document_title` by listening to the `view_submission` event.
However, when handling a `view_submission` event with `response_action='errors'`, Slack shows a message that says there was an unexpected error and does not show an error message I set.
I used the code below:
```python
@self.app.view('view_1')
def _process_submission(ack, body, client, view, logger):
        name = "abc.pdf"  # for example
        ...
        ack(response_action='errors', errors={"document": f"File {name} does not exist!"})
        return
```
When I removed all the arguments in the `ack` call for the test purpose, the view closed well in this case as soon as I clicked the submit button.

### Expected result:
Error message `File abc.pdf does not exist!` is displayed around the input field

### Actual result:
Nothing happens, but `Sorry, there was an unexpected error. Please try again` message pops up when I submit the view.

**Comment by seratch** [comment]
Hi @hojun-y, thank you for your question! I've been assisting developers with the Slack platform for some time, but this error is new to me. To narrow down the issue, how about replacing the current error message in `errors` with a simpler and shorter one like "Something went wrong!"? Including the input in the error message could lead to unexpected issues, such as a length error. Also, please double-check if your modal surely use "document" as a block_id in the `blocks`.

**Comment by hojun-y** [comment]
Hello, @seratch; thank you for the quick response.
I already tested the API by replacing the error message with `{"document": "Hello, world!"}` but it produced the same result. Also, I'm sure the block whose id is `document` is in the modal because I can read what the user wrote in that textbox.

**Comment by seratch** [comment]
@hojun-y, could you provide a minimal, reproducible example of your code? I'm unable to offer any further suggestions based on the information currently available.

**Comment by hojun-y** [comment]
@seratch 
I extracted the core source code from what I'm working on and pasted them below.
Do I need to provide the full code with `App` and `SocketModeHandler`?
```
ui = {
    "type": "modal",
    "callback_id": "document",
    "title": {
        "type": "plain_text",
        "text": "Modal",
        "emoji": True
    },
    "submit": {
        "type": "plain_text",
        "text": "Submit",
        "emoji": True
    },
    "close": {
        "type": "plain_text",
        "text": "Cancel",
        "emoji": True
    },
    "blocks": [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": "Modal test",
                "emoji": True
            }
        },
        {
            "block_id": "document",
            "type": "input",
            "element": {
                "type": "plain_text_input",
                "action_id": "document_title",
                "placeholder": {
                    "type": "plain_text",
                    "text": "e.g., agc_hello012345.odt"
                }
            },
            "label": {
                "type": "plain_text",
                "text": "Document file name",
                "emoji": True
            }
        }
    ]
}

@self.app.action('button')  # This triggers the modal
def _show_modal(ack, body, client):
    ack()
    client.views_open(
        trigger_id=body['trigger_id'],
        view=ui
    )

@self.app.view('modal')
def _process_submission(ack, body, client, view, logger):
    errors = {"document": "error"}
    ack(response_action='errors', errors=errors)
    return
```

**Comment by seratch** [comment]
@hojun-y  The `'modal'` in `@app.view('modal')` needs to be a valid `callback_id`. With the current example, you're using `document` for it (I recommned changing it to a clearer name, though), so `@app.view('document')` worked for me.

**Comment by hojun-y** [comment]
@seratch Sorry, it was my typo while extracting the code. Instead, I made a simple, fully working script that can produce the issue I encountered. Could you test with the code below? In the code, the `ERROR!` is printed in the console when I submit the view, so I'm sure the script receives the submission event well. 
```
import os
from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler

app = App(token=os.environ.get("SLACK_BOT_TOKEN"))
ui = {
    "type": "modal",
    "callback_id": "document",
    "title": {
        "type": "plain_text",
        "text": "Modal",
        "emoji": True
    },
    "submit": {
        "type": "plain_text",
        "text": "Submit",
        "emoji": True
    },
    "close": {
        "type": "plain_text",
        "text": "Cancel",
        "emoji": True
    },
    "blocks": [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": "Modal test",
                "emoji": True
            }
        },
        {
            "block_id": "document",
            "type": "input",
            "element": {
                "type": "plain_text_input",
                "action_id": "document_title",
                "placeholder": {
                    "type": "plain_text",
                    "text": "Type a document file name"
                }
            },
            "label": {
                "type": "plain_text",
                "text": "Document file name",
                "emoji": True
            }
        }
    ]
}


@app.action('button_t1')
def _show_modal(ack, body, client):
    ack()
    client.views_open(
        trigger_id=body['trigger_id'],
        view=ui
    )


@app.view('document')
def _process_submission(ack):
    errors = {"document": "error"}
    print("ERROR!")
    ack(response_action='errors', errors=errors)
    return


if __name__ == "__main__":
    SocketModeHandler(app, os.environ["SLACK_APP_TOKEN"]).start()
```

**Comment by hojun-y** [comment]
When I submit the modal, I get this result:
<img width=50% src="https://github.com/slackapi/bolt-python/assets/48780831/83ac017f-1e6b-4035-b667-396b2c9bc29a" />

**Comment by seratch** [comment]
@hojun-y So, it worked for me. The error message was displayed in the block. There are two possibilities that I can think of:

* Double-check if you've enabled Interactivity (the toggle must be "On")
* If you started with Request URL first and then switch to Socket Mode later, please switch back to the endpoint mode and remove the string for Request URL. This issue existed at least in the past.

If none of above is your case, I am sorry but I really don't have any further suggestions for you.

**Comment by hojun-y** [comment]
@seratch 
The interactivity toggle is on, and I initially started developing the app using Socket Mode.
In this case, do I need to re-install the app to the workspace?

**Comment by seratch** [comment]
I don't think re-installation can help. By the way, are you checking the behavior with a mobile app (Android/iOS)? If yes, please ugrade its version to the latest, just in case. A specific version of mobile app may have some issue (I've never heard of such, though). Another thing you can try is to create a different app from scratch and see if the same issue can arise.

**Comment by hojun-y** [comment]
@seratch 
When I tested the app on the desktop, I got a different error message called `We had some trouble connecting. Try again?`. However, I still can handle the submission event without causing any error when I remove all the arguments in the `ack`.
