### ISSUE TITLE
Slack Events API is showing verified for older URL(s)

### ISSUE THREAD

**Issue by SumanDas94** [slackapi/bolt-python#923]
I verified the challenge parameter using Slack Events API on a paritcular endpoint.
But whenever I retry on the same endpoint , although it shows that the request is verified but I don't see my nginx logging it.
Also endpoints which I have used before still show verified even though I removed my slackbot service from them. I am not understanding why this is happening
I am using slack-bolt==1.1.4

**Comment by seratch** [comment]
Hi @SumanDas94, thank you for your question. 

I agree that it may not be immediately intuitive, but the Request URL verification can actually be bypassed if the same URL has been recently verified for the same app. This behavior may change in the future, but as of today, this is how it operates. 

If there are no further clarifications needed on this, could you close this issue now?

**Comment by SumanDas94** [comment]
@seratch That makes sense for the current endpoint but an endpoint which was used in the past and no longer used now, why would that also show that the request call for url_verification is verified ?

**Comment by seratch** [comment]
> an endpoint which was used in the past and no longer used now

What I meant to say was that this endpoint remains marked as verified on Slack's server-side, even after a certain amount of time has passed. This is why a new url_verification request was not sent to the endpoint when you re-entered the URL.

**Comment by SumanDas94** [comment]
Is there a time period for that ? Like a fixed time period till which the verification would not be resent ?

**Comment by seratch** [comment]
I don't have any specific information at the moment, but to the best of my knowledge, there may be no expiration date. As far as I'm aware, the platform hasn't made any public commitment regarding this. If you need to use the URL verification for some reason, please consider using a query string as a workaround for the test.
