### ISSUE TITLE
How to respond to option select events?

### ISSUE THREAD

**Issue by Mark-Renzi** [slackapi/bolt-python#924]
I have a slack app running on AWS Lambda using slack-bolt python ver 1.18.0. One of the listeners is formatted as the following: `@app.options(re.compile("^column"))`.  This works with no issues and I am able to use the user input from an external select to display the desired options.  The select element in question exists inside of a view element that I push to the user from a slash command.  However, when I try to add the listener: `@app.action(re.compile("^column"))`, `@app.block_action(re.compile("^column"))`, or `@app.action("column")`, the listener never seems to get called, although in the documentation, it lists that there will be a block_action event when a select option is picked.  Is this functionality only for multi-select elements?  If it is, then this will be an issue I should address with slack API.

I am attempting to use a selected option in the first select to store metadata used to narrow down the options available in another select element.  If there is a better way to do this, then any help is greatly appreciated.

### Reproducible in:

```
slack-bolt==1.18.0
slack-sdk==3.21.3
Python 3.8.10
Linux #1 SMP Fri Apr 2 22:23:49 UTC 2021
```

#### The `slack_bolt` version

```
slack-bolt==1.18.0
slack-sdk==3.21.3
```

#### Python runtime version

`Python 3.8.10`

#### OS info

`#1 SMP Fri Apr 2 22:23:49 UTC 2021`

#### Steps to reproduce:

bot scopes: 'channels:read,groups:read,mpim:read,app_mentions:read,metadata.message:read,commands,files:write,chat:write'

1. Enable event subscriptions and interactivity/shortcuts
2. Register action listener for action_id of select element
3. Log or print anything from inside function called by listener

### Expected result:

Information will be logged or printed

### Actual result:

No result of this ever being called exists in this logs or console.

**Comment by mwbrooks** [comment]
Hi @Mark-Renzi 👋🏻 

Thanks for reaching out and writing a detailed message for us!

I believe you should be able to receive an event when an option is selected in an `external_select` or `multi_external_select`. I'll try to put together an example to better understand why you're not receiving the event.

In the meantime, can you confirm that you've setup your **Request URL** to receive the events? I assume that you have, since you've clearly setup your **Optionals Load URL**. I'd also suggest that you try to use your `action_id` directly (unless `"column" is the action_id), rather than using a regex, in case that is causing issues.

**Comment by Mark-Renzi** [comment]
Thanks for the reply! Just confirmed that my Request URL is correctly configured.  I tried changing my external_select to a multi_external_select with a max selected options to one, and was still unable to receive the event for selecting an option.  

I had used a regex for receiving the event as my modal can have any number of these and will add numbers to the extra fields, but that's out of scope for the issue here.  I can confirm that column is the correct action id and using the string itself did not work either.

I am able to get events for button presses from the same modal just fine, is there something else I could be missing here?  Wouldn't bolt print a message in console telling me there was an unhandled event if I was receiving it or is that behavior reserved for events that require an ack?  Possibly there is a scope or an event subscription I am missing?

Thanks for the help,
Mark.

**Comment by mwbrooks** [comment]
Hey @Mark-Renzi,

Just looping back quickly for you! You may want to try to add the `"dispatch_action": true` setting to your `multi_external_select` block to enable block actions to be dispatched. It can be easy to overlook and [here is a link to the `dispatch_action` documentation](https://api.slack.com/reference/block-kit/blocks#input_fields).

You can see under the [timing of payload dispatch docs](https://api.slack.com/reference/interaction-payloads/block-actions#payload_timing) the the mutli-select payload is dispatched "Each time an item is chosen from the multi-select menu."

Please give that a shot and let me know how it goes!

Each time an item is chosen from the multi-select menu.
--
 

<br class="Apple-interchange-newline">

Each time an item is chosen from the multi-select menu.
--
 

<br class="Apple-interchange-newline">

**Comment by Mark-Renzi** [comment]
Ah, thank you.  I didn't have that enabled.  I've looked at that page so many times it's a shame I missed it.  Thanks so much for your help.

**Comment by mwbrooks** [comment]
@Mark-Renzi No problem, you and I both overlooked it. All of the credit goes to @seratch for nudging me in the right direction 🎉
