### ISSUE TITLE
Event Subscriptions "app_mention"does not work when combined with file share

### ISSUE THREAD

**Issue by Chlorine628** [slackapi/bolt-python#925]
#### The `slack_bolt` version

slack-bolt         1.18.0

#### Python runtime version

Python 3.10.5

#### OS info

docker image python:alpine

#### Steps to reproduce:

1. Click share file button which is next to the download button (you could chose any file that is already uploaded to slack)
2. 
<img width="382" alt="1" src="https://github.com/slackapi/bolt-python/assets/72976941/5657bf5d-303a-4dd5-96d7-32d36f45716d">

3. Choose a random **channel**  that the app is already invited  to send message
4. In the message text box, input for example
`@displayname_of_my_app   some kind of message`
5. click forward 

### Expected result:

Since this message mentions the app, it should receive a message in `@app.event('app_mention')`

### Actual result:

It only receives a message in `@app.event("message")`

### Additional info

If I edit the message which is sent above, it will receive a meesage in `@app.event('app_mention')`

**Comment by Chlorine628** [comment]
I just found out that this happen not only when sharing file that is already uploaded to slack, but it also happen when new file is uploaded to slack.
I tried downgrading slack-bolt but it still occurs.
I come feel this is not the problem with this bolt-python. It might be a bug related to upstream side.

**Comment by seratch** [comment]
Hi @Chlorine628, thanks for writing in!

I tried to reproduce your issue on my end, but unfortunately, I wasn't able to encounter the same problem. On my side, the `app_mention` events were delivered correctly. It seems that there might be some differences on your end, but currently, I don't have any ideas or suggestions to offer.

**Comment by Chlorine628** [comment]
Thank you for replying.

When I looked into this furthermore, it seems that slack_bolt is not the fault.

I found out that when attaching a file, payload["text"] is overwritten by 'このメッセージにはインタラクティブ要素が含まれます。'(←I'm using Japanese. In English, it means  "This message includes interactive components"). 
Since payload["text"] does not include a mention, @app.event('app_mention') did not receive anything.

This bug begun to occur from July 1. Before that, it was working fine. I also found that this bug only happens to some people (not all the member in my workspace).  

The notification from slack app(iphone) also shows 'このメッセージにはインタラクティブ要素が含まれます。' when somebody sends an image to slack.
![1](https://github.com/slackapi/bolt-python/assets/72976941/6189e254-83d3-4e88-85a4-c47abe6ee4f9)


I think this is a problem with slack itself.
Maybe I should contact elsewhere.

**Comment by Chlorine628** [comment]
Slack appears to have fixed this issue.
