### ISSUE TITLE
ascii art in radio button block options causes incorrect selection 

### ISSUE THREAD

**Issue by henrieglesorotos** [slackapi/bolt-python#928]
### Reproducible in:

slack-sdk==3.19.5
Python 3.10.4
ProductName:            macOS
ProductVersion:         13.3.1
ProductVersionExtra:    (a)
BuildVersion:           22E772610a

**This only happens on desktop, not on mobile!**

#### Steps to reproduce:

Calling the following method to send as DM:

```
client.chat_postMessage(channel=slack_id, blocks=message, 
                                         text="New Question!", 
                                         metadata={"event_type": "question_asked", 
                                                   "event_payload": { "expert_id": expert_id, 
                                                                     "task_id": task_id}})
```
where the blocks come from json as such:
```
[
  {
    "type": "section",
    "text": {
      "type": "mrkdwn",
      "text": null
    },
    "accessory": {
      "type": "radio_buttons",
      "options": [
        {
          "text": {
            "type": "plain_text",
            "text": "Matching concepts",
            "emoji": true
          },
          "value": "value-0"
        },
        {
          "text": {
            "type": "plain_text",
            "text": "Closely related concepts",
            "emoji": true
          },
          "value": "value-1"
        },
        {
          "text": {
            "type": "plain_text",
            "text": "Concept 1 is more general than 2",
            "emoji": true
          },
          "value": "value-2"
        },
        {
          "text": {
            "type": "plain_text",
            "text": "Concept 1 is more specific than 2",
            "emoji": true
          },
          "value": "value-3"
        },
        {
          "text": {
            "type": "plain_text",
            "text": "Unrelated concepts",
            "emoji": true 
          },
          "value": "value-4"
        },
        {
          "text": {
            "type": "plain_text",
            "text": "\u00af\\_(\u30c4)_/\u00af",
            "emoji": true
          },
          "value": "value-5"
        }
      ],
      "action_id": "radio_buttons-action"
    }
  }
]
```
Notice the `"\u00af\\_(\u30c4)_/\u00af",` value which is shrug ascii art.

### Expected result:

When clicked, all options are selected as per the cursor. 

### Actual result:

When I use the ascii art, the bottom 3 options all default to the bottom shrug. The ascii art seems to interfere with the other options. Whicever I click of the bottom 3 options, it always selects the shrug. When I change this to `:shrug:` emoji it works as expected. 

<img width="453" alt="image" src="https://github.com/slackapi/bolt-python/assets/45067240/61e8e76c-d4b4-4a2e-a526-ca3030fa83a3">

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by zimeg** [comment]
Hi @henrieglesorotos! 👋  Thanks for sharing snippets for replicating the problem!

When testing this myself, I found that all of these selections seem to behave as expected when clicked – causing a `radio_buttons-action` block action payload to be sent with information about the selection for both desktop and mobile.

<img width="511" alt="quizz" src="https://github.com/slackapi/bolt-python/assets/18134219/216b5c7b-b1d5-46fc-b506-8af7972a4b9a">

I'm not noticing anything strange in your snippets, but feel free to compare what you have with [this example](https://github.com/zimeg/slack-sandbox/blob/main/py.bolt.snaek/snippets/issue_928_shrug_quiz/proctor_quiz.py)! I did have to change the `null` text to a placeholder value and replace `true` with `True` to satisfy mrkdwn and Python types, but I don't think either of these would effect the selection behavior you're experiencing...

Let me know if incorrect selections are still happening after checking this! I'd be happy to explore this further if needed 😁

**Comment by henrieglesorotos** [comment]
Thanks for the reply @zimeg - really appreciate it. It's a weird one, I did have multiple people across my org reporting this, but not quite sure what was causing it. I have changed the options so it's no longer a problem - it's now an emoji shrug.
