### ISSUE TITLE
AsyncOAuthFlow- pass request/context to installation_store & state_store during flow

### ISSUE THREAD

**Issue by hila-linx** [slackapi/bolt-python#932]
(** It is written regrading AsyncOAuthFlow but also correct for the non-async oauth flow)

Currently when using AsyncOAuthFlow for installation flow of slack application, 
we have the ability to implement only the interface of AsyncInstallationStore and AsyncOAuthStateStore, to save the state & the installation.

Currently any context/state is not passed to the AsyncOAuthStateStore & AsyncInstallationStore calls, so it limits our ability to save extra internal context of our application, along side the application installation data.

in https://github.com/slackapi/bolt-python/blob/17e37661c144b75522c8a7911238be01c2707804/slack_bolt/oauth/async_oauth_flow.py

if we could change this:
```
 async def issue_new_state(self, request: AsyncBoltRequest) -> str:
        return await self.settings.state_store.async_issue()
```
to:
```
async def issue_new_state(self, request: AsyncBoltRequest) -> str:
        return await self.settings.state_store.async_issue(request=request)
```

and 
```
async def store_installation(self, request: AsyncBoltRequest, installation: Installation):
        # may raise BoltError
        await self.settings.installation_store.async_save(installation)

```
to:
```
async def store_installation(self, request: AsyncBoltRequest, installation: Installation):
        # may raise BoltError
        await self.settings.installation_store.async_save(installation, request=request)
```

This way we will be able to use the request query parameters, or the context values we can pass to AsyncSlackRequestHandler.handle
`async def handle(self, req: Request, addition_context_properties: Optional[Dict[str, Any]] = None) -> Response:`

*Example of use*
Let's say we have a platform and we have a customer that want to install our slack application, if the request is passed to our state/installation store, we will be able to have the information on the customer in the context and save the "slack installation" details along side to the customer identifier... otherwise - we need to implement this flow on our own and not use the awesome implementation of bolt.

### Category

* [x] **slack_bolt.App** and/or its core components
* [x] **slack_bolt.async_app.AsyncApp** and/or its core components
* [ ] Adapters in **slack_bolt.adapter**
* [ ] Others

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @hila-linx, thanks for writing in!

In your case, the `Installation` class accepts [a dict object named `custom_values`](https://github.com/slackapi/python-slack-sdk/blob/v3.21.3/slack_sdk/oauth/installation_store/models/installation.py#L158). Therefore, the recommended approach to achieve your goal is to have your custom OAuth flow class inherit the `AsyncOAuthFlow` class and override the `store_installation` method. With this way, you can configure `custom_values` before calling the installation store's save method using [the setter method](https://github.com/slackapi/python-slack-sdk/blob/v3.21.3/slack_sdk/oauth/installation_store/models/installation.py#L178C9-L182)

Altering the installation store's method signature to include a request object could result in breaking changes to many existing code across the world. So, we are unable to implement this change at least in the short term. Please consider following the suggestion provided above.

I hope this helps.

**Comment by hila-linx** [comment]
Thanks @seratch , I'll try this out.
