### ISSUE TITLE
Deployment of SocketModeHandler on AWS

### ISSUE THREAD

**Issue by muhammad-ahsan099** [slackapi/bolt-python#933]
I am facing challenges with deploying a Slack SocketModeHandler application on AWS. I have developed a Slack bot using SocketModeHandler and it works well in my local environment. However, I am unsure about the steps and configuration required to deploy it on AWS.

I have explored various resources and documentation, but I haven't found a clear guide specifically addressing the deployment of SocketModeHandler on AWS. I am seeking assistance from the community to help me understand the necessary steps, best practices, and potential challenges associated with deploying SocketModeHandler on AWS.

Any guidance, suggestions, or resources related to deploying SocketModeHandler on AWS would be greatly appreciated. Thank you in advance for your support!

**Comment by seratch** [comment]
Hi @muhammad-ahsan099, thanks for asking the question! 

As you know, AWS offers a lot of services, which can be used for deploying Slack apps. When you use SocketMode for running your apps, I recommend going with any of the following:
1. Build a Docker image of your app and deploy it to:
- ECS
- EKS
- Lightsail Containers

These services require your running container process to respond to healthcheck HTTP requests. Thus, adding a web framework to your app and simply serving the endpoint for heathcheck [like this](https://github.com/slackapi/bolt-examples-aws-re-invent-2020/blob/main/lightsail-containers/python/main.py#L20-L22) should be necessary. Also, you can follow their standard way to configure env variables to pass.

2. If you want to avoid using container services, you may want to run your app on:
- Lightsail VCS
- EC2

Note that, as long as you use Socket Mode, AWS Lambda is not an option for it. You need to use any of AWS's solutions that allow you to run an always-running process somewhere.

I hope this helps.
