### ISSUE TITLE
Socket mode event listener for message.im events receiving message.group events

### ISSUE THREAD

**Issue by aursulich** [slackapi/bolt-python#936]
I am subscribed to both message.im events and message.group events. The listener in my code which listens for im events is suddenly receiving group events.

#### The `slack_bolt` version

slack-bolt==1.17.2
slack-sdk==3.21.2

#### Python runtime version

3.9

#### OS info

For one app:
ProductName:		macOS
ProductVersion:		13.4
BuildVersion:		22F66
Darwin Kernel Version 22.5.0: Mon Apr 24 20:51:50 PDT 2023; root:xnu-8796.121.2~5/RELEASE_X86_64

The other two are running on a docker image that runs on Debian Buster-Slim.

#### Steps to reproduce:

Code for the relevant event listener:

```
@app.event({
    "type": "message",
    "channel_type": "im"}
)
def event_intake(event, say, ack):
    try:
        ack()
        handle_command(event, say)
```

1. Have 2+ Slack apps with identical code but different bot/app IDs, both members of the same private channel, both using the events API and subscribed to message.im and message.group events.
2. Configure a listener for message.im events.
3. Send a message in the private channel.

### Expected result:

Nothing, because the message in step 3 is not a message.im event.

### Actual result:

The message ends up in the message.im listener for all bots in the channel. In my case, since the bots log commands sent to them in that channel, this triggers a loop where each bot logs the logs of the other bots, quickly leading to rate limiting. (They are not reacting to their own messages in that channel, only the messages from the other bots.)

This did not happen before last week, and nothing in the code or configuration changed at that point: the event subscriptions, code, libraries (bolt, slack_sdk, or their dependencies), tokens, deploy configuration and deploy environments did not change. Most of them have been in place for months, working correctly. When I attempted to deploy last week, Slack threw an error indicating that one of the permissions (users.read I believe, which to my knowledge had been working previously) was no longer valid, and so I checked that the permission was in fact in place, and reinstalled the app to the workspace.

I spoke to Slack support about this, and they indicated that everything looked normal from their end. We confirmed from the logs that the events are correctly formed and marked as message.group. They're simply ending up in the wrong listener for some unknown reason. Here's an example of one of the group messages that ended up in that im listener:

```{'bot_id': 'REDACTED', 'type': 'message', 'text': 'Not a valid command', 'user': 'REDACTED', 'ts': '1689373707.748199', 'app_id': 'APP1', 'blocks': [{'type': 'rich_text', 'block_id': 'm/T', 'elements': [{'type': 'rich_text_section', 'elements': [{'type': 'text', 'text': 'Not a valid command: test message from CHANNEL'}]}]}], 'team': 'REDACTED', 'bot_profile': {'id': 'REDACTED', 'deleted': False, 'name': 'ccinfo-bolt', 'updated': 1655496113, 'app_id': 'APP1', 'icons': {'image_36': 'https://avatars.slack-edge.com/2022-06-02/3628126773873_746fda39589d70a55388_36.png', 'image_48': 'https://avatars.slack-edge.com/2022-06-02/3628126773873_746fda39589d70a55388_48.png', 'image_72': 'https://avatars.slack-edge.com/2022-06-02/3628126773873_746fda39589d70a55388_72.png'}, 'team_id': 'REDACTED'}, 'channel': 'REDACTED', 'event_ts': '1689373707.748199', 'channel_type': 'group'}```

And here's an example of the type of message that is supposed to end up in that listener, and does still end up there:

```{'client_msg_id': '3c0e5898-7d3e-4be4-b34a-fd4043285a2b', 'type': 'message', 'text': 'help', 'user': 'REDACTED', 'ts': '1689375042.101759', 'blocks': [{'type': 'rich_text', 'block_id': '5Mt', 'elements': [{'type': 'rich_text_section', 'elements': [{'type': 'text', 'text': 'help'}]}]}], 'team': 'REDACTED', 'channel': 'REDACTED', 'event_ts': '1689375042.101759', 'channel_type': 'im'}```

If possible, I'm hoping that at the very least, I can get some info on how these listeners work to indicate how this could be happening, because I am utterly stumped.

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @aursulich, thanks for writing in.

>`@app.event({"type": "message", "channel_type": "im"})`

The 'channel_type' property has never been supported in bolt-python. So, I believe the filtering has never worked.

Instead, I recommend that you write your own listener middleware/matcher to select the message event types to which you want to respond. For more details, see https://slack.dev/bolt-python/concepts#listener-middleware.

I hope this helps.

**Comment by aursulich** [comment]
That's very unusual, because it definitely did work for a period of at least 2 months. So now I'm concerned that the event listener filtering is not working the way it's designed to work.

The filtering in the code I shared above was an important part of the setup, and since the channel_type property isn't a documented option in the filters (apparently because it isn't supported), it was tested carefully to ensure that it worked as a filter before I put it into production. Obviously I can't exactly provide proof, so you'd have to take my word for it, but for months it worked with the setup above, and then two weeks ago there was suddenly chaos.

Additionally, all the bots are present in more than one private channel, and so if the listener is working as it was designed to work, it sounds like that listener should be receiving events from all of those private channels. It isn't: it's only receiving them from the logging channel.

It might sound like I'm just being a dog with a bone here, but this is concerning to me. If I can't trust that the listeners are going to behave as they're designed to when I test them, how am I supposed to verify that my code is correct? I don't want to run into another situation down the line where something appears to be working when I test it, and then goes berserk months later for no apparent reason.

Do you have any theories that could explain the discrepancy between the way it's intended to work and the way it was working in my case? I am of course going to write the middleware as you suggest, but it sounds like there may be some other rogue variable causing the filters to work in a way they're not designed to work, and I'd like to try to squash it. I'm looking into the possibility of some kind of change in the docker image I deployed with (though I'm not hopeful that it will pan out), but I'd appreciate any guidance you could provide.

**Comment by seratch** [comment]
Hi, thank you for your detailed reply. I'm sorry to hear that you had a challenging development experience. Let me do my best to address your concerns and provide some solutions.

>I'm concerned that the event listener filtering is not working the way it's designed to work

I understand that this may seem confusing, but the constraints for `app.event` handlers have consistently accepted only `type` (plus `subtype` only for `type: message`) from the beginning, and this is still true today. Please check these lines of code in the framework: https://github.com/slackapi/bolt-python/blob/v1.18.0/slack_bolt/listener_matcher/builtins.py#L103-L114. These lines check `type` and `subtype` only, and all other dict keys are ignored.

To prevent confusion like yours in the future, we may add a warning message to inform developers if they pass unsupported keys like "channel_type" when registering an `app.event` listener, and that these will not be used. I understand this might be frustrating, but this is the current behavior of the framework.

>Do you have any theories that could explain the discrepancy between the way it's intended to work and the way it was working in my case?

One possible explanation for the behavior change in your app might be modifications to the app configuration. If you (or a collaborator) recently added message event subscriptions for private channels and/or included the `groups:history` scope, the app can start receiving private channel message events as well. If that's the case (please note, I'm aware that you're observing the situation differently), this means that your app, which previously didn't receive private channel events, now receives messages from both DMs and private channels. Again, I know this may not be your case, but this is the only pattern that I can think of.

Lastly, while bolt-python plans to add a unit testing framework in the future, it isn't available as of now. Therefore, manually testing your app in a Slack workspace is currently the only way to verify that there are no bugs in your app. We will continue to explore ways to improve the developer experience with the framework.

I hope these answers are helpful to you in some way.

**Comment by aursulich** [comment]
I understand that only type and subtype are checked in the listener. That's not confusing. What's confusing is that that's not how my app has been behaving. I _did_ add the private channels message event subscription--two months ago.

About the only explanation that I can think of is that there was some bug on the Slack API side that removed the groups:history scope very shortly after I finished testing and pushed out the change that used it. (I didn't remove the scope, and nobody else has access to it.) The team that uses that feature has coincidentally had a slow enough couple of months that they may not have noticed it was down. Then when I pushed my most recent change, it complained about a missing users:read scope (either because when Slack [rolled their change](https://api.slack.com/automation/changelog#v2-5-1) to fix a bug with uninstalling apps it messed with the permissions, or because we hadn't needed that scope much before then), so I reinstalled the app to the workspace with no settings changes--thus adding the groups:history scope back in.

As an explanation I hate it, because it requires so many coincidences (and because it's unclear how I could've caught it under the circumstances), but it's about the only thing I can think of that comes close to fitting all the facts.

**Comment by seratch** [comment]
Thanks for your reply. As an SDK maintainer, I wanted to clarify how bolt-python's `app.event` constraints function, and it seems that we are now on the same page for it. 

As for your app's behavior, it is not an SDK specific issue and it could be influenced by other factors such as the history of changes made to your app's configuration. Since this public issue tracker is dedicated to the Python SDK, we are unable to assist you further with this investigation. That being said, our customer support team might be able to help by examining the changes and their timing in your app, among other things. Sorry for bothering you again but require further assistance, please contact the team either via `/feedback` in your Slack workspace or through https://my.slack.com/help/requests/new I'd appreciate your understanding on this matter. Consequently, I will now close this issue here.
