### ISSUE TITLE
How to save custom `user_info` in `InstallationStore`?

### ISSUE THREAD

**Issue by akshatdalton** [slackapi/bolt-python#940]
I would like to save custom information (`user_info`) of the performing user, which is retrieved from my organization's database, when the `save` method of `InstallationStore` is called. Currently, I am aware that I can use the `set_custom_value` function of the `InstallationStore` to set my custom data. However, I have encountered a challenge: there seems to be no straightforward way to pass the custom user information when I receive my FastAPI request.

Here is the existing method signature of `save` in the `InstallationStore`:

```python
def save(self, installation: Installation):
    """Saves an installation data"""
```

I have explored using callback functions to handle this situation, but it appears that there is no built-in mechanism to pass custom user information to the `save` method.

Could you please provide guidance on how I can save the custom `user_info` along with the installation data when invoking the `save` method? Is there an alternative approach or best practice to achieve this given the constraints?

Thank you for your assistance!

**Comment by seratch** [comment]
Hi @akshatdalton, thanks for asking the question! You can customize the save method behavior on the `OAuthFlow` by inheriting the class plus overriding its `store_installation` method. Refer to https://github.com/slackapi/bolt-python/issues/932#issuecomment-1635183350 for details.

**Comment by akshatdalton** [comment]
@seratch probably I was not able to explain my issue properly; here is my sudo code where I want to use my custom `user_info` when I receive the request:
```.py
from slack_bolt import App as SlackApp
from slack_bolt.adapter.fastapi import SlackRequestHandler
from slack_bolt.oauth.oauth_settings import OAuthSettings
from slack_sdk.oauth import InstallationStore

class CustomInstallationStore(InstallationStore):
    def save(self, installation):
        # Use `user_info` received in the request to save the installation data (by setting in the `custom_value`)
        ...


custom_installation_store = CustomInstallationStore()

slack_app = SlackApp(
    name="MyBot",
    raise_error_for_unhandled_request=True,
    signing_secret=SLACK_APP_SIGNING_SECRET,
    installation_store=custom_installation_store,
    oauth_settings=oauth_settings,
)

slack_request_handler = SlackRequestHandler(slack_app)

@app.post("/v1/slack/token", operation_id="SlackStoreToken", tags=["Slack"])
async def slack_store_token(slack_oauth_request: SlackOAuthRequestModel, request: Request, _: bool = Depends(authenticate)):
    user_info = slack_oauth_request.user_info
    # somehow make this `user_info` get it used inside the `installation_store.save` method
    return await slack_request_handler.handle(request)
```

**Comment by seratch** [comment]
@akshatdalton Thanks for sharing more details. I am still trying to understand how and when `/v1/slack/token` can be used. If that's part of the OAuth installation flow, users.info API can be called only after performing oauth.v2.access API on your server-side (please check the OAuthFlow code to learn how it actually works). So, it's not feasible to bind full user data when receiving a user access request.

**Comment by akshatdalton** [comment]
@seratch Basically frontend calls this API with `code` and `state` values present inside this `SlackOAuthRequestModel` - this backend API is called after the frontend gets the `code` and `state` values from Slack (redirect URL), that said, OAuth installation flow happens at frontend and the final retrieving and storing of `bot_token` and other info is done at backend on this API.

It seems that I need to directly call oauth.v2.access API from my backend and perform other stuff that I want to do.

If you have any other suggestions (or examples) that how other orgs associate slack installation data with performing user's info in their database then please do give them.

**Comment by seratch** [comment]
@akshatdalton, I suggest you examine what `OAuthFlow` accomplishes before proceeding with your custom implementation: https://github.com/slackapi/bolt-python/blob/main/slack_bolt/oauth/oauth_flow.py

It's fine to execute an `oauth.v2.access` API call with the code parameter on the backend side. However, before doing so, your frontend service should verify the validity of the state parameter (or the frontend relays both query string and cookies to backend). We recommend storing the state parameter in the web browser cookies and confirming that the query string one and the cookie one match on the redirect URL side. If this step is skipped, the state parameter will not provide adequate security against OAuth CSRF attacks: https://auth0.com/docs/secure/attack-protection/state-parameters

I hope this explanation clarifies the issue. I'll be closing this issue now, but if you have any further questions, feel free to ask.

**Comment by akshatdalton** [comment]
Thanks for all the help @seratch, now I'm thinking to leave the python slack bolt default implementation for routes (one given in the `examples`) as it is and I can override `OAuthFlow`'s `store_installation` method:
```.py
def store_installation(self, request: BoltRequest, installation: Installation):
    ...
```

Here I believe, I can save the `installation` data along with `user_info` extracted from the `request` body.

**Comment by seratch** [comment]
@akshatdalton No, the request is a web browser access during the OAuth flow. Thus, it does not provide any user information. You need to perform an additional web API call (users.info) to fetch full user data as necessary. I'd recommend doing a quick prototype to see how it works. Please feel free to write in when you have different questions after doing so.

**Comment by akshatdalton** [comment]
@seratch Sorry for pinging you again but I feel you are confusing the users.info with that of [Slack web API call](https://api.slack.com/methods/users.info) - I'm not talking about that, in my case, this user info is the data of the user associated with my org.

I want a similar integration flow to that of AWS Chatbot with Slack.

Consider the following flow:

- authenticated user comes to my org's platform and clicks on the `Add to Slack` button
- user grants the permission 
- user is now at the `redirect_url` (with `code` and `state`)
- since the user was authenticated all this time, now I can make a request to the backend route: `/v1/slack/token` with `state`, `code`, `user_info` (related to my org) (and yes along with the cookie)
- in the backend, I can start my `CustomOAuthFlow` (with `store_installation(self, request: BoltRequest, installation: Installation)` overridden) where I can save the `installation` data along with the `user_info` (related to my org) to my DB.

If you have any other suggestions then please do suggest and yes I'll try this prototype.

**Comment by seratch** [comment]
@akshatdalton Ah, I see. In this case, I don't have anything else to suggest. Associating your service's use data with Slack app installation should work as you expect. Keep it up!
