### ISSUE TITLE
plain_text_input in Messages, how to get content?

### ISSUE THREAD

**Issue by chengyjonathan** [slackapi/bolt-python#942]
Hi there, I'm trying to use the plain_text_input block in messages (not a modal)

```
input_block = {
        "type": "input",
        "element": {
            "type": "plain_text_input",
            "multiline": True,
            "action_id": f"{fn_name}",
            "initial_value": f"{initial_value}",
        },
        "label": {"type": "plain_text", "text": f"{label_text}", "emoji": True},
    }
```

I'm able to get a text input box to appear. But I can't find any guides on how to handle that user input.

Any suggestions? Thank you.

**Comment by chengyjonathan** [comment]
Namely, after a user writes some input. How do I retrieve that input?

**Comment by chengyjonathan** [comment]
I found that the dispatch_action_config param, but upon pressing "enter," nothing happens

**Comment by seratch** [comment]
Hi @chengyjonathan, thanks for asking the question! Could you double-check if you've configured **Request URL** for **Interactivity & Shortcuts** section in the app configuration page? If you're using Socket Mode, just enabling the Interactivity feature should work for you.

**Comment by chengyjonathan** [comment]
Yes, I have. Other modes of interactivity work. (ie. buttons, etc)

**Comment by chengyjonathan** [comment]
I essentially have the following setup

```
input_block = {
        "type": "input",
        "element": {
            "type": "plain_text_input",
            "multiline": True,
            "max_length": 500,
            "action_id": f"{fn_name}",
            "placeholder": f"{initial_value}",
            "dispatch_action_config": {"trigger_actions_on": ["on_enter_pressed"]},
        },
        "label": {"type": "plain_text", "text": f"{label_text}", "emoji": True},
    }

@slack_app.action("fn_name")
def fn_name(ack, say, payload):
    ack()
    print(payload)
```

**Comment by chengyjonathan** [comment]
This produces the text box for input, but I can't find the documentation that would receive/handle any input text by the user.

Note: I'm not using a modal, just using Messages

**Comment by chengyjonathan** [comment]
I'm not sure if this is the right way to implement handling plain_text_input.

And I cannot find the right documentation anywhere. (Most of it pertains to Modals)

Any help is greatly appreciated

**Comment by seratch** [comment]
@chengyjonathan

**Comment by seratch** [comment]
@chengyjonathan Your code does not have `"dispatch_action": True` in the block, and that is the cause of its misbehavior. The following code works for me.

```python
@app.event("app_mention")
def handle_app_mentions(say):
    say(
        {
            "text": "Testing dispatch_action_config",
            "blocks": [
                {
                    "type": "input",
                    "dispatch_action": True,
                    "label": {"type": "plain_text", "text": "Label"},
                    "element": {
                        "type": "plain_text_input",
                        "multiline": True,
                        "max_length": 500,
                        "action_id": "some_action_id",
                        "dispatch_action_config": {
                            "trigger_actions_on": [
                                "on_enter_pressed",
                            ]
                        },
                    },
                }
            ],
        }
    )


@app.action("some_action_id")
def handle_action(body, ack, logger):
    logger.info(body)
    ack()
```

**Comment by chengyjonathan** [comment]
Oh I see! Thank you.

I'll try that today and close this if it works.

One followup question. Is there a way to send additional metadata to the handle_action fn?

I've done this for buttons by packing stuff in the "value" field. But idk if there's a way to do this for plain_text_inputs as well.

Thank you, again!

**Comment by chengyjonathan** [comment]
Alternatively, is there a way to pair plain_text_inputs with a submit button where, I can pass that value field?
