### ISSUE TITLE
Message ID correspondence for analysing reactions added to bot's message

### ISSUE THREAD

**Issue by JoselinSushma** [slackapi/bolt-python#943]
I have create a slack bot to respond based on knowledge base. when user is happy with the answer they might react to the message. I understand to handle it via `reaction_added` event. 
When handling a query, bot generates a response and i store both in sqlite. when user reacts to it with a thumbs up or thumbs down i couldn relate it with the record in my db 
Any suggestion would be of great help 
Thanks

**Comment by seratch** [comment]
Hi @JoselinSushma, thanks for asking the question.

As you mentioned, saving user feedback about the response when receiving a 'reaction_added' event is a great approach. You can update your app settings to subscribe to the event and include an `@app.event("reaction_added")` listener in your app to handle it.

Another approach is to use buttons, as shown below. Here is [a Block Kit Builder link that demonstrates this](https://app.slack.com/block-kit-builder/#%7B%22blocks%22:%5B%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22Here%20is%20an%20answer%20for%20your%20question%20....%22%7D%7D,%7B%22type%22:%22context%22,%22elements%22:%5B%7B%22type%22:%22plain_text%22,%22text%22:%22Did%20you%20like%20this%20response?%22%7D%5D%7D,%7B%22type%22:%22actions%22,%22elements%22:%5B%7B%22type%22:%22button%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22:+1:%22%7D,%22value%22:%22up%22,%22action_id%22:%22up%22%7D,%7B%22type%22:%22button%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22:-1:%22%7D,%22value%22:%22down%22,%22action_id%22:%22down%22%7D%5D%7D%5D%7D). Your app can handle these patterns by including two listeners such as `@app.action("up")` and `@app.action("down")`.
<img width="400" src="https://github.com/slackapi/bolt-python/assets/19658/ae7baf4d-6be4-42c3-b954-3e12cf7b8bdd">

I hope this was helpful to you!

**Comment by JoselinSushma** [comment]
Thank you for the response , 
I am storing the query and bot's response in db. when reactions are added to a particular message is there a way by means of some identifier to relate with the record in my db ?
Please let me know if my question lacks clarity

**Comment by seratch** [comment]
The event payload provides sufficient data for it. If you have a more specific question after checking the actual data, please feel free to ask here.
