### ISSUE TITLE
Slack socket connection stops working after sometime.

### ISSUE THREAD

**Issue by saksham-apt** [slackapi/bolt-python#945]
### Reproducible in:

```
[root@shield share]# pip freeze | grep slack
slack-bolt==1.16.2
slack-sdk==3.19.5
[root@shield share]# python --version
Python 3.9.6
[root@shield share]# uname -v
#1 SMP Wed Mar 13 12:02:46 UTC 2019
```
### Expected result:

I have a slack message block that consists of a button. On clicking it, it should perform the tasks specified in the function.

### Actual result:

The button works fine for sometime after which it stops working.  The logs show this:
```
Aug 08 10:45:08 shield.ndc.aptportfolio.com bash[7817]: [2023-08-08 05:15:08,028: INFO/ForkPoolWorker-62] Task ipa_bridge.tasks.revokeExpiredPermissions[8d96d2ac-e23f-4031-86a5-b4d45c6117c4] succeeded in 0.0029109492897987366s: None
Aug 08 10:49:35 shield.ndc.aptportfolio.com bash[7817]: [2023-08-08 05:19:35,283: WARNING/ForkPoolWorker-62] Unhandled request ({'type': 'block_actions', 'block_id': 'tjT=F', 'action_id': 'accept'})
Aug 08 10:49:35 shield.ndc.aptportfolio.com bash[7817]: ---
Aug 08 10:49:35 shield.ndc.aptportfolio.com bash[7817]: [Suggestion] You can handle this type of event with the following listener function:
Aug 08 10:49:35 shield.ndc.aptportfolio.com bash[7817]: @app.action("accept")
Aug 08 10:49:35 shield.ndc.aptportfolio.com bash[7817]: def handle_some_action(ack, body, logger):
Aug 08 10:49:35 shield.ndc.aptportfolio.com bash[7817]:     ack()
Aug 08 10:49:35 shield.ndc.aptportfolio.com bash[7817]:     logger.info(body)
Aug 08 10:49:35 shield.ndc.aptportfolio.com bash[7817]: [2023-08-08 05:19:35,283: INFO/ForkPoolWorker-62] Unsuccessful Bolt execution result (status: 404, body: {"error": "unhandled request"})
```

Which is weird because the listener exists in the code, and on restart of celery-worker it starts working again. The code corresponding to the button is:

```
@slackSocket.action("accept")
def acceptRequest(ack, request):
    try:
        ack()
    except Exception as e:
        logger.error('Unable to acknowledge message: ' + e)
        reconnectSlackSocket()
    views.approvalRequestSlack(request.body)
```

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @saksham-apt, thank you for asking the question.

While I'm still trying to guess the exact cause of your problem, it appears that the issue might be related to how you're running and managing your apps. You mentioned using celery, but typically there's no need to use it for running Bolt apps. Such unusual setup or configuration on your part could be leading to the unexpected behavior you're experiencing.

In general, a simpler way to run a Bolt app should be much easier to operate. When you build and run a Docker image for it, you will never experience the same issue. If you need scalability, you can scale out the app (10 connections for Socket Mode, unlimited web app processes behind a public endpoint for Request URL). As long as you don't refresh your app process, the reported issue never happens. The Bolt framework does not do anything magical that can cause such a surprise.

I hope this helps.

**Comment by saksham-apt** [comment]
Hey @seratch , thanks for the quick response. What you have mentioned might be causing the issue, but the setup has been working for us for the past 6 months. It's from the past one week that we have started facing this issue. I'll try to move out the Bolt app out of Celery and see if it fixes the issue, but do you have any theory about why it stopped working suddenly without any changes from our end?

**Comment by seratch** [comment]
>do you have any theory about why it stopped working suddenly without any changes from our end?

Based on the information provided, I can't pinpoint a specific cause. The potential reasons could vary depending on how you manage your app. I hope you can figure the underlying issue out soon!

**Comment by saksham-apt** [comment]
@seratch Thanks, I have refactored the Slack bot out of Celery. I'm unable to find in the documentation what is the correct way to increase the number of connections. Here is my code currently:

```
    slackSocket = App(token=settings.SLACK_SOCK_TOKEN)
    SocketModeHandler(slackSocket, settings.SLACK_SOCK_TOKEN,
                      ping_interval=1).connect()

    def reconnectSlackSocket():
        SocketModeHandler(slackSocket, settings.SLACK_SOCK_TOKEN,
                          ping_interval=1).connect()


    @slackSocket.action("accept")
    def acceptRequest(ack, request):
        try:
            ack()
        except Exception as e:
            logger.error('Unable to acknowledge message: ' + e)
            reconnectSlackSocket()
        views.approvalRequestSlack(request.body)
```

1. Am I doing something wrong here? Particulary the `reconnectSlackSocket` thing?
2. How can I spawn multiple connections for resiliency?
3. I'm also facing an issue where I need to click the button on slack multiple times before the acceptRequest function gets invoked.

Can you please help me with the same?

**Comment by saksham-apt** [comment]
Hey @seratch thanks for the detailed explanation. Using `start()` function instead of `connect()` blocks my Django application. Is that expected behaviour? If so, how are we supposed to handle it? Should I configure my Gunicorn such that some workers run the application itself and some workers run the slack socket connection only or ideally the slack socket should run independently without anything else?

**Comment by seratch** [comment]
@saksham-apt Ah, I see. In this case, indeed you can call `connect()` method instead to avoid blocking the currently executed thread. Also, you can call the `connect()` method in Django's startup hook. According to the following starckoverflow, the framework has been providing the feature for a long time: 
* https://stackoverflow.com/a/16111968/840108
* https://docs.djangoproject.com/en/4.2/ref/applications/#django.apps.AppConfig.ready

Gunicorn's server hooks (https://docs.gunicorn.org/en/stable/settings.html#on-starting) are also an option but managing all the things inside Django app project structure should be easier to maintain in the long run.

I hope this helps. Since we are not Django experts, if you have further questions on Django, please post them in the Django forum or stackoverflow instead. If everything on the bolt-python side is clear now, would you mind closing this issue?

**Comment by seratch** [comment]
Also, it's important to highlight that Socket Mode permits a maximum of 10 connections. If you integrate the Socket Mode handler initialization into the Django app's startup process, this limitation will restrict you from scaling your Django app beyond 10 instances. Should this become a potential constraint, I'd recommend considering the deployment of the Socket Mode process separately from your primary Django app.

**Comment by saksham-apt** [comment]
Thanks, closing this issue.
