### ISSUE TITLE
Identifying a bot's message in @app.event("message")

### ISSUE THREAD

**Issue by YuPeiHenry** [slackapi/bolt-python#946]
How can I reliably identify a bot message? I want to prevent the bot from responding to itself. Some methods that I currently use:
* Look for "bot_id" in event
* Save the timestamp whenever the bot sends a message, and ignore message events with the exact timestamp.
* Check the user_id in event (not preferred as it is different for each workspace installation).

Second question. Why does the bot not receive its own messages in the internal workspace but receives it in the external workspace?
Follow up question to second question: If the current 2 token for 2 workspace setup is not appropriate, how should I change the configuration? It is a single server meant for multiple workspaces.

#### The `slack_bolt` version
slack-bolt==1.18.0
slack-sdk==3.21.3

#### Python runtime version
Python 3.9.12

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1. Setup app in socket mode.
2. Install to organization workspace, run server using organization workspace bot token.
3. Activate public distribution and install to external workspace. Respond to messages using organization workspace/external workspace bot token through "https://slack.com/api/chat.postMessage".

### Truncated Logs in organization workspace:
received:
`{"token": ..., "ts": 1691679443.549739, 'event': {'client_msg_id':, 'type': 'message', 'text': 'test', 'user': ,...}}`
post response:
`{'ok': True, ... 'ts': '1691679444.825769, 'message': {'bot_id': , 'type': 'message', 'text': "response", 'user': , ...}}`

### Truncated Logs in external workspace:
received:
`{"token": ..., "ts": 1691679603.243649, 'event': {'client_msg_id':, 'type': 'message', 'text': 'test', 'user': ,...}}`
post response:
`{'ok': True, ... 'ts': '1691679662.924329, 'message': {'bot_id': , 'type': 'message', 'text': "response", 'user': , ...}}`
received:
`{"token": ..., "ts": 1691679662.924329, 'event': {'bot_id':, 'type': 'message', 'text': 'response', 'user': ,...}}`

**Comment by seratch** [comment]
Hi @YuPeiHenry, sorry for our slow response here. 

>How can I reliably identify a bot message? 

You can check if subtype: bot_message exists in the payload. Also, as you mentioned checking if bot_id exists is a good way to go.

>Second question. Why does the bot not receive its own messages in the internal workspace but receives it in the external workspace?

An app receives the same message event only once if the app is connected to several workspaces. As long as the message is identical in a Slack Connect channel, your app receives an event from any of the connected workspaces. If you want to know the list of workspaces / authorized users associatd with an event, you can perform [apps.event.authorizations.list API](https://api.slack.com/methods/apps.event.authorizations.list) with an app-level token and an event_context string data. You will see both the "internal" and "external" workspaces in the response.

I hope this helps.

**Comment by YuPeiHenry** [comment]
Thanks @seratch , I have no further questions.
