### ISSUE TITLE
How to get query params from oauth/v2/authorize to the success handler

### ISSUE THREAD

**Issue by bhaktatejas922** [slackapi/bolt-python#948]
@seratch 

Recently explained that to get a query param from a /slack/install call to the authorize call you need to overload the handle_installation call like so 

`As previously mentioned, you can create a custom OAuthFlow class and override the OAuthFlow#handle_installation(request: BoltRequest) method. Once you've done this, you can then pass its instance during the App instance initialization. This approach will allow you to access any query parameters within the handle_installation(request) method.
`

**However, I still don't understand how to get the query params I need to the success handler.** 
I see the params in the authorize call after following @seratch steps, but still not able to figure out how to get it from there to success handler
https://slack.com/oauth/v2/authorize?state=

**Comment by bhaktatejas922** [comment]
I'm not tied to using query params, I just need some sort of way of getting 2 strings from /slack/install all the way to the slack bolt success handler

**Comment by seratch** [comment]
Hi @bhaktatejas922, thanks for writing in.

>Do I need to add my info to the cookie?

If your goal is to transfer some data to your Redirect URL (`/slack/oauth_redirect` if you go with bolt-python's defeautl settings), yes you are right. Your app needs to set web browser cookies under your public domain. With that, your handler for Redirect URL can access the data by reading passed cookie data.

**Comment by bhaktatejas922** [comment]
got it. Felt like I was doing something overly complicated. Thanks for the help and the speedy response!
