### ISSUE TITLE
Socket Mode connect and listener function location

### ISSUE THREAD

**Issue by fwump38** [slackapi/bolt-python#949]
I've configured Django with Socket Mode and called the connect() method during app startup hook as mentioned here: https://github.com/slackapi/bolt-python/issues/945

I have several listeners in a different folder within the Django app but they don't seem to be working.

### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version

slack-bolt==1.18.0
slack-sdk==3.21.3

#### Python runtime version

Python 3.11.4

#### OS info

ProductName:            macOS
ProductVersion:         13.4.1
ProductVersionExtra:    (c)
BuildVersion:           22F770820d
Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103

#### Steps to reproduce:

1. Create simple Django project similer to: https://github.com/slackapi/bolt-python/tree/main/examples/django/simple_app
2. Configure the Slack app and the Django app to use Socket Mode
3. Configure Slack Bolt to connect during the startup hook for the Django App
4. Write listeners and move them to another folder

My project layout (simplified for point of example):
```
project_root\
    manage.py
    my_app\
        __init__.py
        apps.py
        slack.py
        listeners\
            __init__.py
            actions.py
```

- `apps.py` is Django specific and contains the startup hook to call `socket_mode_handler.connect()`
- `slack.py` is my code which instantiates `slack_bolt.App` as well as `SocketModeHandler` (I then import the instance of socket_mode_handler to `apps.py`)
- Within `actions.py` I've written functions decorated with `@app.action` to handle various events. This file imports the instance of `slack_bolt.App` from `slack.py`

It's not clear to me if I also need to configure the adapters for Django when using Socket Mode since the requests shouldn't actually hit an endpoint in Django and should instead use the Web Socket (a la https://slack.dev/bolt-python/concepts#socket-mode). I tried with the code for using the Django request adapters as well as not using them.

I know the folder structure with listeners worked before when I was using request URLs and had configured Django with `/slack/events` for example.

### Expected result:

The actions in Slack should trigger the listener functions with SocketMode

### Actual result:

The listeners never trigger so all actions are unhandled

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by mwbrooks** [comment]
Hi @fwump38 👋🏻 Thanks for the thoughtful detail added to your issue!

It sounds like you've already explored a lot of directions before reaching out!

I don't believe `listeners/` directory is a built-in Bolt Python convention, so the framework will not automatically import your listeners from the directory. Typically, I've seen projects [import and register the listeners in `apps.py`](https://github.com/slack-samples/bolt-python-news-api-for-slack/blob/main/app.py#L7-L8).

Are you import your listeners in `apps.py`? If not, you may want to try that or test it by defining a listening in `apps.py` to see if it's works.

**Comment by fwump38** [comment]
Well that seems a lot simpler than I expected! I don't know quite how it worked before without needing to import anything from `listeners/`

You're correct that it is not a Bolt convention..I did it because I wanted a way to organize the **many** functions I have to handle various interactive elements (not just actions.py but I also have events.py, middleware.py, options.py, utils.py, and views.py) to handle every aspect of the Slack app functionality).

Looking now I see that in my old Django code I had `project_root/my_app/views.py` (distinct from the `/listeners/views.py` as this was the `views.py` that Django uses) where I had the following code:

`from .listeners import *` and then in `/listeners/__init__.py` I had all the other methods from all the other modules imported. I assume this is how it "just worked" before.

I'll try something similar or directly importing into `apps.py`

**Comment by mwbrooks** [comment]
@fwump38 Thanks for the quick response and good luck trying something similar!

For what it's worth, while `listeners/` isn't an official Bolt convention, we strongly encourage that exact directory structure. We've found it keeps things organized for larger projects. So I'd recommend keeping it! 👌🏻

**Comment by fwump38** [comment]
Thanks. I tried importing the listener functions like suggested but I'm getting an error that the app isn't actually ready yet. The error is Django related and is mostly due to the fact that the listener functions involve Django models.

Since these are Django specific and not related to Slack Bolt anymore I'll go ahead and close this.

**Comment by mwbrooks** [comment]
Thanks @fwump38 - when you work out the Django issue, we'd appreciate it if you could share your solution here. I imagine there will be other Django developers in the future who will read your answer and deeply appreciate it!

**Comment by fwump38** [comment]
The solution I ended up figuring out was to include the listener functions in an import within the `def ready(self):` of Django App Config. Including it above where imports normally go resulted in an error `AppRegistryNotReady("Apps aren't loaded yet.")`

You can't import with a wildcard within a function though so I had to copy all of the functions from `/listeners/__init__.py` into the `ready()` function.

The resulting `apps.py` looked something like this (edited for brevity):

```
from django.apps import AppConfig

from .slack import socket_mode_handler


class SlackappConfig(AppConfig):
    default_auto_field = "django.db.models.BigAutoField"
    name = "slackapp"
    verbose_name = "SlackApp"

    def ready(self):
        # Actions
        from .listeners.actions import handle_edit_conversation  # noqa F401
        from .listeners.actions import handle_modmail_actions  # noqa F401
        ... (all the rest of the listener functions here)

        socket_mode_handler.connect()
```
