### ISSUE TITLE
Transfering ack_method response to async lazy methods

### ISSUE THREAD

**Issue by oxess** [slackapi/bolt-python#950]
Hi! I have a idea for little changes which add new possibilities. 
We can transfer to lazy function data from first sync function in the lazy runner. 

```python
# slack_bolt/listener/thread_runner.py
try:
    self.listener_start_handler.handle(
        request=request,
        response=response,
    )
    returned_value = listener.run_ack_function(request=request, response=response)
    request.body['returned_value_sync_function'] = returned_value # <---------------------------------
    if isinstance(returned_value, BoltResponse):
        response = returned_value
    if ack.response is None and listener.auto_acknowledgement:
        ack()  # automatic ack() call if the call is not yet done

```

Use case: 

When we need more time for processing somethink (like a lot of request to another API) then we can open modal and return modal view_id and modal hash in the first 3 seconds. In the next step process by async methods and update modal view.

```python 

app.action("count_holidays_request")(
    ack=handle_count_holidays_request_ack, 
    lazy=[handle_count_holidays_request]
)

def handle_count_holidays_request_ack(ack, shortcut, client, body):
    modal = Modal("Generowanie listy", "holidays_list_modal")
    r = client.views_open(
        trigger_id=body["trigger_id"],
        view=modal.slack_view(),
    )

    ack()

    return {"view_id": r["data"]["view_id"], "hash": r["data"]["hash"]} # <---------------------------

def handle_count_holidays_request(ack, shortcut, client, body):
    ack()
    requester_id = body["user"]["id"]
    (.... processing ....)

    client.views_update(
        view_id=body["returned_value_sync_function"]["id"], # <---------------------------
        hash=body["returned_value_sync_function"]["hash"], # <---------------------------
        view=template(holidays),
    )


```

### Category (place an `x` in each of the `[ ]`)

* [ ] **slack_bolt.App** and/or its core components
* [ ] **slack_bolt.async_app.AsyncApp** and/or its core components
* [ ] Adapters in **slack_bolt.adapter**
* [x] Others

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @oxess, thanks for writing in. Your idea is interesting! However, unfortunately it does not always work. 

The lazy listeners feature was introduced mainly for better supporting FaaS (Function-as-a-Service) use cases. You can read more about it here: https://slack.dev/bolt-python/concepts#lazy-listeners If you're not building with FaaS, you don't need to use lazy listeners. You can do whatever time-consuming tasks after calling `ack()` method in a listener.

In a FaaS environment, the ack function and lazy listeners run concurrently, but they are separate invocations of the AWS Lambda function. As such, they don't share memory and cannot directly pass data to each other. In other words, while your idea might work with the thread-based lazy listener runner, it does not for FaaS. For this reason, we won't enhance bolt-python like you suggested.

Alternatively, you might consider the following implementation idea to achive your goal:
1. Use a queue or a database table to store the data you wish to transfer from the ack method to the lazy listeners.
1. When the ack function opens a modal, save the view ID in the queue or database table.
1. Poll this queue or table in your lazy listeners, waiting for the expected view ID to appear.

I hope this provides a viable alternative for your use case. If all your questions have been answered, could you please close this issue?

**Comment by seratch** [comment]
Indeed, passing a simple string to lazy listener invocations might work, but I still hesitate to add such complexity. Also, with the current bolt-pyton design, a returned object can mean body data for an HTTP response.

**Comment by oxess** [comment]
I know. This is only proposal of feature, not production solution.
Maybe good validation of output and some architecture changes and this idea will be possible ;)

**Comment by seratch** [comment]
Yeah, thanks for sharing the idea. On another note, considering your specific use case, have you considered invoking both `views.open` and `views.update` APIs within the same lazy listener? There's no constraint preventing you from doing this, and it might simplify your workflow.

**Comment by oxess** [comment]
I'am working on add DynamoDB to the project and storage some information about workflow. 
I cannot open modal from lazy function because the request id is always expired :(

**Comment by oxess** [comment]
Sorry `trigger_id`

**Comment by seratch** [comment]
Hmm, if that's the case, a possible cause might be that your Lambda function experiences a somewhat lengthy cold-start time. As you may already know, loading slack-bolt and slack-sdk modules is quite fast, so these modules are not the source of cold-start issues. However, I am aware that some AWS SDKs (AFAIK, at least SSM and S3; you can refer to [this issue](https://github.com/slackapi/bolt-js/issues/816#issuecomment-786360926) for more details) can take a significant amount of time to initialize. I haven't verified if the DynamoDB SDK has similar issues. Such delays are problematic for Slack apps because the platform has rather strict timeout restrictions for `ack()` calls and `trigger_id` consumption. Let's say, if your cold-start time takes up to 1 second or similar, doubling that for both 'ack' and 'lazy' listener plus other overhead could easily exceed the 3-second limit.

If this is your case, you may want to consider running your app in a different platform such as ECS. Hope this could help.

**Comment by oxess** [comment]
Yeah this is problem with timeout restriction. I use a Notion API and JIRA API for collection information and show modal ;/ This is reason why I use a lazy function. I had add DynamoDB and I storing opened modal hash and view id - this solution works fine :)

**Comment by oxess** [comment]
I had use a AWS Code Guru, X-Trace and local tools for debugging problem with performance ... but this is problem with external API response ;( Slack bot and my workflow work quickly. I don't have a problem at this moment (DynamoDB solved a problem). Thx for your response :)

**Comment by seratch** [comment]
Great to hear that you've resolved th issue 👍
