### ISSUE TITLE
App becomes unresponsive when using Socket Mode after a while

### ISSUE THREAD

**Issue by samschroe** [slackapi/bolt-python#952]
Hey there. :wave: 
I have a Slack app that's using socket mode with bolt, like this:

```python
app = App(token=SLACK_BOT_TOKEN)
socket_mode_handler = SocketModeHandler(app, SLACK_APP_TOKEN, trace_enabled=True, logger=logger)
socket_mode_handler.connect()

@app.command("/ping_my_app")
def ping_my_app(ack, respond):
    logger.info("Detected ping slash command")
    ack()
    respond("Your app is up and running and received your ping!", response_type="ephemeral")

while True:
    time.sleep(1)
```

This works fine at first, but after a while (hours/days), I start getting the dreaded "dispatch_failed" error when running the slash command in Slack. I can see the SocketModeHandler still receiving the slash command data frames in its logs, but my log message "Detected ping slash command" is never logged. Am I using the SocketModeHandler incorrectly here?

One note: I'm using `SocketModeHandler.connect()` rather than `SocketModeHandler.start()` because my app has other, non-Slack functionality that I want to continue while the app runs, and my understanding is that `SocketModeHandler.start()` will block the program's execution.

#### The `slack_bolt` version

1.16.4

**Comment by zimeg** [comment]
Hey @samschroe! :wave:

Using `.connect()` instead of `.start()` to prevent blocking behavior seems correct and I don't immediately see a problem with the code you shared.

Since this is happening after a while of running fine, I'm wondering if you're creating other Socket Mode connections using this `SLACK_APP_TOKEN`? If so, [this comment](https://github.com/slackapi/bolt-js/issues/1151#issuecomment-940616159) explains why this may cause problems and offers a possible solution!

It's still interesting that your app is receiving the slash command pyaloads fine but not executing the command logic though... If the above doesn't seem relevant, please let me know and I'm happy to explore this more!

**Comment by samschroe** [comment]
Thanks for the reply @zimeg 

I don't believe I have any other active Socket Mode connections using that `SLACK_APP_TOKEN`.

For some more info, the last log line I see when the slash command returns "dispatch_failed" is: 
```
DEBUG:__main__:process_message: A message dequeued (current queue size: 0)
```

Whereas when the slash command works, I see a logline after that:
```
DEBUG:__main__:run_message_listeners: Message processing started (type: slash_commands, envelope_id: 3b07e8c9-6a88-4483-9c03-edac6610a94e
```
and then further loglines indicating a response is getting sent:
```
DEBUG:__main__:send_message: Sending a message ...
2023-08-31 04:26:37,970 DEBUG:__main__:send: Sending a text data frame ...
2023-08-31 04:26:37,970 DEBUG:__main__:send_response: Response time: 26 milliseconds
2023-08-31 04:26:37,970 DEBUG:__main__:run_message_listeners: Message processing completed (type: slash_commands, envelope_id: 3b07e8c9-6a88-4483-9c03-edac6610a94e)
```

From what I can tell, the data frame structure that's received when it works vs. when it doesn't looks exactly the same.

**Comment by seratch** [comment]
Hi @samschroe, it seems that the logs do not match with the code snippet you've shared in the description. Would it be possible to ask you to provide the latest and minimum-working example code to reproduce your issue?

**Comment by samschroe** [comment]
Hey @seratch, not sure what you mean that the logs don't match? Those are the logs from `SocketModeHandler` when I set `trace_enabled=True`.

My full code is doing something close to this:
```python
from github import Github
from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler
import logging

logger = logging.getLogger()
log_format_str = "%(asctime)s %(levelname)s:%(name)s:%(funcName)s: %(message)s"
formatter = logging.Formatter(log_format_str)
fh = RotatingFileHandler("C:\\release_poller.log", mode='a', maxBytes=10*1024*1024, backupCount=1)
fh.setFormatter(formatter)

logger.addHandler(fh)
logger.setLevel(logging.DEBUG)

GITHUB_ACCESS_TOKEN = "insert_token_here"
SLACK_BOT_TOKEN = "insert_token_here"
SLACK_APP_TOKEN = "insert_token_here"

app = App(token=SLACK_BOT_TOKEN)
socket_mode_handler = SocketModeHandler(app, SLACK_APP_TOKEN, trace_enabled=True, logger=logger)
socket_mode_handler.connect()

@app.command("/ping_my_app")
def ping_my_app(ack, respond):
    logger.info("Detected ping slash command")
    ack()
    respond("Your app is up and running and received your ping!", response_type="ephemeral")

g = Github(GITHUB_ACCESS_TOKEN)
bolt_repo = g.get_repo("slackapi/bolt-python")
prev_latest_release = bolt_repo.get_latest_release()

while True:
    latest_release = bolt_repo.get_latest_release()
    logger.info(f"Latest release is: {latest_release}")
    if latest_release > prev_latest_release:
        prev_latest_release = latest_release
        app.client.chat_postMessage(
            channel=1234567,
            text=f"Detected new release {latest_release}"
        )
    time.sleep(60)
```
