### ISSUE TITLE
How to run Socket Mode alongside Flask SocketIO?

### ISSUE THREAD

**Issue by chadlieberman-flywire** [slackapi/bolt-python#953]
I am attempting to make a chatbot available both within my web app and via a Slack bot. I have tested both separately and they work well. However, when I attempt to run them in different threads of the same application, I get an SSL error from Bolt

`ERROR:slack_bolt.App:on_error invoked (session id: b524fca5-51da-46cf-8817-6c71b133897a, error: SSLError, message: ('timed out',))`

I am running the Flask-SocketIO app in a daemon thread and starting the SocketModeHandler in the main thread. For the Flask-SocketIO app, I am using eventlet and monkey patching it.

### Reproducible in:

cryptography~=41.0
eventlet~=0.33
flask~=2.2
Flask-SocketIO~=5.3.0
#langchain~=0.0
langchain==0.0.266
looker-sdk~=23.10
openai~=0.27
opentelemetry-distro==0.38b0
pandas~=2.0.0
pylint==2.13.9
pyarrow~=12.0.0
scikit-learn~=1.3.0
sentry-sdk[flask]~=1.0
setuptools-lint==0.6.0
slack-bolt~=1.0
tiktoken~=0.4.0

#### The `slack_bolt` version

slack-bolt==1.18.0

#### Python runtime version

Python 3.10.13

#### OS info

Running Debian GNU/Linux 11 (bullseye) in a Docker container.

#### Steps to reproduce:

Unfortunately, I can't share source code. But, start a Flask-SocketIO app in a background thread and then call Slack SocketModeHandler#start() method. Observe SSL error.

### Expected result:

There to be no SSL error, and the Bolt handler connects properly.

### Actual result:

The SocketModeHandler#start() method fails. The above error message is printed several times over. The app does not respond to mentions in Slack.

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by chadlieberman-flywire** [comment]
I've tried switching to gevent, but ran into the same issue. I'm not sure where else to look. Any guidance or pointers is appreciated! Thank you.

**Comment by chadlieberman-flywire** [comment]
I got slightly more information now on the error
`ERROR:slack_bolt.App:on_error invoked (session id: 1772e3df-7622-4151-96d9-f6fec3ff2759, error: SSLError, message: ('timed out',))
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/slack_sdk/socket_mode/builtin/connection.py", line 305, in run_until_completion
    received_messages: List[Tuple[Optional[FrameHeader], bytes]] = _receive_messages(
  File "/usr/local/lib/python3.10/site-packages/slack_sdk/socket_mode/builtin/internals.py", line 223, in _receive_messages
    return _fetch_messages(
  File "/usr/local/lib/python3.10/site-packages/slack_sdk/socket_mode/builtin/internals.py", line 246, in _fetch_messages
    remaining_bytes = receive()  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/slack_sdk/socket_mode/builtin/internals.py", line 221, in receive
    raise e
  File "/usr/local/lib/python3.10/site-packages/slack_sdk/socket_mode/builtin/internals.py", line 208, in receive
    received_bytes = sock.recv(size)
  File "/usr/local/lib/python3.10/site-packages/eventlet/green/ssl.py", line 243, in recv
    return self._base_recv(buflen, flags, into=False)
  File "/usr/local/lib/python3.10/site-packages/eventlet/green/ssl.py", line 270, in _base_recv
    read = self.read(nbytes)
  File "/usr/local/lib/python3.10/site-packages/eventlet/green/ssl.py", line 187, in read
    return self._call_trampolining(
  File "/usr/local/lib/python3.10/site-packages/eventlet/green/ssl.py", line 165, in _call_trampolining
    trampoline(self,
  File "/usr/local/lib/python3.10/site-packages/eventlet/hubs/__init__.py", line 159, in trampoline
    return hub.switch()
  File "/usr/local/lib/python3.10/site-packages/eventlet/hubs/hub.py", line 313, in switch
    return self.greenlet.switch()
ssl.SSLError: ('timed out',)`

**Comment by zimeg** [comment]
Hey @chadlieberman-flywire 👋

I tried to reproduce this but found that having the Flask app in the dameon thread caused this error from:

```sh
ValueError: signal only works in main thread of the main interpreter
```

Switching the apps on each thread, so that the Slack app runs on the dameon thread instead, seems to fix this and might also remove the `SSLError` too. With [this example](https://github.com/zimeg/slack-sandbox/tree/main/py.bolt.snaek/snippets/issue_953_flask_socketio) I didn't seem to encounter this, so I'm wondering if switching these threads might be an alright solution for you?

If not, I'd be curious to know more about the monkey patching happening with `eventlet` since the Slack app handler is sometimes working fine.

Also, formatting can get strange sometimes, so wanted to check that the `slack-bolt` version you're using is `1.18.0` and not `1.0`?

Hopefully some of this can help, but let me know if this error continues to happen!
