### ISSUE TITLE
Get Invalid 'user_id' when calling  view.publish api   for home tab view

### ISSUE THREAD

**Issue by sunnex0** [slackapi/bolt-python#954]
I am getting this error when trying to publish to home tab

This is the home tab event response :
```python
body: {'token': 'ET2WFtFts2w0ohKXgtAgXxVn', 'team_id': 'T044ELWP8RE', 'api_app_id': 'A04T4F7M77Z', 'event': {'type': 'app_home_opened', 'user': 'U059VM4U6PP', 'channel': 'D05A14JL1FE', 'tab': 'home', 'event_ts': '1693830258.248468'}, 'type': 'event_callback', 'event_id': 'Ev05RJS3616C', 'event_time': 1693830258, 'authorizations': [{'enterprise_id': None, 'team_id': 'T044ELWP8RE', 'user_id': 'U050X9B9XD2', 'is_bot': True, 'is_enterprise_install': False}], 'is_ext_shared_channel': False}
```

using this api 

```
POST https://slack.com/api/views.publish
Content-type: application/json
Authorization: Bearer YOUR_TOKEN_HERE
{
  "user_id": "YOUR_USER_ID",
  "view": {
    "type": "home",
    "blocks": [
      {
        "type": "section",
        "text": {
          "type": "mrkdwn",
          "text": "This is a Block Kit example"
        },
        "accessory": {
          "type": "image",
          "image_url": "https://api.slack.com/img/blocks/bkb_template_images/notifications.png",
          "alt_text": "calendar thumbnail"
        }
      }
    ]
  }
}
```

- I tried using user_id as both  event['user'] and authorizations[0]['user_id'] for the user id to replace YOUR_USER_ID

I am getting this error:
```
resp: {'ok': False, 'error': 'invalid_arguments', 'response_metadata': {'messages': ['[ERROR] invalid `user_id`']}}
```

I used  the xoxb-xxxx-xxx token

what is cause of the error

**Comment by sunnex0** [comment]
I noticed I have to use the bot token generated when the workspace installed my app and not the bot token from my slack api console (OAuth & Permissions)  with the user id of the user from that workspace.

1. What is the best way to retrieve the workspace team bot token after installation of the app?
2. Is there a post message to the home tab without the user's token?

**Comment by seratch** [comment]
> 1. What is the best way to retrieve the workspace team bot token after installation of the app?

Your app can serve public URLs for OAuth installation flows with any workspace users. Please note that your app needs to securely store issued tokens in a database. Refer to the following resources to learn how to build:
* Bolt's OAuth document: https://slack.dev/bolt-python/concepts#authenticating-oauth
* Code exmaples: 
  * SQLite3: https://github.com/slackapi/bolt-python/blob/main/examples/oauth_sqlite3_app.py
  * SQLAlchemy: https://github.com/slackapi/bolt-python/blob/main/examples/sqlalchemy/oauth_app.py
* Underlying SDK document: https://slack.dev/python-slack-sdk/oauth/index.html

> 2. Is there a post message to the home tab without the user's token?

I may not yet fully understad your question here, but usually you don't need user tokens. The only thing you need is a bot token associated with a workspace (when your app is installed into multiple workspaces, your app's database must manage a few bot tokens for those workspaces). If you meant how to send DMs to users, your app needs to have the scopes neccessary to start a DM (im:write): https://api.slack.com/methods/conversations.open

I hope this helps.
