### ISSUE TITLE
Conflict between Slack and Auth0 query parameters in OAuth flow.

### ISSUE THREAD

**Issue by akshatdalton** [slackapi/bolt-python#957]
### Current setup:
Our backend is handling all the Slack OAuth flow, and we have set up a redirect_uri on our frontend route which calls the backend endpoint (**protected endpoint**) to conduct all the required verification using `state` and `code` query params and `cookie` (set during the installation flow).

We also use Auth0 for authentication purposes. Frontend is using it as well.

### The Problem:

We are trying to integrate the Slack Bot installation flow.
But the problem arises when Slack's callback to our frontend route starts Auth0 authentication (since it observes that the call came from an unknown origin). When this Auth0 authentication is completed, Auth0 overrides the `code` and `state` query params initially that were sent by the slack server (because Auth0 also performs the authentication with its `code` and `state` query param). And hence as a result when frontend calls the backend endpoint (**protected endpoint**), slack oauth flow fails.

### Possible solutions we came up with:

We were thinking of making our backend endpoint (which receives this `state` and `code` query param for slack oauth flow) public but the problem is that we manage our `state` generation logic (for the slack install flow) in our database and we don't want to make any endpoint public which performs db operation.

I've also read the [slack server authorize flow](https://api.slack.com/legacy/oauth#send_users) and it is mentioned in the API contract that the `state` parameter is expected - so we cannot do the renaming of the `state` parameter variable.

I want suggestions on how should I handle this oauth flow then.

**Comment by seratch** [comment]
Hi @akshatdalton, thanks for writing in. 

I think the conflict of query parameters cannot be resolved in a reasonable way. So, in your case, I recommend performing Auth0 authentication before redirecting the user who is installing from `/slack/install` to the `slack.com/authorize` URL. 

Specifically, you can create a customized `OAuthFlow` implementation by inheriting the class like this: https://github.com/slackapi/bolt-python/blob/main/slack_bolt/adapter/aws_lambda/lambda_s3_oauth_flow.py

To modify the behavior of /slack/install, you can override this method: https://slack.dev/bolt-python/api-docs/slack_bolt/oauth/index.html#slack_bolt.oauth.OAuthFlow.handle_installation

I hope this helps.

**Comment by seratch** [comment]
Forgt to mention this: If an installing user lost Auth0 authentication for some reason when visiting `/slack/oauth_redirect`, your app needs to prioritize Auth0's query parameter handling over Slack's ones, and then your app needs to ask the same user to go through the Slack OAuth flow again. Until your app completes `oauth.v2.access` API call using a given code parameter, the installation is not yet completed. Thus, it's safe to do it again in the scenario.
