### ISSUE TITLE
New Slack UI Changes Default Tab when Opening Application

### ISSUE THREAD

**Issue by dglindner2** [slackapi/bolt-python#959]
On the old Slack UI the default view when you opened a Slack application was the Home tab. Now, without changing anything in my application, the default view is the messaging tab when you open the application. The only thing that changed was that I was migrated to the new Slack UI that I've been hearing about. Is there a way to change this? I don't want to direct users to the Messages tab every time they click on the app.

**Comment by hello-ashleyintech** [comment]
@dglindner2 Hi, Thanks so much for your question! 🙌 

I would recommend going into your App Config page for the application, then going to App Home in the sidebar and making sure that the app home option is toggled on. Hopefully this should launch the App Home in favor of the messaging tab in the default view.

If this is already enabled, let me know and we can troubleshoot further!

**Comment by dglindner2** [comment]
Hey Ashley!

Sorry if I didn't provide enough information. I've had an application in Slack for the past 6 months where the majority of the features are in the home tab. However, last week my Slack was updated to the new Slack User Interface. With this change, it seems there was a change in the functionality of all Slack applications. Instead of opening to the home tab (like it has for the past 6 months), it now opens to the messages tab by default. 

This must be a feature of the new Slack User Interface, but this is hurtful towards the usability of my application in Slack. I was wondering if the Dev Team at Slack has been working on a way to choose the default tab that your application opens to, so that developers can lead their users to the best place.

**Comment by dglindner2** [comment]
Hi @hello-ashleyintech ,

Were you able to find out anything about the new Slack UI changing the functionality of opening an application? 
It seems like the developer should have the option to determine themselves if the user is routed to the Home tab or the Message tab upon opening the application.

**Comment by hello-ashleyintech** [comment]
Hi, @dglindner2! I will ask internally and see what I can find about those changes to the Slack UI! Thanks for bumping this up. 🙇 I'll post an update once I have one!

**Comment by hello-ashleyintech** [comment]
Hi, @dglindner2! After asking internally, it looks like this is a reported bug that was an unintended side effect of the new Slack UI. It is on the team's radar, however the timeline to resolve this issue is unknown right now due to limited bandwidth.

In the meantime, they suggested this workaround:

> When a user first installs the app, you could send them a message immediately with a button to take them to the Home tab. You can set the url to deeplink to your app's Home. Here are some resources on how to achieve that.
> https://api.slack.com/reference/block-kit/block-elements#button
> https://api.slack.com/reference/deep-linking#open_app_home

**Comment by yongikim** [comment]
First off, I just want to say a huge thank you for all the hard work you’re putting into maintaining and improving Slack! 🙌 I know you’re juggling a lot, and I really appreciate you taking the time to look into this issue.

I completely understand that bandwidth is limited and that prioritization is necessary, but I just wanted to check in and see if there are any updates on this. This change has been impacting the usability of our app quite a bit, and I imagine other developers may be facing similar challenges.

We truly appreciate your efforts and any insights you can share. Thanks again for everything you do! 🚀

**Comment by ravenna-tom** [comment]
Agree - not being able to control this is frustrating.
