### ISSUE TITLE
RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by chadleeshaw** [slackapi/bolt-python#960]
#### The `slack_bolt` version

slack-bolt==1.18.0
slack-sdk==3.22.0

#### Python runtime version

Python 3.9.18

#### OS info

Python3.9 Container
Linux dbcc36ee6b99 4.14.15-1.el7.elrepo.x86_64

#### Steps to reproduce:

1. Running a container in Host mode and start the bot:
``` dockerfile
FROM --platform=linux/amd64 python:3.9

WORKDIR /app
COPY . .
RUN pip install -r requirements.txt
CMD [ "python", "./bot.py" ]
```
``` bash
docker run -d
    --net=host
    --restart=unless-stopped
    -e SLACK_BOT_TOKEN=xxx
    -e SLACK_SIGNING_TOKEN=xxx
    -e SLACK_APP_TOKEN=xxx
    boltbot:latest
```
``` python
...
app = App(
    token = os.getenv("SLACK_BOT_TOKEN"),
    signing_secret = os.getenv("SLACK_SIGNING_TOKEN"),
)
...
# Main
if __name__ == "__main__":
    handler = SocketModeHandler(app, os.getenv("SLACK_APP_TOKEN"))
    handler.start()
```

2.  Get a thread error:

```
Traceback (most recent call last):
  File "/app/./bot.py", line 139, in <module>
    handler = SocketModeHandler(app, os.getenv("SLACK_APP_TOKEN"))
  File "/usr/local/lib/python3.9/site-packages/slack_bolt/adapter/socket_mode/builtin/__init__.py", line 57, in __init__
    self.client = SocketModeClient(
  File "/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/builtin/client.py", line 124, in __init__
    self.current_session_runner = IntervalRunner(self._run_current_session, 0.1).start()
  File "/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/interval_runner.py", line 23, in start
    self.thread.start()
  File "/usr/local/lib/python3.9/threading.py", line 899, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```

3.  Ulimits are not being met:

Current thread count before starting is `1932` and ulimit is `1030626`

### Expected result:

Expected boltbot to start without a thread error

**Comment by hello-ashleyintech** [comment]
Hi, @chadleeshaw! Thanks for reaching out.

After looking at your code and doing some research on the error, I'm wondering if the issue is on the Docker side - what version of Docker are you running, and have you tried upgrading it to the most recent version?

**Comment by chadleeshaw** [comment]
Yes I am running an older version `Server Version: 17.12.1-ce`.  Thanks for the suggestion.  I will try and update.

**Comment by chadleeshaw** [comment]
You are correct, the old version was causing a problem.  Updating to ` Server Version: 20.10.6` fixed the problem for me.
