### ISSUE TITLE
Ack() unhandled request error

### ISSUE THREAD

**Issue by acckiydarik** [slackapi/bolt-python#961]
Hello, I can't get output of a function through ack() but it works well via say().
Also it works when output of ack() has less symbols but I wan't to emphasise that output of unhandled request within limits. It has only 1780 characters.
Thank you.

#### The `slack_bolt` version

slack-bolt==1.17.2
slack-client==0.3.0
slack-notifications==0.2.2
slack-sdk==3.21.2
slackclient==2.9.4

#### Python runtime version

Python 3.8.6

#### OS info

LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.9.2009 (Core)
Release:	7.9.2009
Codename:	Core

#### Steps to reproduce:
```

from slack_bolt import App
from slack_bolt.response import BoltResponse
from slack_bolt.adapter.socket_mode import SocketModeHandler
from slack_bolt.error import BoltUnhandledRequestError

@app.command("/tt")
def handle_rhs_command(ack, logger):
    logger.debug("Received command: /test")
    ack(detect_network(hostname='hostname')) # hand made function 



if __name__ == "__main__":
    try:
        handler = SocketModeHandler(app, app_token)
        handler.start()
    except Exception as e:
        print(f"Error in starting SocketModeHandler: {e}")

```
### Expected result:
Handle request

### Actual result:

> client.py[LINE:234]# DEBUG    [2023-09-15 12:33:42,733]  on_message invoked: (message: ,"trigger_id":"5887757605447.96147373888.08b49cc9c4e10fde967057e4513e999a"},"type":"slash_commands","accepts_response_payload":true})
> client.py[LINE:99]# DEBUG    [2023-09-15 12:33:42,734]  A new message enqueued (current queue size: 1)
> client.py[LINE:105]# DEBUG    [2023-09-15 12:33:42,734]  A message dequeued (current queue size: 0)
> client.py[LINE:125]# DEBUG    [2023-09-15 12:33:42,735]  Message processing started (type: slash_commands, envelope_id: fc5629f2-95c9-45ee-9a20-4af1ebbc9b48)
> app.py[LINE:506]# DEBUG    [2023-09-15 12:33:42,736]  Applying slack_bolt.middleware.ssl_check.ssl_check.SslCheck
> app.py[LINE:506]# DEBUG    [2023-09-15 12:33:42,736]  Applying slack_bolt.middleware.request_verification.request_verification.RequestVerification
> app.py[LINE:506]# DEBUG    [2023-09-15 12:33:42,736]  Applying slack_bolt.middleware.authorization.single_team_authorization.SingleTeamAuthorization
> app.py[LINE:506]# DEBUG    [2023-09-15 12:33:42,736]  Applying slack_bolt.middleware.ignoring_self_events.ignoring_self_events.IgnoringSelfEvents
> app.py[LINE:506]# DEBUG    [2023-09-15 12:33:42,736]  Applying slack_bolt.middleware.url_verification.url_verification.UrlVerification
> app.py[LINE:533]# DEBUG    [2023-09-15 12:33:42,737]  Checking listener: handle_rhs_command ...
> app.py[LINE:533]# DEBUG    [2023-09-15 12:33:42,737]  Checking listener: handle_rhs_command ...
> app.py[LINE:533]# DEBUG    [2023-09-15 12:33:42,737]  Checking listener: handle_rhs_command ...
> app.py[LINE:555]# DEBUG    [2023-09-15 12:33:42,737]  Running listener: handle_rhs_command ...
> slack_hdwr_bot.py[LINE:714]# DEBUG    [2023-09-15 12:33:42,737]  Received command: /tt
> connectionpool.py[LINE:1003]# DEBUG    [2023-09-15 12:33:42,739]  Starting new HTTPS connection (1): hostname:443
> connectionpool.py[LINE:456]# DEBUG    [2023-09-15 12:33:43,184]  https://hostname:443 "GET /api/v0/ports/search/name HTTP/1.1" 200 None
> connectionpool.py[LINE:1003]# DEBUG    [2023-09-15 12:33:43,189]  Starting new HTTPS connection (1): hostname:443
> connectionpool.py[LINE:456]# DEBUG    [2023-09-15 12:33:43,263]  https://hostname:443 "GET /api/v0/ports/13314 HTTP/1.1" 200 None
> connectionpool.py[LINE:1003]# DEBUG    [2023-09-15 12:33:43,270]  Starting new HTTPS connection (1): hostname:443
> connectionpool.py[LINE:456]# DEBUG    [2023-09-15 12:33:43,364]  https://hostname:443 "GET /api/v0/devices/88 HTTP/1.1" 200 None
> connectionpool.py[LINE:1003]# DEBUG    [2023-09-15 12:33:43,369]  Starting new HTTPS connection (1): hostname:443
> connectionpool.py[LINE:456]# DEBUG    [2023-09-15 12:33:43,453]  https://hostname:443 "GET /api/v0/ports/671642 HTTP/1.1" 200 None
> connectionpool.py[LINE:1003]# DEBUG    [2023-09-15 12:33:43,457]  Starting new HTTPS connection (1): hostname:443
> connectionpool.py[LINE:456]# DEBUG    [2023-09-15 12:33:43,539]  https://hostname:443 "GET /api/v0/devices/89 HTTP/1.1" 200 None
> connectionpool.py[LINE:1003]# DEBUG    [2023-09-15 12:33:43,546]  Starting new HTTPS connection (1): hostname:443
> connectionpool.py[LINE:456]# DEBUG    [2023-09-15 12:33:43,633]  https://hostname:443 "GET /api/v0/ports/13315 HTTP/1.1" 200 None
> connectionpool.py[LINE:1003]# DEBUG    [2023-09-15 12:33:43,638]  Starting new HTTPS connection (1): hostname:443
> connectionpool.py[LINE:456]# DEBUG    [2023-09-15 12:33:43,728]  https://hostname:443 "GET /api/v0/devices/88 HTTP/1.1" 200 None
> connectionpool.py[LINE:1003]# DEBUG    [2023-09-15 12:33:43,733]  Starting new HTTPS connection (1): hostname:443
> connectionpool.py[LINE:456]# DEBUG    [2023-09-15 12:33:43,808]  https://hostname:443 "GET /api/v0/ports/671643 HTTP/1.1" 200 None
> connectionpool.py[LINE:1003]# DEBUG    [2023-09-15 12:33:43,815]  Starting new HTTPS connection (1): hostname:443
> connectionpool.py[LINE:456]# DEBUG    [2023-09-15 12:33:43,902]  https://hostname:443 "GET /api/v0/devices/89 HTTP/1.1" 200 None
> connectionpool.py[LINE:1003]# DEBUG    [2023-09-15 12:33:43,908]  Starting new HTTPS connection (1): hostname:443
> connectionpool.py[LINE:456]# DEBUG    [2023-09-15 12:33:43,998]  https://hostname:443 "GET /api/v0/ports/13402 HTTP/1.1" 200 None
> connectionpool.py[LINE:1003]# DEBUG    [2023-09-15 12:33:44,002]  Starting new HTTPS connection (1): hostname:443
> connectionpool.py[LINE:456]# DEBUG    [2023-09-15 12:33:44,083]  https://hostname:443 "GET /api/v0/devices/88 HTTP/1.1" 200 None
> connectionpool.py[LINE:1003]# DEBUG    [2023-09-15 12:33:44,088]  Starting new HTTPS connection (1): hostname:443
> connectionpool.py[LINE:456]# DEBUG    [2023-09-15 12:33:44,156]  https://hostname:443 "GET /api/v0/ports/109672 HTTP/1.1" 200 None
> connectionpool.py[LINE:1003]# DEBUG    [2023-09-15 12:33:44,161]  Starting new HTTPS connection (1): hostname:443
> connectionpool.py[LINE:456]# DEBUG    [2023-09-15 12:33:44,243]  https://hostname:443 "GET /api/v0/devices/90 HTTP/1.1" 200 None
> connectionpool.py[LINE:1003]# DEBUG    [2023-09-15 12:33:44,246]  Starting new HTTPS connection (1): hostname:443
> connectionpool.py[LINE:456]# DEBUG    [2023-09-15 12:33:44,323]  https://hostname:443 "GET /api/v0/ports/546029 HTTP/1.1" 200 None
> connectionpool.py[LINE:1003]# DEBUG    [2023-09-15 12:33:44,328]  Starting new HTTPS connection (1): hostname:443
> connectionpool.py[LINE:456]# DEBUG    [2023-09-15 12:33:44,433]  https://hostname:443 "GET /api/v0/devices/89 HTTP/1.1" 200 None
> connectionpool.py[LINE:1003]# DEBUG    [2023-09-15 12:33:44,438]  Starting new HTTPS connection (1): hostname:443
> connectionpool.py[LINE:456]# DEBUG    [2023-09-15 12:33:44,509]  https://hostname:443 "GET /api/v0/ports/554680 HTTP/1.1" 200 None
> connectionpool.py[LINE:1003]# DEBUG    [2023-09-15 12:33:44,514]  Starting new HTTPS connection (1): hostname:443
> connectionpool.py[LINE:456]# DEBUG    [2023-09-15 12:33:44,624]  https://hostname:443 "GET /api/v0/devices/91 HTTP/1.1" 200 None
> connectionpool.py[LINE:1003]# DEBUG    [2023-09-15 12:33:44,629]  Starting new HTTPS connection (1): hostname:443
> connectionpool.py[LINE:456]# DEBUG    [2023-09-15 12:33:44,714]  https://hostname:443 "GET /api/v0/ports/13526 HTTP/1.1" 200 None
> connectionpool.py[LINE:1003]# DEBUG    [2023-09-15 12:33:44,719]  Starting new HTTPS connection (1): hostname:443
> connectionpool.py[LINE:456]# DEBUG    [2023-09-15 12:33:44,810]  https://hostname:443 "GET /api/v0/devices/88 HTTP/1.1" 200 None
> connectionpool.py[LINE:1003]# DEBUG    [2023-09-15 12:33:44,815]  Starting new HTTPS connection (1): hostname:443
> connectionpool.py[LINE:456]# DEBUG    [2023-09-15 12:33:44,891]  https://hostname:443 "GET /api/v0/ports/546694 HTTP/1.1" 200 None
> connectionpool.py[LINE:1003]# DEBUG    [2023-09-15 12:33:44,895]  Starting new HTTPS connection (1): hostname:443
> connectionpool.py[LINE:456]# DEBUG    [2023-09-15 12:33:44,982]  https://hostname:443 "GET /api/v0/devices/2243 HTTP/1.1" 200 None
> connectionpool.py[LINE:1003]# DEBUG    [2023-09-15 12:33:44,985]  Starting new HTTPS connection (1): hostname:443
> connectionpool.py[LINE:456]# DEBUG    [2023-09-15 12:33:45,070]  https://hostname:443 "GET /api/v0/ports/546755 HTTP/1.1" 200 None
> connectionpool.py[LINE:1003]# DEBUG    [2023-09-15 12:33:45,074]  Starting new HTTPS connection (1): hostname:443
> connectionpool.py[LINE:456]# DEBUG    [2023-09-15 12:33:45,160]  https://hostname:443 "GET /api/v0/devices/2244 HTTP/1.1" 200 None
> connectionpool.py[LINE:1003]# DEBUG    [2023-09-15 12:33:45,164]  Starting new HTTPS connection (1): hostname:443
> connectionpool.py[LINE:456]# DEBUG    [2023-09-15 12:33:45,247]  https://hostname:443 "GET /api/v0/ports/546726 HTTP/1.1" 200 None
> connectionpool.py[LINE:1003]# DEBUG    [2023-09-15 12:33:45,251]  Starting new HTTPS connection (1): hostname:443
> connectionpool.py[LINE:456]# DEBUG    [2023-09-15 12:33:45,329]  https://hostname:443 "GET /api/v0/devices/2243 HTTP/1.1" 200 None
> connectionpool.py[LINE:1003]# DEBUG    [2023-09-15 12:33:45,332]  Starting new HTTPS connection (1): hostname:443
> connectionpool.py[LINE:456]# DEBUG    [2023-09-15 12:33:45,409]  https://hostname:443 "GET /api/v0/ports/555460 HTTP/1.1" 200 None
> connectionpool.py[LINE:1003]# DEBUG    [2023-09-15 12:33:45,417]  Starting new HTTPS connection (1): hostname:443
> connectionpool.py[LINE:456]# DEBUG    [2023-09-15 12:33:45,494]  https://hostname:443 "GET /api/v0/devices/2243 HTTP/1.1" 200 None
> connectionpool.py[LINE:1003]# DEBUG    [2023-09-15 12:33:45,499]  Starting new HTTPS connection (1): hostname:443
> connectionpool.py[LINE:456]# DEBUG    [2023-09-15 12:33:45,578]  https://hostname:443 "GET /api/v0/ports/555461 HTTP/1.1" 200 None
> connectionpool.py[LINE:1003]# DEBUG    [2023-09-15 12:33:45,583]  Starting new HTTPS connection (1): hostname:443
> connectionpool.py[LINE:456]# DEBUG    [2023-09-15 12:33:45,671]  https://hostname:443 "GET /api/v0/devices/2244 HTTP/1.1" 200 None
> connectionpool.py[LINE:1003]# DEBUG    [2023-09-15 12:33:45,676]  Starting new HTTPS connection (1): hostname:443
> thread_runner.py[LINE:167]# WARNING  [2023-09-15 12:33:45,745]  handle_rhs_command didn't call ack()
> listener_error_handler.py[LINE:67]# ERROR    [2023-09-15 12:33:45,746]  Failed to run listener function (error: unhandled request error)
> Traceback (most recent call last):
>   File "/home/user/.local/lib/python3.8/site-packages/slack_bolt/app/app.py", line 569, in dispatch
>     raise BoltUnhandledRequestError(
> slack_bolt.error.BoltUnhandledRequestError: unhandled request error
> internals.py[LINE:43]# INFO     [2023-09-15 12:33:45,746]  Unsuccessful Bolt execution result (status: 404, body: {"error": "unhandled request"})
> client.py[LINE:150]# DEBUG    [2023-09-15 12:33:45,747]  Message processing completed (type: slash_commands, envelope_id: fc5629f2-95c9-45ee-9a20-4af1ebbc9b48)
> connectionpool.py[LINE:456]# DEBUG    [2023-09-15 12:33:45,748]  https://hostname:443 "GET /api/v0/ports/555459 HTTP/1.1" 200 None
> connectionpool.py[LINE:1003]# DEBUG    [2023-09-15 12:33:45,752]  Starting new HTTPS connection (1): hostname:443
> connectionpool.py[LINE:456]# DEBUG    [2023-09-15 12:33:45,839]  https://hostname:443 "GET /api/v0/devices/89 HTTP/1.1" 200 None
> connectionpool.py[LINE:1003]# DEBUG    [2023-09-15 12:33:45,843]  Starting new HTTPS connection (1): hostname:443
> connectionpool.py[LINE:456]# DEBUG    [2023-09-15 12:33:45,930]  https://hostname:443 "GET /api/v0/ports/555462 HTTP/1.1" 200 None
> connectionpool.py[LINE:1003]# DEBUG    [2023-09-15 12:33:45,936]  Starting new HTTPS connection (1): hostname:443
> connectionpool.py[LINE:456]# DEBUG    [2023-09-15 12:33:46,023]  https://hostname:443 "GET /api/v0/devices/88 HTTP/1.1" 200 None

**Comment by hello-ashleyintech** [comment]
Hi, @acckiydarik! Thanks for your question 🙌 

Could you explain why you are trying to get the output of a function through `ack()`? Are you just trying to view the function output in your app logs, or something else?

**Comment by acckiydarik** [comment]
@hello-ashleyintech  Hello, sure. I use ack() because it allows me to print output in a private-style(*Only visible to you), where only the requester receives the information. It helps avoid a spam of messages and can be used from any channel and in private conversations.

**Comment by hello-ashleyintech** [comment]
@acckiydarik Glad to hear it! Thanks for submitting this issue - since you figured it out, I'll close this out, but feel free to submit a new issue if you have any other questions 😄
