### ISSUE TITLE
Getting 'dict' object has no attribute 'bot_token' when using app after installation

### ISSUE THREAD

**Issue by faisalsaifii** [slackapi/bolt-python#966]
I was successfully able to install the app through OAuth using Slack Bolt InstallationStore but the issue comes when I'm using the app. I get this error:

```
Failed to run a middleware middleware (error: 'dict' object has no attribute 'bot_token')
Traceback (most recent call last):
  File "/User/Library/Python/3.11/lib/python/site-packages/slack_bolt/app/app.py", line 477, in dispatch
    resp = middleware.process(req=req, resp=resp, next=middleware_next)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/User/Library/Python/3.11/lib/python/site-packages/slack_bolt/middleware/authorization/multi_teams_authorization.py", line 58, in process
    auth_result: Optional[AuthorizeResult] = self.authorize(
                                             ^^^^^^^^^^^^^^^
  File "/User/Library/Python/3.11/lib/python/site-packages/slack_bolt/authorization/authorize.py", line 180, in __call__
    bot_token = latest_installation.bot_token  # this still can be None
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'bot_token'
```

I believe it's the issue with my installation store set up with MongoDB:

```python
from slack_sdk.oauth.installation_store.installation_store import InstallationStore
from pymongo import MongoClient

class MongoDBInstallationStore(InstallationStore):
    def __init__(self, client: MongoClient, database: str):
        self.client = client
        self.database = database
        self.collection = self.client[self.database]["installations"]

    def save(self, installation):
        data = vars(installation)
        if data["is_enterprise_install"] and data["enterprise"]:
            return self.collection.replace_one(
                {"enterprise_id": data["enterprise_id"]},
                data,
                upsert=True,
            )
        if data["team_id"]:
            return self.collection.replace_one(
                {"team_id": data["team_id"]},
                data,
                upsert=True,
            )
        return "Failed saving installation data to installationStore"

    def find_installation(self, enterprise_id, team_id, is_enterprise_install):
        if is_enterprise_install and enterprise_id:
            document = self.collection.find_one({"enterprise_id": enterprise_id})
            if not document:
                return document
            else:
                document.pop("_id")
                document.pop("installed_at")
                return document
        if team_id:
            document = self.collection.find_one({"team_id": team_id})
            if not document:
                return document
            else:
                document.pop("_id")
                document.pop("installed_at")
                return document
        return "Failed fetching installation"
```

If possible, could the sample code for installation store be provided for Slack Bolt Python like it is present for JS? 

Here's my app code:
```python
.
.
.

oauth_settings = OAuthSettings(
    client_id=client_id,
    client_secret=client_secret,
    scopes=["commands", "chat:write"],
    installation_store=MongoDBInstallationStore(client=client, database="slack"),
)

slack_app = App(
    signing_secret=os.environ.get("SLACK_SIGNING_SECRET"),
    oauth_settings=oauth_settings,
)
slack_web_client = WebClient(token=bot_token)
handler = SlackRequestHandler(slack_app)

.
.
.

@app.route("/slack/install", methods=["GET"])
def install():
    return handler.handle(request)

@app.route("/slack/oauth_redirect", methods=["GET"])
def oauth_redirect():
    return handler.handle(request)
```

### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### Python runtime version:
```
$ python3 --version
Python 3.11.4
```

#### OS info

```
ProductName:		macOS
ProductVersion:		14.0
BuildVersion:		23A344
Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:34 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8103
```

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1. Source Code: https://github.com/faisalsaifii/pollify
2. Install the app and run /poll

### Expected result:

(Tell what you expected to happen)
A modal should open up

### Actual result:

(Tell what actually happened with logs, screenshots)
showing dispatch failed in slack and the error mentioned on server end

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by mwbrooks** [comment]
Hi @faisalsaifii 👋🏻 Thanks for using Bolt for Python!

From your code and question, it sounds as though you started by developing a Slack app for a single workspace using the Bot Token provided by the [App Config](https://api.slack.com/apps). Now that you want to distribute your app to multiple workspaces, you're using OAuth. When your app is installed with OAuth, the [response will include an `access_token` for your bot (also a Bot Token (`xoxb-`)) and also the user (User Token `xoxp-`)](https://api.slack.com/methods/oauth.v2.access). 

Here are two sample apps that use OAuth for Bolt for JavaScript:
- https://github.com/slack-samples/bolt-python-starter-template/blob/main/app_oauth.py
- https://github.com/slackapi/bolt-python/blob/main/examples/oauth_app.py

Would you mind taking a look over the source code to see whether it can help unblock you? Since your app won't know the Bot Token on startup, you'll probably need to refactor your `slack_web_client = WebClient(token=bot_token)` line of code to use the `client` available in most functions.

**Comment by faisalsaifii** [comment]
Hi @mwbrooks Thanks for the info, I missed the client part by mistake and have fixed it now.

As for the sample apps, the second one doesn't have any store or auth flow and the first one uses the file based store which I can't use for a production app.

Can you point out the flaws in my code other than the client part that's been fixed please?

**Comment by seratch** [comment]
Hi @faisalsaifii, our SDK offers these options: https://github.com/slackapi/python-slack-sdk/tree/main/slack_sdk/oauth/installation_store

If none of these options meet your requirements, feel free to implement your own solution.

**Comment by faisalsaifii** [comment]
Hi @seratch, just what I was looking for. The S3 Store helped a lot, was able to convert it to MongoDB.
Finally deployed it, http://pollify-bhos.onrender.com/slack/install. Is there a way to stylize the page provided by Bolt? Add more components maybe?

**Comment by seratch** [comment]
@faisalsaifii Check my reply here: https://github.com/slackapi/bolt-python/issues/324#issuecomment-833499373

**Comment by faisalsaifii** [comment]
Got it, thank you both for the help
