### ISSUE TITLE
Getting "Received an unexpected response for handshake" error when using socketmode

### ISSUE THREAD

**Issue by aksgpt** [slackapi/bolt-python#968]
I am running socketMode and getting below error in Unix machine. The same code works in Windows
### Reproducible in:

```
WARNING:__main__:Received an unexpected response for handshake (status: 200, response: HTTP/1.1 200 OK
Cache-Control: no-cache
X-XSS-Protection: 1
Connection: close
Content-Type: text/html; charset=utf-8
Content-Length: 5923
Pragma: no-cache, session id: 6924c984-abe2-4326-b5b6-f930598b739c)

```

#### The `slack_bolt` version

slack-bolt==1.18.0
slack-sdk==3.23.0

#### Python runtime version

Python 3.9.17

**Comment by seratch** [comment]
Hi @aksgpt, thanks for asking the question. It seems that something on your infra side could prevent passing 101 status response from Slack to your app process: https://github.com/slackapi/python-slack-sdk/blob/9967dc0a206d974f7ef2c09dd6c49f70b98ecf1e/slack_sdk/socket_mode/builtin/connection.py#L157

If your infra has proxy servers and/or something similar, I would recommend contacting your admins and asking them to allow WebSocket connection establishment.
