### ISSUE TITLE
Effects of reinstalling the slack app

### ISSUE THREAD

**Issue by PrajwalNaik07** [slackapi/bolt-python#969]
We have a new usecase to be built in our app which requires us to add new scopes to the app ( channels:read & channels:history). But when we are trying to add them, the slack app website is telling us to reinstall the app. What will be the effect of reinstalling the app, as the app is in production and we need to know the effect it would have on reinstalling it

**Comment by seratch** [comment]
Hi @PrajwalNaik07, thanks for asking the question. When introducing a new scope, your application must be re-installed to reflect this addition to your app's OAuth access token. In the case of the production app, it may be necessary to inform the end-users of the app about re-installing it to utilize the recently added permissions. If these new permissions are only required for a new feature (for instance, a new slash command), your app can notify the end-user when they attempt to use it.

**Comment by PrajwalNaik07** [comment]
Hi @seratch , when you say that the new scope will be added to the app's OAuth access token, does it change the OAuth token?

**Comment by seratch** [comment]
@PrajwalNaik07 In most cases, the token string remains the same, but it's not always guaratteed. Even when the string remains the same, Slack's server-side database associates newly added scopes to your token when the same installing user accepts the scope changes by going through the OAuth flow with a new set of scopes. Does this make sense?

**Comment by PrajwalNaik07** [comment]
Yes, sure thank you
