### ISSUE TITLE
S3 bucket policy for slack to send messages, urls gives downloading image failed errors

### ISSUE THREAD

**Issue by efeozsoy** [slackapi/bolt-python#970]
#### The `slack_bolt` version

(Paste the output of `pip freeze | grep slack`)
slack-bolt==1.18.0
slack-sdk==3.21.3
#### Python runtime version

Python 3.9.18

#### OS info

ProductName:    macOS
ProductVersion: 12.6
BuildVersion:   21G115
Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101

#### Steps to reproduce:

```
image_test ={"blocks": [ {
  "type": "image",
  "title": {
    "type": "plain_text",
    "text": "Please enjoy this photo of a kitten"
  },
  "block_id": "image4",
  "image_url": "https://my-s3-bucket.png",
  "alt_text": "An incredibly cute kitten."
} ]}
```
1. I uploaded my images to the s3 bucket and I tried to allow aws referer with slack domain which is 
```
{
            "Sid": "Allow get requests originating from https:://www.slack.com",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": [
                "arn:aws:s3:::my-bucket-name/*",
                "arn:aws:s3:::my-bucket-name"
            ],
            "Condition": {
                "StringLike": {
                    "aws:Referer": "https://www.slack.com/api"
                }
            }
        }
```

2. I am trying to send messages after I receive mentioned event 
```
@slack_app.event("app_mention")
def say_hello(body, ack, say):
    ack()
    event_type = body["event"]["type"]
    data = body["event"]["text"]
    say(blocks=image_test['blocks'], message="None)

```
4. I am receiving this error 
The server responded with: {'ok': False, 'error': 'invalid_blocks', 'errors': ['downloading image failed [json-pointer:/blocks/0/image_url]'], 'response_metadata': {'messages': ['[ERROR] downloading image failed [json-pointer:/blocks/0/image_url]']}}

How can I adjust my s3 bucket policy without granting all public access to send images to channels in Slack?

**Comment by mwbrooks** [comment]
Hi @efeozsoy 👋🏻  Thanks for the details!

Personally, I haven't tried to restrict S3 images to only a Slack app.

One thing to note is that the image is downloaded on the client-side by the user's machine. In your example code, it looks like the condition is for the referrer `https://www.slack.com/api`. Instead, you may want to try `https://app.slack.com` because that is the host of the client-side Slack app.

Please let me know if that helps and we can follow-up!
