### ISSUE TITLE
Slack does not stop processing events

### ISSUE THREAD

**Issue by WhyIsItSoHardToPickAUsername** [slackapi/bolt-python#971]
(Describe your issue and goal here)

When a user uploads a file to a channel, my code downloads the file. 

The problem I am facing is that Slack keeps processing the function "def handle_file_shared_events(logger, body, say, event, client, ack, token)". So I see repeated messages for the same file, until I kill my Slack app. I must be missing something that will cause Slack to run the function once for a given file and then stop. 

```python
import logging
import os
import requests


from slack_sdk import WebClient
from slack_bolt import App
from slack_bolt import App, Say, BoltContext
from slack_bolt.adapter.socket_mode import SocketModeHandler

logging.basicConfig(level=logging.DEBUG)

proxy_url = "examplecom:443"

app = App(client=WebClient(token=os.environ["SLACK_BOT_TOKEN"], proxy=proxy_url))

@app.event("file_shared")
def handle_file_shared_events(logger, body, say, event, client, ack, token):

    ack()
    logger.info(body)
    say(text=f"Hey, I see a file, the id is {event['file_id']}")
    my_file_id = event['file_id']
    say(text=f"file_id is {my_file_id}")

    file_info = client.files_info(file=my_file_id)

    my_url_private_download = file_info.get("file").get("url_private_download")

    say(f"download url is {my_url_private_download}")

    fname = client.files_info(file = my_file_id).get('file').get('title')

    resp = requests.get(my_url_private_download, headers={'Authorization': 'Bearer %s' % token})

    assert not os.path.exists(fname), print("File already exists. Please remove/rename and re-run")
    out_file = open(fname, mode="wb+")
    out_file.write(resp.content)
    out_file.close()    


if __name__ == "__main__":
    SocketModeHandler(
        app=app,
        app_token=os.environ["SLACK_APP_TOKEN"],
        proxy=proxy_url,
    ).start()
```

#### The `slack_bolt` version

slack-bolt==1.18.0
slack-sdk==3.22.0

#### Python runtime version

Python 3.10.0

#### OS info

ProductName:		macOS
ProductVersion:		14.0
BuildVersion:		23A344
Darwin Kernel Version 23.0.0: Fri Sep 15 14:42:42 PDT 2023; root:xnu-10002.1.13~1/RELEASE_X86_64

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1. Code is shared above
2. To run the code you can use 'python3 app.py' after you download the code in a file called app.py
3. You should see in Slack where this app is running a constant stream of messages.

### Expected result:

I expect Slack to run my function once per file and then stop.

### Actual result:

What happens is that I see this message over and over and over until I kill the app.

Hey, I see a file, the id is XXXXX
file_id is XXXX
download url is https://files.slack.com/files-pri/XXX/download/filename.txt

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by eddyg** [comment]
Try removing this line:

> say(f"download url is {my_url_private_download}")

My guess is that you are repeatedly “sharing” a file by sending a link to a file.

**Comment by WhyIsItSoHardToPickAUsername** [comment]
That worked! Thank you! I am not sure why "say" would trigger the file_share, since it's a URL, not an actual file. 
I wanted to catch events when a file is uploaded, not when a URL  for a file is shared. 
In any case I removed the "say" line and it's not happening now. 
Thanks again!
