### ISSUE TITLE
How to get each user token?

### ISSUE THREAD

**Issue by miguel-arrf** [slackapi/bolt-python#972]
Hi! 👋 

I'm building an App that needs access to all user messages. Essentially, after a user installs the app in their workspace, I want the app to get all of their received messages (IM, channels, groups). 

For it, I understand that I need access to the user token. Is it possible to get the user token for each user that 'allows' it? Or does the user need to first create an app, and then send me the user token? That seems unreasonable.

### Expected result:

Somehow have a magical solution that allows me to get all messages from all users that _allows_ is :)!

**Comment by srajiang** [comment]
Hi @miguel-arrf - Your app can receive a user token for each user that directly installs your app. For that, you might want to take a look at the Bolt Python documentation [on Authenticating with OAuth](https://slack.dev/bolt-python/concepts#authenticating-oauth). The Bolt Python framework ships with a direct install link which you can direct users toward to complete the OAuth flow and a file-based state-store that should allow you to get going out of the box. For production, you'll want to implement your own state store. 

Permissions for tokens are granular, so there is no single scope that exists that grants permissions to read messages from IM, channels, groups. Based on your use cas, you may want to request a few different scopes; you can see the [user token scopes](https://api.slack.com/scopes) and associated [methods](https://api.slack.com/methods) here.

**Comment by nuno86800** [comment]
Hi @srajiang, I'm trying to do the same thing as @miguel-arrf but I'm not able to completely understand the documentation. Can you provide a quick example showing how you can implement this in your app. I also have some doubts regarding the Redirect URL, should I change it? Because in the documentation it says there is a default one.

Thanks for you help 🙌

**Comment by miguel-arrf** [comment]
Thank you so much @srajiang ! 🤩
In the meanwhile I was able to use the documentation code to make this work!

I now have a different question. When setting the `OAuthSettings`, 

```
oauth_settings = OAuthSettings(
    ...
    state_store=FileOAuthStateStore(expiration_seconds=30, base_dir="./data"),
    ...
)
```

What's the impact of the `expiration_seconds` in the `FileOAuthStateStore`? There was something that caught my attention here: [https://api.slack.com/authentication/oauth-v2]( https://api.slack.com/authentication/oauth-v2), where it is says the following:
- "_Will my token expire? OAuth tokens do not expire. If they are no longer needed, they can be revoked._"

Given that, why do we need the `expiration_seconds` parameter?

Thank you for the help! :)
