### ISSUE TITLE
KeyError: 'ts' when trying to reply to a thread

### ISSUE THREAD

**Issue by WhyIsItSoHardToPickAUsername** [slackapi/bolt-python#975]
(Describe your issue and goal here)

I am trying to reply to a thread and I am getting a KeyError: 'ts' message with no reply in the thread.

My code is:

```python

def reply_in_thread(url, say, event):
           thread_ts = event.get("thread_ts", None) or event["ts"]
            say(f"Replying in thread", thread_ts=thread_ts)

@app.event("file_shared")
def handle_file_shared_events(logger, body, say, event, client, token):
   
    logger.info(body)

    <snipped-code-of-no-relation>
    reply_in_thread( url, say, event)
```

#### The `slack_bolt` version

slack-bolt==1.18.0
slack-sdk==3.23.0

#### Python runtime version

Python 3.10.0

#### OS info

ProductName:		macOS
ProductVersion:		14.0
BuildVersion:		23A344
Darwin Kernel Version 23.0.0: Fri Sep 15 14:42:42 PDT 2023; root:xnu-10002.1.13~1/RELEASE_X86_64```

### Expected result:

I expect the string "Replying in thread"

### Actual result:

I get a KeyError: 'ts'.

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by WhyIsItSoHardToPickAUsername** [comment]
So I think the issue is that there is no 'ts' key in 'event' dictionary because it's a file_shared event. 

The keys I see are:

```
event is of type <class 'dict'>
type file_shared
file_id xxxx
user_id xxx
file {'id': 'xx'}
channel_id xx
event_ts 1697673793.001400
```

I am not sure how to get the 'ts' of the message though. The workflow is that a Slack user will tag my app, such as @MyAPP, and then my app will respond in a thread with "Hello user", and in that thread the user will upload a file, which I will process and return the results in that thread, so I need that thread id.

**Comment by WhyIsItSoHardToPickAUsername** [comment]
In order to solve this issue, when I get an app_mention event, I save that event in a global variable.
Then in my file_share event, I refer to that global variable to get the thread information and post a message in that thread.
There must be a better way though.

**Comment by seratch** [comment]
Hi @WhyIsItSoHardToPickAUsername, thanks for asking the question. 

As the event document (https://api.slack.com/events/file_shared) mentions, in this scenario, your app needs to perform a `files.info` API call to obtain additional properties including the message ts. I understand you want more properties in the event payload, but we don't have plans to enhance it in the short term. I hope this helps.

**Comment by WhyIsItSoHardToPickAUsername** [comment]
What's this then? https://github.com/slackapi/java-slack-sdk/issues/511#issuecomment-663314063

**Comment by seratch** [comment]
@WhyIsItSoHardToPickAUsername It is a different one, which one of the subtyped message events: https://api.slack.com/events/message/file_share

**Comment by WhyIsItSoHardToPickAUsername** [comment]
The thread_ts is nested deep, I am not sure how to access it.

```
 "shares": {
            "public": {
                "C0T8SE4AU": [
                    {
                        "reply_users": [
                            "U061F7AUR"
                        ],
                        "reply_users_count": 1,
                        "reply_count": 1,
                        "ts": "1531763348.000001",
                        "thread_ts": "1531763273.000015",
                        "latest_reply": "1531763348.000001",
                        "channel_name": "file-under",
                        "team_id": "T061EG9R6"
                    }
                ]
            }
        },
  ```

Do you have any example code in Python to access thread_ts?

I am trying this and it's failing:

```
    file_info = client.files_info(file=file_id)

    if file_info['file']['is_public'] == "true":
        channel_id = file_info['file']['channels']
        thread_ts = file_info['file']['shares']['public'][channel_id]['thread_ts']
    else:
        channel_id = file_info['file']['channels']
        thread_ts = file_info['file']['shares']['private'][channel_id]['thread_ts']
```

**Comment by seratch** [comment]
You already have the channel ID in the event payload. All you need to do is to scan the channel ID keys under either shares.public or shares.private.

**Comment by WhyIsItSoHardToPickAUsername** [comment]
Thank you, this works perfectly!
