### ISSUE TITLE
Slack unable to reach WebSocket setup in AWS API gateway

### ISSUE THREAD

**Issue by Saithorat** [slackapi/bolt-python#976]
**Goal:**
Use slack WebSocket to trigger the app code deployed in AWS lambda.

**Setup:**
Created API gateway WebSocket, Defined $connect, $disconnect, $default routes and associated it with Lambda.
Enabled lambda proxy.
Added slack_bolt as layer in lambda, gave required permissions for the APIGateway to trigger lambda and lambda has permissions to write to logs.

**Testing:**
When I trigger the WebSocket externally using piesocket, I can successfully reach the WebSocket and print messages in lambda.

**Issue:**
But when i type in massage from Slack App, nothing happens, no logs in API gateway websocket nor lambda.
How to go about this setup?

**Comment by zimeg** [comment]
Hi @Saithorat! 👋 Using `slack_bolt` as a Lambda layer is really interesting and I'm happy to help troubleshoot, but might need more information about your current setup.

If your Slack app is using Socket Mode, then I'm unsure that it's started which might be why no messages are received in API Gateway. For your app to receive events or messages with Socket Mode, it must already be started to listen for messages.

Can you share a bit more about how your app is setup? And if possible, any logs produced when connecting with piesocket would be helpful too!

**Comment by filmaj** [comment]
@zimeg has it exactly right. Socket Mode presupposes that the application establishes a long-lived connection with Slack. If you flip your Slack app to Socket Mode and trigger an event, Slack will send that event over any established socket connections the app has with Slack. If none such connections exist, no event will be delivered.

It sounds to me like HTTP event delivery might be a better option for you. API Gateway + Lambda is purpose-built for HTTP event delivery. Using HTTP has the side benefit of using short-lived network connections, which is a better integration fit with Lambda, built for short-lived computing.

**Comment by Saithorat** [comment]
@zimeg @filmaj 
Here is my app setup:

Created app in slack with socket mode enabled.
Created AWS lambda python code added bolt dependency as a layer
Created AWS API Gateway with SocketMode enable and routes defined ( This is just like any other socket mode development, aws api gateway socketmode will handle the socket connection being open and triggering lambda)


As mentioned earlier, I can externally ping the web socket using piesocket and that does trigger lambda (This did start the app, I can see the Bolt app running message in cloud watch logs).

There are bunch of videos where in the content creator used similar setup, but with non-slack application triggering websocket in api gateway.

@zimeg using HTTP is not an option because the endpoint is unsecure

**Comment by seratch** [comment]
@Saithorat API Gateway's WebSocket API is a solution for building a WebSocket server. However, using SocketMode means that your Slack app will need to function as a WebSocket client, establishing a connection with Slack's WebSocket server. For this reason, API Gateway is not a solution for Socket Mode app development. 

As an alternative, you can consider container services like ECS, EKS or the HTTP endpoint mode using AWS Lambda. You've mentioned concerns over the security of the Request URL approach; however, with the Request URL mode, you will share signing secret for request verification only with Slack. Your app can ensure an incoming request is sent from Slack without any modification for sure. If a malicious 3rd party tries to immitate such a request, Bolt denies to process it as invalid signature request. Hence, from the security viewpoint, it is not insecure. 

If your company policies do not allow having any publicly accessible endpoints, Socket Mode would be your optimal solution. 

Does this make sense?

**Comment by filmaj** [comment]
I can't speak to other services. However, you hitting your API Gateway URL with piesocket is different than how it works on Slack. Slack socket mode requires you to hit the [apps.connections.open](https://api.slack.com/methods/apps.connections.open) API, which will respond with a web socket url that your app must initiate a connection with. At that point, once this long lived connection is established, events will stream over the connection.

Let me repeat: your app must initiate a connection with Slack first for socket mode to work. Furthermore, this connection is long lived and could last minutes, hours, days, weeks, etc. Unlike HTTP delivery of Slack events where you register a delivery URL, no such URL is registered for socket mode. This is why your app must initiate the connection with Slack _first_.

Holding a long lived socket connection with API Gateway is also not a good idea, as lambdas have a maximum running time of 15 mins. I believe API Gateway also has a connection integration time limit.

**Comment by Saithorat** [comment]
@seratch @filmaj Thanks for your inputs, I went ahead with creating a docket image and deployed it using ECS.
Have socket mode enabled and its working fine.

You can close this question.
