### ISSUE TITLE
Hide events that are of no interest 

### ISSUE THREAD

**Issue by WhyIsItSoHardToPickAUsername** [slackapi/bolt-python#977]
(Describe your issue and goal here)

I only care about a few events, and want to know about just the ones I care about, and not others. 
So when I don't handle events that are of no interest to me in my code, I see messages of such type:
```
2023-10-22 07:15:56 Unhandled request ({'type': 'event_callback', 'event': {'type': 'message', 'subtype': 'message_deleted'}})
---
[Suggestion] You can handle this type of event with the following listener function:

@app.event("message")
def handle_message_events(body, logger):
    logger.info(body)

2023-10-22 07:15:56 Unsuccessful Bolt execution result (status: 404, body: {"error": "unhandled request"})
```

Is there a way to hide these errors since I am not interested in them? 

I only care about a few events, and want to know about just the ones I care about, and not others. 
#### The `slack_bolt` version

slack-bolt==1.18.0
slack-sdk==3.23.0
slackeventsapi==3.0.1

#### Python runtime version

Python 3.6.8

#### OS info

RedHat Kernel 4.18.0-372.64.1.el8_6.x86_64

**Comment by eddyg** [comment]
While managing your application, find the "Event Subscriptions" configuration page and select just the [event types](https://api.slack.com/events/api) you want to subscribe to.

**Comment by seratch** [comment]
@WhyIsItSoHardToPickAUsername Perhaps, youre code is currrently handling only some of the subtyped message event patterns. There is no way to disable specific message subtype events on the Slack app configuration page. You can have a listener that does not do anything for the rest this way:

```python
@app.message("hey")
def your_message_handler():
    # do something meaningful here

# you can have other message event listeners here ...

# Note that this listener must be loaded after other specific message event listeners
@app.event("message")
def just_acknowledge_the_rest():
    # just for acknowledging the rest
    pass
```

See also:
* https://github.com/slackapi/bolt-python/issues/433#issuecomment-896007638
* https://github.com/slackapi/bolt-python/issues/906#issuecomment-1577809594

**Comment by WhyIsItSoHardToPickAUsername** [comment]
Thank you @seratch , that's exactly what I was looking for!
