### ISSUE TITLE
Trying to figure out how to ack something in a middleware listener

### ISSUE THREAD

**Issue by ChadDa3mon** [slackapi/bolt-python#979]
Greetings, and thanks so much for the bolt app, it's really made this process quite easy. I'm enjoying the wide world of possibilities open to me and my team. 

I'm working on a sort of gatekeeper using a [middleware listener](https://slack.dev/bolt-python/concepts#listener-middleware). I want to have a simple way to make sure the channel a request comes from isn't a shared channel. I've got all of the code working (right now I'm just looking at the channel name to test this) but when I want to reject a shortcut (request comes in from a shared channel (or right now a channel I haven't allowed) I don't know how to gracefully terminate things. It always ends up sending the user "Sorry, that didnt work. Try again?" 

#### The `slack_bolt` version
```
slack-bolt==1.18.0
slack-sdk==3.23.0
```

#### Python runtime version
```
Python 3.9.7
```

#### OS info
```
ProductName:		macOS
ProductVersion:		14.0
BuildVersion:		23A344
Darwin Kernel Version 23.0.0: Fri Sep 15 14:42:42 PDT 2023; root:xnu-10002.1.13~1/RELEASE_X86_64
```

#### Steps to reproduce:

Running via `python main.py`
```python
# Initializes your app with your bot token and socket mode handler
app_token = settings.slack.app_token.get_secret_value()
bot_token = settings.slack.bot_token.get_secret_value()

app = AsyncApp(token=bot_token)

web_app = app.web_app()
web_app.add_routes([web.get("/health", healthcheck)])

async def check_shared(client, context, payload, next, ack, respond):
    # Goal here is to make sure the message isn't coming from a shared channel
    await ack()
    channel_id = context.get('channel_id', None)
    user_id = context.get('user_id', None)
    channel = await client.conversations_info(channel=channel_id)
    channel_name = channel['channel'].get('name_normalized', 'No Normalized name')
    if channel_name == "authorized-channel":
        await next()
    else: # Request came from an unauthorized channel
        await respond("This channel is not authorized, please try #authorized-channel")
        return 

app.shortcut("create-ticket", middleware=[check_shared])(create_ticket)
app.action("team-selection")(team_selection_modal)  # Action when they select the "Team" from the dropdown

# Start your app
if __name__ == "__main__":
    async def start_socket_mode(_web_app: web.Application):
        handler = AsyncSocketModeHandler(app, app_token)
        settings.slack.socket_mode_client = handler.client
        await handler.connect_async()


    async def shutdown_socket_mode(_web_app: web.Application):
        await settings.slack.socket_mode_client.close()

    web_app.on_startup.append(start_socket_mode)
    web_app.on_shutdown.append(shutdown_socket_mode)
    web.run_app(app=web_app, port=8002)
```

### Expected result:

If a user attempts to execute a shortcut from a channel I don't want (eventually because it's a shared channel) it should send an ephemeral message letting them know it's not allowed, and then move on. 

### Actual result:

User gets the ephemeral message, but then also gets the `Sorry, that didn't work. Try again?`

It seems no matter how I try, the `ack()` just isn't being received. 

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by hello-ashleyintech** [comment]
Hi, @ChadDa3mon! Thank you for your question. 🙇 

If I'm understanding your question correctly, you are essentially looking to `ack()` your shortcut request within the required timeframe and then execute some logic that checks if from an unauthorized channel.

You can actually bypass the middleware and create an `ack()` function that will be called not necessarily within your middleware, but as part of your command execution using a combination of `ack` and [`lazy` listener](https://slack.dev/bolt-python/concepts#lazy-listeners) function parameters that you pass in to your shortcut.

An example would look roughly something like this:
```py
def ack_command(body, ack, logger):
    logger.info(body)
    ack("Thanks!")

def check_shared(client, context, payload, ack, respond):
    # Goal here is to make sure the message isn't coming from a shared channel
    await ack()
    channel_id = context.get('channel_id', None)
    user_id = context.get('user_id', None)
    channel = await client.conversations_info(channel=channel_id)
    channel_name = channel['channel'].get('name_normalized', 'No Normalized name')
    if channel_name == "authorized-channel":
        # respond with a positive response to continue to create_ticket() function that is initialized elsewhere
    else: # Request came from an unauthorized channel
       # end request

app.shortcut("create-ticket")(
    ack=ack_command,
    lazy=[check_shared, create_ticket],
)
```
This example was pulled from [this code](https://github.com/slackapi/bolt-python/blob/main/examples/lazy_modals_app.py). I hope this helps! Let me know if you have further questions.

**Comment by ChadDa3mon** [comment]
Thanks for such a fast response. I’ll try this out hen I get back from trick or treating :)

**Comment by ChadDa3mon** [comment]
Ok, I tried this and it feels like a step backwards. Now the modal is shown even if the request comes from an unauthorized channel. Here's the updated code with your suggestion, maybe I missed something. 

```python
app = AsyncApp(token=bot_token)

web_app = app.web_app()
web_app.add_routes([web.get("/health", healthcheck)])

async def ack_command(body, ack, logger):
    logger.info(body)
    await ack("Thanks!")

async def check_shared(client, context, payload, next, ack, respond):
    # Goal here is to make sure the message isn't coming from a shared channel

    # Make sure the event shortcut comes from an authorized channel, otherwise ignore it
    channel_id = context.get('channel_id', None)
    user_id = context.get('user_id', None)
    channel = await client.conversations_info(channel=channel_id)
    channel_name = channel['channel'].get('name_normalized', 'No Normalized name')
    if channel_name == "authorized-channel":
        print(f" - Request came from authorized channel")
        await next()
    else:
        print(f" - Request came from an UNAUTHORIZED channel")
        await respond("This channel is not authorized, please try #authorized-channel")


# app.shortcut("create-mss-ticket", middleware=[check_shared])(create_internal_ticket)
app.shortcut("create-ticket")(
    ack=ack_command,
    lazy=[check_shared,create_internal_ticket]
)
```

So basically if the shortcut is executed in a specific channel, then present the modal (or whatever else), but if the shortcut is executed from another channel, send an ephemeral message to the user with some helpful information, then just "skip" the request. 

I can get the "skip the request" to work fine, but the `ack()` just never works, so the user gets an error.

**Comment by seratch** [comment]
@ChadDa3mon `await ack("Thanks!")` works only for slash commands. So, the ack() method call must be `await ack()` instead. 

When it comes to the ways to post messages in response, there are several patterns:
* If the shortcut can be a global shortcut, context.channel_id does not always exist because global ones can be invoked from the search bar etc. In the case, you can use chat.postMessage with the user's ID to send a DM
* If it is guaranteed that the shortcut is a message shortuct, you can use `respond()` instead. Also, `say()` and its underlying `chat.postMessage` API all works too.

As for the lazy listener issue, those lazy listeners can be executed in pararell. So, the current behaivor is expected. If you want to go with lazy listeners for this, you can merge the two listeners into a single one (meaning having if/else in the unified function instead). Lazy listeners are not middleware, so you don't need to call `next()` method. Actually it does nothing.

Alternatively, if you want to simply use listener middleware, the following approach can work too. Listener matchers can be simpler in this case, but either is fine.

```python
# the middleware calls next() only for internal channels
app.shortcut("create-ticket", middleware=[skip_shared_channels])(create_ticket)
# define another shortcut listener registration right after the above one
# this one handles the rest unmatched ones (only slack connect channel ones in this case)
app.shortcut("create-ticket")(just_ack_without_doing_anything)
```

I hope this helps.

**Comment by ChadDa3mon** [comment]
Thank you, I feel like the answer is in there somewhere, especially your last example. Maybe I'm just a python noob still, but I don't quite follow how this works: 

```
# the middleware calls next() only for internal channels
app.shortcut("create-ticket", middleware=[skip_shared_channels])(create_ticket)
# define another shortcut listener registration right after the above one
# this one handles the rest unmatched ones (only slack connect channel ones in this case)
app.shortcut("create-ticket")(just_ack_without_doing_anything)
```

How does the second line (just_ack_without_doing_anything) ever get called? 

P.S - Thanks for the fast responses!

**Comment by ChadDa3mon** [comment]
Well that did the trick. Still don't understand how or why, but thank you so much for all of your help.
