### ISSUE TITLE
What is the difference between ts and event_ts VERSUS ts and thread_ts?

### ISSUE THREAD

**Issue by WhyIsItSoHardToPickAUsername** [slackapi/bolt-python#981]
(Describe your issue and goal here)

What is the difference between ts and event_ts VERSUS ts and thread_ts?

For instance when a thread is replied to, an event of the following type is generated:

```python
{
    "type": "reaction_added",
    "user": "xxx",
    "reaction": "happy-face",
    "item": {"type": "message", "channel": "xxx", "ts": "1698820283.053449"},
    "item_user": "U03CVKELZU6",
    "event_ts": "1698820290.008000",
}
```

Even though this event was generated when a reaction was added to a file uploaded in a thread, there is no thread_ts value?

### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version

(Paste the output of `pip freeze | grep slack`)

#### Python runtime version

(Paste the output of `python --version`)

#### OS info

(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1.
2.
3.

### Expected result:

(Tell what you expected to happen)

### Actual result:

(Tell what actually happened with logs, screenshots)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @WhyIsItSoHardToPickAUsername, thanks for asking the question. 

The event_ts represents the timestamp that Slack's system delievered the event. Thus, the value can be slightly different 
from the mesage's ts and thread_ts. In a nutshell, you won't use the event_ts in most cases. Please always use a message's ts/thread_ts.
