### ISSUE TITLE
Handling app events for multiple workspaces with one websocket/http server

### ISSUE THREAD

**Issue by shovalyechiel1** [slackapi/bolt-python#982]
Hey!
Im developing a slack app which i would like to make public. i installed it on my workspace, and started listening for events with the Webocket interface which is fine. But when the application will go public i would like to open few Websockets for load balancing that will serve all the apps ( more workspaces then websockets ) but Im not sure how to do it with the SDK, since every app instance take one app-token and every websocket take one app.

**Comment by hello-ashleyintech** [comment]
Hi, @shovalyechiel1!

This [example](https://github.com/slackapi/bolt-python/blob/main/examples/socket_mode_oauth.py) demonstrates how to use socket mode along with OAuth to support downloads to multiple workspaces. Is this along the lines of what you were looking for?

**Comment by shovalyechiel1** [comment]
Hey @hello-ashleyintech and thanks for the quick response!
I have seen this example yes. but maybe im missing something. lets say that my app is installed on 2 workspaces so i have two slack_app_token which is per application right ? i'm just not so sure how can one instance digest events for multiple workspaces

**Comment by seratch** [comment]
>Im developing a slack app which i would like to make public

Please note that, if you're going to submit your app to App Directory listing, currently the listing side does not support apps serving via Socket Mode:

>Apps using Socket Mode are not currently allowed in the public [Slack App Directory](https://slack.com/apps).
>https://api.slack.com/apis/connections/socket

If that's the case, you need to switch to Request URL mode before submitting to App Directory.

If you're plannig to distribute your app just for your specific customers and/or your organization's workspaces (these workspaces can install your app if they know the URL to start the installation), and you don't need to make the app searchable for everyone on the App Directory side, there is no obstacle to go with Socket Mode.

**Comment by shovalyechiel1** [comment]
Ok got it! 
thank you for your help.
