### ISSUE TITLE
As you gave `client` as well, `token` will be unused.

### ISSUE THREAD

**Issue by WhyIsItSoHardToPickAUsername** [slackapi/bolt-python#983]
(Describe your issue and goal here)

I am getting this message when I start my Slack App on my laptop:

```
2023-11-02 16:05:38 As you gave `client` as well, `token` will be unused.
2023-11-02 16:05:38 Starting HELLOWORLD SLACK App....
2023-11-02 16:05:39 A new session has been established (session id: xxx)
2023-11-02 16:05:39 ⚡️ Bolt app is running!
2023-11-02 16:05:39 Starting to receive messages from a new connection (session id: xxxb)

```

I have SLACK_APP_TOKEN and SLACK_BOT_TOKEN, since I am using socket based Slack events.
Do I need to remove one of these for this message to go away?

### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version

(Paste the output of `pip freeze | grep slack`)

#### Python runtime version

(Paste the output of `python --version`)

#### OS info

(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1.
2.
3.

### Expected result:

(Tell what you expected to happen)

### Actual result:

(Tell what actually happened with logs, screenshots)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by hello-ashleyintech** [comment]
Hi, @WhyIsItSoHardToPickAUsername! Thanks for your question. 🙇 

Would you be able to share your `app.py` where the app is being initialized? This would help me get a better idea of what you're passing in!

**Comment by WhyIsItSoHardToPickAUsername** [comment]
```python

app = App(client=WebClient(token=os.environ["SLACK_BOT_TOKEN"], proxy=proxy_url))

  SocketModeHandler(
            app=app,
            app_token=os.environ["SLACK_APP_TOKEN"],
        ).start()
```

**Comment by hello-ashleyintech** [comment]
@WhyIsItSoHardToPickAUsername thanks for submitting that snippet! Have you tried passing in your bot token outside the web client to see if you still get the error? ex:

```python
app = App(token=os.environ["SLACK_BOT_TOKEN"],client=WebClient(proxy=proxy_url))
```
