### ISSUE TITLE
preformatted block limits

### ISSUE THREAD

**Issue by WhyIsItSoHardToPickAUsername** [slackapi/bolt-python#984]
(Describe your issue and goal here)

I have a list and for each item of the list I want to print a preformatted block, I am doing that this way:

```
            for error in mylist:
                error_msg += f"```\n{error}```\n\n"

            say(f"{error_msg}", thread_ts=thread_ts)
``` 

This is printing 7 rows in preformatted blocks, and then for some odd reason it prints \```, and the rest of the list comes out as a separate message. , without the preformatted block.

What I would like to see is:

```
list row one
```

```
list row two
```

``` 
list row three
```

instead what I see is:

```
list row one
```

```
list row two
```
(this repeated until row 7 and then I see the below)

Each row contains around 5 lines of text. 

list row eight
list row nine

**Comment by WilliamBergamin** [comment]
Hi @WhyIsItSoHardToPickAUsername thanks for writing in 💯 

This seems like an odd issue, would you be able to share the value of `error_msg` before it is passed to the `say` function?

**Comment by seratch** [comment]
Hi @WhyIsItSoHardToPickAUsername,
>Each row contains around 5 lines of text.

I guess your API call should have thousands of text characters for a single message. In this case, the Slack server-side can automatically split the text into a few for more human-readability and optimal user experience. As mentioned here: https://github.com/slackapi/java-slack-sdk/issues/704 , the platform does not have plans to change this behavior at least in the short term. The only approach I can suggest is to split the long text message into a few in its thread and/or to have a text file attached instead. I understand this could be a frustrating restriction but I hope you will find a reasonable workaround for it.
