### ISSUE TITLE
Are you planning to make a new release soon?

### ISSUE THREAD

**Issue by freud14-tm** [slackapi/bolt-python#989]
I'm particularly interested in setting the metadata using the Reponse object.

**Comment by filmaj** [comment]
Hi!

Yes, we plan to release a patch release soon. There is one outstanding issue left to be tackled; if you are curious, you can look at the [1.18.1 Milestone](https://github.com/slackapi/bolt-python/milestone/79) for details and progress.

I will close this issue as I believe your question has been answered, but if you have other follow-ups, feel free to re-open or create a new issue.

**Comment by freud14-tm** [comment]
Thank you very much. First time I've seen GitHub milestones actually used!

**Comment by filmaj** [comment]
FYI @freud14-tm [v1.18.1 is now released](https://github.com/slackapi/bolt-python/releases/tag/v1.18.1).
