### ISSUE TITLE
Django with Bolt for Python - Socket Mode

### ISSUE THREAD

**Issue by duell-git** [slackapi/bolt-python#993]
Hello there!

This is not an issue, rather than a request. 
I couldn't find info about it online.

I want to migrate my previously written Slack Python app in Django.
I have found the Django examples in the repo, but it is using Event URL's, which is not an option for me.
I have to use Socket Mode since we cannot publicize any of our internal URL's for this app.

Is it even possible to use Bolt in Django with the use of Socket mode? 

If so, how could that be done?

Thank you very much in advance! 

#### The `slack_bolt` version

slack-bolt==1.18.0
slack-sdk==3.24.0

#### Python runtime version

Python 3.12.0

#### OS info

#1 SMP Debian 5.10.197-1 (2023-09-29)

**Comment by seratch** [comment]
Hi @duell-git, thanks for asking the question!

When you go with Socket Mode, you no longer need Django for serving web endpoints. So, you can simply remove the Django dependency. The `App` instance and your event listeners such as `@app.event(...)`  are framework agnostic. So, just switching from the Django adapter (`slack_bolt.adapter.django`) to the Socket Mode adapter (`slack_bolt.adapter.socket_mode`) should work for you. Check the Socket Mode examples under examples/ directory in this repo.

If you manage tokens etc. using Django ORM, you can use the ORM library without the Django web app project structure: https://stackoverflow.com/questions/45595750/use-django-orm-outside-of-django

I hope this helps.

**Comment by duell-git** [comment]
Hey @seratch!

Thank you for the swift answer.
I already know about the Socket Mode bolt adapter, have been using it in a "normal" Python script. 
I was just confused about how could Django handle the event listeners and the socket mode connection, but to my luck in issue #949 the last comment helped me tremendously. 
I think I will close this ticket.
