### ISSUE TITLE
Using threading.Lock in an asyncio app

### ISSUE THREAD

**Issue by pbrooks** [slackapi/bolt-python#994]
Hi,

I've been trying to boil down a problem I'm observing with my approach.
The goal is to have two separate threads:
1 - The Bolt SDK socket clinet
2 - A resource updater [Real world, this is a Health check class to iterate over the health checks and update]

In this example, I've created an arbitrary resource **shared_value**.
To ensure that the data isn't accessed by both threads at once, I've used an execution wrapping lock (mutex).
Whilst the update logic is executing, the call to **get()** should wait until the update has finished.

However, in this example. As soon as get() attempts to access the mutex, then the update logic immediately stops. Which I can assume is a deadlock.

I appreciate, that my assumptions for valid concurrency here may be invalid.
The example should be simple enough to replicate with any slack app.

Any help or tips would be greatly appreciated.

### Reproducible in:

```python
import asyncio
import os
from threading import Lock

from slack_bolt.async_app import AsyncApp
from slack_bolt.adapter.socket_mode import SocketModeHandler
from slack_bolt.adapter.socket_mode.aiohttp import AsyncSocketModeHandler

import logging
# logging.basicConfig(level=logging.DEBUG)

app = AsyncApp(token=os.environ.get("SLACK_BOT_TOKEN"))
socket_handler = AsyncSocketModeHandler(app, os.environ["SLACK_APP_TOKEN"])

mutex = Lock()

shared_value = None


async def assign(i):
    with mutex:
        shared_value = i
        print("shared_value", i)
        await asyncio.sleep(0.1)


async def update():
    while True:
        print("-- update --")
        for i in range(0, 200):
            await assign(i)
        await asyncio.sleep(2)


async def get():
    with mutex:
        print("get ", shared_value)
        return shared_value


@app.command("/echo")
async def echo_command(ack, body):
    value = await get()
    user_id = body["user_id"]
    await ack(f"Hi <@{user_id}> value {value}!")


async def main():
    asyncio.ensure_future(update())
    await AsyncSocketModeHandler(
            app, os.environ["SLACK_APP_TOKEN"]).start_async()


if __name__ == "__main__":
    asyncio.run(main2())

```

#### The `slack_bolt` version

(Paste the output of `pip freeze | grep slack`)

#### Python runtime version

(Paste the output of `python --version`)

#### OS info

(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1.
2.
3.

### Expected result:

(Tell what you expected to happen)

### Actual result:

When the slack app command is received, a deadlock will occur at the mutex call.

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @pbrooks, thanks for asking the question. 

This is a common pitfall for developers who are not yet familiar with the characteristics of asyncio in Python. As you might be aware, asyncio functions under an entirely different programming paradigm, which requires understanding of non-blocking event loops. It seems that the cause of your issue should be the usage of `threading.Lock` objects. Instead, you must use asyncio.Lock for the same purpose: https://docs.python.org/3/library/asyncio-sync.html#asyncio.Lock

FYI; here is a similar question I've answered in the past: https://github.com/slackapi/bolt-python/issues/791#issuecomment-1355825843

**Comment by pbrooks** [comment]
Thank you for your extremely prompt and insightful response @seratch :) 
I knew it would be an assumption I'd made about the async paradigm somewhere.

So it's pretty nice to wake up to a solution. 👍
